voogasalad_TheException: editor.ElementAccordianSubPaneController Class Reference
editor.ElementAccordianSubPaneController Class Reference
Classes
class GameElementListCell
Public Member Functions
ElementAccordianSubPaneController (String gameElement)
void addElement (String element, Node image)
Private Member Functions
void initListView ()
void initAddElementButton ()
void addElement ()
Private Attributes
String myGameElement
Button myAddElementButton
ListView< String > myListView
ObservableList< String > myElementsList
HashMap< String, Node > myElementsMap
Static Private Attributes
static final String CREATE_NEW_STRING = "Create new "
Detailed Description
Author
Jonathan Tseng
Nishad Agrawal
Definition at line 26 of file ElementAccordianSubPaneController.java.
Constructor & Destructor Documentation
editor.ElementAccordianSubPaneController.ElementAccordianSubPaneController (String gameElement)
Definition at line 35 of file ElementAccordianSubPaneController.java.
References editor.ElementAccordianSubPaneController.initAddElementButton(), and editor.ElementAccordianSubPaneController.initListView().
Member Function Documentation
void editor.ElementAccordianSubPaneController.addElement (String element, Node image)
Definition at line 83 of file ElementAccordianSubPaneController.java.
void editor.ElementAccordianSubPaneController.addElement () private
Definition at line 94 of file ElementAccordianSubPaneController.java.
Referenced by editor.ElementAccordianSubPaneController.initAddElementButton().
void editor.ElementAccordianSubPaneController.initAddElementButton () private
Definition at line 88 of file ElementAccordianSubPaneController.java.
References editor.ElementAccordianSubPaneController.addElement().
Referenced by editor.ElementAccordianSubPaneController.ElementAccordianSubPaneController().
void editor.ElementAccordianSubPaneController.initListView () private
Definition at line 50 of file ElementAccordianSubPaneController.java.
Referenced by editor.ElementAccordianSubPaneController.ElementAccordianSubPaneController().
Member Data Documentation
final String editor.ElementAccordianSubPaneController.CREATE_NEW_STRING = "Create new " static private
Definition at line 28 of file ElementAccordianSubPaneController.java.
Button editor.ElementAccordianSubPaneController.myAddElementButton private
Definition at line 30 of file ElementAccordianSubPaneController.java.
ObservableList<String> editor.ElementAccordianSubPaneController.myElementsList private
Definition at line 32 of file ElementAccordianSubPaneController.java.
HashMap<String, Node> editor.ElementAccordianSubPaneController.myElementsMap private
Definition at line 33 of file ElementAccordianSubPaneController.java.
String editor.ElementAccordianSubPaneController.myGameElement private
Definition at line 29 of file ElementAccordianSubPaneController.java.
ListView<String> editor.ElementAccordianSubPaneController.myListView private
Definition at line 31 of file ElementAccordianSubPaneController.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/ElementAccordianSubPaneController.java