voogasalad_TheException: editor.ElementDropDownControl Class Reference
editor.ElementDropDownControl Class Reference
Classes
class GameElementListCell
Public Member Functions
void addElement (String element, Node image)
void setGameElement (String gameElement)
Node getRoot ()
void initialize ()
Private Member Functions
void initListView ()
void initNewElementButton ()
void addElement ()
Private Attributes
Button newElementButton
ListView< String > elementListView
TitledPane elementDropDown
ObservableList< String > myElementsList
HashMap< String, Node > myElementsMap
String myGameElement
SimpleStringProperty myButtonText
Static Private Attributes
static final String CREATE_NEW_STRING = "Create new "
Detailed Description
Author
Nishad Agrawal
Jonathan Tseng
Definition at line 24 of file ElementDropDownControl.java.
Member Function Documentation
void editor.ElementDropDownControl.addElement (String element, Node image)
Definition at line 41 of file ElementDropDownControl.java.
Referenced by editor.ElementAccordianController.initialize().
void editor.ElementDropDownControl.addElement () private
Definition at line 77 of file ElementDropDownControl.java.
Referenced by editor.ElementDropDownControl.initNewElementButton().
Node editor.ElementDropDownControl.getRoot ()
Implements view.GUIController.
Definition at line 93 of file ElementDropDownControl.java.
References editor.ElementDropDownControl.elementDropDown.
Referenced by editor.ElementAccordianController.initialize().
void editor.ElementDropDownControl.initialize ()
Implements view.GUIController.
Definition at line 98 of file ElementDropDownControl.java.
References editor.ElementDropDownControl.initListView(), and editor.ElementDropDownControl.initNewElementButton().
void editor.ElementDropDownControl.initListView () private
Definition at line 52 of file ElementDropDownControl.java.
Referenced by editor.ElementDropDownControl.initialize().
void editor.ElementDropDownControl.initNewElementButton () private
Definition at line 72 of file ElementDropDownControl.java.
References editor.ElementDropDownControl.addElement().
Referenced by editor.ElementDropDownControl.initialize().
void editor.ElementDropDownControl.setGameElement (String gameElement)
Definition at line 46 of file ElementDropDownControl.java.
Referenced by editor.ElementAccordianController.initialize().
Member Data Documentation
final String editor.ElementDropDownControl.CREATE_NEW_STRING = "Create new " static private
Definition at line 26 of file ElementDropDownControl.java.
TitledPane editor.ElementDropDownControl.elementDropDown private
Definition at line 33 of file ElementDropDownControl.java.
Referenced by editor.ElementDropDownControl.getRoot().
ListView<String> editor.ElementDropDownControl.elementListView private
Definition at line 31 of file ElementDropDownControl.java.
SimpleStringProperty editor.ElementDropDownControl.myButtonText private
Definition at line 39 of file ElementDropDownControl.java.
ObservableList<String> editor.ElementDropDownControl.myElementsList private
Definition at line 35 of file ElementDropDownControl.java.
HashMap<String, Node> editor.ElementDropDownControl.myElementsMap private
Definition at line 36 of file ElementDropDownControl.java.
String editor.ElementDropDownControl.myGameElement private
Definition at line 37 of file ElementDropDownControl.java.
Button editor.ElementDropDownControl.newElementButton private
Definition at line 29 of file ElementDropDownControl.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/ElementDropDownControl.java