voogasalad_TheException: engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T > Class Template Reference
engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T > Class Template Reference abstract
Public Member Functions
AttributeParameter (Class< T > type, String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier)
AttributeParameter (Class< T > type, String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier, String elementTag)
T evaluate (ElementPair elements)
boolean setValue (ElementPair elements, T attributeValue)
Public Member Functions inherited from engine.gameRepresentation.evaluatables.parameters.Parameter< T >
Parameter (Class< T > type)
abstract T evaluate (ElementPair elements)
abstract boolean setValue (ElementPair elements, T value)
Public Member Functions inherited from engine.gameRepresentation.evaluatables.Evaluatable< T >
Evaluatable (Class< T > type)
abstract T evaluate (ElementPair elements)
boolean setValue (ElementPair elements, T value)
boolean setValue (T value)
Class< T > getType ()
Protected Member Functions
String getTag ()
abstract T getValue (List< GameElement > elements, String attributeTag)
abstract boolean setValue (List< GameElement > elements, String attributeTag, T attributeValue)
Private Member Functions
List< GameElement > getElementsOfInterest (GameElementManager elementManager, ElementPair elementPair, String elementTag)
Private Attributes
String myAttributeTag
String myElementTag
ObjectOfInterestIdentifier myObjectIdentifier
GameElementManager myManager
Detailed Description
An evaluator parameter that extracts a numerical or textual attribute contained within an object
Author
Zach
Definition at line 17 of file AttributeParameter.java.
Constructor & Destructor Documentation
engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.AttributeParameter (Class< T > type, String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier)
Make an attribute parameter targeting parameters with a given tag.
Parameters
attributeTag the tag of the attribute that will be targeted
manager the GameElementManager containing all the game elements
objectOfInterestIdentifier an identifier that will return an object of interest
Definition at line 34 of file AttributeParameter.java.
engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.AttributeParameter (Class< T > type, String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier, String elementTag)
Specify an attribute parameter with an element tag. Used for referencing global variables
Parameters
attributeTag
manager
objectOfInterestIdentifier
elementTag
Definition at line 52 of file AttributeParameter.java.
Member Function Documentation
T engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.evaluate (ElementPair elements)
Definition at line 87 of file AttributeParameter.java.
List<GameElement> engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.getElementsOfInterest (GameElementManager elementManager, ElementPair elementPair, String elementTag) private
Get the elements of interest from the object of interest identifier contained within the AttributeParameter
Parameters
elementManager the object holding all the current game elements
elementPair a pair of the game elements that the player is currently interested in
elementTag the tag of an element that the player is interested. Optional. Only really used for globals
Returns
Definition at line 81 of file AttributeParameter.java.
Referenced by engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.evaluate(), and engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.setValue().
String engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.getTag () protected
Get the tag for the attribute this references
Returns
the attribute tag
Definition at line 63 of file AttributeParameter.java.
abstract T engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.getValue (List< GameElement > elements, String attributeTag) abstract protected
Get the desired value given the current list of elements of interest.
Parameters
elements the elements whose values need to be examined
attributeTag the tag for the attribute that is being referenced by the parameter
Returns
the value of the parameter that is being requested
Referenced by engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.evaluate().
boolean engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.setValue (ElementPair elements, T attributeValue)
Definition at line 104 of file AttributeParameter.java.
Referenced by engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.setValue().
abstract boolean engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.setValue (List< GameElement > elements, String attributeTag, T attributeValue) abstract protected
Set the referenced value given the current list of elements of interest
Parameters
elements the current list of elements of interest
attributeTag the tag for the attribute to set
attributeValue the new value of the attribute
Member Data Documentation
String engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.myAttributeTag private
Definition at line 19 of file AttributeParameter.java.
Referenced by engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.getTag().
String engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.myElementTag private
Definition at line 20 of file AttributeParameter.java.
GameElementManager engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.myManager private
Definition at line 22 of file AttributeParameter.java.
ObjectOfInterestIdentifier engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.myObjectIdentifier private
Definition at line 21 of file AttributeParameter.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/evaluatables/parameters/AttributeParameter.java