voogasalad_TheException: vooga.request.forwarder.ReceiverNotFoundException Class Reference
vooga.request.forwarder.ReceiverNotFoundException Class Reference
Public Member Functions
ReceiverNotFoundException (String address)
String address ()
ReceiverNotFoundException (String address)
String address ()
Private Attributes
String myAddress
Static Private Attributes
static final long serialVersionUID = 2016239501767275842L
Detailed Description
An exception encapsulating when a receiver address could not be resolved to a receiver
Definition at line 7 of file ReceiverNotFoundException.java.
Constructor & Destructor Documentation
vooga.request.forwarder.ReceiverNotFoundException.ReceiverNotFoundException (String address)
Create a new receiver not found exception
Parameters
address The address that could not be resolved
Definition at line 17 of file ReceiverNotFoundException.java.
References vooga.request.forwarder.ReceiverNotFoundException.address().
vooga.request.forwarder.ReceiverNotFoundException.ReceiverNotFoundException (String address)
Create a new receiver not found exception
Parameters
address The address that could not be resolved
Definition at line 17 of file ReceiverNotFoundException.java.
References vooga.request.forwarder.ReceiverNotFoundException.address().
Member Function Documentation
String vooga.request.forwarder.ReceiverNotFoundException.address ()
Get the address
Returns
The address that could not be resolved
Definition at line 26 of file ReceiverNotFoundException.java.
References vooga.request.forwarder.ReceiverNotFoundException.myAddress.
Referenced by vooga.request.forwarder.ReceiverNotFoundException.ReceiverNotFoundException(), and test.request.RequestMediatorTest.testReceiverNotFoundException().
String vooga.request.forwarder.ReceiverNotFoundException.address ()
Get the address
Returns
The address that could not be resolved
Definition at line 26 of file ReceiverNotFoundException.java.
References vooga.request.forwarder.ReceiverNotFoundException.myAddress.
Member Data Documentation
String vooga.request.forwarder.ReceiverNotFoundException.myAddress private
Definition at line 10 of file ReceiverNotFoundException.java.
Referenced by vooga.request.forwarder.ReceiverNotFoundException.address().
static final long vooga.request.forwarder.ReceiverNotFoundException.serialVersionUID = 2016239501767275842L static private
Definition at line 9 of file ReceiverNotFoundException.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/build/build/src/vooga/request/forwarder/ReceiverNotFoundException.java