voogasalad_TheException: vooga.request.forwarder.RequestMediator Class Reference
vooga.request.forwarder.RequestMediator Class Reference
Public Member Functions
RequestMediator ()
void forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
void register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
RequestMediator ()
void forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
void register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
Private Member Functions
void checkValidAddress (String address) throws InvalidAddressException
void checkKnownAddress (String address) throws ReceiverNotFoundException
boolean isKnownAddress (String address)
void checkValidAddress (String address) throws InvalidAddressException
void checkKnownAddress (String address) throws ReceiverNotFoundException
boolean isKnownAddress (String address)
Private Attributes
Map< String, IReceiver > myAddresses
Detailed Description
The main request manager class which forwards messages between game components
Definition at line 12 of file RequestMediator.java.
Constructor & Destructor Documentation
vooga.request.forwarder.RequestMediator.RequestMediator ()
Definition at line 16 of file RequestMediator.java.
vooga.request.forwarder.RequestMediator.RequestMediator ()
Definition at line 16 of file RequestMediator.java.
Member Function Documentation
void vooga.request.forwarder.RequestMediator.checkKnownAddress (String address) throws ReceiverNotFoundException private
Definition at line 49 of file RequestMediator.java.
References vooga.request.forwarder.RequestMediator.isKnownAddress().
Referenced by vooga.request.forwarder.RequestMediator.forward().
void vooga.request.forwarder.RequestMediator.checkKnownAddress (String address) throws ReceiverNotFoundException private
Definition at line 49 of file RequestMediator.java.
References vooga.request.forwarder.RequestMediator.isKnownAddress().
void vooga.request.forwarder.RequestMediator.checkValidAddress (String address) throws InvalidAddressException private
Definition at line 45 of file RequestMediator.java.
Referenced by vooga.request.forwarder.RequestMediator.forward(), and vooga.request.forwarder.RequestMediator.register().
void vooga.request.forwarder.RequestMediator.checkValidAddress (String address) throws InvalidAddressException private
Definition at line 45 of file RequestMediator.java.
void vooga.request.forwarder.RequestMediator.forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
Forward a request to a recipient based on the details of that request
Parameters
request The request to forward
Exceptions
InvalidAddressException If the sender or receiver addresses are invalid
ReceiverNotFoundException If the receiver is not registered with this forwarder
DeliveryException If a problem occurs during delivery of the message to a receiver
Implements vooga.request.forwarder.IForwarder.
Definition at line 21 of file RequestMediator.java.
References vooga.request.forwarder.RequestMediator.checkKnownAddress(), and vooga.request.forwarder.RequestMediator.checkValidAddress().
void vooga.request.forwarder.RequestMediator.forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
Forward a request to a recipient based on the details of that request
Parameters
request The request to forward
Exceptions
InvalidAddressException If the sender or receiver addresses are invalid
ReceiverNotFoundException If the receiver is not registered with this forwarder
DeliveryException If a problem occurs during delivery of the message to a receiver
Implements vooga.request.forwarder.IForwarder.
Definition at line 21 of file RequestMediator.java.
References vooga.request.forwarder.RequestMediator.checkKnownAddress(), and vooga.request.forwarder.RequestMediator.checkValidAddress().
boolean vooga.request.forwarder.RequestMediator.isKnownAddress (String address) private
Definition at line 55 of file RequestMediator.java.
Referenced by vooga.request.forwarder.RequestMediator.checkKnownAddress(), and vooga.request.forwarder.RequestMediator.register().
boolean vooga.request.forwarder.RequestMediator.isKnownAddress (String address) private
Definition at line 55 of file RequestMediator.java.
void vooga.request.forwarder.RequestMediator.register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
Register a receiver that can receive messages via forward()
Parameters
address The address where the receiver can receive requests
receiver The receiver associated with the address
Exceptions
InvalidAddressException If the format of the address is not allowed by the forwarder
AddressConflictException If the address is already used by another receiver
Implements vooga.request.forwarder.IForwarder.
Definition at line 36 of file RequestMediator.java.
References vooga.request.forwarder.RequestMediator.checkValidAddress(), and vooga.request.forwarder.RequestMediator.isKnownAddress().
void vooga.request.forwarder.RequestMediator.register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
Register a receiver that can receive messages via forward()
Parameters
address The address where the receiver can receive requests
receiver The receiver associated with the address
Exceptions
InvalidAddressException If the format of the address is not allowed by the forwarder
AddressConflictException If the address is already used by another receiver
Implements vooga.request.forwarder.IForwarder.
Definition at line 36 of file RequestMediator.java.
References vooga.request.forwarder.RequestMediator.checkValidAddress(), and vooga.request.forwarder.RequestMediator.isKnownAddress().
Member Data Documentation
Map< String, IReceiver > vooga.request.forwarder.RequestMediator.myAddresses private
Definition at line 14 of file RequestMediator.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/build/build/src/vooga/request/forwarder/RequestMediator.java