voogasalad_TheException: game_engine.visuals.TerrainGrid Class Reference
game_engine.visuals.TerrainGrid Class Reference
Public Member Functions
TerrainGrid (double mapWidth, double mapHeight)
int[][] generateDefaultGrid (double mapWidth, double mapHeight)
List< DrawableGameElementState > renderTerrain (int[][] terrainArray)
List< DrawableGameElementState > renderTerrain ()
Static Public Attributes
static final double TILE_X_DIMENSION = 96
static final double TILE_Y_DIMENSION = 48
Package Attributes
int[][] grid
Detailed Description
Grid for storing and creating the terrain. Will allow for a simpler method of storing the tiled terrain (not mountains or obstacles like that) and later recreating it than just saving all of the tile objects if its deemed necessary
Author
John
Definition at line 17 of file TerrainGrid.java.
Constructor & Destructor Documentation
game_engine.visuals.TerrainGrid.TerrainGrid (double mapWidth, double mapHeight)
Definition at line 24 of file TerrainGrid.java.
References game_engine.visuals.TerrainGrid.generateDefaultGrid().
Member Function Documentation
int [][] game_engine.visuals.TerrainGrid.generateDefaultGrid (double mapWidth, double mapHeight)
Generates a grid with size determined by the tile dimensions and the total map size. Contains a 0 in every element, representing the default terrain type
Parameters
mapWidth the number of pixels for the entire map width
mapHeight the number of pixels for the entire map height
Returns
a two dimensional array with zeros
Definition at line 36 of file TerrainGrid.java.
Referenced by game_engine.visuals.TerrainGrid.TerrainGrid().
List<DrawableGameElementState> game_engine.visuals.TerrainGrid.renderTerrain (int terrainArray[][])
Creates a new DrawableGameElementState with settings for the proper location
Parameters
mapWidth the number of pixels for the entire map width
mapHeight the number of pixels for the entire map height
Returns
the list of DrawableGameElementStates representing all the terrain objects
Definition at line 55 of file TerrainGrid.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setSpritesheet().
Referenced by application.ShittyMain.hardCodeAGame().
List<DrawableGameElementState> game_engine.visuals.TerrainGrid.renderTerrain ()
Definition at line 74 of file TerrainGrid.java.
Member Data Documentation
int [][] game_engine.visuals.TerrainGrid.grid package
Definition at line 22 of file TerrainGrid.java.
final double game_engine.visuals.TerrainGrid.TILE_X_DIMENSION = 96 static
Definition at line 19 of file TerrainGrid.java.
final double game_engine.visuals.TerrainGrid.TILE_Y_DIMENSION = 48 static
Definition at line 20 of file TerrainGrid.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/TerrainGrid.java