voogasalad_TheException: game_engine.gameRepresentation.conditions.evaluators.Evaluator Class Reference
game_engine.gameRepresentation.conditions.evaluators.Evaluator Class Reference abstract
Public Member Functions
Evaluator (String evaluatorRepresentation, GameElementManager elementManager, String parameter1, String parameter2)
boolean evaluate (ElementPair elements)
String toString ()
Protected Member Functions
abstract boolean evaluate (double number1, double number2)
boolean evaluate (Object item1, Object item2)
Package Attributes
String myEvaluatorRepresentation
Private Attributes
Parameter myParameter1
Parameter myParameter2
Detailed Description
An abstract class for evaluators that acts on parameters to provide for functionality such as < > <= >=. If a data type is not supported for an operation, the evaluator will evaluate to false to fail silently in the case of improperly formatted input.
Author
Zach
Definition at line 19 of file Evaluator.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.conditions.evaluators.Evaluator.Evaluator (String evaluatorRepresentation, GameElementManager elementManager, String parameter1, String parameter2)
Create the evaluator with the string representation of the evaluator. This string representation will be set by the children of the evaluator and will be used in the creation of evaluators by a factory.
Parameters
evaluatorRepresentation the representation of the evaluator e.g. "<=", "==","+="
elementManager the main game element manager
parameter1 a string representation of the parameter on the left side of the evaluator
parameter2 a string representation of the parameter on the right side of the evaluator
Definition at line 34 of file Evaluator.java.
Member Function Documentation
abstract boolean game_engine.gameRepresentation.conditions.evaluators.Evaluator.evaluate (double number1, double number2) abstract protected
Evaluate a condition on the two given numbers and return the result
Parameters
number1 the leftmost number
number2 the rightmost number
Returns
the result of the evaluation on the numbers
Referenced by game_engine.gameRepresentation.conditions.evaluators.Evaluator.evaluate().
boolean game_engine.gameRepresentation.conditions.evaluators.Evaluator.evaluate (Object item1, Object item2) protected
Evaluate on two objects. By default returns false as only a subset of evaluators will act on generic objects
Parameters
item1 the object on the left side of the evaluator
item2 the object on the right side of the evaluator
Returns
the result of the evaluation on the two objects
Definition at line 60 of file Evaluator.java.
boolean game_engine.gameRepresentation.conditions.evaluators.Evaluator.evaluate (ElementPair elements)
Evaluate the evaluator on the element pair
Parameters
elements a pairing of the current element and the element that is being examined by it
Implements game_engine.gameRepresentation.conditions.Evaluatable.
Definition at line 70 of file Evaluator.java.
References game_engine.gameRepresentation.conditions.evaluators.Evaluator.evaluate(), and game_engine.gameRepresentation.conditions.evaluators.parameters.Parameter.getValue().
String game_engine.gameRepresentation.conditions.evaluators.Evaluator.toString ()
Definition at line 86 of file Evaluator.java.
References game_engine.gameRepresentation.conditions.evaluators.Evaluator.myEvaluatorRepresentation.
Member Data Documentation
String game_engine.gameRepresentation.conditions.evaluators.Evaluator.myEvaluatorRepresentation package
Definition at line 20 of file Evaluator.java.
Referenced by game_engine.gameRepresentation.conditions.evaluators.Evaluator.toString().
Parameter game_engine.gameRepresentation.conditions.evaluators.Evaluator.myParameter1 private
Definition at line 21 of file Evaluator.java.
Parameter game_engine.gameRepresentation.conditions.evaluators.Evaluator.myParameter2 private
Definition at line 22 of file Evaluator.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/conditions/evaluators/Evaluator.java