voogasalad_TheException: engine.Engine Class Reference
engine.Engine Class Reference
Public Member Functions
Engine (MainModel mainModel, LevelState levelState) throws ClassNotFoundException, JSONException, IOException
void setInputManager (Class<?> inputManagerClass) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException
void setAnimationEnabled (boolean b)
void play ()
void pause ()
void update (Observable observable, Object arg)
ScrollablePane getScene ()
Static Public Member Functions
static Color colorFromInt (int colorValue)
static int colorIntFromString (String color)
static String colorStringFromInt (int color)
Static Public Attributes
static final String DEFAULT_PLAYER_COLOR_STRING = "0x0000ffff"
static final int DEFAULT_PLAYER_COLOR = colorIntFromString(DEFAULT_PLAYER_COLOR_STRING)
Private Member Functions
void instantiateManagers (String backgroundPath)
void updateObservers ()
Private Attributes
MainModel myMainModel
GameLoop myGameLoop
LevelState myLevelState
GameElementManager myElementManager
VisualManager myVisualManager
InputManager myInputManager
ParticipantManager myParticipantManager
GameElementFactory myElementFactory
LevelFactory myLevelFactory
ActionFactory myEvaluatableFactory
VisualizerFactory myVisualizerFactory
HumanParticipant myUser
Detailed Description
The concrete boundary of the Engine - this class exposes the public API of the Engine to the rest of the project.
Author
Steve, Jonathan, Michael D., John L.
Definition at line 39 of file Engine.java.
Constructor & Destructor Documentation
engine.Engine.Engine (MainModel mainModel, LevelState levelState) throws ClassNotFoundException, JSONException, IOException
Definition at line 59 of file Engine.java.
References model.state.gameelement.StateTags.BACKGROUND_PATH, model.MainModel.getGameUniverse(), engine.Engine.instantiateManagers(), engine.Engine.myEvaluatableFactory, and engine.Engine.myVisualizerFactory.
Member Function Documentation
static Color engine.Engine.colorFromInt (int colorValue) static
Definition at line 77 of file Engine.java.
References engine.Engine.colorStringFromInt().
Referenced by model.sprite.SpriteImageContainer.getColorMask(), engine.visuals.elementVisuals.animations.Animator.setColorMasking(), and engine.visuals.MiniMap.setUnitColor().
static int engine.Engine.colorIntFromString (String color) static
Definition at line 81 of file Engine.java.
static String engine.Engine.colorStringFromInt (int color) static
Definition at line 85 of file Engine.java.
Referenced by engine.Engine.colorFromInt().
ScrollablePane engine.Engine.getScene ()
Gets the view of the background
Returns
The scene
Definition at line 169 of file Engine.java.
References engine.visuals.VisualManager.getScrollingScene().
Referenced by view.runner.GameRunnerPaneController.setLevel(), application.RPG.start(), and application.Pong.start().
void engine.Engine.instantiateManagers (String backgroundPath) private
Definition at line 110 of file Engine.java.
References engine.visuals.VisualManager.addObject(), engine.visuals.VisualManager.attachInputManager(), engine.visuals.VisualManager.attachParticipantManager(), engine.elementFactories.LevelFactory.createLevel(), engine.gameRepresentation.renderedRepresentation.Level.getGroups(), engine.gameRepresentation.renderedRepresentation.Level.getMapHeight(), engine.gameRepresentation.renderedRepresentation.Level.getMapWidth(), engine.gameRepresentation.evaluatables.actions.ActionFactory.setGameElementManager(), engine.stateManaging.GameElementManager.setLevel(), and engine.gameRepresentation.evaluatables.actions.ActionFactory.setParticipantManager().
Referenced by engine.Engine.Engine().
void engine.Engine.pause ()
Definition at line 142 of file Engine.java.
References engine.stateManaging.GameLoop.pause().
void engine.Engine.play ()
Definition at line 138 of file Engine.java.
References engine.stateManaging.GameLoop.play().
Referenced by view.runner.GameRunnerPaneController.setLevel(), application.RPG.start(), and application.Pong.start().
void engine.Engine.setAnimationEnabled (boolean b)
Definition at line 106 of file Engine.java.
References engine.elementFactories.VisualizerFactory.setAnimationEnabled().
Referenced by application.RPG.hardCodeAGame().
void engine.Engine.setInputManager (Class<?> inputManagerClass) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException
Definition at line 90 of file Engine.java.
References engine.visuals.VisualManager.attachInputManager().
Referenced by view.runner.GameRunnerPaneController.setInputManager().
void engine.Engine.update (Observable observable, Object arg)
Definition at line 147 of file Engine.java.
References engine.users.Participant.getAttributes(), engine.stateManaging.GameLoop.stop(), and engine.Engine.updateObservers().
void engine.Engine.updateObservers () private
called only when game is won
Definition at line 158 of file Engine.java.
References engine.users.Participant.getAttributes().
Referenced by engine.Engine.update().
Member Data Documentation
final int engine.Engine.DEFAULT_PLAYER_COLOR = colorIntFromString(DEFAULT_PLAYER_COLOR_STRING) static
Definition at line 42 of file Engine.java.
Referenced by engine.UI.ParticipantManager.update().
final String engine.Engine.DEFAULT_PLAYER_COLOR_STRING = "0x0000ffff" static
Definition at line 41 of file Engine.java.
Referenced by model.MainModel.newGame().
GameElementFactory engine.Engine.myElementFactory private
Definition at line 52 of file Engine.java.
GameElementManager engine.Engine.myElementManager private
Definition at line 47 of file Engine.java.
ActionFactory engine.Engine.myEvaluatableFactory private
Definition at line 54 of file Engine.java.
Referenced by engine.Engine.Engine().
GameLoop engine.Engine.myGameLoop private
Definition at line 44 of file Engine.java.
InputManager engine.Engine.myInputManager private
Definition at line 49 of file Engine.java.
LevelFactory engine.Engine.myLevelFactory private
Definition at line 53 of file Engine.java.
LevelState engine.Engine.myLevelState private
Definition at line 45 of file Engine.java.
MainModel engine.Engine.myMainModel private
Definition at line 43 of file Engine.java.
ParticipantManager engine.Engine.myParticipantManager private
Definition at line 50 of file Engine.java.
HumanParticipant engine.Engine.myUser private
Definition at line 57 of file Engine.java.
VisualizerFactory engine.Engine.myVisualizerFactory private
Definition at line 55 of file Engine.java.
Referenced by engine.Engine.Engine().
VisualManager engine.Engine.myVisualManager private
Definition at line 48 of file Engine.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/Engine.java