voogasalad_TheException: model.sprite.SpriteImageLoader Class Reference
model.sprite.SpriteImageLoader Class Reference
Static Public Member Functions
static Image loadTeamColorMask (String imageTag) throws SaveLoadException
static Image loadSpritesheet (String imageTag) throws SaveLoadException
Static Private Attributes
static final String DEFAULT_COLORMASK = "resources/gameelementresources/default.png"
Detailed Description
This class uses the mediator pattern to connect the SpriteImageGenerator with the SaveLoadUtility. This adds another layer of indirection and allows for all loading and saving of spritesheets and colormasks to pass through this module.
Author
Rahul
Definition at line 16 of file SpriteImageLoader.java.
Member Function Documentation
static Image model.sprite.SpriteImageLoader.loadSpritesheet (String imageTag) throws SaveLoadException static
Loads the image of the spritesheet at the specified file path
Parameters
imageTag file path to image
Returns
image at the specified path
Exceptions
SaveLoadException
Definition at line 40 of file SpriteImageLoader.java.
References util.SaveLoadUtility.loadImage().
Referenced by model.sprite.SpriteImageContainer.locateSpritesheet().
static Image model.sprite.SpriteImageLoader.loadTeamColorMask (String imageTag) throws SaveLoadException static
Loads the image of the color mask at the specified file path
Parameters
imageTag file path to image
Returns
image at the specified path
Exceptions
SaveLoadException
Definition at line 27 of file SpriteImageLoader.java.
References util.SaveLoadUtility.loadImage().
Referenced by model.sprite.SpriteImageContainer.locateColorMask().
Member Data Documentation
final String model.sprite.SpriteImageLoader.DEFAULT_COLORMASK = "resources/gameelementresources/default.png" static private
Definition at line 17 of file SpriteImageLoader.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/sprite/SpriteImageLoader.java