voogasalad_TheException: game_engine.visuals.VisualManager Class Reference
game_engine.visuals.VisualManager Class Reference
Public Member Functions
VisualManager (Group gameObjectVisuals, InputManager inputManager, double screenWidth, double screenHeight)
ScrollablePane getScrollingScene ()
Group getRoot ()
void update ()
Group getVisualRepresentation ()
void addBoxObserver (Observer o)
void addObjects (Group g)
void addMiniMap (Canvas c)
ScrollableBackground getBackground ()
Private Attributes
ScrollablePane scene
ScrollableBackground background
Group root
Detailed Description
The class containing the visual IO and UI pieces for the player. Manages retrieving and allowing observers to react to IO for clicking and key presses, as well as scrolling the map
Author
John, Michael D.
Definition at line 16 of file VisualManager.java.
Constructor & Destructor Documentation
game_engine.visuals.VisualManager.VisualManager (Group gameObjectVisuals, InputManager inputManager, double screenWidth, double screenHeight)
Creates a new VisualManager. One visual manager should be created for every Scene (map)
Parameters
gameObjectVisuals the group for initial objects on the map. If no objects yet exist, add an empty new Group()
screenWidth the width of the screen to create
screenHeight the height of the screen to create
Definition at line 29 of file VisualManager.java.
References game_engine.visuals.ScrollablePane.getScrollingBackground().
Member Function Documentation
void game_engine.visuals.VisualManager.addBoxObserver (Observer o)
Adds a new observer to any boxes drawn by this visual manager instance
Parameters
o
Definition at line 75 of file VisualManager.java.
References game_engine.visuals.ScrollablePane.addBoxObserver().
Referenced by game_engine.Engine.selectLevel(), and game_engine.Engine.updateGameLoop().
void game_engine.visuals.VisualManager.addMiniMap (Canvas c)
Definition at line 88 of file VisualManager.java.
References game_engine.visuals.ScrollablePane.addToScene().
Referenced by game_engine.Engine.selectLevel(), and game_engine.Engine.updateGameLoop().
void game_engine.visuals.VisualManager.addObjects (Group g)
Adds new objects to the map
Parameters
g
Definition at line 84 of file VisualManager.java.
References game_engine.visuals.ScrollableBackground.addObjects().
Referenced by game_engine.Engine.selectLevel(), and game_engine.Engine.updateGameLoop().
ScrollableBackground game_engine.visuals.VisualManager.getBackground ()
gets the ScrollableBackground that represents the map
Returns
the map's scrollablebackground representation
Definition at line 97 of file VisualManager.java.
References game_engine.visuals.VisualManager.background.
Referenced by game_engine.stateManaging.GameLoop.addPathsToRoot(), and game_engine.stateManaging.GameLoop.clearLinesFromRoot().
Group game_engine.visuals.VisualManager.getRoot ()
Definition at line 47 of file VisualManager.java.
References game_engine.visuals.VisualManager.root.
ScrollablePane game_engine.visuals.VisualManager.getScrollingScene ()
Gets the background scene in order to display
Returns
the Scene object that represents the map
Definition at line 43 of file VisualManager.java.
References game_engine.visuals.VisualManager.scene.
Referenced by game_engine.Engine.Engine(), and game_engine.Engine.getScene().
Group game_engine.visuals.VisualManager.getVisualRepresentation ()
Gets the group containing all elements added to the map
Returns
the group containing all nodes that have been added to the map. These will only have the JavaFX nodes, not all the states
Definition at line 65 of file VisualManager.java.
Referenced by game_engine.Engine.getVisualRepresentation().
void game_engine.visuals.VisualManager.update ()
updates the scene, should be called in each KeyFrame so that the background can update appropriately with scrolling
Definition at line 55 of file VisualManager.java.
References game_engine.visuals.ScrollablePane.update().
Referenced by game_engine.stateManaging.GameLoop.update().
Member Data Documentation
ScrollableBackground game_engine.visuals.VisualManager.background private
Definition at line 18 of file VisualManager.java.
Referenced by game_engine.visuals.VisualManager.getBackground().
Group game_engine.visuals.VisualManager.root private
Definition at line 19 of file VisualManager.java.
Referenced by game_engine.visuals.VisualManager.getRoot().
ScrollablePane game_engine.visuals.VisualManager.scene private
Definition at line 17 of file VisualManager.java.
Referenced by game_engine.visuals.VisualManager.getScrollingScene().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/VisualManager.java