voogasalad_TheException: game_engine.visuals.AnimationPlayer Class Reference
game_engine.visuals.AnimationPlayer Class Reference
Public Member Functions
AnimationPlayer (Image spriteSheet, Dimension tileSize, int numCols)
void setAnimation (AnimationSequence animation)
void setNextAnimation (@NotNull AnimationSequence animation)
Node getNode ()
boolean update ()
Dimension getDimension ()
Private Member Functions
Rectangle2D getImageBounds (Image img)
Rectangle2D getViewport (int frameNumber)
Private Attributes
Dimension myTileSize
AnimationSequence myCurrentAnimation
int myNumCols
ImageView myDisplay
Rectangle2D myImageBounds
Detailed Description
An animation player that allows for the playing of animations using a given spritesheet. This utility assumes all spritesheets are given with a horizontally traversable sheet
Author
Zach
Definition at line 19 of file AnimationPlayer.java.
Constructor & Destructor Documentation
game_engine.visuals.AnimationPlayer.AnimationPlayer (Image spriteSheet, Dimension tileSize, int numCols)
Initialize the player
Parameters
spriteSheet the image containing the spritesheet
tileSize a point2D containing the width(x) and height(y) of each frame in the spritesheet
numCols the number of columns across the spritesheet goes before moving to the next row
Definition at line 39 of file AnimationPlayer.java.
References game_engine.visuals.Dimension.getHeight(), game_engine.visuals.AnimationPlayer.getImageBounds(), and game_engine.visuals.Dimension.getWidth().
Member Function Documentation
Dimension game_engine.visuals.AnimationPlayer.getDimension ()
Definition at line 118 of file AnimationPlayer.java.
References game_engine.visuals.AnimationPlayer.myTileSize.
Referenced by game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.initializeDisplay().
Rectangle2D game_engine.visuals.AnimationPlayer.getImageBounds (Image img) private
Get a rectangular bounds of an image based on its dimensions
Parameters
img the image of interest
Returns
the bounds
Definition at line 55 of file AnimationPlayer.java.
Referenced by game_engine.visuals.AnimationPlayer.AnimationPlayer().
Node game_engine.visuals.AnimationPlayer.getNode ()
Get the display view for the animation
Implements game_engine.visuals.Displayable.
Definition at line 81 of file AnimationPlayer.java.
References game_engine.visuals.AnimationPlayer.myDisplay.
Referenced by test.animations.VisualTester.getDisplay(), and game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.initializeDisplay().
Rectangle2D game_engine.visuals.AnimationPlayer.getViewport (int frameNumber) private
Creates and returns a viewport based on a frame number. Assumes horizontal traversal of frames
Definition at line 108 of file AnimationPlayer.java.
References game_engine.visuals.Dimension.getHeight(), game_engine.visuals.Dimension.getWidth(), and game_engine.visuals.AnimationPlayer.myNumCols.
Referenced by game_engine.visuals.AnimationPlayer.update().
void game_engine.visuals.AnimationPlayer.setAnimation (AnimationSequence animation)
Set and play the current animation
Parameters
animation the current animation
Definition at line 66 of file AnimationPlayer.java.
Referenced by test.animations.VisualTester.getDisplay(), game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setAnimation(), and game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.update().
void game_engine.visuals.AnimationPlayer.setNextAnimation (@NotNull AnimationSequence animation)
Set the animation to be played once the current animation completes
Definition at line 73 of file AnimationPlayer.java.
References game_engine.visuals.AnimationSequence.setNextAnimation().
boolean game_engine.visuals.AnimationPlayer.update ()
Update the animation. Increment the frame and move on to the next animation if the current one is finished.
Implements game_engine.gameRepresentation.stateRepresentation.gameElement.traits.Updatable.
Definition at line 90 of file AnimationPlayer.java.
References game_engine.visuals.AnimationSequence.getFrame(), game_engine.visuals.AnimationSequence.getNextAnimation(), game_engine.visuals.AnimationPlayer.getViewport(), and game_engine.visuals.AnimationSequence.update().
Referenced by test.animations.VisualTester.getDisplay(), and game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.update().
Member Data Documentation
AnimationSequence game_engine.visuals.AnimationPlayer.myCurrentAnimation private
Definition at line 22 of file AnimationPlayer.java.
ImageView game_engine.visuals.AnimationPlayer.myDisplay private
Definition at line 24 of file AnimationPlayer.java.
Referenced by game_engine.visuals.AnimationPlayer.getNode().
Rectangle2D game_engine.visuals.AnimationPlayer.myImageBounds private
Definition at line 25 of file AnimationPlayer.java.
int game_engine.visuals.AnimationPlayer.myNumCols private
Definition at line 23 of file AnimationPlayer.java.
Referenced by game_engine.visuals.AnimationPlayer.getViewport().
Dimension game_engine.visuals.AnimationPlayer.myTileSize private
Definition at line 21 of file AnimationPlayer.java.
Referenced by game_engine.visuals.AnimationPlayer.getDimension().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/AnimationPlayer.java