voogasalad_TheException: application.ShittyMain Class Reference
application.ShittyMain Class Reference
Public Member Functions
void start (Stage primaryStage)
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final java.awt.Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize()
static final int shittyWidth = 1279
Private Member Functions
MainModel hardCodeAGame () throws Exception
SelectableGameElementState createArcher (double[] bounds, double x, double y, int teamID, int randomMovement)
Detailed Description
Definition at line 25 of file ShittyMain.java.
Member Function Documentation
SelectableGameElementState application.ShittyMain.createArcher (double[] bounds, double x, double y, int teamID, int randomMovement) private
Definition at line 92 of file ShittyMain.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.addAnimation(), game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.CAN_MOVE_STRING, game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.RANDOM_MOVEMENT_STRING, game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setBounds(), game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setNumericalAttribute(), game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setSpritesheet(), and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.TEAM_ID.
Referenced by application.ShittyMain.hardCodeAGame().
MainModel application.ShittyMain.hardCodeAGame () throws Exception private
Definition at line 53 of file ShittyMain.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.addAnimation(), game_engine.gameRepresentation.stateRepresentation.LevelState.addTerrain(), game_engine.gameRepresentation.stateRepresentation.LevelState.addUnit(), application.ShittyMain.createArcher(), gamemodel.MainModel.createCampaign(), gamemodel.MainModel.createLevel(), game_engine.visuals.ScrollablePane.FIELD_HEIGHT, game_engine.visuals.ScrollablePane.FIELD_WIDTH, gamemodel.MainModel.getCurrentLevel(), gamemodel.MainModel.newGame(), game_engine.visuals.TerrainGrid.renderTerrain(), game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setBounds(), game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setNumericalAttribute(), game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setSpritesheet(), and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.TEAM_ID.
Referenced by application.ShittyMain.start().
static void application.ShittyMain.main (String[] args) static
Definition at line 135 of file ShittyMain.java.
void application.ShittyMain.start (Stage primaryStage)
Definition at line 31 of file ShittyMain.java.
References game_engine.visuals.Dimension.getHeight(), game_engine.Engine.getScene(), application.ShittyMain.hardCodeAGame(), game_engine.Engine.play(), and application.ShittyMain.screenSize.
Member Data Documentation
final java.awt.Dimension application.ShittyMain.screenSize = Toolkit.getDefaultToolkit().getScreenSize() static
Definition at line 27 of file ShittyMain.java.
Referenced by game_engine.Engine.Engine(), and application.ShittyMain.start().
final int application.ShittyMain.shittyWidth = 1279 static
Definition at line 28 of file ShittyMain.java.
Referenced by game_engine.Engine.Engine().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/application/ShittyMain.java