voogasalad_TheException: model.state.DescribableState Class Reference
model.state.DescribableState Class Reference abstract
Public Member Functions
void updateName (String name)
void updateDescription (String description)
String getName ()
String getDescription ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from util.JSONable
default String toJSON ()
Protected Member Functions
DescribableState ()
DescribableState (String name)
Private Attributes
String myName
String myDescription
final int myHashingPrime = 31
Static Private Attributes
static final long serialVersionUID = 267624806010749314L
Detailed Description
A state object that has a name and description. Essentially used to create states with associated name and description metadata.
Author
Jonathan, Nishad, Rahul
Definition at line 13 of file DescribableState.java.
Constructor & Destructor Documentation
model.state.DescribableState.DescribableState () protected
Definition at line 23 of file DescribableState.java.
Referenced by model.state.DescribableState.equals().
model.state.DescribableState.DescribableState (String name) protected
Definition at line 27 of file DescribableState.java.
Member Function Documentation
boolean model.state.DescribableState.equals (Object obj)
Checks equality of describable states
Definition at line 102 of file DescribableState.java.
References model.state.DescribableState.DescribableState(), model.state.DescribableState.myDescription, and model.state.DescribableState.myName.
String model.state.DescribableState.getDescription ()
Returns the description of the DescribableState
Returns
description the description of the describable state
Definition at line 68 of file DescribableState.java.
References model.state.DescribableState.myDescription.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.getDescription(), model.state.DescribableState.toString(), and view.editor.EditorScreen.updateInfoBox().
String model.state.DescribableState.getName ()
Returns the name of the DescribableState
Returns
name the name of the describable state
Definition at line 58 of file DescribableState.java.
References model.state.DescribableState.myName.
Referenced by view.runner.GameRunnerPaneController.engineUpdate(), engine.gameRepresentation.renderedRepresentation.Level.getName(), model.MainModel.saveGame(), model.state.DescribableState.toString(), view.editor.EditorScreen.updateInfoBox(), and view.editor.EditorScreen.updateProjectExplorer().
int model.state.DescribableState.hashCode ()
Returns the hashcode of the describable state for comparison
Returns
int the custom hashcode of the describable state
Definition at line 90 of file DescribableState.java.
References model.state.DescribableState.myHashingPrime.
String model.state.DescribableState.toString ()
Returns the Stringified version of the Describable State
Returns
String a concatenated string of the name and description
Definition at line 79 of file DescribableState.java.
References model.state.DescribableState.getDescription(), and model.state.DescribableState.getName().
void model.state.DescribableState.updateDescription (String description)
Sets the description of the DescribableState
Parameters
description the description of the describable state
Definition at line 48 of file DescribableState.java.
Referenced by model.MainModel.updateDescribableState().
void model.state.DescribableState.updateName (String name)
Sets the name of the DescribableState
Parameters
name the name of the describable state
Definition at line 38 of file DescribableState.java.
Referenced by model.MainModel.updateDescribableState().
Member Data Documentation
String model.state.DescribableState.myDescription private
Definition at line 20 of file DescribableState.java.
Referenced by model.state.DescribableState.equals(), and model.state.DescribableState.getDescription().
final int model.state.DescribableState.myHashingPrime = 31 private
Definition at line 21 of file DescribableState.java.
Referenced by model.state.DescribableState.hashCode().
String model.state.DescribableState.myName private
Definition at line 19 of file DescribableState.java.
Referenced by model.state.DescribableState.equals(), and model.state.DescribableState.getName().
final long model.state.DescribableState.serialVersionUID = 267624806010749314L static private
Auto-generated
Definition at line 18 of file DescribableState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/DescribableState.java