voogasalad_TheException: view.SplashScreen Class Reference
view.SplashScreen Class Reference
Public Member Functions
Node getRoot ()
void init ()
void update ()
Public Member Functions inherited from view.GUIScreen
void attachSceneHandler (MainView mainView)
Public Member Functions inherited from view.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
abstract void update ()
Private Member Functions
void setUpButtons ()
void drawTitle ()
void attachStringProperties ()
Private Attributes
GridPane splash
Button launchEditorButton
Button launchRunnerButton
ComboBox< String > myGames
ComboBox< String > gameDropDown
Button newGameButton
Label title
Static Private Attributes
static final String LAUNCH_EDITOR_KEY = "LaunchEditor"
static final String LAUNCH_RUNNER_KEY = "LaunchRunner"
static final String NEW_GAME_KEY = "NewGame"
static final String CHOOSE_GAME_KEY = "ChooseGame"
static final String DUVALL_PATH = "resources/duvall.txt"
static final Integer LOAD_DURATION = 50
static final String LAUNCH_EDITOR = "Launch Editor"
static final String LAUNCH_RUNNER = "Launch Runner"
static final String GAMES_DIRECTORY = "./myGames/"
Additional Inherited Members
Protected Member Functions inherited from view.GUIScreen
void switchScreen (ViewScreen screen)
Protected Member Functions inherited from view.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.GUIContainer
MainModel myMainModel
Detailed Description
Author
Jonathan
Nishad
Joshua
Definition at line 34 of file SplashScreen.java.
Member Function Documentation
void view.SplashScreen.attachStringProperties () private
Definition at line 140 of file SplashScreen.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.SplashScreen.setUpButtons().
void view.SplashScreen.drawTitle () private
Definition at line 120 of file SplashScreen.java.
Referenced by view.SplashScreen.init().
Node view.SplashScreen.getRoot ()
Implements view.GUIController.
Definition at line 65 of file SplashScreen.java.
References view.SplashScreen.splash.
void view.SplashScreen.init ()
Definition at line 70 of file SplashScreen.java.
References view.SplashScreen.drawTitle(), and view.SplashScreen.setUpButtons().
void view.SplashScreen.setUpButtons () private
Definition at line 87 of file SplashScreen.java.
References view.SplashScreen.attachStringProperties(), view.ViewScreen.EDITOR, gamemodel.MainModel.loadGame(), view.GUIContainer.myMainModel, gamemodel.MainModel.newGame(), and view.GUIScreen.switchScreen().
Referenced by view.SplashScreen.init().
void view.SplashScreen.update ()
Definition at line 155 of file SplashScreen.java.
Member Data Documentation
final String view.SplashScreen.CHOOSE_GAME_KEY = "ChooseGame" static private
Definition at line 39 of file SplashScreen.java.
final String view.SplashScreen.DUVALL_PATH = "resources/duvall.txt" static private
Definition at line 41 of file SplashScreen.java.
ComboBox<String> view.SplashScreen.gameDropDown private
Definition at line 58 of file SplashScreen.java.
final String view.SplashScreen.GAMES_DIRECTORY = "./myGames/" static private
Definition at line 55 of file SplashScreen.java.
final String view.SplashScreen.LAUNCH_EDITOR = "Launch Editor" static private
Definition at line 53 of file SplashScreen.java.
final String view.SplashScreen.LAUNCH_EDITOR_KEY = "LaunchEditor" static private
Definition at line 36 of file SplashScreen.java.
final String view.SplashScreen.LAUNCH_RUNNER = "Launch Runner" static private
Definition at line 54 of file SplashScreen.java.
final String view.SplashScreen.LAUNCH_RUNNER_KEY = "LaunchRunner" static private
Definition at line 37 of file SplashScreen.java.
Button view.SplashScreen.launchEditorButton private
Definition at line 48 of file SplashScreen.java.
Button view.SplashScreen.launchRunnerButton private
Definition at line 50 of file SplashScreen.java.
final Integer view.SplashScreen.LOAD_DURATION = 50 static private
Definition at line 42 of file SplashScreen.java.
ComboBox<String> view.SplashScreen.myGames private
Definition at line 52 of file SplashScreen.java.
final String view.SplashScreen.NEW_GAME_KEY = "NewGame" static private
Definition at line 38 of file SplashScreen.java.
Button view.SplashScreen.newGameButton private
Definition at line 60 of file SplashScreen.java.
GridPane view.SplashScreen.splash private
Definition at line 46 of file SplashScreen.java.
Referenced by view.SplashScreen.getRoot().
Label view.SplashScreen.title private
Definition at line 62 of file SplashScreen.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/SplashScreen.java