voogasalad_TheException: gamemodel.MainModel Class Reference
gamemodel.MainModel Class Reference
Public Member Functions
MainModel ()
void newGame (String newGameName)
void loadGame (String game) throws Exception
void updateDescribableState (String[] selection, String name, String description) throws CampaignNotFoundException, LevelNotFoundException
DescribableState getDescribableState (String[] selection) throws CampaignNotFoundException, LevelNotFoundException
void saveGame () throws RuntimeException
GameState getCurrentGame ()
void setCurrentLevel (String campaignName, String levelName) throws DescribableStateException
void setEditorSelected (String elementName)
GameElementState getEditorSelected ()
void createCampaign (String campaignName) throws CampaignExistsException
void createLevel (String levelName, String campaignName) throws LevelExistsException, CampaignNotFoundException
void createGameElement (WizardData data)
void createDrawableGameElement (WizardData data)
void createSelectableGameElement (WizardData data)
void addGoal (WizardData data)
CampaignState getCurrentCampaign ()
LevelState getCurrentLevel ()
GameUniverse getGameUniverse ()
Private Member Functions
String getGameSaveLocation (String name)
Private Attributes
GameState myGameState
CampaignState myCurrentCampaignState
LevelState myCurrentLevelState
GameElementState myEditorSelectedElement
SaveLoadUtility mySLUtil
Static Private Attributes
static final String JSON_EXT = ".json"
Detailed Description
Main class for the model of the game
Author
Jonathan Tseng, Rahul Harikrishnan, Nishad Agrawal
Definition at line 28 of file MainModel.java.
Constructor & Destructor Documentation
gamemodel.MainModel.MainModel ()
Definition at line 37 of file MainModel.java.
Member Function Documentation
void gamemodel.MainModel.addGoal (WizardData data)
Definition at line 242 of file MainModel.java.
References game_engine.gameRepresentation.stateRepresentation.LevelState.addGoal(), and gamemodel.GameElementStateFactory.createGoal().
Referenced by editor.TabViewController.launchNestedWizard().
void gamemodel.MainModel.createCampaign (String campaignName) throws CampaignExistsException
called by editor when creating a new campaign
Parameters
campaignName
Exceptions
CampaignExistsException
Definition at line 156 of file MainModel.java.
References game_engine.gameRepresentation.stateRepresentation.GameState.addCampaign().
Referenced by application.ShittyMain.hardCodeAGame(), and editor.EditorMenuBarController.onNewCampaignClick().
void gamemodel.MainModel.createDrawableGameElement (WizardData data)
called by editor when creating a new game element
Parameters
data
Definition at line 201 of file MainModel.java.
References gamemodel.GameUniverse.addDrawableGameElementState(), gamemodel.GameElementStateFactory.createDrawableGameElementState(), game_engine.gameRepresentation.stateRepresentation.GameState.getGameUniverse(), editor.wizards.WizardData.getValueByKey(), gamemodel.GameElementStateFactory.IMAGE, gamemodel.GameElementStateFactory.NAME, and util.SaveLoadUtility.saveImage().
Referenced by editor.ElementAccordionController.openGameElementWizard().
void gamemodel.MainModel.createGameElement (WizardData data)
called by editor when creating a new game element
Parameters
data
Definition at line 186 of file MainModel.java.
References gamemodel.GameUniverse.addGameElementState(), gamemodel.GameElementStateFactory.createGameElementState(), and game_engine.gameRepresentation.stateRepresentation.GameState.getGameUniverse().
void gamemodel.MainModel.createLevel (String levelName, String campaignName) throws LevelExistsException, CampaignNotFoundException
called by editor when creating a new level under a certain campaign
Parameters
campaignName
levelName
Exceptions
LevelExistsException
Definition at line 171 of file MainModel.java.
References game_engine.gameRepresentation.stateRepresentation.CampaignState.addLevel(), and game_engine.gameRepresentation.stateRepresentation.GameState.getCampaign().
Referenced by application.ShittyMain.hardCodeAGame(), and editor.EditorMenuBarController.onNewLevelClick().
void gamemodel.MainModel.createSelectableGameElement (WizardData data)
called by editor when creating a new game element
Parameters
data
Definition at line 232 of file MainModel.java.
References gamemodel.GameUniverse.addSelectableGameElementState(), gamemodel.GameElementStateFactory.createSelectableGameElementState(), and game_engine.gameRepresentation.stateRepresentation.GameState.getGameUniverse().
CampaignState gamemodel.MainModel.getCurrentCampaign ()
returns the current campaign
Returns
Definition at line 256 of file MainModel.java.
References gamemodel.MainModel.myCurrentCampaignState.
Referenced by game_engine.Engine.play(), and game_engine.Engine.update().
GameState gamemodel.MainModel.getCurrentGame ()
Definition at line 116 of file MainModel.java.
References gamemodel.MainModel.myGameState.
Referenced by editor.EditorScreen.updateProjectExplorer().
LevelState gamemodel.MainModel.getCurrentLevel ()
returns the current level
Returns
Definition at line 265 of file MainModel.java.
References gamemodel.MainModel.myCurrentLevelState.
Referenced by application.ShittyMain.hardCodeAGame(), game_engine.Engine.play(), game_engine.Engine.selectLevel(), game_engine.Engine.update(), game_engine.Engine.updateGameLoop(), and editor.TabViewController.updateLevelTriggersView().
DescribableState gamemodel.MainModel.getDescribableState (String[] selection) throws CampaignNotFoundException, LevelNotFoundException
Definition at line 81 of file MainModel.java.
References game_engine.gameRepresentation.stateRepresentation.GameState.getCampaign(), game_engine.gameRepresentation.stateRepresentation.CampaignState.getLevel(), and gamemodel.MainModel.myGameState.
Referenced by gamemodel.MainModel.updateDescribableState(), and editor.EditorScreen.updateInfoBox().
GameElementState gamemodel.MainModel.getEditorSelected ()
called by engine when registers click and needs what the editor has selected to place on the map
Definition at line 143 of file MainModel.java.
References gamemodel.MainModel.myEditorSelectedElement.
String gamemodel.MainModel.getGameSaveLocation (String name) private
Definition at line 112 of file MainModel.java.
References gamemodel.MainModel.JSON_EXT.
Referenced by gamemodel.MainModel.loadGame(), and gamemodel.MainModel.saveGame().
GameUniverse gamemodel.MainModel.getGameUniverse ()
gets the game universe (list of all elements that could be used in the currently selected game
Returns
Definition at line 275 of file MainModel.java.
References game_engine.gameRepresentation.stateRepresentation.GameState.getGameUniverse().
Referenced by game_engine.Engine.Engine(), and editor.EditorScreen.updateAccordion().
void gamemodel.MainModel.loadGame (String game) throws Exception
Sets the game of the Model.
Parameters
game
Exceptions
Exception
Definition at line 53 of file MainModel.java.
References game_engine.gameRepresentation.stateRepresentation.GameState.getCampaigns(), gamemodel.MainModel.getGameSaveLocation(), and util.SaveLoadUtility.loadResource().
Referenced by view.SplashScreen.setUpButtons().
void gamemodel.MainModel.newGame (String newGameName)
Definition at line 41 of file MainModel.java.
Referenced by application.ShittyMain.hardCodeAGame(), and view.SplashScreen.setUpButtons().
void gamemodel.MainModel.saveGame () throws RuntimeException
Definition at line 97 of file MainModel.java.
References gamemodel.MainModel.getGameSaveLocation(), game_engine.gameRepresentation.stateRepresentation.DescribableState.getName(), and util.SaveLoadUtility.save().
Referenced by editor.EditorMenuBarController.initFileMenu().
void gamemodel.MainModel.setCurrentLevel (String campaignName, String levelName) throws DescribableStateException
Definition at line 120 of file MainModel.java.
References game_engine.gameRepresentation.stateRepresentation.GameState.getCampaign(), and game_engine.gameRepresentation.stateRepresentation.CampaignState.getLevel().
Referenced by game_engine.Engine.selectLevel().
void gamemodel.MainModel.setEditorSelected (String elementName)
called by editor when user selects new element from accordion pane
Parameters
element
Definition at line 131 of file MainModel.java.
void gamemodel.MainModel.updateDescribableState (String[] selection, String name, String description) throws CampaignNotFoundException, LevelNotFoundException
Definition at line 70 of file MainModel.java.
References gamemodel.MainModel.getDescribableState(), game_engine.gameRepresentation.stateRepresentation.DescribableState.updateDescription(), and game_engine.gameRepresentation.stateRepresentation.DescribableState.updateName().
Referenced by editor.EditorScreen.initInfoBox().
Member Data Documentation
final String gamemodel.MainModel.JSON_EXT = ".json" static private
Definition at line 30 of file MainModel.java.
Referenced by gamemodel.MainModel.getGameSaveLocation().
CampaignState gamemodel.MainModel.myCurrentCampaignState private
Definition at line 32 of file MainModel.java.
Referenced by gamemodel.MainModel.getCurrentCampaign().
LevelState gamemodel.MainModel.myCurrentLevelState private
Definition at line 33 of file MainModel.java.
Referenced by gamemodel.MainModel.getCurrentLevel().
GameElementState gamemodel.MainModel.myEditorSelectedElement private
Definition at line 34 of file MainModel.java.
Referenced by gamemodel.MainModel.getEditorSelected().
GameState gamemodel.MainModel.myGameState private
Definition at line 31 of file MainModel.java.
Referenced by gamemodel.MainModel.getCurrentGame(), and gamemodel.MainModel.getDescribableState().
SaveLoadUtility gamemodel.MainModel.mySLUtil private
Definition at line 35 of file MainModel.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/gamemodel/MainModel.java