voogasalad_TheException: util.DeepCopy Class Reference
util.DeepCopy Class Reference
Static Public Member Functions
static Object deepCopy (Object originalObject)
Detailed Description
Deep copy utility that makes deep copies using serialization..
Author
Steve
Definition at line 17 of file DeepCopy.java.
Member Function Documentation
static Object util.DeepCopy.deepCopy (Object originalObject) static
Return a deep copy of an object
Parameters
originalObject the serializable object to deep copy
Returns
a deep copy of the object
Definition at line 25 of file DeepCopy.java.
Referenced by model.GameUniverse.getDrawableGameElementState(), model.GameUniverse.getGameElementState(), model.GameUniverse.getSelectableGameElementState(), and view.runner.GameRunnerPaneController.setLevel().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/util/DeepCopy.java