voogasalad_TheException: engine.stateManaging.GameElementManager Class Reference
engine.stateManaging.GameElementManager Class Reference
Public Member Functions
GameElementManager (GameElementFactory factory)
void setLevel (Level level)
List< GameElement > findAllElementsOfType (String typeName)
void addGameElementToLevel (String typeName, double x, double y)
void addDrawableGameElementToLevel (String typeName, double x, double y)
SelectableGameElement addSelectableGameElementToLevel (String typeName, double x, double y, Number color)
void selectAnySingleUnit (Point2D clickLoc, Participant u)
void moveSelectedUnit (Point2D mapPoint2d, Participant user)
void deleteSelectedUnit ()
void selectUnitsInBounds (double[] rectPoints, boolean multiSelect, Participant u)
void selectSingleUnit (Point2D clickLoc, boolean multiSelect, Participant u)
void setSelectedUnitCommand (Point2D click, boolean queueCommand, Participant u)
void notifyButtonClicked (int buttonID, Participant u)
Private Member Functions
void selectUnit (List< DrawableGameElement > elements, Point2D clickLoc)
void deselectAllElements ()
boolean checkOnTeam (SelectableGameElement e, Participant u)
void notifySelectedElementsOfTarget (SelectableGameElement e, Participant u)
void clearSelectedElementsOfTarget (Participant u)
List< SelectableGameElement > filterSelectedUnits (List< SelectableGameElement > list)
List< SelectableGameElement > filterTeamIDElements (List< SelectableGameElement > list, Participant p)
boolean contains (double[] rectPoints, Point2D unitLocationCenter)
Private Attributes
Level myLevel
GameElementFactory myFactory
PathingComputer pathingComputer
DrawableGameElement selectedElement
Detailed Description
A manager for selecting, deselecting, and interacting with game elements
Author
John, Steve, Michael D., Zach
Definition at line 24 of file GameElementManager.java.
Constructor & Destructor Documentation
engine.stateManaging.GameElementManager.GameElementManager (GameElementFactory factory)
Definition at line 32 of file GameElementManager.java.
Member Function Documentation
void engine.stateManaging.GameElementManager.addDrawableGameElementToLevel (String typeName, double x, double y)
Definition at line 64 of file GameElementManager.java.
References engine.gameRepresentation.renderedRepresentation.Level.addElement(), and engine.elementFactories.GameElementFactory.createDrawableGameElement().
Referenced by engine.UI.EditorInputManager.primaryClickOccurred().
void engine.stateManaging.GameElementManager.addGameElementToLevel (String typeName, double x, double y)
Definition at line 59 of file GameElementManager.java.
References engine.gameRepresentation.renderedRepresentation.Level.addElement(), and engine.elementFactories.GameElementFactory.createGameElement().
SelectableGameElement engine.stateManaging.GameElementManager.addSelectableGameElementToLevel (String typeName, double x, double y, Number color)
Definition at line 71 of file GameElementManager.java.
References engine.gameRepresentation.renderedRepresentation.Level.addElement(), and engine.elementFactories.GameElementFactory.createSelectableGameElement().
Referenced by engine.gameRepresentation.evaluatables.evaluators.SpawnSelectableElement< A, B >.evaluate(), and engine.UI.EditorInputManager.primaryClickOccurred().
boolean engine.stateManaging.GameElementManager.checkOnTeam (SelectableGameElement e, Participant u) private
Definition at line 148 of file GameElementManager.java.
References engine.users.Participant.checkSameTeam(), engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), and model.state.gameelement.StateTags.TEAM_COLOR.
Referenced by engine.stateManaging.GameElementManager.selectSingleUnit(), engine.stateManaging.GameElementManager.selectUnitsInBounds(), and engine.stateManaging.GameElementManager.setSelectedUnitCommand().
void engine.stateManaging.GameElementManager.clearSelectedElementsOfTarget (Participant u) private
Definition at line 211 of file GameElementManager.java.
References engine.stateManaging.GameElementManager.filterSelectedUnits(), engine.stateManaging.GameElementManager.filterTeamIDElements(), and engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Referenced by engine.stateManaging.GameElementManager.setSelectedUnitCommand().
boolean engine.stateManaging.GameElementManager.contains (double[] rectPoints, Point2D unitLocationCenter) private
Determines whether the rectangle defined by rectPoints contains a Point2D
Parameters
rectPoints a length 4 array with points { x_top_right, y_top_right, x_bottom_left, y_bottom_left}
unitLocationCenter point2D that contains is checking
Returns
whether the rectangle contains the point2D
Definition at line 246 of file GameElementManager.java.
Referenced by engine.stateManaging.GameElementManager.selectSingleUnit(), engine.stateManaging.GameElementManager.selectUnit(), engine.stateManaging.GameElementManager.selectUnitsInBounds(), and engine.stateManaging.GameElementManager.setSelectedUnitCommand().
void engine.stateManaging.GameElementManager.deleteSelectedUnit ()
Definition at line 110 of file GameElementManager.java.
References engine.gameRepresentation.renderedRepresentation.Level.removeElement().
Referenced by engine.UI.EditorInputManager.keyPressed().
void engine.stateManaging.GameElementManager.deselectAllElements () private
Definition at line 101 of file GameElementManager.java.
References engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Referenced by engine.stateManaging.GameElementManager.selectAnySingleUnit().
List<SelectableGameElement> engine.stateManaging.GameElementManager.filterSelectedUnits (List< SelectableGameElement > list) private
Definition at line 216 of file GameElementManager.java.
References model.state.gameelement.StateTags.IS_SELECTED.
Referenced by engine.stateManaging.GameElementManager.clearSelectedElementsOfTarget(), engine.stateManaging.GameElementManager.notifyButtonClicked(), engine.stateManaging.GameElementManager.notifySelectedElementsOfTarget(), and engine.stateManaging.GameElementManager.setSelectedUnitCommand().
List<SelectableGameElement> engine.stateManaging.GameElementManager.filterTeamIDElements (List< SelectableGameElement > list, Participant p) private
Definition at line 223 of file GameElementManager.java.
References engine.users.Participant.checkSameTeam(), and model.state.gameelement.StateTags.TEAM_COLOR.
Referenced by engine.stateManaging.GameElementManager.clearSelectedElementsOfTarget(), engine.stateManaging.GameElementManager.notifyButtonClicked(), engine.stateManaging.GameElementManager.notifySelectedElementsOfTarget(), and engine.stateManaging.GameElementManager.setSelectedUnitCommand().
List<GameElement> engine.stateManaging.GameElementManager.findAllElementsOfType (String typeName)
Get all the game elements of a given type
Parameters
typeName the name of the type of the game elements
Returns
all the game elements with the given type
Definition at line 53 of file GameElementManager.java.
References engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Referenced by engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.evaluate(), and engine.gameRepresentation.evaluatables.parameters.objectIdentifiers.GlobalObjectIdentifier.getElementOfInterest().
void engine.stateManaging.GameElementManager.moveSelectedUnit (Point2D mapPoint2d, Participant user)
Definition at line 105 of file GameElementManager.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.setPosition().
Referenced by engine.UI.EditorInputManager.secondaryClickOccurred().
void engine.stateManaging.GameElementManager.notifyButtonClicked (int buttonID, Participant u)
Definition at line 231 of file GameElementManager.java.
References engine.stateManaging.GameElementManager.filterSelectedUnits(), engine.stateManaging.GameElementManager.filterTeamIDElements(), engine.gameRepresentation.renderedRepresentation.Level.getUnits(), and model.state.gameelement.StateTags.LAST_BUTTON_CLICKED_ID.
Referenced by engine.UI.RunnerInputManager.keyPressed(), and engine.UI.RunnerInputManager.screenButtonClicked().
void engine.stateManaging.GameElementManager.notifySelectedElementsOfTarget (SelectableGameElement e, Participant u) private
Definition at line 205 of file GameElementManager.java.
References engine.stateManaging.GameElementManager.filterSelectedUnits(), engine.stateManaging.GameElementManager.filterTeamIDElements(), and engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Referenced by engine.stateManaging.GameElementManager.setSelectedUnitCommand().
void engine.stateManaging.GameElementManager.selectAnySingleUnit (Point2D clickLoc, Participant u)
Definition at line 81 of file GameElementManager.java.
References engine.stateManaging.GameElementManager.deselectAllElements(), engine.gameRepresentation.renderedRepresentation.Level.getTerrain(), engine.gameRepresentation.renderedRepresentation.Level.getUnits(), and engine.stateManaging.GameElementManager.selectUnit().
Referenced by engine.UI.EditorInputManager.primaryClickOccurred().
void engine.stateManaging.GameElementManager.selectSingleUnit (Point2D clickLoc, boolean multiSelect, Participant u)
Definition at line 152 of file GameElementManager.java.
References engine.stateManaging.GameElementManager.checkOnTeam(), engine.stateManaging.GameElementManager.contains(), and engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Referenced by engine.UI.EditorInputManager.primaryClickOccurred(), and engine.UI.RunnerInputManager.primaryClickOccurred().
void engine.stateManaging.GameElementManager.selectUnit (List< DrawableGameElement > elements, Point2D clickLoc) private
Definition at line 91 of file GameElementManager.java.
References engine.stateManaging.GameElementManager.contains().
Referenced by engine.stateManaging.GameElementManager.selectAnySingleUnit().
void engine.stateManaging.GameElementManager.selectUnitsInBounds (double[] rectPoints, boolean multiSelect, Participant u)
Select all the elements in a given rectangle
Parameters
rectPoints the points in the rectangle surrounding the player's units
Definition at line 121 of file GameElementManager.java.
References engine.stateManaging.GameElementManager.checkOnTeam(), engine.stateManaging.GameElementManager.contains(), and engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Referenced by engine.UI.RunnerInputManager.primaryClickReleaseOccurred().
void engine.stateManaging.GameElementManager.setLevel (Level level)
Set the level for the element manager
Parameters
level
Definition at line 41 of file GameElementManager.java.
References engine.gameRepresentation.renderedRepresentation.Level.getGrid().
Referenced by engine.Engine.instantiateManagers().
void engine.stateManaging.GameElementManager.setSelectedUnitCommand (Point2D click, boolean queueCommand, Participant u)
Definition at line 169 of file GameElementManager.java.
References engine.stateManaging.GameElementManager.checkOnTeam(), engine.stateManaging.GameElementManager.clearSelectedElementsOfTarget(), engine.stateManaging.GameElementManager.contains(), engine.stateManaging.GameElementManager.filterSelectedUnits(), engine.stateManaging.GameElementManager.filterTeamIDElements(), engine.computers.pathingComputers.PathingComputer.findPath(), engine.gameRepresentation.renderedRepresentation.Level.getUnits(), engine.stateManaging.GameElementManager.notifySelectedElementsOfTarget(), model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
Referenced by engine.UI.RunnerInputManager.secondaryClickOccurred().
Member Data Documentation
GameElementFactory engine.stateManaging.GameElementManager.myFactory private
Definition at line 27 of file GameElementManager.java.
Level engine.stateManaging.GameElementManager.myLevel private
Definition at line 26 of file GameElementManager.java.
PathingComputer engine.stateManaging.GameElementManager.pathingComputer private
Definition at line 28 of file GameElementManager.java.
DrawableGameElement engine.stateManaging.GameElementManager.selectedElement private
Definition at line 30 of file GameElementManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/stateManaging/GameElementManager.java