voogasalad_TheException: view.editor.DescribableInfoBoxController Class Reference
view.editor.DescribableInfoBoxController Class Reference
Public Member Functions
void setSubmitAction (BiConsumer< String, String > textChangedAction)
void setText (String name, String description)
Node getRoot ()
void initialize ()
Private Member Functions
void initLabelInputSwitching ()
void setEditableToggle (TextInputControl textInputControl)
Private Attributes
BiConsumer< String, String > mySubmitConsumer
VBox infoRoot
TextField nameTextField
TextArea descriptionTextArea
Button submitButton
Static Private Attributes
static final String SUBMIT_KEY = "Update"
Detailed Description
Author
Jonathan Tseng
Definition at line 21 of file DescribableInfoBoxController.java.
Member Function Documentation
Node view.editor.DescribableInfoBoxController.getRoot ()
Implements view.gui.GUIController.
Definition at line 59 of file DescribableInfoBoxController.java.
References view.editor.DescribableInfoBoxController.infoRoot.
void view.editor.DescribableInfoBoxController.initialize ()
Implements view.gui.GUIController.
Definition at line 64 of file DescribableInfoBoxController.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), and view.editor.DescribableInfoBoxController.initLabelInputSwitching().
void view.editor.DescribableInfoBoxController.initLabelInputSwitching () private
Definition at line 37 of file DescribableInfoBoxController.java.
References view.editor.DescribableInfoBoxController.setEditableToggle().
Referenced by view.editor.DescribableInfoBoxController.initialize().
void view.editor.DescribableInfoBoxController.setEditableToggle (TextInputControl textInputControl) private
Definition at line 51 of file DescribableInfoBoxController.java.
Referenced by view.editor.DescribableInfoBoxController.initLabelInputSwitching().
void view.editor.DescribableInfoBoxController.setSubmitAction (BiConsumer< String, String > textChangedAction)
Definition at line 42 of file DescribableInfoBoxController.java.
Referenced by view.editor.EditorScreen.initInfoBox().
void view.editor.DescribableInfoBoxController.setText (String name, String description)
Definition at line 46 of file DescribableInfoBoxController.java.
Referenced by view.editor.EditorScreen.updateInfoBox().
Member Data Documentation
TextArea view.editor.DescribableInfoBoxController.descriptionTextArea private
Definition at line 33 of file DescribableInfoBoxController.java.
VBox view.editor.DescribableInfoBoxController.infoRoot private
Definition at line 29 of file DescribableInfoBoxController.java.
Referenced by view.editor.DescribableInfoBoxController.getRoot().
BiConsumer<String, String> view.editor.DescribableInfoBoxController.mySubmitConsumer private
Initial value:
= (String name, String description) -> {
    }
Definition at line 25 of file DescribableInfoBoxController.java.
TextField view.editor.DescribableInfoBoxController.nameTextField private
Definition at line 31 of file DescribableInfoBoxController.java.
final String view.editor.DescribableInfoBoxController.SUBMIT_KEY = "Update" static private
Definition at line 24 of file DescribableInfoBoxController.java.
Button view.editor.DescribableInfoBoxController.submitButton private
Definition at line 35 of file DescribableInfoBoxController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/DescribableInfoBoxController.java