voogasalad_TheException: editor.ProjectExplorerController Class Reference
editor.ProjectExplorerController Class Reference
Public Member Functions
void update (String game, List< String > campaignOrder, Map< String, List< String >> campaignLevelMap)
void setOnSelectionChanged (Consumer< String[]> selectionChangedConsumer)
void setOnLevelClicked (Consumer< String > levelClicked)
String[] getSelectedHierarchy ()
Node getRoot ()
void initialize ()
Private Member Functions
void initListeners ()
void itemClicked (MouseEvent mouseEvent)
Private Attributes
TreeView< String > myTreeView
ProjectExplorerTreeItem< String > myGameNode
ObservableList< TreeItem< String > > myCampaigns
List< ProjectExplorerTreeItem< String > > myLevels
Consumer< String[]> mySelectionChangedConsumer
Consumer< String > myLevelClickedConsumer
Detailed Description
Controller for the project explorer
Author
Jonathan Tseng
Definition at line 25 of file ProjectExplorerController.java.
Member Function Documentation
Node editor.ProjectExplorerController.getRoot ()
Implements view.GUIController.
Definition at line 123 of file ProjectExplorerController.java.
References editor.ProjectExplorerController.myTreeView.
String [] editor.ProjectExplorerController.getSelectedHierarchy ()
ugly code to get the hierarchy for the selected index
Returns
Definition at line 99 of file ProjectExplorerController.java.
Referenced by editor.ProjectExplorerController.initListeners(), and editor.EditorScreen.update().
void editor.ProjectExplorerController.initialize ()
Implements view.GUIController.
Definition at line 128 of file ProjectExplorerController.java.
References editor.ProjectExplorerController.initListeners().
void editor.ProjectExplorerController.initListeners () private
Definition at line 83 of file ProjectExplorerController.java.
References editor.ProjectExplorerController.getSelectedHierarchy(), and editor.ProjectExplorerController.itemClicked().
Referenced by editor.ProjectExplorerController.initialize().
void editor.ProjectExplorerController.itemClicked (MouseEvent mouseEvent) private
Definition at line 113 of file ProjectExplorerController.java.
References editor.ProjectExplorerTreeItem< T >.onClicked().
Referenced by editor.ProjectExplorerController.initListeners().
void editor.ProjectExplorerController.setOnLevelClicked (Consumer< String > levelClicked)
Definition at line 76 of file ProjectExplorerController.java.
Referenced by editor.EditorScreen.initProjectExplorer().
void editor.ProjectExplorerController.setOnSelectionChanged (Consumer< String[]> selectionChangedConsumer)
Definition at line 72 of file ProjectExplorerController.java.
Referenced by editor.EditorScreen.initProjectExplorer().
void editor.ProjectExplorerController.update (String game, List< String > campaignOrder, Map< String, List< String >> campaignLevelMap)
Definition at line 37 of file ProjectExplorerController.java.
References editor.ProjectExplorerTreeItem< T >.setAction().
Referenced by editor.EditorScreen.updateProjectExplorer().
Member Data Documentation
ObservableList<TreeItem<String> > editor.ProjectExplorerController.myCampaigns private
Definition at line 30 of file ProjectExplorerController.java.
ProjectExplorerTreeItem<String> editor.ProjectExplorerController.myGameNode private
Definition at line 29 of file ProjectExplorerController.java.
Consumer<String> editor.ProjectExplorerController.myLevelClickedConsumer private
Initial value:
= (String s) -> {
    }
Definition at line 34 of file ProjectExplorerController.java.
List<ProjectExplorerTreeItem<String> > editor.ProjectExplorerController.myLevels private
Definition at line 31 of file ProjectExplorerController.java.
Consumer<String[]> editor.ProjectExplorerController.mySelectionChangedConsumer private
Initial value:
= (String[] s) -> {
    }
Definition at line 32 of file ProjectExplorerController.java.
TreeView<String> editor.ProjectExplorerController.myTreeView private
Definition at line 28 of file ProjectExplorerController.java.
Referenced by editor.ProjectExplorerController.getRoot().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/ProjectExplorerController.java