voogasalad_TheException: test.request.RequestMediatorTest Class Reference
test.request.RequestMediatorTest Class Reference
Public Member Functions
void setup (int receiverCount, int pingPongMax) throws InvalidAddressException, AddressConflictException
void testSendToSelf () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
void testSendPingPong () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
void testAddressConflictException () throws InvalidAddressException, AddressConflictException
void testReceiverNotFoundException () throws InvalidAddressException, AddressConflictException, DeliveryException, ReceiverNotFoundException
void setup (int receiverCount, int pingPongMax) throws InvalidAddressException, AddressConflictException
void testSendToSelf () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
void testSendPingPong () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
void testAddressConflictException () throws InvalidAddressException, AddressConflictException
void testReceiverNotFoundException () throws InvalidAddressException, AddressConflictException, DeliveryException, ReceiverNotFoundException
void setup (int receiverCount, int pingPongMax) throws InvalidAddressException, AddressConflictException
void testSendToSelf () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
void testSendPingPong () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
void testAddressConflictException () throws InvalidAddressException, AddressConflictException
void testReceiverNotFoundException () throws InvalidAddressException, AddressConflictException, DeliveryException, ReceiverNotFoundException
Package Attributes
IForwarder myMediator
List< ReceiverTestStub > myReceivers
Detailed Description
Definition at line 18 of file RequestMediatorTest.java.
Member Function Documentation
void test.request.RequestMediatorTest.setup (int receiverCount, int pingPongMax) throws InvalidAddressException, AddressConflictException
Definition at line 23 of file RequestMediatorTest.java.
References vooga.request.forwarder.IForwarder.register().
Referenced by test.request.RequestMediatorTest.testAddressConflictException(), test.request.RequestMediatorTest.testReceiverNotFoundException(), test.request.RequestMediatorTest.testSendPingPong(), and test.request.RequestMediatorTest.testSendToSelf().
void test.request.RequestMediatorTest.setup (int receiverCount, int pingPongMax) throws InvalidAddressException, AddressConflictException
Definition at line 23 of file RequestMediatorTest.java.
void test.request.RequestMediatorTest.setup (int receiverCount, int pingPongMax) throws InvalidAddressException, AddressConflictException
Definition at line 24 of file RequestMediatorTest.java.
void test.request.RequestMediatorTest.testAddressConflictException () throws InvalidAddressException, AddressConflictException
Tests that adding two identical addresses actually creates the right exception
Definition at line 86 of file RequestMediatorTest.java.
References vooga.request.forwarder.AddressConflictException.conflictingAddress(), and test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testAddressConflictException () throws InvalidAddressException, AddressConflictException
Tests that adding two identical addresses actually creates the right exception
Definition at line 86 of file RequestMediatorTest.java.
References vooga.request.forwarder.AddressConflictException.conflictingAddress(), vooga.request.forwarder.IForwarder.register(), and test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testAddressConflictException () throws InvalidAddressException, AddressConflictException
Tests that adding two identical addresses actually creates the right exception
Definition at line 98 of file RequestMediatorTest.java.
References vooga.request.forwarder.AddressConflictException.conflictingAddress(), and test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testReceiverNotFoundException () throws InvalidAddressException, AddressConflictException, DeliveryException, ReceiverNotFoundException
Definition at line 107 of file RequestMediatorTest.java.
References vooga.request.forwarder.ReceiverNotFoundException.address(), and test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testReceiverNotFoundException () throws InvalidAddressException, AddressConflictException, DeliveryException, ReceiverNotFoundException
Definition at line 107 of file RequestMediatorTest.java.
References vooga.request.forwarder.ReceiverNotFoundException.address(), vooga.request.forwarder.IForwarder.forward(), and test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testReceiverNotFoundException () throws InvalidAddressException, AddressConflictException, DeliveryException, ReceiverNotFoundException
Definition at line 120 of file RequestMediatorTest.java.
References vooga.request.forwarder.ReceiverNotFoundException.address(), and test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testSendPingPong () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
Test if a message can be passed back and forth between two receivers in the correct order.
ReceiverTestStub contains special "ping pong" logic where if the special key "pingPong" is in the message, the ReceiverTestStub will send back a new message to the sender, incrementing a counter until it reaches a certain value.
Definition at line 57 of file RequestMediatorTest.java.
References test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testSendPingPong () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
Test if a message can be passed back and forth between two receivers in the correct order.
ReceiverTestStub contains special "ping pong" logic where if the special key "pingPong" is in the message, the ReceiverTestStub will send back a new message to the sender, incrementing a counter until it reaches a certain value.
Definition at line 57 of file RequestMediatorTest.java.
References vooga.request.forwarder.IForwarder.forward(), and test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testSendPingPong () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
Test if a message can be passed back and forth between two receivers in the correct order.
ReceiverTestStub contains special "ping pong" logic where if the special key "pingPong" is in the message, the ReceiverTestStub will send back a new message to the sender, incrementing a counter until it reaches a certain value.
Definition at line 62 of file RequestMediatorTest.java.
References test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testSendToSelf () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
Test sending to the same receiver
Definition at line 36 of file RequestMediatorTest.java.
References test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testSendToSelf () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
Test sending to the same receiver
Definition at line 36 of file RequestMediatorTest.java.
References vooga.request.forwarder.IForwarder.forward(), and test.request.RequestMediatorTest.setup().
void test.request.RequestMediatorTest.testSendToSelf () throws InvalidAddressException, AddressConflictException, ReceiverNotFoundException, DeliveryException
Test sending to the same receiver
Definition at line 39 of file RequestMediatorTest.java.
References test.request.RequestMediatorTest.setup().
Member Data Documentation
IForwarder test.request.RequestMediatorTest.myMediator package
Definition at line 20 of file RequestMediatorTest.java.
List< ReceiverTestStub > test.request.RequestMediatorTest.myReceivers package
Definition at line 21 of file RequestMediatorTest.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/build/build/src/test/request/RequestMediatorTest.java