voogasalad_TheException: editor.wizards.GameElementWizard Class Reference
editor.wizards.GameElementWizard Class Reference
Public Member Functions
void initialize ()
boolean checkCanSave ()
void updateData ()
Public Member Functions inherited from editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
WizardData getWizardData ()
void setErrorMesssage (String error)
void setStage (Stage s)
Stage getStage ()
Private Member Functions
void launchTriggerEditor ()
void launchStringAttributeEditor ()
void launchNumberAttributeEditor ()
void launchNestedWizard (String s)
Private Attributes
TextField name
Button trigger
Button stringAttribute
Button numberAttribute
Static Private Attributes
static final String NUM_ATTR_WIZARD
static final String STRING_ATTR_WIZARD
static final String TRIGGER_WIZARD = "/editor/wizards/guipanes/TriggerWizard.fxml"
Additional Inherited Members
Protected Member Functions inherited from editor.wizards.Wizard
void addToData (String key, String value)
void addWizardData (WizardData wizData)
void setDataName (String name)
Protected Attributes inherited from editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Detailed Description
Author
Joshua, Nishad
Definition at line 17 of file GameElementWizard.java.
Member Function Documentation
boolean editor.wizards.GameElementWizard.checkCanSave ()
Definition at line 79 of file GameElementWizard.java.
void editor.wizards.GameElementWizard.initialize ()
Binds all the listeners to the scene
Implements view.GUIController.
Definition at line 71 of file GameElementWizard.java.
References editor.wizards.GameElementWizard.launchNumberAttributeEditor(), editor.wizards.GameElementWizard.launchStringAttributeEditor(), and editor.wizards.GameElementWizard.launchTriggerEditor().
void editor.wizards.GameElementWizard.launchNestedWizard (String s) private
Definition at line 57 of file GameElementWizard.java.
References editor.wizards.Wizard.addWizardData(), editor.wizards.Wizard.getStage(), view.WizardUtility.loadWizard(), and editor.wizards.Wizard.setSubmit().
Referenced by editor.wizards.GameElementWizard.launchNumberAttributeEditor(), editor.wizards.GameElementWizard.launchStringAttributeEditor(), and editor.wizards.GameElementWizard.launchTriggerEditor().
void editor.wizards.GameElementWizard.launchNumberAttributeEditor () private
Launches a Nuumber Attribute Wizard
Definition at line 53 of file GameElementWizard.java.
References editor.wizards.GameElementWizard.launchNestedWizard().
Referenced by editor.wizards.GameElementWizard.initialize().
void editor.wizards.GameElementWizard.launchStringAttributeEditor () private
Launches a String Attribute Wizard
Definition at line 45 of file GameElementWizard.java.
References editor.wizards.GameElementWizard.launchNestedWizard().
Referenced by editor.wizards.GameElementWizard.initialize().
void editor.wizards.GameElementWizard.launchTriggerEditor () private
Launches a TriggerEditorWizard
Definition at line 37 of file GameElementWizard.java.
References editor.wizards.GameElementWizard.launchNestedWizard().
Referenced by editor.wizards.GameElementWizard.initialize().
void editor.wizards.GameElementWizard.updateData ()
Definition at line 84 of file GameElementWizard.java.
References editor.wizards.Wizard.addToData(), gamemodel.GameElementStateFactory.GAME_ELEMENT, gamemodel.GameElementStateFactory.NAME, and editor.wizards.Wizard.setDataName().
Member Data Documentation
TextField editor.wizards.GameElementWizard.name private
Definition at line 25 of file GameElementWizard.java.
final String editor.wizards.GameElementWizard.NUM_ATTR_WIZARD static private
Initial value:
=
            "/editor/wizards/guipanes/NumberAttributeWizard.fxml"
Definition at line 19 of file GameElementWizard.java.
Button editor.wizards.GameElementWizard.numberAttribute private
Definition at line 31 of file GameElementWizard.java.
final String editor.wizards.GameElementWizard.STRING_ATTR_WIZARD static private
Initial value:
=
            "/editor/wizards/guipanes/StringAttributeWizard.fxml"
Definition at line 21 of file GameElementWizard.java.
Button editor.wizards.GameElementWizard.stringAttribute private
Definition at line 29 of file GameElementWizard.java.
Button editor.wizards.GameElementWizard.trigger private
Definition at line 27 of file GameElementWizard.java.
final String editor.wizards.GameElementWizard.TRIGGER_WIZARD = "/editor/wizards/guipanes/TriggerWizard.fxml" static private
Definition at line 23 of file GameElementWizard.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/wizards/GameElementWizard.java