voogasalad_TheException: view.editor.ElementAccordionController Class Reference
view.editor.ElementAccordionController Class Reference
Classes
class ImageElementPair
Public Member Functions
void init ()
void modelUpdate ()
Node getRoot ()
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Private Member Functions
WizardData createWizardData (DrawableGameElementState state)
void editorChooseDrawableElement (String selection)
void editorChooseSelectableElement (String selection)
void attachStringProperties ()
void updateList (ElementDropDownController dropDownController, List< ImageElementPair > units)
Consumer< String > openSelectableGameElementWizard (WizardData oldData)
Consumer< String > openDrawableGameElementWizard (WizardData oldData)
void addNumberAttributes (GameElementWizard wiz)
void addStringAttributes (GameElementWizard wiz)
Private Attributes
Accordion elementAccordion
TitledPane terrainTitledPane
TitledPane unitTitledPane
ElementDropDownController terrainTitledPaneController
ElementDropDownController unitTitledPaneController
Static Private Attributes
static final String DRAWABLE_KEY = "Drawable"
static final String SELECTABLE_KEY = "Selectable"
Additional Inherited Members
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Detailed Description
Element Accordion Controller to handle communication between model and element accordion as well as to the titled panes in the accordion
Author
Jonathan Tseng
Definition at line 37 of file ElementAccordionController.java.
Member Function Documentation
void view.editor.ElementAccordionController.addNumberAttributes (GameElementWizard wiz) private
Definition at line 207 of file ElementAccordionController.java.
References view.editor.wizards.GameElementWizard.attachNumberAttributes(), model.MainModel.getGameUniverse(), model.GameUniverse.getNumericalAttributes(), and view.gui.GUIContainer.myMainModel.
Referenced by view.editor.ElementAccordionController.openDrawableGameElementWizard(), and view.editor.ElementAccordionController.openSelectableGameElementWizard().
void view.editor.ElementAccordionController.addStringAttributes (GameElementWizard wiz) private
Definition at line 213 of file ElementAccordionController.java.
References view.editor.wizards.GameElementWizard.attachStringAttributes(), model.MainModel.getGameUniverse(), model.GameUniverse.getStringAttributes(), and view.gui.GUIContainer.myMainModel.
Referenced by view.editor.ElementAccordionController.openDrawableGameElementWizard(), and view.editor.ElementAccordionController.openSelectableGameElementWizard().
void view.editor.ElementAccordionController.attachStringProperties () private
Definition at line 118 of file ElementAccordionController.java.
References view.editor.ElementDropDownController.bindGameElement(), view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.editor.ElementAccordionController.init().
WizardData view.editor.ElementAccordionController.createWizardData (DrawableGameElementState state) private
Definition at line 102 of file ElementAccordionController.java.
References model.data.WizardDataFactory.createWizardData().
Referenced by view.editor.ElementAccordionController.init().
void view.editor.ElementAccordionController.editorChooseDrawableElement (String selection) private
Definition at line 106 of file ElementAccordionController.java.
References view.gui.GUIContainer.myMainModel, and model.MainModel.setEditorChosenDrawable().
Referenced by view.editor.ElementAccordionController.init().
void view.editor.ElementAccordionController.editorChooseSelectableElement (String selection) private
Definition at line 112 of file ElementAccordionController.java.
References view.gui.GUIContainer.myMainModel, and model.MainModel.setEditorChosenSelectable().
Referenced by view.editor.ElementAccordionController.init().
Node view.editor.ElementAccordionController.getRoot ()
Implements view.gui.GUIController.
Definition at line 262 of file ElementAccordionController.java.
References view.editor.ElementAccordionController.elementAccordion.
void view.editor.ElementAccordionController.init ()
Definition at line 54 of file ElementAccordionController.java.
References view.editor.ElementAccordionController.attachStringProperties(), view.dialog.DialogBoxUtility.createMessageDialog(), view.editor.ElementAccordionController.createWizardData(), view.editor.ElementAccordionController.editorChooseDrawableElement(), view.editor.ElementAccordionController.editorChooseSelectableElement(), model.GameUniverse.getDrawableGameElementState(), model.MainModel.getGameUniverse(), model.GameUniverse.getSelectableGameElementState(), view.gui.GUIContainer.myMainModel, view.editor.ElementAccordionController.openDrawableGameElementWizard(), view.editor.ElementAccordionController.openSelectableGameElementWizard(), model.MainModel.removeDrawableGameElement(), model.MainModel.removeSelectableGameElement(), view.editor.ElementDropDownController.setButtonAction(), view.editor.ElementDropDownController.setDeleteConsumer(), view.editor.ElementDropDownController.setEditConsumer(), and view.editor.ElementDropDownController.setOnSelectionChanged().
void view.editor.ElementAccordionController.modelUpdate ()
Definition at line 220 of file ElementAccordionController.java.
References model.GameUniverse.getDrawableGameElementStates(), model.MainModel.getGameUniverse(), model.GameUniverse.getSelectableGameElementStates(), view.gui.GUIContainer.myMainModel, and view.editor.ElementAccordionController.updateList().
Consumer<String> view.editor.ElementAccordionController.openDrawableGameElementWizard (WizardData oldData) private
Definition at line 172 of file ElementAccordionController.java.
References view.editor.ElementAccordionController.addNumberAttributes(), view.editor.ElementAccordionController.addStringAttributes(), view.editor.wizards.Wizard.closeStage(), model.MainModel.createDrawableGameElementState(), view.gui.GUIPanePath.GAME_ELEMENT_WIZARD, model.GameUniverse.getDrawableGameElementStates(), model.MainModel.getGameUniverse(), model.data.WizardData.getType(), view.editor.wizards.GameElementWizard.launchForEdit(), view.gui.GUIContainer.myMainModel, model.data.WizardDataType.NAME, model.GameUniverse.removeDrawableGameElementState(), view.editor.wizards.Wizard.setSubmit(), and model.data.WizardType.UNSPECIFIED.
Referenced by view.editor.ElementAccordionController.init().
Consumer<String> view.editor.ElementAccordionController.openSelectableGameElementWizard (WizardData oldData) private
Definition at line 139 of file ElementAccordionController.java.
References view.editor.ElementAccordionController.addNumberAttributes(), view.editor.ElementAccordionController.addStringAttributes(), view.editor.wizards.Wizard.closeStage(), model.MainModel.createSelectableGameElementState(), view.gui.GUIPanePath.GAME_ELEMENT_WIZARD, model.MainModel.getGameUniverse(), model.GameUniverse.getSelectableGameElementStates(), model.data.WizardData.getType(), view.editor.wizards.GameElementWizard.launchForEdit(), view.gui.GUIContainer.myMainModel, model.data.WizardDataType.NAME, model.GameUniverse.removeSelectableGameElementState(), view.editor.wizards.Wizard.setSubmit(), and model.data.WizardType.UNSPECIFIED.
Referenced by view.editor.ElementAccordionController.init().
void view.editor.ElementAccordionController.updateList (ElementDropDownController dropDownController, List< ImageElementPair > units) private
Definition at line 131 of file ElementAccordionController.java.
References view.editor.ElementDropDownController.addElement(), and view.editor.ElementDropDownController.clearItems().
Referenced by view.editor.ElementAccordionController.modelUpdate().
Member Data Documentation
final String view.editor.ElementAccordionController.DRAWABLE_KEY = "Drawable" static private
Definition at line 39 of file ElementAccordionController.java.
Accordion view.editor.ElementAccordionController.elementAccordion private
Definition at line 43 of file ElementAccordionController.java.
Referenced by view.editor.ElementAccordionController.getRoot().
final String view.editor.ElementAccordionController.SELECTABLE_KEY = "Selectable" static private
Definition at line 40 of file ElementAccordionController.java.
TitledPane view.editor.ElementAccordionController.terrainTitledPane private
Definition at line 45 of file ElementAccordionController.java.
ElementDropDownController view.editor.ElementAccordionController.terrainTitledPaneController private
Definition at line 49 of file ElementAccordionController.java.
TitledPane view.editor.ElementAccordionController.unitTitledPane private
Definition at line 47 of file ElementAccordionController.java.
ElementDropDownController view.editor.ElementAccordionController.unitTitledPaneController private
Definition at line 51 of file ElementAccordionController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/ElementAccordionController.java