voogasalad_TheException: engine.stateManaging.GameLoop Class Reference
engine.stateManaging.GameLoop Class Reference
Public Member Functions
GameLoop (Level level, VisualManager visualManager, GameElementManager elementManager, ParticipantManager participantManager)
void setEditorLoop ()
void setRunnerLoop ()
void play ()
void pause ()
void stop ()
Static Public Attributes
static final Double framesPerSecond = 60.0
Private Member Functions
void updateRunner ()
void updateEditor ()
void startTimeline ()
void setLoop (KeyFrame frame)
Private Attributes
Level myCurrentLevel
GameElementManager myManager
ParticipantManager myParticipantManager
VisualManager myVisualManager
List< Computer< DrawableGameElement, DrawableGameElement > > myComputers
Timeline timeline
EventHandler< ActionEvent > oneFrameRunner
EventHandler< ActionEvent > oneFrameEditor
Detailed Description
The main loop for running the game, checking for collisions, and updating game entities
Author
Michael D., John L., Steve, Zach
Definition at line 30 of file GameLoop.java.
Constructor & Destructor Documentation
engine.stateManaging.GameLoop.GameLoop (Level level, VisualManager visualManager, GameElementManager elementManager, ParticipantManager participantManager)
Definition at line 56 of file GameLoop.java.
References engine.stateManaging.GameLoop.startTimeline().
Member Function Documentation
void engine.stateManaging.GameLoop.pause ()
Toggle Pause the game
Definition at line 170 of file GameLoop.java.
Referenced by engine.UI.RunnerInputManager.keyPressed(), and engine.Engine.pause().
void engine.stateManaging.GameLoop.play ()
Play the game
Definition at line 163 of file GameLoop.java.
Referenced by engine.Engine.play().
void engine.stateManaging.GameLoop.setEditorLoop ()
Definition at line 145 of file GameLoop.java.
References engine.stateManaging.GameLoop.oneFrameEditor, and engine.stateManaging.GameLoop.setLoop().
Referenced by engine.UI.EditorInputManager.EditorInputManager().
void engine.stateManaging.GameLoop.setLoop (KeyFrame frame) private
Definition at line 153 of file GameLoop.java.
Referenced by engine.stateManaging.GameLoop.setEditorLoop(), and engine.stateManaging.GameLoop.setRunnerLoop().
void engine.stateManaging.GameLoop.setRunnerLoop ()
Definition at line 149 of file GameLoop.java.
References engine.stateManaging.GameLoop.oneFrameRunner, and engine.stateManaging.GameLoop.setLoop().
Referenced by engine.UI.RunnerInputManager.RunnerInputManager(), and engine.stateManaging.GameLoop.startTimeline().
void engine.stateManaging.GameLoop.startTimeline () private
Start the timeline
Parameters
frame the keyframe for the timeline
Definition at line 139 of file GameLoop.java.
References engine.stateManaging.GameLoop.setRunnerLoop().
Referenced by engine.stateManaging.GameLoop.GameLoop().
void engine.stateManaging.GameLoop.stop ()
Stop the game
Definition at line 182 of file GameLoop.java.
Referenced by engine.Engine.update().
void engine.stateManaging.GameLoop.updateEditor () private
Update the states of all prominent elements and aspects of the game
Definition at line 120 of file GameLoop.java.
References engine.gameRepresentation.renderedRepresentation.Level.getTerrain(), engine.gameRepresentation.renderedRepresentation.Level.getUnits(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.update(), engine.visuals.VisualManager.update(), and engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
void engine.stateManaging.GameLoop.updateRunner () private
Update the states of all prominent elements and aspects of the game
Definition at line 71 of file GameLoop.java.
References engine.gameRepresentation.renderedRepresentation.Level.evaluateGoals(), engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), engine.gameRepresentation.renderedRepresentation.Level.getUnits(), model.state.gameelement.StateTags.IS_DEAD, engine.gameRepresentation.renderedRepresentation.Level.removeElement(), engine.UI.ParticipantManager.update(), engine.visuals.VisualManager.update(), and engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
Member Data Documentation
final Double engine.stateManaging.GameLoop.framesPerSecond = 60.0 static
Definition at line 31 of file GameLoop.java.
List<Computer<DrawableGameElement, DrawableGameElement> > engine.stateManaging.GameLoop.myComputers private
Initial value:
=
            new ArrayList<>()
Definition at line 38 of file GameLoop.java.
Level engine.stateManaging.GameLoop.myCurrentLevel private
Definition at line 32 of file GameLoop.java.
GameElementManager engine.stateManaging.GameLoop.myManager private
Definition at line 33 of file GameLoop.java.
ParticipantManager engine.stateManaging.GameLoop.myParticipantManager private
Definition at line 34 of file GameLoop.java.
VisualManager engine.stateManaging.GameLoop.myVisualManager private
Definition at line 36 of file GameLoop.java.
EventHandler<ActionEvent> engine.stateManaging.GameLoop.oneFrameEditor private
Initial value:
= new EventHandler<ActionEvent>() {
        @Override
        public void handle (ActionEvent evt) {
            updateEditor();
        }
    }
Definition at line 49 of file GameLoop.java.
Referenced by engine.stateManaging.GameLoop.setEditorLoop().
EventHandler<ActionEvent> engine.stateManaging.GameLoop.oneFrameRunner private
Initial value:
= new EventHandler<ActionEvent>() {
        @Override
        public void handle (ActionEvent evt) {
            updateRunner();
        }
    }
Definition at line 42 of file GameLoop.java.
Referenced by engine.stateManaging.GameLoop.setRunnerLoop().
Timeline engine.stateManaging.GameLoop.timeline private
Definition at line 40 of file GameLoop.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/stateManaging/GameLoop.java