voogasalad_TheException: engine.gameRepresentation.evaluatables.actions.EvaluatableFactory Class Reference
engine.gameRepresentation.evaluatables.actions.EvaluatableFactory Class Reference
Public Member Functions
EvaluatableFactory (EvaluatorFactory evaluatorFactory)
void setGameElementManager (GameElementManager manager)
void setParticipantManager (ParticipantManager manager)
Evaluatable<?> createAction (ActionWrapper wrapper) throws ClassNotFoundException, ActionCreationException
Private Attributes
EvaluatorFactory myEvaluatorFactory
GameElementManager myGameElementManager
ParticipantManager myParticipantManager
Detailed Description
A class that follows the factory pattern for creating actions from ActionWrappers.
Author
Zach, Michael R., John L.
Definition at line 18 of file EvaluatableFactory.java.
Constructor & Destructor Documentation
engine.gameRepresentation.evaluatables.actions.EvaluatableFactory.EvaluatableFactory (EvaluatorFactory evaluatorFactory)
Initialize the action factory
Definition at line 26 of file EvaluatableFactory.java.
Member Function Documentation
Evaluatable<?> engine.gameRepresentation.evaluatables.actions.EvaluatableFactory.createAction (ActionWrapper wrapper) throws ClassNotFoundException, ActionCreationException
Create an action from an action wrapper
Parameters
wrapper the action wrapper
Returns
the action
Exceptions
ClassNotFoundException if the class isn't found
ActionCreationException if the action can't be created
Definition at line 59 of file EvaluatableFactory.java.
Referenced by engine.elementFactories.GameElementFactory.generateActions().
void engine.gameRepresentation.evaluatables.actions.EvaluatableFactory.setGameElementManager (GameElementManager manager)
Set the factory of the game element manager
Parameters
manager
Definition at line 35 of file EvaluatableFactory.java.
Referenced by engine.Engine.initializeEvaluatableFactory().
void engine.gameRepresentation.evaluatables.actions.EvaluatableFactory.setParticipantManager (ParticipantManager manager)
Set the participant manager to be a given manager
Parameters
manager
Definition at line 44 of file EvaluatableFactory.java.
Referenced by engine.Engine.initializeEvaluatableFactory().
Member Data Documentation
EvaluatorFactory engine.gameRepresentation.evaluatables.actions.EvaluatableFactory.myEvaluatorFactory private
Definition at line 19 of file EvaluatableFactory.java.
GameElementManager engine.gameRepresentation.evaluatables.actions.EvaluatableFactory.myGameElementManager private
Definition at line 20 of file EvaluatableFactory.java.
ParticipantManager engine.gameRepresentation.evaluatables.actions.EvaluatableFactory.myParticipantManager private
Definition at line 21 of file EvaluatableFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/evaluatables/actions/EvaluatableFactory.java