voogasalad_TheException: engine.computers.pathingComputers.PathingComputer Class Reference
engine.computers.pathingComputers.PathingComputer Class Reference
Public Member Functions
PathingComputer (MapGrid grid)
List< Location > findPath (Location from, Location to)
double determineCost (Location from, Location to)
Private Member Functions
List< Location > optimizePath (List< Location > rawPath)
boolean pointsAreColinear (Location first, Location second, Location third)
double determineHeuristic (Location location)
double determinePathLength (Location from, Location to)
List< Location > computePath (Location from, Location to)
List< Location > reconstructPath (Location destination)
Private Attributes
MapGrid myGrid
PriorityQueue< Location > frontierLocations
HashMap< Location, Location > previousLocations
HashMap< Location, Double > minimumCosts
Location origin
List< Location > goals
Detailed Description
Implements the A* Search algorithm to figure out a path from a location to an objective.
Author
Steve
Definition at line 17 of file PathingComputer.java.
Constructor & Destructor Documentation
engine.computers.pathingComputers.PathingComputer.PathingComputer (MapGrid grid)
Definition at line 21 of file PathingComputer.java.
Member Function Documentation
List<Location> engine.computers.pathingComputers.PathingComputer.computePath (Location from, Location to) private
Definition at line 103 of file PathingComputer.java.
References engine.computers.pathingComputers.PathingComputer.determineCost(), engine.computers.pathingComputers.PathingComputer.determineHeuristic(), engine.computers.pathingComputers.MapGrid.getNeighbors(), engine.computers.pathingComputers.MapGrid.getNeighborsForXYCoordinate(), and engine.computers.pathingComputers.PathingComputer.reconstructPath().
Referenced by engine.computers.pathingComputers.PathingComputer.findPath().
double engine.computers.pathingComputers.PathingComputer.determineCost (Location from, Location to)
Definition at line 96 of file PathingComputer.java.
References engine.computers.pathingComputers.PathingComputer.determinePathLength().
Referenced by engine.computers.pathingComputers.PathingComputer.computePath().
double engine.computers.pathingComputers.PathingComputer.determineHeuristic (Location location) private
Naive implementation of heuristic function (for now) assuming constant traversal time for every square, allowing for 8-directional movement and weighting diagonals appropriately.
Parameters
location
starting location
goal
ending location
Returns
diagonal adjustment to Chebyshev distance
Definition at line 69 of file PathingComputer.java.
References engine.computers.pathingComputers.Location.getX(), and engine.computers.pathingComputers.Location.getY().
Referenced by engine.computers.pathingComputers.PathingComputer.computePath().
double engine.computers.pathingComputers.PathingComputer.determinePathLength (Location from, Location to) private
Naive implementation of distance function allowing for 8-directional movement and weighting diagonals appropriately.
Parameters
from
to
Returns
Definition at line 90 of file PathingComputer.java.
References engine.computers.pathingComputers.Location.getMovementSpeed(), engine.computers.pathingComputers.Location.getX(), and engine.computers.pathingComputers.Location.getY().
Referenced by engine.computers.pathingComputers.PathingComputer.determineCost().
List<Location> engine.computers.pathingComputers.PathingComputer.findPath (Location from, Location to)
Definition at line 25 of file PathingComputer.java.
References engine.computers.pathingComputers.PathingComputer.computePath(), and engine.computers.pathingComputers.PathingComputer.optimizePath().
Referenced by engine.stateManaging.GameElementManager.setSelectedUnitCommand().
List<Location> engine.computers.pathingComputers.PathingComputer.optimizePath (List< Location > rawPath) private
Definition at line 30 of file PathingComputer.java.
References engine.computers.pathingComputers.PathingComputer.pointsAreColinear().
Referenced by engine.computers.pathingComputers.PathingComputer.findPath().
boolean engine.computers.pathingComputers.PathingComputer.pointsAreColinear (Location first, Location second, Location third) private
Definition at line 41 of file PathingComputer.java.
References engine.computers.pathingComputers.Location.getX(), and engine.computers.pathingComputers.Location.getY().
Referenced by engine.computers.pathingComputers.PathingComputer.optimizePath().
List<Location> engine.computers.pathingComputers.PathingComputer.reconstructPath (Location destination) private
Definition at line 136 of file PathingComputer.java.
References engine.computers.pathingComputers.MapGrid.getNeighborsForXYCoordinate().
Referenced by engine.computers.pathingComputers.PathingComputer.computePath().
Member Data Documentation
PriorityQueue<Location> engine.computers.pathingComputers.PathingComputer.frontierLocations private
Definition at line 52 of file PathingComputer.java.
List<Location> engine.computers.pathingComputers.PathingComputer.goals private
Definition at line 56 of file PathingComputer.java.
HashMap<Location, Double> engine.computers.pathingComputers.PathingComputer.minimumCosts private
Definition at line 54 of file PathingComputer.java.
MapGrid engine.computers.pathingComputers.PathingComputer.myGrid private
Definition at line 19 of file PathingComputer.java.
Location engine.computers.pathingComputers.PathingComputer.origin private
Definition at line 55 of file PathingComputer.java.
HashMap<Location, Location> engine.computers.pathingComputers.PathingComputer.previousLocations private
Definition at line 53 of file PathingComputer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/computers/pathingComputers/PathingComputer.java