voogasalad_TheException: view.dialog.DialogBoxUtility Class Reference
view.dialog.DialogBoxUtility Class Reference
Static Public Member Functions
static DialogBoxController createDialogBox (String message, DialogChoice...choices)
static DialogBoxController createDialogBox (String message, Collection< DialogChoice > choices)
static DialogBoxController createMessageDialog (String message)
Static Private Attributes
static final String OKAY_KEY = "Okay"
static final Dimension SIZE = new Dimension(400, 200)
Detailed Description
Definition at line 17 of file DialogBoxUtility.java.
Member Function Documentation
static DialogBoxController view.dialog.DialogBoxUtility.createDialogBox (String message, DialogChoice... choices) static
Definition at line 22 of file DialogBoxUtility.java.
Referenced by view.dialog.DialogBoxUtility.createMessageDialog().
static DialogBoxController view.dialog.DialogBoxUtility.createDialogBox (String message, Collection< DialogChoice > choices) static
Definition at line 26 of file DialogBoxUtility.java.
References view.GUILoadStyleUtility.addScene(), view.dialog.DialogBoxController.attachInfo(), view.gui.GUIPanePath.DIALOG_BOX, view.GUILoadStyleUtility.generateGUIPane(), view.GUILoadStyleUtility.getInstance(), and view.dialog.DialogBoxController.getRoot().
static DialogBoxController view.dialog.DialogBoxUtility.createMessageDialog (String message) static
Definition at line 42 of file DialogBoxUtility.java.
References view.dialog.DialogBoxUtility.createDialogBox(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.GUILoadStyleUtility.addStyle(), view.editor.wizards.BoundsWizard.addXYPair(), view.editor.ElementAccordionController.attachStringProperties(), view.splash.SplashScreen.attachStringProperties(), view.gui.MenuBarController.attachTextProperties(), view.runner.LevelChooserController.attachTextProperties(), view.editor.wizards.GameElementWizard.attachTextProperties(), view.editor.EditorScreen.attachTextProperties(), view.editor.EditorScreen.createNewTab(), view.editor.wizards.Wizard.displayWarning(), view.editor.ElementAccordionController.init(), view.splash.SplashScreen.init(), view.editor.TabViewController.init(), view.editor.wizards.BoundsWizard.initialize(), view.runner.GameEndController.initialize(), view.runner.LevelChooserController.initialize(), view.editor.LevelTriggersViewController.initialize(), view.editor.EditorScreen.initInfoBox(), model.MainModel.loadGame(), view.splash.SplashScreen.loadGameAndSwitchScreen(), view.runner.RunnerScreen.playLevel(), view.runner.GameRunnerPaneController.setInputManager(), view.runner.GameRunnerPaneController.setLevel(), view.splash.SplashScreen.setUpButtons(), application.Main.start(), view.editor.EditorScreen.updateInfoBox(), view.editor.TabViewController.updateModelToSave(), and model.MainModel.updateSpritesAndMasks().
Member Data Documentation
final String view.dialog.DialogBoxUtility.OKAY_KEY = "Okay" static private
Definition at line 19 of file DialogBoxUtility.java.
final Dimension view.dialog.DialogBoxUtility.SIZE = new Dimension(400, 200) static private
Definition at line 20 of file DialogBoxUtility.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/dialog/DialogBoxUtility.java