voogasalad_TheException: game_engine.stateManaging.GameLoop Class Reference
game_engine.stateManaging.GameLoop Class Reference
Public Member Functions
GameLoop (String campaignName, Level level, VisualManager visualManager, MiniMap miniMap)
void startGameLoop ()
void play ()
void pause ()
void stop ()
boolean isCurrentLevel (LevelState level, String campaignName)
Static Public Attributes
static final Double framesPerSecond = 60.0
Private Member Functions
void addColisionEvents ()
KeyFrame start (Double framesPerSecond)
void update ()
void addPathsToRoot ()
void clearLinesFromRoot ()
void startTimeline (KeyFrame frame)
Private Attributes
String myCampaignName
Level myCurrentLevel
VisualManager myVisualManager
MiniMap myMiniMap
List< Computer > myComputers = new ArrayList<>()
Timeline timeline
List< Line > unitPaths
EventHandler< ActionEvent > oneFrame
Detailed Description
The main loop for running the game, checking for collisions, and updating game entities
Author
Michael D., John, Steve, Zach
Definition at line 40 of file GameLoop.java.
Constructor & Destructor Documentation
game_engine.stateManaging.GameLoop.GameLoop (String campaignName, Level level, VisualManager visualManager, MiniMap miniMap)
Definition at line 61 of file GameLoop.java.
References game_engine.stateManaging.GameLoop.addColisionEvents(), and game_engine.stateManaging.GameLoop.startGameLoop().
Member Function Documentation
void game_engine.stateManaging.GameLoop.addColisionEvents () private
Definition at line 74 of file GameLoop.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.getUnits(), game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.X_POS_STRING, game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.X_VEL, game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.Y_POS_STRING, and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.Y_VEL.
Referenced by game_engine.stateManaging.GameLoop.GameLoop().
void game_engine.stateManaging.GameLoop.addPathsToRoot () private
Definition at line 147 of file GameLoop.java.
References game_engine.visuals.VisualManager.getBackground(), and game_engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Referenced by game_engine.stateManaging.GameLoop.update().
void game_engine.stateManaging.GameLoop.clearLinesFromRoot () private
Definition at line 154 of file GameLoop.java.
References game_engine.visuals.VisualManager.getBackground().
Referenced by game_engine.stateManaging.GameLoop.update().
boolean game_engine.stateManaging.GameLoop.isCurrentLevel (LevelState level, String campaignName)
Definition at line 178 of file GameLoop.java.
References game_engine.gameRepresentation.stateRepresentation.DescribableState.getName(), and game_engine.gameRepresentation.renderedRepresentation.Level.getName().
Referenced by game_engine.Engine.updateGameLoop().
void game_engine.stateManaging.GameLoop.pause ()
Definition at line 170 of file GameLoop.java.
Referenced by game_engine.Engine.pause().
void game_engine.stateManaging.GameLoop.play ()
Definition at line 166 of file GameLoop.java.
Referenced by game_engine.Engine.play().
KeyFrame game_engine.stateManaging.GameLoop.start (Double framesPerSecond) private
Definition at line 115 of file GameLoop.java.
References game_engine.stateManaging.GameLoop.oneFrame.
Referenced by game_engine.stateManaging.GameLoop.startGameLoop().
void game_engine.stateManaging.GameLoop.startGameLoop ()
Definition at line 110 of file GameLoop.java.
References game_engine.stateManaging.GameLoop.start(), and game_engine.stateManaging.GameLoop.startTimeline().
Referenced by game_engine.stateManaging.GameLoop.GameLoop().
void game_engine.stateManaging.GameLoop.startTimeline (KeyFrame frame) private
Definition at line 159 of file GameLoop.java.
Referenced by game_engine.stateManaging.GameLoop.startGameLoop().
void game_engine.stateManaging.GameLoop.stop ()
Definition at line 174 of file GameLoop.java.
void game_engine.stateManaging.GameLoop.update () private
Definition at line 120 of file GameLoop.java.
References game_engine.stateManaging.GameLoop.addPathsToRoot(), game_engine.stateManaging.GameLoop.clearLinesFromRoot(), game_engine.gameRepresentation.renderedRepresentation.Level.getUnits(), game_engine.visuals.VisualManager.update(), and game_engine.visuals.MiniMap.updateMiniMap().
Member Data Documentation
final Double game_engine.stateManaging.GameLoop.framesPerSecond = 60.0 static
Definition at line 42 of file GameLoop.java.
String game_engine.stateManaging.GameLoop.myCampaignName private
Definition at line 44 of file GameLoop.java.
List<Computer> game_engine.stateManaging.GameLoop.myComputers = new ArrayList<>() private
Definition at line 49 of file GameLoop.java.
Level game_engine.stateManaging.GameLoop.myCurrentLevel private
Definition at line 45 of file GameLoop.java.
MiniMap game_engine.stateManaging.GameLoop.myMiniMap private
Definition at line 47 of file GameLoop.java.
VisualManager game_engine.stateManaging.GameLoop.myVisualManager private
Definition at line 46 of file GameLoop.java.
EventHandler<ActionEvent> game_engine.stateManaging.GameLoop.oneFrame private
Initial value:
= new EventHandler<ActionEvent>() {
        @Override
        public void handle (ActionEvent evt) {
            update();
        }
    }
Definition at line 54 of file GameLoop.java.
Referenced by game_engine.stateManaging.GameLoop.start().
Timeline game_engine.stateManaging.GameLoop.timeline private
Definition at line 50 of file GameLoop.java.
List<Line> game_engine.stateManaging.GameLoop.unitPaths private
Definition at line 52 of file GameLoop.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/stateManaging/GameLoop.java