voogasalad_TheException: game_engine.gameRepresentation.renderedRepresentation.GameElement Class Reference
game_engine.gameRepresentation.renderedRepresentation.GameElement Class Reference
Public Member Functions
GameElement (GameElementState gameElementState, Map< String, List< Evaluatable<?>>> conditionActionPairs, ResourceBundle actionTypesBundle)
Iterator< Evaluatable<?> > getActionsOfType (String actionType)
void addAction (String actionType, Evaluatable<?> action)
void removeAction (String actionID)
void update ()
Number getNumericalAttribute (String attributeTag)
void setNumericalAttribute (String attributeTag, Number attributeValue)
String getTextualAttribute (String attributeTag)
void setTextualAttribute (String attributeTag, String attributeValue)
void setPosition (double x, double y)
Protected Member Functions
void executeAllActions (String actionKey, ElementPair elementPair)
void executeAllActions (String actionKey)
Protected Attributes
ResourceBundle actionTypes
Private Member Functions
void createActionLists ()
void updateSelfDueToInternalFactors ()
Private Attributes
Map< String, List< Evaluatable<?> > > myActionLists
GameElementState myState
Detailed Description
A basic game element. Contains a state and a map strings to conditions and actions. Also contains an update method to update the element due to its internal state.
Author
Jonathan, Nishad, Rahul, Steve, Zach
Definition at line 24 of file GameElement.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.renderedRepresentation.GameElement.GameElement (GameElementState gameElementState, Map< String, List< Evaluatable<?>>> conditionActionPairs, ResourceBundle actionTypesBundle)
Create a game element with the given state
Parameters
gameElementState the state of the game element
Definition at line 40 of file GameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.createActionLists().
Member Function Documentation
void game_engine.gameRepresentation.renderedRepresentation.GameElement.addAction (String actionType, Evaluatable<?> action)
Add an action of the given type to the array of actions
Parameters
actionType the type of the action to be added
action the action to be added
Definition at line 90 of file GameElement.java.
Referenced by game_engine.gameRepresentation.evaluatables.evaluators.AddEvaluatableEvaluator< A, B >.evaluate(), and test.conditions.ConditionFunctionalityTest.testRemoveAction().
void game_engine.gameRepresentation.renderedRepresentation.GameElement.createActionLists () private
Ensure that lists are instantiated for all the possible action types of an element to protect against uninstantiated action entities at runtime.
Definition at line 53 of file GameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.GameElement.GameElement().
void game_engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions (String actionKey, ElementPair elementPair) protected
Execute all the actions in a given key's list. Given an element pair
Parameters
actionKey the key of the action set for which to execute all of the actions
ElementPair an element pair of the current object and any objects it might be interested in e.g. the current unit and a unit nearby it
Definition at line 135 of file GameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.getActionsOfType().
Referenced by game_engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions(), game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCurrentObjective(), game_engine.gameRepresentation.renderedRepresentation.GameElement.updateSelfDueToInternalFactors(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToSelection().
void game_engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions (String actionKey) protected
Execute all the actions in a given key's list given that there are no applicable elements for the action set.
Parameters
actionKey the key of the action set for which to execute all of the actions
Definition at line 145 of file GameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions().
Iterator<Evaluatable<?> > game_engine.gameRepresentation.renderedRepresentation.GameElement.getActionsOfType (String actionType)
Get an iterator of the actions with a given tag
Parameters
actionType the tag for the type of action
Returns
an iterator containing all the actions of the desired type
Definition at line 72 of file GameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions(), game_engine.gameRepresentation.renderedRepresentation.GameElement.removeAction(), test.conditions.ConditionFunctionalityTest.testAddAction(), test.conditions.ConditionFunctionalityTest.testRemoveAction(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToInteractingElementsSubset().
Number game_engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute (String attributeTag)
Get a numeric attribute contained by the game element
Parameters
attributTag the tag of the attribute of interest
Returns
the atribute's value or 0 if the attribute was not declared
Definition at line 155 of file GameElement.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getNumericalAttribute().
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.addElement(), game_engine.gameRepresentation.evaluatables.evaluators.CollisionEvaluator< A, B >.findGlobalBounds(), game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.initializeDisplay(), game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move(), test.conditions.ConditionFunctionalityTest.testValueAssignment(), and game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.updateImageLocation().
String game_engine.gameRepresentation.renderedRepresentation.GameElement.getTextualAttribute (String attributeTag)
Get a textual attribute contained by the game element
Parameters
attributeTag the tag of the attribute
Returns
the value of the attribute or "" if it does not exist
Definition at line 175 of file GameElement.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getTextualAttribute().
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getType().
void game_engine.gameRepresentation.renderedRepresentation.GameElement.removeAction (String actionID)
Remove the given action the array of actions
Parameters
actionID the identifier string for the action tree
See also
Evaluatable
Definition at line 102 of file GameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.getActionsOfType().
Referenced by game_engine.gameRepresentation.evaluatables.evaluators.RemoveEvaluatableEvaluator< A, B >.evaluate().
void game_engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute (String attributeTag, Number attributeValue)
Set a numeric attribute contained by the game element
Parameters
attributeTag the tag of the attribute
attributeValue the value of the attribute
Definition at line 165 of file GameElement.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setNumericalAttribute().
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move(), game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.SelectableGameElement(), game_engine.gameRepresentation.renderedRepresentation.GameElement.setPosition(), and test.conditions.ConditionFunctionalityTest.testCollisions().
void game_engine.gameRepresentation.renderedRepresentation.GameElement.setPosition (double x, double y)
Definition at line 189 of file GameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute().
Referenced by game_engine.elementFactories.GameElementFactory.createDrawableGameElement(), game_engine.elementFactories.GameElementFactory.createGameElement(), and game_engine.elementFactories.GameElementFactory.createSelectableGameElement().
void game_engine.gameRepresentation.renderedRepresentation.GameElement.setTextualAttribute (String attributeTag, String attributeValue)
Set the value of a textual attribute contained by the game element
Parameters
attributeTag the tag of the attribute
attributeValue the attribute's value
Definition at line 185 of file GameElement.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setTextualAttribute().
void game_engine.gameRepresentation.renderedRepresentation.GameElement.update ()
Update the element based on its internal state
Definition at line 116 of file GameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.updateSelfDueToInternalFactors().
void game_engine.gameRepresentation.renderedRepresentation.GameElement.updateSelfDueToInternalFactors () private
Update the game element due to actions that execute on its internal factors e.g. move the element based on its internal velocity parameters.
Definition at line 124 of file GameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions().
Referenced by game_engine.gameRepresentation.renderedRepresentation.GameElement.update().
Member Data Documentation
ResourceBundle game_engine.gameRepresentation.renderedRepresentation.GameElement.actionTypes protected
Definition at line 33 of file GameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCurrentObjective(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToSelection().
Map<String, List<Evaluatable<?> > > game_engine.gameRepresentation.renderedRepresentation.GameElement.myActionLists private
The action lists map is a map of action strings to lists of possible actions. For example, The String "Collision" might map to a list of actions that should be run whenever an element is dealing with a collision with another element whereas "Action1" might map to a list of actions that should be executed when an element's action button is clicked.
Definition at line 31 of file GameElement.java.
GameElementState game_engine.gameRepresentation.renderedRepresentation.GameElement.myState private
Definition at line 32 of file GameElement.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/renderedRepresentation/GameElement.java