voogasalad_TheException: game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T > Class Template Reference
game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T > Class Template Reference abstract
Public Member Functions
AttributeParameter (Class< T > type, String id, String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier)
AttributeParameter (Class< T > type, String attributeTag, String id, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier, String elementTag)
T evaluate (ElementPair elements)
boolean setValue (ElementPair elements, T attributeValue)
Public Member Functions inherited from game_engine.gameRepresentation.evaluatables.parameters.Parameter< T >
Parameter (Class< T > type, String id)
abstract T evaluate (ElementPair elements)
abstract boolean setValue (ElementPair elements, T value)
Public Member Functions inherited from game_engine.gameRepresentation.evaluatables.Evaluatable< T >
Evaluatable (Class< T > type, String id)
abstract T evaluate (ElementPair elements)
T evaluate ()
boolean setValue (ElementPair elements, T value)
boolean setValue (T value)
Class< T > getType ()
String getID ()
Protected Member Functions
String getTag ()
abstract T getValue (List< GameElement > elements, String attributeTag)
abstract boolean setValue (List< GameElement > elements, String attributeTag, T attributeValue)
Private Member Functions
List< GameElement > getElementsOfInterest (GameElementManager elementManager, ElementPair elementPair, String elementTag)
Private Attributes
String myAttributeTag
String myElementTag
ObjectOfInterestIdentifier myObjectIdentifier
GameElementManager myManager
Detailed Description
An evaluator parameter that extracts a parameter contained within an object
Author
Zach
Definition at line 16 of file AttributeParameter.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.AttributeParameter (Class< T > type, String id, String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier)
Make an attribute parameter targeting parameters with a given tag.
Parameters
attributeTag the tag of the attribute that will be targeted
manager the GameElementManager containing all the game elements
objectOfInterestIdentifier an identifier that will return an object of interest
Definition at line 33 of file AttributeParameter.java.
game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.AttributeParameter (Class< T > type, String attributeTag, String id, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier, String elementTag)
Specify an attribute parameter with an element tag. Used for referencing global variables
Parameters
attributeTag
manager
objectOfInterestIdentifier
elementTag
Definition at line 52 of file AttributeParameter.java.
Member Function Documentation
T game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.evaluate (ElementPair elements)
Definition at line 93 of file AttributeParameter.java.
List<GameElement> game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.getElementsOfInterest (GameElementManager elementManager, ElementPair elementPair, String elementTag) private
Get the elements of interest from the object of interest identifier contained within the AttributeParameter
Parameters
elementManager the object holding all the current game elements
elementPair a pair of the game elements that the player is currently interested in
elementTag the tag of an element that the player is interested. Optional. Only really used for globals
Returns
Definition at line 84 of file AttributeParameter.java.
Referenced by game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.evaluate(), and game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.setValue().
String game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.getTag () protected
Get the tag for the attribute this references
Returns
the attribute tag
Definition at line 66 of file AttributeParameter.java.
abstract T game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.getValue (List< GameElement > elements, String attributeTag) abstract protected
Get the desired value given the current list of elements of interest.
Parameters
elements the elements whose values need to be examined
attributeTag the tag for the attribute that is being referenced by the parameter
Returns
the value of the parameter that is being requested
Referenced by game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.evaluate().
boolean game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.setValue (ElementPair elements, T attributeValue)
Definition at line 113 of file AttributeParameter.java.
Referenced by game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.setValue().
abstract boolean game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.setValue (List< GameElement > elements, String attributeTag, T attributeValue) abstract protected
Set the referenced value given the current list of elements of interest
Parameters
elements the current list of elements of interest
attributeTag the tag for the attribute to set
attributeValue the new value of the attribute
Member Data Documentation
String game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.myAttributeTag private
Definition at line 18 of file AttributeParameter.java.
Referenced by game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< Number >.getTag().
String game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.myElementTag private
Definition at line 19 of file AttributeParameter.java.
GameElementManager game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.myManager private
Definition at line 21 of file AttributeParameter.java.
ObjectOfInterestIdentifier game_engine.gameRepresentation.evaluatables.parameters.AttributeParameter< T >.myObjectIdentifier private
Definition at line 20 of file AttributeParameter.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/evaluatables/parameters/AttributeParameter.java