voogasalad_TheException: game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter Class Reference
game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter Class Reference abstract
Public Member Functions
AttributeParameter (String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier)
AttributeParameter (String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier, String elementTag)
String getValue (ElementPair elements)
boolean setValue (ElementPair elements, String attributeValue)
Protected Member Functions
String getTag ()
abstract String getValue (List< GameElementState > elements, String attributeTag)
abstract boolean setValue (List< GameElementState > elements, String attributeTag, String attributeValue)
Private Member Functions
List< GameElementState > getElementsOfInterest (GameElementManager elementManager, ElementPair elementPair, String elementTag)
Private Attributes
String myAttributeTag
String myElementTag
ObjectOfInterestIdentifier myObjectIdentifier
GameElementManager myManager
Detailed Description
An evaluator parameter that extracts a parameter contained within an object
Author
Zach
Definition at line 16 of file AttributeParameter.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.AttributeParameter (String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier)
Make an attribute parameter targeting parameters with a given tag.
Parameters
attributeTag the tag of the attribute that will be targeted
manager the GameElementManager containing all the game elements
objectOfInterestIdentifier an identifier that will return an object of interest
Definition at line 30 of file AttributeParameter.java.
game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.AttributeParameter (String attributeTag, GameElementManager manager, ObjectOfInterestIdentifier objectOfInterestIdentifier, String elementTag)
Specify an attribute parameter with an element tag. Used for referencing global variables
Parameters
attributeTag
manager
objectOfInterestIdentifier
elementTag
Definition at line 47 of file AttributeParameter.java.
Member Function Documentation
List<GameElementState> game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.getElementsOfInterest (GameElementManager elementManager, ElementPair elementPair, String elementTag) private
Get the elements of interest from the object of interest identifier contained within the AttributeParameter
Parameters
elementManager the object holding all the current game elements
elementPair a pair of the game elements that the player is currently interested in
elementTag the tag of an element that the player is interested. Optional. Only really used for globals
Returns
Definition at line 75 of file AttributeParameter.java.
References game_engine.gameRepresentation.conditions.evaluators.parameters.objectIdentifiers.ObjectOfInterestIdentifier.getElementOfInterest().
Referenced by game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.getValue(), and game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.setValue().
String game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.getTag () protected
Get the tag for the attribute this references
Returns
the attribute tag
Definition at line 60 of file AttributeParameter.java.
References game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.myAttributeTag.
String game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.getValue (ElementPair elements)
Given an element pair, extract required parameter and return it as a string
Parameters
elements the element pair to act on
Returns
the value of the evaluator
Implements game_engine.gameRepresentation.conditions.evaluators.parameters.Parameter.
Definition at line 82 of file AttributeParameter.java.
References game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.getElementsOfInterest().
abstract String game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.getValue (List< GameElementState > elements, String attributeTag) abstract protected
Get the desired value given the current list of elements of interest.
Parameters
elements the elements whose values need to be examined
attributeTag the tag for the attribute that is being referenced by the parameter
Returns
the value of the parameter that is being requested
boolean game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.setValue (ElementPair elements, String value)
Sets the value of the given parameter. Note: modifies the actual attribute of the object being referenced. This is intended.
Parameters
elements the element pair to act on
value the value to set
Returns
true if value setting was successful. False if value could not be found
Implements game_engine.gameRepresentation.conditions.evaluators.parameters.Parameter.
Definition at line 96 of file AttributeParameter.java.
References game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.getElementsOfInterest().
abstract boolean game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.setValue (List< GameElementState > elements, String attributeTag, String attributeValue) abstract protected
Set the referenced value given the current list of elements of interest
Parameters
elements the current list of elements of interest
attributeTag the tag for the attribute to set
attributeValue the new value of the attribute
Member Data Documentation
String game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.myAttributeTag private
Definition at line 18 of file AttributeParameter.java.
Referenced by game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.getTag().
String game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.myElementTag private
Definition at line 19 of file AttributeParameter.java.
GameElementManager game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.myManager private
Definition at line 21 of file AttributeParameter.java.
ObjectOfInterestIdentifier game_engine.gameRepresentation.conditions.evaluators.parameters.AttributeParameter.myObjectIdentifier private
Definition at line 20 of file AttributeParameter.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/conditions/evaluators/parameters/AttributeParameter.java