voogasalad_TheException: view.GUIContainer Class Reference
view.GUIContainer Class Reference abstract
Public Member Functions
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
abstract void update ()
Public Member Functions inherited from view.GUIController
abstract Node getRoot ()
Protected Member Functions
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes
MainModel myMainModel
Private Member Functions
void checkAndCreateChildContainers ()
Private Attributes
List< GUIContainer > myChildContainers
Detailed Description
Superclass for any GUI pane that holds sub guipanes and needs to delegate info to its subpanes. Handles updating from the model and delegating updates to its subpanes
Author
Jonathan Tseng
Definition at line 19 of file GUIContainer.java.
Member Function Documentation
void view.GUIContainer.attachChildContainers (GUIContainer... children) protected
Definition at line 40 of file GUIContainer.java.
Referenced by editor.EditorScreen.createNewTab(), and editor.EditorScreen.init().
void view.GUIContainer.checkAndCreateChildContainers () private
Definition at line 60 of file GUIContainer.java.
void view.GUIContainer.clearChildContainers () protected
Definition at line 48 of file GUIContainer.java.
Referenced by editor.EditorScreen.createNewTab().
abstract void view.GUIContainer.init () abstract protected
Referenced by view.GUIContainer.initialize().
final void view.GUIContainer.initialize ()
Implements view.GUIController.
Definition at line 26 of file GUIContainer.java.
References view.GUIContainer.init().
void view.GUIContainer.setModel (MainModel model)
Definition at line 33 of file GUIContainer.java.
Referenced by view.MainView.launchScreen().
final void view.GUIContainer.update (Observable o, Object arg)
Definition at line 53 of file GUIContainer.java.
References view.GUIContainer.update().
Referenced by view.MainView.launchScreen(), and view.MainView.update().
abstract void view.GUIContainer.update () abstract
Referenced by view.GUIContainer.update().
Member Data Documentation
List<GUIContainer> view.GUIContainer.myChildContainers private
Definition at line 22 of file GUIContainer.java.
MainModel view.GUIContainer.myMainModel protected
Definition at line 21 of file GUIContainer.java.
Referenced by editor.EditorMenuBarController.initFileMenu(), editor.EditorScreen.initInfoBox(), editor.TabViewController.launchNestedWizard(), editor.EditorMenuBarController.onNewCampaignClick(), editor.EditorMenuBarController.onNewLevelClick(), editor.ElementAccordionController.openGameElementWizard(), view.SplashScreen.setUpButtons(), editor.EditorScreen.updateAccordion(), editor.EditorScreen.updateInfoBox(), editor.TabViewController.updateLevelTriggersView(), and editor.EditorScreen.updateProjectExplorer().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/GUIContainer.java