voogasalad_TheException: view.editor.TabViewController Class Reference
view.editor.TabViewController Class Reference
Classes
class TriggerPair
Public Member Functions
boolean isLevel (LevelIdentifier levelID)
void updateModelToSave ()
void setLevel (LevelIdentifier levelID) throws LevelNotFoundException, CampaignNotFoundException
void modelUpdate ()
void init ()
Node getRoot ()
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Private Member Functions
Consumer< Consumer< WizardData > > launchNestedWizard ()
void addNumberAttributes (Wizard wiz)
void startLevel ()
void updateLevelTriggersView ()
ActionOptions getByClassName (String className)
void initToggle ()
BiConsumer< Integer, String > modifyGoals ()
WizardData recreateWizardData (String[] oldStrings)
Consumer< WizardData > createInternalConsumer (Integer position, Wizard wiz)
String extractParamString (String[] oldStrings)
String removeEnds (String value)
Consumer< Integer > deleteGoal ()
Private Attributes
VBox levelTrigger
LevelTriggersViewController levelTriggerController
StackPane gameRunnerPane
GameRunnerPaneController gameRunnerPaneController
BorderPane tabPane
Button resetButton
ToggleButton controllerToggle
VBox vbox
LevelState myLevel
Static Private Attributes
static final Dimension WIZARD_SIZE = new Dimension(400, 600)
static final String EDITOR_INPUT_KEY = "EditorInput"
static final String RUNNER_INPUT_KEY = "RunnerInput"
static final String RESET_KEY = "Reset"
Additional Inherited Members
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Detailed Description
Author
Jonathan Tseng
Nishad Agrawal
Definition at line 46 of file TabViewController.java.
Member Function Documentation
void view.editor.TabViewController.addNumberAttributes (Wizard wiz) private
Definition at line 101 of file TabViewController.java.
References model.MainModel.getGameUniverse(), model.GameUniverse.getNumericalAttributes(), view.editor.wizards.Wizard.loadGlobalValues(), and view.gui.GUIContainer.myMainModel.
Referenced by view.editor.TabViewController.launchNestedWizard().
Consumer<WizardData> view.editor.TabViewController.createInternalConsumer (Integer position, Wizard wiz) private
Definition at line 236 of file TabViewController.java.
References model.data.WizardDataType.ACTION, model.data.WizardDataType.ACTION_PARAMETERS, model.data.WizardDataType.ACTIONTYPE, view.editor.wizards.Wizard.closeStage(), model.state.LevelState.getGoals(), and view.editor.TabViewController.updateLevelTriggersView().
Referenced by view.editor.TabViewController.modifyGoals().
Consumer<Integer> view.editor.TabViewController.deleteGoal () private
Definition at line 273 of file TabViewController.java.
References view.gui.GUIContainer.myMainModel, and model.MainModel.removeGoal().
Referenced by view.editor.TabViewController.init().
String view.editor.TabViewController.extractParamString (String[] oldStrings) private
Definition at line 262 of file TabViewController.java.
References view.editor.TabViewController.removeEnds().
Referenced by view.editor.TabViewController.recreateWizardData().
ActionOptions view.editor.TabViewController.getByClassName (String className) private
Definition at line 152 of file TabViewController.java.
Referenced by view.editor.TabViewController.updateLevelTriggersView().
Node view.editor.TabViewController.getRoot ()
Implements view.gui.GUIController.
Definition at line 283 of file TabViewController.java.
References view.editor.TabViewController.tabPane.
Referenced by view.editor.EditorScreen.createNewTab().
void view.editor.TabViewController.init ()
Definition at line 172 of file TabViewController.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), view.editor.TabViewController.deleteGoal(), util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), view.editor.TabViewController.initToggle(), view.editor.TabViewController.launchNestedWizard(), view.editor.TabViewController.modifyGoals(), view.editor.LevelTriggersViewController.setButtonAction(), view.editor.LevelTriggersViewController.setDeleteAction(), view.editor.LevelTriggersViewController.setSelectedAction(), and view.editor.TabViewController.startLevel().
void view.editor.TabViewController.initToggle () private
Definition at line 188 of file TabViewController.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), and view.runner.GameRunnerPaneController.setInputManager().
Referenced by view.editor.TabViewController.init().
boolean view.editor.TabViewController.isLevel (LevelIdentifier levelID)
Definition at line 73 of file TabViewController.java.
References model.state.LevelIdentifier.equals(), and model.state.LevelState.getIdentifier().
Consumer<Consumer<WizardData> > view.editor.TabViewController.launchNestedWizard () private
Definition at line 86 of file TabViewController.java.
References view.gui.GUIPanePath.ACTION_WIZARD, view.editor.TabViewController.addNumberAttributes(), view.editor.wizards.Wizard.closeStage(), model.MainModel.createGoal(), view.editor.wizards.WizardUtility.loadWizard(), view.gui.GUIContainer.myMainModel, and view.editor.wizards.Wizard.setSubmit().
Referenced by view.editor.TabViewController.init().
void view.editor.TabViewController.modelUpdate ()
Definition at line 122 of file TabViewController.java.
References view.editor.TabViewController.updateLevelTriggersView().
Referenced by view.editor.EditorScreen.createNewTab().
BiConsumer<Integer, String> view.editor.TabViewController.modifyGoals () private
Definition at line 212 of file TabViewController.java.
References view.gui.GUIPanePath.ACTION_WIZARD, view.editor.TabViewController.createInternalConsumer(), view.editor.wizards.Wizard.launchForEdit(), view.editor.wizards.WizardUtility.loadWizard(), view.editor.TabViewController.recreateWizardData(), view.editor.wizards.Wizard.setSubmit(), and view.editor.TabViewController.updateLevelTriggersView().
Referenced by view.editor.TabViewController.init().
WizardData view.editor.TabViewController.recreateWizardData (String[] oldStrings) private
Definition at line 227 of file TabViewController.java.
References model.data.WizardDataType.ACTION, model.data.WizardDataType.ACTION_PARAMETERS, model.data.WizardDataType.ACTIONTYPE, model.data.WizardData.addDataPair(), and view.editor.TabViewController.extractParamString().
Referenced by view.editor.TabViewController.modifyGoals().
String view.editor.TabViewController.removeEnds (String value) private
Definition at line 269 of file TabViewController.java.
Referenced by view.editor.TabViewController.extractParamString().
void view.editor.TabViewController.setLevel (LevelIdentifier levelID) throws LevelNotFoundException, CampaignNotFoundException
Definition at line 107 of file TabViewController.java.
References view.gui.GUIContainer.attachChildContainers(), model.MainModel.getLevel(), view.gui.GUIContainer.myMainModel, view.runner.GameRunnerPaneController.setOnDone(), and view.editor.TabViewController.startLevel().
Referenced by view.editor.EditorScreen.createNewTab().
void view.editor.TabViewController.startLevel () private
Definition at line 116 of file TabViewController.java.
References view.runner.GameRunnerPaneController.setLevel().
Referenced by view.editor.TabViewController.init(), and view.editor.TabViewController.setLevel().
void view.editor.TabViewController.updateLevelTriggersView () private
This is the code required to filter the goals by type within the level goals view
Definition at line 130 of file TabViewController.java.
References view.editor.TabViewController.getByClassName(), model.state.LevelState.getGoals(), and view.editor.LevelTriggersViewController.updateTriggerList().
Referenced by view.editor.TabViewController.createInternalConsumer(), view.editor.TabViewController.modelUpdate(), and view.editor.TabViewController.modifyGoals().
void view.editor.TabViewController.updateModelToSave ()
Definition at line 77 of file TabViewController.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), model.state.LevelState.getIdentifier(), view.runner.GameRunnerPaneController.getLevelState(), view.gui.GUIContainer.myMainModel, and model.MainModel.setLevel().
Member Data Documentation
ToggleButton view.editor.TabViewController.controllerToggle private
Definition at line 67 of file TabViewController.java.
final String view.editor.TabViewController.EDITOR_INPUT_KEY = "EditorInput" static private
Definition at line 50 of file TabViewController.java.
StackPane view.editor.TabViewController.gameRunnerPane private
Definition at line 59 of file TabViewController.java.
GameRunnerPaneController view.editor.TabViewController.gameRunnerPaneController private
Definition at line 61 of file TabViewController.java.
VBox view.editor.TabViewController.levelTrigger private
Definition at line 55 of file TabViewController.java.
LevelTriggersViewController view.editor.TabViewController.levelTriggerController private
Definition at line 57 of file TabViewController.java.
LevelState view.editor.TabViewController.myLevel private
Definition at line 71 of file TabViewController.java.
final String view.editor.TabViewController.RESET_KEY = "Reset" static private
Definition at line 52 of file TabViewController.java.
Button view.editor.TabViewController.resetButton private
Definition at line 65 of file TabViewController.java.
final String view.editor.TabViewController.RUNNER_INPUT_KEY = "RunnerInput" static private
Definition at line 51 of file TabViewController.java.
BorderPane view.editor.TabViewController.tabPane private
Definition at line 63 of file TabViewController.java.
Referenced by view.editor.TabViewController.getRoot().
VBox view.editor.TabViewController.vbox private
Definition at line 69 of file TabViewController.java.
final Dimension view.editor.TabViewController.WIZARD_SIZE = new Dimension(400, 600) static private
Definition at line 48 of file TabViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/TabViewController.java