voogasalad_TheException: view.GUILoadStyleUtility Class Reference
view.GUILoadStyleUtility Class Reference
Public Member Functions
void setScene (Scene scene)
void setStyle (String...cssFiles)
void addStyle (String...cssFiles)
Static Public Member Functions
static synchronized GUILoadStyleUtility getInstance ()
static GUIController generateGUIPane (String filePath)
Private Member Functions
GUILoadStyleUtility ()
Private Attributes
Scene myScene
Static Private Attributes
static GUILoadStyleUtility myOnlyInstance
Detailed Description
A class for the generation and styling of GUIPanes based on FXML files
Author
Jonathan Tseng
Nishad Agrawal
Joshua Miller
Definition at line 15 of file GUILoadStyleUtility.java.
Constructor & Destructor Documentation
view.GUILoadStyleUtility.GUILoadStyleUtility () private
private constructor for the utility
Definition at line 24 of file GUILoadStyleUtility.java.
Referenced by view.GUILoadStyleUtility.getInstance().
Member Function Documentation
void view.GUILoadStyleUtility.addStyle (String... cssFiles)
Definition at line 78 of file GUILoadStyleUtility.java.
Referenced by view.MainView.MainView(), and view.GUILoadStyleUtility.setStyle().
static GUIController view.GUILoadStyleUtility.generateGUIPane (String filePath) static
static method to load an FXML file returns the GUIController associated with the FXML file
Parameters
filePath
Returns
Definition at line 56 of file GUILoadStyleUtility.java.
Referenced by editor.EditorScreen.createNewTab(), view.MainView.launchScreen(), and view.WizardUtility.loadWizard().
static synchronized GUILoadStyleUtility view.GUILoadStyleUtility.getInstance () static
returns the single instance of the utility in the program
Returns
Definition at line 32 of file GUILoadStyleUtility.java.
References view.GUILoadStyleUtility.GUILoadStyleUtility(), and view.GUILoadStyleUtility.myOnlyInstance.
Referenced by view.MainView.MainView().
void view.GUILoadStyleUtility.setScene (Scene scene)
sets the scene
Parameters
scene
Definition at line 44 of file GUILoadStyleUtility.java.
Referenced by view.MainView.MainView().
void view.GUILoadStyleUtility.setStyle (String... cssFiles)
sets the style of the scene using
Parameters
cssFiles
Definition at line 73 of file GUILoadStyleUtility.java.
References view.GUILoadStyleUtility.addStyle().
Member Data Documentation
GUILoadStyleUtility view.GUILoadStyleUtility.myOnlyInstance static private
Definition at line 17 of file GUILoadStyleUtility.java.
Referenced by view.GUILoadStyleUtility.getInstance().
Scene view.GUILoadStyleUtility.myScene private
Definition at line 19 of file GUILoadStyleUtility.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/GUILoadStyleUtility.java