voogasalad_TheException: editor.EditorScreen Class Reference
editor.EditorScreen Class Reference
Classes
class ImageElementPair
Public Member Functions
Node getRoot ()
void init ()
void update ()
Public Member Functions inherited from view.GUIScreen
void attachSceneHandler (MainView mainView)
Public Member Functions inherited from view.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
abstract void update ()
Private Member Functions
void initProjectExplorer ()
void initInfoBox ()
void updateInfoBox (String[] selection)
void initTabs ()
void launchTab (String level)
void createNewTab (String level)
void tabChanged (ObservableValue<?extends Tab > observable, Tab oldTab, Tab newTab)
void updateAccordion ()
void updateProjectExplorer ()
void updateTabViewControllers ()
Private Attributes
TabPane tabPane
TreeView< String > projectExplorer
ProjectExplorerController projectExplorerController
VBox gameInfoBox
DescribableInfoBoxController gameInfoBoxController
Parent editorMenuBar
EditorMenuBarController editorMenuBarController
BorderPane editorRoot
Button newGameElement
Button newTerrain
Button save
Accordion levelElementAccordion
ElementAccordionController levelElementAccordionController
HashMap< String, TabViewController > myTabViewControllers
Tab myCurrentTab
Additional Inherited Members
Protected Member Functions inherited from view.GUIScreen
void switchScreen (ViewScreen screen)
Protected Member Functions inherited from view.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.GUIContainer
MainModel myMainModel
Detailed Description
Screen for the Editor. Holds many sub-GUI panes
Author
Jonathan Tseng
Nishad Agrawal
Definition at line 40 of file EditorScreen.java.
Member Function Documentation
void editor.EditorScreen.createNewTab (String level) private
Definition at line 133 of file EditorScreen.java.
References view.GUIContainer.attachChildContainers(), view.GUIContainer.clearChildContainers(), view.GUILoadStyleUtility.generateGUIPane(), and editor.TabViewController.getRoot().
Referenced by editor.EditorScreen.launchTab().
Node editor.EditorScreen.getRoot ()
Implements view.GUIController.
Definition at line 73 of file EditorScreen.java.
References editor.EditorScreen.editorRoot.
void editor.EditorScreen.init ()
Definition at line 155 of file EditorScreen.java.
References view.GUIContainer.attachChildContainers(), editor.EditorScreen.initInfoBox(), editor.EditorScreen.initProjectExplorer(), and editor.EditorScreen.initTabs().
void editor.EditorScreen.initInfoBox () private
Definition at line 87 of file EditorScreen.java.
References view.GUIContainer.myMainModel, editor.DescribableInfoBoxController.setSubmitAction(), and gamemodel.MainModel.updateDescribableState().
Referenced by editor.EditorScreen.init().
void editor.EditorScreen.initProjectExplorer () private
Definition at line 77 of file EditorScreen.java.
References editor.EditorScreen.launchTab(), editor.ProjectExplorerController.setOnLevelClicked(), editor.ProjectExplorerController.setOnSelectionChanged(), and editor.EditorScreen.updateInfoBox().
Referenced by editor.EditorScreen.init().
void editor.EditorScreen.initTabs () private
Definition at line 114 of file EditorScreen.java.
References editor.EditorScreen.tabChanged().
Referenced by editor.EditorScreen.init().
void editor.EditorScreen.launchTab (String level) private
Definition at line 121 of file EditorScreen.java.
References editor.EditorScreen.createNewTab().
Referenced by editor.EditorScreen.initProjectExplorer().
void editor.EditorScreen.tabChanged (ObservableValue<?extends Tab > observable, Tab oldTab, Tab newTab) private
Definition at line 150 of file EditorScreen.java.
Referenced by editor.EditorScreen.initTabs().
void editor.EditorScreen.update ()
Definition at line 164 of file EditorScreen.java.
References editor.ProjectExplorerController.getSelectedHierarchy(), editor.EditorScreen.updateAccordion(), editor.EditorScreen.updateInfoBox(), editor.EditorScreen.updateProjectExplorer(), and editor.EditorScreen.updateTabViewControllers().
Referenced by editor.EditorScreen.updateTabViewControllers().
void editor.EditorScreen.updateAccordion () private
Definition at line 173 of file EditorScreen.java.
References gamemodel.GameUniverse.getDrawableGameElementStates(), gamemodel.MainModel.getGameUniverse(), view.GUIContainer.myMainModel, and editor.ElementAccordionController.updateItems().
Referenced by editor.EditorScreen.update().
void editor.EditorScreen.updateInfoBox (String[] selection) private
Definition at line 102 of file EditorScreen.java.
References gamemodel.MainModel.getDescribableState(), game_engine.gameRepresentation.stateRepresentation.DescribableState.getDescription(), game_engine.gameRepresentation.stateRepresentation.DescribableState.getName(), view.GUIContainer.myMainModel, and editor.DescribableInfoBoxController.setText().
Referenced by editor.EditorScreen.initProjectExplorer(), and editor.EditorScreen.update().
void editor.EditorScreen.updateProjectExplorer () private
Definition at line 207 of file EditorScreen.java.
References game_engine.gameRepresentation.stateRepresentation.GameState.getCampaigns(), gamemodel.MainModel.getCurrentGame(), game_engine.gameRepresentation.stateRepresentation.DescribableState.getName(), view.GUIContainer.myMainModel, and editor.ProjectExplorerController.update().
Referenced by editor.EditorScreen.update().
void editor.EditorScreen.updateTabViewControllers () private
Definition at line 222 of file EditorScreen.java.
References editor.EditorScreen.update().
Referenced by editor.EditorScreen.update().
Member Data Documentation
Parent editor.EditorScreen.editorMenuBar private
Definition at line 53 of file EditorScreen.java.
EditorMenuBarController editor.EditorScreen.editorMenuBarController private
Definition at line 55 of file EditorScreen.java.
BorderPane editor.EditorScreen.editorRoot private
Definition at line 57 of file EditorScreen.java.
Referenced by editor.EditorScreen.getRoot().
VBox editor.EditorScreen.gameInfoBox private
Definition at line 49 of file EditorScreen.java.
DescribableInfoBoxController editor.EditorScreen.gameInfoBoxController private
Definition at line 51 of file EditorScreen.java.
Accordion editor.EditorScreen.levelElementAccordion private
Definition at line 65 of file EditorScreen.java.
ElementAccordionController editor.EditorScreen.levelElementAccordionController private
Definition at line 67 of file EditorScreen.java.
Tab editor.EditorScreen.myCurrentTab private
Definition at line 70 of file EditorScreen.java.
HashMap<String, TabViewController> editor.EditorScreen.myTabViewControllers private
Definition at line 69 of file EditorScreen.java.
Button editor.EditorScreen.newGameElement private
Definition at line 59 of file EditorScreen.java.
Button editor.EditorScreen.newTerrain private
Definition at line 61 of file EditorScreen.java.
TreeView<String> editor.EditorScreen.projectExplorer private
Definition at line 45 of file EditorScreen.java.
ProjectExplorerController editor.EditorScreen.projectExplorerController private
Definition at line 47 of file EditorScreen.java.
Button editor.EditorScreen.save private
Definition at line 63 of file EditorScreen.java.
TabPane editor.EditorScreen.tabPane private
Definition at line 43 of file EditorScreen.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/EditorScreen.java