voogasalad_TheException: game_engine.gameRepresentation.stateRepresentation.DescribableState Class Reference
game_engine.gameRepresentation.stateRepresentation.DescribableState Class Reference abstract
Public Member Functions
void updateName (String name)
void updateDescription (String description)
String getName ()
String getDescription ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from util.JSONable
default String toJSON ()
Protected Member Functions
DescribableState (String name)
Private Attributes
String myName
String myDescription
Detailed Description
A state object that has a name and description. Essentially used to create states with associated name and description metadata.
Author
Jonathan, Nishad, Rahul
Definition at line 12 of file DescribableState.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.stateRepresentation.DescribableState.DescribableState (String name) protected
Definition at line 17 of file DescribableState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.DescribableState.equals().
Member Function Documentation
boolean game_engine.gameRepresentation.stateRepresentation.DescribableState.equals (Object obj)
Definition at line 53 of file DescribableState.java.
References game_engine.gameRepresentation.stateRepresentation.DescribableState.DescribableState(), game_engine.gameRepresentation.stateRepresentation.DescribableState.myDescription, and game_engine.gameRepresentation.stateRepresentation.DescribableState.myName.
String game_engine.gameRepresentation.stateRepresentation.DescribableState.getDescription ()
Definition at line 34 of file DescribableState.java.
References game_engine.gameRepresentation.stateRepresentation.DescribableState.myDescription.
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.getDescription(), and editor.EditorScreen.updateInfoBox().
String game_engine.gameRepresentation.stateRepresentation.DescribableState.getName ()
Definition at line 30 of file DescribableState.java.
References game_engine.gameRepresentation.stateRepresentation.DescribableState.myName.
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.getName(), game_engine.stateManaging.GameLoop.isCurrentLevel(), game_engine.Engine.play(), gamemodel.MainModel.saveGame(), game_engine.gameRepresentation.stateRepresentation.DescribableState.toString(), game_engine.Engine.update(), editor.EditorScreen.updateInfoBox(), and editor.EditorScreen.updateProjectExplorer().
int game_engine.gameRepresentation.stateRepresentation.DescribableState.hashCode ()
Definition at line 44 of file DescribableState.java.
String game_engine.gameRepresentation.stateRepresentation.DescribableState.toString ()
Definition at line 39 of file DescribableState.java.
References game_engine.gameRepresentation.stateRepresentation.DescribableState.getName().
void game_engine.gameRepresentation.stateRepresentation.DescribableState.updateDescription (String description)
Definition at line 26 of file DescribableState.java.
Referenced by gamemodel.MainModel.updateDescribableState().
void game_engine.gameRepresentation.stateRepresentation.DescribableState.updateName (String name)
Definition at line 22 of file DescribableState.java.
Referenced by gamemodel.MainModel.updateDescribableState().
Member Data Documentation
String game_engine.gameRepresentation.stateRepresentation.DescribableState.myDescription private
Definition at line 15 of file DescribableState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.DescribableState.equals(), and game_engine.gameRepresentation.stateRepresentation.DescribableState.getDescription().
String game_engine.gameRepresentation.stateRepresentation.DescribableState.myName private
Definition at line 14 of file DescribableState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.DescribableState.equals(), and game_engine.gameRepresentation.stateRepresentation.DescribableState.getName().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/stateRepresentation/DescribableState.java