voogasalad_TheException: engine.gameRepresentation.renderedRepresentation.SelectableGameElement Class Reference
engine.gameRepresentation.renderedRepresentation.SelectableGameElement Class Reference
Public Member Functions
SelectableGameElement (SelectableGameElementState element, Visualizer visualizer)
void setFocusedElement (SelectableGameElement element)
void clearFocusedElement ()
String getType ()
void addInteractingElement (InteractingElementType elementType, DrawableGameElement element)
void addInteractingElements (InteractingElementType interactingElementType, List< DrawableGameElement > interactingElements)
void select ()
void deselect ()
void update ()
void updateSelfDueToSelection ()
void registerAsSelectableChild (Consumer< SelectableGameElementState > function)
void executeAllButtonActions ()
Map< Integer, String > getAbilityDescriptionMap (int numAttributes)
Public Member Functions inherited from engine.gameRepresentation.renderedRepresentation.DrawableGameElement
DrawableGameElement (DrawableGameElementState state, Visualizer visualizer)
void update ()
Node getNode ()
double[] getBounds ()
Point2D getPosition ()
void registerAsDrawableChild (Consumer< DrawableGameElementState > function)
double[] findGlobalBounds ()
void setWaypoints (List< Location > waypointsToAdd)
void addWaypoint (double x, double y)
Location getNextWaypoint ()
List< Line > getLines ()
Public Member Functions inherited from engine.gameRepresentation.renderedRepresentation.GameElement
GameElement (GameElementState gameElementState)
GameElementState getState ()
Iterator< Evaluatable<?> > getActionsOfType (ActionType actionType)
void addAction (ActionType actionType, Evaluatable<?> action)
void removeAction (String actionID)
Number getNumericalAttribute (String attributeTag)
void setNumericalAttribute (String attributeTag, Number attributeValue)
String getTextualAttribute (String attributeTag)
void setTextualAttribute (String attributeTag, String attributeValue)
void update ()
long getTimer (String timerName)
void setTimer (String timerName, long timerValue)
void updateTimers ()
Map< String, Long > getTimersCopy ()
void registerAsChild (Consumer< GameElementState > function)
boolean isType (String typeString)
List< String > getTypes ()
void setPosition (double x, double y)
Private Member Functions
void initializeInteractingElementLists ()
void updateSelfDueToCurrentObjective ()
void updateSelfDueToFocusedElement ()
void updateSelfDueToVisions ()
void updateSelfDueToCollisions ()
void updateSelfDueToInteractingElementsSubset (InteractingElementType elementType, ActionType actionType)
Private Attributes
SelectableGameElementState selectableState
Map< InteractingElementType, Set< DrawableGameElement > > myInteractingElements
SelectableGameElement myFocusedElement
Additional Inherited Members
Protected Member Functions inherited from engine.gameRepresentation.renderedRepresentation.GameElement
void executeAllActions (ActionType actionKey, ElementPair elementPair)
void executeAllActions (ActionType actionKey)
Detailed Description
A wrapper for game elements capable of being selected. Adds a "selected" visual appearance to the appearance defined by the DrawableGameElement and handles animations for actions resulting from being selected.
Author
Jonathan , Steve, Nishad, Rahul, John, Michael D., Zach, Stanley
Definition at line 26 of file SelectableGameElement.java.
Constructor & Destructor Documentation
engine.gameRepresentation.renderedRepresentation.SelectableGameElement.SelectableGameElement (SelectableGameElementState element, Visualizer visualizer)
Definition at line 34 of file SelectableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.SelectableGameElement.initializeInteractingElementLists().
Member Function Documentation
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElement (InteractingElementType elementType, DrawableGameElement element)
Definition at line 63 of file SelectableGameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElements().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElements (InteractingElementType interactingElementType, List< DrawableGameElement > interactingElements)
Definition at line 74 of file SelectableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElement().
Referenced by engine.computers.boundsComputers.VisionComputer.givePrimaryObjectElements().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.clearFocusedElement ()
Definition at line 45 of file SelectableGameElement.java.
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.deselect ()
Definition at line 85 of file SelectableGameElement.java.
References model.state.gameelement.StateTags.IS_SELECTED, and engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.executeAllButtonActions ()
Definition at line 142 of file SelectableGameElement.java.
References engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.BUTTON, and engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions().
Map<Integer, String> engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getAbilityDescriptionMap (int numAttributes)
Definition at line 146 of file SelectableGameElement.java.
References model.state.gameelement.StateTags.ATTRIBUTE_DESCRIPTION, and engine.gameRepresentation.renderedRepresentation.GameElement.getTextualAttribute().
Referenced by engine.visuals.VisualManager.update().
String engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getType ()
Definition at line 59 of file SelectableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.getTextualAttribute(), and model.state.gameelement.StateTags.TYPE.
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.initializeInteractingElementLists () private
Definition at line 49 of file SelectableGameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.SelectableGameElement().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.registerAsSelectableChild (Consumer< SelectableGameElementState > function)
Definition at line 138 of file SelectableGameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.select ()
Definition at line 81 of file SelectableGameElement.java.
References model.state.gameelement.StateTags.IS_SELECTED, and engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.setFocusedElement (SelectableGameElement element)
Definition at line 41 of file SelectableGameElement.java.
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update ()
Definition at line 90 of file SelectableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCollisions(), engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCurrentObjective(), engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToFocusedElement(), and engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToVisions().
Referenced by engine.stateManaging.GameLoop.updateEditor(), and engine.stateManaging.GameLoop.updateRunner().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCollisions () private
Definition at line 116 of file SelectableGameElement.java.
References engine.computers.objectClassifications.InteractingElementType.COLLIDING, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.COLLISION, and engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToInteractingElementsSubset().
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCurrentObjective () private
Definition at line 100 of file SelectableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions(), and engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.OBJECTIVE.
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToFocusedElement () private
Definition at line 104 of file SelectableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions(), and engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.FOCUSED.
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToInteractingElementsSubset (InteractingElementType elementType, ActionType actionType) private
Definition at line 121 of file SelectableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.getActionsOfType().
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCollisions(), and engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToVisions().
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToSelection ()
Definition at line 108 of file SelectableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions(), and engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.SELECTION.
void engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToVisions () private
Definition at line 112 of file SelectableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToInteractingElementsSubset(), engine.computers.objectClassifications.InteractingElementType.VISIBLE, and engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.VISION.
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
Member Data Documentation
SelectableGameElement engine.gameRepresentation.renderedRepresentation.SelectableGameElement.myFocusedElement private
Definition at line 32 of file SelectableGameElement.java.
Map<InteractingElementType, Set<DrawableGameElement> > engine.gameRepresentation.renderedRepresentation.SelectableGameElement.myInteractingElements private
Definition at line 30 of file SelectableGameElement.java.
SelectableGameElementState engine.gameRepresentation.renderedRepresentation.SelectableGameElement.selectableState private
Definition at line 28 of file SelectableGameElement.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/renderedRepresentation/SelectableGameElement.java