voogasalad_TheException: game_engine.gameRepresentation.stateRepresentation.GameState Class Reference
game_engine.gameRepresentation.stateRepresentation.GameState Class Reference
Public Member Functions
GameState (String name)
CampaignState getCampaign (String campaignName) throws CampaignNotFoundException
List< CampaignState > getCampaigns ()
void addCampaign (CampaignState campaignToAdd) throws CampaignExistsException
void removeCampaign (String campaignName)
GameUniverse getGameUniverse ()
Public Member Functions inherited from game_engine.gameRepresentation.stateRepresentation.DescribableState
void updateName (String name)
void updateDescription (String description)
String getName ()
String getDescription ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from util.JSONable
default String toJSON ()
Private Attributes
List< CampaignState > myCampaigns
GameUniverse myGameUniverse
Additional Inherited Members
Protected Member Functions inherited from game_engine.gameRepresentation.stateRepresentation.DescribableState
DescribableState (String name)
Detailed Description
This class is analogous to a genre of game or a game tile such as Warcraft (tm).
Author
Steve, Jonathan, Nishad, Rahul
Definition at line 18 of file GameState.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.stateRepresentation.GameState.GameState (String name)
Definition at line 23 of file GameState.java.
Member Function Documentation
void game_engine.gameRepresentation.stateRepresentation.GameState.addCampaign (CampaignState campaignToAdd) throws CampaignExistsException
adds a campaign to the game
Parameters
campaignToAdd
Exceptions
CampaignExistsExeption
Definition at line 63 of file GameState.java.
Referenced by gamemodel.MainModel.createCampaign().
CampaignState game_engine.gameRepresentation.stateRepresentation.GameState.getCampaign (String campaignName) throws CampaignNotFoundException
gets the campaign with associated campaignName
Parameters
campaignName
Returns
Exceptions
CampaignNotFoundException
Definition at line 36 of file GameState.java.
Referenced by gamemodel.MainModel.createLevel(), gamemodel.MainModel.getDescribableState(), and gamemodel.MainModel.setCurrentLevel().
List<CampaignState> game_engine.gameRepresentation.stateRepresentation.GameState.getCampaigns ()
returns unmodifiable list of campaigns
Returns
Definition at line 53 of file GameState.java.
Referenced by gamemodel.MainModel.loadGame(), and editor.EditorScreen.updateProjectExplorer().
GameUniverse game_engine.gameRepresentation.stateRepresentation.GameState.getGameUniverse ()
returns the game universe for this game
Returns
Definition at line 90 of file GameState.java.
References game_engine.gameRepresentation.stateRepresentation.GameState.myGameUniverse.
Referenced by gamemodel.MainModel.createDrawableGameElement(), gamemodel.MainModel.createGameElement(), gamemodel.MainModel.createSelectableGameElement(), and gamemodel.MainModel.getGameUniverse().
void game_engine.gameRepresentation.stateRepresentation.GameState.removeCampaign (String campaignName)
removes a campaign with a given name
Parameters
campaignName
Definition at line 79 of file GameState.java.
Member Data Documentation
List<CampaignState> game_engine.gameRepresentation.stateRepresentation.GameState.myCampaigns private
Definition at line 20 of file GameState.java.
GameUniverse game_engine.gameRepresentation.stateRepresentation.GameState.myGameUniverse private
Definition at line 21 of file GameState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.GameState.getGameUniverse().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/stateRepresentation/GameState.java