voogasalad_TheException: view.editor.wizards.DirectionGrid Class Reference
view.editor.wizards.DirectionGrid Class Reference
Public Member Functions
DirectionGrid (double frameX, double frameY)
void selectFrame (int row, int col)
void selectFrame (int row, int col, Paint fill)
List< AnimationTag > getDirections ()
Public Member Functions inherited from view.editor.wizards.Grid
Grid (double frameX, double frameY)
abstract void selectFrame (int row, int col, Paint fill)
double getFrameX ()
double getFrameY ()
Static Public Attributes
static final int GRID_SIZE = 3
Protected Member Functions
void createColumns ()
Group createColumn (int col)
Protected Member Functions inherited from view.editor.wizards.Grid
void resetExistingFill (String primary, Paint reset)
void createGrid ()
abstract void createColumns ()
abstract Group createColumn (int col)
Frame createFrame (int row, int col, Paint fill)
Private Attributes
List< AnimationTag > directions
Static Private Attributes
static final String SELECTED_COLOR = "red"
static final Paint FILL_COLOR = Paint.valueOf("white")
Additional Inherited Members
Protected Attributes inherited from view.editor.wizards.Grid
double myFrameX
double myFrameY
List< List< Frame > > frameCols
Static Protected Attributes inherited from view.editor.wizards.Grid
static final String FRAME_STROKE_COLOR = "black"
Detailed Description
Grid Lines used to be displayed over a sprite sheet within the drawable game element wizard.
Author
Jonathan Tseng, Nishad Agrawal
Definition at line 16 of file DirectionGrid.java.
Constructor & Destructor Documentation
view.editor.wizards.DirectionGrid.DirectionGrid (double frameX, double frameY)
Definition at line 23 of file DirectionGrid.java.
Member Function Documentation
Group view.editor.wizards.DirectionGrid.createColumn (int col) protected
Definition at line 62 of file DirectionGrid.java.
References view.editor.wizards.Grid.createFrame(), view.editor.wizards.Grid.frameCols, view.editor.wizards.DirectionGrid.GRID_SIZE, view.editor.wizards.Grid.myFrameY, and view.editor.wizards.DirectionGrid.selectFrame().
Referenced by view.editor.wizards.DirectionGrid.createColumns().
void view.editor.wizards.DirectionGrid.createColumns () protected
Definition at line 52 of file DirectionGrid.java.
References view.editor.wizards.DirectionGrid.createColumn(), view.editor.wizards.Grid.frameCols, view.editor.wizards.DirectionGrid.GRID_SIZE, and view.editor.wizards.Grid.myFrameX.
List<AnimationTag> view.editor.wizards.DirectionGrid.getDirections ()
Definition at line 47 of file DirectionGrid.java.
References view.editor.wizards.DirectionGrid.directions.
Referenced by view.editor.wizards.AnimationWizard.checkCanSave(), and view.editor.wizards.AnimationWizard.getTags().
void view.editor.wizards.DirectionGrid.selectFrame (int row, int col)
Definition at line 28 of file DirectionGrid.java.
Referenced by view.editor.wizards.DirectionGrid.createColumn(), and view.editor.wizards.AnimationWizard.selectCorrectFrame().
void view.editor.wizards.DirectionGrid.selectFrame (int row, int col, Paint fill)
Definition at line 33 of file DirectionGrid.java.
References engine.visuals.elementVisuals.animations.AnimationTag.BACKWARD, engine.visuals.elementVisuals.animations.AnimationTag.FORWARD, view.editor.wizards.Grid.frameCols, engine.visuals.elementVisuals.animations.AnimationTag.HERE, engine.visuals.elementVisuals.animations.AnimationTag.LEFT, view.editor.wizards.Grid.resetExistingFill(), and engine.visuals.elementVisuals.animations.AnimationTag.RIGHT.
Member Data Documentation
List<AnimationTag> view.editor.wizards.DirectionGrid.directions private
Definition at line 21 of file DirectionGrid.java.
Referenced by view.editor.wizards.DirectionGrid.getDirections().
final Paint view.editor.wizards.DirectionGrid.FILL_COLOR = Paint.valueOf("white") static private
Definition at line 20 of file DirectionGrid.java.
final int view.editor.wizards.DirectionGrid.GRID_SIZE = 3 static
Definition at line 18 of file DirectionGrid.java.
Referenced by view.editor.wizards.DirectionGrid.createColumn(), view.editor.wizards.DirectionGrid.createColumns(), and view.editor.wizards.AnimationWizard.selectCorrectFrame().
final String view.editor.wizards.DirectionGrid.SELECTED_COLOR = "red" static private
Definition at line 19 of file DirectionGrid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/DirectionGrid.java