voogasalad_TheException: engine.elementFactories.LevelFactory Class Reference
engine.elementFactories.LevelFactory Class Reference
Public Member Functions
LevelFactory (GameElementFactory elementFactory)
Level createLevel (LevelState state)
Private Member Functions
List< GameElement > generateGoalElements (List< GameElementState > goals)
List< DrawableGameElement > generateTerrainElements (List< DrawableGameElementState > terrain)
List< SelectableGameElement > generateUnitEelements (List< SelectableGameElementState > units)
MapGrid generateUpToDateGrid (Number levelHeight, Number levelWidth, List< DrawableGameElement > terrain, List< SelectableGameElement > units)
void updateGridForObstacles (List< DrawableGameElement > terrain, List< SelectableGameElement > units, MapGrid newGrid)
Group generateBackGroundGroup (List< DrawableGameElement > terrain, List< SelectableGameElement > units)
Group generateUnitsGroup (List< SelectableGameElement > units)
Private Attributes
GameElementFactory myElementFactory
Detailed Description
Factory for creating Level objects from LevelState objects.
Author
Steve
Definition at line 24 of file LevelFactory.java.
Constructor & Destructor Documentation
engine.elementFactories.LevelFactory.LevelFactory (GameElementFactory elementFactory)
Definition at line 28 of file LevelFactory.java.
Member Function Documentation
Level engine.elementFactories.LevelFactory.createLevel (LevelState state)
Definition at line 32 of file LevelFactory.java.
References model.state.LevelState.attributes, engine.elementFactories.LevelFactory.generateBackGroundGroup(), engine.elementFactories.LevelFactory.generateGoalElements(), engine.elementFactories.LevelFactory.generateTerrainElements(), engine.elementFactories.LevelFactory.generateUnitEelements(), engine.elementFactories.LevelFactory.generateUnitsGroup(), engine.elementFactories.LevelFactory.generateUpToDateGrid(), model.state.LevelState.getGoals(), model.state.gameelement.AttributeContainer.getNumericalAttribute(), model.state.LevelState.getTerrain(), model.state.LevelState.getUnits(), model.state.gameelement.StateTags.LEVEL_HEIGHT, and model.state.gameelement.StateTags.LEVEL_WIDTH.
Referenced by engine.Engine.instantiateManagers().
Group engine.elementFactories.LevelFactory.generateBackGroundGroup (List< DrawableGameElement > terrain, List< SelectableGameElement > units) private
Definition at line 81 of file LevelFactory.java.
References model.state.gameelement.StateTags.MOVEMENT_SPEED.
Referenced by engine.elementFactories.LevelFactory.createLevel().
List<GameElement> engine.elementFactories.LevelFactory.generateGoalElements (List< GameElementState > goals) private
Definition at line 46 of file LevelFactory.java.
References engine.elementFactories.GameElementFactory.createGameElement().
Referenced by engine.elementFactories.LevelFactory.createLevel().
List<DrawableGameElement> engine.elementFactories.LevelFactory.generateTerrainElements (List< DrawableGameElementState > terrain) private
Definition at line 51 of file LevelFactory.java.
References engine.elementFactories.GameElementFactory.createDrawableGameElement().
Referenced by engine.elementFactories.LevelFactory.createLevel().
List<SelectableGameElement> engine.elementFactories.LevelFactory.generateUnitEelements (List< SelectableGameElementState > units) private
Definition at line 56 of file LevelFactory.java.
References engine.elementFactories.GameElementFactory.createSelectableGameElement().
Referenced by engine.elementFactories.LevelFactory.createLevel().
Group engine.elementFactories.LevelFactory.generateUnitsGroup (List< SelectableGameElement > units) private
Definition at line 93 of file LevelFactory.java.
References model.state.gameelement.StateTags.MOVEMENT_SPEED.
Referenced by engine.elementFactories.LevelFactory.createLevel().
MapGrid engine.elementFactories.LevelFactory.generateUpToDateGrid (Number levelHeight, Number levelWidth, List< DrawableGameElement > terrain, List< SelectableGameElement > units) private
Definition at line 61 of file LevelFactory.java.
References engine.elementFactories.LevelFactory.updateGridForObstacles().
Referenced by engine.elementFactories.LevelFactory.createLevel().
void engine.elementFactories.LevelFactory.updateGridForObstacles (List< DrawableGameElement > terrain, List< SelectableGameElement > units, MapGrid newGrid) private
Definition at line 70 of file LevelFactory.java.
References model.state.gameelement.StateTags.BLOCKING, model.state.gameelement.StateTags.MOVEMENT_SPEED, and engine.computers.pathingComputers.MapGrid.registerObstaclePlacement().
Referenced by engine.elementFactories.LevelFactory.generateUpToDateGrid().
Member Data Documentation
GameElementFactory engine.elementFactories.LevelFactory.myElementFactory private
Definition at line 26 of file LevelFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/elementFactories/LevelFactory.java