voogasalad_TheException: view.editor.wizards.AnimationWizard Class Reference
view.editor.wizards.AnimationWizard Class Reference
Public Member Functions
void initialize ()
boolean checkCanSave ()
void updateData ()
void launchForEdit (WizardData oldValues)
void loadGlobalValues (List< String > values)
Public Member Functions inherited from view.editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
abstract void launchForEdit (WizardData oldValues)
abstract void loadGlobalValues (List< String > values)
WizardData getWizardData ()
void displayErrorMessage (String error)
void removeWizardData (WizardData data)
void setStage (Stage s)
void closeStage ()
Protected Member Functions
void attachTextProperties ()
Protected Member Functions inherited from view.editor.wizards.Wizard
void addToData (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void setWizardType (WizardType type)
void attachTextProperties ()
boolean isNumber (String value)
Private Member Functions
void loadImage ()
Image addImage (String path) throws FileNotFoundException
void updateAnimationGrid (Consumer< Integer > updateCons, String newValue)
String getTags ()
void selectCorrectFrame (List< AnimationTag > tags)
Private Attributes
final int DIRECTION_GRID_SIZE = 50
AnchorPane leftPane
Group spritesheet
ScrollPane imageScroll
ComboBox< AnimationTag > animationAction
Group animationDirection
Text gridPrompt
TextField startFrame
TextField stopFrame
CheckBox animationRepeat
TextField slownessMultiplier
ImageView imageView
AnimationGrid animationGrid
DirectionGrid directionGrid
String imagePath
String colorMaskPath
Double frameWidth
Double frameHeight
Static Private Attributes
static final String GRID_PROMPT_KEY = "DirectionGridPrompt"
static final String ANIMATION_ACTION_KEY = "AnimationAction"
static final String START_FRAME_KEY = "StartFrame"
static final String STOP_FRAME_KEY = "StopFrame"
Additional Inherited Members
Static Public Attributes inherited from view.editor.wizards.Wizard
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
Protected Attributes inherited from view.editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Detailed Description
Author
Joshua, Nishad
Definition at line 36 of file AnimationWizard.java.
Member Function Documentation
Image view.editor.wizards.AnimationWizard.addImage (String path) throws FileNotFoundException private
Definition at line 99 of file AnimationWizard.java.
Referenced by view.editor.wizards.AnimationWizard.loadImage().
void view.editor.wizards.AnimationWizard.attachTextProperties () protected
Attaches multilanguage utility to text in the wizard
Definition at line 152 of file AnimationWizard.java.
References view.editor.wizards.Wizard.displayErrorMessage(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.editor.wizards.AnimationWizard.initialize().
boolean view.editor.wizards.AnimationWizard.checkCanSave ()
Definition at line 167 of file AnimationWizard.java.
References view.editor.wizards.DirectionGrid.getDirections(), and view.editor.wizards.Wizard.isNumber().
String view.editor.wizards.AnimationWizard.getTags () private
Definition at line 188 of file AnimationWizard.java.
References view.editor.wizards.DirectionGrid.getDirections().
Referenced by view.editor.wizards.AnimationWizard.updateData().
void view.editor.wizards.AnimationWizard.initialize ()
Binds all the listeners to the scene
Implements view.gui.GUIController.
Definition at line 113 of file AnimationWizard.java.
References engine.visuals.elementVisuals.animations.AnimationTag.AnimationType.ACTION, view.editor.wizards.AnimationWizard.attachTextProperties(), view.editor.wizards.Wizard.errorMessage, view.editor.wizards.AnimationGrid.setStart(), view.editor.wizards.AnimationGrid.setStop(), and view.editor.wizards.AnimationWizard.updateAnimationGrid().
void view.editor.wizards.AnimationWizard.launchForEdit (WizardData oldValues)
Definition at line 198 of file AnimationWizard.java.
References engine.visuals.elementVisuals.animations.AnimationTag.AnimationType.ACTION, model.data.WizardDataType.ANIMATION_REPEAT, model.data.WizardDataType.ANIMATION_TAG, model.data.WizardData.getValueByKey(), view.editor.wizards.AnimationWizard.selectCorrectFrame(), model.data.WizardDataType.SLOWNESS_MULTIPLIER, model.data.WizardDataType.START_FRAME, and model.data.WizardDataType.STOP_FRAME.
void view.editor.wizards.AnimationWizard.loadGlobalValues (List< String > values)
Definition at line 229 of file AnimationWizard.java.
References view.editor.wizards.AnimationWizard.loadImage().
void view.editor.wizards.AnimationWizard.loadImage () private
Fired when the user uploads a new picture
Credit for the buffered image code goes to StackOverflow user mathew11
Definition at line 80 of file AnimationWizard.java.
References view.editor.wizards.AnimationWizard.addImage(), and view.editor.wizards.Wizard.displayErrorMessage().
Referenced by view.editor.wizards.AnimationWizard.loadGlobalValues().
void view.editor.wizards.AnimationWizard.selectCorrectFrame (List< AnimationTag > tags) private
Definition at line 214 of file AnimationWizard.java.
References engine.visuals.elementVisuals.animations.AnimationTag.BACKWARD, engine.visuals.elementVisuals.animations.AnimationTag.FORWARD, view.editor.wizards.DirectionGrid.GRID_SIZE, engine.visuals.elementVisuals.animations.AnimationTag.LEFT, engine.visuals.elementVisuals.animations.AnimationTag.RIGHT, and view.editor.wizards.DirectionGrid.selectFrame().
Referenced by view.editor.wizards.AnimationWizard.launchForEdit().
void view.editor.wizards.AnimationWizard.updateAnimationGrid (Consumer< Integer > updateCons, String newValue) private
Definition at line 134 of file AnimationWizard.java.
References view.editor.wizards.Wizard.displayErrorMessage(), and view.editor.wizards.Wizard.isNumber().
Referenced by view.editor.wizards.AnimationWizard.initialize().
void view.editor.wizards.AnimationWizard.updateData ()
Definition at line 179 of file AnimationWizard.java.
References view.editor.wizards.Wizard.addToData(), model.data.WizardDataType.ANIMATION_REPEAT, model.data.WizardType.ANIMATION_SEQUENCE, model.data.WizardDataType.ANIMATION_TAG, view.editor.wizards.AnimationWizard.getTags(), view.editor.wizards.Wizard.setWizardType(), model.data.WizardDataType.SLOWNESS_MULTIPLIER, model.data.WizardDataType.START_FRAME, and model.data.WizardDataType.STOP_FRAME.
Member Data Documentation
final String view.editor.wizards.AnimationWizard.ANIMATION_ACTION_KEY = "AnimationAction" static private
Definition at line 39 of file AnimationWizard.java.
ComboBox<AnimationTag> view.editor.wizards.AnimationWizard.animationAction private
Definition at line 52 of file AnimationWizard.java.
Group view.editor.wizards.AnimationWizard.animationDirection private
Definition at line 54 of file AnimationWizard.java.
AnimationGrid view.editor.wizards.AnimationWizard.animationGrid private
Definition at line 67 of file AnimationWizard.java.
CheckBox view.editor.wizards.AnimationWizard.animationRepeat private
Definition at line 62 of file AnimationWizard.java.
String view.editor.wizards.AnimationWizard.colorMaskPath private
Definition at line 70 of file AnimationWizard.java.
final int view.editor.wizards.AnimationWizard.DIRECTION_GRID_SIZE = 50 private
Definition at line 43 of file AnimationWizard.java.
DirectionGrid view.editor.wizards.AnimationWizard.directionGrid private
Definition at line 68 of file AnimationWizard.java.
Double view.editor.wizards.AnimationWizard.frameHeight private
Definition at line 72 of file AnimationWizard.java.
Double view.editor.wizards.AnimationWizard.frameWidth private
Definition at line 71 of file AnimationWizard.java.
final String view.editor.wizards.AnimationWizard.GRID_PROMPT_KEY = "DirectionGridPrompt" static private
Definition at line 38 of file AnimationWizard.java.
Text view.editor.wizards.AnimationWizard.gridPrompt private
Definition at line 56 of file AnimationWizard.java.
String view.editor.wizards.AnimationWizard.imagePath private
Definition at line 69 of file AnimationWizard.java.
ScrollPane view.editor.wizards.AnimationWizard.imageScroll private
Definition at line 50 of file AnimationWizard.java.
ImageView view.editor.wizards.AnimationWizard.imageView private
Definition at line 66 of file AnimationWizard.java.
AnchorPane view.editor.wizards.AnimationWizard.leftPane private
Definition at line 46 of file AnimationWizard.java.
TextField view.editor.wizards.AnimationWizard.slownessMultiplier private
Definition at line 64 of file AnimationWizard.java.
Group view.editor.wizards.AnimationWizard.spritesheet private
Definition at line 48 of file AnimationWizard.java.
final String view.editor.wizards.AnimationWizard.START_FRAME_KEY = "StartFrame" static private
Definition at line 40 of file AnimationWizard.java.
TextField view.editor.wizards.AnimationWizard.startFrame private
Definition at line 58 of file AnimationWizard.java.
final String view.editor.wizards.AnimationWizard.STOP_FRAME_KEY = "StopFrame" static private
Definition at line 41 of file AnimationWizard.java.
TextField view.editor.wizards.AnimationWizard.stopFrame private
Definition at line 60 of file AnimationWizard.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/AnimationWizard.java