voogasalad_TheException: game_engine.visuals.Dimension Class Reference
game_engine.visuals.Dimension Class Reference
Public Member Functions
Dimension (int row, int col)
int getWidth ()
int getHeight ()
Dimension addToFormNewDimension (Dimension dimension)
boolean equals (Object o)
String toString ()
Private Attributes
int myWidth
int myHeight
Detailed Description
Very simple class that holds dimensions for an object. This was created to avoid using the unserializable Point2D from JavaFX. A data wrapping class that contains no logic of its own.
Author
Steve, Zach
Definition at line 11 of file Dimension.java.
Constructor & Destructor Documentation
game_engine.visuals.Dimension.Dimension (int row, int col)
Definition at line 15 of file Dimension.java.
Referenced by game_engine.visuals.Dimension.addToFormNewDimension(), and game_engine.visuals.Dimension.equals().
Member Function Documentation
Dimension game_engine.visuals.Dimension.addToFormNewDimension (Dimension dimension)
Definition at line 28 of file Dimension.java.
References game_engine.visuals.Dimension.Dimension(), game_engine.visuals.Dimension.myHeight, and game_engine.visuals.Dimension.myWidth.
boolean game_engine.visuals.Dimension.equals (Object o)
Definition at line 33 of file Dimension.java.
References game_engine.visuals.Dimension.Dimension(), game_engine.visuals.Dimension.myHeight, and game_engine.visuals.Dimension.myWidth.
int game_engine.visuals.Dimension.getHeight ()
Definition at line 24 of file Dimension.java.
References game_engine.visuals.Dimension.myHeight.
Referenced by game_engine.visuals.AnimationPlayer.AnimationPlayer(), game_engine.Engine.Engine(), game_engine.visuals.LayeredAnimationPlayer.getViewport(), game_engine.visuals.AnimationPlayer.getViewport(), game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.initializeDisplay(), game_engine.visuals.LayeredAnimationPlayer.LayeredAnimationPlayer(), and application.ShittyMain.start().
int game_engine.visuals.Dimension.getWidth ()
Definition at line 20 of file Dimension.java.
References game_engine.visuals.Dimension.myWidth.
Referenced by game_engine.visuals.AnimationPlayer.AnimationPlayer(), game_engine.visuals.LayeredAnimationPlayer.getViewport(), game_engine.visuals.AnimationPlayer.getViewport(), game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.initializeDisplay(), and game_engine.visuals.LayeredAnimationPlayer.LayeredAnimationPlayer().
String game_engine.visuals.Dimension.toString ()
Definition at line 46 of file Dimension.java.
Member Data Documentation
int game_engine.visuals.Dimension.myHeight private
Definition at line 13 of file Dimension.java.
Referenced by game_engine.visuals.Dimension.addToFormNewDimension(), game_engine.visuals.Dimension.equals(), and game_engine.visuals.Dimension.getHeight().
int game_engine.visuals.Dimension.myWidth private
Definition at line 12 of file Dimension.java.
Referenced by game_engine.visuals.Dimension.addToFormNewDimension(), game_engine.visuals.Dimension.equals(), and game_engine.visuals.Dimension.getWidth().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/Dimension.java