voogasalad_TheException: view.editor.wizards.WidgetWizard Class Reference
view.editor.wizards.WidgetWizard Class Reference
Public Member Functions
boolean checkCanSave ()
void updateData ()
void initialize ()
void launchForEdit (WizardData oldValues)
void loadGlobalValues (List< String > values)
Public Member Functions inherited from view.editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
abstract void launchForEdit (WizardData oldValues)
abstract void loadGlobalValues (List< String > values)
WizardData getWizardData ()
void displayErrorMessage (String error)
void removeWizardData (WizardData data)
void setStage (Stage s)
void closeStage ()
Protected Member Functions
void attachTextProperties ()
Protected Member Functions inherited from view.editor.wizards.Wizard
void addToData (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void setWizardType (WizardType type)
void attachTextProperties ()
boolean isNumber (String value)
Protected Attributes
ComboBox< String > displayerTag
ComboBox< String > attribute
VBox arguments
Protected Attributes inherited from view.editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Private Member Functions
boolean argumentsValid ()
String getArguments ()
void newAttribute (String newVal)
Private Attributes
List< TextField > argFields
List< String > myGlobalNumberAttributes
Set< String > allAttributes
Static Private Attributes
static final int NUMERIC_TEXT_FIELD_VALUE = 2
static final String WIDGET_TYPE_KEY = "WidgetType"
static final String ATTRIBUTE_KEY = "Attribute"
Additional Inherited Members
Static Public Attributes inherited from view.editor.wizards.Wizard
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
Detailed Description
This represents the Wizard responsible for storing a string attribute along with its attribute name as a key. It only requires both fields to not be null.
Author
Joshua, Nishad
Definition at line 29 of file WidgetWizard.java.
Member Function Documentation
boolean view.editor.wizards.WidgetWizard.argumentsValid () private
Definition at line 54 of file WidgetWizard.java.
References view.editor.wizards.Wizard.isNumber().
Referenced by view.editor.wizards.WidgetWizard.checkCanSave().
void view.editor.wizards.WidgetWizard.attachTextProperties () protected
Definition at line 110 of file WidgetWizard.java.
References view.editor.wizards.Wizard.displayErrorMessage(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
boolean view.editor.wizards.WidgetWizard.checkCanSave ()
Definition at line 48 of file WidgetWizard.java.
References view.editor.wizards.WidgetWizard.argumentsValid().
String view.editor.wizards.WidgetWizard.getArguments () private
Definition at line 70 of file WidgetWizard.java.
Referenced by view.editor.wizards.WidgetWizard.updateData().
void view.editor.wizards.WidgetWizard.initialize ()
Implements view.gui.GUIController.
Definition at line 79 of file WidgetWizard.java.
References model.state.gameelement.StateTags.getAllAttributes(), and view.editor.wizards.WidgetWizard.newAttribute().
void view.editor.wizards.WidgetWizard.launchForEdit (WizardData oldValues)
Definition at line 123 of file WidgetWizard.java.
References model.data.WizardDataType.ATTRIBUTE, model.data.WizardData.getValueByKey(), and model.data.WizardDataType.WIDGET_TYPE.
void view.editor.wizards.WidgetWizard.loadGlobalValues (List< String > values)
Definition at line 129 of file WidgetWizard.java.
void view.editor.wizards.WidgetWizard.newAttribute (String newVal) private
Definition at line 91 of file WidgetWizard.java.
References model.state.gameelement.StateTags.getAllNumericalAttributes().
Referenced by view.editor.wizards.WidgetWizard.initialize().
void view.editor.wizards.WidgetWizard.updateData ()
Definition at line 63 of file WidgetWizard.java.
References view.editor.wizards.Wizard.addToData(), model.data.WizardDataType.ATTRIBUTE, view.editor.wizards.WidgetWizard.getArguments(), view.editor.wizards.Wizard.setWizardType(), model.data.WizardType.WIDGET, model.data.WizardDataType.WIDGET_PARAMETERS, and model.data.WizardDataType.WIDGET_TYPE.
Member Data Documentation
Set<String> view.editor.wizards.WidgetWizard.allAttributes private
Definition at line 45 of file WidgetWizard.java.
List<TextField> view.editor.wizards.WidgetWizard.argFields private
Definition at line 42 of file WidgetWizard.java.
VBox view.editor.wizards.WidgetWizard.arguments protected
Definition at line 40 of file WidgetWizard.java.
ComboBox<String> view.editor.wizards.WidgetWizard.attribute protected
Definition at line 38 of file WidgetWizard.java.
final String view.editor.wizards.WidgetWizard.ATTRIBUTE_KEY = "Attribute" static private
Definition at line 33 of file WidgetWizard.java.
ComboBox<String> view.editor.wizards.WidgetWizard.displayerTag protected
Definition at line 36 of file WidgetWizard.java.
List<String> view.editor.wizards.WidgetWizard.myGlobalNumberAttributes private
Definition at line 44 of file WidgetWizard.java.
final int view.editor.wizards.WidgetWizard.NUMERIC_TEXT_FIELD_VALUE = 2 static private
Definition at line 31 of file WidgetWizard.java.
final String view.editor.wizards.WidgetWizard.WIDGET_TYPE_KEY = "WidgetType" static private
Definition at line 32 of file WidgetWizard.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/WidgetWizard.java