voogasalad_TheException: editor.wizards.TerrainWizard Class Reference
editor.wizards.TerrainWizard Class Reference
Public Member Functions
void initialize ()
boolean checkCanSave ()
void updateData ()
Public Member Functions inherited from editor.wizards.DrawableGameElementWizard
void initialize ()
boolean checkCanSave ()
void updateData ()
Public Member Functions inherited from editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
WizardData getWizardData ()
void setErrorMesssage (String error)
void setStage (Stage s)
Stage getStage ()
Private Member Functions
void loadImage ()
Private Attributes
Button image
ImageView spritesheet
Additional Inherited Members
Protected Member Functions inherited from editor.wizards.Wizard
void addToData (String key, String value)
void addWizardData (WizardData wizData)
void setDataName (String name)
Protected Attributes inherited from editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Detailed Description
Author
Joshua, Nishad
Definition at line 19 of file TerrainWizard.java.
Member Function Documentation
boolean editor.wizards.TerrainWizard.checkCanSave ()
Definition at line 51 of file TerrainWizard.java.
void editor.wizards.TerrainWizard.initialize ()
Implements view.GUIController.
Definition at line 45 of file TerrainWizard.java.
References editor.wizards.TerrainWizard.loadImage().
void editor.wizards.TerrainWizard.loadImage () private
Fired when the user uploads a new picture
Credit for the buffered image code goes to StackOverflow user mathew11
Definition at line 32 of file TerrainWizard.java.
References editor.wizards.Wizard.addToData().
Referenced by editor.wizards.TerrainWizard.initialize().
void editor.wizards.TerrainWizard.updateData ()
Definition at line 56 of file TerrainWizard.java.
References editor.wizards.Wizard.setDataName().
Member Data Documentation
Button editor.wizards.TerrainWizard.image private
Definition at line 22 of file TerrainWizard.java.
ImageView editor.wizards.TerrainWizard.spritesheet private
Definition at line 24 of file TerrainWizard.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/wizards/TerrainWizard.java