voogasalad_TheException: vooga.request.receiver.UnknownSenderException Class Reference
vooga.request.receiver.UnknownSenderException Class Reference
Public Member Functions
UnknownSenderException (String sender, IRequest request)
String sender ()
IRequest request ()
UnknownSenderException (String sender, IRequest request)
String sender ()
IRequest request ()
Private Attributes
String mySender
IRequest myRequest
Detailed Description
An exception encapsulating when a sender is not recognized as known or valid
Definition at line 8 of file UnknownSenderException.java.
Constructor & Destructor Documentation
vooga.request.receiver.UnknownSenderException.UnknownSenderException (String sender, IRequest request)
Create a new unknown sender exception
Parameters
sender The address of the sender that is unknown
request The sender's request
Definition at line 19 of file UnknownSenderException.java.
References vooga.request.receiver.UnknownSenderException.request(), and vooga.request.receiver.UnknownSenderException.sender().
vooga.request.receiver.UnknownSenderException.UnknownSenderException (String sender, IRequest request)
Create a new unknown sender exception
Parameters
sender The address of the sender that is unknown
request The sender's request
Definition at line 19 of file UnknownSenderException.java.
References vooga.request.receiver.UnknownSenderException.request(), and vooga.request.receiver.UnknownSenderException.sender().
Member Function Documentation
IRequest vooga.request.receiver.UnknownSenderException.request ()
Get the request
Returns
The request associated with the sender
Definition at line 39 of file UnknownSenderException.java.
References vooga.request.receiver.UnknownSenderException.myRequest.
Referenced by vooga.request.receiver.UnknownSenderException.UnknownSenderException().
IRequest vooga.request.receiver.UnknownSenderException.request ()
Get the request
Returns
The request associated with the sender
Definition at line 39 of file UnknownSenderException.java.
References vooga.request.receiver.UnknownSenderException.myRequest.
String vooga.request.receiver.UnknownSenderException.sender ()
Get the sender
Returns
The address of the sender
Definition at line 30 of file UnknownSenderException.java.
References vooga.request.receiver.UnknownSenderException.mySender.
String vooga.request.receiver.UnknownSenderException.sender ()
Get the sender
Returns
The address of the sender
Definition at line 30 of file UnknownSenderException.java.
References vooga.request.receiver.UnknownSenderException.mySender.
Referenced by vooga.request.receiver.UnknownSenderException.UnknownSenderException().
Member Data Documentation
IRequest vooga.request.receiver.UnknownSenderException.myRequest private
Definition at line 11 of file UnknownSenderException.java.
Referenced by vooga.request.receiver.UnknownSenderException.request().
String vooga.request.receiver.UnknownSenderException.mySender private
Definition at line 10 of file UnknownSenderException.java.
Referenced by vooga.request.receiver.UnknownSenderException.sender().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/build/build/src/vooga/request/receiver/UnknownSenderException.java