voogasalad_TheException: engine.elementFactories.AnimatorFactory Class Reference
engine.elementFactories.AnimatorFactory Class Reference
Public Member Functions
AnimatorFactory (MainModel model)
Animator createAnimator (DrawableGameElementState elementState, SimpleBooleanProperty animationEnabled)
Private Attributes
MainModel myModel
Detailed Description
Definition at line 11 of file AnimatorFactory.java.
Constructor & Destructor Documentation
engine.elementFactories.AnimatorFactory.AnimatorFactory (MainModel model)
Definition at line 15 of file AnimatorFactory.java.
Member Function Documentation
Animator engine.elementFactories.AnimatorFactory.createAnimator (DrawableGameElementState elementState, SimpleBooleanProperty animationEnabled)
Definition at line 19 of file AnimatorFactory.java.
References model.state.gameelement.GameElementState.attributes, model.MainModel.fetchImageContainer(), engine.visuals.elementVisuals.animations.AnimatorState.getImageTag(), and model.state.gameelement.DrawableGameElementState.myAnimatorState.
Referenced by engine.elementFactories.VisualizerFactory.createVisualizer().
Member Data Documentation
MainModel engine.elementFactories.AnimatorFactory.myModel private
Definition at line 13 of file AnimatorFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/elementFactories/AnimatorFactory.java