voogasalad_TheException: view.editor.wizards.LevelWizard Class Reference
view.editor.wizards.LevelWizard Class Reference
Public Member Functions
boolean checkCanSave ()
void updateData ()
void initialize ()
void launchForEdit (WizardData oldValues)
void loadGlobalValues (List< String > values)
Public Member Functions inherited from view.editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
abstract void launchForEdit (WizardData oldValues)
abstract void loadGlobalValues (List< String > values)
WizardData getWizardData ()
void displayErrorMessage (String error)
void removeWizardData (WizardData data)
void setStage (Stage s)
void closeStage ()
Protected Member Functions
void attachTextProperties ()
Protected Member Functions inherited from view.editor.wizards.Wizard
void addToData (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void setWizardType (WizardType type)
void attachTextProperties ()
boolean isNumber (String value)
Private Member Functions
void selectBackground ()
Private Attributes
final String NEW_LEVEL_DEFAULT_KEY = "NewLevelDefault"
final String CAMPAIGN_KEY = "Campaign"
final String LEVEL_WIDTH_KEY = "LevelWidth"
final String LEVEL_HEIGHT_KEY = "LevelHeight"
final String BACKGROUND_KEY = "Background"
ComboBox< String > campaignName
TextField levelName
TextField levelWidth
TextField levelHeight
AnchorPane leftPane
Button image
ObservableList< String > campaigns
String backgroundPath
Additional Inherited Members
Static Public Attributes inherited from view.editor.wizards.Wizard
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
Protected Attributes inherited from view.editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Detailed Description
This is the concrete implementation of a Wizard used to create a new LevelState within our GameState. It is spawned within the file menu and holds two textfields for campaignName and campaignLevel. It is important to note that the Wizard does not hold the responsibility for checking whether or not the campaign actually exists because it has no knowledge of the GameState. Therefore, it will send this to the class which launches the wizard which should hold the checking knowledge.
Author
Nishad
Definition at line 33 of file LevelWizard.java.
Member Function Documentation
void view.editor.wizards.LevelWizard.attachTextProperties () protected
Definition at line 77 of file LevelWizard.java.
References view.editor.wizards.Wizard.displayErrorMessage(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
boolean view.editor.wizards.LevelWizard.checkCanSave ()
Definition at line 58 of file LevelWizard.java.
References view.editor.wizards.Wizard.isNumber().
void view.editor.wizards.LevelWizard.initialize ()
Implements view.gui.GUIController.
Definition at line 93 of file LevelWizard.java.
References view.editor.wizards.LevelWizard.selectBackground().
void view.editor.wizards.LevelWizard.launchForEdit (WizardData oldValues)
Definition at line 108 of file LevelWizard.java.
References model.data.WizardDataType.CAMPAIGN_NAME, model.data.WizardData.getValueByKey(), and model.data.WizardDataType.NAME.
void view.editor.wizards.LevelWizard.loadGlobalValues (List< String > values)
Definition at line 115 of file LevelWizard.java.
void view.editor.wizards.LevelWizard.selectBackground () private
Definition at line 101 of file LevelWizard.java.
Referenced by view.editor.wizards.LevelWizard.initialize().
void view.editor.wizards.LevelWizard.updateData ()
Definition at line 67 of file LevelWizard.java.
References view.editor.wizards.Wizard.addToData(), model.data.WizardDataType.CAMPAIGN_NAME, model.data.WizardDataType.HEIGHT, model.data.WizardDataType.IMAGE, model.data.WizardType.LEVEL, model.data.WizardDataType.NAME, view.editor.wizards.Wizard.setWizardType(), and model.data.WizardDataType.WIDTH.
Member Data Documentation
final String view.editor.wizards.LevelWizard.BACKGROUND_KEY = "Background" private
Definition at line 39 of file LevelWizard.java.
String view.editor.wizards.LevelWizard.backgroundPath private
Definition at line 55 of file LevelWizard.java.
final String view.editor.wizards.LevelWizard.CAMPAIGN_KEY = "Campaign" private
Definition at line 36 of file LevelWizard.java.
ComboBox<String> view.editor.wizards.LevelWizard.campaignName private
Definition at line 42 of file LevelWizard.java.
ObservableList<String> view.editor.wizards.LevelWizard.campaigns private
Definition at line 54 of file LevelWizard.java.
Button view.editor.wizards.LevelWizard.image private
Definition at line 52 of file LevelWizard.java.
AnchorPane view.editor.wizards.LevelWizard.leftPane private
Definition at line 50 of file LevelWizard.java.
final String view.editor.wizards.LevelWizard.LEVEL_HEIGHT_KEY = "LevelHeight" private
Definition at line 38 of file LevelWizard.java.
final String view.editor.wizards.LevelWizard.LEVEL_WIDTH_KEY = "LevelWidth" private
Definition at line 37 of file LevelWizard.java.
TextField view.editor.wizards.LevelWizard.levelHeight private
Definition at line 48 of file LevelWizard.java.
TextField view.editor.wizards.LevelWizard.levelName private
Definition at line 44 of file LevelWizard.java.
TextField view.editor.wizards.LevelWizard.levelWidth private
Definition at line 46 of file LevelWizard.java.
final String view.editor.wizards.LevelWizard.NEW_LEVEL_DEFAULT_KEY = "NewLevelDefault" private
Definition at line 35 of file LevelWizard.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/LevelWizard.java