voogasalad_TheException: model.state.gameelement.traits.AttributeDisplayerState Class Reference
model.state.gameelement.traits.AttributeDisplayerState Class Reference
Public Member Functions
AttributeDisplayerState (AttributeDisplayerTags displayerTag, String numericParameterTag, double minAttributeValue, double maxAttributeValue)
AttributeDisplayerState (AttributeDisplayerTags displayerTag, String textualParameterTag, String value)
AttributeDisplayerTags getDisplayerTag ()
String getParameterTag ()
double getMinValue ()
double getMaxValue ()
String getTextValue ()
Public Member Functions inherited from util.JSONable
default String toJSON ()
Private Attributes
AttributeDisplayerTags myDisplayerTags
String myParameterTag
double myMinAttributeValue
double myMaxAttributeValue
String myTextValue
Static Private Attributes
static final long serialVersionUID = -4791954709522087485L
Detailed Description
A wrapper for all the savable information needed to represent an attribute displayer. This is just a data wrapper and as such all of its instance variables are public.
Author
Zach, Michael D., Stanley
Definition at line 15 of file AttributeDisplayerState.java.
Constructor & Destructor Documentation
model.state.gameelement.traits.AttributeDisplayerState.AttributeDisplayerState (AttributeDisplayerTags displayerTag, String numericParameterTag, double minAttributeValue, double maxAttributeValue)
Constructor
Parameters
displayerTag The reference to a widget's class
numericParameterTag The attribute name
minAttributeValue The max attribute value
maxAttributeValue The min attribute value
BackgroundColor The color in the background
ForegroundColor The color in the foreground
Definition at line 40 of file AttributeDisplayerState.java.
model.state.gameelement.traits.AttributeDisplayerState.AttributeDisplayerState (AttributeDisplayerTags displayerTag, String textualParameterTag, String value)
Definition at line 48 of file AttributeDisplayerState.java.
Member Function Documentation
AttributeDisplayerTags model.state.gameelement.traits.AttributeDisplayerState.getDisplayerTag ()
Definition at line 55 of file AttributeDisplayerState.java.
References model.state.gameelement.traits.AttributeDisplayerState.myDisplayerTags.
Referenced by engine.elementFactories.AttributeDisplayerFactory.createAttributeDisplayer().
double model.state.gameelement.traits.AttributeDisplayerState.getMaxValue ()
Definition at line 67 of file AttributeDisplayerState.java.
References model.state.gameelement.traits.AttributeDisplayerState.myMaxAttributeValue.
Referenced by engine.elementFactories.AttributeDisplayerFactory.createNumericalAttributeDisplayer().
double model.state.gameelement.traits.AttributeDisplayerState.getMinValue ()
Definition at line 63 of file AttributeDisplayerState.java.
References model.state.gameelement.traits.AttributeDisplayerState.myMinAttributeValue.
Referenced by engine.elementFactories.AttributeDisplayerFactory.createNumericalAttributeDisplayer().
String model.state.gameelement.traits.AttributeDisplayerState.getParameterTag ()
Definition at line 59 of file AttributeDisplayerState.java.
References model.state.gameelement.traits.AttributeDisplayerState.myParameterTag.
Referenced by engine.elementFactories.AttributeDisplayerFactory.createNumericalAttributeDisplayer(), and engine.elementFactories.AttributeDisplayerFactory.createTextualAttributeDisplayer().
String model.state.gameelement.traits.AttributeDisplayerState.getTextValue ()
Definition at line 71 of file AttributeDisplayerState.java.
References model.state.gameelement.traits.AttributeDisplayerState.myTextValue.
Referenced by engine.elementFactories.AttributeDisplayerFactory.createAttributeDisplayer(), and engine.elementFactories.AttributeDisplayerFactory.createTextualAttributeDisplayer().
Member Data Documentation
AttributeDisplayerTags model.state.gameelement.traits.AttributeDisplayerState.myDisplayerTags private
Definition at line 18 of file AttributeDisplayerState.java.
Referenced by model.state.gameelement.traits.AttributeDisplayerState.getDisplayerTag().
double model.state.gameelement.traits.AttributeDisplayerState.myMaxAttributeValue private
Definition at line 21 of file AttributeDisplayerState.java.
Referenced by model.state.gameelement.traits.AttributeDisplayerState.getMaxValue().
double model.state.gameelement.traits.AttributeDisplayerState.myMinAttributeValue private
Definition at line 20 of file AttributeDisplayerState.java.
Referenced by model.state.gameelement.traits.AttributeDisplayerState.getMinValue().
String model.state.gameelement.traits.AttributeDisplayerState.myParameterTag private
Definition at line 19 of file AttributeDisplayerState.java.
Referenced by model.state.gameelement.traits.AttributeDisplayerState.getParameterTag().
String model.state.gameelement.traits.AttributeDisplayerState.myTextValue private
Definition at line 22 of file AttributeDisplayerState.java.
Referenced by model.state.gameelement.traits.AttributeDisplayerState.getTextValue().
final long model.state.gameelement.traits.AttributeDisplayerState.serialVersionUID = -4791954709522087485L static private
Definition at line 17 of file AttributeDisplayerState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/gameelement/traits/AttributeDisplayerState.java