voogasalad_TheException: engine.visuals.SelectionBox Class Reference
engine.visuals.SelectionBox Class Reference
Public Member Functions
SelectionBox ()
Rectangle getBox ()
double[] clickReleased (MouseEvent e, double mapTranslateX, double mapTranslateY)
void primaryClick (MouseEvent e)
void reactToDrag (MouseEvent e)
Package Attributes
double pressedY
Private Member Functions
void resetBox ()
void setSize (double width, double height)
void setX (double x)
void setY (double y)
void setLocation (double x, double y)
void setVisible (boolean b)
Private Attributes
Rectangle myRectangle
double pressedX
MouseEvent lastEvent
Detailed Description
The class for creating the rectangle that the user draws during a game with their cursor. Extends observable so that other classes that want to be notified of unit selection can see where the box was drawn
Author
John
Definition at line 17 of file SelectionBox.java.
Constructor & Destructor Documentation
engine.visuals.SelectionBox.SelectionBox ()
Definition at line 22 of file SelectionBox.java.
Member Function Documentation
double [] engine.visuals.SelectionBox.clickReleased (MouseEvent e, double mapTranslateX, double mapTranslateY)
Definition at line 61 of file SelectionBox.java.
References engine.visuals.SelectionBox.setVisible().
Referenced by engine.UI.RunnerInputManager.primaryClickReleaseOccurred().
Rectangle engine.visuals.SelectionBox.getBox ()
Definition at line 29 of file SelectionBox.java.
References engine.visuals.SelectionBox.myRectangle.
Referenced by engine.visuals.ScrollablePane.ScrollablePane().
void engine.visuals.SelectionBox.primaryClick (MouseEvent e)
Definition at line 71 of file SelectionBox.java.
References engine.visuals.SelectionBox.resetBox(), and engine.visuals.SelectionBox.setLocation().
Referenced by engine.UI.RunnerInputManager.primaryClickOccurred().
void engine.visuals.SelectionBox.reactToDrag (MouseEvent e)
Definition at line 80 of file SelectionBox.java.
References engine.visuals.SelectionBox.pressedX, engine.visuals.SelectionBox.pressedY, engine.visuals.SelectionBox.setSize(), engine.visuals.SelectionBox.setVisible(), engine.visuals.SelectionBox.setX(), and engine.visuals.SelectionBox.setY().
Referenced by engine.UI.RunnerInputManager.primaryDragOccurred().
void engine.visuals.SelectionBox.resetBox () private
Definition at line 33 of file SelectionBox.java.
References engine.visuals.SelectionBox.setLocation(), and engine.visuals.SelectionBox.setSize().
Referenced by engine.visuals.SelectionBox.primaryClick().
void engine.visuals.SelectionBox.setLocation (double x, double y) private
Definition at line 52 of file SelectionBox.java.
References engine.visuals.SelectionBox.setX(), and engine.visuals.SelectionBox.setY().
Referenced by engine.visuals.SelectionBox.primaryClick(), and engine.visuals.SelectionBox.resetBox().
void engine.visuals.SelectionBox.setSize (double width, double height) private
Definition at line 39 of file SelectionBox.java.
Referenced by engine.visuals.SelectionBox.reactToDrag(), and engine.visuals.SelectionBox.resetBox().
void engine.visuals.SelectionBox.setVisible (boolean b) private
Definition at line 57 of file SelectionBox.java.
Referenced by engine.visuals.SelectionBox.clickReleased(), and engine.visuals.SelectionBox.reactToDrag().
void engine.visuals.SelectionBox.setX (double x) private
Definition at line 44 of file SelectionBox.java.
Referenced by engine.visuals.SelectionBox.reactToDrag(), and engine.visuals.SelectionBox.setLocation().
void engine.visuals.SelectionBox.setY (double y) private
Definition at line 48 of file SelectionBox.java.
Referenced by engine.visuals.SelectionBox.reactToDrag(), and engine.visuals.SelectionBox.setLocation().
Member Data Documentation
MouseEvent engine.visuals.SelectionBox.lastEvent private
Definition at line 20 of file SelectionBox.java.
Rectangle engine.visuals.SelectionBox.myRectangle private
Definition at line 18 of file SelectionBox.java.
Referenced by engine.visuals.SelectionBox.getBox().
double engine.visuals.SelectionBox.pressedX private
Definition at line 19 of file SelectionBox.java.
Referenced by engine.visuals.SelectionBox.reactToDrag().
double engine.visuals.SelectionBox.pressedY package
Definition at line 19 of file SelectionBox.java.
Referenced by engine.visuals.SelectionBox.reactToDrag().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/SelectionBox.java