voogasalad_TheException: view.editor.EditorMenuBarController Class Reference
view.editor.EditorMenuBarController Class Reference
Public Member Functions
void initMenuBar ()
Public Member Functions inherited from view.gui.MenuBarController
void attachScreen (GUIScreen screen)
Node getRoot ()
void modelUpdate ()
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Protected Member Functions
void bindTextProperties () throws LanguageException
Protected Member Functions inherited from view.gui.MenuBarController
final void init ()
abstract void initMenuBar ()
abstract void bindTextProperties () throws LanguageException
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Private Member Functions
void initFileMenu ()
void saveGame ()
void onNewLevelClick ()
void onNewCampaignClick ()
Private Attributes
MenuItem newCampaignMenuItem
MenuItem newLevelMenuItem
Static Private Attributes
static final String NEW_CAMPAIGN_KEY = "NewCampaign"
static final String NEW_LEVEL_KEY = "NewLevel"
Additional Inherited Members
Protected Attributes inherited from view.gui.MenuBarController
MenuItem saveMenuItem
MenuItem quitMenuItem
Menu fileMenu
MenuBar menuBar
Menu languageMenu
GUIScreen myScreen
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Detailed Description
Author
Nishad Agrawal
Jonathan Tseng
Definition at line 26 of file EditorMenuBarController.java.
Member Function Documentation
void view.editor.EditorMenuBarController.bindTextProperties () throws LanguageException protected
Definition at line 42 of file EditorMenuBarController.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
void view.editor.EditorMenuBarController.initFileMenu () private
Definition at line 48 of file EditorMenuBarController.java.
References view.gui.MenuBarController.myScreen, view.editor.EditorMenuBarController.onNewCampaignClick(), view.editor.EditorMenuBarController.onNewLevelClick(), view.gui.MenuBarController.quitMenuItem, view.editor.EditorMenuBarController.saveGame(), view.gui.MenuBarController.saveMenuItem, view.gui.ViewScreenPath.SPLASH, and view.gui.GUIScreen.switchScreen().
Referenced by view.editor.EditorMenuBarController.initMenuBar().
void view.editor.EditorMenuBarController.initMenuBar ()
Definition at line 37 of file EditorMenuBarController.java.
References view.editor.EditorMenuBarController.initFileMenu().
void view.editor.EditorMenuBarController.onNewCampaignClick () private
Definition at line 82 of file EditorMenuBarController.java.
References view.gui.GUIPanePath.CAMPAIGN_WIZARD, view.editor.wizards.Wizard.closeStage(), model.MainModel.createCampaign(), view.editor.wizards.Wizard.displayErrorMessage(), view.editor.wizards.WizardUtility.loadWizard(), view.gui.GUIContainer.myMainModel, model.data.WizardDataType.NAME, and view.editor.wizards.Wizard.setSubmit().
Referenced by view.editor.EditorMenuBarController.initFileMenu().
void view.editor.EditorMenuBarController.onNewLevelClick () private
Definition at line 60 of file EditorMenuBarController.java.
References model.data.WizardDataType.CAMPAIGN_NAME, view.editor.wizards.Wizard.closeStage(), model.MainModel.createLevel(), view.editor.wizards.Wizard.displayErrorMessage(), model.state.GameState.getCampaigns(), model.MainModel.getCurrentGame(), model.data.WizardDataType.HEIGHT, model.data.WizardDataType.IMAGE, view.gui.GUIPanePath.LEVEL_WIZARD, view.editor.wizards.Wizard.loadGlobalValues(), view.editor.wizards.WizardUtility.loadWizard(), view.gui.GUIContainer.myMainModel, model.data.WizardDataType.NAME, view.editor.wizards.Wizard.setSubmit(), and model.data.WizardDataType.WIDTH.
Referenced by view.editor.EditorMenuBarController.initFileMenu().
void view.editor.EditorMenuBarController.saveGame () private
Definition at line 55 of file EditorMenuBarController.java.
References view.gui.GUIContainer.myMainModel, view.gui.MenuBarController.myScreen, and model.MainModel.saveGame().
Referenced by view.editor.EditorMenuBarController.initFileMenu().
Member Data Documentation
final String view.editor.EditorMenuBarController.NEW_CAMPAIGN_KEY = "NewCampaign" static private
Definition at line 28 of file EditorMenuBarController.java.
final String view.editor.EditorMenuBarController.NEW_LEVEL_KEY = "NewLevel" static private
Definition at line 29 of file EditorMenuBarController.java.
MenuItem view.editor.EditorMenuBarController.newCampaignMenuItem private
Definition at line 32 of file EditorMenuBarController.java.
MenuItem view.editor.EditorMenuBarController.newLevelMenuItem private
Definition at line 34 of file EditorMenuBarController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/EditorMenuBarController.java