voogasalad_TheException: game_engine.Engine Class Reference
game_engine.Engine Class Reference
Public Member Functions
Engine (MainModel mainModel)
Group getVisualRepresentation ()
void selectLevel (String campaignName, String levelName) throws DescribableStateException
void play ()
void pause ()
MiniMap getMiniMap ()
void update (Observable observable, Object arg)
ScrollablePane getScene ()
Private Member Functions
void updateGameLoop (LevelState levelState, String currentCampaign)
Private Attributes
MainModel myMainModel
GameLoop myGameLoop
GameElementManager myElementManager
VisualManager myVisualManager
InputManager myInputManager
MiniMap myMiniMap
GameElementFactory myElementFactory
LevelFactory myLevelFactory
Detailed Description
The concrete boundary of the Engine - this class exposes the public API of the Engine to the rest of the project.
Author
Steve, Jonathan, Nishad, Rahul, Michael D.
Definition at line 29 of file Engine.java.
Constructor & Destructor Documentation
game_engine.Engine.Engine (MainModel mainModel)
Definition at line 40 of file Engine.java.
References gamemodel.MainModel.getGameUniverse(), game_engine.visuals.Dimension.getHeight(), game_engine.visuals.VisualManager.getScrollingScene(), application.ShittyMain.screenSize, and application.ShittyMain.shittyWidth.
Member Function Documentation
MiniMap game_engine.Engine.getMiniMap ()
Definition at line 84 of file Engine.java.
References game_engine.Engine.myMiniMap.
ScrollablePane game_engine.Engine.getScene ()
Definition at line 95 of file Engine.java.
References game_engine.visuals.VisualManager.getScrollingScene().
Referenced by application.ShittyMain.start().
Group game_engine.Engine.getVisualRepresentation ()
Definition at line 55 of file Engine.java.
References game_engine.visuals.VisualManager.getVisualRepresentation().
void game_engine.Engine.pause ()
Definition at line 80 of file Engine.java.
References game_engine.stateManaging.GameLoop.pause().
void game_engine.Engine.play ()
Definition at line 75 of file Engine.java.
References gamemodel.MainModel.getCurrentCampaign(), gamemodel.MainModel.getCurrentLevel(), game_engine.gameRepresentation.stateRepresentation.DescribableState.getName(), game_engine.stateManaging.GameLoop.play(), and game_engine.Engine.updateGameLoop().
Referenced by application.ShittyMain.start().
void game_engine.Engine.selectLevel (String campaignName, String levelName) throws DescribableStateException
Definition at line 61 of file Engine.java.
References game_engine.visuals.VisualManager.addBoxObserver(), game_engine.UI.InputManager.addClickObserver(), game_engine.UI.InputManager.addKeyboardObserver(), game_engine.visuals.VisualManager.addMiniMap(), game_engine.visuals.VisualManager.addObjects(), game_engine.elementFactories.LevelFactory.createLevel(), gamemodel.MainModel.getCurrentLevel(), game_engine.visuals.MiniMap.getDisplay(), gamemodel.MainModel.setCurrentLevel(), and game_engine.visuals.MiniMap.setUnits().
void game_engine.Engine.update (Observable observable, Object arg)
Definition at line 89 of file Engine.java.
References gamemodel.MainModel.getCurrentCampaign(), gamemodel.MainModel.getCurrentLevel(), game_engine.gameRepresentation.stateRepresentation.DescribableState.getName(), and game_engine.Engine.updateGameLoop().
void game_engine.Engine.updateGameLoop (LevelState levelState, String currentCampaign) private
Definition at line 99 of file Engine.java.
References game_engine.visuals.VisualManager.addBoxObserver(), game_engine.UI.InputManager.addClickObserver(), game_engine.UI.InputManager.addKeyboardObserver(), game_engine.visuals.VisualManager.addMiniMap(), game_engine.visuals.VisualManager.addObjects(), game_engine.elementFactories.LevelFactory.createLevel(), gamemodel.MainModel.getCurrentLevel(), game_engine.visuals.MiniMap.getDisplay(), game_engine.stateManaging.GameLoop.isCurrentLevel(), and game_engine.visuals.MiniMap.setUnits().
Referenced by game_engine.Engine.play(), and game_engine.Engine.update().
Member Data Documentation
GameElementFactory game_engine.Engine.myElementFactory private
Definition at line 37 of file Engine.java.
GameElementManager game_engine.Engine.myElementManager private
Definition at line 33 of file Engine.java.
GameLoop game_engine.Engine.myGameLoop private
Definition at line 32 of file Engine.java.
InputManager game_engine.Engine.myInputManager private
Definition at line 35 of file Engine.java.
LevelFactory game_engine.Engine.myLevelFactory private
Definition at line 38 of file Engine.java.
MainModel game_engine.Engine.myMainModel private
Definition at line 31 of file Engine.java.
MiniMap game_engine.Engine.myMiniMap private
Definition at line 36 of file Engine.java.
Referenced by game_engine.Engine.getMiniMap().
VisualManager game_engine.Engine.myVisualManager private
Definition at line 34 of file Engine.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/Engine.java