voogasalad_TheException: engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer Class Reference
engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer Class Reference abstract
Public Member Functions
AttributeDisplayer (AttributeContainer attributes, String numericParameterTag, double minValue, double maxValue)
AttributeDisplayer (AttributeContainer attributes, String numericParameterTag, String value)
void registerAsComponent (Consumer< Node > registeringFunction)
boolean update ()
Protected Member Functions
void toggleOpacity ()
abstract Group createDisplay ()
abstract void updateDisplay (double attributeValue, double attributeMinValue, double attributeMaxValue)
Protected Attributes
Group myGroup
Private Attributes
AttributeContainer attributesOfInterest
String myParameterTag
double myMinValue
double myMaxValue
String myTextValue
Detailed Description
A parent class for a basic visual element that displays an attribute of an element and updates its visual representation.
Author
Zach, Stanley
Definition at line 18 of file AttributeDisplayer.java.
Constructor & Destructor Documentation
engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.AttributeDisplayer (AttributeContainer attributes, String numericParameterTag, double minValue, double maxValue)
Create an attribute displayer
Parameters
attributes the element whose attribute will be reflected
numericParameterTag the tag of the numeric parameter to display
minValue the min value of the parameter
maxValue the max value of the parameter
Definition at line 39 of file AttributeDisplayer.java.
References engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.createDisplay().
engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.AttributeDisplayer (AttributeContainer attributes, String numericParameterTag, String value)
Definition at line 48 of file AttributeDisplayer.java.
References engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.createDisplay().
Member Function Documentation
abstract Group engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.createDisplay () abstract protected
Create the display for the graphical element
Returns
a group containing the visual representation for the element
Referenced by engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.AttributeDisplayer().
void engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.registerAsComponent (Consumer< Node > registeringFunction)
Implements engine.visuals.elementVisuals.widgets.Widget.
Definition at line 57 of file AttributeDisplayer.java.
Referenced by engine.visuals.elementVisuals.Visualizer.addWidget().
void engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.toggleOpacity () protected
Hide the displayable widget if the player is not selected
Definition at line 73 of file AttributeDisplayer.java.
References model.state.gameelement.AttributeContainer.getNumericalAttribute(), and model.state.gameelement.StateTags.IS_SELECTED.
Referenced by engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.update().
boolean engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.update ()
Update the object
Returns
a boolean status for the update
Implements model.state.gameelement.traits.Updatable.
Definition at line 62 of file AttributeDisplayer.java.
References engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.toggleOpacity(), and engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.updateDisplay().
abstract void engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.updateDisplay (double attributeValue, double attributeMinValue, double attributeMaxValue) abstract protected
Update the display of the attribute displayer
Parameters
attributeValue the attribute's value
attributeMinValue the minimum value of the attribute
attributeMaxValue the maximum value of the attribute
Referenced by engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.update().
Member Data Documentation
AttributeContainer engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.attributesOfInterest private
Definition at line 21 of file AttributeDisplayer.java.
Group engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.myGroup protected
Definition at line 20 of file AttributeDisplayer.java.
double engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.myMaxValue private
Definition at line 24 of file AttributeDisplayer.java.
double engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.myMinValue private
Definition at line 23 of file AttributeDisplayer.java.
String engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.myParameterTag private
Definition at line 22 of file AttributeDisplayer.java.
String engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.myTextValue private
Definition at line 25 of file AttributeDisplayer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/elementVisuals/widgets/attributeDisplays/AttributeDisplayer.java