voogasalad_TheException: vooga.request.forwarder.IForwarder Interface Reference
vooga.request.forwarder.IForwarder Interface Reference
Public Member Functions
void forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
void register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
void forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
void register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
Detailed Description
An interface which forwards IRequests between registered IReceivers.
Definition at line 9 of file IForwarder.java.
Member Function Documentation
void vooga.request.forwarder.IForwarder.forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
Forward a request to a recipient based on the details of that request
Parameters
request The request to forward
Exceptions
InvalidAddressException If the sender or receiver addresses are invalid
ReceiverNotFoundException If the receiver is not registered with this forwarder
DeliveryException If a problem occurs during delivery of the message to a receiver
Implemented in vooga.request.forwarder.RequestMediator, and vooga.request.forwarder.RequestMediator.
Referenced by test.request.ReceiverTestStub.receive(), test.request.RequestMediatorTest.testReceiverNotFoundException(), test.request.RequestMediatorTest.testSendPingPong(), and test.request.RequestMediatorTest.testSendToSelf().
void vooga.request.forwarder.IForwarder.forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
Forward a request to a recipient based on the details of that request
Parameters
request The request to forward
Exceptions
InvalidAddressException If the sender or receiver addresses are invalid
ReceiverNotFoundException If the receiver is not registered with this forwarder
DeliveryException If a problem occurs during delivery of the message to a receiver
Implemented in vooga.request.forwarder.RequestMediator, and vooga.request.forwarder.RequestMediator.
void vooga.request.forwarder.IForwarder.register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
Register a receiver that can receive messages via forward()
Parameters
address The address where the receiver can receive requests
receiver The receiver associated with the address
Exceptions
InvalidAddressException If the format of the address is not allowed by the forwarder
AddressConflictException If the address is already used by another receiver
Implemented in vooga.request.forwarder.RequestMediator, and vooga.request.forwarder.RequestMediator.
void vooga.request.forwarder.IForwarder.register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
Register a receiver that can receive messages via forward()
Parameters
address The address where the receiver can receive requests
receiver The receiver associated with the address
Exceptions
InvalidAddressException If the format of the address is not allowed by the forwarder
AddressConflictException If the address is already used by another receiver
Implemented in vooga.request.forwarder.RequestMediator, and vooga.request.forwarder.RequestMediator.
Referenced by test.request.RequestMediatorTest.setup(), and test.request.RequestMediatorTest.testAddressConflictException().
The documentation for this interface was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/build/build/src/vooga/request/forwarder/IForwarder.java