voogasalad_TheException: engine.visuals.VisualManager Class Reference
engine.visuals.VisualManager Class Reference
Public Member Functions
VisualManager (Group gameObjectVisuals, double fieldWidth, double fieldHeight, String backgroundURI)
ScrollablePane getScrollingScene ()
void changeBackground (String backgroundURI)
void update (List< SelectableGameElement > list)
Group getVisualRepresentation ()
void addObject (Group g)
void removeObject (Group g)
ScrollableBackground getBackground ()
void attachInputManager (InputManager inputManager)
void attachParticipantManager (ParticipantManager participantManager)
void drawWayPointLines (List< SelectableGameElement > units)
Private Member Functions
SelectableGameElement findFirstSelectedElement (List< SelectableGameElement > list, Participant user)
Private Attributes
StatisticsBox myStatisticsBox
ScrollablePane scene
ScrollableBackground background
MiniMap myMiniMap
AbilityMatrix myAbilityMatrix
Group root
ParticipantManager myParticipantManager
List< Line > unitPaths
Detailed Description
The class containing the visual IO and UI pieces for the player. Manages retrieving and allowing observers to react to IO for clicking and key presses, as well as scrolling the map
Author
John, Michael D.
Definition at line 24 of file VisualManager.java.
Constructor & Destructor Documentation
engine.visuals.VisualManager.VisualManager (Group gameObjectVisuals, double fieldWidth, double fieldHeight, String backgroundURI)
Creates a new VisualManager. One visual manager should be created for every Scene (map)
Parameters
gameObjectVisuals the group for initial objects on the map. If no objects yet exist, add an empty new Group()
fieldWidth the width of the map to create
fieldHeight the height of the map to create
Definition at line 42 of file VisualManager.java.
References engine.visuals.ScrollablePane.addToScene(), engine.visuals.MiniMap.getDisplay(), engine.visuals.AbilityMatrix.getNode(), and engine.visuals.ScrollablePane.getScrollingBackground().
Member Function Documentation
void engine.visuals.VisualManager.addObject (Group g)
Adds new objects to the map
Parameters
g
Definition at line 112 of file VisualManager.java.
References engine.visuals.ScrollableBackground.addObjects().
Referenced by engine.Engine.instantiateManagers().
void engine.visuals.VisualManager.attachInputManager (InputManager inputManager)
Definition at line 134 of file VisualManager.java.
References engine.visuals.AbilityMatrix.attachInputManager(), and engine.visuals.ScrollablePane.attachInputManager().
Referenced by engine.Engine.instantiateManagers(), and engine.Engine.setInputManager().
void engine.visuals.VisualManager.attachParticipantManager (ParticipantManager participantManager)
Definition at line 140 of file VisualManager.java.
References engine.visuals.ScrollablePane.addToScene().
Referenced by engine.Engine.instantiateManagers().
void engine.visuals.VisualManager.changeBackground (String backgroundURI)
Definition at line 64 of file VisualManager.java.
References engine.visuals.ScrollablePane.changeBackground().
void engine.visuals.VisualManager.drawWayPointLines (List< SelectableGameElement > units)
Definition at line 147 of file VisualManager.java.
References engine.visuals.VisualManager.getBackground().
SelectableGameElement engine.visuals.VisualManager.findFirstSelectedElement (List< SelectableGameElement > list, Participant user) private
Definition at line 86 of file VisualManager.java.
References engine.users.Participant.checkSameTeam(), model.state.gameelement.StateTags.IS_SELECTED, and model.state.gameelement.StateTags.TEAM_COLOR.
Referenced by engine.visuals.VisualManager.update().
ScrollableBackground engine.visuals.VisualManager.getBackground ()
gets the ScrollableBackground that represents the map
Returns
the map's scrollablebackground representation
Definition at line 130 of file VisualManager.java.
References engine.visuals.VisualManager.background.
Referenced by engine.visuals.VisualManager.drawWayPointLines().
ScrollablePane engine.visuals.VisualManager.getScrollingScene ()
Gets the background scene in order to display
Returns
the Scene object that represents the map
Definition at line 60 of file VisualManager.java.
References engine.visuals.VisualManager.scene.
Referenced by engine.Engine.getScene().
Group engine.visuals.VisualManager.getVisualRepresentation ()
Gets the group containing all elements added to the map
Returns
the group containing all nodes that have been added to the map. These will only have the JavaFX nodes, not all the states
Definition at line 102 of file VisualManager.java.
void engine.visuals.VisualManager.removeObject (Group g)
Remove an object from the display
Parameters
g the group of the object to remove
Definition at line 121 of file VisualManager.java.
References engine.visuals.ScrollableBackground.removeObjects().
void engine.visuals.VisualManager.update (List< SelectableGameElement > list)
updates the scene, should be called in each KeyFrame so that the background can update appropriately with scrolling
Definition at line 72 of file VisualManager.java.
References engine.visuals.VisualManager.findFirstSelectedElement(), engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getAbilityDescriptionMap(), engine.gameRepresentation.renderedRepresentation.GameElement.getTimersCopy(), engine.UI.ParticipantManager.getUser(), engine.visuals.AbilityMatrix.NUM_ATTRIBUTES, engine.visuals.ScrollablePane.update(), engine.visuals.AbilityMatrix.updateGridImages(), and engine.visuals.MiniMap.updateMiniMap().
Referenced by engine.stateManaging.GameLoop.updateEditor(), and engine.stateManaging.GameLoop.updateRunner().
Member Data Documentation
ScrollableBackground engine.visuals.VisualManager.background private
Definition at line 27 of file VisualManager.java.
Referenced by engine.visuals.VisualManager.getBackground().
AbilityMatrix engine.visuals.VisualManager.myAbilityMatrix private
Definition at line 29 of file VisualManager.java.
MiniMap engine.visuals.VisualManager.myMiniMap private
Definition at line 28 of file VisualManager.java.
ParticipantManager engine.visuals.VisualManager.myParticipantManager private
Definition at line 31 of file VisualManager.java.
StatisticsBox engine.visuals.VisualManager.myStatisticsBox private
Definition at line 25 of file VisualManager.java.
Group engine.visuals.VisualManager.root private
Definition at line 30 of file VisualManager.java.
ScrollablePane engine.visuals.VisualManager.scene private
Definition at line 26 of file VisualManager.java.
Referenced by engine.visuals.VisualManager.getScrollingScene().
List<Line> engine.visuals.VisualManager.unitPaths private
Definition at line 32 of file VisualManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/VisualManager.java