voogasalad_TheException: engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B > Class Template Reference
engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B > Class Template Reference
Public Member Functions
Bounce (Evaluatable< A > parameter1, Evaluatable< B > parameter2)
Public Member Functions inherited from engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Boolean >
Evaluator (Class< T > type, String evaluatorRepresentation, Evaluatable< A > parameter1, Evaluatable< B > parameter2)
T evaluate (ElementPair elements)
T delegateEvaluator (A parameter1Value, B parameter2Value)
String toString ()
Protected Member Functions
Boolean evaluate (GameElement element1, GameElement element2)
Protected Member Functions inherited from engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Boolean >
T evaluate (Object item1, Object item2)
T evaluate (Number item1, Number item2)
T evaluate (Boolean item1, Boolean item2)
T evaluate (GameElement item1, GameElement item2)
T evaluate (GameElement item1, String item2)
T evaluate (GameElement item1, ActionRepresentation item2)
T evaluate (GameElement item1, ElementPromise item2)
Evaluatable< A > getParameter1 ()
Evaluatable< B > getParameter2 ()
boolean setParameter1Value (Object value)
boolean setParameter2Value (Object value)
Private Member Functions
Point2D getCenter (GameElement element)
Detailed Description
An evaluator that implements classical game bouncing. element 1 bounces off of element 2
Author
Zach
Definition at line 17 of file Bounce.java.
Constructor & Destructor Documentation
engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.Bounce (Evaluatable< A > parameter1, Evaluatable< B > parameter2)
Definition at line 19 of file Bounce.java.
Member Function Documentation
Boolean engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.evaluate (GameElement element1, GameElement element2) protected
Definition at line 24 of file Bounce.java.
References engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.getCenter(), engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), model.state.gameelement.StateTags.MOVEMENT_SPEED, engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute(), model.state.gameelement.StateTags.X_VELOCITY, and model.state.gameelement.StateTags.Y_VELOCITY.
Point2D engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.getCenter (GameElement element) private
Get the center of one element
Parameters
element
Returns
a Point2D of the element center
Definition at line 46 of file Bounce.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
Referenced by engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.evaluate().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/evaluatables/evaluators/Bounce.java