voogasalad_TheException: engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory Class Reference
engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory Class Reference
Public Member Functions
AttributeDisplayer createAttributeDisplayer (AttributeDisplayerState attributeDisplayerState, AttributeContainer attachee)
Static Public Attributes
static final String ATTRIBUTE_CLASS_LOCATIONS = "engine.visuals.elementVisuals.widgets.attributeDisplays."
Private Member Functions
AttributeDisplayer createNumericalAttributeDisplayer (Class<?> c, AttributeDisplayerState attributeDisplayerState, AttributeContainer attachee)
AttributeDisplayer createTextualAttributeDisplayer (Class<?> c, AttributeDisplayerState attributeDisplayerState, AttributeContainer attachee)
Detailed Description
A class that uses the factory pattern to create attribute displayers given the game element to attach to and the AttributeDisplayerState to display.
Author
Zach, Michael D., Stanley
Definition at line 14 of file AttributeDisplayerFactory.java.
Member Function Documentation
AttributeDisplayer engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createAttributeDisplayer (AttributeDisplayerState attributeDisplayerState, AttributeContainer attachee)
Create an attribute displayer.
Parameters
attributeDisplayerState the state of the attribute displayer
attachee the game element to attach the attribute displayer to.
Returns
Definition at line 26 of file AttributeDisplayerFactory.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createNumericalAttributeDisplayer(), engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createTextualAttributeDisplayer(), engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getDisplayerTag(), engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getTextValue(), and engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerTags.getValue().
AttributeDisplayer engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createNumericalAttributeDisplayer (Class<?> c, AttributeDisplayerState attributeDisplayerState, AttributeContainer attachee) private
Definition at line 47 of file AttributeDisplayerFactory.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getMaxValue(), engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getMinValue(), and engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getParameterTag().
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createAttributeDisplayer().
AttributeDisplayer engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createTextualAttributeDisplayer (Class<?> c, AttributeDisplayerState attributeDisplayerState, AttributeContainer attachee) private
Definition at line 66 of file AttributeDisplayerFactory.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getParameterTag(), and engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getTextValue().
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createAttributeDisplayer().
Member Data Documentation
final String engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.ATTRIBUTE_CLASS_LOCATIONS = "engine.visuals.elementVisuals.widgets.attributeDisplays." static
Definition at line 15 of file AttributeDisplayerFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/renderedRepresentation/attributeDisplayer/AttributeDisplayerFactory.java