voogasalad_TheException: game_engine.gameRepresentation.renderedRepresentation.Level Class Reference
game_engine.gameRepresentation.renderedRepresentation.Level Class Reference
Public Member Functions
Level (LevelState levelState, List< DrawableGameElement > terrain, List< SelectableGameElement > units, List< GameElement > goals, Group terrainAndBuildingsGroup, Group unitsGroup, MapGrid grid)
LevelState getLevelState ()
String getName ()
String getDescription ()
MapGrid getGrid ()
List< DrawableGameElement > getTerrain ()
List< SelectableGameElement > getUnits ()
List< GameElement > getGoals ()
List< Group > getGroups ()
void addElement (GameElement newElement)
void addElement (DrawableGameElement newElement)
void addElement (SelectableGameElement newElement)
Private Attributes
LevelState myState
Group myTerrainAndBuildingsGroup
Group myUnitsGroup
MapGrid myGrid
List< DrawableGameElement > myTerrain
List< SelectableGameElement > myUnits
List< GameElement > myGoals
Detailed Description
The representation of a basic level in the game. Contains a state of the level, a display group, lists of terrains and units, and a list of goals for the level. Essentially acts as a displayable wrapper around the serializable levelState object.
Author
Jonathan, Nishad, Rahul
Definition at line 19 of file Level.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.renderedRepresentation.Level.Level (LevelState levelState, List< DrawableGameElement > terrain, List< SelectableGameElement > units, List< GameElement > goals, Group terrainAndBuildingsGroup, Group unitsGroup, MapGrid grid)
Take in a level state and create the visual representation of the level from it.
Parameters
levelState
Definition at line 34 of file Level.java.
Member Function Documentation
void game_engine.gameRepresentation.renderedRepresentation.Level.addElement (GameElement newElement)
Definition at line 85 of file Level.java.
Referenced by game_engine.stateManaging.GameElementManager.addDrawableGameElementToLevel(), game_engine.stateManaging.GameElementManager.addGameElementToLevel(), and game_engine.stateManaging.GameElementManager.addSelectableGameElementToLevel().
void game_engine.gameRepresentation.renderedRepresentation.Level.addElement (DrawableGameElement newElement)
Definition at line 89 of file Level.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.BLOCKING, game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getBounds(), game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode(), game_engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), and game_engine.computers.pathingComputers.MapGrid.registerObstaclePlacement().
void game_engine.gameRepresentation.renderedRepresentation.Level.addElement (SelectableGameElement newElement)
Definition at line 97 of file Level.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.BLOCKING, game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getBounds(), game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode(), game_engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.MOVEMENT_SPEED, and game_engine.computers.pathingComputers.MapGrid.registerObstaclePlacement().
String game_engine.gameRepresentation.renderedRepresentation.Level.getDescription ()
Definition at line 58 of file Level.java.
References game_engine.gameRepresentation.stateRepresentation.DescribableState.getDescription().
List<GameElement> game_engine.gameRepresentation.renderedRepresentation.Level.getGoals ()
Definition at line 74 of file Level.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.myGoals.
MapGrid game_engine.gameRepresentation.renderedRepresentation.Level.getGrid ()
Definition at line 62 of file Level.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.myGrid.
List<Group> game_engine.gameRepresentation.renderedRepresentation.Level.getGroups ()
Definition at line 78 of file Level.java.
LevelState game_engine.gameRepresentation.renderedRepresentation.Level.getLevelState ()
Definition at line 50 of file Level.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.myState.
String game_engine.gameRepresentation.renderedRepresentation.Level.getName ()
Definition at line 54 of file Level.java.
References game_engine.gameRepresentation.stateRepresentation.DescribableState.getName().
Referenced by game_engine.stateManaging.GameLoop.isCurrentLevel().
List<DrawableGameElement> game_engine.gameRepresentation.renderedRepresentation.Level.getTerrain ()
Definition at line 66 of file Level.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.myTerrain.
List<SelectableGameElement> game_engine.gameRepresentation.renderedRepresentation.Level.getUnits ()
Definition at line 70 of file Level.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.myUnits.
Referenced by game_engine.stateManaging.GameLoop.addColisionEvents(), game_engine.stateManaging.GameLoop.addPathsToRoot(), game_engine.stateManaging.GameElementManager.findAllElementsOfType(), game_engine.stateManaging.GameElementManager.selectUnitsBox(), game_engine.stateManaging.GameElementManager.selectUnitsClick(), game_engine.stateManaging.GameElementManager.sendClickToSelectedUnits(), and game_engine.stateManaging.GameLoop.update().
Member Data Documentation
List<GameElement> game_engine.gameRepresentation.renderedRepresentation.Level.myGoals private
Definition at line 27 of file Level.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.getGoals().
MapGrid game_engine.gameRepresentation.renderedRepresentation.Level.myGrid private
Definition at line 24 of file Level.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.getGrid().
LevelState game_engine.gameRepresentation.renderedRepresentation.Level.myState private
Definition at line 21 of file Level.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.getLevelState().
List<DrawableGameElement> game_engine.gameRepresentation.renderedRepresentation.Level.myTerrain private
Definition at line 25 of file Level.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.getTerrain().
Group game_engine.gameRepresentation.renderedRepresentation.Level.myTerrainAndBuildingsGroup private
Definition at line 22 of file Level.java.
List<SelectableGameElement> game_engine.gameRepresentation.renderedRepresentation.Level.myUnits private
Definition at line 26 of file Level.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Group game_engine.gameRepresentation.renderedRepresentation.Level.myUnitsGroup private
Definition at line 23 of file Level.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/renderedRepresentation/Level.java