voogasalad_TheException: editor.ElementAccordianController Class Reference
editor.ElementAccordianController Class Reference
Public Member Functions
Node getRoot ()
void initialize ()
void update ()
Public Member Functions inherited from view.GUIContainer
void setModel (MainModel model)
final void update (Observable o, Object arg)
abstract void update ()
Private Attributes
Accordion elementAccordian
Additional Inherited Members
Protected Member Functions inherited from view.GUIContainer
void attachChildContainers (GUIContainer...child)
void clearChildContainers ()
Protected Attributes inherited from view.GUIContainer
MainModel myMainModel
Detailed Description
Definition at line 12 of file ElementAccordianController.java.
Member Function Documentation
Node editor.ElementAccordianController.getRoot ()
Implements view.GUIController.
Definition at line 18 of file ElementAccordianController.java.
void editor.ElementAccordianController.initialize ()
Implements view.GUIController.
Definition at line 23 of file ElementAccordianController.java.
References editor.ElementDropDownControl.addElement(), editor.ElementDropDownControl.getRoot(), and editor.ElementDropDownControl.setGameElement().
void editor.ElementAccordianController.update ()
Definition at line 35 of file ElementAccordianController.java.
Member Data Documentation
Accordion editor.ElementAccordianController.elementAccordian private
Definition at line 15 of file ElementAccordianController.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/ElementAccordianController.java