voogasalad_TheException: view.editor.wizards.NumberAttributeWizard Class Reference
view.editor.wizards.NumberAttributeWizard Class Reference
Public Member Functions
boolean checkCanSave ()
void initialize ()
void updateData ()
Public Member Functions inherited from view.editor.wizards.AttributeWizard
boolean checkCanSave ()
void updateData ()
void initialize ()
void launchForEdit (WizardData oldValues)
void loadGlobalValues (List< String > values)
Public Member Functions inherited from view.editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
abstract void launchForEdit (WizardData oldValues)
abstract void loadGlobalValues (List< String > values)
WizardData getWizardData ()
void displayErrorMessage (String error)
void removeWizardData (WizardData data)
void setStage (Stage s)
void closeStage ()
Additional Inherited Members
Static Public Attributes inherited from view.editor.wizards.Wizard
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
Protected Member Functions inherited from view.editor.wizards.AttributeWizard
boolean areFieldsNotNull ()
void storeKeyValuePair ()
void attachTextProperties ()
Protected Member Functions inherited from view.editor.wizards.Wizard
void addToData (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void setWizardType (WizardType type)
void attachTextProperties ()
boolean isNumber (String value)
Protected Attributes inherited from view.editor.wizards.AttributeWizard
ComboBox< String > key
TextField value
Set< String > attributes
Protected Attributes inherited from view.editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Detailed Description
This represents the Wizard used to accept a numerical value with an attribute name. It checks whether the inputted value is numeric, and then stores this value as a string, to conform with the WizardData data structure.
Author
Joshua, Nishad
Definition at line 17 of file NumberAttributeWizard.java.
Member Function Documentation
boolean view.editor.wizards.NumberAttributeWizard.checkCanSave ()
Definition at line 20 of file NumberAttributeWizard.java.
References view.editor.wizards.AttributeWizard.areFieldsNotNull(), view.editor.wizards.Wizard.isNumber(), and view.editor.wizards.AttributeWizard.value.
void view.editor.wizards.NumberAttributeWizard.initialize ()
Implements view.gui.GUIController.
Definition at line 25 of file NumberAttributeWizard.java.
References view.editor.wizards.AttributeWizard.attributes, model.state.gameelement.StateTags.getAllNumericalAttributes(), and view.editor.wizards.AttributeWizard.key.
void view.editor.wizards.NumberAttributeWizard.updateData ()
Definition at line 31 of file NumberAttributeWizard.java.
References model.data.WizardType.NUMBER_ATTRIBUTE, view.editor.wizards.Wizard.setWizardType(), and view.editor.wizards.AttributeWizard.storeKeyValuePair().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/NumberAttributeWizard.java