voogasalad_TheException: editor.DescribableInfoBoxController Class Reference
editor.DescribableInfoBoxController Class Reference
Public Member Functions
void setSubmitAction (BiConsumer< String, String > textChangedAction)
void setText (String name, String description)
Node getRoot ()
void initialize ()
Private Member Functions
void initLabelInputSwitching ()
void setEditableToggle (TextInputControl textInputControl)
Private Attributes
BiConsumer< String, String > mySubmitConsumer
VBox infoRoot
TextField nameTextField
TextArea descriptionTextArea
Button submitButton
Static Private Attributes
static final String SUBMIT_KEY = "Update"
Detailed Description
Author
Jonathan Tseng
Definition at line 21 of file DescribableInfoBoxController.java.
Member Function Documentation
Node editor.DescribableInfoBoxController.getRoot ()
Implements view.GUIController.
Definition at line 80 of file DescribableInfoBoxController.java.
References editor.DescribableInfoBoxController.infoRoot.
void editor.DescribableInfoBoxController.initialize ()
Implements view.GUIController.
Definition at line 85 of file DescribableInfoBoxController.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), and editor.DescribableInfoBoxController.initLabelInputSwitching().
void editor.DescribableInfoBoxController.initLabelInputSwitching () private
Definition at line 57 of file DescribableInfoBoxController.java.
References editor.DescribableInfoBoxController.setEditableToggle().
Referenced by editor.DescribableInfoBoxController.initialize().
void editor.DescribableInfoBoxController.setEditableToggle (TextInputControl textInputControl) private
Definition at line 72 of file DescribableInfoBoxController.java.
Referenced by editor.DescribableInfoBoxController.initLabelInputSwitching().
void editor.DescribableInfoBoxController.setSubmitAction (BiConsumer< String, String > textChangedAction)
Definition at line 62 of file DescribableInfoBoxController.java.
Referenced by editor.EditorScreen.initInfoBox().
void editor.DescribableInfoBoxController.setText (String name, String description)
Definition at line 66 of file DescribableInfoBoxController.java.
Referenced by editor.EditorScreen.updateInfoBox().
Member Data Documentation
TextArea editor.DescribableInfoBoxController.descriptionTextArea private
Definition at line 33 of file DescribableInfoBoxController.java.
VBox editor.DescribableInfoBoxController.infoRoot private
Definition at line 29 of file DescribableInfoBoxController.java.
Referenced by editor.DescribableInfoBoxController.getRoot().
BiConsumer<String, String> editor.DescribableInfoBoxController.mySubmitConsumer private
Initial value:
= (String name, String description) -> {
    }
Definition at line 25 of file DescribableInfoBoxController.java.
TextField editor.DescribableInfoBoxController.nameTextField private
Definition at line 31 of file DescribableInfoBoxController.java.
final String editor.DescribableInfoBoxController.SUBMIT_KEY = "Update" static private
Definition at line 24 of file DescribableInfoBoxController.java.
Button editor.DescribableInfoBoxController.submitButton private
Definition at line 35 of file DescribableInfoBoxController.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/DescribableInfoBoxController.java