voogasalad_TheException: game_requests.forwarding.InvalidAddressException Class Reference
game_requests.forwarding.InvalidAddressException Class Reference
Public Member Functions
InvalidAddressException (String address, String reason)
String address ()
String reason ()
Private Attributes
String myAddress
String myReason
Static Private Attributes
static final long serialVersionUID = 7207103882222096620L
Detailed Description
An exception capturing when an invalid address has been used
Definition at line 6 of file InvalidAddressException.java.
Constructor & Destructor Documentation
game_requests.forwarding.InvalidAddressException.InvalidAddressException (String address, String reason)
Create a new invalid address exception
Parameters
address The invalid address
reason The reason the address is invalid
Definition at line 20 of file InvalidAddressException.java.
References game_requests.forwarding.InvalidAddressException.address(), and game_requests.forwarding.InvalidAddressException.reason().
Member Function Documentation
String game_requests.forwarding.InvalidAddressException.address ()
Get the invalid address
Returns
The invalid address
Definition at line 31 of file InvalidAddressException.java.
References game_requests.forwarding.InvalidAddressException.myAddress.
Referenced by game_requests.forwarding.InvalidAddressException.InvalidAddressException().
String game_requests.forwarding.InvalidAddressException.reason ()
Get the reason the address is invalid
Returns
The reason the address is invalid
Definition at line 40 of file InvalidAddressException.java.
References game_requests.forwarding.InvalidAddressException.myReason.
Referenced by game_requests.forwarding.InvalidAddressException.InvalidAddressException().
Member Data Documentation
String game_requests.forwarding.InvalidAddressException.myAddress private
Definition at line 9 of file InvalidAddressException.java.
Referenced by game_requests.forwarding.InvalidAddressException.address().
String game_requests.forwarding.InvalidAddressException.myReason private
Definition at line 10 of file InvalidAddressException.java.
Referenced by game_requests.forwarding.InvalidAddressException.reason().
final long game_requests.forwarding.InvalidAddressException.serialVersionUID = 7207103882222096620L static private
Definition at line 8 of file InvalidAddressException.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_requests/forwarding/InvalidAddressException.java