voogasalad_TheException: game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement Class Reference
game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement Class Reference
Public Member Functions
DrawableGameElement (DrawableGameElementState state, Map< String, List< Evaluatable<?>>> actions, ResourceBundle actionTypes)
void update ()
void setAnimation (AnimationSequence animation)
AnimationSequence getAnimation ()
void setAnimation (String animationName)
Node getNode ()
VBox getDisplayVBox ()
double[] getBounds ()
Point2D getLocation ()
Public Member Functions inherited from game_engine.gameRepresentation.renderedRepresentation.GameElement
GameElement (GameElementState gameElementState, Map< String, List< Evaluatable<?>>> conditionActionPairs, ResourceBundle actionTypesBundle)
Iterator< Evaluatable<?> > getActionsOfType (String actionType)
void addAction (String actionType, Evaluatable<?> action)
void removeAction (String actionID)
void update ()
Number getNumericalAttribute (String attributeTag)
void setNumericalAttribute (String attributeTag, Number attributeValue)
String getTextualAttribute (String attributeTag)
void setTextualAttribute (String attributeTag, String attributeValue)
void setPosition (double x, double y)
Protected Member Functions
void updateImageLocation ()
Protected Member Functions inherited from game_engine.gameRepresentation.renderedRepresentation.GameElement
void executeAllActions (String actionKey, ElementPair elementPair)
void executeAllActions (String actionKey)
Protected Attributes
AnimationPlayer myAnimation
Group myDisplay
VBox myDisplayVBox
Protected Attributes inherited from game_engine.gameRepresentation.renderedRepresentation.GameElement
ResourceBundle actionTypes
Static Package Attributes
static final String SELECT_ARROW_URL = "resources/img/Red_Arrow_Down.png"
Private Member Functions
void initializeDisplay ()
Private Attributes
DrawableGameElementState drawableState
Image mySelectedImage
ImageView mySelectedImageView
AnimationSequence myCurrentAnimation
Detailed Description
A game element that is capable of being drawn. Combines a game element state as well as an animation player. Essentially wraps a savable game element state with a drawable wrapper to avoid JavaFX serialization problems.
Author
Zach, Jonathan, Nishad, Rahul, John L., Michael D.
Definition at line 32 of file DrawableGameElement.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.DrawableGameElement (DrawableGameElementState state, Map< String, List< Evaluatable<?>>> actions, ResourceBundle actionTypes)
Create a drawable game element from the given state
Parameters
state the state of the drawable element
actions the actions map for the game element (Created by a factory to be passed into the element)
Definition at line 51 of file DrawableGameElement.java.
References game_engine.visuals.Spritesheet.frameDimensions, game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.getSpritesheet(), game_engine.visuals.Spritesheet.imageTag, game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.initializeDisplay(), and game_engine.visuals.Spritesheet.numCols.
Member Function Documentation
AnimationSequence game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getAnimation ()
Returns
the animation that is currently being displayed by the element
Definition at line 113 of file DrawableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.myCurrentAnimation.
double [] game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getBounds ()
Get the bound array of the object
Returns
the object's bounds
Implements game_engine.gameRepresentation.stateRepresentation.gameElement.traits.Boundable.
Definition at line 151 of file DrawableGameElement.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.getBounds().
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.addElement().
VBox game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getDisplayVBox ()
Gets the VBox of stats of the game element
Returns
The VBox of the game element
Definition at line 142 of file DrawableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.myDisplayVBox.
Point2D game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLocation ()
Definition at line 158 of file DrawableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode().
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getLines(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move().
Node game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode ()
Gets the node that is being displayed on the scene
Returns
The game element
Implements game_engine.visuals.Displayable.
Definition at line 133 of file DrawableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.myDisplay.
Referenced by game_engine.gameRepresentation.renderedRepresentation.Level.addElement(), and game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLocation().
void game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.initializeDisplay () private
Initializes the display for each game element
Definition at line 167 of file DrawableGameElement.java.
References game_engine.visuals.AnimationPlayer.getDimension(), game_engine.visuals.Dimension.getHeight(), game_engine.visuals.AnimationPlayer.getNode(), game_engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), game_engine.visuals.Dimension.getWidth(), game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.X_POS_STRING, and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.Y_POS_STRING.
Referenced by game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.DrawableGameElement().
void game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setAnimation (AnimationSequence animation)
Set the element's animation to a given sequence
Parameters
animation the animation sequence to set
Definition at line 106 of file DrawableGameElement.java.
References game_engine.visuals.AnimationPlayer.setAnimation().
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.setAnimationDirection().
void game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setAnimation (String animationName)
Set the animation currently being played by the drawable game element to the animation with the given name
Parameters
animationName the name of the animation to set the current animation to
Definition at line 123 of file DrawableGameElement.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.getAnimation().
void game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.update ()
Update the drawable game element and its visual appearance.
Definition at line 86 of file DrawableGameElement.java.
References game_engine.visuals.AnimationPlayer.setAnimation(), and game_engine.visuals.AnimationPlayer.update().
void game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.updateImageLocation () protected
Update the element's image location based on its x and y position
Definition at line 95 of file DrawableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.X_POS_STRING, and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.Y_POS_STRING.
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move().
Member Data Documentation
DrawableGameElementState game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.drawableState private
Definition at line 35 of file DrawableGameElement.java.
AnimationPlayer game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.myAnimation protected
Definition at line 36 of file DrawableGameElement.java.
AnimationSequence game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.myCurrentAnimation private
Definition at line 41 of file DrawableGameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getAnimation().
Group game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.myDisplay protected
Definition at line 37 of file DrawableGameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode().
VBox game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.myDisplayVBox protected
Definition at line 38 of file DrawableGameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getDisplayVBox(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelectedIndicator().
Image game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.mySelectedImage private
Definition at line 39 of file DrawableGameElement.java.
ImageView game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.mySelectedImageView private
Definition at line 40 of file DrawableGameElement.java.
final String game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.SELECT_ARROW_URL = "resources/img/Red_Arrow_Down.png" static package
Definition at line 34 of file DrawableGameElement.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/renderedRepresentation/DrawableGameElement.java