voogasalad_TheException: editor.wizards.Wizard Class Reference
editor.wizards.Wizard Class Reference abstract
Public Member Functions
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
WizardData getWizardData ()
void setErrorMesssage (String error)
void setStage (Stage s)
Stage getStage ()
Protected Member Functions
void addToData (String key, String value)
void addWizardData (WizardData wizData)
void setDataName (String name)
Protected Attributes
SplitPane root
Button save
Text errorMessage
Private Member Functions
void save ()
void displayWarning ()
Private Attributes
Consumer< WizardData > mySaveConsumer
WizardData userInput
Stage myStage
Static Private Attributes
static final String ERROR = "CANNOT SAVE!"
Detailed Description
Author
Joshua, Nishad
Definition at line 18 of file Wizard.java.
Member Function Documentation
void editor.wizards.Wizard.addToData (String key, String value) protected
Definition at line 67 of file Wizard.java.
References editor.wizards.WizardData.addDataPair().
Referenced by editor.wizards.TerrainWizard.loadImage(), editor.wizards.CampaignWizard.updateData(), editor.wizards.LevelWizard.updateData(), editor.wizards.StringAttributeWizard.updateData(), editor.wizards.TriggerWizard.updateData(), editor.wizards.NumberAttributeWizard.updateData(), editor.wizards.GameElementWizard.updateData(), and editor.wizards.DrawableGameElementWizard.updateData().
void editor.wizards.Wizard.addWizardData (WizardData wizData) protected
Definition at line 71 of file Wizard.java.
References editor.wizards.WizardData.addWizardData().
Referenced by editor.wizards.GameElementWizard.launchNestedWizard(), and editor.wizards.DrawableGameElementWizard.launchNestedWizard().
abstract boolean editor.wizards.Wizard.checkCanSave () abstract
Referenced by editor.wizards.Wizard.save().
void editor.wizards.Wizard.displayWarning () private
Definition at line 83 of file Wizard.java.
Referenced by editor.wizards.Wizard.save().
Node editor.wizards.Wizard.getRoot ()
Returns the root of the wizard's scene
Returns
Node root - the root of the scene
Implements view.GUIController.
Definition at line 40 of file Wizard.java.
References editor.wizards.Wizard.root.
Referenced by view.WizardUtility.loadWizard().
Stage editor.wizards.Wizard.getStage ()
Definition at line 100 of file Wizard.java.
References editor.wizards.Wizard.myStage.
Referenced by editor.TabViewController.launchNestedWizard(), editor.wizards.GameElementWizard.launchNestedWizard(), editor.wizards.DrawableGameElementWizard.launchNestedWizard(), editor.EditorMenuBarController.onNewCampaignClick(), editor.EditorMenuBarController.onNewLevelClick(), and editor.ElementAccordionController.openGameElementWizard().
WizardData editor.wizards.Wizard.getWizardData ()
Definition at line 88 of file Wizard.java.
References editor.wizards.Wizard.userInput.
void editor.wizards.Wizard.initialize ()
Implements view.GUIController.
Definition at line 45 of file Wizard.java.
References editor.wizards.Wizard.save(), and editor.wizards.Wizard.userInput.
void editor.wizards.Wizard.save () private
Definition at line 52 of file Wizard.java.
References editor.wizards.Wizard.checkCanSave(), editor.wizards.Wizard.displayWarning(), and editor.wizards.Wizard.updateData().
Referenced by editor.wizards.Wizard.initialize().
void editor.wizards.Wizard.setDataName (String name) protected
Definition at line 75 of file Wizard.java.
References editor.wizards.WizardData.setName().
Referenced by editor.wizards.CampaignWizard.updateData(), editor.wizards.LevelWizard.updateData(), editor.wizards.StringAttributeWizard.updateData(), editor.wizards.TriggerWizard.updateData(), editor.wizards.NumberAttributeWizard.updateData(), editor.wizards.TerrainWizard.updateData(), editor.wizards.GameElementWizard.updateData(), and editor.wizards.DrawableGameElementWizard.updateData().
void editor.wizards.Wizard.setErrorMesssage (String error)
Definition at line 92 of file Wizard.java.
Referenced by editor.EditorMenuBarController.onNewCampaignClick(), and editor.EditorMenuBarController.onNewLevelClick().
void editor.wizards.Wizard.setStage (Stage s)
Definition at line 96 of file Wizard.java.
Referenced by view.WizardUtility.loadWizard().
void editor.wizards.Wizard.setSubmit (Consumer< WizardData > c)
Definition at line 63 of file Wizard.java.
Referenced by editor.TabViewController.launchNestedWizard(), editor.wizards.GameElementWizard.launchNestedWizard(), editor.wizards.DrawableGameElementWizard.launchNestedWizard(), editor.EditorMenuBarController.onNewCampaignClick(), editor.EditorMenuBarController.onNewLevelClick(), and editor.ElementAccordionController.openGameElementWizard().
abstract void editor.wizards.Wizard.updateData () abstract
Referenced by editor.wizards.Wizard.save().
Member Data Documentation
final String editor.wizards.Wizard.ERROR = "CANNOT SAVE!" static private
Definition at line 28 of file Wizard.java.
Text editor.wizards.Wizard.errorMessage protected
Definition at line 26 of file Wizard.java.
Consumer<WizardData> editor.wizards.Wizard.mySaveConsumer private
Definition at line 30 of file Wizard.java.
Stage editor.wizards.Wizard.myStage private
Definition at line 32 of file Wizard.java.
Referenced by editor.wizards.Wizard.getStage().
SplitPane editor.wizards.Wizard.root protected
Definition at line 21 of file Wizard.java.
Referenced by editor.wizards.Wizard.getRoot().
Button editor.wizards.Wizard.save protected
Definition at line 23 of file Wizard.java.
WizardData editor.wizards.Wizard.userInput private
Definition at line 31 of file Wizard.java.
Referenced by editor.wizards.Wizard.getWizardData(), and editor.wizards.Wizard.initialize().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/wizards/Wizard.java