voogasalad_TheException: view.MainView Class Reference
view.MainView Class Reference
Public Member Functions
MainView (Stage stage, MainModel model)
void start ()
void launchScreen (ViewScreenPath screen)
void update (Observable arg0, Object arg1)
Private Member Functions
void launchScreen (String filePath)
Private Attributes
Stage myStage
Scene myScene
MainModel myMainModel
GUIScreen myCurrentController
GUILoadStyleUtility myLoadStyleUtility
Static Private Attributes
static final String[] myLanguages
static final Dimension SCENE_DIMENSIONS = Toolkit.getDefaultToolkit().getScreenSize()
Detailed Description
MainView that has control of the stage and handles switching between different scenes
Author
Jonathan Tseng
Nishad Agrawal
Definition at line 25 of file MainView.java.
Constructor & Destructor Documentation
view.MainView.MainView (Stage stage, MainModel model)
Definition at line 40 of file MainView.java.
References view.GUILoadStyleUtility.addScene(), view.GUILoadStyleUtility.addStyle(), view.GUILoadStyleUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.initLanguages(), view.MainView.launchScreen(), and view.gui.ViewScreenPath.SPLASH.
Member Function Documentation
void view.MainView.launchScreen (ViewScreenPath screen)
Definition at line 59 of file MainView.java.
References view.gui.ViewScreenPath.getFilePath().
Referenced by view.MainView.MainView(), and view.gui.GUIScreen.switchScreen().
void view.MainView.launchScreen (String filePath) private
private helper method to launch a screen for the stage
Parameters
filePath
Definition at line 68 of file MainView.java.
References view.gui.GUIScreen.attachSceneHandler(), view.GUILoadStyleUtility.generateGUIPane(), view.gui.GUIController.getRoot(), view.gui.GUIContainer.setModel(), and view.MainView.update().
void view.MainView.start ()
Definition at line 54 of file MainView.java.
Referenced by application.Main.start().
void view.MainView.update (Observable arg0, Object arg1)
Definition at line 78 of file MainView.java.
References view.gui.GUIContainer.update().
Referenced by view.MainView.launchScreen().
Member Data Documentation
GUIScreen view.MainView.myCurrentController private
Definition at line 37 of file MainView.java.
final String [] view.MainView.myLanguages static private
Initial value:
=
            new String[] {
                          "resources.languages.English.properties",
                          "resources.languages.Chinese.properties"
            }
Definition at line 27 of file MainView.java.
GUILoadStyleUtility view.MainView.myLoadStyleUtility private
Definition at line 38 of file MainView.java.
MainModel view.MainView.myMainModel private
Definition at line 36 of file MainView.java.
Scene view.MainView.myScene private
Definition at line 35 of file MainView.java.
Stage view.MainView.myStage private
Definition at line 34 of file MainView.java.
final Dimension view.MainView.SCENE_DIMENSIONS = Toolkit.getDefaultToolkit().getScreenSize() static private
Definition at line 33 of file MainView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/MainView.java