voogasalad_TheException: view.runner.RunnerMenuBarController Class Reference
view.runner.RunnerMenuBarController Class Reference
Protected Member Functions
void initMenuBar ()
void bindTextProperties () throws LanguageException
Protected Member Functions inherited from view.gui.MenuBarController
final void init ()
abstract void initMenuBar ()
abstract void bindTextProperties () throws LanguageException
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Private Member Functions
void initFileMenu ()
Additional Inherited Members
Public Member Functions inherited from view.gui.MenuBarController
void attachScreen (GUIScreen screen)
Node getRoot ()
void modelUpdate ()
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Protected Attributes inherited from view.gui.MenuBarController
MenuItem saveMenuItem
MenuItem quitMenuItem
Menu fileMenu
MenuBar menuBar
Menu languageMenu
GUIScreen myScreen
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Detailed Description
MenuBar for the runner view
Author
Jonathan Tseng
Definition at line 14 of file RunnerMenuBarController.java.
Member Function Documentation
void view.runner.RunnerMenuBarController.bindTextProperties () throws LanguageException protected
Definition at line 27 of file RunnerMenuBarController.java.
void view.runner.RunnerMenuBarController.initFileMenu () private
Definition at line 21 of file RunnerMenuBarController.java.
References view.gui.GUIContainer.myMainModel, view.gui.MenuBarController.myScreen, view.gui.MenuBarController.quitMenuItem, model.MainModel.saveGame(), view.gui.MenuBarController.saveMenuItem, view.gui.ViewScreenPath.SPLASH, and view.gui.GUIScreen.switchScreen().
Referenced by view.runner.RunnerMenuBarController.initMenuBar().
void view.runner.RunnerMenuBarController.initMenuBar () protected
Definition at line 17 of file RunnerMenuBarController.java.
References view.runner.RunnerMenuBarController.initFileMenu().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/runner/RunnerMenuBarController.java