voogasalad_TheException: util.multilanguage.MultiLanguageUtility Class Reference
util.multilanguage.MultiLanguageUtility Class Reference
Public Member Functions
void initLanguages (String...languageResourceFiles)
void setLanguage (String language) throws LanguageNotFoundException
String getCurrentLanguage ()
ObjectProperty< ObservableList< String > > getSupportedLanguages ()
ObjectProperty< String > getStringProperty (String propertyKey) throws LanguagePropertyNotFoundException
ObjectProperty< ObservableList< String > > getStringListProperty (String propertyKey) throws LanguagePropertyNotFoundException
Static Public Member Functions
static synchronized MultiLanguageUtility getInstance ()
Package Functions
private< T > ObjectProperty< T > getProperty (Map< String, ObjectProperty< T >> map, String propertyKey) throws LanguagePropertyNotFoundException
Private Member Functions
MultiLanguageUtility ()
void initLanguages (List< String > fileNames)
void addLanguage (ResourceBundle bundle, String languageName)
void createStringProperties ()
void createStringListProperties ()
void updateProperties ()
void updateStringProperties ()
void updateStringListProperties ()
String fileExtension (String filePath)
String fileName (String filePath)
Private Attributes
Map< String, Map< String, String > > myLanguagesToStringsMap
Map< String, Map< String, List< String > > > myLanguagesToStringListsMap
Map< String, ObjectProperty< String > > myStringProperties
Map< String, ObjectProperty< ObservableList< String > > > myStringListProperties
ObjectProperty< ObservableList< String > > myLanguages
String myCurrentLanguage
Static Private Attributes
static final String LANGUAGE_KEY = "Language"
static final String LIST_SPLITTER = "\\|"
static final String DIVIDER = "\\"
static final String PROPERTIES_FILE_EXTENSION = ".properties"
static final String DOT = "."
static MultiLanguageUtility myOnlyInstance
Detailed Description
Utility for supporting multiple languages in the view. The utility works by reading a list of resource files for different languages and uses JavaFX ObjectProperties (which use native JavaFX Observer/Observable pattern) to bind JavaFX nodes to certain texts. Furthermore, switching between languages is supported by a call to the setLanguage(String languageName) method. For any JavaFX node to update it's text it requires a 1-time setup to bind the property e.g., myButton.getTextProperty().bind(MultiLanguageUtility.newInstance().getString("BUTTON_LABEL"));
public API: getInstance() –> instance of the utility initLanguages(String ... resourceFiles) –> initializes the languages in the utility setLanguage(String language) –> sets the language of the utility getCurrentLanguage() –> returns the current language getSupportedLanguages() –> ObjectProperty holding ObservableList for supported languages getStringProperty(String propertyName) –> gets the string property (ObjectProperty holding String) getStringListProperty(String propertyName) –> gets the string list property (ObjectProperty holding ObservableList) Requires a resource (.properties) file for each language. The name of the language must be specified in the resource file as a tag "language=..." If it is not, then the name of the language is assumed to be the name of the file.
Singleton pattern: 1 MultiLanguageUtility instance per program to handle language (assumes that a program can only have 1 language at any given time)
Author
Jonathan Tseng
Definition at line 46 of file MultiLanguageUtility.java.
Constructor & Destructor Documentation
util.multilanguage.MultiLanguageUtility.MultiLanguageUtility () private
private constructor for the utility
Definition at line 66 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.getInstance().
Member Function Documentation
void util.multilanguage.MultiLanguageUtility.addLanguage (ResourceBundle bundle, String languageName) private
private helper method to add a single language with resourcebundle to the utility
Parameters
bundle
languageName
Definition at line 206 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.initLanguages().
void util.multilanguage.MultiLanguageUtility.createStringListProperties () private
creates the string list properties that are sent to GUI components to bind to
Definition at line 238 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.updateProperties().
void util.multilanguage.MultiLanguageUtility.createStringProperties () private
creates the string properties that are sent to GUI components to bind to
Definition at line 228 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.updateProperties().
String util.multilanguage.MultiLanguageUtility.fileExtension (String filePath) private
gets the extension of a filePath if no "." found, then returns the given filePath
Parameters
filePath
Definition at line 292 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.fileName(), and util.multilanguage.MultiLanguageUtility.initLanguages().
String util.multilanguage.MultiLanguageUtility.fileName (String filePath) private
gets the language name from the file path by removing the extension
Parameters
filePath
Returns
Definition at line 302 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.fileExtension().
Referenced by util.multilanguage.MultiLanguageUtility.initLanguages().
String util.multilanguage.MultiLanguageUtility.getCurrentLanguage ()
returns the current language
Definition at line 120 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.myCurrentLanguage.
static synchronized MultiLanguageUtility util.multilanguage.MultiLanguageUtility.getInstance () static
returns the single instance of the utility in the program
Returns
Definition at line 78 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.MultiLanguageUtility(), and util.multilanguage.MultiLanguageUtility.myOnlyInstance.
Referenced by view.editor.wizards.BoundsWizard.addXYPair(), view.editor.ElementAccordionController.attachStringProperties(), view.splash.SplashScreen.attachStringProperties(), view.editor.wizards.CampaignWizard.attachTextProperties(), view.editor.wizards.PositionWizard.attachTextProperties(), view.gui.MenuBarController.attachTextProperties(), view.editor.wizards.AttributeWizard.attachTextProperties(), view.editor.wizards.LevelWizard.attachTextProperties(), view.runner.LevelChooserController.attachTextProperties(), view.editor.wizards.WidgetWizard.attachTextProperties(), view.editor.wizards.GameElementWizard.attachTextProperties(), view.editor.wizards.AnimationWizard.attachTextProperties(), view.editor.EditorScreen.attachTextProperties(), view.editor.wizards.Wizard.attachTextProperties(), view.editor.EditorMenuBarController.bindTextProperties(), view.dialog.DialogBoxUtility.createMessageDialog(), view.editor.wizards.Wizard.displayWarning(), view.editor.TabViewController.init(), view.editor.wizards.BoundsWizard.initialize(), view.runner.GameEndController.initialize(), view.editor.DescribableInfoBoxController.initialize(), view.runner.LevelChooserController.initialize(), view.editor.LevelTriggersViewController.initialize(), view.editor.ElementDropDownController.initialize(), view.gui.MenuBarController.initLanguageMenu(), view.editor.TabViewController.initToggle(), model.MainModel.loadGame(), view.splash.SplashScreen.loadGameAndSwitchScreen(), view.MainView.MainView(), view.runner.RunnerScreen.playLevel(), and view.splash.SplashScreen.setUpButtons().
private<T> ObjectProperty<T> util.multilanguage.MultiLanguageUtility.getProperty (Map< String, ObjectProperty< T >> map, String propertyKey) throws LanguagePropertyNotFoundException package
helper method to get a generic objectproperty by key from a map
Parameters
map
propertyKey
Returns
Exceptions
LanguagePropertyNotFoundException
Definition at line 169 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.getStringListProperty(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
ObjectProperty<ObservableList<String> > util.multilanguage.MultiLanguageUtility.getStringListProperty (String propertyKey) throws LanguagePropertyNotFoundException
returns the object property with an observablelist for a given key the observablelist is a list of strings in the resource file, a string list property must be "|" separated e.g., animals=dog|cat|fish
Parameters
propertyKey
Returns
Exceptions
LanguagePropertyNotFoundException
Definition at line 156 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.getProperty().
ObjectProperty<String> util.multilanguage.MultiLanguageUtility.getStringProperty (String propertyKey) throws LanguagePropertyNotFoundException
returns the string property for a given key
Parameters
propertyKey
Returns
Exceptions
LanguagePropertyNotFoundException
Definition at line 141 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.getProperty().
Referenced by view.editor.wizards.BoundsWizard.addXYPair(), view.editor.ElementAccordionController.attachStringProperties(), view.splash.SplashScreen.attachStringProperties(), view.editor.wizards.CampaignWizard.attachTextProperties(), view.editor.wizards.PositionWizard.attachTextProperties(), view.gui.MenuBarController.attachTextProperties(), view.editor.wizards.AttributeWizard.attachTextProperties(), view.editor.wizards.LevelWizard.attachTextProperties(), view.runner.LevelChooserController.attachTextProperties(), view.editor.wizards.WidgetWizard.attachTextProperties(), view.editor.wizards.GameElementWizard.attachTextProperties(), view.editor.wizards.AnimationWizard.attachTextProperties(), view.editor.EditorScreen.attachTextProperties(), view.editor.wizards.Wizard.attachTextProperties(), view.editor.EditorMenuBarController.bindTextProperties(), view.dialog.DialogBoxUtility.createMessageDialog(), view.editor.wizards.Wizard.displayWarning(), view.editor.TabViewController.init(), view.editor.wizards.BoundsWizard.initialize(), view.runner.GameEndController.initialize(), view.editor.DescribableInfoBoxController.initialize(), view.runner.LevelChooserController.initialize(), view.editor.LevelTriggersViewController.initialize(), view.editor.ElementDropDownController.initialize(), view.editor.TabViewController.initToggle(), model.MainModel.loadGame(), view.splash.SplashScreen.loadGameAndSwitchScreen(), view.runner.RunnerScreen.playLevel(), and view.splash.SplashScreen.setUpButtons().
ObjectProperty<ObservableList<String> > util.multilanguage.MultiLanguageUtility.getSupportedLanguages ()
returns an object property containing an observable list of the languages currently parsed and supported by this utility
Returns
Definition at line 130 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.myLanguages.
Referenced by view.gui.MenuBarController.initLanguageMenu().
void util.multilanguage.MultiLanguageUtility.initLanguages (String... languageResourceFiles)
initializes the languages available in the utility with the given array of language resource files
Parameters
languageResourceFiles
Definition at line 91 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.updateProperties().
Referenced by view.MainView.MainView().
void util.multilanguage.MultiLanguageUtility.initLanguages (List< String > fileNames) private
private helper method that takes list of files and reads them also sets a random default language
Definition at line 184 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.addLanguage(), util.multilanguage.MultiLanguageUtility.fileExtension(), and util.multilanguage.MultiLanguageUtility.fileName().
void util.multilanguage.MultiLanguageUtility.setLanguage (String language) throws LanguageNotFoundException
sets the current language of the program if the language property file exists
Parameters
language
Exceptions
LanguageNotFoundException
Definition at line 107 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.updateProperties().
Referenced by view.gui.MenuBarController.initLanguageMenu().
void util.multilanguage.MultiLanguageUtility.updateProperties () private
updates the properties that GUI components are bound to
Definition at line 249 of file MultiLanguageUtility.java.
References util.multilanguage.MultiLanguageUtility.createStringListProperties(), util.multilanguage.MultiLanguageUtility.createStringProperties(), util.multilanguage.MultiLanguageUtility.updateStringListProperties(), and util.multilanguage.MultiLanguageUtility.updateStringProperties().
Referenced by util.multilanguage.MultiLanguageUtility.initLanguages(), and util.multilanguage.MultiLanguageUtility.setLanguage().
void util.multilanguage.MultiLanguageUtility.updateStringListProperties () private
updates the string list properties that GUI components are bound to
Definition at line 274 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.updateProperties().
void util.multilanguage.MultiLanguageUtility.updateStringProperties () private
updates the string properties that GUI components are bound to
Definition at line 263 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.updateProperties().
Member Data Documentation
final String util.multilanguage.MultiLanguageUtility.DIVIDER = "\\" static private
Definition at line 50 of file MultiLanguageUtility.java.
final String util.multilanguage.MultiLanguageUtility.DOT = "." static private
Definition at line 52 of file MultiLanguageUtility.java.
final String util.multilanguage.MultiLanguageUtility.LANGUAGE_KEY = "Language" static private
Definition at line 48 of file MultiLanguageUtility.java.
final String util.multilanguage.MultiLanguageUtility.LIST_SPLITTER = "\\|" static private
Definition at line 49 of file MultiLanguageUtility.java.
String util.multilanguage.MultiLanguageUtility.myCurrentLanguage private
Definition at line 61 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.getCurrentLanguage().
ObjectProperty<ObservableList<String> > util.multilanguage.MultiLanguageUtility.myLanguages private
Definition at line 60 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.getSupportedLanguages().
Map<String, Map<String, List<String> > > util.multilanguage.MultiLanguageUtility.myLanguagesToStringListsMap private
Definition at line 57 of file MultiLanguageUtility.java.
Map<String, Map<String, String> > util.multilanguage.MultiLanguageUtility.myLanguagesToStringsMap private
Definition at line 56 of file MultiLanguageUtility.java.
MultiLanguageUtility util.multilanguage.MultiLanguageUtility.myOnlyInstance static private
Definition at line 54 of file MultiLanguageUtility.java.
Referenced by util.multilanguage.MultiLanguageUtility.getInstance().
Map<String, ObjectProperty<ObservableList<String> > > util.multilanguage.MultiLanguageUtility.myStringListProperties private
Definition at line 59 of file MultiLanguageUtility.java.
Map<String, ObjectProperty<String> > util.multilanguage.MultiLanguageUtility.myStringProperties private
Definition at line 58 of file MultiLanguageUtility.java.
final String util.multilanguage.MultiLanguageUtility.PROPERTIES_FILE_EXTENSION = ".properties" static private
Definition at line 51 of file MultiLanguageUtility.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/util/multilanguage/MultiLanguageUtility.java