voogasalad_TheException: util.imageprocessing.SpriteSheetCreationUtility Class Reference
util.imageprocessing.SpriteSheetCreationUtility Class Reference
Classes
class Location
Public Member Functions
void createSpriteSheet (String baseInputDirectoryPath, int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags, Color maskColor) throws Exception
Static Public Member Functions
static void main (String[] args) throws Exception
Static Package Functions
static BufferedImage toBufferedImage (Image src)
Static Package Attributes
static final String[] EXTENSIONS = new String[] { "png" }
static final FilenameFilter IMAGE_FILTER
Private Member Functions
void doThing () throws IOException
void populateTagLists ()
void extractAllSpriteLists (int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags, File unitDirectory, List< ArrayList< BufferedImage >> allSpriteLists)
List< BufferedImage > extrapolateSprites (List< BufferedImage > uniqueSprites, int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags)
BufferedImage mirrorImageHorizontally (BufferedImage input)
void createStateSpritesheets (int[] extrapolatedStateIndicies, Color maskColor, List< ArrayList< BufferedImage >> allSpriteLists, List< BufferedImage > spritesheets, int frameWidth, int frameHeight) throws IOException
BufferedImage tileImagesIntoColumns (List< BufferedImage > images, int numColumns, int frameWidth, int frameHeight, Color maskColor)
BufferedImage tileSpritesheets (List< BufferedImage > spritesheets, int frameWidth, int frameHeight)
int findMaximumImageHeight (List< BufferedImage > images)
int findMaximumImageWidth (List< BufferedImage > images)
List< BufferedImage > loadFilesInDirectory (File directory)
BufferedImage colorToTransparency (BufferedImage input, Color maskColor) throws IOException
Private Attributes
List< Integer > rowCountsByColumn = new ArrayList<>()
List< List< AnimationTag > > animationTags = new ArrayList<>()
List< List< AnimationTag > > directionTags = new ArrayList<>()
List< AnimationTag > stateTags = new ArrayList<>()
Detailed Description
This utility creates spritesheets with transparent backgrounds from single sprite images.
Author
Steve
Definition at line 39 of file SpriteSheetCreationUtility.java.
Member Function Documentation
BufferedImage util.imageprocessing.SpriteSheetCreationUtility.colorToTransparency (BufferedImage input, Color maskColor) throws IOException private
Changes all pink pixels to transparent pixels.
Parameters
input image
Returns
- image with all pink (0xFFFF00FF) pixels now transparent
Exceptions
IOException
Definition at line 468 of file SpriteSheetCreationUtility.java.
References util.imageprocessing.SpriteSheetCreationUtility.toBufferedImage().
Referenced by util.imageprocessing.SpriteSheetCreationUtility.createStateSpritesheets(), and util.imageprocessing.SpriteSheetCreationUtility.doThing().
void util.imageprocessing.SpriteSheetCreationUtility.createSpriteSheet (String baseInputDirectoryPath, int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags, Color maskColor) throws Exception
Creates a sprite sheet from a batch of bitmaps with pixel masks.
Parameters
inputDirectoryPath
path to directory holding single sprite bitmaps
outputDirectoryPath
path to directory holding output file
outputFileName
name to give to output
uniqueSpriteIndicies
incidies of states in input
extrapolatedStateIndicies
order of states in output
extrapolatedStateMirrorFlags
which states to mirror horizontally in output
Exceptions
Exception
Definition at line 136 of file SpriteSheetCreationUtility.java.
References util.imageprocessing.SpriteSheetCreationUtility.createStateSpritesheets(), util.imageprocessing.SpriteSheetCreationUtility.extractAllSpriteLists(), util.imageprocessing.ColorMaskExtractor.extractColorMask(), util.imageprocessing.SpriteSheetCreationUtility.findMaximumImageHeight(), util.imageprocessing.SpriteSheetCreationUtility.findMaximumImageWidth(), util.imageprocessing.ColorMaskExtractor.mutateColorMask(), util.imageprocessing.ColorMaskExtractor.mutatedMask, util.SaveLoadUtility.save(), util.imageprocessing.ColorMaskExtractor.spritesheetColorRemoved, and util.imageprocessing.SpriteSheetCreationUtility.tileSpritesheets().
void util.imageprocessing.SpriteSheetCreationUtility.createStateSpritesheets (int[] extrapolatedStateIndicies, Color maskColor, List< ArrayList< BufferedImage >> allSpriteLists, List< BufferedImage > spritesheets, int frameWidth, int frameHeight) throws IOException private
Definition at line 316 of file SpriteSheetCreationUtility.java.
References util.imageprocessing.SpriteSheetCreationUtility.colorToTransparency(), and util.imageprocessing.SpriteSheetCreationUtility.tileImagesIntoColumns().
Referenced by util.imageprocessing.SpriteSheetCreationUtility.createSpriteSheet().
void util.imageprocessing.SpriteSheetCreationUtility.doThing () throws IOException private
Definition at line 62 of file SpriteSheetCreationUtility.java.
References util.imageprocessing.SpriteSheetCreationUtility.colorToTransparency(), and util.imageprocessing.SpriteSheetCreationUtility.loadFilesInDirectory().
Referenced by util.imageprocessing.SpriteSheetCreationUtility.main().
void util.imageprocessing.SpriteSheetCreationUtility.extractAllSpriteLists (int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags, File unitDirectory, List< ArrayList< BufferedImage >> allSpriteLists) private
Definition at line 222 of file SpriteSheetCreationUtility.java.
References util.imageprocessing.SpriteSheetCreationUtility.extrapolateSprites(), and util.imageprocessing.SpriteSheetCreationUtility.loadFilesInDirectory().
Referenced by util.imageprocessing.SpriteSheetCreationUtility.createSpriteSheet().
List<BufferedImage> util.imageprocessing.SpriteSheetCreationUtility.extrapolateSprites (List< BufferedImage > uniqueSprites, int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags) private
This method is able to extrapolate all sprite states necessary from a base set of unique sprite states.
Parameters
uniqueSprites
BufferedImage list of all unique sprites
uniqueStateIndicies
array like [0, 1, 2, 3, 4] (for a five-directional spritesheet)
extrapolatedStateIndicies
array like [0, 1, 2, 3, 4, 3, 2, 1] (to make an eight-directional spritesheet from a five-directional sheet)
extrapolatedStateMirrorFlags
flags to mirror state images
Returns
Definition at line 257 of file SpriteSheetCreationUtility.java.
References util.imageprocessing.SpriteSheetCreationUtility.mirrorImageHorizontally().
Referenced by util.imageprocessing.SpriteSheetCreationUtility.extractAllSpriteLists().
int util.imageprocessing.SpriteSheetCreationUtility.findMaximumImageHeight (List< BufferedImage > images) private
Definition at line 403 of file SpriteSheetCreationUtility.java.
Referenced by util.imageprocessing.SpriteSheetCreationUtility.createSpriteSheet().
int util.imageprocessing.SpriteSheetCreationUtility.findMaximumImageWidth (List< BufferedImage > images) private
Definition at line 413 of file SpriteSheetCreationUtility.java.
Referenced by util.imageprocessing.SpriteSheetCreationUtility.createSpriteSheet().
List<BufferedImage> util.imageprocessing.SpriteSheetCreationUtility.loadFilesInDirectory (File directory) private
Definition at line 441 of file SpriteSheetCreationUtility.java.
Referenced by util.imageprocessing.SpriteSheetCreationUtility.doThing(), and util.imageprocessing.SpriteSheetCreationUtility.extractAllSpriteLists().
static void util.imageprocessing.SpriteSheetCreationUtility.main (String[] args) throws Exception static
Definition at line 46 of file SpriteSheetCreationUtility.java.
References util.imageprocessing.SpriteSheetCreationUtility.doThing().
BufferedImage util.imageprocessing.SpriteSheetCreationUtility.mirrorImageHorizontally (BufferedImage input) private
Mirrors a BufferedImage horizontally.
Parameters
input image
Returns
mirrored input
Definition at line 308 of file SpriteSheetCreationUtility.java.
Referenced by util.imageprocessing.SpriteSheetCreationUtility.extrapolateSprites().
void util.imageprocessing.SpriteSheetCreationUtility.populateTagLists () private
Definition at line 85 of file SpriteSheetCreationUtility.java.
References engine.visuals.elementVisuals.animations.AnimationTag.ATTACK, engine.visuals.elementVisuals.animations.AnimationTag.BACKWARD, engine.visuals.elementVisuals.animations.AnimationTag.DECAY, engine.visuals.elementVisuals.animations.AnimationTag.DIE, engine.visuals.elementVisuals.animations.AnimationTag.FORWARD, engine.visuals.elementVisuals.animations.AnimationTag.LEFT, engine.visuals.elementVisuals.animations.AnimationTag.MOVE, engine.visuals.elementVisuals.animations.AnimationTag.RIGHT, and engine.visuals.elementVisuals.animations.AnimationTag.STAND.
BufferedImage util.imageprocessing.SpriteSheetCreationUtility.tileImagesIntoColumns (List< BufferedImage > images, int numColumns, int frameWidth, int frameHeight, Color maskColor) private
Tiles many images into columns in a spritesheet.
Parameters
images
source sprites
numColumns
number of output columns
Returns
- finished spritesheet with pink background
Definition at line 340 of file SpriteSheetCreationUtility.java.
References util.imageprocessing.SpriteSheetCreationUtility.Location.x, and util.imageprocessing.SpriteSheetCreationUtility.Location.y.
Referenced by util.imageprocessing.SpriteSheetCreationUtility.createStateSpritesheets().
BufferedImage util.imageprocessing.SpriteSheetCreationUtility.tileSpritesheets (List< BufferedImage > spritesheets, int frameWidth, int frameHeight) private
Definition at line 379 of file SpriteSheetCreationUtility.java.
Referenced by util.imageprocessing.SpriteSheetCreationUtility.createSpriteSheet().
static BufferedImage util.imageprocessing.SpriteSheetCreationUtility.toBufferedImage (Image src) static package
Definition at line 481 of file SpriteSheetCreationUtility.java.
Referenced by util.imageprocessing.SpriteSheetCreationUtility.colorToTransparency(), util.imageprocessing.ColorMaskExtractor.extractColorMask(), and util.imageprocessing.ColorMaskExtractor.mutateColorMask().
Member Data Documentation
List<List<AnimationTag> > util.imageprocessing.SpriteSheetCreationUtility.animationTags = new ArrayList<>() private
Definition at line 42 of file SpriteSheetCreationUtility.java.
List<List<AnimationTag> > util.imageprocessing.SpriteSheetCreationUtility.directionTags = new ArrayList<>() private
Definition at line 43 of file SpriteSheetCreationUtility.java.
final String [] util.imageprocessing.SpriteSheetCreationUtility.EXTENSIONS = new String[] { "png" } static package
Definition at line 423 of file SpriteSheetCreationUtility.java.
final FilenameFilter util.imageprocessing.SpriteSheetCreationUtility.IMAGE_FILTER static package
Initial value:
= new FilenameFilter() {
        @Override
        public boolean accept (final File dir, final String name) {
            for (final String ext : EXTENSIONS) {
                if (name.endsWith("." + ext)) { return (true); }
            }
            return (false);
        }
    }
Filters for acceptable images.
Definition at line 430 of file SpriteSheetCreationUtility.java.
List<Integer> util.imageprocessing.SpriteSheetCreationUtility.rowCountsByColumn = new ArrayList<>() private
Definition at line 41 of file SpriteSheetCreationUtility.java.
List<AnimationTag> util.imageprocessing.SpriteSheetCreationUtility.stateTags = new ArrayList<>() private
Definition at line 44 of file SpriteSheetCreationUtility.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/util/imageprocessing/SpriteSheetCreationUtility.java