voogasalad_TheException: util.SaveLoadUtility Class Reference
util.SaveLoadUtility Class Reference
Static Public Member Functions
static< T > T loadResource (Class className, String filePath) throws Exception
static String save (JSONable object, String filePath) throws Exception
static String saveImage (String source, String destination) throws IOException
static Image loadImage (String filePath) throws Exception
Static Public Attributes
static String FILE_SEPARATOR = System.getProperty("file.separator")
Static Private Member Functions
static String topLevelDirectory (String filePath) throws Exception
static File obtainFile (String filePath) throws IOException
static String preProcess (String source)
static boolean fileExists (String filePath)
Static Private Attributes
static final String IMAGE_NOT_LOADED = "Image could not be loaded"
static DefaultResource myDefaultResource = new DefaultResource()
static Gson myGson = new Gson()
Detailed Description
Utility class that handles the loading/saving of files.
Author
Rahul
Definition at line 26 of file SaveLoadUtility.java.
Member Function Documentation
static boolean util.SaveLoadUtility.fileExists (String filePath) static private
Definition at line 129 of file SaveLoadUtility.java.
Referenced by util.SaveLoadUtility.loadImage().
static Image util.SaveLoadUtility.loadImage (String filePath) throws Exception static
Parameters
filePath encoding of the file path
Returns
Image object at that file path
Exceptions
Exception
Definition at line 114 of file SaveLoadUtility.java.
References util.SaveLoadUtility.fileExists(), and util.SaveLoadUtility.obtainFile().
Referenced by test.util.TestLoadSaveUtility.testLoadSaveFunction().
static <T> T util.SaveLoadUtility.loadResource (Class className, String filePath) throws Exception static
Load a resource from a given file and return Java object representation
Parameters
className Java class object that is being loaded
filePath that resource to be loaded from
Returns
Java class object
Exceptions
Exception
Definition at line 42 of file SaveLoadUtility.java.
Referenced by gamemodel.MainModel.loadGame().
static File util.SaveLoadUtility.obtainFile (String filePath) throws IOException static private
Definition at line 74 of file SaveLoadUtility.java.
Referenced by util.SaveLoadUtility.loadImage(), util.SaveLoadUtility.save(), and util.SaveLoadUtility.saveImage().
static String util.SaveLoadUtility.preProcess (String source) static private
Definition at line 102 of file SaveLoadUtility.java.
Referenced by util.SaveLoadUtility.save(), and util.SaveLoadUtility.saveImage().
static String util.SaveLoadUtility.save (JSONable object, String filePath) throws Exception static
Save a JSONable object to a library file.
Parameters
object that can be converted to JSON format
sourcePath location to which object should be saved
Returns
filePath to which the JSON file is saved
Exceptions
Exception
Definition at line 58 of file SaveLoadUtility.java.
References util.SaveLoadUtility.obtainFile(), util.SaveLoadUtility.preProcess(), util.DefaultResource.setDefaults(), and util.SaveLoadUtility.topLevelDirectory().
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet(), gamemodel.MainModel.saveGame(), and test.util.TestLoadSaveUtility.testLoadSaveFunction().
static String util.SaveLoadUtility.saveImage (String source, String destination) throws IOException static
Parameters
sourcePath source location for the image
destinationPath destination location for the image
Returns
location that image is saved to (may be different to allow for cross-platform compatibility)
Exceptions
IOException
Definition at line 94 of file SaveLoadUtility.java.
References util.SaveLoadUtility.obtainFile(), and util.SaveLoadUtility.preProcess().
Referenced by gamemodel.MainModel.createDrawableGameElement(), and test.util.TestLoadSaveUtility.testLoadSaveFunction().
static String util.SaveLoadUtility.topLevelDirectory (String filePath) throws Exception static private
Definition at line 69 of file SaveLoadUtility.java.
Referenced by util.SaveLoadUtility.save().
Member Data Documentation
String util.SaveLoadUtility.FILE_SEPARATOR = System.getProperty("file.separator") static
Definition at line 28 of file SaveLoadUtility.java.
Referenced by test.util.TestLoadSaveUtility.testLoadSaveFunction().
final String util.SaveLoadUtility.IMAGE_NOT_LOADED = "Image could not be loaded" static private
Definition at line 27 of file SaveLoadUtility.java.
DefaultResource util.SaveLoadUtility.myDefaultResource = new DefaultResource() static private
Definition at line 29 of file SaveLoadUtility.java.
Gson util.SaveLoadUtility.myGson = new Gson() static private
Definition at line 30 of file SaveLoadUtility.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/util/SaveLoadUtility.java