voogasalad_TheException: game_requests.forwarding.RequestMediator Class Reference
game_requests.forwarding.RequestMediator Class Reference
Public Member Functions
RequestMediator ()
void forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
void register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
Private Member Functions
void checkValidAddress (String address) throws InvalidAddressException
void checkKnownAddress (String address) throws ReceiverNotFoundException
boolean isKnownAddress (String address)
Private Attributes
Map< String, IReceiver > myAddresses
Detailed Description
The main request manager class which forwards messages between game components
Definition at line 14 of file RequestMediator.java.
Constructor & Destructor Documentation
game_requests.forwarding.RequestMediator.RequestMediator ()
Definition at line 18 of file RequestMediator.java.
Member Function Documentation
void game_requests.forwarding.RequestMediator.checkKnownAddress (String address) throws ReceiverNotFoundException private
Definition at line 50 of file RequestMediator.java.
References game_requests.forwarding.RequestMediator.isKnownAddress().
Referenced by game_requests.forwarding.RequestMediator.forward().
void game_requests.forwarding.RequestMediator.checkValidAddress (String address) throws InvalidAddressException private
Definition at line 46 of file RequestMediator.java.
Referenced by game_requests.forwarding.RequestMediator.forward(), and game_requests.forwarding.RequestMediator.register().
void game_requests.forwarding.RequestMediator.forward (IRequest request) throws InvalidAddressException, ReceiverNotFoundException, DeliveryException
Forward a request to a recipient based on the details of that request
Parameters
request The request to forward
Exceptions
InvalidAddressException If the sender or receiver addresses are invalid
ReceiverNotFoundException If the receiver is not registered with this forwarder
DeliveryException If a problem occurs during delivery of the message to a receiver
Implements game_requests.forwarding.IForwarder.
Definition at line 23 of file RequestMediator.java.
References game_requests.forwarding.RequestMediator.checkKnownAddress(), and game_requests.forwarding.RequestMediator.checkValidAddress().
boolean game_requests.forwarding.RequestMediator.isKnownAddress (String address) private
Definition at line 56 of file RequestMediator.java.
Referenced by game_requests.forwarding.RequestMediator.checkKnownAddress(), and game_requests.forwarding.RequestMediator.register().
void game_requests.forwarding.RequestMediator.register (String address, IReceiver receiver) throws InvalidAddressException, AddressConflictException
Register a receiver that can receive messages via forward()
Parameters
address The address where the receiver can receive requests
receiver The receiver associated with the address
Exceptions
InvalidAddressException If the format of the address is not allowed by the forwarder
AddressConflictException If the address is already used by another receiver
Implements game_requests.forwarding.IForwarder.
Definition at line 37 of file RequestMediator.java.
References game_requests.forwarding.RequestMediator.checkValidAddress(), and game_requests.forwarding.RequestMediator.isKnownAddress().
Member Data Documentation
Map<String, IReceiver> game_requests.forwarding.RequestMediator.myAddresses private
Definition at line 16 of file RequestMediator.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_requests/forwarding/RequestMediator.java