voogasalad_TheException: engine.gameRepresentation.renderedRepresentation.GameElement Class Reference
engine.gameRepresentation.renderedRepresentation.GameElement Class Reference
Public Member Functions
GameElement (GameElementState gameElementState)
GameElementState getState ()
Iterator< Evaluatable<?> > getActionsOfType (ActionType actionType)
void addAction (ActionType actionType, Evaluatable<?> action)
Number getNumericalAttribute (String attributeTag)
void setNumericalAttribute (String attributeTag, Number attributeValue)
String getTextualAttribute (String attributeTag)
void setTextualAttribute (String attributeTag, String attributeValue)
void update ()
long getTimer (String timerName)
void setTimer (String timerName, long timerValue)
void updateTimers ()
Map< String, Long > getTimersCopy ()
void registerAsChild (Consumer< GameElementState > function)
boolean isType (String typeString)
List< String > getTypes ()
void setPosition (double x, double y)
Protected Member Functions
void executeAllActions (ActionType actionKey, ElementPair elementPair)
void executeAllActions (ActionType actionKey)
Private Member Functions
void createActionLists ()
void updateSelfDueToInternalFactors ()
Private Attributes
Map< ActionType, List< Evaluatable<?> > > myActionLists
GameElementState myState
Map< String, Long > myTimers
Detailed Description
A basic game element. Contains a state and a map strings to conditions and actions. Also contains an update method to update the element due to its internal state.
Author
Jonathan, Nishad, Rahul, Steve, Zach, Stanley
Definition at line 25 of file GameElement.java.
Constructor & Destructor Documentation
engine.gameRepresentation.renderedRepresentation.GameElement.GameElement (GameElementState gameElementState)
Create a game element with the given state
Parameters
gameElementState the state of the game element
Definition at line 41 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.createActionLists().
Member Function Documentation
void engine.gameRepresentation.renderedRepresentation.GameElement.addAction (ActionType actionType, Evaluatable<?> action)
Add an action of the given type to the array of actions
Parameters
actionType the type of the action to be added
action the action to be added
Definition at line 91 of file GameElement.java.
Referenced by engine.elementFactories.GameElementFactory.generateActions().
void engine.gameRepresentation.renderedRepresentation.GameElement.createActionLists () private
Ensure that lists are instantiated for all the possible action types of an element to protect against uninstantiated action entities at runtime.
Definition at line 55 of file GameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.GameElement.GameElement().
void engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions (ActionType actionKey, ElementPair elementPair) protected
Execute all the actions in a given key's list. Given an element pair
Parameters
actionKey the key of the action set for which to execute all of the actions
ElementPair an element pair of the current object and any objects it might be interested in e.g. the current unit and a unit nearby it
Definition at line 161 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.getActionsOfType().
Referenced by engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions(), engine.gameRepresentation.renderedRepresentation.SelectableGameElement.executeAllButtonActions(), engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCurrentObjective(), engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToFocusedElement(), engine.gameRepresentation.renderedRepresentation.GameElement.updateSelfDueToInternalFactors(), and engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToSelection().
void engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions (ActionType actionKey) protected
Execute all the actions in a given key's list given that there are no applicable elements for the action set.
Parameters
actionKey the key of the action set for which to execute all of the actions
Definition at line 171 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions().
Iterator<Evaluatable<?> > engine.gameRepresentation.renderedRepresentation.GameElement.getActionsOfType (ActionType actionType)
Get an iterator of the actions with a given tag
Parameters
actionType the tag for the type of action
Returns
an iterator containing all the actions of the desired type
Definition at line 73 of file GameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions(), and engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToInteractingElementsSubset().
Number engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute (String attributeTag)
Get a numeric attribute contained by the game element
Parameters
attributTag the tag of the attribute of interest
Returns
the atribute's value or 0 if the attribute was not declared
Definition at line 104 of file GameElement.java.
References model.state.gameelement.GameElementState.attributes, and model.state.gameelement.AttributeContainer.getNumericalAttribute().
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement(), engine.stateManaging.GameElementManager.checkOnTeam(), engine.gameRepresentation.evaluatables.evaluators.MovePlayer< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.MoveBack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Follow< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.UpdateMovementDirection< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.FollowX< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Attack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.SpawnSelectableElement< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.RandomWaypoint< A, B >.evaluate(), engine.gameRepresentation.evaluatables.actions.AttributeIncrementerAction.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.getCenter(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNextWaypoint(), engine.visuals.MiniMap.setUnitColor(), engine.visuals.MiniMap.setUnitShape(), and engine.stateManaging.GameLoop.updateRunner().
GameElementState engine.gameRepresentation.renderedRepresentation.GameElement.getState ()
Definition at line 47 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.myState.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.removeElement().
String engine.gameRepresentation.renderedRepresentation.GameElement.getTextualAttribute (String attributeTag)
Get a textual attribute contained by the game element
Parameters
attributeTag the tag of the attribute
Returns
the value of the attribute or "" if it does not exist
Definition at line 124 of file GameElement.java.
References model.state.gameelement.GameElementState.attributes, and model.state.gameelement.AttributeContainer.getTextualAttribute().
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getAbilityDescriptionMap(), and engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getType().
long engine.gameRepresentation.renderedRepresentation.GameElement.getTimer (String timerName)
Get the value of a timer with a given name
Parameters
timerName the name of the timer
Returns
the timer's value or 0 if the timer has not been initialized
Definition at line 181 of file GameElement.java.
Referenced by engine.gameRepresentation.evaluatables.evaluators.Attack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.actions.AttributeIncrementerAction.evaluate(), engine.gameRepresentation.evaluatables.actions.DecrementIncrementAttributeAction.evaluate(), engine.gameRepresentation.evaluatables.actions.MotherOfAllActions.evaluate(), and engine.gameRepresentation.evaluatables.actions.Action.executeActionIfTimerExpired().
Map<String, Long> engine.gameRepresentation.renderedRepresentation.GameElement.getTimersCopy ()
Definition at line 220 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.myTimers.
Referenced by engine.visuals.VisualManager.update().
List<String> engine.gameRepresentation.renderedRepresentation.GameElement.getTypes ()
Definition at line 232 of file GameElement.java.
References model.state.gameelement.GameElementState.getTypes().
boolean engine.gameRepresentation.renderedRepresentation.GameElement.isType (String typeString)
Definition at line 228 of file GameElement.java.
References model.state.gameelement.GameElementState.isType().
Referenced by engine.gameRepresentation.evaluatables.evaluators.TypeCheck< A, B >.evaluate().
void engine.gameRepresentation.renderedRepresentation.GameElement.registerAsChild (Consumer< GameElementState > function)
Definition at line 224 of file GameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement().
void engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute (String attributeTag, Number attributeValue)
Set a numeric attribute contained by the game element
Parameters
attributeTag the tag of the attribute
attributeValue the value of the attribute
Definition at line 114 of file GameElement.java.
References model.state.gameelement.GameElementState.attributes, and model.state.gameelement.AttributeContainer.setNumericalAttribute().
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.deselect(), engine.gameRepresentation.evaluatables.evaluators.MoveBack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.MovePlayer< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Follow< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.UpdateMovementDirection< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.FollowX< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Attack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.RandomWaypoint< A, B >.evaluate(), engine.gameRepresentation.evaluatables.actions.AttributeIncrementerAction.evaluate(), engine.gameRepresentation.evaluatables.actions.CheckAttributeCreateObjectAction.evaluate(), engine.gameRepresentation.renderedRepresentation.SelectableGameElement.select(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setGoalPositions(), engine.gameRepresentation.renderedRepresentation.GameElement.setPosition(), engine.gameRepresentation.renderedRepresentation.GameElement.setTimer(), and engine.gameRepresentation.renderedRepresentation.GameElement.updateTimers().
void engine.gameRepresentation.renderedRepresentation.GameElement.setPosition (double x, double y)
Definition at line 236 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute(), model.state.gameelement.StateTags.X_GOAL_POSITION, model.state.gameelement.StateTags.X_POSITION, model.state.gameelement.StateTags.X_TEMP_GOAL_POSITION, model.state.gameelement.StateTags.Y_GOAL_POSITION, model.state.gameelement.StateTags.Y_POSITION, and model.state.gameelement.StateTags.Y_TEMP_GOAL_POSITION.
Referenced by engine.elementFactories.GameElementFactory.createDrawableGameElement(), engine.elementFactories.GameElementFactory.createGameElement(), engine.elementFactories.GameElementFactory.createSelectableGameElement(), and engine.stateManaging.GameElementManager.moveSelectedUnit().
void engine.gameRepresentation.renderedRepresentation.GameElement.setTextualAttribute (String attributeTag, String attributeValue)
Set the value of a textual attribute contained by the game element
Parameters
attributeTag the tag of the attribute
attributeValue the attribute's value
Definition at line 134 of file GameElement.java.
References model.state.gameelement.GameElementState.attributes, and model.state.gameelement.AttributeContainer.setTextualAttribute().
void engine.gameRepresentation.renderedRepresentation.GameElement.setTimer (String timerName, long timerValue)
Set the value of a timer with a given name to a given number of updates
Parameters
timerName the name of the timer
timerValue its value
Definition at line 195 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute().
Referenced by engine.gameRepresentation.evaluatables.evaluators.Attack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.actions.AttributeIncrementerAction.evaluate(), engine.gameRepresentation.evaluatables.actions.DecrementIncrementAttributeAction.evaluate(), engine.gameRepresentation.evaluatables.actions.MotherOfAllActions.evaluate(), and engine.gameRepresentation.evaluatables.actions.Action.executeActionIfTimerExpired().
void engine.gameRepresentation.renderedRepresentation.GameElement.update ()
Update the element based on its internal state
Definition at line 141 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.updateSelfDueToInternalFactors(), and engine.gameRepresentation.renderedRepresentation.GameElement.updateTimers().
void engine.gameRepresentation.renderedRepresentation.GameElement.updateSelfDueToInternalFactors () private
Update the game element due to actions that execute on its internal factors e.g. move the element based on its internal velocity parameters.
Definition at line 150 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions(), and engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL.
Referenced by engine.gameRepresentation.renderedRepresentation.GameElement.update().
void engine.gameRepresentation.renderedRepresentation.GameElement.updateTimers ()
Update all the timers. If a timer's value is 0, remove the timer from the map in order to save space and processing time.
Definition at line 204 of file GameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute().
Referenced by engine.gameRepresentation.renderedRepresentation.GameElement.update().
Member Data Documentation
Map<ActionType, List<Evaluatable<?> > > engine.gameRepresentation.renderedRepresentation.GameElement.myActionLists private
The action lists map is a map of action strings to lists of possible actions. For example, The String "Collision" might map to a list of actions that should be run whenever an element is dealing with a collision with another element whereas "Action1" might map to a list of actions that should be executed when an element's action button is clicked.
Definition at line 32 of file GameElement.java.
GameElementState engine.gameRepresentation.renderedRepresentation.GameElement.myState private
Definition at line 33 of file GameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.GameElement.getState().
Map<String, Long> engine.gameRepresentation.renderedRepresentation.GameElement.myTimers private
Definition at line 34 of file GameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.GameElement.getTimersCopy().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/renderedRepresentation/GameElement.java