voogasalad_TheException: view.runner.GameRunnerPaneController Class Reference
view.runner.GameRunnerPaneController Class Reference
Public Member Functions
Node getRoot ()
LevelState getLevelState ()
void setLevel (LevelState levelState)
void setInputManager (Class<?> inputManagerClass)
void setOnDone (EventHandler< ActionEvent > event)
void modelUpdate ()
void engineUpdate (AttributeContainer attributes)
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Protected Member Functions
void init ()
Protected Member Functions inherited from view.gui.StackPaneGUIContainer
void setFront (Node child)
void bindPaneSize (Pane pane)
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Private Attributes
Button sizedButton
BorderPane runnerPane
BorderPane gameEnd
GameEndController gameEndController
LevelState myLevel
Engine myEngine
Additional Inherited Members
Protected Attributes inherited from view.gui.StackPaneGUIContainer
StackPane stackPane
Button sizedButton
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Detailed Description
Game Runner View Controller holds scene graph as well as button pane, status pane, and minimap
Author
Jonathan Tseng
Definition at line 31 of file GameRunnerPaneController.java.
Member Function Documentation
void view.runner.GameRunnerPaneController.engineUpdate (AttributeContainer attributes)
Definition at line 101 of file GameRunnerPaneController.java.
References model.state.DescribableState.getName(), model.state.gameelement.AttributeContainer.getNumericalAttributes(), view.gui.StackPaneGUIContainer.setFront(), and view.runner.GameEndController.updateGameEndView().
LevelState view.runner.GameRunnerPaneController.getLevelState ()
Definition at line 50 of file GameRunnerPaneController.java.
References view.runner.GameRunnerPaneController.myLevel.
Referenced by view.editor.TabViewController.updateModelToSave().
Node view.runner.GameRunnerPaneController.getRoot ()
Implements view.gui.GUIController.
Definition at line 46 of file GameRunnerPaneController.java.
References view.gui.StackPaneGUIContainer.stackPane.
void view.runner.GameRunnerPaneController.init () protected
Definition at line 91 of file GameRunnerPaneController.java.
void view.runner.GameRunnerPaneController.modelUpdate ()
Definition at line 96 of file GameRunnerPaneController.java.
void view.runner.GameRunnerPaneController.setInputManager (Class<?> inputManagerClass)
Definition at line 76 of file GameRunnerPaneController.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), and engine.Engine.setInputManager().
Referenced by view.editor.TabViewController.initToggle().
void view.runner.GameRunnerPaneController.setLevel (LevelState levelState)
Definition at line 54 of file GameRunnerPaneController.java.
References view.gui.StackPaneGUIContainer.bindPaneSize(), view.dialog.DialogBoxUtility.createMessageDialog(), util.DeepCopy.deepCopy(), engine.Engine.getScene(), view.gui.GUIContainer.myMainModel, engine.Engine.play(), and view.gui.StackPaneGUIContainer.setFront().
Referenced by view.runner.RunnerScreen.playLevel(), and view.editor.TabViewController.startLevel().
void view.runner.GameRunnerPaneController.setOnDone (EventHandler< ActionEvent > event)
Definition at line 86 of file GameRunnerPaneController.java.
References view.runner.GameEndController.setOnDone().
Referenced by view.runner.RunnerScreen.init(), and view.editor.TabViewController.setLevel().
Member Data Documentation
BorderPane view.runner.GameRunnerPaneController.gameEnd private
Definition at line 38 of file GameRunnerPaneController.java.
GameEndController view.runner.GameRunnerPaneController.gameEndController private
Definition at line 40 of file GameRunnerPaneController.java.
Engine view.runner.GameRunnerPaneController.myEngine private
Definition at line 43 of file GameRunnerPaneController.java.
LevelState view.runner.GameRunnerPaneController.myLevel private
Definition at line 42 of file GameRunnerPaneController.java.
Referenced by view.runner.GameRunnerPaneController.getLevelState().
BorderPane view.runner.GameRunnerPaneController.runnerPane private
Definition at line 36 of file GameRunnerPaneController.java.
Button view.runner.GameRunnerPaneController.sizedButton private
Definition at line 34 of file GameRunnerPaneController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/runner/GameRunnerPaneController.java