voogasalad_TheException: game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState Class Reference
game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState Class Reference
Public Member Functions
DrawableGameElementState (Number xPosition, Number yPosition)
void addAnimation (AnimationSequence animation)
AnimationSequence getAnimation (String animationName)
void setSpritesheet (Spritesheet spritesheet)
Spritesheet getSpritesheet ()
double[] getBounds ()
void setBounds (double[] bounds)
Public Member Functions inherited from game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState
GameElementState ()
String getName ()
String getType ()
String getTextualAttribute (String name)
Number getNumericalAttribute (String name)
void setTextualAttribute (String name, String value)
void setNumericalAttribute (String name, Number value)
void addAction (String actionType, String actionString)
Map< String, List< String > > getActions ()
Public Member Functions inherited from util.JSONable
default String toJSON ()
Private Attributes
Spritesheet mySpritesheet
Map< String, AnimationSequence > myAnimations
double[] myBounds
boolean myIsAnimationSequenceInitalized = true
Additional Inherited Members
Protected Attributes inherited from game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState
Map< String, List< String > > myActions
Set< Attribute< Number > > myNumericalAttributes
Set< Attribute< String > > myTextualAttributes
Package Functions inherited from game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState
private< T > T getAttribute (Collection< Attribute< T >> collection, String attributeName, T defaultReturnObject)
private< T > void addAttribute (Collection< Attribute< T >> collection, String attributeName, T attributeValue)
Detailed Description
This GameElement is drawable but not necessarily selectable - examples include terrain. These elements must have a bounding box.
Author
Steve, Jonathan, Rahul, Zach
Definition at line 19 of file DrawableGameElementState.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.DrawableGameElementState (Number xPosition, Number yPosition)
Create a drawable game element at a given x and y position.
Parameters
xPosition the x position of the element
yPosition the y position of the element
Definition at line 33 of file DrawableGameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.myNumericalAttributes, game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.X_POS_STRING, and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.Y_POS_STRING.
Member Function Documentation
void game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.addAnimation (AnimationSequence animation)
Add an animation to the DrawableGameElementState's list of possible animations
Parameters
animation the animation to add
Definition at line 52 of file DrawableGameElementState.java.
References game_engine.visuals.AnimationSequence.toString().
Referenced by application.ShittyMain.createArcher(), and application.ShittyMain.hardCodeAGame().
AnimationSequence game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.getAnimation (String animationName)
Return the animation sequence with a given name
Parameters
animationName the name of the amimation sequence
Returns
the animation of interest if it exists or null if it does not
Definition at line 69 of file DrawableGameElementState.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setAnimation().
double [] game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.getBounds ()
Returns
the bounds of the bounded object
Implements game_engine.gameRepresentation.stateRepresentation.gameElement.traits.Boundable.
Definition at line 93 of file DrawableGameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.myBounds.
Referenced by game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getBounds().
Spritesheet game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.getSpritesheet ()
Get the current spritesheet held by the state
Returns
the current spritesheet of the state
Definition at line 88 of file DrawableGameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.mySpritesheet.
Referenced by game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.DrawableGameElement().
void game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setBounds (double[] bounds)
Set the bounds
Parameters
bounds the new bounds of the state set in a format that is usable by JavaFx's Polygon object
Definition at line 103 of file DrawableGameElementState.java.
Referenced by application.ShittyMain.createArcher(), gamemodel.GameElementStateFactory.createDrawableGameElementState(), application.ShittyMain.hardCodeAGame(), and test.conditions.ConditionFunctionalityTest.initialize().
void game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setSpritesheet (Spritesheet spritesheet)
Set the spritesheet of the game element to be the given spritesheet object
Parameters
spritesheet the spritesheet to set
Definition at line 79 of file DrawableGameElementState.java.
Referenced by application.ShittyMain.createArcher(), gamemodel.GameElementStateFactory.createDrawableGameElementState(), application.ShittyMain.hardCodeAGame(), test.conditions.ConditionFunctionalityTest.initialize(), and game_engine.visuals.TerrainGrid.renderTerrain().
Member Data Documentation
Map<String, AnimationSequence> game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.myAnimations private
Definition at line 23 of file DrawableGameElementState.java.
double [] game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.myBounds private
Definition at line 24 of file DrawableGameElementState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.getBounds().
boolean game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.myIsAnimationSequenceInitalized = true private
Definition at line 25 of file DrawableGameElementState.java.
Spritesheet game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.mySpritesheet private
Definition at line 22 of file DrawableGameElementState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.getSpritesheet().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/stateRepresentation/gameElement/DrawableGameElementState.java