voogasalad_TheException: editor.EditorMenuBarController Class Reference
editor.EditorMenuBarController Class Reference
Public Member Functions
Node getRoot ()
void init ()
void update ()
Public Member Functions inherited from view.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
abstract void update ()
Private Member Functions
void attachTextProperties ()
void initLanguageMenu ()
void initFileMenu ()
void onNewLevelClick ()
void onNewCampaignClick ()
Private Attributes
MenuBar menuBar
Menu fileMenu
MenuItem newCampaignMenuItem
MenuItem newLevelMenuItem
MenuItem saveMenuItem
Menu languageMenu
Static Private Attributes
static final String FILE_KEY = "File"
static final String NEW_CAMPAIGN_KEY = "NewCampaign"
static final String NEW_LEVEL_KEY = "NewLevel"
static final String SAVE_KEY = "Save"
static final String LANGUAGE_KEY = "Languages"
static final String CAMPAIGN_WIZARD = "/editor/wizards/guipanes/CampaignWizard.fxml"
static final String LEVEL_WIZARD = "/editor/wizards/guipanes/LevelWizard.fxml"
Additional Inherited Members
Protected Member Functions inherited from view.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.GUIContainer
MainModel myMainModel
Detailed Description
Author
Nishad Agrawal
Jonathan Tseng
Definition at line 25 of file EditorMenuBarController.java.
Member Function Documentation
void editor.EditorMenuBarController.attachTextProperties () private
Definition at line 63 of file EditorMenuBarController.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by editor.EditorMenuBarController.init().
Node editor.EditorMenuBarController.getRoot ()
Implements view.GUIController.
Definition at line 52 of file EditorMenuBarController.java.
References editor.EditorMenuBarController.menuBar.
void editor.EditorMenuBarController.init ()
Definition at line 57 of file EditorMenuBarController.java.
References editor.EditorMenuBarController.attachTextProperties(), editor.EditorMenuBarController.initFileMenu(), and editor.EditorMenuBarController.initLanguageMenu().
void editor.EditorMenuBarController.initFileMenu () private
Definition at line 93 of file EditorMenuBarController.java.
References view.GUIContainer.myMainModel, editor.EditorMenuBarController.onNewCampaignClick(), editor.EditorMenuBarController.onNewLevelClick(), and gamemodel.MainModel.saveGame().
Referenced by editor.EditorMenuBarController.init().
void editor.EditorMenuBarController.initLanguageMenu () private
Definition at line 77 of file EditorMenuBarController.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getSupportedLanguages(), and util.multilanguage.MultiLanguageUtility.setLanguage().
Referenced by editor.EditorMenuBarController.init().
void editor.EditorMenuBarController.onNewCampaignClick () private
Definition at line 115 of file EditorMenuBarController.java.
References gamemodel.MainModel.createCampaign(), editor.wizards.Wizard.getStage(), view.WizardUtility.loadWizard(), view.GUIContainer.myMainModel, gamemodel.GameElementStateFactory.NAME, editor.wizards.Wizard.setErrorMesssage(), and editor.wizards.Wizard.setSubmit().
Referenced by editor.EditorMenuBarController.initFileMenu().
void editor.EditorMenuBarController.onNewLevelClick () private
Definition at line 101 of file EditorMenuBarController.java.
References gamemodel.GameElementStateFactory.CAMPAIGN, gamemodel.MainModel.createLevel(), editor.wizards.Wizard.getStage(), view.WizardUtility.loadWizard(), view.GUIContainer.myMainModel, gamemodel.GameElementStateFactory.NAME, editor.wizards.Wizard.setErrorMesssage(), and editor.wizards.Wizard.setSubmit().
Referenced by editor.EditorMenuBarController.initFileMenu().
void editor.EditorMenuBarController.update ()
Definition at line 130 of file EditorMenuBarController.java.
Member Data Documentation
final String editor.EditorMenuBarController.CAMPAIGN_WIZARD = "/editor/wizards/guipanes/CampaignWizard.fxml" static private
Definition at line 34 of file EditorMenuBarController.java.
final String editor.EditorMenuBarController.FILE_KEY = "File" static private
Definition at line 27 of file EditorMenuBarController.java.
Menu editor.EditorMenuBarController.fileMenu private
Definition at line 40 of file EditorMenuBarController.java.
final String editor.EditorMenuBarController.LANGUAGE_KEY = "Languages" static private
Definition at line 32 of file EditorMenuBarController.java.
Menu editor.EditorMenuBarController.languageMenu private
Definition at line 49 of file EditorMenuBarController.java.
final String editor.EditorMenuBarController.LEVEL_WIZARD = "/editor/wizards/guipanes/LevelWizard.fxml" static private
Definition at line 35 of file EditorMenuBarController.java.
MenuBar editor.EditorMenuBarController.menuBar private
Definition at line 38 of file EditorMenuBarController.java.
Referenced by editor.EditorMenuBarController.getRoot().
final String editor.EditorMenuBarController.NEW_CAMPAIGN_KEY = "NewCampaign" static private
Definition at line 28 of file EditorMenuBarController.java.
final String editor.EditorMenuBarController.NEW_LEVEL_KEY = "NewLevel" static private
Definition at line 29 of file EditorMenuBarController.java.
MenuItem editor.EditorMenuBarController.newCampaignMenuItem private
Definition at line 42 of file EditorMenuBarController.java.
MenuItem editor.EditorMenuBarController.newLevelMenuItem private
Definition at line 44 of file EditorMenuBarController.java.
final String editor.EditorMenuBarController.SAVE_KEY = "Save" static private
Definition at line 30 of file EditorMenuBarController.java.
MenuItem editor.EditorMenuBarController.saveMenuItem private
Definition at line 46 of file EditorMenuBarController.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/EditorMenuBarController.java