voogasalad_TheException: engine.gameRepresentation.renderedRepresentation.DrawableGameElement Class Reference
engine.gameRepresentation.renderedRepresentation.DrawableGameElement Class Reference
Public Member Functions
DrawableGameElement (DrawableGameElementState state, Visualizer visualizer)
void update ()
Node getNode ()
double[] getBounds ()
Point2D getPosition ()
void registerAsDrawableChild (Consumer< DrawableGameElementState > function)
double[] findGlobalBounds ()
void setWaypoints (List< Location > waypointsToAdd)
void addWaypoint (double x, double y)
Location getNextWaypoint ()
List< Line > getLines ()
Public Member Functions inherited from engine.gameRepresentation.renderedRepresentation.GameElement
GameElement (GameElementState gameElementState)
GameElementState getState ()
Iterator< Evaluatable<?> > getActionsOfType (ActionType actionType)
void addAction (ActionType actionType, Evaluatable<?> action)
Number getNumericalAttribute (String attributeTag)
void setNumericalAttribute (String attributeTag, Number attributeValue)
String getTextualAttribute (String attributeTag)
void setTextualAttribute (String attributeTag, String attributeValue)
void update ()
long getTimer (String timerName)
void setTimer (String timerName, long timerValue)
void updateTimers ()
Map< String, Long > getTimersCopy ()
void registerAsChild (Consumer< GameElementState > function)
boolean isType (String typeString)
List< String > getTypes ()
void setPosition (double x, double y)
Private Member Functions
void setGoalPositions (Location newGoal)
void createLine (List< Line > lines, Color color, double firstX, double firstY, double lastX, double lastY)
Private Attributes
DrawableGameElementState drawableState
Visualizer myVisualizer
Queue< Location > wayPoints
Additional Inherited Members
Protected Member Functions inherited from engine.gameRepresentation.renderedRepresentation.GameElement
void executeAllActions (ActionType actionKey, ElementPair elementPair)
void executeAllActions (ActionType actionKey)
Detailed Description
A game element that is capable of being drawn. Combines a game element state as well as an animation player. Essentially wraps a savable game element state with a drawable wrapper to avoid JavaFX serialization problems.
Author
Zach, Jonathan, Nishad, Rahul, John L., Michael D., Stanley
Definition at line 28 of file DrawableGameElement.java.
Constructor & Destructor Documentation
engine.gameRepresentation.renderedRepresentation.DrawableGameElement.DrawableGameElement (DrawableGameElementState state, Visualizer visualizer)
Create a drawable game element from the given state
Parameters
state the state of the drawable element
actions the actions map for the game element (Created by a factory to be passed into the element)
Definition at line 44 of file DrawableGameElement.java.
References engine.visuals.elementVisuals.Visualizer.initializeDisplay().
Member Function Documentation
void engine.gameRepresentation.renderedRepresentation.DrawableGameElement.addWaypoint (double x, double y)
Definition at line 100 of file DrawableGameElement.java.
void engine.gameRepresentation.renderedRepresentation.DrawableGameElement.createLine (List< Line > lines, Color color, double firstX, double firstY, double lastX, double lastY) private
Definition at line 153 of file DrawableGameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines().
double [] engine.gameRepresentation.renderedRepresentation.DrawableGameElement.findGlobalBounds ()
Implements model.state.gameelement.traits.Boundable.
Definition at line 78 of file DrawableGameElement.java.
References model.state.gameelement.DrawableGameElementState.findGlobalBounds().
double [] engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getBounds ()
Returns
the bounds of the bounded object
Implements model.state.gameelement.traits.Boundable.
Definition at line 64 of file DrawableGameElement.java.
References model.state.gameelement.DrawableGameElementState.getBounds().
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement().
List<Line> engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines ()
Definition at line 114 of file DrawableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.DrawableGameElement.createLine(), engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), engine.computers.pathingComputers.Location.getX(), engine.computers.pathingComputers.Location.getY(), model.state.gameelement.StateTags.IS_SELECTED, model.state.gameelement.StateTags.X_GOAL_POSITION, model.state.gameelement.StateTags.X_POSITION, model.state.gameelement.StateTags.Y_GOAL_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
Location engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNextWaypoint ()
Definition at line 105 of file DrawableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
Referenced by engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate().
Node engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode ()
Returns
the object's display node
Implements engine.visuals.Displayable.
Definition at line 60 of file DrawableGameElement.java.
References engine.visuals.elementVisuals.Visualizer.getNode().
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement(), and engine.gameRepresentation.renderedRepresentation.Level.removeElement().
Point2D engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getPosition ()
Definition at line 68 of file DrawableGameElement.java.
References engine.visuals.elementVisuals.Visualizer.getNodeLocation().
Referenced by engine.visuals.MiniMap.setUnitShape().
void engine.gameRepresentation.renderedRepresentation.DrawableGameElement.registerAsDrawableChild (Consumer< DrawableGameElementState > function)
Definition at line 72 of file DrawableGameElement.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement().
void engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setGoalPositions (Location newGoal) private
Definition at line 89 of file DrawableGameElement.java.
References engine.computers.pathingComputers.Location.getX(), engine.computers.pathingComputers.Location.getY(), engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute(), model.state.gameelement.StateTags.X_GOAL_POSITION, model.state.gameelement.StateTags.X_TEMP_GOAL_POSITION, model.state.gameelement.StateTags.Y_GOAL_POSITION, and model.state.gameelement.StateTags.Y_TEMP_GOAL_POSITION.
Referenced by engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setWaypoints().
void engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setWaypoints (List< Location > waypointsToAdd)
Definition at line 82 of file DrawableGameElement.java.
References engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setGoalPositions().
void engine.gameRepresentation.renderedRepresentation.DrawableGameElement.update ()
Definition at line 54 of file DrawableGameElement.java.
References engine.visuals.elementVisuals.Visualizer.update().
Referenced by engine.stateManaging.GameLoop.updateEditor().
Member Data Documentation
DrawableGameElementState engine.gameRepresentation.renderedRepresentation.DrawableGameElement.drawableState private
Definition at line 31 of file DrawableGameElement.java.
Visualizer engine.gameRepresentation.renderedRepresentation.DrawableGameElement.myVisualizer private
Definition at line 32 of file DrawableGameElement.java.
Queue<Location> engine.gameRepresentation.renderedRepresentation.DrawableGameElement.wayPoints private
Definition at line 33 of file DrawableGameElement.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/renderedRepresentation/DrawableGameElement.java