voogasalad_TheException: engine.visuals.AbilityMatrix Class Reference
engine.visuals.AbilityMatrix Class Reference
Public Member Functions
AbilityMatrix (ReadOnlyDoubleProperty widthProperty, ReadOnlyDoubleProperty heightProperty)
Node getNode ()
void attachInputManager (InputManager inputManager)
void updateGridImages (Map< Integer, String > map, Map< String, Long > timerMap)
Static Public Attributes
static final int MATRIX_NUM_ROWS = 4
static final int MATRIX_NUM_COLS = 4
static final double BUTTON_WIDTH = 45
static final int NUM_ATTRIBUTES = MATRIX_NUM_COLS * MATRIX_NUM_ROWS
Private Member Functions
void initializeDisplay (ReadOnlyDoubleProperty heightProperty)
void initializeButtons ()
Private Attributes
GridPane buttonGrid
List< Button > buttonList
InputManager myInputManager
Static Private Attributes
static final double GRID_SPACING = 2
static NumberBinding yPos
Detailed Description
Definition at line 24 of file AbilityMatrix.java.
Constructor & Destructor Documentation
engine.visuals.AbilityMatrix.AbilityMatrix (ReadOnlyDoubleProperty widthProperty, ReadOnlyDoubleProperty heightProperty)
Definition at line 38 of file AbilityMatrix.java.
References engine.visuals.AbilityMatrix.initializeButtons(), and engine.visuals.AbilityMatrix.initializeDisplay().
Member Function Documentation
void engine.visuals.AbilityMatrix.attachInputManager (InputManager inputManager)
Definition at line 80 of file AbilityMatrix.java.
Referenced by engine.visuals.VisualManager.attachInputManager().
Node engine.visuals.AbilityMatrix.getNode ()
Definition at line 76 of file AbilityMatrix.java.
References engine.visuals.AbilityMatrix.buttonGrid.
Referenced by engine.visuals.VisualManager.VisualManager().
void engine.visuals.AbilityMatrix.initializeButtons () private
Definition at line 58 of file AbilityMatrix.java.
References engine.visuals.AbilityMatrix.MATRIX_NUM_COLS, engine.visuals.AbilityMatrix.MATRIX_NUM_ROWS, and engine.UI.InputManager.screenButtonClicked().
Referenced by engine.visuals.AbilityMatrix.AbilityMatrix().
void engine.visuals.AbilityMatrix.initializeDisplay (ReadOnlyDoubleProperty heightProperty) private
Definition at line 46 of file AbilityMatrix.java.
References engine.visuals.ScrollablePane.FAST_SCROLL_BOUNDARY.
Referenced by engine.visuals.AbilityMatrix.AbilityMatrix().
void engine.visuals.AbilityMatrix.updateGridImages (Map< Integer, String > map, Map< String, Long > timerMap)
Definition at line 84 of file AbilityMatrix.java.
References util.SaveLoadUtility.loadImage().
Referenced by engine.visuals.VisualManager.update().
Member Data Documentation
final double engine.visuals.AbilityMatrix.BUTTON_WIDTH = 45 static
Definition at line 28 of file AbilityMatrix.java.
GridPane engine.visuals.AbilityMatrix.buttonGrid private
Definition at line 32 of file AbilityMatrix.java.
Referenced by engine.visuals.AbilityMatrix.getNode().
List<Button> engine.visuals.AbilityMatrix.buttonList private
Definition at line 33 of file AbilityMatrix.java.
final double engine.visuals.AbilityMatrix.GRID_SPACING = 2 static private
Definition at line 25 of file AbilityMatrix.java.
final int engine.visuals.AbilityMatrix.MATRIX_NUM_COLS = 4 static
Definition at line 27 of file AbilityMatrix.java.
Referenced by engine.visuals.AbilityMatrix.initializeButtons().
final int engine.visuals.AbilityMatrix.MATRIX_NUM_ROWS = 4 static
Definition at line 26 of file AbilityMatrix.java.
Referenced by engine.visuals.AbilityMatrix.initializeButtons().
InputManager engine.visuals.AbilityMatrix.myInputManager private
Definition at line 34 of file AbilityMatrix.java.
final int engine.visuals.AbilityMatrix.NUM_ATTRIBUTES = MATRIX_NUM_COLS * MATRIX_NUM_ROWS static
Definition at line 30 of file AbilityMatrix.java.
Referenced by engine.visuals.VisualManager.update().
NumberBinding engine.visuals.AbilityMatrix.yPos static private
Definition at line 36 of file AbilityMatrix.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/AbilityMatrix.java