voogasalad_TheException: model.state.gameelement.StateTags Enum Reference
model.state.gameelement.StateTags Enum Reference
Classes
enum StateType
Public Member Functions
StateType getType ()
String getValue ()
Static Public Member Functions
static Set< String > getAllAttributes ()
static Set< String > getAllNumericalAttributes ()
static Set< String > getAllTextualAttributes ()
Public Attributes
BACKGROUND_PATH =(StateType.STRING, "backgroundPath")
NAME =(StateType.STRING, "name")
TYPE =(StateType.STRING, "type")
CURRENT_ACTION =(StateType.STRING, "currentAction")
ATTRIBUTE_DESCRIPTION =(StateType.STRING, "attributeDescription")
TEAM_COLOR =(StateType.NUMBER, "teamColor")
X_POSITION =(StateType.NUMBER, "xPosition")
Y_POSITION =(StateType.NUMBER, "yPosition")
X_VELOCITY =(StateType.NUMBER, "xVelocity")
Y_VELOCITY =(StateType.NUMBER, "yVelocity")
X_GOAL_POSITION =(StateType.NUMBER, "xGoalPosition")
Y_GOAL_POSITION =(StateType.NUMBER, "yGoalPosition")
X_TEMP_GOAL_POSITION =(StateType.NUMBER, "xTempGoalPosition")
Y_TEMP_GOAL_POSITION =(StateType.NUMBER, "yTempGoalPosition")
RANDOM_MOVEMENT_FLAG =(StateType.NUMBER, "randomMovementFlag")
MOVEMENT_SPEED =(StateType.NUMBER, "movementSpeed")
BLOCKING =(StateType.NUMBER, "blocking")
IS_SELECTED =(StateType.NUMBER, "isSelected")
ATTACK =(StateType.NUMBER, "attack")
HEALTH =(StateType.NUMBER, "health")
LEVEL_HEIGHT =(StateType.NUMBER, "levelHeight")
LEVEL_WIDTH =(StateType.NUMBER, "levelWidth")
RELOAD_TIME =(StateType.NUMBER, "reloadTime")
IS_DEAD =(StateType.NUMBER, "isDead")
X_SPAWN_OFFSET =(StateType.NUMBER, "xSpawnOffset")
Y_SPAWN_OFFSET =(StateType.NUMBER, "ySpawnOffset")
SUPPORTS_RANGED_ATTACK =(StateType.NUMBER, "supportsRangedAttack")
LAST_BUTTON_CLICKED_ID =(StateType.NUMBER, "lastButtonID")
RESOURCES =(StateType.NUMBER, "resources")
TIMER =(StateType.NUMBER, "gameTimer")
Private Member Functions
StateTags (StateType type, String value)
Static Private Member Functions
static Set< StateTags > getAttributes ()
static Set< String > filterByType (StateType type)
Private Attributes
StateType myType
String myValue
Detailed Description
An enumeration to allow for the important tags of states.
Author
Zach, Stanley
Definition at line 14 of file StateTags.java.
Constructor & Destructor Documentation
model.state.gameelement.StateTags.StateTags (StateType type, String value) private
Definition at line 51 of file StateTags.java.
Member Function Documentation
static Set<String> model.state.gameelement.StateTags.filterByType (StateType type) static private
Definition at line 77 of file StateTags.java.
static Set<String> model.state.gameelement.StateTags.getAllAttributes () static
Definition at line 73 of file StateTags.java.
Referenced by view.editor.wizards.WidgetWizard.initialize(), and view.editor.wizards.ActionWizard.initialize().
static Set<String> model.state.gameelement.StateTags.getAllNumericalAttributes () static
Definition at line 82 of file StateTags.java.
References model.state.gameelement.StateTags.StateType.NUMBER.
Referenced by view.editor.wizards.NumberAttributeWizard.initialize(), and view.editor.wizards.WidgetWizard.newAttribute().
static Set<String> model.state.gameelement.StateTags.getAllTextualAttributes () static
Definition at line 86 of file StateTags.java.
References model.state.gameelement.StateTags.StateType.STRING.
Referenced by view.editor.wizards.AttributeWizard.initialize().
static Set<StateTags> model.state.gameelement.StateTags.getAttributes () static private
Definition at line 68 of file StateTags.java.
StateType model.state.gameelement.StateTags.getType ()
Definition at line 56 of file StateTags.java.
String model.state.gameelement.StateTags.getValue ()
Definition at line 60 of file StateTags.java.
Member Data Documentation
model.state.gameelement.StateTags.ATTACK =(StateType.NUMBER, "attack")
Definition at line 35 of file StateTags.java.
Referenced by application.RPG.createMovingUnit(), engine.gameRepresentation.evaluatables.evaluators.Attack< A, B >.evaluate(), and application.RPG.hardCodeAGame().
model.state.gameelement.StateTags.ATTRIBUTE_DESCRIPTION =(StateType.STRING, "attributeDescription")
Definition at line 20 of file StateTags.java.
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getAbilityDescriptionMap(), and application.RPG.hardCodeAGame().
model.state.gameelement.StateTags.BACKGROUND_PATH =(StateType.STRING, "backgroundPath")
Definition at line 16 of file StateTags.java.
Referenced by model.MainModel.createLevel(), application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), and engine.Engine.instantiateVisualManager().
model.state.gameelement.StateTags.BLOCKING =(StateType.NUMBER, "blocking")
Definition at line 33 of file StateTags.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement(), and engine.elementFactories.LevelFactory.updateGridForObstacles().
model.state.gameelement.StateTags.CURRENT_ACTION =(StateType.STRING, "currentAction")
Definition at line 19 of file StateTags.java.
Referenced by application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalDisplayMarker(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), and engine.visuals.elementVisuals.animations.Animator.determineAnimationType().
model.state.gameelement.StateTags.HEALTH =(StateType.NUMBER, "health")
Definition at line 36 of file StateTags.java.
Referenced by application.RPG.createMovingUnit(), application.RPG.createSpawnPoint(), engine.gameRepresentation.evaluatables.evaluators.Attack< A, B >.evaluate(), application.RPG.hardCodeAGame(), and engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.toggleOpacity().
model.state.gameelement.StateTags.IS_DEAD =(StateType.NUMBER, "isDead")
Definition at line 40 of file StateTags.java.
Referenced by application.RPG.createEnemyUnit(), application.RPG.hardCodeAGame(), and engine.stateManaging.GameLoop.updateRunner().
model.state.gameelement.StateTags.IS_SELECTED =(StateType.NUMBER, "isSelected")
Definition at line 34 of file StateTags.java.
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.deselect(), engine.stateManaging.GameElementManager.filterSelectedUnits(), engine.visuals.VisualManager.findFirstSelectedElement(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines(), application.Pong.hardCodeAGame(), engine.gameRepresentation.renderedRepresentation.SelectableGameElement.select(), and engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.toggleOpacity().
model.state.gameelement.StateTags.LAST_BUTTON_CLICKED_ID =(StateType.NUMBER, "lastButtonID")
Definition at line 44 of file StateTags.java.
Referenced by application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), and engine.stateManaging.GameElementManager.notifyButtonClicked().
model.state.gameelement.StateTags.LEVEL_HEIGHT =(StateType.NUMBER, "levelHeight")
Definition at line 37 of file StateTags.java.
Referenced by model.MainModel.areCoordinatesValid(), engine.elementFactories.LevelFactory.createLevel(), model.MainModel.createLevel(), engine.gameRepresentation.renderedRepresentation.Level.getMapHeight(), application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), and model.MainModel.setTerrain().
model.state.gameelement.StateTags.LEVEL_WIDTH =(StateType.NUMBER, "levelWidth")
Definition at line 38 of file StateTags.java.
Referenced by model.MainModel.areCoordinatesValid(), engine.elementFactories.LevelFactory.createLevel(), model.MainModel.createLevel(), engine.gameRepresentation.renderedRepresentation.Level.getMapWidth(), application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), and model.MainModel.setTerrain().
model.state.gameelement.StateTags.MOVEMENT_SPEED =(StateType.NUMBER, "movementSpeed")
Definition at line 32 of file StateTags.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement(), application.Pong.createBall(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), application.RPG.createSpawnPoint(), engine.gameRepresentation.evaluatables.evaluators.UpdateMovementDirection< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.RandomWaypoint< A, B >.evaluate(), engine.elementFactories.LevelFactory.generateBackGroundGroup(), engine.elementFactories.LevelFactory.generateUnitsGroup(), application.Pong.hardCodeAGame(), engine.visuals.MiniMap.setUnitShape(), and engine.elementFactories.LevelFactory.updateGridForObstacles().
StateType model.state.gameelement.StateTags.myType private
Definition at line 48 of file StateTags.java.
String model.state.gameelement.StateTags.myValue private
Definition at line 49 of file StateTags.java.
model.state.gameelement.StateTags.NAME =(StateType.STRING, "name")
Definition at line 17 of file StateTags.java.
Referenced by model.GameElementStateFactory.addEssentials(), application.Pong.createGoalDisplayMarker(), model.state.gameelement.GameElementState.getName(), and application.RPG.hardCodeAGame().
model.state.gameelement.StateTags.RANDOM_MOVEMENT_FLAG =(StateType.NUMBER, "randomMovementFlag")
Definition at line 31 of file StateTags.java.
model.state.gameelement.StateTags.RELOAD_TIME =(StateType.NUMBER, "reloadTime")
Definition at line 39 of file StateTags.java.
Referenced by application.RPG.createMovingUnit(), application.RPG.createSpawnPoint(), and engine.gameRepresentation.evaluatables.evaluators.Attack< A, B >.evaluate().
model.state.gameelement.StateTags.RESOURCES =(StateType.NUMBER, "resources")
Definition at line 45 of file StateTags.java.
Referenced by application.RPG.createEnemyUnit(), application.Pong.createGoalRegion(), application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), engine.visuals.StatisticsBox.StatisticsBox(), and engine.UI.ParticipantManager.update().
model.state.gameelement.StateTags.SUPPORTS_RANGED_ATTACK =(StateType.NUMBER, "supportsRangedAttack")
Definition at line 43 of file StateTags.java.
model.state.gameelement.StateTags.TEAM_COLOR =(StateType.NUMBER, "teamColor")
Definition at line 22 of file StateTags.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.Animator(), engine.stateManaging.GameElementManager.checkOnTeam(), application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalDisplayMarker(), application.Pong.createGoalRegion(), application.Pong.createPaddle(), engine.elementFactories.GameElementFactory.createSelectableGameElement(), engine.gameRepresentation.evaluatables.evaluators.Attack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.SpawnSelectableElement< A, B >.evaluate(), engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.evaluate(), engine.stateManaging.GameElementManager.filterTeamIDElements(), engine.visuals.VisualManager.findFirstSelectedElement(), application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), engine.users.Participant.Participant(), engine.visuals.MiniMap.setUnitColor(), and engine.UI.ParticipantManager.update().
model.state.gameelement.StateTags.TIMER =(StateType.NUMBER, "gameTimer")
Definition at line 46 of file StateTags.java.
model.state.gameelement.StateTags.TYPE =(StateType.STRING, "type")
Definition at line 18 of file StateTags.java.
Referenced by engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getType().
model.state.gameelement.StateTags.X_GOAL_POSITION =(StateType.NUMBER, "xGoalPosition")
Definition at line 27 of file StateTags.java.
Referenced by application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setGoalPositions(), and engine.gameRepresentation.renderedRepresentation.GameElement.setPosition().
model.state.gameelement.StateTags.X_POSITION =(StateType.NUMBER, "xPosition")
Definition at line 23 of file StateTags.java.
Referenced by model.MainModel.addTerrainToLevel(), model.MainModel.addUnitToLevel(), application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), application.RPG.createSpawnPoint(), model.state.gameelement.DrawableGameElementState.DrawableGameElementState(), engine.gameRepresentation.evaluatables.evaluators.MovePlayer< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.UpdateMovementDirection< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Follow< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.FollowX< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.MoveBack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.SpawnSelectableElement< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.RandomWaypoint< A, B >.evaluate(), engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.evaluate(), model.state.gameelement.DrawableGameElementState.findGlobalBounds(), engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.getCenter(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNextWaypoint(), engine.visuals.elementVisuals.Visualizer.initializeDisplay(), engine.gameRepresentation.renderedRepresentation.GameElement.setPosition(), engine.stateManaging.GameElementManager.setSelectedUnitCommand(), model.MainModel.setTerrain(), and engine.visuals.elementVisuals.Visualizer.updateNodeLocation().
model.state.gameelement.StateTags.X_SPAWN_OFFSET =(StateType.NUMBER, "xSpawnOffset")
Definition at line 41 of file StateTags.java.
Referenced by application.Pong.createGoalRegion(), application.RPG.createSpawnPoint(), and engine.gameRepresentation.evaluatables.evaluators.SpawnSelectableElement< A, B >.evaluate().
model.state.gameelement.StateTags.X_TEMP_GOAL_POSITION =(StateType.NUMBER, "xTempGoalPosition")
Definition at line 29 of file StateTags.java.
Referenced by application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), engine.gameRepresentation.evaluatables.evaluators.UpdateMovementDirection< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.FollowX< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Follow< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.RandomWaypoint< A, B >.evaluate(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setGoalPositions(), and engine.gameRepresentation.renderedRepresentation.GameElement.setPosition().
model.state.gameelement.StateTags.X_VELOCITY =(StateType.NUMBER, "xVelocity")
Definition at line 25 of file StateTags.java.
Referenced by application.Pong.createBall(), engine.visuals.elementVisuals.animations.Animator.determineAnimationDirection(), engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), engine.gameRepresentation.evaluatables.evaluators.MovePlayer< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.MoveBack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.UpdateMovementDirection< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.evaluate(), and application.Pong.hardCodeAGame().
model.state.gameelement.StateTags.Y_GOAL_POSITION =(StateType.NUMBER, "yGoalPosition")
Definition at line 28 of file StateTags.java.
Referenced by application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setGoalPositions(), and engine.gameRepresentation.renderedRepresentation.GameElement.setPosition().
model.state.gameelement.StateTags.Y_POSITION =(StateType.NUMBER, "yPosition")
Definition at line 24 of file StateTags.java.
Referenced by model.MainModel.addTerrainToLevel(), model.MainModel.addUnitToLevel(), application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), application.RPG.createSpawnPoint(), model.state.gameelement.DrawableGameElementState.DrawableGameElementState(), engine.gameRepresentation.evaluatables.evaluators.MovePlayer< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Follow< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.MoveBack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.UpdateMovementDirection< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.SpawnSelectableElement< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.RandomWaypoint< A, B >.evaluate(), engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.evaluate(), model.state.gameelement.DrawableGameElementState.findGlobalBounds(), engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.getCenter(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNextWaypoint(), engine.visuals.elementVisuals.Visualizer.initializeDisplay(), engine.gameRepresentation.renderedRepresentation.GameElement.setPosition(), engine.stateManaging.GameElementManager.setSelectedUnitCommand(), model.MainModel.setTerrain(), and engine.visuals.elementVisuals.Visualizer.updateNodeLocation().
model.state.gameelement.StateTags.Y_SPAWN_OFFSET =(StateType.NUMBER, "ySpawnOffset")
Definition at line 42 of file StateTags.java.
Referenced by application.Pong.createGoalRegion(), application.RPG.createSpawnPoint(), and engine.gameRepresentation.evaluatables.evaluators.SpawnSelectableElement< A, B >.evaluate().
model.state.gameelement.StateTags.Y_TEMP_GOAL_POSITION =(StateType.NUMBER, "yTempGoalPosition")
Definition at line 30 of file StateTags.java.
Referenced by application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), engine.gameRepresentation.evaluatables.evaluators.UpdateMovementDirection< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Follow< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.RandomWaypoint< A, B >.evaluate(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setGoalPositions(), and engine.gameRepresentation.renderedRepresentation.GameElement.setPosition().
model.state.gameelement.StateTags.Y_VELOCITY =(StateType.NUMBER, "yVelocity")
Definition at line 26 of file StateTags.java.
Referenced by application.Pong.createBall(), engine.visuals.elementVisuals.animations.Animator.determineAnimationDirection(), engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), engine.gameRepresentation.evaluatables.evaluators.MovePlayer< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.MoveBack< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.UpdateMovementDirection< A, B >.evaluate(), engine.gameRepresentation.evaluatables.evaluators.Bounce< A, B >.evaluate(), and application.Pong.hardCodeAGame().
The documentation for this enum was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/gameelement/StateTags.java