voogasalad_TheException: game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement Class Reference
game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement Class Reference
Classes
enum DIRECTION
Public Member Functions
SelectableGameElement (DrawableGameElementState element, Map< String, List< Evaluatable<?>>> conditionActionPairs, ResourceBundle actionTypes, ResourceBundle interactingElementTypes)
String getType ()
void addInteractingElement (String elementType, DrawableGameElement element)
void addInteractingElements (String interactingElementType, List< DrawableGameElement > visibleElements)
void select (boolean select)
List< Line > getLines ()
void update ()
void updateSelfDueToSelection ()
boolean isSelected ()
void setHeading (Point2D click)
void clearHeadings ()
Public Member Functions inherited from game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement
DrawableGameElement (DrawableGameElementState state, Map< String, List< Evaluatable<?>>> actions, ResourceBundle actionTypes)
void update ()
void setAnimation (AnimationSequence animation)
AnimationSequence getAnimation ()
void setAnimation (String animationName)
Node getNode ()
VBox getDisplayVBox ()
double[] getBounds ()
Point2D getLocation ()
Public Member Functions inherited from game_engine.gameRepresentation.renderedRepresentation.GameElement
GameElement (GameElementState gameElementState, Map< String, List< Evaluatable<?>>> conditionActionPairs, ResourceBundle actionTypesBundle)
Iterator< Evaluatable<?> > getActionsOfType (String actionType)
void addAction (String actionType, Evaluatable<?> action)
void removeAction (String actionID)
void update ()
Number getNumericalAttribute (String attributeTag)
void setNumericalAttribute (String attributeTag, Number attributeValue)
String getTextualAttribute (String attributeTag)
void setTextualAttribute (String attributeTag, String attributeValue)
void setPosition (double x, double y)
Static Public Attributes
static final String X_VEL = "xVelocity"
static final String Y_VEL = "yVelocity"
Private Member Functions
void initializeInteractingElementLists ()
void updateSelfDueToCurrentObjective ()
void updateSelfDueToVisions ()
void updateSelfDueToCollisions ()
void updateSelfDueToInteractingElementsSubset (String elementType, String actionType)
void updateSelectedIndicator ()
DIRECTION getDirection (Point2D loc, Point2D destination)
void setAnimationDirection (Point2D loc, Point2D destination, boolean isMoving)
void move ()
Private Attributes
boolean isSelected
SelectableGameElementState selectableState
Map< String, Set< DrawableGameElement > > myInteractingElements
ResourceBundle myInteractingElementTypes
double speed = 3
DIRECTION myDirection = DIRECTION.FWD
Queue< Point2D > headings
Additional Inherited Members
Protected Member Functions inherited from game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement
void updateImageLocation ()
Protected Member Functions inherited from game_engine.gameRepresentation.renderedRepresentation.GameElement
void executeAllActions (String actionKey, ElementPair elementPair)
void executeAllActions (String actionKey)
Protected Attributes inherited from game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement
AnimationPlayer myAnimation
Group myDisplay
VBox myDisplayVBox
Protected Attributes inherited from game_engine.gameRepresentation.renderedRepresentation.GameElement
ResourceBundle actionTypes
Static Package Attributes inherited from game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement
static final String SELECT_ARROW_URL = "resources/img/Red_Arrow_Down.png"
Detailed Description
A wrapper for game elements capable of being selected. Adds a "selected" visual appearance to the appearance defined by the DrawableGameElement and handles animations for actions resulting from being selected.
Author
Jonathan , Steve, Nishad, Rahul, John, Michael D., Zach
Definition at line 35 of file SelectableGameElement.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.SelectableGameElement (DrawableGameElementState element, Map< String, List< Evaluatable<?>>> conditionActionPairs, ResourceBundle actionTypes, ResourceBundle interactingElementTypes)
Parameters
interactingElementTypes2
actionTypes
See also
DrawableGameElementState
Definition at line 61 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.initializeInteractingElementLists(), and game_engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute().
Member Function Documentation
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElement (String elementType, DrawableGameElement element)
Add an element that the game element is currently interacting with
Parameters
elementType the type of element i.e. visible, colliding, etc
element the element to be added
Definition at line 102 of file SelectableGameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElements().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElements (String interactingElementType, List< DrawableGameElement > visibleElements)
Add elements interacting with the game element to be evaluated when the element updates
Parameters
visibleElements the elements that are currently visible by the object
Definition at line 117 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElement().
Referenced by game_engine.computers.boundsComputers.VisionComputer.givePrimaryObjectElements().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.clearHeadings ()
Definition at line 312 of file SelectableGameElement.java.
DIRECTION game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getDirection (Point2D loc, Point2D destination) private
Definition at line 219 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.DIRECTION.BK, game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.DIRECTION.BK_LEFT, game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.DIRECTION.BK_RIGHT, game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.DIRECTION.FWD, game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.DIRECTION.FWD_LEFT, game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.DIRECTION.FWD_RIGHT, game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.DIRECTION.LEFT, and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.DIRECTION.RIGHT.
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.setAnimationDirection().
List<Line> game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getLines ()
Definition at line 136 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLocation(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.isSelected().
String game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getType ()
Definition at line 92 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.getTextualAttribute(), and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.TYPE_STRING.
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.initializeInteractingElementLists () private
Ensure that lists are instantiated for all the possible action types of an element to protect against uninstantiated action entities at runtime.
Definition at line 81 of file SelectableGameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.SelectableGameElement().
boolean game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.isSelected ()
Definition at line 304 of file SelectableGameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getLines().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move () private
Definition at line 261 of file SelectableGameElement.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.CAN_MOVE_STRING, game_engine.visuals.ScrollablePane.FIELD_HEIGHT, game_engine.visuals.ScrollablePane.FIELD_WIDTH, game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLocation(), game_engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.RANDOM_MOVEMENT_STRING, game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.setAnimationDirection(), game_engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute(), game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.speed, game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.updateImageLocation(), game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.X_POS_STRING, and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.Y_POS_STRING.
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.select (boolean select)
Select the element
Parameters
select a boolean indicating whether the object should be selected
Definition at line 130 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelectedIndicator().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.setAnimationDirection (Point2D loc, Point2D destination, boolean isMoving) private
Definition at line 249 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.getDirection(), and game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setAnimation().
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.setHeading (Point2D click)
Definition at line 308 of file SelectableGameElement.java.
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update ()
Update the object due to internal influences then update the object due to collisions, visible objects, and the current objective of the object
Definition at line 169 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move(), game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCollisions(), game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCurrentObjective(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToVisions().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelectedIndicator () private
Definition at line 208 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.DrawableGameElement.myDisplayVBox.
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.select().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCollisions () private
Definition at line 189 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToInteractingElementsSubset().
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCurrentObjective () private
Definition at line 177 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.actionTypes, and game_engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions().
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToInteractingElementsSubset (String elementType, String actionType) private
Definition at line 194 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.getActionsOfType().
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToCollisions(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToVisions().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToSelection ()
Definition at line 181 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.actionTypes, and game_engine.gameRepresentation.renderedRepresentation.GameElement.executeAllActions().
void game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToVisions () private
Definition at line 185 of file SelectableGameElement.java.
References game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.updateSelfDueToInteractingElementsSubset().
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.update().
Member Data Documentation
Queue<Point2D> game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.headings private
Definition at line 54 of file SelectableGameElement.java.
boolean game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.isSelected private
Definition at line 37 of file SelectableGameElement.java.
DIRECTION game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.myDirection = DIRECTION.FWD private
Definition at line 45 of file SelectableGameElement.java.
Map<String, Set<DrawableGameElement> > game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.myInteractingElements private
Definition at line 39 of file SelectableGameElement.java.
ResourceBundle game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.myInteractingElementTypes private
Definition at line 40 of file SelectableGameElement.java.
SelectableGameElementState game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.selectableState private
Definition at line 38 of file SelectableGameElement.java.
double game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.speed = 3 private
Definition at line 43 of file SelectableGameElement.java.
Referenced by game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move().
final String game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.X_VEL = "xVelocity" static
Definition at line 51 of file SelectableGameElement.java.
Referenced by game_engine.stateManaging.GameLoop.addColisionEvents().
final String game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.Y_VEL = "yVelocity" static
Definition at line 52 of file SelectableGameElement.java.
Referenced by game_engine.stateManaging.GameLoop.addColisionEvents().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/renderedRepresentation/SelectableGameElement.java