voogasalad_TheException: game_engine.gameRepresentation.stateRepresentation.LevelState Class Reference
game_engine.gameRepresentation.stateRepresentation.LevelState Class Reference
Public Member Functions
LevelState (String name)
List< DrawableGameElementState > getTerrain ()
void addTerrain (DrawableGameElementState terrain)
List< SelectableGameElementState > getUnits ()
void addUnit (SelectableGameElementState unit)
List< GameElementState > getGoals ()
void addGoal (GameElementState goal)
String getTextualAttribute (String name)
Number getNumericalAttribute (String name)
void setTextualAttribute (String name, String value)
void setNumericalAttribute (String name, Number value)
Public Member Functions inherited from game_engine.gameRepresentation.stateRepresentation.DescribableState
void updateName (String name)
void updateDescription (String description)
String getName ()
String getDescription ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from util.JSONable
default String toJSON ()
Package Functions
private< T > T getAttribute (Collection< Attribute< T >> collection, String attributeName, T defaultReturnObject)
private< T > void addAttribute (Collection< Attribute< T >> collection, String attributeName, T attributeValue)
Private Attributes
Set< Attribute< Number > > myNumericalAttributes
Set< Attribute< String > > myTextualAttributes
List< DrawableGameElementState > myTerrains
List< SelectableGameElementState > myUnits
List< GameElementState > myGoals
Additional Inherited Members
Protected Member Functions inherited from game_engine.gameRepresentation.stateRepresentation.DescribableState
DescribableState (String name)
Detailed Description
The Level class is the direct point of interaction for most gameplay and editing - this class holds all of the GameElements being used for the current editing and/or game running session. Essentially a data wrapper class for all objects and states contained in a level.
Author
Steve, Jonathan, Nishad, Rahul
Definition at line 23 of file LevelState.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.stateRepresentation.LevelState.LevelState (String name)
Definition at line 31 of file LevelState.java.
Member Function Documentation
private<T> void game_engine.gameRepresentation.stateRepresentation.LevelState.addAttribute (Collection< Attribute< T >> collection, String attributeName, T attributeValue) package
Add an attribute with the given values to a given collection. Used to make switching between internal collection implementations easy
Parameters
collection
attributeName
attributeValue
Definition at line 111 of file LevelState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.LevelState.setNumericalAttribute(), and game_engine.gameRepresentation.stateRepresentation.LevelState.setTextualAttribute().
void game_engine.gameRepresentation.stateRepresentation.LevelState.addGoal (GameElementState goal)
Definition at line 60 of file LevelState.java.
Referenced by gamemodel.MainModel.addGoal().
void game_engine.gameRepresentation.stateRepresentation.LevelState.addTerrain (DrawableGameElementState terrain)
Definition at line 44 of file LevelState.java.
Referenced by application.ShittyMain.hardCodeAGame().
void game_engine.gameRepresentation.stateRepresentation.LevelState.addUnit (SelectableGameElementState unit)
Definition at line 52 of file LevelState.java.
Referenced by application.ShittyMain.hardCodeAGame().
private<T> T game_engine.gameRepresentation.stateRepresentation.LevelState.getAttribute (Collection< Attribute< T >> collection, String attributeName, T defaultReturnObject) package
Get an attribute from an internal collection
Parameters
collection the collection to extract the element from
attributeName the name of the attribute to extract
defaultReturnObject the value that should be returned if no attribute of the specified type was found
Returns
the attribute's value or the default return object if the attribute was not found
Definition at line 79 of file LevelState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.LevelState.getNumericalAttribute(), and game_engine.gameRepresentation.stateRepresentation.LevelState.getTextualAttribute().
List<GameElementState> game_engine.gameRepresentation.stateRepresentation.LevelState.getGoals ()
Definition at line 56 of file LevelState.java.
References game_engine.gameRepresentation.stateRepresentation.LevelState.myGoals.
Referenced by game_engine.elementFactories.LevelFactory.createLevel(), and editor.TabViewController.updateLevelTriggersView().
Number game_engine.gameRepresentation.stateRepresentation.LevelState.getNumericalAttribute (String name)
Get a numerical attribute with the given name
Definition at line 99 of file LevelState.java.
References game_engine.gameRepresentation.stateRepresentation.LevelState.getAttribute().
Referenced by game_engine.elementFactories.LevelFactory.createLevel().
List<DrawableGameElementState> game_engine.gameRepresentation.stateRepresentation.LevelState.getTerrain ()
Definition at line 40 of file LevelState.java.
References game_engine.gameRepresentation.stateRepresentation.LevelState.myTerrains.
Referenced by game_engine.elementFactories.LevelFactory.createLevel().
String game_engine.gameRepresentation.stateRepresentation.LevelState.getTextualAttribute (String name)
Get a textual attribute with the given name
Definition at line 92 of file LevelState.java.
References game_engine.gameRepresentation.stateRepresentation.LevelState.getAttribute().
List<SelectableGameElementState> game_engine.gameRepresentation.stateRepresentation.LevelState.getUnits ()
Definition at line 48 of file LevelState.java.
References game_engine.gameRepresentation.stateRepresentation.LevelState.myUnits.
Referenced by game_engine.elementFactories.LevelFactory.createLevel().
void game_engine.gameRepresentation.stateRepresentation.LevelState.setNumericalAttribute (String name, Number value)
Set a numerical attribute with the given name to the given value
Definition at line 134 of file LevelState.java.
References game_engine.gameRepresentation.stateRepresentation.LevelState.addAttribute().
void game_engine.gameRepresentation.stateRepresentation.LevelState.setTextualAttribute (String name, String value)
Add an attribute Set a textual attribute with the given name to the given value
Definition at line 127 of file LevelState.java.
References game_engine.gameRepresentation.stateRepresentation.LevelState.addAttribute().
Member Data Documentation
List<GameElementState> game_engine.gameRepresentation.stateRepresentation.LevelState.myGoals private
Definition at line 29 of file LevelState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.LevelState.getGoals().
Set<Attribute<Number> > game_engine.gameRepresentation.stateRepresentation.LevelState.myNumericalAttributes private
Definition at line 25 of file LevelState.java.
List<DrawableGameElementState> game_engine.gameRepresentation.stateRepresentation.LevelState.myTerrains private
Definition at line 27 of file LevelState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.LevelState.getTerrain().
Set<Attribute<String> > game_engine.gameRepresentation.stateRepresentation.LevelState.myTextualAttributes private
Definition at line 26 of file LevelState.java.
List<SelectableGameElementState> game_engine.gameRepresentation.stateRepresentation.LevelState.myUnits private
Definition at line 28 of file LevelState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.LevelState.getUnits().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/stateRepresentation/LevelState.java