voogasalad_TheException: view.editor.ElementDropDownController Class Reference
view.editor.ElementDropDownController Class Reference
Classes
class GameElementListCell
Public Member Functions
void setOnSelectionChanged (Consumer< String > selectionChangedConsumer)
void setEditConsumer (Consumer< String > editConsumer)
void addElement (String element, Node image)
void setButtonAction (Consumer< String > consumer)
void setDeleteConsumer (Consumer< String > deleteConsumer)
void bindGameElement (ObjectProperty< String > elementName)
void clearItems ()
Node getRoot ()
void initialize ()
Private Member Functions
void initListView ()
void initDeleteElementButton ()
Private Attributes
Button newElementButton
Button deleteElementButton
ListView< String > elementListView
TitledPane elementDropDown
VBox vboxRoot
HashMap< String, Node > myElementsMap
Consumer< String > myDeletionConsumer
Consumer< String > mySelectionChangedConsumer
Consumer< String > myEditConsumer
Static Private Attributes
static final String DELETE_SELECTED_KEY = "DeleteSelected"
static final String CREATE_NEW_KEY = "CreateNew"
Detailed Description
Author
Nishad Agrawal
Jonathan Tseng
Definition at line 27 of file ElementDropDownController.java.
Member Function Documentation
void view.editor.ElementDropDownController.addElement (String element, Node image)
Definition at line 59 of file ElementDropDownController.java.
Referenced by view.editor.ElementAccordionController.updateList().
void view.editor.ElementDropDownController.bindGameElement (ObjectProperty< String > elementName)
Definition at line 74 of file ElementDropDownController.java.
Referenced by view.editor.ElementAccordionController.attachStringProperties().
void view.editor.ElementDropDownController.clearItems ()
Definition at line 104 of file ElementDropDownController.java.
Referenced by view.editor.ElementAccordionController.updateList().
Node view.editor.ElementDropDownController.getRoot ()
Implements view.gui.GUIController.
Definition at line 120 of file ElementDropDownController.java.
References view.editor.ElementDropDownController.elementDropDown.
void view.editor.ElementDropDownController.initDeleteElementButton () private
Definition at line 90 of file ElementDropDownController.java.
Referenced by view.editor.ElementDropDownController.initialize().
void view.editor.ElementDropDownController.initialize ()
Implements view.gui.GUIController.
Definition at line 125 of file ElementDropDownController.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), view.editor.ElementDropDownController.initDeleteElementButton(), and view.editor.ElementDropDownController.initListView().
void view.editor.ElementDropDownController.initListView () private
Definition at line 78 of file ElementDropDownController.java.
Referenced by view.editor.ElementDropDownController.initialize().
void view.editor.ElementDropDownController.setButtonAction (Consumer< String > consumer)
Definition at line 66 of file ElementDropDownController.java.
Referenced by view.editor.ElementAccordionController.init().
void view.editor.ElementDropDownController.setDeleteConsumer (Consumer< String > deleteConsumer)
Definition at line 70 of file ElementDropDownController.java.
Referenced by view.editor.ElementAccordionController.init().
void view.editor.ElementDropDownController.setEditConsumer (Consumer< String > editConsumer)
Definition at line 55 of file ElementDropDownController.java.
Referenced by view.editor.ElementAccordionController.init().
void view.editor.ElementDropDownController.setOnSelectionChanged (Consumer< String > selectionChangedConsumer)
Definition at line 51 of file ElementDropDownController.java.
Referenced by view.editor.ElementAccordionController.init().
Member Data Documentation
final String view.editor.ElementDropDownController.CREATE_NEW_KEY = "CreateNew" static private
Definition at line 30 of file ElementDropDownController.java.
final String view.editor.ElementDropDownController.DELETE_SELECTED_KEY = "DeleteSelected" static private
Definition at line 29 of file ElementDropDownController.java.
Button view.editor.ElementDropDownController.deleteElementButton private
Definition at line 35 of file ElementDropDownController.java.
TitledPane view.editor.ElementDropDownController.elementDropDown private
Definition at line 39 of file ElementDropDownController.java.
Referenced by view.editor.ElementDropDownController.getRoot().
ListView<String> view.editor.ElementDropDownController.elementListView private
Definition at line 37 of file ElementDropDownController.java.
Consumer<String> view.editor.ElementDropDownController.myDeletionConsumer private
Initial value:
= (String element) -> {
    }
Definition at line 44 of file ElementDropDownController.java.
Consumer<String> view.editor.ElementDropDownController.myEditConsumer private
Initial value:
= (String element) -> {
    }
Definition at line 48 of file ElementDropDownController.java.
HashMap<String, Node> view.editor.ElementDropDownController.myElementsMap private
Definition at line 43 of file ElementDropDownController.java.
Consumer<String> view.editor.ElementDropDownController.mySelectionChangedConsumer private
Initial value:
= (String element) -> {
    }
Definition at line 46 of file ElementDropDownController.java.
Button view.editor.ElementDropDownController.newElementButton private
Definition at line 33 of file ElementDropDownController.java.
VBox view.editor.ElementDropDownController.vboxRoot private
Definition at line 41 of file ElementDropDownController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/ElementDropDownController.java