voogasalad_TheException: model.data.WizardDataFactory Class Reference
model.data.WizardDataFactory Class Reference
Static Public Member Functions
static WizardData createWizardData (DrawableGameElementState state)
Static Private Member Functions
static String getAction (String actionClassName)
static String removeEnds (String input)
Detailed Description
This represents the complement to the GameElementStateFactory and it allows for conversion from GameElementState to WizardData, this is useful for launching for editing.
Author
Nishad Agrawal
Definition at line 22 of file WizardDataFactory.java.
Member Function Documentation
static WizardData model.data.WizardDataFactory.createWizardData (DrawableGameElementState state) static
Definition at line 24 of file WizardDataFactory.java.
References model.data.WizardDataType.ACTION, model.data.WizardDataType.ACTION_PARAMETERS, model.data.WizardDataType.ACTIONTYPE, model.data.WizardData.addDataPair(), model.data.WizardData.addWizardData(), model.data.WizardType.ANIMATION_SEQUENCE, model.data.WizardDataType.ATTRIBUTE, model.data.WizardDataType.COLOR_MASK, model.data.WizardDataType.FRAME_X, model.data.WizardDataType.FRAME_Y, model.data.WizardType.GAME_ELEMENT, model.data.WizardDataFactory.getAction(), model.state.gameelement.GameElementState.getActions(), engine.visuals.elementVisuals.animations.AnimatorState.getAllAnimationSequences(), engine.visuals.elementVisuals.animations.AnimatorState.getColorMaskTag(), model.state.gameelement.DrawableGameElementState.getDisplayerStates(), engine.visuals.Dimension.getHeight(), engine.visuals.elementVisuals.animations.AnimatorState.getImageTag(), model.state.gameelement.GameElementState.getName(), model.state.gameelement.AttributeContainer.getNumericalAttributes(), model.state.gameelement.AttributeContainer.getTextualAttributes(), model.state.gameelement.GameElementState.getTypes(), engine.visuals.elementVisuals.animations.AnimatorState.getViewportSize(), engine.visuals.Dimension.getWidth(), model.data.WizardDataType.IMAGE, model.state.gameelement.DrawableGameElementState.myAnimatorState, model.state.gameelement.GameElementState.myAttributes, model.data.WizardDataType.NAME, model.data.WizardType.NUMBER_ATTRIBUTE, model.data.WizardDataFactory.removeEnds(), model.data.WizardData.setType(), model.data.WizardType.STRING_ATTRIBUTE, model.data.WizardType.TRIGGER, model.data.WizardDataType.TYPE, model.data.WizardDataType.VALUE, model.data.WizardType.WIDGET, and model.data.WizardDataType.WIDGET_TYPE.
Referenced by view.editor.ElementAccordionController.createWizardData().
static String model.data.WizardDataFactory.getAction (String actionClassName) static private
Definition at line 83 of file WizardDataFactory.java.
Referenced by model.data.WizardDataFactory.createWizardData().
static String model.data.WizardDataFactory.removeEnds (String input) static private
Definition at line 89 of file WizardDataFactory.java.
Referenced by model.data.WizardDataFactory.createWizardData().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/data/WizardDataFactory.java