voogasalad_TheException: game_engine.gameRepresentation.stateRepresentation.CampaignState Class Reference
game_engine.gameRepresentation.stateRepresentation.CampaignState Class Reference
Public Member Functions
CampaignState (String name)
LevelState getLevel (String levelName) throws LevelNotFoundException
List< LevelState > getLevels ()
void addLevel (LevelState levelToAdd) throws LevelExistsException
void removeLevel (String levelName)
Public Member Functions inherited from game_engine.gameRepresentation.stateRepresentation.DescribableState
void updateName (String name)
void updateDescription (String description)
String getName ()
String getDescription ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from util.JSONable
default String toJSON ()
Private Attributes
List< LevelState > myLevels
Additional Inherited Members
Protected Member Functions inherited from game_engine.gameRepresentation.stateRepresentation.DescribableState
DescribableState (String name)
Detailed Description
This class is a collection of Levels used to string together gameplay in order to make a cohesive user experience.
Author
Steve, Jonathan, Nishad, Rahul
Definition at line 18 of file CampaignState.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.stateRepresentation.CampaignState.CampaignState (String name)
Definition at line 22 of file CampaignState.java.
Member Function Documentation
void game_engine.gameRepresentation.stateRepresentation.CampaignState.addLevel (LevelState levelToAdd) throws LevelExistsException
adds a level to the campaign
Parameters
levelToAdd
Exceptions
LevelExistsException
Definition at line 61 of file CampaignState.java.
Referenced by gamemodel.MainModel.createLevel().
LevelState game_engine.gameRepresentation.stateRepresentation.CampaignState.getLevel (String levelName) throws LevelNotFoundException
gets the level with associated levelName
Parameters
levelName
Returns
the state of the level of interest
Exceptions
LevelNotFoundException
Definition at line 34 of file CampaignState.java.
Referenced by gamemodel.MainModel.getDescribableState(), and gamemodel.MainModel.setCurrentLevel().
List<LevelState> game_engine.gameRepresentation.stateRepresentation.CampaignState.getLevels ()
gets unmodifiable list of all of the levels
Returns
Definition at line 51 of file CampaignState.java.
void game_engine.gameRepresentation.stateRepresentation.CampaignState.removeLevel (String levelName)
removes a level with a given name
Parameters
levelName
Definition at line 77 of file CampaignState.java.
Member Data Documentation
List<LevelState> game_engine.gameRepresentation.stateRepresentation.CampaignState.myLevels private
Definition at line 20 of file CampaignState.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/stateRepresentation/CampaignState.java