voogasalad_TheException: view.runner.GameEndController Class Reference
view.runner.GameEndController Class Reference
Public Member Functions
void updateGameEndView (String titleString, List< String > attributes)
void setOnDone (EventHandler< ActionEvent > event)
Node getRoot ()
void initialize ()
Private Attributes
BorderPane root
Label title
VBox attributeList
Button doneButton
Static Private Attributes
static final String DONE_KEY = "Done"
Detailed Description
Controller for showing the game ending
Author
Jonathan Tseng
Definition at line 26 of file GameEndController.java.
Member Function Documentation
Node view.runner.GameEndController.getRoot ()
Implements view.gui.GUIController.
Definition at line 55 of file GameEndController.java.
References view.runner.GameEndController.root.
void view.runner.GameEndController.initialize ()
Implements view.gui.GUIController.
Definition at line 60 of file GameEndController.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
void view.runner.GameEndController.setOnDone (EventHandler< ActionEvent > event)
Definition at line 50 of file GameEndController.java.
Referenced by view.runner.GameRunnerPaneController.setOnDone().
void view.runner.GameEndController.updateGameEndView (String titleString, List< String > attributes)
Definition at line 39 of file GameEndController.java.
Referenced by view.runner.GameRunnerPaneController.engineUpdate().
Member Data Documentation
VBox view.runner.GameEndController.attributeList private
Definition at line 35 of file GameEndController.java.
final String view.runner.GameEndController.DONE_KEY = "Done" static private
Definition at line 28 of file GameEndController.java.
Button view.runner.GameEndController.doneButton private
Definition at line 37 of file GameEndController.java.
BorderPane view.runner.GameEndController.root private
Definition at line 31 of file GameEndController.java.
Referenced by view.runner.GameEndController.getRoot().
Label view.runner.GameEndController.title private
Definition at line 33 of file GameEndController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/runner/GameEndController.java