voogasalad_TheException: util.ResourceBundleRetriever Class Reference
util.ResourceBundleRetriever Class Reference
Public Member Functions
ResourceBundle getBundle (File file) throws SaveLoadException
Protected Member Functions
String removeFileExtension (String fileName)
Detailed Description
Utility class to load a resource bundle from a file with a .properties extension. Reference: http://stackoverflow.com/questions /1172424/how-to-load-a-resource-bundle-from-a-file-resource-in-java
Author
Rahul
Definition at line 21 of file ResourceBundleRetriever.java.
Member Function Documentation
ResourceBundle util.ResourceBundleRetriever.getBundle (File file) throws SaveLoadException
Parameters
file name with .properties extension
Returns
resource bundle associated with the provided file
Exceptions
MalformedURLException
Definition at line 29 of file ResourceBundleRetriever.java.
References util.ResourceBundleRetriever.removeFileExtension().
Referenced by model.sprite.SpriteImageGenerator.SpriteImageGenerator().
String util.ResourceBundleRetriever.removeFileExtension (String fileName) protected
Helper method to remove file extension (.properties, in this case, but general enough for any other extension type)
Parameters
file
Returns
file name without extensions (which may be the file name passed in when no extension exists)
Definition at line 51 of file ResourceBundleRetriever.java.
Referenced by util.ResourceBundleRetriever.getBundle().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/util/ResourceBundleRetriever.java