voogasalad_TheException: engine.visuals.elementVisuals.animations.AnimationSequence Class Reference
engine.visuals.elementVisuals.animations.AnimationSequence Class Reference
Public Member Functions
AnimationSequence (List< AnimationTag > name, int startFrame, int stopFrame, boolean repeats, double slownessMultiplier)
AnimationSequence (List< AnimationTag > name, int startFrame, int stopFrame)
void reset ()
boolean update ()
int getFrame ()
List< AnimationTag > getTags ()
boolean equals (Object arg)
int hashCode ()
String toString ()
Private Attributes
int myStartFrame
int myStopFrame
int myCurrentFrame
boolean myRepeatFlag
List< AnimationTag > myTags
double mySlownessMultiplier
int myFrameCounter
Static Private Attributes
static final long serialVersionUID = -9193394127044465741L
Detailed Description
A basic animation. Keeps track of progress, the frame bounds, and the animation that will be played after it
Author
Zachary Bears, Rahul Harikrishnan, Steve
Definition at line 15 of file AnimationSequence.java.
Constructor & Destructor Documentation
engine.visuals.elementVisuals.animations.AnimationSequence.AnimationSequence (List< AnimationTag > name, int startFrame, int stopFrame, boolean repeats, double slownessMultiplier)
Initialize the animation and insert a multiplier for slowness
Parameters
slownessMultiplier a multiplier for the speed of the animation. Must be less than 1.
startFrame the startframe of the animation. This is the index at which the animation begins.
stopFrame the stopFrame of the animation. This is the index at which the animation ends.
repeats a boolean which controls whether or not the animation sequence repeats itself.
name the name of the particular list of sprites the animation traverses through.
Definition at line 51 of file AnimationSequence.java.
engine.visuals.elementVisuals.animations.AnimationSequence.AnimationSequence (List< AnimationTag > name, int startFrame, int stopFrame)
Definition at line 66 of file AnimationSequence.java.
Member Function Documentation
boolean engine.visuals.elementVisuals.animations.AnimationSequence.equals (Object arg)
Definition at line 118 of file AnimationSequence.java.
References engine.visuals.elementVisuals.animations.AnimationSequence.hashCode().
Referenced by engine.visuals.elementVisuals.animations.Animator.determineCorrectAnimation().
int engine.visuals.elementVisuals.animations.AnimationSequence.getFrame ()
Get the current frame of the animation
Returns
Definition at line 109 of file AnimationSequence.java.
References engine.visuals.elementVisuals.animations.AnimationSequence.myCurrentFrame.
Referenced by engine.visuals.elementVisuals.animations.Animator.update().
List<AnimationTag> engine.visuals.elementVisuals.animations.AnimationSequence.getTags ()
Definition at line 113 of file AnimationSequence.java.
References engine.visuals.elementVisuals.animations.AnimationSequence.myTags.
int engine.visuals.elementVisuals.animations.AnimationSequence.hashCode ()
Definition at line 124 of file AnimationSequence.java.
Referenced by engine.visuals.elementVisuals.animations.AnimationSequence.equals().
void engine.visuals.elementVisuals.animations.AnimationSequence.reset ()
Reset the animation to the start frame
Definition at line 78 of file AnimationSequence.java.
References engine.visuals.elementVisuals.animations.AnimationSequence.myStartFrame.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineCorrectAnimation(), and engine.visuals.elementVisuals.animations.AnimationSequence.update().
String engine.visuals.elementVisuals.animations.AnimationSequence.toString ()
Definition at line 129 of file AnimationSequence.java.
References engine.visuals.elementVisuals.animations.AnimationSequence.myCurrentFrame.
boolean engine.visuals.elementVisuals.animations.AnimationSequence.update ()
Increments the animation frame. Return true if the animation is complete.
Implements model.state.gameelement.traits.Updatable.
Definition at line 86 of file AnimationSequence.java.
References engine.visuals.elementVisuals.animations.AnimationSequence.reset().
Referenced by engine.visuals.elementVisuals.animations.Animator.update().
Member Data Documentation
int engine.visuals.elementVisuals.animations.AnimationSequence.myCurrentFrame private
Definition at line 24 of file AnimationSequence.java.
Referenced by engine.visuals.elementVisuals.animations.AnimationSequence.getFrame(), and engine.visuals.elementVisuals.animations.AnimationSequence.toString().
int engine.visuals.elementVisuals.animations.AnimationSequence.myFrameCounter private
Definition at line 29 of file AnimationSequence.java.
boolean engine.visuals.elementVisuals.animations.AnimationSequence.myRepeatFlag private
Definition at line 25 of file AnimationSequence.java.
double engine.visuals.elementVisuals.animations.AnimationSequence.mySlownessMultiplier private
Definition at line 28 of file AnimationSequence.java.
int engine.visuals.elementVisuals.animations.AnimationSequence.myStartFrame private
Definition at line 22 of file AnimationSequence.java.
Referenced by engine.visuals.elementVisuals.animations.AnimationSequence.reset().
int engine.visuals.elementVisuals.animations.AnimationSequence.myStopFrame private
Definition at line 23 of file AnimationSequence.java.
List<AnimationTag> engine.visuals.elementVisuals.animations.AnimationSequence.myTags private
Definition at line 26 of file AnimationSequence.java.
Referenced by engine.visuals.elementVisuals.animations.AnimationSequence.getTags().
final long engine.visuals.elementVisuals.animations.AnimationSequence.serialVersionUID = -9193394127044465741L static private
Definition at line 20 of file AnimationSequence.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/elementVisuals/animations/AnimationSequence.java