voogasalad_TheException: view.editor.wizards.GameElementWizard Class Reference
view.editor.wizards.GameElementWizard Class Reference
Public Member Functions
void initialize ()
boolean checkCanSave ()
void updateData ()
void attachStringAttributes (List< String > stringAttributes)
void attachNumberAttributes (List< String > numberAttributes)
void launchForEdit (WizardData oldValues)
void loadGlobalValues (List< String > values)
Public Member Functions inherited from view.editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
abstract void launchForEdit (WizardData oldValues)
abstract void loadGlobalValues (List< String > values)
WizardData getWizardData ()
void displayErrorMessage (String error)
void removeWizardData (WizardData data)
void setStage (Stage s)
void closeStage ()
Protected Member Functions
void attachTextProperties ()
Protected Member Functions inherited from view.editor.wizards.Wizard
void addToData (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void setWizardType (WizardType type)
void attachTextProperties ()
boolean isNumber (String value)
Private Member Functions
void launchBoundsWizard (WizardType boundsType)
boolean boundsAlreadyExist (WizardType boundsType)
WizardData getBoundsFromWizardData (WizardType boundsType)
File fetchImage () throws FileNotFoundException
void loadColorMask ()
void loadImage ()
void renderImage (File imageFile) throws FileNotFoundException
Image addImageToView (File imageFile) throws FileNotFoundException
void initializeSliders (Image image)
void initContainers ()
BiConsumer< Button, WizardData > getActionConsumer ()
BiConsumer< Button, WizardData > getAttributeConsumer ()
BiConsumer< Button, WizardData > getWidgetConsumer ()
BiConsumer< Button, WizardData > getAnimationConsumer ()
BooleanSupplier isAnimationLaunchValid ()
void createTextFieldListeners ()
void setTextListener (TextField field, Consumer< Double > cons)
void createSliderListeners ()
void setValueListener (Slider slider, Consumer< String > cons, Consumer< Double > gridCons)
void storeContainerData (CRUDContainer container)
void addContainerData (CRUDContainer container, WizardData oldValues, WizardType type)
Private Attributes
final int DEFAULT_GRID_MIN = 10
final int DEFAULT_GRID_VALUE = 100
ScrollPane leftPane
TextField name
TextField type
Button image
Button colorMask
Group spritesheet
ScrollPane imageScroll
Label frameHeightLabel
Slider frameWidth
TextField frameWidthText
Label frameWidthLabel
Slider frameHeight
TextField frameHeightText
Button setBounds
Button setVisionBounds
CRUDContainer stringAttributesController
CRUDContainer numberAttributesController
CRUDContainer triggersController
CRUDContainer widgetsController
CRUDContainer animationsController
List< String > imageValues
List< String > myGlobalStringAttributes
List< String > myGlobalNumberAttributes
ImageView imageView
AnimationGrid animationGrid
String imagePath
String colorMaskPath
Static Private Attributes
static final String UNABLE_TO_LAUNCH_ANIM
static final String UNABLE_TO_LOAD = "Unable to Load Image"
static final String NAME_KEY = "Name"
static final String TYPE_KEY = "Type"
static final String NEW_ACTION_KEY = "NewAction"
static final String NEW_STRING_ATTRIBUTE_KEY = "NewStringAttribute"
static final String NEW_NUMBER_ATTRIBUTE_KEY = "NewNumberAttribute"
static final String NEW_WIDGET_KEY = "NewWidget"
static final String ADD_ANIMATION_KEY = "AddAnimation"
static final String SET_BOUNDS_KEY = "SetBounds"
static final String SET_VISION_BOUNDS_KEY = "SetVisionBounds"
static final String LOAD_IMAGE_KEY = "LoadImage"
static final String FRAME_HEIGHT_KEY = "FrameHeight"
static final String FRAME_WIDTH_KEY = "FrameWidth"
static final String COLOR_MASK_KEY = "ColorMask"
static final Dimension BOUNDS_WIZARD_SIZE = new Dimension(500, 700)
static final Dimension ACTION_WIZARD_SIZE = new Dimension(400, 600)
static final Dimension ANIMATION_WIZARD_SIZE = new Dimension(800, 800)
Additional Inherited Members
Static Public Attributes inherited from view.editor.wizards.Wizard
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
Protected Attributes inherited from view.editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Detailed Description
Author
Joshua, Nishad
Definition at line 38 of file GameElementWizard.java.
Member Function Documentation
void view.editor.wizards.GameElementWizard.addContainerData (CRUDContainer container, WizardData oldValues, WizardType type) private
Definition at line 384 of file GameElementWizard.java.
References view.editor.wizards.CRUDContainer.addAndRenderWizardDatas(), and model.data.WizardData.getWizardDataByType().
Referenced by view.editor.wizards.GameElementWizard.launchForEdit().
Image view.editor.wizards.GameElementWizard.addImageToView (File imageFile) throws FileNotFoundException private
Definition at line 281 of file GameElementWizard.java.
References view.editor.wizards.GameElementWizard.image.
Referenced by view.editor.wizards.GameElementWizard.launchForEdit(), view.editor.wizards.GameElementWizard.loadColorMask(), and view.editor.wizards.GameElementWizard.renderImage().
void view.editor.wizards.GameElementWizard.attachNumberAttributes (List< String > numberAttributes)
Definition at line 178 of file GameElementWizard.java.
Referenced by view.editor.ElementAccordionController.addNumberAttributes().
void view.editor.wizards.GameElementWizard.attachStringAttributes (List< String > stringAttributes)
Definition at line 174 of file GameElementWizard.java.
Referenced by view.editor.ElementAccordionController.addStringAttributes().
void view.editor.wizards.GameElementWizard.attachTextProperties () protected
Definition at line 126 of file GameElementWizard.java.
References view.editor.wizards.CRUDContainer.bindButtonText(), view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
boolean view.editor.wizards.GameElementWizard.boundsAlreadyExist (WizardType boundsType) private
Definition at line 223 of file GameElementWizard.java.
References view.editor.wizards.Wizard.getWizardData(), and model.data.WizardData.getWizardDataByType().
Referenced by view.editor.wizards.GameElementWizard.launchBoundsWizard().
boolean view.editor.wizards.GameElementWizard.checkCanSave ()
Definition at line 152 of file GameElementWizard.java.
References model.data.WizardType.BOUNDS, view.editor.wizards.Wizard.getWizardData(), and model.data.WizardData.getWizardDataByType().
void view.editor.wizards.GameElementWizard.createSliderListeners () private
Definition at line 363 of file GameElementWizard.java.
References view.editor.wizards.AnimationGrid.changeSize(), view.editor.wizards.Grid.getFrameX(), view.editor.wizards.Grid.getFrameY(), and view.editor.wizards.GameElementWizard.setValueListener().
Referenced by view.editor.wizards.GameElementWizard.initializeSliders().
void view.editor.wizards.GameElementWizard.createTextFieldListeners () private
Definition at line 350 of file GameElementWizard.java.
References view.editor.wizards.GameElementWizard.setTextListener().
Referenced by view.editor.wizards.GameElementWizard.initializeSliders().
File view.editor.wizards.GameElementWizard.fetchImage () throws FileNotFoundException private
Gets an image from a file of the user's choice
Returns
image an Image of the user's choosing
Exceptions
FileNotFoundException
Definition at line 238 of file GameElementWizard.java.
Referenced by view.editor.wizards.GameElementWizard.loadColorMask(), and view.editor.wizards.GameElementWizard.loadImage().
BiConsumer<Button, WizardData> view.editor.wizards.GameElementWizard.getActionConsumer () private
Definition at line 313 of file GameElementWizard.java.
References model.data.WizardDataType.ACTION.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
BiConsumer<Button, WizardData> view.editor.wizards.GameElementWizard.getAnimationConsumer () private
Definition at line 329 of file GameElementWizard.java.
References model.data.WizardDataType.ANIMATION_TAG.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
BiConsumer<Button, WizardData> view.editor.wizards.GameElementWizard.getAttributeConsumer () private
Definition at line 317 of file GameElementWizard.java.
References model.data.WizardDataType.ATTRIBUTE, and model.data.WizardDataType.VALUE.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
WizardData view.editor.wizards.GameElementWizard.getBoundsFromWizardData (WizardType boundsType) private
Definition at line 227 of file GameElementWizard.java.
References view.editor.wizards.Wizard.getWizardData(), and model.data.WizardData.getWizardDataByType().
Referenced by view.editor.wizards.GameElementWizard.launchBoundsWizard().
BiConsumer<Button, WizardData> view.editor.wizards.GameElementWizard.getWidgetConsumer () private
Definition at line 325 of file GameElementWizard.java.
References model.data.WizardDataType.WIDGET_TYPE.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
void view.editor.wizards.GameElementWizard.initContainers () private
Definition at line 299 of file GameElementWizard.java.
References view.gui.GUIPanePath.ACTION_WIZARD, view.gui.GUIPanePath.ANIMATION_WIZARD, view.editor.wizards.GameElementWizard.getActionConsumer(), view.editor.wizards.GameElementWizard.getAnimationConsumer(), view.editor.wizards.GameElementWizard.getAttributeConsumer(), view.editor.wizards.GameElementWizard.getWidgetConsumer(), view.editor.wizards.CRUDContainer.init(), view.editor.wizards.GameElementWizard.isAnimationLaunchValid(), view.gui.GUIPanePath.NUMBER_ATTRIBUTE_WIZARD, view.editor.wizards.CRUDContainer.setValidToLaunch(), view.gui.GUIPanePath.STRING_ATTRIBUTE_WIZARD, and view.gui.GUIPanePath.WIDGET_WIZARD.
Referenced by view.editor.wizards.GameElementWizard.initialize().
void view.editor.wizards.GameElementWizard.initialize ()
Implements view.gui.GUIController.
Definition at line 110 of file GameElementWizard.java.
References model.data.WizardType.BOUNDS, view.editor.wizards.Wizard.errorMessage, view.editor.wizards.GameElementWizard.initContainers(), view.editor.wizards.GameElementWizard.launchBoundsWizard(), view.editor.wizards.GameElementWizard.loadColorMask(), view.editor.wizards.GameElementWizard.loadImage(), and model.data.WizardType.VISION_BOUNDS.
void view.editor.wizards.GameElementWizard.initializeSliders (Image image) private
Definition at line 288 of file GameElementWizard.java.
References view.editor.wizards.GameElementWizard.createSliderListeners(), and view.editor.wizards.GameElementWizard.createTextFieldListeners().
Referenced by view.editor.wizards.GameElementWizard.renderImage().
BooleanSupplier view.editor.wizards.GameElementWizard.isAnimationLaunchValid () private
Definition at line 333 of file GameElementWizard.java.
References view.editor.wizards.Wizard.displayErrorMessage().
Referenced by view.editor.wizards.GameElementWizard.initContainers().
void view.editor.wizards.GameElementWizard.launchBoundsWizard (WizardType boundsType) private
Definition at line 210 of file GameElementWizard.java.
References view.editor.wizards.Wizard.addWizardData(), view.gui.GUIPanePath.BOUNDS_WIZARD, view.editor.wizards.GameElementWizard.boundsAlreadyExist(), view.editor.wizards.Wizard.closeStage(), view.editor.wizards.GameElementWizard.getBoundsFromWizardData(), view.editor.wizards.Wizard.getWizardData(), view.editor.wizards.Wizard.launchForEdit(), view.editor.wizards.WizardUtility.loadWizard(), model.data.WizardData.removeWizardData(), and view.editor.wizards.Wizard.setSubmit().
Referenced by view.editor.wizards.GameElementWizard.initialize().
void view.editor.wizards.GameElementWizard.launchForEdit (WizardData oldValues)
Definition at line 183 of file GameElementWizard.java.
References view.editor.wizards.GameElementWizard.addContainerData(), view.editor.wizards.GameElementWizard.addImageToView(), model.data.WizardType.ANIMATION_SEQUENCE, model.data.WizardDataType.COLOR_MASK, model.data.WizardDataType.FRAME_X, model.data.WizardDataType.FRAME_Y, model.data.WizardData.getValueByKey(), model.data.WizardDataType.IMAGE, model.data.WizardDataType.NAME, model.data.WizardType.NUMBER_ATTRIBUTE, view.editor.wizards.GameElementWizard.renderImage(), model.data.WizardType.STRING_ATTRIBUTE, model.data.WizardType.TRIGGER, model.data.WizardDataType.TYPE, and model.data.WizardType.WIDGET.
Referenced by view.editor.ElementAccordionController.openDrawableGameElementWizard(), and view.editor.ElementAccordionController.openSelectableGameElementWizard().
void view.editor.wizards.GameElementWizard.loadColorMask () private
Definition at line 247 of file GameElementWizard.java.
References view.editor.wizards.GameElementWizard.addImageToView(), view.editor.wizards.Wizard.displayErrorMessage(), and view.editor.wizards.GameElementWizard.fetchImage().
Referenced by view.editor.wizards.GameElementWizard.initialize().
void view.editor.wizards.GameElementWizard.loadGlobalValues (List< String > values)
Definition at line 206 of file GameElementWizard.java.
void view.editor.wizards.GameElementWizard.loadImage () private
Definition at line 258 of file GameElementWizard.java.
References view.editor.wizards.Wizard.displayErrorMessage(), view.editor.wizards.GameElementWizard.fetchImage(), and view.editor.wizards.GameElementWizard.renderImage().
Referenced by view.editor.wizards.GameElementWizard.initialize().
void view.editor.wizards.GameElementWizard.renderImage (File imageFile) throws FileNotFoundException private
Definition at line 271 of file GameElementWizard.java.
References view.editor.wizards.GameElementWizard.addImageToView(), and view.editor.wizards.GameElementWizard.initializeSliders().
Referenced by view.editor.wizards.GameElementWizard.launchForEdit(), and view.editor.wizards.GameElementWizard.loadImage().
void view.editor.wizards.GameElementWizard.setTextListener (TextField field, Consumer< Double > cons) private
Definition at line 355 of file GameElementWizard.java.
References view.editor.wizards.Wizard.isNumber().
Referenced by view.editor.wizards.GameElementWizard.createTextFieldListeners().
void view.editor.wizards.GameElementWizard.setValueListener (Slider slider, Consumer< String > cons, Consumer< Double > gridCons) private
Definition at line 372 of file GameElementWizard.java.
Referenced by view.editor.wizards.GameElementWizard.createSliderListeners().
void view.editor.wizards.GameElementWizard.storeContainerData (CRUDContainer container) private
Definition at line 380 of file GameElementWizard.java.
References view.editor.wizards.Wizard.addWizardData(), and view.editor.wizards.CRUDContainer.getWizardDatas().
Referenced by view.editor.wizards.GameElementWizard.updateData().
void view.editor.wizards.GameElementWizard.updateData ()
Definition at line 158 of file GameElementWizard.java.
References view.editor.wizards.Wizard.addToData(), model.data.WizardDataType.COLOR_MASK, model.data.WizardDataType.FRAME_X, model.data.WizardDataType.FRAME_Y, model.data.WizardType.GAME_ELEMENT, view.editor.wizards.AnimationGrid.getNumRows(), model.data.WizardDataType.IMAGE, model.data.WizardDataType.NAME, model.data.WizardDataType.ROWS, view.editor.wizards.Wizard.setWizardType(), view.editor.wizards.GameElementWizard.storeContainerData(), and model.data.WizardDataType.TYPE.
Member Data Documentation
final Dimension view.editor.wizards.GameElementWizard.ACTION_WIZARD_SIZE = new Dimension(400, 600) static private
Definition at line 57 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.ADD_ANIMATION_KEY = "AddAnimation" static private
Definition at line 49 of file GameElementWizard.java.
final Dimension view.editor.wizards.GameElementWizard.ANIMATION_WIZARD_SIZE = new Dimension(800, 800) static private
Definition at line 58 of file GameElementWizard.java.
AnimationGrid view.editor.wizards.GameElementWizard.animationGrid private
Definition at line 105 of file GameElementWizard.java.
CRUDContainer view.editor.wizards.GameElementWizard.animationsController private
Definition at line 100 of file GameElementWizard.java.
final Dimension view.editor.wizards.GameElementWizard.BOUNDS_WIZARD_SIZE = new Dimension(500, 700) static private
Definition at line 56 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.COLOR_MASK_KEY = "ColorMask" static private
Definition at line 55 of file GameElementWizard.java.
Button view.editor.wizards.GameElementWizard.colorMask private
Definition at line 70 of file GameElementWizard.java.
String view.editor.wizards.GameElementWizard.colorMaskPath private
Definition at line 107 of file GameElementWizard.java.
final int view.editor.wizards.GameElementWizard.DEFAULT_GRID_MIN = 10 private
Definition at line 59 of file GameElementWizard.java.
final int view.editor.wizards.GameElementWizard.DEFAULT_GRID_VALUE = 100 private
Definition at line 60 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.FRAME_HEIGHT_KEY = "FrameHeight" static private
Definition at line 53 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.FRAME_WIDTH_KEY = "FrameWidth" static private
Definition at line 54 of file GameElementWizard.java.
Slider view.editor.wizards.GameElementWizard.frameHeight private
Definition at line 84 of file GameElementWizard.java.
Label view.editor.wizards.GameElementWizard.frameHeightLabel private
Definition at line 76 of file GameElementWizard.java.
TextField view.editor.wizards.GameElementWizard.frameHeightText private
Definition at line 86 of file GameElementWizard.java.
Slider view.editor.wizards.GameElementWizard.frameWidth private
Definition at line 78 of file GameElementWizard.java.
Label view.editor.wizards.GameElementWizard.frameWidthLabel private
Definition at line 82 of file GameElementWizard.java.
TextField view.editor.wizards.GameElementWizard.frameWidthText private
Definition at line 80 of file GameElementWizard.java.
Button view.editor.wizards.GameElementWizard.image private
Definition at line 68 of file GameElementWizard.java.
Referenced by view.editor.wizards.GameElementWizard.addImageToView().
String view.editor.wizards.GameElementWizard.imagePath private
Definition at line 106 of file GameElementWizard.java.
ScrollPane view.editor.wizards.GameElementWizard.imageScroll private
Definition at line 74 of file GameElementWizard.java.
List<String> view.editor.wizards.GameElementWizard.imageValues private
Definition at line 101 of file GameElementWizard.java.
ImageView view.editor.wizards.GameElementWizard.imageView private
Definition at line 104 of file GameElementWizard.java.
ScrollPane view.editor.wizards.GameElementWizard.leftPane private
Definition at line 62 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.LOAD_IMAGE_KEY = "LoadImage" static private
Definition at line 52 of file GameElementWizard.java.
List<String> view.editor.wizards.GameElementWizard.myGlobalNumberAttributes private
Definition at line 103 of file GameElementWizard.java.
List<String> view.editor.wizards.GameElementWizard.myGlobalStringAttributes private
Definition at line 102 of file GameElementWizard.java.
TextField view.editor.wizards.GameElementWizard.name private
Definition at line 64 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.NAME_KEY = "Name" static private
Definition at line 43 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.NEW_ACTION_KEY = "NewAction" static private
Definition at line 45 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.NEW_NUMBER_ATTRIBUTE_KEY = "NewNumberAttribute" static private
Definition at line 47 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.NEW_STRING_ATTRIBUTE_KEY = "NewStringAttribute" static private
Definition at line 46 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.NEW_WIDGET_KEY = "NewWidget" static private
Definition at line 48 of file GameElementWizard.java.
CRUDContainer view.editor.wizards.GameElementWizard.numberAttributesController private
Definition at line 94 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.SET_BOUNDS_KEY = "SetBounds" static private
Definition at line 50 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.SET_VISION_BOUNDS_KEY = "SetVisionBounds" static private
Definition at line 51 of file GameElementWizard.java.
Button view.editor.wizards.GameElementWizard.setBounds private
Definition at line 88 of file GameElementWizard.java.
Button view.editor.wizards.GameElementWizard.setVisionBounds private
Definition at line 90 of file GameElementWizard.java.
Group view.editor.wizards.GameElementWizard.spritesheet private
Definition at line 72 of file GameElementWizard.java.
CRUDContainer view.editor.wizards.GameElementWizard.stringAttributesController private
Definition at line 92 of file GameElementWizard.java.
CRUDContainer view.editor.wizards.GameElementWizard.triggersController private
Definition at line 96 of file GameElementWizard.java.
TextField view.editor.wizards.GameElementWizard.type private
Definition at line 66 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.TYPE_KEY = "Type" static private
Definition at line 44 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.UNABLE_TO_LAUNCH_ANIM static private
Initial value:
=
            "Can't launch due to unspecified image information"
Definition at line 40 of file GameElementWizard.java.
final String view.editor.wizards.GameElementWizard.UNABLE_TO_LOAD = "Unable to Load Image" static private
Definition at line 42 of file GameElementWizard.java.
CRUDContainer view.editor.wizards.GameElementWizard.widgetsController private
Definition at line 98 of file GameElementWizard.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/GameElementWizard.java