voogasalad_TheException: game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory Class Reference
game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory Class Reference
Public Member Functions
ParameterFactory (GameElementManager manager)
Parameter createParameter (String actorTag, String dataType, String attributeTag) throws BadParameterFormatException
Private Member Functions
Parameter getParameter (ObjectOfInterestIdentifier identifier, String dataType, String attributeTag) throws BadParameterFormatException
ObjectOfInterestIdentifier getObjectOfInterestIdentifier (String actorTag) throws BadParameterFormatException
Class<?> getClassFromString (Map< String, Class<?>> classMap, String tagString)
Private Attributes
GameElementManager myManager
Detailed Description
A factory for parameters that takes in a string representing a parameter and returns the parameter associated with it
Author
John
Definition at line 19 of file ParameterFactory.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.ParameterFactory (GameElementManager manager)
Definition at line 23 of file ParameterFactory.java.
Member Function Documentation
Parameter game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.createParameter (String actorTag, String dataType, String attributeTag) throws BadParameterFormatException
Given the three important attributes of a parameter, return the parameter associated with these attributes
Parameters
actorTag the type of actor this parameter is referencing
dataType the type of data this parameter will be interacting with
attributeTag the tag of the attribute referenced by this parameter
Returns
Exceptions
BadParameterFormatException
Definition at line 37 of file ParameterFactory.java.
References game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.getObjectOfInterestIdentifier(), and game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.getParameter().
Class<?> game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.getClassFromString (Map< String, Class<?>> classMap, String tagString) private
Definition at line 84 of file ParameterFactory.java.
Referenced by game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.getObjectOfInterestIdentifier(), and game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.getParameter().
ObjectOfInterestIdentifier game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.getObjectOfInterestIdentifier (String actorTag) throws BadParameterFormatException private
Definition at line 65 of file ParameterFactory.java.
References game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.getClassFromString().
Referenced by game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.createParameter().
Parameter game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.getParameter (ObjectOfInterestIdentifier identifier, String dataType, String attributeTag) throws BadParameterFormatException private
Definition at line 44 of file ParameterFactory.java.
References game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.getClassFromString().
Referenced by game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.createParameter().
Member Data Documentation
GameElementManager game_engine.gameRepresentation.conditions.evaluators.parameters.ParameterFactory.myManager private
Definition at line 21 of file ParameterFactory.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/conditions/evaluators/parameters/ParameterFactory.java