voogasalad_TheException: engine.UI.RunnerInputManager Class Reference
engine.UI.RunnerInputManager Class Reference
Public Member Functions
RunnerInputManager (MainModel model, GameElementManager gameElementManager, GameLoop gameLoop, Participant user)
void primaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
void secondaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
void primaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
void secondaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
void keyPressed (KeyEvent e)
void primaryDragOccurred (MouseEvent e, SelectionBox b)
void secondaryDragOccurred (MouseEvent e, SelectionBox b)
void screenButtonClicked (int buttonID)
Public Member Functions inherited from engine.UI.InputManager
InputManager (MainModel model, GameElementManager gameElementManager, GameLoop gameLoop, Participant user)
abstract void primaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
abstract void secondaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
abstract void primaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
abstract void secondaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
abstract void primaryDragOccurred (MouseEvent e, SelectionBox b)
abstract void secondaryDragOccurred (MouseEvent e, SelectionBox b)
abstract void keyPressed (KeyEvent e)
abstract void screenButtonClicked (int buttonID)
Static Private Attributes
static final String DIGIT = "DIGIT"
Additional Inherited Members
Protected Attributes inherited from engine.UI.InputManager
MainModel myMainModel
GameElementManager myElementManager
GameLoop myGameLoop
Participant myUser
Detailed Description
Input Manager for the game runner
Author
John Lorenz, Jonathan Tseng
Definition at line 21 of file RunnerInputManager.java.
Constructor & Destructor Documentation
engine.UI.RunnerInputManager.RunnerInputManager (MainModel model, GameElementManager gameElementManager, GameLoop gameLoop, Participant user)
Definition at line 24 of file RunnerInputManager.java.
References engine.stateManaging.GameLoop.setRunnerLoop().
Member Function Documentation
void engine.UI.RunnerInputManager.keyPressed (KeyEvent e)
Definition at line 72 of file RunnerInputManager.java.
References engine.UI.InputManager.myElementManager, engine.UI.InputManager.myGameLoop, engine.UI.InputManager.myUser, engine.stateManaging.GameElementManager.notifyButtonClicked(), and engine.stateManaging.GameLoop.pause().
void engine.UI.RunnerInputManager.primaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
Definition at line 32 of file RunnerInputManager.java.
References engine.UI.InputManager.myElementManager, engine.UI.InputManager.myUser, engine.visuals.SelectionBox.primaryClick(), and engine.stateManaging.GameElementManager.selectSingleUnit().
void engine.UI.RunnerInputManager.primaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
Definition at line 54 of file RunnerInputManager.java.
References engine.visuals.SelectionBox.clickReleased(), engine.UI.InputManager.myElementManager, engine.UI.InputManager.myUser, and engine.stateManaging.GameElementManager.selectUnitsInBounds().
void engine.UI.RunnerInputManager.primaryDragOccurred (MouseEvent e, SelectionBox b)
Definition at line 86 of file RunnerInputManager.java.
References engine.visuals.SelectionBox.reactToDrag().
void engine.UI.RunnerInputManager.screenButtonClicked (int buttonID)
Definition at line 96 of file RunnerInputManager.java.
References engine.UI.InputManager.myElementManager, engine.UI.InputManager.myUser, and engine.stateManaging.GameElementManager.notifyButtonClicked().
void engine.UI.RunnerInputManager.secondaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
Definition at line 43 of file RunnerInputManager.java.
References engine.UI.InputManager.myElementManager, engine.UI.InputManager.myUser, and engine.stateManaging.GameElementManager.setSelectedUnitCommand().
void engine.UI.RunnerInputManager.secondaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
Definition at line 64 of file RunnerInputManager.java.
void engine.UI.RunnerInputManager.secondaryDragOccurred (MouseEvent e, SelectionBox b)
Definition at line 91 of file RunnerInputManager.java.
Member Data Documentation
final String engine.UI.RunnerInputManager.DIGIT = "DIGIT" static private
Definition at line 23 of file RunnerInputManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/UI/RunnerInputManager.java