voogasalad_TheException: model.data.WizardData Class Reference
model.data.WizardData Class Reference
Public Member Functions
WizardData ()
void setType (WizardType type)
void addDataPair (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void clear ()
Map< WizardDataType, String > getData ()
List< WizardData > getWizards ()
WizardType getType ()
String getValueByKey (WizardDataType key)
List< WizardData > getWizardDataByType (WizardType type)
void removeWizardData (WizardData data)
String toString ()
Private Attributes
WizardType myType
Map< WizardDataType, String > myData
List< WizardData > myWizards
Detailed Description
This class is the data structure which backs all Wizards. The data structure holds a type specified by an enum along with a map of enums to Strings to specify the data at the lowest level. Furthermore, one can nest WizardData objects within one another to represent Wizards being nested within one another.
Author
Nishad Agrawal
Definition at line 19 of file WizardData.java.
Constructor & Destructor Documentation
model.data.WizardData.WizardData ()
Definition at line 24 of file WizardData.java.
References model.data.WizardType.UNSPECIFIED.
Member Function Documentation
void model.data.WizardData.addDataPair (WizardDataType key, String value)
Definition at line 34 of file WizardData.java.
Referenced by view.editor.wizards.Wizard.addToData(), model.MainModel.createDrawableGameElementState(), model.MainModel.createSelectableGameElementState(), model.data.WizardDataFactory.createWizardData(), view.editor.wizards.CRUDContainer.launchEditWizard(), and view.editor.TabViewController.recreateWizardData().
void model.data.WizardData.addWizardData (WizardData wizData)
Definition at line 38 of file WizardData.java.
Referenced by view.editor.wizards.Wizard.addWizardData(), and model.data.WizardDataFactory.createWizardData().
void model.data.WizardData.clear ()
Definition at line 42 of file WizardData.java.
Referenced by view.editor.wizards.CRUDContainer.launchEditWizard().
Map<WizardDataType, String> model.data.WizardData.getData ()
Definition at line 47 of file WizardData.java.
References model.data.WizardData.myData.
WizardType model.data.WizardData.getType ()
Definition at line 55 of file WizardData.java.
References model.data.WizardData.myType.
Referenced by view.editor.ElementAccordionController.openDrawableGameElementWizard(), and view.editor.ElementAccordionController.openSelectableGameElementWizard().
String model.data.WizardData.getValueByKey (WizardDataType key)
Definition at line 59 of file WizardData.java.
Referenced by model.GameElementStateFactory.addEssentials(), model.GameElementStateFactory.createActionWrapper(), model.AnimatorStateFactory.createAnimationTags(), model.AnimatorStateFactory.createAnimatorState(), view.editor.wizards.CampaignWizard.launchForEdit(), view.editor.wizards.PositionWizard.launchForEdit(), view.editor.wizards.AttributeWizard.launchForEdit(), view.editor.wizards.LevelWizard.launchForEdit(), view.editor.wizards.BoundsWizard.launchForEdit(), view.editor.wizards.WidgetWizard.launchForEdit(), view.editor.wizards.ActionWizard.launchForEdit(), view.editor.wizards.GameElementWizard.launchForEdit(), and view.editor.wizards.AnimationWizard.launchForEdit().
List<WizardData> model.data.WizardData.getWizardDataByType (WizardType type)
Definition at line 63 of file WizardData.java.
Referenced by view.editor.wizards.GameElementWizard.addContainerData(), model.GameElementStateFactory.addEssentials(), model.GameElementStateFactory.addToState(), view.editor.wizards.GameElementWizard.boundsAlreadyExist(), view.editor.wizards.GameElementWizard.checkCanSave(), model.AnimatorStateFactory.createAnimationSequences(), model.GameElementStateFactory.createAttributeDisplayerState(), model.GameElementStateFactory.createBounds(), and view.editor.wizards.GameElementWizard.getBoundsFromWizardData().
List<WizardData> model.data.WizardData.getWizards ()
Definition at line 51 of file WizardData.java.
References model.data.WizardData.myWizards.
void model.data.WizardData.removeWizardData (WizardData data)
Definition at line 68 of file WizardData.java.
Referenced by view.editor.wizards.GameElementWizard.launchBoundsWizard(), and view.editor.wizards.Wizard.removeWizardData().
void model.data.WizardData.setType (WizardType type)
Definition at line 30 of file WizardData.java.
Referenced by model.data.WizardDataFactory.createWizardData(), and view.editor.wizards.Wizard.setWizardType().
String model.data.WizardData.toString ()
Definition at line 73 of file WizardData.java.
Member Data Documentation
Map<WizardDataType, String> model.data.WizardData.myData private
Definition at line 21 of file WizardData.java.
Referenced by model.data.WizardData.getData().
WizardType model.data.WizardData.myType private
Definition at line 20 of file WizardData.java.
Referenced by model.data.WizardData.getType().
List<WizardData> model.data.WizardData.myWizards private
Definition at line 22 of file WizardData.java.
Referenced by model.data.WizardData.getWizards().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/data/WizardData.java