voogasalad_TheException: game_engine.stateManaging.GameElementManager Class Reference
game_engine.stateManaging.GameElementManager Class Reference
Public Member Functions
GameElementManager (Level level, GameElementFactory factory)
List< GameElement > findAllElementsOfType (String typeName)
void addGameElementToLevel (String typeName, double x, double y)
void addDrawableGameElementToLevel (String typeName, double x, double y)
void addSelectableGameElementToLevel (String typeName, double x, double y)
void update (Observable o, Object arg)
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void selectUnitsBox (double[] rectPoints, boolean isShiftDown)
void selectUnitsClick (Point2D clickLoc, boolean isShiftDown)
boolean contains (double[] rectPoints, Point2D unitLocationCenter)
void sendClickToSelectedUnits (Point2D click, boolean isPrimary, boolean shiftHeld)
Private Attributes
Level myLevel
GameElementFactory myFactory
Detailed Description
A manager for selecting, deselecting, and interacting with game elements
Author
John, Steve, Michael D., Zach
Definition at line 31 of file GameElementManager.java.
Constructor & Destructor Documentation
game_engine.stateManaging.GameElementManager.GameElementManager (Level level, GameElementFactory factory)
Definition at line 36 of file GameElementManager.java.
Referenced by game_engine.stateManaging.GameElementManager.main().
Member Function Documentation
void game_engine.stateManaging.GameElementManager.addDrawableGameElementToLevel (String typeName, double x, double y)
Definition at line 58 of file GameElementManager.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.addElement(), and game_engine.elementFactories.GameElementFactory.createDrawableGameElement().
void game_engine.stateManaging.GameElementManager.addGameElementToLevel (String typeName, double x, double y)
Definition at line 53 of file GameElementManager.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.addElement(), and game_engine.elementFactories.GameElementFactory.createGameElement().
void game_engine.stateManaging.GameElementManager.addSelectableGameElementToLevel (String typeName, double x, double y)
Definition at line 63 of file GameElementManager.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.addElement(), and game_engine.elementFactories.GameElementFactory.createSelectableGameElement().
Referenced by game_engine.stateManaging.GameElementManager.main().
boolean game_engine.stateManaging.GameElementManager.contains (double[] rectPoints, Point2D unitLocationCenter) private
Definition at line 106 of file GameElementManager.java.
Referenced by game_engine.stateManaging.GameElementManager.selectUnitsBox(), and game_engine.stateManaging.GameElementManager.selectUnitsClick().
List<GameElement> game_engine.stateManaging.GameElementManager.findAllElementsOfType (String typeName)
Get all the game elements of a given type
Parameters
typeName the name of the type of the game elements
Returns
all the game elements with the given type
Definition at line 48 of file GameElementManager.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Referenced by game_engine.gameRepresentation.evaluatables.parameters.objectIdentifiers.GlobalObjectIdentifier.getElementOfInterest().
static void game_engine.stateManaging.GameElementManager.main (String[] args) static
Definition at line 161 of file GameElementManager.java.
References gamemodel.GameUniverse.addSelectableGameElementState(), game_engine.stateManaging.GameElementManager.addSelectableGameElementToLevel(), game_engine.elementFactories.LevelFactory.createLevel(), game_engine.stateManaging.GameElementManager.GameElementManager(), game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.NAME_ATTRIBUTE_STRING, and game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setTextualAttribute().
void game_engine.stateManaging.GameElementManager.selectUnitsBox (double[] rectPoints, boolean isShiftDown) private
Select all the elements in a given rectangle
Parameters
rectPoints the points in the rectangle surrounding the player's units
Definition at line 74 of file GameElementManager.java.
References game_engine.stateManaging.GameElementManager.contains(), game_engine.gameRepresentation.renderedRepresentation.Level.getUnits(), and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.TEAM_ID.
Referenced by game_engine.stateManaging.GameElementManager.update().
void game_engine.stateManaging.GameElementManager.selectUnitsClick (Point2D clickLoc, boolean isShiftDown) private
Definition at line 86 of file GameElementManager.java.
References game_engine.stateManaging.GameElementManager.contains(), game_engine.gameRepresentation.renderedRepresentation.Level.getUnits(), and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.TEAM_ID.
Referenced by game_engine.stateManaging.GameElementManager.update().
void game_engine.stateManaging.GameElementManager.sendClickToSelectedUnits (Point2D click, boolean isPrimary, boolean shiftHeld) private
Definition at line 120 of file GameElementManager.java.
References game_engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Referenced by game_engine.stateManaging.GameElementManager.update().
void game_engine.stateManaging.GameElementManager.update (Observable o, Object arg)
Update the rectangle on the image and check for clicks
Definition at line 135 of file GameElementManager.java.
References game_engine.UI.MouseManager.getLastClick(), game_engine.visuals.SelectionBox.getLastClick(), game_engine.UI.MouseManager.getMapLoc(), game_engine.visuals.SelectionBox.getPoints(), game_engine.stateManaging.GameElementManager.selectUnitsBox(), game_engine.stateManaging.GameElementManager.selectUnitsClick(), and game_engine.stateManaging.GameElementManager.sendClickToSelectedUnits().
Member Data Documentation
GameElementFactory game_engine.stateManaging.GameElementManager.myFactory private
Definition at line 34 of file GameElementManager.java.
Level game_engine.stateManaging.GameElementManager.myLevel private
Definition at line 33 of file GameElementManager.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/stateManaging/GameElementManager.java