voogasalad_TheException: application.RPG Class Reference
application.RPG Class Reference
Public Member Functions
void start (Stage primaryStage)
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final java.awt.Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize()
static final int shittyWidth = 1000
Private Member Functions
Engine hardCodeAGame () throws Exception
SelectableGameElementState createSpawnPoint (double x, double y, String Color) throws Exception
GameElementState createGoal ()
SelectableGameElementState createEnemyUnit (double[] bounds, double health, double attack, double reloadTime, double x, double y, double movementSpeed, int teamID, String pictureURI) throws Exception
SelectableGameElementState createMovingUnit (double[] bounds, double health, double attack, double reloadTime, double x, double y, double movementSpeed, int teamID, String pictureURI) throws Exception
Detailed Description
Definition at line 27 of file RPG.java.
Member Function Documentation
SelectableGameElementState application.RPG.createEnemyUnit (double[] bounds, double health, double attack, double reloadTime, double x, double y, double movementSpeed, int teamID, String pictureURI) throws Exception private
Definition at line 214 of file RPG.java.
References model.state.gameelement.GameElementState.addAction(), model.state.gameelement.GameElementState.addType(), model.state.gameelement.GameElementState.attributes, application.RPG.createMovingUnit(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL, model.state.gameelement.StateTags.IS_DEAD, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.MOTHER_OF_ALL_ACTIONS, model.state.gameelement.StateTags.RESOURCES, and model.state.gameelement.AttributeContainer.setNumericalAttribute().
Referenced by application.RPG.hardCodeAGame().
GameElementState application.RPG.createGoal () private
Definition at line 200 of file RPG.java.
References model.state.gameelement.GameElementState.addAction(), model.state.gameelement.GameElementState.attributes, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.PLAYER_ATTRIBUTE_CONDITION, and model.state.gameelement.AttributeContainer.setNumericalAttribute().
Referenced by application.RPG.hardCodeAGame().
SelectableGameElementState application.RPG.createMovingUnit (double[] bounds, double health, double attack, double reloadTime, double x, double y, double movementSpeed, int teamID, String pictureURI) throws Exception private
Definition at line 242 of file RPG.java.
References engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.ACT_ON_OBJECTS_ACTION, model.state.gameelement.GameElementState.addAction(), model.state.gameelement.GameElementState.addType(), model.state.gameelement.StateTags.ATTACK, model.state.gameelement.GameElementState.attributes, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.CHECK_ATTR_SET_ATTR_ACTION, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.COLLISION, model.state.gameelement.StateTags.CURRENT_ACTION, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.FOCUSED, model.state.gameelement.StateTags.HEALTH, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL, util.SaveLoadUtility.loadResource(), model.state.gameelement.StateTags.MOVEMENT_SPEED, model.state.gameelement.DrawableGameElementState.myAnimatorState, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.OBJECT_CONDITION_ACTION, model.state.gameelement.StateTags.RELOAD_TIME, model.state.gameelement.DrawableGameElementState.setBounds(), model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), model.state.gameelement.StateTags.X_GOAL_POSITION, model.state.gameelement.StateTags.X_POSITION, model.state.gameelement.StateTags.X_TEMP_GOAL_POSITION, model.state.gameelement.StateTags.Y_GOAL_POSITION, model.state.gameelement.StateTags.Y_POSITION, and model.state.gameelement.StateTags.Y_TEMP_GOAL_POSITION.
Referenced by application.RPG.createEnemyUnit(), and application.RPG.hardCodeAGame().
SelectableGameElementState application.RPG.createSpawnPoint (double x, double y, String Color) throws Exception private
Definition at line 167 of file RPG.java.
References model.state.gameelement.GameElementState.addAction(), model.state.gameelement.GameElementState.addType(), model.state.gameelement.GameElementState.attributes, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.CHECK_CONDITION_CREATE_OBJECT_ACTION, model.state.gameelement.StateTags.HEALTH, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL, util.SaveLoadUtility.loadResource(), model.state.gameelement.StateTags.MOVEMENT_SPEED, model.state.gameelement.DrawableGameElementState.myAnimatorState, model.state.gameelement.StateTags.RELOAD_TIME, model.state.gameelement.DrawableGameElementState.setBounds(), model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.StateTags.X_POSITION, model.state.gameelement.StateTags.X_SPAWN_OFFSET, model.state.gameelement.StateTags.Y_POSITION, and model.state.gameelement.StateTags.Y_SPAWN_OFFSET.
Referenced by application.RPG.hardCodeAGame().
Engine application.RPG.hardCodeAGame () throws Exception private
Definition at line 49 of file RPG.java.
References model.state.gameelement.GameElementState.addAction(), model.state.gameelement.DrawableGameElementState.addAttributeDisplayerState(), model.state.GameState.addCampaign(), model.state.LevelState.addGoal(), model.state.CampaignState.addLevel(), model.GameUniverse.addSelectableGameElementState(), model.state.LevelState.addUnit(), model.state.gameelement.StateTags.ATTACK, engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerTags.ATTRIBUTE_BAR_DISPLAYER, model.state.gameelement.StateTags.ATTRIBUTE_DESCRIPTION, model.state.LevelState.attributes, model.state.gameelement.GameElementState.attributes, model.state.gameelement.StateTags.BACKGROUND_PATH, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.BUTTON, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.CHECK_ATTR_SET_ATTR_ACTION, application.RPG.createEnemyUnit(), application.RPG.createGoal(), application.RPG.createMovingUnit(), application.RPG.createSpawnPoint(), model.MainModel.getGameUniverse(), model.MainModel.getLevel(), model.state.gameelement.StateTags.HEALTH, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL, model.state.gameelement.StateTags.IS_DEAD, model.state.gameelement.StateTags.LAST_BUTTON_CLICKED_ID, model.state.gameelement.StateTags.LEVEL_HEIGHT, model.state.gameelement.StateTags.LEVEL_WIDTH, model.MainModel.loadGame(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.MOTHER_OF_ALL_ACTIONS, model.state.gameelement.StateTags.NAME, model.state.gameelement.StateTags.RESOURCES, model.MainModel.saveGame(), engine.Engine.setAnimationEnabled(), model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), and model.state.gameelement.StateTags.TEAM_COLOR.
Referenced by application.RPG.start().
static void application.RPG.main (String[] args) static
Definition at line 315 of file RPG.java.
void application.RPG.start (Stage primaryStage)
Definition at line 33 of file RPG.java.
References engine.Engine.getScene(), application.RPG.hardCodeAGame(), engine.Engine.play(), and application.RPG.screenSize.
Member Data Documentation
final java.awt.Dimension application.RPG.screenSize = Toolkit.getDefaultToolkit().getScreenSize() static
Definition at line 29 of file RPG.java.
Referenced by application.RPG.start().
final int application.RPG.shittyWidth = 1000 static
Definition at line 30 of file RPG.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/application/RPG.java