voogasalad_TheException: engine.users.Participant Class Reference
engine.users.Participant Class Reference abstract
Public Member Functions
Participant (long teamColor, String name)
String getName ()
boolean getIsAI ()
AttributeContainer getAttributes ()
boolean checkSameTeam (Number otherTeamColor)
long getTeamColor ()
Public Member Functions inherited from util.JSONable
default String toJSON ()
Protected Attributes
AttributeContainer attributes
long myTeamColor
String myName
boolean isAI
Static Private Attributes
static final long serialVersionUID = 9150235534545105031L
Detailed Description
The representation of the actual player of the game.
Author
Michael D.
Definition at line 16 of file Participant.java.
Constructor & Destructor Documentation
engine.users.Participant.Participant (long teamColor, String name)
Definition at line 29 of file Participant.java.
References model.state.gameelement.AttributeContainer.setNumericalAttribute(), and model.state.gameelement.StateTags.TEAM_COLOR.
Member Function Documentation
boolean engine.users.Participant.checkSameTeam (Number otherTeamColor)
checks whether the team ID passed into this one is the same as this Participant's team ID
Parameters
otherTeamID
Returns
true if the team IDs are the same
Definition at line 65 of file Participant.java.
Referenced by engine.stateManaging.GameElementManager.checkOnTeam(), engine.UI.ParticipantManager.filterParticipants(), engine.stateManaging.GameElementManager.filterTeamIDElements(), and engine.visuals.VisualManager.findFirstSelectedElement().
AttributeContainer engine.users.Participant.getAttributes ()
Definition at line 54 of file Participant.java.
References engine.users.Participant.attributes.
Referenced by engine.UI.ParticipantManager.update(), engine.Engine.update(), and engine.Engine.updateObservers().
boolean engine.users.Participant.getIsAI ()
Gets whether or not the particular user is run by an AI
Returns
true when an AI
Definition at line 50 of file Participant.java.
References engine.users.Participant.isAI.
String engine.users.Participant.getName ()
Gets the name of the user
Returns
The name of the user
Definition at line 41 of file Participant.java.
References engine.users.Participant.myName.
long engine.users.Participant.getTeamColor ()
Definition at line 69 of file Participant.java.
References engine.users.Participant.myTeamColor.
Referenced by engine.UI.EditorInputManager.primaryClickOccurred().
Member Data Documentation
AttributeContainer engine.users.Participant.attributes protected
Definition at line 24 of file Participant.java.
Referenced by engine.users.Participant.getAttributes().
boolean engine.users.Participant.isAI protected
Definition at line 27 of file Participant.java.
Referenced by engine.users.AIParticipant.AIParticipant(), engine.users.Participant.getIsAI(), and engine.users.HumanParticipant.HumanParticipant().
String engine.users.Participant.myName protected
Definition at line 26 of file Participant.java.
Referenced by engine.users.Participant.getName().
long engine.users.Participant.myTeamColor protected
Definition at line 25 of file Participant.java.
Referenced by engine.users.Participant.getTeamColor().
final long engine.users.Participant.serialVersionUID = 9150235534545105031L static private
Definition at line 21 of file Participant.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/users/Participant.java