voogasalad_TheException: model.state.LevelIdentifier Class Reference
model.state.LevelIdentifier Class Reference
Public Member Functions
LevelIdentifier (String levelName, String campaignName)
boolean equals (Object o)
Public Member Functions inherited from util.JSONable
default String toJSON ()
Public Attributes
String levelName
String campaignName
Static Private Attributes
static final long serialVersionUID = -4397687057831738116L
Detailed Description
Definition at line 7 of file LevelIdentifier.java.
Constructor & Destructor Documentation
model.state.LevelIdentifier.LevelIdentifier (String levelName, String campaignName)
Definition at line 13 of file LevelIdentifier.java.
References model.state.LevelIdentifier.campaignName, and model.state.LevelIdentifier.levelName.
Referenced by model.state.LevelIdentifier.equals().
Member Function Documentation
boolean model.state.LevelIdentifier.equals (Object o)
Definition at line 19 of file LevelIdentifier.java.
References model.state.LevelIdentifier.campaignName, model.state.LevelIdentifier.LevelIdentifier(), and model.state.LevelIdentifier.levelName.
Referenced by model.state.LevelState.equals(), and view.editor.TabViewController.isLevel().
Member Data Documentation
String model.state.LevelIdentifier.campaignName
Definition at line 11 of file LevelIdentifier.java.
Referenced by view.editor.EditorScreen.createNewTab(), model.state.LevelIdentifier.equals(), and model.state.LevelIdentifier.LevelIdentifier().
String model.state.LevelIdentifier.levelName
Definition at line 10 of file LevelIdentifier.java.
Referenced by view.editor.EditorScreen.createNewTab(), model.state.LevelIdentifier.equals(), and model.state.LevelIdentifier.LevelIdentifier().
final long model.state.LevelIdentifier.serialVersionUID = -4397687057831738116L static private
Definition at line 9 of file LevelIdentifier.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/LevelIdentifier.java