voogasalad_TheException: resources.processing.SpriteSheetCreationUtility Class Reference
resources.processing.SpriteSheetCreationUtility Class Reference
Classes
class Location
Public Member Functions
void createSpriteSheet (String baseInputDirectoryPath, int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags, Color maskColor) throws Exception
Static Public Member Functions
static void main (String[] args) throws Exception
Static Package Functions
static BufferedImage toBufferedImage (Image src)
Static Package Attributes
static final String[] EXTENSIONS = new String[] { "bmp" }
static final FilenameFilter IMAGE_FILTER
Private Member Functions
void doThing () throws IOException
void extractAllSpriteLists (int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags, File unitDirectory, List< ArrayList< BufferedImage >> allSpriteLists)
List< BufferedImage > extrapolateSprites (List< BufferedImage > uniqueSprites, int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags)
BufferedImage mirrorImageHorizontally (BufferedImage input)
void createStateSpritesheets (int[] extrapolatedStateIndicies, Color maskColor, List< ArrayList< BufferedImage >> allSpriteLists, List< BufferedImage > spritesheets, int frameWidth, int frameHeight) throws IOException
BufferedImage tileImagesIntoColumns (List< BufferedImage > images, int numColumns, int frameWidth, int frameHeight, Color maskColor)
BufferedImage tileSpritesheets (List< BufferedImage > spritesheets, int frameWidth, int frameHeight)
int findMaximumImageHeight (List< BufferedImage > images)
int findMaximumImageWidth (List< BufferedImage > images)
List< BufferedImage > loadFilesInDirectory (File directory)
BufferedImage colorToTransparency (BufferedImage input, Color maskColor) throws IOException
Detailed Description
This utility creates spritesheets with transparent backgrounds from single sprite images.
Author
Steve
Definition at line 37 of file SpriteSheetCreationUtility.java.
Member Function Documentation
BufferedImage resources.processing.SpriteSheetCreationUtility.colorToTransparency (BufferedImage input, Color maskColor) throws IOException private
Changes all pink pixels to transparent pixels.
Parameters
input image
Returns
- image with all pink (0xFFFF00FF) pixels now transparent
Exceptions
IOException
Definition at line 370 of file SpriteSheetCreationUtility.java.
References resources.processing.SpriteSheetCreationUtility.toBufferedImage().
Referenced by resources.processing.SpriteSheetCreationUtility.createStateSpritesheets().
void resources.processing.SpriteSheetCreationUtility.createSpriteSheet (String baseInputDirectoryPath, int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags, Color maskColor) throws Exception
Creates a sprite sheet from a batch of bitmaps with pixel masks.
Parameters
inputDirectoryPath - path to directory holding single sprite bitmaps
outputDirectoryPath - path to directory holding output file
outputFileName - name to give to output
uniqueSpriteIndicies - incidies of states in input
extrapolatedStateIndicies - order of states in output
extrapolatedStateMirrorFlags - which states to mirror horizontally in output
Exceptions
Exception
Definition at line 84 of file SpriteSheetCreationUtility.java.
References resources.processing.ColorMaskExtractor.colorMask, resources.processing.SpriteSheetCreationUtility.createStateSpritesheets(), resources.processing.SpriteSheetCreationUtility.extractAllSpriteLists(), resources.processing.ColorMaskExtractor.extractColorMask(), resources.processing.SpriteSheetCreationUtility.findMaximumImageHeight(), resources.processing.SpriteSheetCreationUtility.findMaximumImageWidth(), resources.processing.ColorMaskExtractor.mutateColorMask(), resources.processing.ColorMaskExtractor.mutatedMask, util.SaveLoadUtility.save(), resources.processing.ColorMaskExtractor.spritesheetColorRemoved, and resources.processing.SpriteSheetCreationUtility.tileSpritesheets().
Referenced by resources.processing.SpriteSheetCreationUtility.main().
void resources.processing.SpriteSheetCreationUtility.createStateSpritesheets (int[] extrapolatedStateIndicies, Color maskColor, List< ArrayList< BufferedImage >> allSpriteLists, List< BufferedImage > spritesheets, int frameWidth, int frameHeight) throws IOException private
Definition at line 227 of file SpriteSheetCreationUtility.java.
References resources.processing.SpriteSheetCreationUtility.colorToTransparency(), and resources.processing.SpriteSheetCreationUtility.tileImagesIntoColumns().
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
void resources.processing.SpriteSheetCreationUtility.doThing () throws IOException private
Definition at line 57 of file SpriteSheetCreationUtility.java.
void resources.processing.SpriteSheetCreationUtility.extractAllSpriteLists (int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags, File unitDirectory, List< ArrayList< BufferedImage >> allSpriteLists) private
Definition at line 140 of file SpriteSheetCreationUtility.java.
References resources.processing.SpriteSheetCreationUtility.extrapolateSprites(), and resources.processing.SpriteSheetCreationUtility.loadFilesInDirectory().
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
List<BufferedImage> resources.processing.SpriteSheetCreationUtility.extrapolateSprites (List< BufferedImage > uniqueSprites, int[] uniqueStateIndicies, int[] extrapolatedStateIndicies, boolean[] extrapolatedStateMirrorFlags) private
This method is able to extrapolate all sprite states necessary from a base set of unique sprite states.
Parameters
uniqueSprites - BufferedImage list of all unique sprites
uniqueStateIndicies - array like [0, 1, 2, 3, 4] (for a five-directional spritesheet)
extrapolatedStateIndicies - array like [0, 1, 2, 3, 4, 3, 2, 1] (to make an eight-directional spritesheet from a five-directional sheet)
extrapolatedStateMirrorFlags - flags to mirror state images
Returns
Definition at line 170 of file SpriteSheetCreationUtility.java.
References resources.processing.SpriteSheetCreationUtility.mirrorImageHorizontally().
Referenced by resources.processing.SpriteSheetCreationUtility.extractAllSpriteLists().
int resources.processing.SpriteSheetCreationUtility.findMaximumImageHeight (List< BufferedImage > images) private
Definition at line 306 of file SpriteSheetCreationUtility.java.
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
int resources.processing.SpriteSheetCreationUtility.findMaximumImageWidth (List< BufferedImage > images) private
Definition at line 316 of file SpriteSheetCreationUtility.java.
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
List<BufferedImage> resources.processing.SpriteSheetCreationUtility.loadFilesInDirectory (File directory) private
Definition at line 344 of file SpriteSheetCreationUtility.java.
Referenced by resources.processing.SpriteSheetCreationUtility.extractAllSpriteLists().
static void resources.processing.SpriteSheetCreationUtility.main (String[] args) throws Exception static
Definition at line 39 of file SpriteSheetCreationUtility.java.
References resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
BufferedImage resources.processing.SpriteSheetCreationUtility.mirrorImageHorizontally (BufferedImage input) private
Mirrors a BufferedImage horizontally.
Parameters
input image
Returns
mirrored input
Definition at line 219 of file SpriteSheetCreationUtility.java.
Referenced by resources.processing.SpriteSheetCreationUtility.extrapolateSprites().
BufferedImage resources.processing.SpriteSheetCreationUtility.tileImagesIntoColumns (List< BufferedImage > images, int numColumns, int frameWidth, int frameHeight, Color maskColor) private
Tiles many images into columns in a spritesheet.
Parameters
images - source sprites
numColumns - number of output columns
Returns
- finished spritesheet with pink background
Definition at line 250 of file SpriteSheetCreationUtility.java.
References resources.processing.SpriteSheetCreationUtility.Location.x, and resources.processing.SpriteSheetCreationUtility.Location.y.
Referenced by resources.processing.SpriteSheetCreationUtility.createStateSpritesheets().
BufferedImage resources.processing.SpriteSheetCreationUtility.tileSpritesheets (List< BufferedImage > spritesheets, int frameWidth, int frameHeight) private
Definition at line 281 of file SpriteSheetCreationUtility.java.
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
static BufferedImage resources.processing.SpriteSheetCreationUtility.toBufferedImage (Image src) static package
Definition at line 387 of file SpriteSheetCreationUtility.java.
Referenced by resources.processing.SpriteSheetCreationUtility.colorToTransparency(), resources.processing.ColorMaskExtractor.extractColorMask(), and resources.processing.ColorMaskExtractor.mutateColorMask().
Member Data Documentation
final String [] resources.processing.SpriteSheetCreationUtility.EXTENSIONS = new String[] { "bmp" } static package
Definition at line 326 of file SpriteSheetCreationUtility.java.
final FilenameFilter resources.processing.SpriteSheetCreationUtility.IMAGE_FILTER static package
Initial value:
= new FilenameFilter() {
        @Override
        public boolean accept (final File dir, final String name) {
            for (final String ext : EXTENSIONS) {
                if (name.endsWith("." + ext)) {
                return (true);
                }
            }
            return (false);
        }
    }
Filters for acceptable images.
Definition at line 331 of file SpriteSheetCreationUtility.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/resources/processing/SpriteSheetCreationUtility.java