voogasalad_TheException: editor.ElementDropDownController Class Reference
editor.ElementDropDownController Class Reference
Classes
class GameElementListCell
Public Member Functions
void addElement (String element, Node image)
void setButtonAction (Consumer< Consumer< WizardData >> consumer)
void bindGameElement (ObjectProperty< String > elementName)
Node getRoot ()
void initialize ()
Private Member Functions
void initListView ()
void initNewElementButton ()
void addElement ()
Private Attributes
Button newElementButton
ListView< String > elementListView
TitledPane elementDropDown
ObservableList< String > myElementsList
HashMap< String, Node > myElementsMap
Static Private Attributes
static final String CREATE_NEW_KEY = "CreateNew"
Detailed Description
Author
Nishad Agrawal
Jonathan Tseng
Definition at line 29 of file ElementDropDownController.java.
Member Function Documentation
void editor.ElementDropDownController.addElement (String element, Node image)
Definition at line 43 of file ElementDropDownController.java.
Referenced by editor.ElementAccordionController.updateItems().
void editor.ElementDropDownController.addElement () private
Definition at line 86 of file ElementDropDownController.java.
Referenced by editor.ElementDropDownController.initNewElementButton().
void editor.ElementDropDownController.bindGameElement (ObjectProperty< String > elementName)
Definition at line 52 of file ElementDropDownController.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by editor.ElementAccordionController.updateItems().
Node editor.ElementDropDownController.getRoot ()
Implements view.GUIController.
Definition at line 102 of file ElementDropDownController.java.
References editor.ElementDropDownController.elementDropDown.
Referenced by editor.ElementAccordionController.updateItems().
void editor.ElementDropDownController.initialize ()
Implements view.GUIController.
Definition at line 107 of file ElementDropDownController.java.
References editor.ElementDropDownController.initListView(), and editor.ElementDropDownController.initNewElementButton().
void editor.ElementDropDownController.initListView () private
Definition at line 62 of file ElementDropDownController.java.
Referenced by editor.ElementDropDownController.initialize().
void editor.ElementDropDownController.initNewElementButton () private
Definition at line 82 of file ElementDropDownController.java.
References editor.ElementDropDownController.addElement().
Referenced by editor.ElementDropDownController.initialize().
void editor.ElementDropDownController.setButtonAction (Consumer< Consumer< WizardData >> consumer)
Definition at line 48 of file ElementDropDownController.java.
Referenced by editor.ElementAccordionController.updateItems().
Member Data Documentation
final String editor.ElementDropDownController.CREATE_NEW_KEY = "CreateNew" static private
Definition at line 31 of file ElementDropDownController.java.
TitledPane editor.ElementDropDownController.elementDropDown private
Definition at line 38 of file ElementDropDownController.java.
Referenced by editor.ElementDropDownController.getRoot().
ListView<String> editor.ElementDropDownController.elementListView private
Definition at line 36 of file ElementDropDownController.java.
ObservableList<String> editor.ElementDropDownController.myElementsList private
Definition at line 40 of file ElementDropDownController.java.
HashMap<String, Node> editor.ElementDropDownController.myElementsMap private
Definition at line 41 of file ElementDropDownController.java.
Button editor.ElementDropDownController.newElementButton private
Definition at line 34 of file ElementDropDownController.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/ElementDropDownController.java