voogasalad_TheException: application.Pong Class Reference
application.Pong Class Reference
Public Member Functions
void start (Stage primaryStage)
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final java.awt.Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize()
static final int shittyWidth = 1000
Private Member Functions
Engine hardCodeAGame () throws Exception
SelectableGameElementState createGoalDisplayMarker () throws SaveLoadException
SelectableGameElementState createBall (double x, double y) throws Exception
AnimatorState generateNullAnimatorState ()
SelectableGameElementState createBoundary (double x, double y) throws SaveLoadException
SelectableGameElementState createGoalRegion (double x, double y, boolean mine) throws SaveLoadException
SelectableGameElementState createPaddle (double x, double y, int teamID) throws Exception
Detailed Description
Definition at line 32 of file Pong.java.
Member Function Documentation
SelectableGameElementState application.Pong.createBall (double x, double y) throws Exception private
Definition at line 160 of file Pong.java.
References engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.ACT_ON_OBJECTS_ACTION, model.state.gameelement.GameElementState.addAction(), model.state.gameelement.GameElementState.addType(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.COLLISION, model.state.gameelement.StateTags.CURRENT_ACTION, application.Pong.generateNullAnimatorState(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL, model.state.gameelement.StateTags.MOVEMENT_SPEED, model.state.gameelement.DrawableGameElementState.myAnimatorState, model.state.gameelement.GameElementState.myAttributes, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.OBJECT_TYPE_CHECK_ACTION, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.PERFORM_CALCULATION_ON_VALUE, model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), model.state.gameelement.StateTags.TEAM_COLOR, model.state.gameelement.StateTags.X_GOAL_POSITION, model.state.gameelement.StateTags.X_POSITION, model.state.gameelement.StateTags.X_TEMP_GOAL_POSITION, model.state.gameelement.StateTags.X_VELOCITY, model.state.gameelement.StateTags.Y_GOAL_POSITION, model.state.gameelement.StateTags.Y_POSITION, model.state.gameelement.StateTags.Y_TEMP_GOAL_POSITION, and model.state.gameelement.StateTags.Y_VELOCITY.
Referenced by application.Pong.hardCodeAGame().
SelectableGameElementState application.Pong.createBoundary (double x, double y) throws SaveLoadException private
Definition at line 228 of file Pong.java.
References model.state.gameelement.GameElementState.addType(), model.state.gameelement.StateTags.CURRENT_ACTION, application.Pong.generateNullAnimatorState(), model.state.gameelement.DrawableGameElementState.myAnimatorState, model.state.gameelement.GameElementState.myAttributes, model.state.gameelement.DrawableGameElementState.setBounds(), model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), model.state.gameelement.StateTags.TEAM_COLOR, model.state.gameelement.StateTags.X_GOAL_POSITION, model.state.gameelement.StateTags.X_POSITION, model.state.gameelement.StateTags.X_TEMP_GOAL_POSITION, model.state.gameelement.StateTags.Y_GOAL_POSITION, model.state.gameelement.StateTags.Y_POSITION, and model.state.gameelement.StateTags.Y_TEMP_GOAL_POSITION.
Referenced by application.Pong.hardCodeAGame().
SelectableGameElementState application.Pong.createGoalDisplayMarker () throws SaveLoadException private
Definition at line 144 of file Pong.java.
References model.state.gameelement.GameElementState.addType(), model.state.gameelement.StateTags.CURRENT_ACTION, application.Pong.generateNullAnimatorState(), model.state.gameelement.DrawableGameElementState.myAnimatorState, model.state.gameelement.GameElementState.myAttributes, model.state.gameelement.StateTags.NAME, model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), and model.state.gameelement.StateTags.TEAM_COLOR.
Referenced by application.Pong.hardCodeAGame().
SelectableGameElementState application.Pong.createGoalRegion (double x, double y, boolean mine) throws SaveLoadException private
Definition at line 250 of file Pong.java.
References model.state.gameelement.GameElementState.addAction(), model.state.gameelement.GameElementState.addType(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.CHECK_CONDITION_CREATE_OBJECT_ACTION, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.COLLISION, model.state.gameelement.StateTags.CURRENT_ACTION, application.Pong.generateNullAnimatorState(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL, model.state.gameelement.DrawableGameElementState.myAnimatorState, model.state.gameelement.GameElementState.myAttributes, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.OBJECT_TYPE_CHECK_ACTION, model.state.gameelement.StateTags.RESOURCES, model.state.gameelement.DrawableGameElementState.setBounds(), model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), model.state.gameelement.StateTags.TEAM_COLOR, model.state.gameelement.StateTags.X_GOAL_POSITION, model.state.gameelement.StateTags.X_POSITION, model.state.gameelement.StateTags.X_SPAWN_OFFSET, model.state.gameelement.StateTags.X_TEMP_GOAL_POSITION, model.state.gameelement.StateTags.Y_GOAL_POSITION, model.state.gameelement.StateTags.Y_POSITION, model.state.gameelement.StateTags.Y_SPAWN_OFFSET, and model.state.gameelement.StateTags.Y_TEMP_GOAL_POSITION.
Referenced by application.Pong.hardCodeAGame().
SelectableGameElementState application.Pong.createPaddle (double x, double y, int teamID) throws Exception private
Definition at line 289 of file Pong.java.
References engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.ACT_ON_OBJECTS_ACTION, model.state.gameelement.GameElementState.addAction(), model.state.gameelement.GameElementState.addType(), model.state.gameelement.StateTags.CURRENT_ACTION, application.Pong.generateNullAnimatorState(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL, model.state.gameelement.StateTags.MOVEMENT_SPEED, model.state.gameelement.DrawableGameElementState.myAnimatorState, model.state.gameelement.GameElementState.myAttributes, model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), model.state.gameelement.StateTags.TEAM_COLOR, model.state.gameelement.StateTags.X_GOAL_POSITION, model.state.gameelement.StateTags.X_POSITION, model.state.gameelement.StateTags.X_TEMP_GOAL_POSITION, model.state.gameelement.StateTags.Y_GOAL_POSITION, model.state.gameelement.StateTags.Y_POSITION, and model.state.gameelement.StateTags.Y_TEMP_GOAL_POSITION.
Referenced by application.Pong.hardCodeAGame().
AnimatorState application.Pong.generateNullAnimatorState () private
Definition at line 217 of file Pong.java.
References engine.visuals.elementVisuals.animations.AnimationTag.DO_NOTHING.
Referenced by application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalDisplayMarker(), application.Pong.createGoalRegion(), and application.Pong.createPaddle().
Engine application.Pong.hardCodeAGame () throws Exception private
Definition at line 53 of file Pong.java.
References engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.ACT_ON_OBJECTS_ACTION, model.state.gameelement.GameElementState.addAction(), model.state.GameState.addCampaign(), model.state.LevelState.addGoal(), model.state.CampaignState.addLevel(), model.GameUniverse.addSelectableGameElementState(), model.state.LevelState.addUnit(), model.state.gameelement.StateTags.BACKGROUND_PATH, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.BUTTON, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.CHECK_ATTR_SET_ATTR_ACTION, engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.COLLISION, application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalDisplayMarker(), application.Pong.createGoalRegion(), application.Pong.createPaddle(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.FOCUSED, model.MainModel.getGameUniverse(), model.MainModel.getLevel(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionType.INTERNAL, model.state.gameelement.StateTags.IS_SELECTED, model.state.gameelement.StateTags.LAST_BUTTON_CLICKED_ID, model.state.gameelement.StateTags.LEVEL_HEIGHT, model.state.gameelement.StateTags.LEVEL_WIDTH, model.MainModel.loadGame(), model.state.gameelement.StateTags.MOVEMENT_SPEED, model.state.LevelState.myAttributes, model.state.gameelement.GameElementState.myAttributes, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.OBJECT_TYPE_CHECK_ACTION, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.PERFORM_CALCULATION_ON_VALUE, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.PLAYER_ATTRIBUTE_CONDITION, model.state.gameelement.StateTags.RESOURCES, model.MainModel.saveGame(), model.state.gameelement.DrawableGameElementState.setBounds(), model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), model.state.gameelement.StateTags.TEAM_COLOR, model.state.gameelement.StateTags.X_VELOCITY, and model.state.gameelement.StateTags.Y_VELOCITY.
Referenced by application.Pong.start().
static void application.Pong.main (String[] args) static
Definition at line 314 of file Pong.java.
void application.Pong.start (Stage primaryStage)
Definition at line 38 of file Pong.java.
References engine.visuals.Dimension.getHeight(), engine.Engine.getScene(), application.Pong.hardCodeAGame(), engine.Engine.play(), and application.Pong.screenSize.
Member Data Documentation
final java.awt.Dimension application.Pong.screenSize = Toolkit.getDefaultToolkit().getScreenSize() static
Definition at line 34 of file Pong.java.
Referenced by application.Pong.start().
final int application.Pong.shittyWidth = 1000 static
Definition at line 35 of file Pong.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/application/Pong.java