voogasalad_TheException: editor.TabViewController Class Reference
editor.TabViewController Class Reference
Classes
class TriggerPair
Public Member Functions
void update ()
void init ()
Node getRoot ()
Public Member Functions inherited from view.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
abstract void update ()
Private Member Functions
Consumer< Consumer< WizardData > > launchNestedWizard ()
void updateLevelTriggersView ()
Private Attributes
VBox levelTrigger
LevelTriggersViewController levelTriggerController
BorderPane gameRunnerPane
BorderPane tabPane
Static Private Attributes
static final String TRIGGER_WIZARD = "/editor/wizards/guipanes/TriggerWizard.fxml"
Additional Inherited Members
Protected Member Functions inherited from view.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.GUIContainer
MainModel myMainModel
Detailed Description
Author
Jonathan Tseng
Nishad Agrawal
Definition at line 24 of file TabViewController.java.
Member Function Documentation
Node editor.TabViewController.getRoot ()
Implements view.GUIController.
Definition at line 81 of file TabViewController.java.
References editor.TabViewController.tabPane.
Referenced by editor.EditorScreen.createNewTab().
void editor.TabViewController.init ()
Definition at line 75 of file TabViewController.java.
References editor.TabViewController.launchNestedWizard(), and editor.LevelTriggersViewController.setButtonAction().
Consumer<Consumer<WizardData> > editor.TabViewController.launchNestedWizard () private
Definition at line 37 of file TabViewController.java.
References gamemodel.MainModel.addGoal(), editor.wizards.Wizard.getStage(), view.WizardUtility.loadWizard(), view.GUIContainer.myMainModel, and editor.wizards.Wizard.setSubmit().
Referenced by editor.TabViewController.init().
void editor.TabViewController.update ()
Definition at line 50 of file TabViewController.java.
References editor.TabViewController.updateLevelTriggersView().
void editor.TabViewController.updateLevelTriggersView () private
Definition at line 55 of file TabViewController.java.
References gamemodel.MainModel.getCurrentLevel(), game_engine.gameRepresentation.stateRepresentation.LevelState.getGoals(), view.GUIContainer.myMainModel, and editor.LevelTriggersViewController.updateTriggerList().
Referenced by editor.TabViewController.update().
Member Data Documentation
BorderPane editor.TabViewController.gameRunnerPane private
Definition at line 31 of file TabViewController.java.
VBox editor.TabViewController.levelTrigger private
Definition at line 27 of file TabViewController.java.
LevelTriggersViewController editor.TabViewController.levelTriggerController private
Definition at line 29 of file TabViewController.java.
BorderPane editor.TabViewController.tabPane private
Definition at line 33 of file TabViewController.java.
Referenced by editor.TabViewController.getRoot().
final String editor.TabViewController.TRIGGER_WIZARD = "/editor/wizards/guipanes/TriggerWizard.fxml" static private
Definition at line 35 of file TabViewController.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/TabViewController.java