voogasalad_TheException: resources.processing.ColorMaskExtractor Class Reference
resources.processing.ColorMaskExtractor Class Reference
Public Member Functions
ColorMaskExtractor (BufferedImage image)
void extractColorMask () throws IOException
void mutateColorMask (int desiredHue)
Static Public Member Functions
static void main (String[] args) throws IOException
static void printColorValues (BufferedImage img)
Public Attributes
BufferedImage colorMask
BufferedImage mutatedMask
BufferedImage spritesheetColorRemoved
Private Attributes
BufferedImage originalImage
Detailed Description
Definition at line 17 of file ColorMaskExtractor.java.
Constructor & Destructor Documentation
resources.processing.ColorMaskExtractor.ColorMaskExtractor (BufferedImage image)
Definition at line 24 of file ColorMaskExtractor.java.
Member Function Documentation
void resources.processing.ColorMaskExtractor.extractColorMask () throws IOException
Definition at line 65 of file ColorMaskExtractor.java.
References resources.processing.SpriteSheetCreationUtility.toBufferedImage().
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
static void resources.processing.ColorMaskExtractor.main (String[] args) throws IOException static
Definition at line 28 of file ColorMaskExtractor.java.
References resources.processing.ColorMaskExtractor.printColorValues().
void resources.processing.ColorMaskExtractor.mutateColorMask (int desiredHue)
Definition at line 105 of file ColorMaskExtractor.java.
References resources.processing.SpriteSheetCreationUtility.toBufferedImage().
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
static void resources.processing.ColorMaskExtractor.printColorValues (BufferedImage img) static
Definition at line 34 of file ColorMaskExtractor.java.
Referenced by resources.processing.ColorMaskExtractor.main().
Member Data Documentation
BufferedImage resources.processing.ColorMaskExtractor.colorMask
Definition at line 19 of file ColorMaskExtractor.java.
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
BufferedImage resources.processing.ColorMaskExtractor.mutatedMask
Definition at line 20 of file ColorMaskExtractor.java.
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
BufferedImage resources.processing.ColorMaskExtractor.originalImage private
Definition at line 22 of file ColorMaskExtractor.java.
BufferedImage resources.processing.ColorMaskExtractor.spritesheetColorRemoved
Definition at line 21 of file ColorMaskExtractor.java.
Referenced by resources.processing.SpriteSheetCreationUtility.createSpriteSheet().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/resources/processing/ColorMaskExtractor.java