voogasalad_TheException: game_engine.UI.InputManager Class Reference
game_engine.UI.InputManager Class Reference
Public Member Functions
InputManager ()
void inputOccurred (Event e)
void inputOccurred (MouseEvent e, double mapTranslationX, double mapTranslationY, boolean drag)
Event getEvent ()
void addClickObserver (Observer o)
void addKeyboardObserver (Observer o)
void addMouseDragObserver (Observer o)
Private Attributes
Event e
ClickManager myClickManager
KeyboardManager myKeyboardManager
MouseDragManager myMouseDragManager
Detailed Description
Definition at line 8 of file InputManager.java.
Constructor & Destructor Documentation
game_engine.UI.InputManager.InputManager ()
Definition at line 14 of file InputManager.java.
Member Function Documentation
void game_engine.UI.InputManager.addClickObserver (Observer o)
adds an observer to the clicks on the scene
Parameters
o the object that wants to be notified about the location on the map that was clicked and which button was used
Definition at line 45 of file InputManager.java.
Referenced by game_engine.visuals.ScrollablePane.ScrollablePane(), game_engine.Engine.selectLevel(), and game_engine.Engine.updateGameLoop().
void game_engine.UI.InputManager.addKeyboardObserver (Observer o)
adds an observer to the keys pressed while focused on the scene
Parameters
o the object that wants to be notified about the key that was pressed
Definition at line 55 of file InputManager.java.
Referenced by game_engine.Engine.selectLevel(), and game_engine.Engine.updateGameLoop().
void game_engine.UI.InputManager.addMouseDragObserver (Observer o)
Definition at line 59 of file InputManager.java.
Referenced by game_engine.visuals.ScrollablePane.ScrollablePane().
Event game_engine.UI.InputManager.getEvent ()
Definition at line 35 of file InputManager.java.
References game_engine.UI.InputManager.e.
void game_engine.UI.InputManager.inputOccurred (Event e)
Definition at line 20 of file InputManager.java.
References game_engine.UI.InputManager.e.
Referenced by game_engine.visuals.ScrollablePane.initializeHandlers(), and game_engine.visuals.ScrollablePane.mousePressed().
void game_engine.UI.InputManager.inputOccurred (MouseEvent e, double mapTranslationX, double mapTranslationY, boolean drag)
Definition at line 26 of file InputManager.java.
References game_engine.UI.MouseManager.clicked().
Member Data Documentation
Event game_engine.UI.InputManager.e private
Definition at line 9 of file InputManager.java.
Referenced by game_engine.UI.InputManager.getEvent(), and game_engine.UI.InputManager.inputOccurred().
ClickManager game_engine.UI.InputManager.myClickManager private
Definition at line 10 of file InputManager.java.
KeyboardManager game_engine.UI.InputManager.myKeyboardManager private
Definition at line 11 of file InputManager.java.
MouseDragManager game_engine.UI.InputManager.myMouseDragManager private
Definition at line 12 of file InputManager.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/UI/InputManager.java