voogasalad_TheException: util.DefaultResource Class Reference
util.DefaultResource Class Reference
Static Public Attributes
static final String LIBRARY_DIRECTORY = "src/resources/img"
Package Functions
void setDefaults (String destination) throws Exception
Private Member Functions
void copyResources (String filePath) throws Exception
Detailed Description
Class to perform copying of default library resources to game
Author
Rahul
Definition at line 14 of file DefaultResource.java.
Member Function Documentation
void util.DefaultResource.copyResources (String filePath) throws Exception private
Definition at line 18 of file DefaultResource.java.
Referenced by util.DefaultResource.setDefaults().
void util.DefaultResource.setDefaults (String destination) throws Exception package
Definition at line 24 of file DefaultResource.java.
References util.DefaultResource.copyResources().
Referenced by util.SaveLoadUtility.save().
Member Data Documentation
final String util.DefaultResource.LIBRARY_DIRECTORY = "src/resources/img" static
Definition at line 16 of file DefaultResource.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/util/DefaultResource.java