voogasalad_TheException: gamemodel.GameUniverse Class Reference
gamemodel.GameUniverse Class Reference
Public Member Functions
GameUniverse ()
void addGameElementState (GameElementState ges)
void addDrawableGameElementState (DrawableGameElementState dges)
void addSelectableGameElementState (SelectableGameElementState sges)
Set< GameElementState > getGameElementStates ()
Set< DrawableGameElementState > getDrawableGameElementStates ()
Set< SelectableGameElementState > getSelectableGameElementStates ()
void removeSelectableGameElementState (SelectableGameElementState sges)
void removeDrawableGameElementState (DrawableGameElementState dges)
void removeGameElementState (GameElementState ges)
GameElementState getGameElementState (String elementName)
DrawableGameElementState getDrawableGameElementState (String elementName)
SelectableGameElementState getSelectableGameElementState (String elementName)
void addNumericalAttribute (Attribute< Number > number)
void addStringAttribute (Attribute< String > string)
Set< Attribute< Number > > getNumericalAttributes ()
Set< Attribute< String > > getStringAttributes ()
Private Attributes
Set< Attribute< Number > > myNumericalAttributes
Set< Attribute< String > > myStringAttributes
Set< GameElementState > myGameElementStates
Set< DrawableGameElementState > myDrawableGameElementStates
Set< SelectableGameElementState > mySelectableGameElementStates
Detailed Description
Class that represents all possible elements that could make up a game. This is a passive data structure/wrapper class** with no behavior.
Author
Jonathan Tseng, Rahul
Definition at line 23 of file GameUniverse.java.
Constructor & Destructor Documentation
gamemodel.GameUniverse.GameUniverse ()
Definition at line 30 of file GameUniverse.java.
Member Function Documentation
void gamemodel.GameUniverse.addDrawableGameElementState (DrawableGameElementState dges)
Definition at line 42 of file GameUniverse.java.
Referenced by gamemodel.MainModel.createDrawableGameElement().
void gamemodel.GameUniverse.addGameElementState (GameElementState ges)
Definition at line 38 of file GameUniverse.java.
Referenced by gamemodel.MainModel.createGameElement().
void gamemodel.GameUniverse.addNumericalAttribute (Attribute< Number > number)
Definition at line 97 of file GameUniverse.java.
void gamemodel.GameUniverse.addSelectableGameElementState (SelectableGameElementState sges)
Definition at line 46 of file GameUniverse.java.
Referenced by gamemodel.MainModel.createSelectableGameElement(), and game_engine.stateManaging.GameElementManager.main().
void gamemodel.GameUniverse.addStringAttribute (Attribute< String > string)
Definition at line 101 of file GameUniverse.java.
DrawableGameElementState gamemodel.GameUniverse.getDrawableGameElementState (String elementName)
Definition at line 82 of file GameUniverse.java.
Referenced by game_engine.elementFactories.GameElementFactory.createDrawableGameElement().
Set<DrawableGameElementState> gamemodel.GameUniverse.getDrawableGameElementStates ()
Definition at line 54 of file GameUniverse.java.
Referenced by editor.EditorScreen.updateAccordion().
GameElementState gamemodel.GameUniverse.getGameElementState (String elementName)
Definition at line 74 of file GameUniverse.java.
Referenced by game_engine.elementFactories.GameElementFactory.createGameElement().
Set<GameElementState> gamemodel.GameUniverse.getGameElementStates ()
Definition at line 50 of file GameUniverse.java.
References game_engine.elementFactories.DeepCopy.deepCopy().
Set<Attribute<Number> > gamemodel.GameUniverse.getNumericalAttributes ()
Definition at line 105 of file GameUniverse.java.
References gamemodel.GameUniverse.myNumericalAttributes.
SelectableGameElementState gamemodel.GameUniverse.getSelectableGameElementState (String elementName)
Definition at line 89 of file GameUniverse.java.
Referenced by game_engine.elementFactories.GameElementFactory.createSelectableGameElement().
Set<SelectableGameElementState> gamemodel.GameUniverse.getSelectableGameElementStates ()
Definition at line 58 of file GameUniverse.java.
References game_engine.elementFactories.DeepCopy.deepCopy().
Set<Attribute<String> > gamemodel.GameUniverse.getStringAttributes ()
Definition at line 109 of file GameUniverse.java.
References gamemodel.GameUniverse.myStringAttributes.
void gamemodel.GameUniverse.removeDrawableGameElementState (DrawableGameElementState dges)
Definition at line 66 of file GameUniverse.java.
void gamemodel.GameUniverse.removeGameElementState (GameElementState ges)
Definition at line 70 of file GameUniverse.java.
void gamemodel.GameUniverse.removeSelectableGameElementState (SelectableGameElementState sges)
Definition at line 62 of file GameUniverse.java.
Member Data Documentation
Set<DrawableGameElementState> gamemodel.GameUniverse.myDrawableGameElementStates private
Definition at line 27 of file GameUniverse.java.
Set<GameElementState> gamemodel.GameUniverse.myGameElementStates private
Definition at line 26 of file GameUniverse.java.
Set<Attribute<Number> > gamemodel.GameUniverse.myNumericalAttributes private
Definition at line 24 of file GameUniverse.java.
Referenced by gamemodel.GameUniverse.getNumericalAttributes().
Set<SelectableGameElementState> gamemodel.GameUniverse.mySelectableGameElementStates private
Definition at line 28 of file GameUniverse.java.
Set<Attribute<String> > gamemodel.GameUniverse.myStringAttributes private
Definition at line 25 of file GameUniverse.java.
Referenced by gamemodel.GameUniverse.getStringAttributes().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/gamemodel/GameUniverse.java