voogasalad_TheException: model.GameElementStateFactory Class Reference
model.GameElementStateFactory Class Reference
Static Public Member Functions
static GameElementState createGameElementState (WizardData data)
static DrawableGameElementState createDrawableGameElementState (WizardData data)
static SelectableGameElementState createSelectableGameElementState (WizardData data)
static GameElementState createGoal (WizardData data)
Static Private Member Functions
static ActionWrapper createActionWrapper (WizardData data)
static DrawableGameElementState addVisuals (WizardData data, DrawableGameElementState state)
static void createAttributeDisplayerState (WizardData data, DrawableGameElementState state)
static double[] createBounds (WizardData data, WizardType boundsType)
static GameElementState addEssentials (GameElementState state, WizardData data)
static void addToState (BiConsumer< String, String > cons, WizardData data, WizardType type, WizardDataType...dataTypes)
Detailed Description
Factory that creates a SavableGameElementState based on the info args
Author
Nishad Agrawal, Jonathan Tseng
Definition at line 24 of file GameElementStateFactory.java.
Member Function Documentation
static GameElementState model.GameElementStateFactory.addEssentials (GameElementState state, WizardData data) static private
Definition at line 101 of file GameElementStateFactory.java.
References model.state.gameelement.GameElementState.addAction(), model.GameElementStateFactory.addToState(), model.data.WizardDataType.ATTRIBUTE, model.state.gameelement.GameElementState.attributes, model.GameElementStateFactory.createActionWrapper(), model.data.WizardData.getValueByKey(), model.data.WizardData.getWizardDataByType(), model.data.WizardDataType.NAME, model.state.gameelement.StateTags.NAME, model.data.WizardType.NUMBER_ATTRIBUTE, model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), model.data.WizardType.STRING_ATTRIBUTE, model.data.WizardType.TRIGGER, and model.data.WizardDataType.VALUE.
Referenced by model.GameElementStateFactory.createDrawableGameElementState(), model.GameElementStateFactory.createGameElementState(), and model.GameElementStateFactory.createSelectableGameElementState().
static void model.GameElementStateFactory.addToState (BiConsumer< String, String > cons, WizardData data, WizardType type, WizardDataType... dataTypes) static private
Definition at line 121 of file GameElementStateFactory.java.
References model.data.WizardData.getWizardDataByType().
Referenced by model.GameElementStateFactory.addEssentials().
static DrawableGameElementState model.GameElementStateFactory.addVisuals (WizardData data, DrawableGameElementState state) static private
Definition at line 57 of file GameElementStateFactory.java.
References model.data.WizardType.BOUNDS, model.AnimatorStateFactory.createAnimatorState(), model.GameElementStateFactory.createAttributeDisplayerState(), model.GameElementStateFactory.createBounds(), model.state.gameelement.DrawableGameElementState.myAnimatorState, model.state.gameelement.DrawableGameElementState.setBounds(), model.state.gameelement.DrawableGameElementState.setVisionBounds(), and model.data.WizardType.VISION_BOUNDS.
Referenced by model.GameElementStateFactory.createDrawableGameElementState(), and model.GameElementStateFactory.createSelectableGameElementState().
static ActionWrapper model.GameElementStateFactory.createActionWrapper (WizardData data) static private
Definition at line 49 of file GameElementStateFactory.java.
References model.data.WizardDataType.ACTION, model.data.WizardDataType.ACTION_PARAMETERS, model.data.WizardDataType.ACTIONTYPE, and model.data.WizardData.getValueByKey().
Referenced by model.GameElementStateFactory.addEssentials(), and model.GameElementStateFactory.createGoal().
static void model.GameElementStateFactory.createAttributeDisplayerState (WizardData data, DrawableGameElementState state) static private
Definition at line 66 of file GameElementStateFactory.java.
References model.state.gameelement.DrawableGameElementState.addAttributeDisplayerState(), model.data.WizardDataType.ATTRIBUTE, model.data.WizardData.getWizardDataByType(), model.data.WizardType.WIDGET, model.data.WizardDataType.WIDGET_PARAMETERS, and model.data.WizardDataType.WIDGET_TYPE.
Referenced by model.GameElementStateFactory.addVisuals().
static double [] model.GameElementStateFactory.createBounds (WizardData data, WizardType boundsType) static private
Definition at line 86 of file GameElementStateFactory.java.
References model.data.WizardDataType.BOUND_VALUES, and model.data.WizardData.getWizardDataByType().
Referenced by model.GameElementStateFactory.addVisuals().
static DrawableGameElementState model.GameElementStateFactory.createDrawableGameElementState (WizardData data) static
Definition at line 30 of file GameElementStateFactory.java.
References model.GameElementStateFactory.addEssentials(), and model.GameElementStateFactory.addVisuals().
Referenced by model.MainModel.createDrawableGameElementState().
static GameElementState model.GameElementStateFactory.createGameElementState (WizardData data) static
Definition at line 26 of file GameElementStateFactory.java.
References model.GameElementStateFactory.addEssentials().
Referenced by model.MainModel.createGameElementState().
static GameElementState model.GameElementStateFactory.createGoal (WizardData data) static
Definition at line 43 of file GameElementStateFactory.java.
References model.state.gameelement.GameElementState.addAction(), and model.GameElementStateFactory.createActionWrapper().
Referenced by model.MainModel.createGoal().
static SelectableGameElementState model.GameElementStateFactory.createSelectableGameElementState (WizardData data) static
Definition at line 37 of file GameElementStateFactory.java.
References model.GameElementStateFactory.addEssentials(), and model.GameElementStateFactory.addVisuals().
Referenced by model.MainModel.createSelectableGameElementState().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/GameElementStateFactory.java