voogasalad_TheException: game_engine.visuals.ScrollableScene Class Reference
game_engine.visuals.ScrollableScene Class Reference
Public Member Functions
ScrollableScene (Group root, double width, double height)
ScrollableBackground getBackground ()
void update ()
void addBoxObserver (Observer o)
void addClickObserver (Observer o)
void addKeyboardObserver (Observer o)
Static Public Attributes
static final double SLOW_SCROLL_BOUNDARY = 75
static final double FAST_SCROLL_BOUNDARY = 30
static final double FAST_SPEED = 15
static final double SLOW_SPEED = 7
static final double FIELD_WIDTH = 2000
static final double FIELD_HEIGHT = 2000
Package Attributes
double pressedY
Private Member Functions
void initializeHandlers ()
Private Attributes
ScrollableBackground myBackground
ClickManager myClickManager
SelectionBox mySelectionBox
KeyboardManager myKeyboardManager
Rectangle myBox
double myScreenHeight
double myScreenWidth
double pressedX
Detailed Description
Basically the map. JavaFX Scene node that contains the eventHandlers necessary to scroll the map and register clicks.
Author
John
Definition at line 24 of file ScrollableScene.java.
Constructor & Destructor Documentation
game_engine.visuals.ScrollableScene.ScrollableScene (Group root, double width, double height)
<<<<<<< HEAD Create a scrollable scene
Parameters
root the root group for the scene
width the width of the scene
height the height of the scene
Creates a new ScrollableScene for the map.
Parameters
root the group of elements to add to the Scene initially. If no objects have been created yet to add, just add an empty new Group()
width the width of the map (ideally larger than the screen width)
height the height of the map (ideally larger than the screen height)
0801fd70045877fb15b0936ba684c4c2ac0b0f9c
Definition at line 57 of file ScrollableScene.java.
References game_engine.visuals.UI.SelectionBox.getBox(), and game_engine.visuals.ScrollableScene.initializeHandlers().
Member Function Documentation
void game_engine.visuals.ScrollableScene.addBoxObserver (Observer o)
adds an observer to the selection boxes drawn on this scene
Parameters
o the object that wants to be notified about the location on the map the box was drawn
Definition at line 233 of file ScrollableScene.java.
Referenced by game_engine.visuals.VisualManager.addBoxObserver().
void game_engine.visuals.ScrollableScene.addClickObserver (Observer o)
adds an observer to the clicks on the scene
Parameters
o the object that wants to be notified about the location on the map that was clicked and which button was used
Definition at line 243 of file ScrollableScene.java.
Referenced by game_engine.visuals.VisualManager.addClickObserver().
void game_engine.visuals.ScrollableScene.addKeyboardObserver (Observer o)
adds an observer to the keys pressed while focused on the scene
Parameters
o the object that wants to be notified about the key that was pressed
Definition at line 253 of file ScrollableScene.java.
Referenced by game_engine.visuals.VisualManager.addKeyboardObserver().
ScrollableBackground game_engine.visuals.ScrollableScene.getBackground ()
<<<<<<< HEAD
the background of the scrollable scene
gets the background map that objects actually get added to
Returns
0801fd70045877fb15b0936ba684c4c2ac0b0f9c
Definition at line 79 of file ScrollableScene.java.
References game_engine.visuals.ScrollableScene.myBackground.
Referenced by game_engine.visuals.VisualManager.VisualManager().
void game_engine.visuals.ScrollableScene.initializeHandlers () private
<<<<<<< HEAD
Add all the necessary click and scroll handlers to the scene
initializes the handlers that respond to JavaFX events necessary for scrolling and registering clicks/ drags
0801fd70045877fb15b0936ba684c4c2ac0b0f9c
Definition at line 91 of file ScrollableScene.java.
References game_engine.visuals.UI.ClickManager.clicked(), game_engine.visuals.UI.KeyboardManager.keyPressed(), game_engine.visuals.ScrollableScene.myScreenHeight, game_engine.visuals.ScrollableScene.myScreenWidth, game_engine.visuals.ScrollableScene.pressedX, game_engine.visuals.ScrollableScene.pressedY, game_engine.visuals.UI.SelectionBox.released(), game_engine.visuals.UI.SelectionBox.resetBox(), game_engine.visuals.UI.SelectionBox.setLocation(), game_engine.visuals.ScrollableBackground.setXScrollSpeed(), and game_engine.visuals.ScrollableBackground.setYScrollSpeed().
Referenced by game_engine.visuals.ScrollableScene.ScrollableScene().
void game_engine.visuals.ScrollableScene.update ()
updates the background to scroll and draw selection boxes
Definition at line 223 of file ScrollableScene.java.
References game_engine.visuals.ScrollableBackground.update().
Referenced by game_engine.visuals.VisualManager.update().
Member Data Documentation
final double game_engine.visuals.ScrollableScene.FAST_SCROLL_BOUNDARY = 30 static
Definition at line 26 of file ScrollableScene.java.
final double game_engine.visuals.ScrollableScene.FAST_SPEED = 15 static
Definition at line 27 of file ScrollableScene.java.
final double game_engine.visuals.ScrollableScene.FIELD_HEIGHT = 2000 static
Definition at line 30 of file ScrollableScene.java.
Referenced by application.ShittyMain.hardCodeAGame().
final double game_engine.visuals.ScrollableScene.FIELD_WIDTH = 2000 static
Definition at line 29 of file ScrollableScene.java.
Referenced by application.ShittyMain.hardCodeAGame().
ScrollableBackground game_engine.visuals.ScrollableScene.myBackground private
Definition at line 32 of file ScrollableScene.java.
Referenced by game_engine.visuals.ScrollableScene.getBackground().
Rectangle game_engine.visuals.ScrollableScene.myBox private
Definition at line 36 of file ScrollableScene.java.
ClickManager game_engine.visuals.ScrollableScene.myClickManager private
Definition at line 33 of file ScrollableScene.java.
KeyboardManager game_engine.visuals.ScrollableScene.myKeyboardManager private
Definition at line 35 of file ScrollableScene.java.
double game_engine.visuals.ScrollableScene.myScreenHeight private
Definition at line 37 of file ScrollableScene.java.
Referenced by game_engine.visuals.ScrollableScene.initializeHandlers().
double game_engine.visuals.ScrollableScene.myScreenWidth private
Definition at line 38 of file ScrollableScene.java.
Referenced by game_engine.visuals.ScrollableScene.initializeHandlers().
SelectionBox game_engine.visuals.ScrollableScene.mySelectionBox private
Definition at line 34 of file ScrollableScene.java.
double game_engine.visuals.ScrollableScene.pressedX private
Definition at line 39 of file ScrollableScene.java.
Referenced by game_engine.visuals.ScrollableScene.initializeHandlers().
double game_engine.visuals.ScrollableScene.pressedY package
Definition at line 39 of file ScrollableScene.java.
Referenced by game_engine.visuals.ScrollableScene.initializeHandlers().
final double game_engine.visuals.ScrollableScene.SLOW_SCROLL_BOUNDARY = 75 static
Definition at line 25 of file ScrollableScene.java.
final double game_engine.visuals.ScrollableScene.SLOW_SPEED = 7 static
Definition at line 28 of file ScrollableScene.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/ScrollableScene.java