voogasalad_TheException: game_engine.visuals.ScrollableBackground Class Reference
game_engine.visuals.ScrollableBackground Class Reference
Public Member Functions
ScrollableBackground (double screenWidth, double screenHeight, double xBoundary, double yBoundary)
void addObjects (Group g)
void update (double screenWidth, double screenHeight)
void setXScrollSpeed (double speed)
void setYScrollSpeed (double speed)
void update (Observable o, Object arg)
Package Attributes
double myYScrollSpeed
double myYBoundary
Private Member Functions
void retractOutOfBoundsScroll (double screenWidth, double screenHeight)
Private Attributes
double myXScrollSpeed
double myXBoundary
Detailed Description
A scrollablebackground pane for the game
Author
John
Definition at line 16 of file ScrollableBackground.java.
Constructor & Destructor Documentation
game_engine.visuals.ScrollableBackground.ScrollableBackground (double screenWidth, double screenHeight, double xBoundary, double yBoundary)
Create the scrollable background
Parameters
screenWidth
screenHeight
xBoundary the maximum X value that can be scrolled to
yBoundary the maximum Y value that can be scrolled to
Definition at line 29 of file ScrollableBackground.java.
Member Function Documentation
void game_engine.visuals.ScrollableBackground.addObjects (Group g)
Add objects to be displayed in the scrollablebackground
Parameters
g a group of the objects to add
Definition at line 48 of file ScrollableBackground.java.
Referenced by game_engine.visuals.VisualManager.addObjects().
void game_engine.visuals.ScrollableBackground.retractOutOfBoundsScroll (double screenWidth, double screenHeight) private
Undo scrolling if we're going out of bounds
Definition at line 70 of file ScrollableBackground.java.
Referenced by game_engine.visuals.ScrollableBackground.update().
void game_engine.visuals.ScrollableBackground.setXScrollSpeed (double speed)
Definition at line 79 of file ScrollableBackground.java.
Referenced by game_engine.visuals.ScrollablePane.mousePressed(), game_engine.visuals.ScrollablePane.setScrollSpeed(), and game_engine.visuals.ScrollableBackground.update().
void game_engine.visuals.ScrollableBackground.setYScrollSpeed (double speed)
Definition at line 83 of file ScrollableBackground.java.
Referenced by game_engine.visuals.ScrollablePane.mousePressed(), game_engine.visuals.ScrollablePane.setScrollSpeed(), and game_engine.visuals.ScrollableBackground.update().
void game_engine.visuals.ScrollableBackground.update (double screenWidth, double screenHeight)
Update the view of the background based on the current scroll speed
Definition at line 55 of file ScrollableBackground.java.
References game_engine.visuals.ScrollableBackground.retractOutOfBoundsScroll(), game_engine.visuals.ScrollableBackground.setXScrollSpeed(), and game_engine.visuals.ScrollableBackground.setYScrollSpeed().
Referenced by game_engine.visuals.ScrollablePane.update().
void game_engine.visuals.ScrollableBackground.update (Observable o, Object arg)
Definition at line 88 of file ScrollableBackground.java.
Member Data Documentation
double game_engine.visuals.ScrollableBackground.myXBoundary private
Definition at line 19 of file ScrollableBackground.java.
double game_engine.visuals.ScrollableBackground.myXScrollSpeed private
Definition at line 18 of file ScrollableBackground.java.
double game_engine.visuals.ScrollableBackground.myYBoundary package
Definition at line 19 of file ScrollableBackground.java.
double game_engine.visuals.ScrollableBackground.myYScrollSpeed package
Definition at line 18 of file ScrollableBackground.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/ScrollableBackground.java