voogasalad_TheException: editor.wizards.DrawableGameElementWizard Class Reference
editor.wizards.DrawableGameElementWizard Class Reference
Public Member Functions
void initialize ()
boolean checkCanSave ()
void updateData ()
Public Member Functions inherited from editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
WizardData getWizardData ()
void setErrorMesssage (String error)
void setStage (Stage s)
Stage getStage ()
Private Member Functions
void launchTriggerEditor ()
void launchStringAttributeEditor ()
void launchNumberAttributeEditor ()
void launchNestedWizard (String s)
void loadImage ()
void createTextFieldListeners ()
void createSliderListeners ()
Private Attributes
TextField name
Button trigger
Button stringAttribute
Button numberAttribute
Button image
Group spritesheet
ScrollPane imageScroll
Slider frameWidth
TextField frameWidthText
Slider frameHeight
TextField frameHeightText
TextField numRows
TextField startFrame
TextField stopFrame
CheckBox animationRepeat
ImageView imageView
GridLines gridLines
String imagePath
Static Private Attributes
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
static final String NUM_ATTR_WIZARD
static final String STRING_ATTR_WIZARD
static final String TRIGGER_WIZARD = "/editor/wizards/guipanes/TriggerWizard.fxml"
Additional Inherited Members
Protected Member Functions inherited from editor.wizards.Wizard
void addToData (String key, String value)
void addWizardData (WizardData wizData)
void setDataName (String name)
Protected Attributes inherited from editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Detailed Description
Author
Joshua, Nishad
Definition at line 28 of file DrawableGameElementWizard.java.
Member Function Documentation
boolean editor.wizards.DrawableGameElementWizard.checkCanSave ()
Definition at line 184 of file DrawableGameElementWizard.java.
void editor.wizards.DrawableGameElementWizard.createSliderListeners () private
Definition at line 168 of file DrawableGameElementWizard.java.
References editor.wizards.GridLines.changeSize(), editor.wizards.GridLines.getFrameX(), and editor.wizards.GridLines.getFrameY().
Referenced by editor.wizards.DrawableGameElementWizard.initialize().
void editor.wizards.DrawableGameElementWizard.createTextFieldListeners () private
Definition at line 155 of file DrawableGameElementWizard.java.
Referenced by editor.wizards.DrawableGameElementWizard.initialize().
void editor.wizards.DrawableGameElementWizard.initialize ()
Binds all the listeners to the scene
Implements view.GUIController.
Definition at line 144 of file DrawableGameElementWizard.java.
References editor.wizards.DrawableGameElementWizard.createSliderListeners(), editor.wizards.DrawableGameElementWizard.createTextFieldListeners(), editor.wizards.DrawableGameElementWizard.launchNumberAttributeEditor(), editor.wizards.DrawableGameElementWizard.launchStringAttributeEditor(), editor.wizards.DrawableGameElementWizard.launchTriggerEditor(), and editor.wizards.DrawableGameElementWizard.loadImage().
void editor.wizards.DrawableGameElementWizard.launchNestedWizard (String s) private
Definition at line 96 of file DrawableGameElementWizard.java.
References editor.wizards.Wizard.addWizardData(), editor.wizards.Wizard.getStage(), view.WizardUtility.loadWizard(), and editor.wizards.Wizard.setSubmit().
Referenced by editor.wizards.DrawableGameElementWizard.launchNumberAttributeEditor(), editor.wizards.DrawableGameElementWizard.launchStringAttributeEditor(), and editor.wizards.DrawableGameElementWizard.launchTriggerEditor().
void editor.wizards.DrawableGameElementWizard.launchNumberAttributeEditor () private
Launches a Nuumber Attribute Wizard
Definition at line 92 of file DrawableGameElementWizard.java.
References editor.wizards.DrawableGameElementWizard.launchNestedWizard().
Referenced by editor.wizards.DrawableGameElementWizard.initialize().
void editor.wizards.DrawableGameElementWizard.launchStringAttributeEditor () private
Launches a String Attribute Wizard
Definition at line 84 of file DrawableGameElementWizard.java.
References editor.wizards.DrawableGameElementWizard.launchNestedWizard().
Referenced by editor.wizards.DrawableGameElementWizard.initialize().
void editor.wizards.DrawableGameElementWizard.launchTriggerEditor () private
Launches a TriggerEditorWizard
Definition at line 76 of file DrawableGameElementWizard.java.
References editor.wizards.DrawableGameElementWizard.launchNestedWizard().
Referenced by editor.wizards.DrawableGameElementWizard.initialize().
void editor.wizards.DrawableGameElementWizard.loadImage () private
Fired when the user uploads a new picture
Credit for the buffered image code goes to StackOverflow user mathew11
Definition at line 111 of file DrawableGameElementWizard.java.
Referenced by editor.wizards.DrawableGameElementWizard.initialize().
void editor.wizards.DrawableGameElementWizard.updateData ()
Definition at line 192 of file DrawableGameElementWizard.java.
References editor.wizards.Wizard.addToData(), gamemodel.GameElementStateFactory.ANIMATION_REPEAT, gamemodel.GameElementStateFactory.DRAWABLE_GAME_ELEMENT, gamemodel.GameElementStateFactory.FRAME_X, gamemodel.GameElementStateFactory.FRAME_Y, gamemodel.GameElementStateFactory.HEIGHT, gamemodel.GameElementStateFactory.IMAGE, gamemodel.GameElementStateFactory.NAME, gamemodel.GameElementStateFactory.ROWS, editor.wizards.Wizard.setDataName(), gamemodel.GameElementStateFactory.START_FRAME, gamemodel.GameElementStateFactory.STOP_FRAME, and gamemodel.GameElementStateFactory.WIDTH.
Member Data Documentation
CheckBox editor.wizards.DrawableGameElementWizard.animationRepeat private
Definition at line 65 of file DrawableGameElementWizard.java.
Slider editor.wizards.DrawableGameElementWizard.frameHeight private
Definition at line 55 of file DrawableGameElementWizard.java.
TextField editor.wizards.DrawableGameElementWizard.frameHeightText private
Definition at line 57 of file DrawableGameElementWizard.java.
Slider editor.wizards.DrawableGameElementWizard.frameWidth private
Definition at line 51 of file DrawableGameElementWizard.java.
TextField editor.wizards.DrawableGameElementWizard.frameWidthText private
Definition at line 53 of file DrawableGameElementWizard.java.
GridLines editor.wizards.DrawableGameElementWizard.gridLines private
Definition at line 69 of file DrawableGameElementWizard.java.
Button editor.wizards.DrawableGameElementWizard.image private
Definition at line 45 of file DrawableGameElementWizard.java.
String editor.wizards.DrawableGameElementWizard.imagePath private
Definition at line 70 of file DrawableGameElementWizard.java.
ScrollPane editor.wizards.DrawableGameElementWizard.imageScroll private
Definition at line 49 of file DrawableGameElementWizard.java.
ImageView editor.wizards.DrawableGameElementWizard.imageView private
Definition at line 68 of file DrawableGameElementWizard.java.
TextField editor.wizards.DrawableGameElementWizard.name private
Definition at line 37 of file DrawableGameElementWizard.java.
final String editor.wizards.DrawableGameElementWizard.NUM_ATTR_WIZARD static private
Initial value:
=
            "/editor/wizards/guipanes/NumberAttributeWizard.fxml"
Definition at line 31 of file DrawableGameElementWizard.java.
final String editor.wizards.DrawableGameElementWizard.NUM_REGEX = "-?[0-9]+\\.?[0-9]*" static private
Definition at line 30 of file DrawableGameElementWizard.java.
Button editor.wizards.DrawableGameElementWizard.numberAttribute private
Definition at line 43 of file DrawableGameElementWizard.java.
TextField editor.wizards.DrawableGameElementWizard.numRows private
Definition at line 59 of file DrawableGameElementWizard.java.
Group editor.wizards.DrawableGameElementWizard.spritesheet private
Definition at line 47 of file DrawableGameElementWizard.java.
TextField editor.wizards.DrawableGameElementWizard.startFrame private
Definition at line 61 of file DrawableGameElementWizard.java.
TextField editor.wizards.DrawableGameElementWizard.stopFrame private
Definition at line 63 of file DrawableGameElementWizard.java.
final String editor.wizards.DrawableGameElementWizard.STRING_ATTR_WIZARD static private
Initial value:
=
            "/editor/wizards/guipanes/StringAttributeWizard.fxml"
Definition at line 33 of file DrawableGameElementWizard.java.
Button editor.wizards.DrawableGameElementWizard.stringAttribute private
Definition at line 41 of file DrawableGameElementWizard.java.
Button editor.wizards.DrawableGameElementWizard.trigger private
Definition at line 39 of file DrawableGameElementWizard.java.
final String editor.wizards.DrawableGameElementWizard.TRIGGER_WIZARD = "/editor/wizards/guipanes/TriggerWizard.fxml" static private
Definition at line 35 of file DrawableGameElementWizard.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/wizards/DrawableGameElementWizard.java