voogasalad_TheException: engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction Class Reference
engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction Class Reference
Public Member Functions
ObjectLocationCheckAction (EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager, String[] args)
Public Member Functions inherited from engine.gameRepresentation.evaluatables.actions.Action
Action (EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager, String[] args)
Boolean evaluate (ElementPair elements)
Public Member Functions inherited from engine.gameRepresentation.evaluatables.Evaluatable< T >
Evaluatable (Class< T > type)
abstract T evaluate (ElementPair elements)
boolean setValue (ElementPair elements, T value)
boolean setValue (T value)
Class< T > getType ()
Protected Member Functions
Evaluatable<?> initializeAction (String[] args, EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager) throws ClassNotFoundException, EvaluatorCreationException
Boolean evaluate (Evaluatable<?> action, ElementPair elements)
Protected Member Functions inherited from engine.gameRepresentation.evaluatables.actions.Action
abstract Evaluatable<?> initializeAction (String[] args, EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager) throws ClassNotFoundException, EvaluatorCreationException
abstract Boolean evaluate (Evaluatable<?> action, ElementPair elements)
ObjectOfInterestIdentifier makeObjectIdentifier (String objectIdentifierString)
List< Participant > identifyParticipantsOfInterest (String participantIdentifier, ParticipantManager manager)
boolean executeActionIfTimerExpired (GameElement element, String timerName, long timerReloadTime, ElementPair elements, Consumer< ElementPair > action)
Private Attributes
String myPlayerTypeString
String myGameElementType
int myRadius
int myXLocation
int myYLocation
GameElementManager myManager
ParticipantManager myParticipantManager
String myAttributeToSet
Evaluatable<?> myEvaluatorToUse
int myValueToSet
Additional Inherited Members
Static Public Attributes inherited from engine.gameRepresentation.evaluatables.actions.Action
static final String MY_ELEMENT = "me"
static final String MY_PARTICIPANT = "my"
Static Protected Attributes inherited from engine.gameRepresentation.evaluatables.actions.Action
static final GameElementParameter ACTOR
static final GameElementParameter ACTEE
Detailed Description
See also
ActionOptions.OBJECT_LOCATION_DETECTION
Author
Michael R.
Definition at line 26 of file ObjectLocationCheckAction.java.
Constructor & Destructor Documentation
engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.ObjectLocationCheckAction (EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager, String[] args)
Definition at line 39 of file ObjectLocationCheckAction.java.
Member Function Documentation
Boolean engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.evaluate (Evaluatable<?> action, ElementPair elements) protected
Definition at line 70 of file ObjectLocationCheckAction.java.
References engine.gameRepresentation.evaluatables.Evaluatable< T >.evaluate(), engine.stateManaging.GameElementManager.findAllElementsOfType(), engine.UI.ParticipantManager.getAI(), engine.UI.ParticipantManager.getUser(), model.state.gameelement.StateTags.TEAM_COLOR, model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
Evaluatable<?> engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.initializeAction (String[] args, EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager) throws ClassNotFoundException, EvaluatorCreationException protected
Definition at line 47 of file ObjectLocationCheckAction.java.
Member Data Documentation
String engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myAttributeToSet private
Definition at line 35 of file ObjectLocationCheckAction.java.
Evaluatable<?> engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myEvaluatorToUse private
Definition at line 36 of file ObjectLocationCheckAction.java.
String engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myGameElementType private
Definition at line 28 of file ObjectLocationCheckAction.java.
GameElementManager engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myManager private
Definition at line 33 of file ObjectLocationCheckAction.java.
ParticipantManager engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myParticipantManager private
Definition at line 34 of file ObjectLocationCheckAction.java.
String engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myPlayerTypeString private
Definition at line 27 of file ObjectLocationCheckAction.java.
int engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myRadius private
Definition at line 29 of file ObjectLocationCheckAction.java.
int engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myValueToSet private
Definition at line 37 of file ObjectLocationCheckAction.java.
int engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myXLocation private
Definition at line 30 of file ObjectLocationCheckAction.java.
int engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.myYLocation private
Definition at line 31 of file ObjectLocationCheckAction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/evaluatables/actions/ObjectLocationCheckAction.java