voogasalad_TheException: game_engine.elementFactories.LevelFactory Class Reference
game_engine.elementFactories.LevelFactory Class Reference
Public Member Functions
LevelFactory (GameElementFactory elementFactory)
Level createLevel (LevelState state)
Private Member Functions
List< GameElement > generateGoalElements (List< GameElementState > goals)
List< DrawableGameElement > generateTerrainElements (List< DrawableGameElementState > terrain)
List< SelectableGameElement > generateUnitEelements (List< SelectableGameElementState > units)
MapGrid generateUpToDateGrid (Number levelHeight, Number levelWidth, List< DrawableGameElement > terrain, List< SelectableGameElement > units)
void updateGridForObstacles (List< DrawableGameElement > terrain, List< SelectableGameElement > units, MapGrid newGrid)
Group generateBackGroundGroup (List< DrawableGameElement > terrain, List< SelectableGameElement > units)
Group generateUnitsGroup (List< SelectableGameElement > units)
Private Attributes
GameElementFactory myElementFactory
Detailed Description
Factory for creating Level objects from LevelState objects.
Author
Steve
Definition at line 24 of file LevelFactory.java.
Constructor & Destructor Documentation
game_engine.elementFactories.LevelFactory.LevelFactory (GameElementFactory elementFactory)
Definition at line 28 of file LevelFactory.java.
Member Function Documentation
Level game_engine.elementFactories.LevelFactory.createLevel (LevelState state)
Definition at line 32 of file LevelFactory.java.
References game_engine.elementFactories.LevelFactory.generateBackGroundGroup(), game_engine.elementFactories.LevelFactory.generateGoalElements(), game_engine.elementFactories.LevelFactory.generateTerrainElements(), game_engine.elementFactories.LevelFactory.generateUnitEelements(), game_engine.elementFactories.LevelFactory.generateUnitsGroup(), game_engine.elementFactories.LevelFactory.generateUpToDateGrid(), game_engine.gameRepresentation.stateRepresentation.LevelState.getGoals(), game_engine.gameRepresentation.stateRepresentation.LevelState.getNumericalAttribute(), game_engine.gameRepresentation.stateRepresentation.LevelState.getTerrain(), and game_engine.gameRepresentation.stateRepresentation.LevelState.getUnits().
Referenced by game_engine.stateManaging.GameElementManager.main(), game_engine.Engine.selectLevel(), and game_engine.Engine.updateGameLoop().
Group game_engine.elementFactories.LevelFactory.generateBackGroundGroup (List< DrawableGameElement > terrain, List< SelectableGameElement > units) private
Definition at line 80 of file LevelFactory.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.MOVEMENT_SPEED.
Referenced by game_engine.elementFactories.LevelFactory.createLevel().
List<GameElement> game_engine.elementFactories.LevelFactory.generateGoalElements (List< GameElementState > goals) private
Definition at line 45 of file LevelFactory.java.
References game_engine.elementFactories.GameElementFactory.createGameElement().
Referenced by game_engine.elementFactories.LevelFactory.createLevel().
List<DrawableGameElement> game_engine.elementFactories.LevelFactory.generateTerrainElements (List< DrawableGameElementState > terrain) private
Definition at line 50 of file LevelFactory.java.
References game_engine.elementFactories.GameElementFactory.createDrawableGameElement().
Referenced by game_engine.elementFactories.LevelFactory.createLevel().
List<SelectableGameElement> game_engine.elementFactories.LevelFactory.generateUnitEelements (List< SelectableGameElementState > units) private
Definition at line 55 of file LevelFactory.java.
References game_engine.elementFactories.GameElementFactory.createSelectableGameElement().
Referenced by game_engine.elementFactories.LevelFactory.createLevel().
Group game_engine.elementFactories.LevelFactory.generateUnitsGroup (List< SelectableGameElement > units) private
Definition at line 91 of file LevelFactory.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.MOVEMENT_SPEED.
Referenced by game_engine.elementFactories.LevelFactory.createLevel().
MapGrid game_engine.elementFactories.LevelFactory.generateUpToDateGrid (Number levelHeight, Number levelWidth, List< DrawableGameElement > terrain, List< SelectableGameElement > units) private
Definition at line 60 of file LevelFactory.java.
References game_engine.elementFactories.LevelFactory.updateGridForObstacles().
Referenced by game_engine.elementFactories.LevelFactory.createLevel().
void game_engine.elementFactories.LevelFactory.updateGridForObstacles (List< DrawableGameElement > terrain, List< SelectableGameElement > units, MapGrid newGrid) private
Definition at line 69 of file LevelFactory.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.BLOCKING, game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.MOVEMENT_SPEED, and game_engine.computers.pathingComputers.MapGrid.registerObstaclePlacement().
Referenced by game_engine.elementFactories.LevelFactory.generateUpToDateGrid().
Member Data Documentation
GameElementFactory game_engine.elementFactories.LevelFactory.myElementFactory private
Definition at line 26 of file LevelFactory.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/elementFactories/LevelFactory.java