voogasalad_TheException: view.gui.GUIScreen Class Reference
view.gui.GUIScreen Class Reference abstract
Public Member Functions
void attachSceneHandler (MainView mainView)
void switchScreen (ViewScreenPath screen)
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Public Member Functions inherited from view.gui.GUIController
abstract Node getRoot ()
Private Attributes
MainView myMainView
Additional Inherited Members
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Detailed Description
Author
Nishad Agrawal, Jonathan Tseng
Definition at line 10 of file GUIScreen.java.
Member Function Documentation
void view.gui.GUIScreen.attachSceneHandler (MainView mainView)
Definition at line 14 of file GUIScreen.java.
Referenced by view.MainView.launchScreen().
void view.gui.GUIScreen.switchScreen (ViewScreenPath screen)
Definition at line 18 of file GUIScreen.java.
References view.MainView.launchScreen().
Referenced by view.runner.RunnerMenuBarController.initFileMenu(), view.editor.EditorMenuBarController.initFileMenu(), view.splash.SplashScreen.loadGameAndSwitchScreen(), and view.splash.SplashScreen.setUpButtons().
Member Data Documentation
MainView view.gui.GUIScreen.myMainView private
Definition at line 12 of file GUIScreen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/gui/GUIScreen.java