voogasalad_TheException: view.editor.wizards.AnimationGrid Class Reference
view.editor.wizards.AnimationGrid Class Reference
Public Member Functions
AnimationGrid (double imageWidth, double imageHeight, double frameX, double frameY)
void changeSize (double frameX, double frameY)
void setStart (int frameIndex) throws IndexOutOfBoundsException
void setStop (int frameIndex) throws IndexOutOfBoundsException
void selectFrame (int row, int col, Paint fill)
int getNumRows ()
Public Member Functions inherited from view.editor.wizards.Grid
Grid (double frameX, double frameY)
abstract void selectFrame (int row, int col, Paint fill)
double getFrameX ()
double getFrameY ()
Protected Member Functions
void createColumns ()
Group createColumn (int col)
Protected Member Functions inherited from view.editor.wizards.Grid
void resetExistingFill (String primary, Paint reset)
void createGrid ()
abstract void createColumns ()
abstract Group createColumn (int col)
Frame createFrame (int row, int col, Paint fill)
Private Member Functions
void selectFrame (int frameIndex, String color) throws IndexOutOfBoundsException
Private Attributes
double myWidth
double myHeight
int start
Static Private Attributes
static final String STOP_COLOR = "red"
static final String START_COLOR = "green"
static final String INVALID_STOP_MESSAGE = "Stop frame must come after start frame"
static final String INVALID_FRAME_MESSAGE = "this is an invalid frame number"
Additional Inherited Members
Protected Attributes inherited from view.editor.wizards.Grid
double myFrameX
double myFrameY
List< List< Frame > > frameCols
Static Protected Attributes inherited from view.editor.wizards.Grid
static final String FRAME_STROKE_COLOR = "black"
Detailed Description
Grid Lines used to be displayed over a sprite sheet within the drawable game element wizard.
Author
Jonathan Tseng, Nishad Agrawal
Definition at line 14 of file AnimationGrid.java.
Constructor & Destructor Documentation
view.editor.wizards.AnimationGrid.AnimationGrid (double imageWidth, double imageHeight, double frameX, double frameY)
Definition at line 23 of file AnimationGrid.java.
References view.editor.wizards.AnimationGrid.changeSize().
Member Function Documentation
void view.editor.wizards.AnimationGrid.changeSize (double frameX, double frameY)
Definition at line 30 of file AnimationGrid.java.
References view.editor.wizards.Grid.createGrid(), view.editor.wizards.Grid.myFrameX, and view.editor.wizards.Grid.myFrameY.
Referenced by view.editor.wizards.AnimationGrid.AnimationGrid(), and view.editor.wizards.GameElementWizard.createSliderListeners().
Group view.editor.wizards.AnimationGrid.createColumn (int col) protected
Definition at line 79 of file AnimationGrid.java.
References view.editor.wizards.Grid.createFrame(), view.editor.wizards.Grid.frameCols, view.editor.wizards.Grid.myFrameY, and view.editor.wizards.AnimationGrid.myHeight.
Referenced by view.editor.wizards.AnimationGrid.createColumns().
void view.editor.wizards.AnimationGrid.createColumns () protected
Definition at line 67 of file AnimationGrid.java.
References view.editor.wizards.AnimationGrid.createColumn(), view.editor.wizards.Grid.frameCols, view.editor.wizards.Grid.myFrameX, and view.editor.wizards.AnimationGrid.myWidth.
int view.editor.wizards.AnimationGrid.getNumRows ()
Definition at line 92 of file AnimationGrid.java.
References view.editor.wizards.Grid.frameCols.
Referenced by view.editor.wizards.GameElementWizard.updateData().
void view.editor.wizards.AnimationGrid.selectFrame (int frameIndex, String color) throws IndexOutOfBoundsException private
Definition at line 47 of file AnimationGrid.java.
References view.editor.wizards.Grid.frameCols, and view.editor.wizards.Grid.resetExistingFill().
Referenced by view.editor.wizards.AnimationGrid.setStart(), and view.editor.wizards.AnimationGrid.setStop().
void view.editor.wizards.AnimationGrid.selectFrame (int row, int col, Paint fill)
Definition at line 59 of file AnimationGrid.java.
References view.editor.wizards.Grid.frameCols.
void view.editor.wizards.AnimationGrid.setStart (int frameIndex) throws IndexOutOfBoundsException
Definition at line 37 of file AnimationGrid.java.
References view.editor.wizards.AnimationGrid.selectFrame().
Referenced by view.editor.wizards.AnimationWizard.initialize().
void view.editor.wizards.AnimationGrid.setStop (int frameIndex) throws IndexOutOfBoundsException
Definition at line 42 of file AnimationGrid.java.
References view.editor.wizards.AnimationGrid.selectFrame().
Referenced by view.editor.wizards.AnimationWizard.initialize().
Member Data Documentation
final String view.editor.wizards.AnimationGrid.INVALID_FRAME_MESSAGE = "this is an invalid frame number" static private
Definition at line 18 of file AnimationGrid.java.
final String view.editor.wizards.AnimationGrid.INVALID_STOP_MESSAGE = "Stop frame must come after start frame" static private
Definition at line 17 of file AnimationGrid.java.
double view.editor.wizards.AnimationGrid.myHeight private
Definition at line 20 of file AnimationGrid.java.
Referenced by view.editor.wizards.AnimationGrid.createColumn().
double view.editor.wizards.AnimationGrid.myWidth private
Definition at line 19 of file AnimationGrid.java.
Referenced by view.editor.wizards.AnimationGrid.createColumns().
int view.editor.wizards.AnimationGrid.start private
Definition at line 21 of file AnimationGrid.java.
final String view.editor.wizards.AnimationGrid.START_COLOR = "green" static private
Definition at line 16 of file AnimationGrid.java.
final String view.editor.wizards.AnimationGrid.STOP_COLOR = "red" static private
Definition at line 15 of file AnimationGrid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/AnimationGrid.java