voogasalad_TheException: model.GameSaveLoadMediator Class Reference
model.GameSaveLoadMediator Class Reference
Public Member Functions
String saveGame (JSONable gameState, String gameName) throws SaveLoadException
String saveImage (WizardData data, GameElementImageType elementType) throws SaveLoadException
String saveColorMask (WizardData data, GameElementImageType elementType) throws SaveLoadException
Image loadImage (String filePath) throws SaveLoadException
void loadSpritesAndMasks (Set< AnimatorState > animatorStates) throws SaveLoadException
Static Public Attributes
static final String GAME_ELEMENT_RESOURCES = "gameelementresources"
static final String GAME_DIRECTORY = "myGames"
static final String JSON_EXT = ".json"
static final String PATH_DELIMITER = "/"
Package Functions
public< T > T loadGame (String gameName) throws SaveLoadException
Private Member Functions
String processImagePath (String localLocation, GameElementImageType imageType, GameElementImageType stateType)
String getImageName (String localLocation)
String getGameLocation (String name)
Detailed Description
This class mediates between the Model and the SaveLoadUtility. Using the composition pattern, MainModel holds a reference to this class allowing us to consolidate all file path related function calls in one place and specifically away from the model.
Author
Rahul
Definition at line 24 of file GameSaveLoadMediator.java.
Member Function Documentation
String model.GameSaveLoadMediator.getGameLocation (String name) private
Definition at line 97 of file GameSaveLoadMediator.java.
References model.GameSaveLoadMediator.JSON_EXT.
Referenced by model.GameSaveLoadMediator.loadGame(), and model.GameSaveLoadMediator.saveGame().
String model.GameSaveLoadMediator.getImageName (String localLocation) private
Definition at line 77 of file GameSaveLoadMediator.java.
Referenced by model.GameSaveLoadMediator.processImagePath().
public<T> T model.GameSaveLoadMediator.loadGame (String gameName) throws SaveLoadException package
Parameters
gameName
Returns
Exceptions
Exception
Definition at line 36 of file GameSaveLoadMediator.java.
References model.GameSaveLoadMediator.getGameLocation(), and util.SaveLoadUtility.loadResource().
Referenced by model.MainModel.loadGame().
Image model.GameSaveLoadMediator.loadImage (String filePath) throws SaveLoadException
Parameters
filePath
Returns
Exceptions
Exception
Definition at line 107 of file GameSaveLoadMediator.java.
References util.SaveLoadUtility.loadImage().
void model.GameSaveLoadMediator.loadSpritesAndMasks (Set< AnimatorState > animatorStates) throws SaveLoadException
Parameters
animatorStates
Exceptions
SaveLoadException
Definition at line 116 of file GameSaveLoadMediator.java.
References model.sprite.SpriteImageGenerator.loadSpriteImageContainers().
Referenced by model.MainModel.updateSpritesAndMasks().
String model.GameSaveLoadMediator.processImagePath (String localLocation, GameElementImageType imageType, GameElementImageType stateType) private
Definition at line 69 of file GameSaveLoadMediator.java.
References model.GameElementImageType.getFolderName(), and model.GameSaveLoadMediator.getImageName().
Referenced by model.GameSaveLoadMediator.saveColorMask(), and model.GameSaveLoadMediator.saveImage().
String model.GameSaveLoadMediator.saveColorMask (WizardData data, GameElementImageType elementType) throws SaveLoadException
Parameters
data
elementType
Returns
Exceptions
SaveLoadException
Definition at line 89 of file GameSaveLoadMediator.java.
References model.data.WizardDataType.COLOR_MASK, model.GameElementImageType.Colormask, model.GameSaveLoadMediator.processImagePath(), and util.SaveLoadUtility.saveImage().
Referenced by model.MainModel.createDrawableGameElementState(), and model.MainModel.createSelectableGameElementState().
String model.GameSaveLoadMediator.saveGame (JSONable gameState, String gameName) throws SaveLoadException
Parameters
gameState
gameName
Returns
Exceptions
Exception
Definition at line 48 of file GameSaveLoadMediator.java.
References model.GameSaveLoadMediator.getGameLocation(), and util.SaveLoadUtility.save().
Referenced by model.MainModel.saveGame().
String model.GameSaveLoadMediator.saveImage (WizardData data, GameElementImageType elementType) throws SaveLoadException
Parameters
data
elementType
Returns
Exceptions
SaveLoadException
Definition at line 60 of file GameSaveLoadMediator.java.
References model.data.WizardDataType.IMAGE, model.GameSaveLoadMediator.processImagePath(), util.SaveLoadUtility.saveImage(), and model.GameElementImageType.Spritesheet.
Referenced by model.MainModel.createDrawableGameElementState(), and model.MainModel.createSelectableGameElementState().
Member Data Documentation
final String model.GameSaveLoadMediator.GAME_DIRECTORY = "myGames" static
Definition at line 26 of file GameSaveLoadMediator.java.
final String model.GameSaveLoadMediator.GAME_ELEMENT_RESOURCES = "gameelementresources" static
Definition at line 25 of file GameSaveLoadMediator.java.
final String model.GameSaveLoadMediator.JSON_EXT = ".json" static
Definition at line 27 of file GameSaveLoadMediator.java.
Referenced by model.GameSaveLoadMediator.getGameLocation().
final String model.GameSaveLoadMediator.PATH_DELIMITER = "/" static
Definition at line 28 of file GameSaveLoadMediator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/GameSaveLoadMediator.java