voogasalad_TheException: engine.visuals.elementVisuals.animations.Animator Class Reference
engine.visuals.elementVisuals.animations.Animator Class Reference
Public Member Functions
Animator (SpriteImageContainer images, AnimatorState state, AttributeContainer attributes, SimpleBooleanProperty animationEnabled)
void registerNode (Consumer< Node > registerFunction)
void setAnimation (AnimationSequence animation)
boolean update ()
Dimension getViewportSize ()
Static Public Attributes
static final String SINGLE_IMAGE_PATH_STRING
static final String DEFAULT_IMAGE_STRING
Private Member Functions
void setColorMasking (long teamColor)
Rectangle2D getImageBounds (Image img)
void determineCorrectAnimation ()
void determineAnimationDirection ()
AnimationTag determineAnimationType ()
Rectangle2D getViewport (int frameNumber)
Private Attributes
SpriteImageContainer myImages
AnimatorState myState
AttributeContainer attributesOfInterest
Group mySpriteDisplay
ImageView mySprite
ImageView mySpriteTeamOverlay
Rectangle2D mySpritesheetBounds
AnimationSequence myCurrentAnimation
List< AnimationTag > currentDirection
SimpleBooleanProperty animationEnabled = new SimpleBooleanProperty(false)
Detailed Description
An animation player that allows for the playing of animations using a given spritesheet. This utility assumes all spritesheets are given with a horizontally traversable sheet
Author
Zach, Steve, Rahul, John L.
Definition at line 34 of file Animator.java.
Constructor & Destructor Documentation
engine.visuals.elementVisuals.animations.Animator.Animator (SpriteImageContainer images, AnimatorState state, AttributeContainer attributes, SimpleBooleanProperty animationEnabled)
Initialize the player
Parameters
spriteSheet the image containing the spritesheet
tileSize a point2D containing the width(x) and height(y) of each frame in the spritesheet
numCols the number of columns across the spritesheet goes before moving to the next row
animationEnabled whether to keep track of the actual animation of the object or replace with the default image. JavaFX has difficulty managing large sprite sheets
Definition at line 71 of file Animator.java.
References engine.visuals.elementVisuals.animations.Animator.animationEnabled, engine.visuals.elementVisuals.animations.AnimationTag.FORWARD, model.sprite.SpriteImageContainer.getColorMask(), engine.visuals.elementVisuals.animations.Animator.getImageBounds(), engine.visuals.elementVisuals.animations.AnimatorState.getImageTag(), model.state.gameelement.AttributeContainer.getNumericalAttribute(), model.sprite.SpriteImageContainer.getSpritesheet(), engine.visuals.elementVisuals.animations.Animator.setColorMasking(), and model.state.gameelement.StateTags.TEAM_COLOR.
Member Function Documentation
void engine.visuals.elementVisuals.animations.Animator.determineAnimationDirection () private
Definition at line 193 of file Animator.java.
References engine.visuals.elementVisuals.animations.AnimationTag.BACKWARD, engine.visuals.elementVisuals.animations.AnimationTag.FORWARD, model.state.gameelement.AttributeContainer.getNumericalAttribute(), engine.visuals.elementVisuals.animations.AnimationTag.LEFT, engine.visuals.elementVisuals.animations.AnimationTag.RIGHT, model.state.gameelement.StateTags.X_VELOCITY, and model.state.gameelement.StateTags.Y_VELOCITY.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineCorrectAnimation().
AnimationTag engine.visuals.elementVisuals.animations.Animator.determineAnimationType () private
Definition at line 213 of file Animator.java.
References engine.visuals.elementVisuals.animations.AnimationTag.ATTACK, model.state.gameelement.StateTags.CURRENT_ACTION, engine.visuals.elementVisuals.animations.AnimationTag.DECAY, engine.visuals.elementVisuals.animations.AnimationTag.DIE, model.state.gameelement.AttributeContainer.getNumericalAttribute(), model.state.gameelement.AttributeContainer.getTextualAttribute(), engine.visuals.elementVisuals.animations.AnimationTag.MOVE, engine.visuals.elementVisuals.animations.AnimationTag.STAND, model.state.gameelement.StateTags.X_VELOCITY, and model.state.gameelement.StateTags.Y_VELOCITY.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineCorrectAnimation().
void engine.visuals.elementVisuals.animations.Animator.determineCorrectAnimation () private
Definition at line 181 of file Animator.java.
References engine.visuals.elementVisuals.animations.Animator.determineAnimationDirection(), engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), engine.visuals.elementVisuals.animations.AnimationSequence.equals(), engine.visuals.elementVisuals.animations.AnimatorState.getAnimationSequence(), and engine.visuals.elementVisuals.animations.AnimationSequence.reset().
Referenced by engine.visuals.elementVisuals.animations.Animator.update().
Rectangle2D engine.visuals.elementVisuals.animations.Animator.getImageBounds (Image img) private
Definition at line 155 of file Animator.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.Animator().
Rectangle2D engine.visuals.elementVisuals.animations.Animator.getViewport (int frameNumber) private
Creates and returns a viewport based on a frame number. Assumes vertical traversal of frames
Definition at line 250 of file Animator.java.
References engine.visuals.Dimension.getHeight(), engine.visuals.elementVisuals.animations.AnimatorState.getNumRows(), engine.visuals.elementVisuals.animations.AnimatorState.getViewportSize(), and engine.visuals.Dimension.getWidth().
Referenced by engine.visuals.elementVisuals.animations.Animator.update().
Dimension engine.visuals.elementVisuals.animations.Animator.getViewportSize ()
Definition at line 260 of file Animator.java.
References engine.visuals.elementVisuals.animations.AnimatorState.getViewportSize().
Referenced by engine.visuals.elementVisuals.Visualizer.initializeDisplay().
void engine.visuals.elementVisuals.animations.Animator.registerNode (Consumer< Node > registerFunction)
Definition at line 151 of file Animator.java.
Referenced by engine.visuals.elementVisuals.Visualizer.Visualizer().
void engine.visuals.elementVisuals.animations.Animator.setAnimation (AnimationSequence animation)
Definition at line 160 of file Animator.java.
Referenced by engine.visuals.elementVisuals.Visualizer.initializeDisplay().
void engine.visuals.elementVisuals.animations.Animator.setColorMasking (long teamColor) private
Sets the hue of the unit to match the team color. Use only if animations are disabled
Parameters
teamColor
Definition at line 125 of file Animator.java.
References model.sprite.ColorMapGenerator.colorFromLong(), and model.sprite.SpriteImageContainer.getSpritesheet().
Referenced by engine.visuals.elementVisuals.animations.Animator.Animator().
boolean engine.visuals.elementVisuals.animations.Animator.update ()
Update the animation. Increment the frame and move on to the next animation if the current one is finished.
Implements model.state.gameelement.traits.Updatable.
Definition at line 169 of file Animator.java.
References engine.visuals.elementVisuals.animations.Animator.determineCorrectAnimation(), engine.visuals.elementVisuals.animations.AnimationSequence.getFrame(), engine.visuals.elementVisuals.animations.Animator.getViewport(), and engine.visuals.elementVisuals.animations.AnimationSequence.update().
Referenced by engine.visuals.elementVisuals.Visualizer.initializeDisplay(), and engine.visuals.elementVisuals.Visualizer.updateAnimator().
Member Data Documentation
SimpleBooleanProperty engine.visuals.elementVisuals.animations.Animator.animationEnabled = new SimpleBooleanProperty(false) private
Definition at line 52 of file Animator.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.Animator().
AttributeContainer engine.visuals.elementVisuals.animations.Animator.attributesOfInterest private
Definition at line 42 of file Animator.java.
List<AnimationTag> engine.visuals.elementVisuals.animations.Animator.currentDirection private
Definition at line 50 of file Animator.java.
final String engine.visuals.elementVisuals.animations.Animator.DEFAULT_IMAGE_STRING static
Initial value:
=
            "resources/gameelementresources/terrain/stone6.png"
Definition at line 38 of file Animator.java.
AnimationSequence engine.visuals.elementVisuals.animations.Animator.myCurrentAnimation private
Definition at line 49 of file Animator.java.
SpriteImageContainer engine.visuals.elementVisuals.animations.Animator.myImages private
Definition at line 40 of file Animator.java.
ImageView engine.visuals.elementVisuals.animations.Animator.mySprite private
Definition at line 45 of file Animator.java.
Group engine.visuals.elementVisuals.animations.Animator.mySpriteDisplay private
Definition at line 44 of file Animator.java.
Rectangle2D engine.visuals.elementVisuals.animations.Animator.mySpritesheetBounds private
Definition at line 47 of file Animator.java.
ImageView engine.visuals.elementVisuals.animations.Animator.mySpriteTeamOverlay private
Definition at line 46 of file Animator.java.
AnimatorState engine.visuals.elementVisuals.animations.Animator.myState private
Definition at line 41 of file Animator.java.
final String engine.visuals.elementVisuals.animations.Animator.SINGLE_IMAGE_PATH_STRING static
Initial value:
=
            "resources/gameelementresources/units/singleImages/"
Definition at line 36 of file Animator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/elementVisuals/animations/Animator.java