voogasalad_TheException: view.gui.MenuBarController Class Reference
view.gui.MenuBarController Class Reference abstract
Public Member Functions
void attachScreen (GUIScreen screen)
Node getRoot ()
void modelUpdate ()
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Protected Member Functions
final void init ()
abstract void initMenuBar ()
abstract void bindTextProperties () throws LanguageException
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes
MenuItem saveMenuItem
MenuItem quitMenuItem
Menu fileMenu
MenuBar menuBar
Menu languageMenu
GUIScreen myScreen
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Private Member Functions
final void attachTextProperties ()
void initLanguageMenu ()
Static Private Attributes
static final String FILE_KEY = "File"
static final String SAVE_KEY = "Save"
static final String QUIT_KEY = "Quit"
static final String LANGUAGE_KEY = "Languages"
Detailed Description
Definition at line 13 of file MenuBarController.java.
Member Function Documentation
void view.gui.MenuBarController.attachScreen (GUIScreen screen)
Definition at line 34 of file MenuBarController.java.
Referenced by view.runner.RunnerScreen.init(), and view.editor.EditorScreen.init().
final void view.gui.MenuBarController.attachTextProperties () private
Definition at line 52 of file MenuBarController.java.
References view.gui.MenuBarController.bindTextProperties(), view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.gui.MenuBarController.init().
abstract void view.gui.MenuBarController.bindTextProperties () throws LanguageException abstract protected
Referenced by view.gui.MenuBarController.attachTextProperties().
Node view.gui.MenuBarController.getRoot ()
Implements view.gui.GUIController.
Definition at line 39 of file MenuBarController.java.
References view.gui.MenuBarController.menuBar.
final void view.gui.MenuBarController.init () protected
Definition at line 44 of file MenuBarController.java.
References view.gui.MenuBarController.attachTextProperties(), view.gui.MenuBarController.initLanguageMenu(), and view.gui.MenuBarController.initMenuBar().
void view.gui.MenuBarController.initLanguageMenu () private
Definition at line 68 of file MenuBarController.java.
References util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getSupportedLanguages(), and util.multilanguage.MultiLanguageUtility.setLanguage().
Referenced by view.gui.MenuBarController.init().
abstract void view.gui.MenuBarController.initMenuBar () abstract protected
Referenced by view.gui.MenuBarController.init().
void view.gui.MenuBarController.modelUpdate ()
Definition at line 85 of file MenuBarController.java.
Member Data Documentation
final String view.gui.MenuBarController.FILE_KEY = "File" static private
Definition at line 15 of file MenuBarController.java.
Menu view.gui.MenuBarController.fileMenu protected
Definition at line 25 of file MenuBarController.java.
final String view.gui.MenuBarController.LANGUAGE_KEY = "Languages" static private
Definition at line 18 of file MenuBarController.java.
Menu view.gui.MenuBarController.languageMenu protected
Definition at line 30 of file MenuBarController.java.
MenuBar view.gui.MenuBarController.menuBar protected
Definition at line 27 of file MenuBarController.java.
Referenced by view.gui.MenuBarController.getRoot().
GUIScreen view.gui.MenuBarController.myScreen protected
Definition at line 32 of file MenuBarController.java.
Referenced by view.runner.RunnerMenuBarController.initFileMenu(), view.editor.EditorMenuBarController.initFileMenu(), and view.editor.EditorMenuBarController.saveGame().
final String view.gui.MenuBarController.QUIT_KEY = "Quit" static private
Definition at line 17 of file MenuBarController.java.
MenuItem view.gui.MenuBarController.quitMenuItem protected
Definition at line 23 of file MenuBarController.java.
Referenced by view.runner.RunnerMenuBarController.initFileMenu(), and view.editor.EditorMenuBarController.initFileMenu().
final String view.gui.MenuBarController.SAVE_KEY = "Save" static private
Definition at line 16 of file MenuBarController.java.
MenuItem view.gui.MenuBarController.saveMenuItem protected
Definition at line 21 of file MenuBarController.java.
Referenced by view.runner.RunnerMenuBarController.initFileMenu(), and view.editor.EditorMenuBarController.initFileMenu().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/gui/MenuBarController.java