voogasalad_TheException: game_engine.computers.boundsComputers.VisionComputer Class Reference
game_engine.computers.boundsComputers.VisionComputer Class Reference
Protected Member Functions
boolean checkComputingCondition (SelectableGameElement primaryObject, DrawableGameElement otherObject)
void givePrimaryObjectElements (SelectableGameElement primaryObject, List< DrawableGameElement > listToAdd)
Protected Member Functions inherited from game_engine.computers.Computer< T, E >
abstract void givePrimaryObjectElements (T primaryObject, List< E > objectsOfInterest)
abstract boolean checkComputingCondition (T primaryObject, E otherObject)
Additional Inherited Members
Public Member Functions inherited from game_engine.computers.Computer< T, E >
void compute (T primaryObject, List< E > objectsToCheck)
Detailed Description
A computer that indicates which objects an object with sight can see
Author
Zachary Bears, Jonathan
Definition at line 18 of file VisionComputer.java.
Member Function Documentation
boolean game_engine.computers.boundsComputers.VisionComputer.checkComputingCondition (SelectableGameElement primaryObject, DrawableGameElement otherObject) protected
Return true if the other object is contained within the primary object's vision bounds
See also
Computer::checkComputingCondition
Definition at line 27 of file VisionComputer.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.traits.Boundable.getBounds(), and game_engine.gameRepresentation.stateRepresentation.gameElement.traits.Sighted.getVisionBounds().
void game_engine.computers.boundsComputers.VisionComputer.givePrimaryObjectElements (SelectableGameElement primaryObject, List< DrawableGameElement > listToAdd) protected
Add the elements of interest to the primary object's visible elements list
See also
Computer::givePrimaryObjectElements
Definition at line 48 of file VisionComputer.java.
References game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElements().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/computers/boundsComputers/VisionComputer.java