voogasalad_TheException: view.editor.wizards.CRUDContainer Class Reference
view.editor.wizards.CRUDContainer Class Reference
Public Member Functions
Node getRoot ()
void initialize ()
void setValidToLaunch (BooleanSupplier supplier)
List< WizardData > getWizardDatas ()
void addAndRenderWizardDatas (Collection< WizardData > datas)
void init (GUIPanePath path, List< String > globalAttrs, BiConsumer< Button, WizardData > setTextConsumer)
void init (GUIPanePath path, List< String > globalAttrs, BiConsumer< Button, WizardData > setTextConsumer, Dimension dim)
void bindButtonText (ObjectProperty< String > property)
Package Attributes
List< WizardData > myWizardDatas
BooleanSupplier valid
Private Member Functions
void launchNestedWizard ()
void createVisualRepresentation (WizardData data)
void launchEditWizard (WizardData oldData, Button button)
Private Attributes
VBox root
Button add
VBox existing
GUIPanePath myPath
List< String > myGlobals
BiConsumer< Button, WizardData > myTextConsumer
Dimension myDim
Static Private Attributes
static final String DELETE_TEXT = "X"
static final Dimension DEFAULT_WIZARD_SIZE = new Dimension(300, 300)
Detailed Description
Definition at line 23 of file CRUDContainer.java.
Member Function Documentation
void view.editor.wizards.CRUDContainer.addAndRenderWizardDatas (Collection< WizardData > datas)
Definition at line 67 of file CRUDContainer.java.
References view.editor.wizards.CRUDContainer.createVisualRepresentation().
Referenced by view.editor.wizards.GameElementWizard.addContainerData().
void view.editor.wizards.CRUDContainer.bindButtonText (ObjectProperty< String > property)
Definition at line 86 of file CRUDContainer.java.
Referenced by view.editor.wizards.GameElementWizard.attachTextProperties().
void view.editor.wizards.CRUDContainer.createVisualRepresentation (WizardData data) private
Definition at line 101 of file CRUDContainer.java.
References view.editor.wizards.CRUDContainer.launchEditWizard().
Referenced by view.editor.wizards.CRUDContainer.addAndRenderWizardDatas(), and view.editor.wizards.CRUDContainer.launchNestedWizard().
Node view.editor.wizards.CRUDContainer.getRoot ()
Implements view.gui.GUIController.
Definition at line 44 of file CRUDContainer.java.
References view.editor.wizards.CRUDContainer.root.
List<WizardData> view.editor.wizards.CRUDContainer.getWizardDatas ()
Definition at line 63 of file CRUDContainer.java.
Referenced by view.editor.wizards.GameElementWizard.storeContainerData().
void view.editor.wizards.CRUDContainer.init (GUIPanePath path, List< String > globalAttrs, BiConsumer< Button, WizardData > setTextConsumer)
Definition at line 72 of file CRUDContainer.java.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
void view.editor.wizards.CRUDContainer.init (GUIPanePath path, List< String > globalAttrs, BiConsumer< Button, WizardData > setTextConsumer, Dimension dim)
Definition at line 77 of file CRUDContainer.java.
void view.editor.wizards.CRUDContainer.initialize ()
Implements view.gui.GUIController.
Definition at line 49 of file CRUDContainer.java.
References view.editor.wizards.CRUDContainer.launchNestedWizard().
void view.editor.wizards.CRUDContainer.launchEditWizard (WizardData oldData, Button button) private
Definition at line 119 of file CRUDContainer.java.
References model.data.WizardData.addDataPair(), model.data.WizardData.clear(), view.editor.wizards.Wizard.closeStage(), view.editor.wizards.Wizard.launchForEdit(), view.editor.wizards.Wizard.loadGlobalValues(), view.editor.wizards.WizardUtility.loadWizard(), and view.editor.wizards.Wizard.setSubmit().
Referenced by view.editor.wizards.CRUDContainer.createVisualRepresentation().
void view.editor.wizards.CRUDContainer.launchNestedWizard () private
Definition at line 90 of file CRUDContainer.java.
References view.editor.wizards.Wizard.closeStage(), view.editor.wizards.CRUDContainer.createVisualRepresentation(), view.editor.wizards.Wizard.loadGlobalValues(), view.editor.wizards.WizardUtility.loadWizard(), and view.editor.wizards.Wizard.setSubmit().
Referenced by view.editor.wizards.CRUDContainer.initialize().
void view.editor.wizards.CRUDContainer.setValidToLaunch (BooleanSupplier supplier)
Definition at line 59 of file CRUDContainer.java.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
Member Data Documentation
Button view.editor.wizards.CRUDContainer.add private
Definition at line 31 of file CRUDContainer.java.
final Dimension view.editor.wizards.CRUDContainer.DEFAULT_WIZARD_SIZE = new Dimension(300, 300) static private
Definition at line 26 of file CRUDContainer.java.
final String view.editor.wizards.CRUDContainer.DELETE_TEXT = "X" static private
Definition at line 25 of file CRUDContainer.java.
VBox view.editor.wizards.CRUDContainer.existing private
Definition at line 33 of file CRUDContainer.java.
Dimension view.editor.wizards.CRUDContainer.myDim private
Definition at line 41 of file CRUDContainer.java.
List<String> view.editor.wizards.CRUDContainer.myGlobals private
Definition at line 39 of file CRUDContainer.java.
GUIPanePath view.editor.wizards.CRUDContainer.myPath private
Definition at line 38 of file CRUDContainer.java.
BiConsumer<Button, WizardData> view.editor.wizards.CRUDContainer.myTextConsumer private
Definition at line 40 of file CRUDContainer.java.
List<WizardData> view.editor.wizards.CRUDContainer.myWizardDatas package
Definition at line 35 of file CRUDContainer.java.
VBox view.editor.wizards.CRUDContainer.root private
Definition at line 29 of file CRUDContainer.java.
Referenced by view.editor.wizards.CRUDContainer.getRoot().
BooleanSupplier view.editor.wizards.CRUDContainer.valid package
Definition at line 36 of file CRUDContainer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/CRUDContainer.java