voogasalad_TheException: view.runner.LevelChooserController Class Reference
view.runner.LevelChooserController Class Reference
Public Member Functions
void updateDropDowns (Map< String, List< String >> campaignLevelMap)
void setOnSubmit (Consumer< LevelIdentifier > submitConsumer)
Node getRoot ()
void initialize ()
Private Member Functions
void attachTextProperties ()
void initDropDowns ()
void updateLevelDropDown (String campaign)
Private Attributes
BorderPane root
ComboBox< String > campaignDropDown
ComboBox< String > levelDropDown
Button submitButton
Consumer< LevelIdentifier > mySubmitConsumer
Map< String, List< String > > myCampaignLevelMap
Static Private Attributes
static final String PLAY_KEY = "Play"
static final String CAMPAIGN_KEY = "Campaign"
static final String LEVEL_KEY = "Level"
static final String INVALID_SELECTION_KEY = "InvalidSelection"
Detailed Description
Controller for the game runner to choose a level
Author
Jonathan Tseng
Definition at line 28 of file LevelChooserController.java.
Member Function Documentation
void view.runner.LevelChooserController.attachTextProperties () private
Definition at line 89 of file LevelChooserController.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.runner.LevelChooserController.initialize().
Node view.runner.LevelChooserController.getRoot ()
Implements view.gui.GUIController.
Definition at line 60 of file LevelChooserController.java.
References view.runner.LevelChooserController.root.
void view.runner.LevelChooserController.initDropDowns () private
Definition at line 102 of file LevelChooserController.java.
Referenced by view.runner.LevelChooserController.initialize(), and view.runner.LevelChooserController.updateDropDowns().
void view.runner.LevelChooserController.initialize ()
Implements view.gui.GUIController.
Definition at line 65 of file LevelChooserController.java.
References view.runner.LevelChooserController.attachTextProperties(), view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), view.runner.LevelChooserController.initDropDowns(), and view.runner.LevelChooserController.updateLevelDropDown().
void view.runner.LevelChooserController.setOnSubmit (Consumer< LevelIdentifier > submitConsumer)
Definition at line 55 of file LevelChooserController.java.
Referenced by view.runner.RunnerScreen.init().
void view.runner.LevelChooserController.updateDropDowns (Map< String, List< String >> campaignLevelMap)
Definition at line 49 of file LevelChooserController.java.
References view.runner.LevelChooserController.initDropDowns().
Referenced by view.runner.RunnerScreen.updateLevelChooser().
void view.runner.LevelChooserController.updateLevelDropDown (String campaign) private
Definition at line 108 of file LevelChooserController.java.
Referenced by view.runner.LevelChooserController.initialize().
Member Data Documentation
final String view.runner.LevelChooserController.CAMPAIGN_KEY = "Campaign" static private
Definition at line 31 of file LevelChooserController.java.
ComboBox<String> view.runner.LevelChooserController.campaignDropDown private
Definition at line 38 of file LevelChooserController.java.
final String view.runner.LevelChooserController.INVALID_SELECTION_KEY = "InvalidSelection" static private
Definition at line 33 of file LevelChooserController.java.
final String view.runner.LevelChooserController.LEVEL_KEY = "Level" static private
Definition at line 32 of file LevelChooserController.java.
ComboBox<String> view.runner.LevelChooserController.levelDropDown private
Definition at line 40 of file LevelChooserController.java.
Map<String, List<String> > view.runner.LevelChooserController.myCampaignLevelMap private
Definition at line 47 of file LevelChooserController.java.
Consumer<LevelIdentifier> view.runner.LevelChooserController.mySubmitConsumer private
Initial value:
= (LevelIdentifier levelID) -> {
    }
Definition at line 44 of file LevelChooserController.java.
final String view.runner.LevelChooserController.PLAY_KEY = "Play" static private
Definition at line 30 of file LevelChooserController.java.
BorderPane view.runner.LevelChooserController.root private
Definition at line 36 of file LevelChooserController.java.
Referenced by view.runner.LevelChooserController.getRoot().
Button view.runner.LevelChooserController.submitButton private
Definition at line 42 of file LevelChooserController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/runner/LevelChooserController.java