voogasalad_TheException: engine.computers.pathingComputers.Location Class Reference
engine.computers.pathingComputers.Location Class Reference
Public Member Functions
Location (double x, double y)
void setPriority (double priority)
boolean equals (Object o)
String toString ()
int compareTo (Location arg0)
double getX ()
double getY ()
double getPriority ()
double getMovementSpeed ()
Private Attributes
double myX
double myY
double movementSpeedScalingFactor = 1
double myPriority
Detailed Description
Simple Point2D clone for use in pathing calculations.
Author
Steve, Michael D.
Parameters
<T>
Definition at line 9 of file Location.java.
Constructor & Destructor Documentation
engine.computers.pathingComputers.Location.Location (double x, double y)
Definition at line 15 of file Location.java.
Referenced by engine.computers.pathingComputers.Location.equals().
Member Function Documentation
int engine.computers.pathingComputers.Location.compareTo (Location arg0)
Definition at line 44 of file Location.java.
References engine.computers.pathingComputers.Location.myPriority.
boolean engine.computers.pathingComputers.Location.equals (Object o)
Definition at line 25 of file Location.java.
References engine.computers.pathingComputers.Location.Location(), engine.computers.pathingComputers.Location.myX, and engine.computers.pathingComputers.Location.myY.
double engine.computers.pathingComputers.Location.getMovementSpeed ()
Definition at line 60 of file Location.java.
References engine.computers.pathingComputers.Location.movementSpeedScalingFactor.
Referenced by engine.computers.pathingComputers.PathingComputer.determinePathLength().
double engine.computers.pathingComputers.Location.getPriority ()
Definition at line 56 of file Location.java.
References engine.computers.pathingComputers.Location.myPriority.
double engine.computers.pathingComputers.Location.getX ()
Definition at line 48 of file Location.java.
References engine.computers.pathingComputers.Location.myX.
Referenced by engine.computers.pathingComputers.MapGrid.alterLocationsInsideBounds(), engine.computers.pathingComputers.PathingComputer.determineHeuristic(), engine.computers.pathingComputers.PathingComputer.determinePathLength(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines(), engine.computers.pathingComputers.MapGrid.getNeighbors(), engine.computers.pathingComputers.MapGrid.getNeighborsForXYCoordinate(), engine.computers.pathingComputers.PathingComputer.pointsAreColinear(), and engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setGoalPositions().
double engine.computers.pathingComputers.Location.getY ()
Definition at line 52 of file Location.java.
References engine.computers.pathingComputers.Location.myY.
Referenced by engine.computers.pathingComputers.MapGrid.alterLocationsInsideBounds(), engine.computers.pathingComputers.PathingComputer.determineHeuristic(), engine.computers.pathingComputers.PathingComputer.determinePathLength(), engine.gameRepresentation.evaluatables.evaluators.HeadingUpdate< A, B >.evaluate(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getLines(), engine.computers.pathingComputers.MapGrid.getNeighbors(), engine.computers.pathingComputers.MapGrid.getNeighborsForXYCoordinate(), engine.computers.pathingComputers.PathingComputer.pointsAreColinear(), and engine.gameRepresentation.renderedRepresentation.DrawableGameElement.setGoalPositions().
void engine.computers.pathingComputers.Location.setPriority (double priority)
Definition at line 20 of file Location.java.
String engine.computers.pathingComputers.Location.toString ()
Definition at line 39 of file Location.java.
Referenced by engine.computers.pathingComputers.MapGrid.toString().
Member Data Documentation
double engine.computers.pathingComputers.Location.movementSpeedScalingFactor = 1 private
Definition at line 12 of file Location.java.
Referenced by engine.computers.pathingComputers.Location.getMovementSpeed().
double engine.computers.pathingComputers.Location.myPriority private
Definition at line 13 of file Location.java.
Referenced by engine.computers.pathingComputers.Location.compareTo(), and engine.computers.pathingComputers.Location.getPriority().
double engine.computers.pathingComputers.Location.myX private
Definition at line 10 of file Location.java.
Referenced by engine.computers.pathingComputers.Location.equals(), and engine.computers.pathingComputers.Location.getX().
double engine.computers.pathingComputers.Location.myY private
Definition at line 11 of file Location.java.
Referenced by engine.computers.pathingComputers.Location.equals(), and engine.computers.pathingComputers.Location.getY().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/computers/pathingComputers/Location.java