voogasalad_TheException: engine.visuals.elementVisuals.animations.AnimationTag Enum Reference
engine.visuals.elementVisuals.animations.AnimationTag Enum Reference
Classes
enum AnimationType
Public Member Functions
AnimationType getType ()
Public Attributes
FORWARD =(AnimationType.DIRECTION)
BACKWARD =(AnimationType.DIRECTION)
LEFT =(AnimationType.DIRECTION)
RIGHT =(AnimationType.DIRECTION)
HERE =(AnimationType.DIRECTION)
STAND =(AnimationType.ACTION)
MOVE =(AnimationType.ACTION)
ATTACK =(AnimationType.ACTION)
DIE =(AnimationType.ACTION)
DECAY =(AnimationType.ACTION)
DO_NOTHING =(AnimationType.ACTION)
Private Member Functions
AnimationTag (AnimationType type)
Private Attributes
AnimationType myType
Detailed Description
Enum with Animation Tags allowing for easy reference to specific animation sequences.
Author
Rahul, Steve
Definition at line 10 of file AnimationTag.java.
Constructor & Destructor Documentation
engine.visuals.elementVisuals.animations.AnimationTag.AnimationTag (AnimationType type) private
Definition at line 27 of file AnimationTag.java.
Member Function Documentation
AnimationType engine.visuals.elementVisuals.animations.AnimationTag.getType ()
Definition at line 31 of file AnimationTag.java.
Member Data Documentation
engine.visuals.elementVisuals.animations.AnimationTag.ATTACK =(AnimationType.ACTION)
Definition at line 21 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), and util.imageprocessing.SpriteSheetCreationUtility.populateTagLists().
engine.visuals.elementVisuals.animations.AnimationTag.BACKWARD =(AnimationType.DIRECTION)
Definition at line 14 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineAnimationDirection(), util.imageprocessing.SpriteSheetCreationUtility.populateTagLists(), view.editor.wizards.AnimationWizard.selectCorrectFrame(), and view.editor.wizards.DirectionGrid.selectFrame().
engine.visuals.elementVisuals.animations.AnimationTag.DECAY =(AnimationType.ACTION)
Definition at line 23 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), and util.imageprocessing.SpriteSheetCreationUtility.populateTagLists().
engine.visuals.elementVisuals.animations.AnimationTag.DIE =(AnimationType.ACTION)
Definition at line 22 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), and util.imageprocessing.SpriteSheetCreationUtility.populateTagLists().
engine.visuals.elementVisuals.animations.AnimationTag.DO_NOTHING =(AnimationType.ACTION)
Definition at line 24 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.NullAnimationSequence.NullAnimationSequence().
engine.visuals.elementVisuals.animations.AnimationTag.FORWARD =(AnimationType.DIRECTION)
Definition at line 13 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.Animator(), engine.visuals.elementVisuals.animations.Animator.determineAnimationDirection(), util.imageprocessing.SpriteSheetCreationUtility.populateTagLists(), view.editor.wizards.AnimationWizard.selectCorrectFrame(), and view.editor.wizards.DirectionGrid.selectFrame().
engine.visuals.elementVisuals.animations.AnimationTag.HERE =(AnimationType.DIRECTION)
Definition at line 17 of file AnimationTag.java.
Referenced by view.editor.wizards.DirectionGrid.selectFrame().
engine.visuals.elementVisuals.animations.AnimationTag.LEFT =(AnimationType.DIRECTION)
Definition at line 15 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineAnimationDirection(), util.imageprocessing.SpriteSheetCreationUtility.populateTagLists(), view.editor.wizards.AnimationWizard.selectCorrectFrame(), and view.editor.wizards.DirectionGrid.selectFrame().
engine.visuals.elementVisuals.animations.AnimationTag.MOVE =(AnimationType.ACTION)
Definition at line 20 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), and util.imageprocessing.SpriteSheetCreationUtility.populateTagLists().
AnimationType engine.visuals.elementVisuals.animations.AnimationTag.myType private
Definition at line 26 of file AnimationTag.java.
engine.visuals.elementVisuals.animations.AnimationTag.RIGHT =(AnimationType.DIRECTION)
Definition at line 16 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineAnimationDirection(), util.imageprocessing.SpriteSheetCreationUtility.populateTagLists(), view.editor.wizards.AnimationWizard.selectCorrectFrame(), and view.editor.wizards.DirectionGrid.selectFrame().
engine.visuals.elementVisuals.animations.AnimationTag.STAND =(AnimationType.ACTION)
Definition at line 19 of file AnimationTag.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), and util.imageprocessing.SpriteSheetCreationUtility.populateTagLists().
The documentation for this enum was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/elementVisuals/animations/AnimationTag.java