voogasalad_TheException: engine.visuals.ScrollableBackground Class Reference
engine.visuals.ScrollableBackground Class Reference
Public Member Functions
ScrollableBackground (double xBoundary, double yBoundary, ScrollablePane pane, String backgroundURI)
void tileBackground (String backgroundURI)
void addObjects (Group g)
void removeObjects (Group g)
void update ()
void setXScrollSpeed (double speed)
void setYScrollSpeed (double speed)
Package Attributes
double myYScrollSpeed
double myYBoundary
ScrollablePane myPane
Private Member Functions
void retractOutOfBoundsScroll ()
Private Attributes
double myXScrollSpeed
double myXBoundary
Detailed Description
A scrollablebackground pane for the game
Author
John
Definition at line 19 of file ScrollableBackground.java.
Constructor & Destructor Documentation
engine.visuals.ScrollableBackground.ScrollableBackground (double xBoundary, double yBoundary, ScrollablePane pane, String backgroundURI)
Create the scrollable background
Parameters
screenWidth
screenHeight
xBoundary the maximum X value that can be scrolled to
yBoundary the maximum Y value that can be scrolled to
Definition at line 36 of file ScrollableBackground.java.
References engine.visuals.ScrollableBackground.tileBackground().
Member Function Documentation
void engine.visuals.ScrollableBackground.addObjects (Group g)
Add objects to be displayed in the scrollablebackground
Parameters
g a group of the objects to add
Definition at line 71 of file ScrollableBackground.java.
Referenced by engine.visuals.VisualManager.addObject().
void engine.visuals.ScrollableBackground.removeObjects (Group g)
Remove an object from the scrollablebackground
Parameters
g the object to remove
Definition at line 80 of file ScrollableBackground.java.
Referenced by engine.visuals.VisualManager.removeObject().
void engine.visuals.ScrollableBackground.retractOutOfBoundsScroll () private
Undo scrolling if we're going out of bounds
Definition at line 102 of file ScrollableBackground.java.
Referenced by engine.visuals.ScrollableBackground.update().
void engine.visuals.ScrollableBackground.setXScrollSpeed (double speed)
Definition at line 111 of file ScrollableBackground.java.
Referenced by engine.visuals.ScrollablePane.initializeHandlers(), engine.visuals.ScrollablePane.setScrollSpeed(), and engine.visuals.ScrollableBackground.update().
void engine.visuals.ScrollableBackground.setYScrollSpeed (double speed)
Definition at line 115 of file ScrollableBackground.java.
Referenced by engine.visuals.ScrollablePane.initializeHandlers(), engine.visuals.ScrollablePane.setScrollSpeed(), and engine.visuals.ScrollableBackground.update().
void engine.visuals.ScrollableBackground.tileBackground (String backgroundURI)
Definition at line 54 of file ScrollableBackground.java.
References util.SaveLoadUtility.loadImage().
Referenced by engine.visuals.ScrollablePane.changeBackground(), and engine.visuals.ScrollableBackground.ScrollableBackground().
void engine.visuals.ScrollableBackground.update ()
Update the view of the background based on the current scroll speed
Definition at line 87 of file ScrollableBackground.java.
References engine.visuals.ScrollableBackground.retractOutOfBoundsScroll(), engine.visuals.ScrollableBackground.setXScrollSpeed(), and engine.visuals.ScrollableBackground.setYScrollSpeed().
Referenced by engine.visuals.ScrollablePane.update().
Member Data Documentation
ScrollablePane engine.visuals.ScrollableBackground.myPane package
Definition at line 26 of file ScrollableBackground.java.
double engine.visuals.ScrollableBackground.myXBoundary private
Definition at line 22 of file ScrollableBackground.java.
double engine.visuals.ScrollableBackground.myXScrollSpeed private
Definition at line 21 of file ScrollableBackground.java.
double engine.visuals.ScrollableBackground.myYBoundary package
Definition at line 22 of file ScrollableBackground.java.
double engine.visuals.ScrollableBackground.myYScrollSpeed package
Definition at line 21 of file ScrollableBackground.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/ScrollableBackground.java