voogasalad_TheException: engine.UI.ParticipantManager Class Reference
engine.UI.ParticipantManager Class Reference
Public Member Functions
ParticipantManager (HumanParticipant user, GameElementManager gameElementManager)
Participant getUser ()
List< Participant > getAI ()
void update (List< SelectableGameElement > allUnits)
void adjustParticipantNumericalAttribute (Number teamColor, String tag, double value)
void setParticipantNumericalAttribute (Number teamColor, String tag, Number value)
void setParticipantTextualAttribute (Number teamColor, String tag, String value)
ObservableValue<?extends String > getPlayerResourceProperty ()
Private Member Functions
List< Participant > filterParticipants (Number teamColor)
Private Attributes
GameElementManager myElementManager
List< AIParticipant > myAIUsers
HumanParticipant humanUser
ObjectProperty< String > player1Resources
Detailed Description
The manager that controls all of the Participants TODO: actually implement some logic for the AI. For now, all the AI is going to do is have all of it's units just run haphazardly
Author
John Lorenz
Definition at line 27 of file ParticipantManager.java.
Constructor & Destructor Documentation
engine.UI.ParticipantManager.ParticipantManager (HumanParticipant user, GameElementManager gameElementManager)
Definition at line 34 of file ParticipantManager.java.
Member Function Documentation
void engine.UI.ParticipantManager.adjustParticipantNumericalAttribute (Number teamColor, String tag, double value)
Used to adjust the participant's (by ID value) numerical attribute by the adjustment value
Parameters
teamColor
tag
value the value to adjust the current numerical attribute's value by
Definition at line 110 of file ParticipantManager.java.
References engine.UI.ParticipantManager.filterParticipants().
List<Participant> engine.UI.ParticipantManager.filterParticipants (Number teamColor) private
filters participants by ID. if ID = -1, returns all participants, both human and ai
Parameters
teamColor
Returns
Definition at line 149 of file ParticipantManager.java.
References engine.users.Participant.checkSameTeam().
Referenced by engine.UI.ParticipantManager.adjustParticipantNumericalAttribute(), engine.UI.ParticipantManager.setParticipantNumericalAttribute(), and engine.UI.ParticipantManager.setParticipantTextualAttribute().
List<Participant> engine.UI.ParticipantManager.getAI ()
Get the current manager's AI
Returns
Definition at line 56 of file ParticipantManager.java.
References engine.UI.ParticipantManager.myAIUsers.
Referenced by engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.evaluate(), and engine.gameRepresentation.evaluatables.actions.Action.identifyParticipantsOfInterest().
ObservableValue<? extends String> engine.UI.ParticipantManager.getPlayerResourceProperty ()
Definition at line 158 of file ParticipantManager.java.
References engine.UI.ParticipantManager.player1Resources.
Referenced by engine.visuals.StatisticsBox.StatisticsBox().
Participant engine.UI.ParticipantManager.getUser ()
Get the current manager's users
Returns
Definition at line 47 of file ParticipantManager.java.
References engine.UI.ParticipantManager.humanUser.
Referenced by engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.evaluate(), engine.gameRepresentation.evaluatables.actions.Action.identifyParticipantsOfInterest(), and engine.visuals.VisualManager.update().
void engine.UI.ParticipantManager.setParticipantNumericalAttribute (Number teamColor, String tag, Number value)
Used to reset the participant's (by ID value) numerical attribute. Overwrites current value
Parameters
teamColor
tag
value
Definition at line 124 of file ParticipantManager.java.
References engine.UI.ParticipantManager.filterParticipants().
void engine.UI.ParticipantManager.setParticipantTextualAttribute (Number teamColor, String tag, String value)
Used to reset participant's string attribute by ID value
Parameters
teamColor
tag
value
Definition at line 137 of file ParticipantManager.java.
References engine.UI.ParticipantManager.filterParticipants().
void engine.UI.ParticipantManager.update (List< SelectableGameElement > allUnits)
Determines AI actions to take on each frame. Functions as a finite state machine in that each action the AI takes is based on the current situation of the game
Parameters
allUnits
Goes through and for every team that does not correspond to the human player that exists, creates a new AI team for it
Tells all units on all teams to move at complete random around the screen
Definition at line 66 of file ParticipantManager.java.
References engine.Engine.DEFAULT_PLAYER_COLOR, engine.users.Participant.getAttributes(), model.state.gameelement.AttributeContainer.getNumericalAttribute(), model.state.gameelement.StateTags.RESOURCES, and model.state.gameelement.StateTags.TEAM_COLOR.
Referenced by engine.stateManaging.GameLoop.updateRunner().
Member Data Documentation
HumanParticipant engine.UI.ParticipantManager.humanUser private
Definition at line 30 of file ParticipantManager.java.
Referenced by engine.UI.ParticipantManager.getUser().
List<AIParticipant> engine.UI.ParticipantManager.myAIUsers private
Definition at line 29 of file ParticipantManager.java.
Referenced by engine.UI.ParticipantManager.getAI().
GameElementManager engine.UI.ParticipantManager.myElementManager private
Definition at line 28 of file ParticipantManager.java.
ObjectProperty<String> engine.UI.ParticipantManager.player1Resources private
Definition at line 32 of file ParticipantManager.java.
Referenced by engine.UI.ParticipantManager.getPlayerResourceProperty().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/UI/ParticipantManager.java