voogasalad_TheException: model.MainModel Class Reference
model.MainModel Class Reference
Public Member Functions
MainModel () throws SaveLoadException
void newGame (String gameName)
void loadGame (String game) throws LanguagePropertyNotFoundException
void saveGame () throws RuntimeException
void saveGame (GameState game)
void addParticipantColor (String color)
void updateDescribableState (String[] selection, String name, String description) throws CampaignNotFoundException, LevelNotFoundException
DescribableState getDescribableState (String[] selection) throws CampaignNotFoundException, LevelNotFoundException
GameState getCurrentGame ()
LevelState getLevel (LevelIdentifier levelID) throws LevelNotFoundException, CampaignNotFoundException
void setLevel (LevelIdentifier levelID, LevelState levelState) throws CampaignNotFoundException, LevelNotFoundException
CampaignState getCampaign (String campaignName) throws CampaignNotFoundException
void setEditorChosenColor (String color)
long getEditorChosenColor ()
void setEditorChosenDrawable (String elementName)
void setEditorChosenSelectable (String elementName)
void clearEditorChosen ()
String getEditorChosenSelectable ()
String getEditorChosenDrawable ()
void createCampaign (String campaignName) throws CampaignExistsException
void createLevel (String levelName, String campaignName, Number width, Number height, String backgroundPath) throws LevelExistsException, CampaignNotFoundException, Exception
void createGameElementState (WizardData data)
void createDrawableGameElementState (WizardData data)
void createSelectableGameElementState (WizardData data)
void removeDrawableGameElement (String elementName) throws ElementInUseException
void removeSelectableGameElement (String elementName) throws ElementInUseException
void createGoal (LevelState levelState, WizardData data)
void removeGoal (LevelState levelState, int index)
void addUnitToLevel (LevelState levelState, String elementName, Double xValue, Double yValue) throws Exception
void setTerrain (LevelState levelState, String terrainName)
void addTerrainToLevel (LevelState levelState, String elementName, Double xValue, Double yValue) throws Exception
GameUniverse getGameUniverse ()
SpriteImageContainer fetchImageContainer (String imageTag)
Private Member Functions
void updateSpritesAndMasks ()
boolean elementIsInUse (String elementName)
boolean areCoordinatesValid (LevelState levelState, Double x, Double y)
void updateObservers ()
Private Attributes
GameState myGameState
String myEditorChosenSelectableElement
String myEditorChosenDrawableElement
String myEditorChosenColor
GameSaveLoadMediator mySaveLoadMediator
SpriteImageGenerator mySpriteImageGenerator
Static Private Attributes
static final String LOAD_GAME_ERROR_KEY = "LoadGameError"
Detailed Description
Main class for the model of the game
Author
Jonathan Tseng, Rahul Harikrishnan, Nishad Agrawal
Definition at line 45 of file MainModel.java.
Constructor & Destructor Documentation
model.MainModel.MainModel () throws SaveLoadException
Definition at line 54 of file MainModel.java.
References model.MainModel.clearEditorChosen().
Member Function Documentation
void model.MainModel.addParticipantColor (String color)
Definition at line 129 of file MainModel.java.
References model.GameUniverse.addParticipantColor(), model.MainModel.getGameUniverse(), and model.MainModel.updateObservers().
Referenced by view.editor.EditorScreen.initParticipantInfo().
void model.MainModel.addTerrainToLevel (LevelState levelState, String elementName, Double xValue, Double yValue) throws Exception
Definition at line 389 of file MainModel.java.
References model.MainModel.areCoordinatesValid(), model.GameUniverse.getDrawableGameElementState(), model.MainModel.getGameUniverse(), model.state.gameelement.GameElementState.myAttributes, model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
void model.MainModel.addUnitToLevel (LevelState levelState, String elementName, Double xValue, Double yValue) throws Exception
Definition at line 354 of file MainModel.java.
References model.MainModel.areCoordinatesValid(), model.MainModel.getGameUniverse(), model.GameUniverse.getSelectableGameElementState(), model.state.gameelement.GameElementState.myAttributes, model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
boolean model.MainModel.areCoordinatesValid (LevelState levelState, Double x, Double y) private
Definition at line 406 of file MainModel.java.
References model.state.gameelement.AttributeContainer.getNumericalAttribute(), model.state.gameelement.StateTags.LEVEL_HEIGHT, model.state.gameelement.StateTags.LEVEL_WIDTH, and model.state.LevelState.myAttributes.
Referenced by model.MainModel.addTerrainToLevel(), and model.MainModel.addUnitToLevel().
void model.MainModel.clearEditorChosen ()
Definition at line 197 of file MainModel.java.
Referenced by model.MainModel.MainModel(), engine.UI.EditorInputManager.primaryClickOccurred(), model.MainModel.setEditorChosenDrawable(), and model.MainModel.setEditorChosenSelectable().
void model.MainModel.createCampaign (String campaignName) throws CampaignExistsException
called by editor when creating a new campaign
Parameters
campaignName
Exceptions
CampaignExistsException
Definition at line 216 of file MainModel.java.
References model.state.GameState.addCampaign(), and model.MainModel.updateObservers().
Referenced by view.editor.EditorMenuBarController.onNewCampaignClick().
void model.MainModel.createDrawableGameElementState (WizardData data)
called by editor when creating a new game element
Parameters
data
Definition at line 268 of file MainModel.java.
References model.data.WizardData.addDataPair(), model.GameUniverse.addDrawableGameElementState(), model.data.WizardDataType.COLOR_MASK, model.GameElementStateFactory.createDrawableGameElementState(), model.GameElementImageType.Drawable, model.state.GameState.getGameUniverse(), model.data.WizardDataType.IMAGE, model.sprite.SpriteImageGenerator.loadSpriteImageContainer(), model.state.gameelement.DrawableGameElementState.myAnimatorState, model.GameSaveLoadMediator.saveColorMask(), model.GameSaveLoadMediator.saveImage(), and model.MainModel.updateObservers().
Referenced by view.editor.ElementAccordionController.openDrawableGameElementWizard().
void model.MainModel.createGameElementState (WizardData data)
called by editor when creating a new game element
Parameters
data
Definition at line 257 of file MainModel.java.
References model.GameUniverse.addGameElementState(), model.GameElementStateFactory.createGameElementState(), model.state.GameState.getGameUniverse(), and model.MainModel.updateObservers().
void model.MainModel.createGoal (LevelState levelState, WizardData data)
Definition at line 342 of file MainModel.java.
References model.state.LevelState.addGoal(), model.GameElementStateFactory.createGoal(), and model.MainModel.updateObservers().
Referenced by view.editor.TabViewController.launchNestedWizard().
void model.MainModel.createLevel (String levelName, String campaignName, Number width, Number height, String backgroundPath) throws LevelExistsException, CampaignNotFoundException, Exception
called by editor when creating a new level under a certain campaign
Parameters
campaignName
levelName
Exceptions
LevelExistsException
Definition at line 229 of file MainModel.java.
References model.state.CampaignState.addLevel(), model.state.gameelement.StateTags.BACKGROUND_PATH, model.state.GameState.getCampaign(), model.state.gameelement.StateTags.LEVEL_HEIGHT, model.state.gameelement.StateTags.LEVEL_WIDTH, model.state.LevelState.myAttributes, model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.AttributeContainer.setTextualAttribute(), and model.MainModel.updateObservers().
Referenced by view.editor.EditorMenuBarController.onNewLevelClick().
void model.MainModel.createSelectableGameElementState (WizardData data)
called by editor when creating a new game element
Parameters
data
Definition at line 293 of file MainModel.java.
References model.data.WizardData.addDataPair(), model.GameUniverse.addSelectableGameElementState(), model.data.WizardDataType.COLOR_MASK, model.GameElementStateFactory.createSelectableGameElementState(), model.state.GameState.getGameUniverse(), model.data.WizardDataType.IMAGE, model.sprite.SpriteImageGenerator.loadSpriteImageContainer(), model.state.gameelement.DrawableGameElementState.myAnimatorState, model.GameSaveLoadMediator.saveColorMask(), model.GameSaveLoadMediator.saveImage(), model.GameElementImageType.Selectable, and model.MainModel.updateObservers().
Referenced by view.editor.ElementAccordionController.openSelectableGameElementWizard().
boolean model.MainModel.elementIsInUse (String elementName) private
Definition at line 327 of file MainModel.java.
References model.state.GameState.getCampaigns().
Referenced by model.MainModel.removeDrawableGameElement(), and model.MainModel.removeSelectableGameElement().
SpriteImageContainer model.MainModel.fetchImageContainer (String imageTag)
Parameters
imageTag
Returns
Exceptions
Exception
Definition at line 436 of file MainModel.java.
References model.sprite.SpriteImageGenerator.fetchImageContainer(), model.sprite.SpriteImageContainer.getColorMask(), and model.sprite.SpriteImageContainer.getSpritesheet().
Referenced by engine.elementFactories.AnimatorFactory.createAnimator().
CampaignState model.MainModel.getCampaign (String campaignName) throws CampaignNotFoundException
Definition at line 175 of file MainModel.java.
References model.state.GameState.getCampaign().
Referenced by model.MainModel.getLevel(), and model.MainModel.setLevel().
GameState model.MainModel.getCurrentGame ()
Definition at line 159 of file MainModel.java.
References model.MainModel.myGameState.
Referenced by view.runner.GameRunnerPaneController.engineUpdate(), view.editor.EditorMenuBarController.onNewLevelClick(), view.runner.RunnerScreen.updateLevelChooser(), and view.editor.EditorScreen.updateProjectExplorer().
DescribableState model.MainModel.getDescribableState (String[] selection) throws CampaignNotFoundException, LevelNotFoundException
Definition at line 143 of file MainModel.java.
References model.state.GameState.getCampaign(), model.state.CampaignState.getLevel(), and model.MainModel.myGameState.
Referenced by model.MainModel.updateDescribableState(), and view.editor.EditorScreen.updateInfoBox().
long model.MainModel.getEditorChosenColor ()
Definition at line 183 of file MainModel.java.
Referenced by engine.UI.EditorInputManager.primaryClickOccurred().
String model.MainModel.getEditorChosenDrawable ()
Definition at line 206 of file MainModel.java.
References model.MainModel.myEditorChosenDrawableElement.
Referenced by engine.UI.EditorInputManager.primaryClickOccurred().
String model.MainModel.getEditorChosenSelectable ()
Definition at line 202 of file MainModel.java.
References model.MainModel.myEditorChosenSelectableElement.
Referenced by engine.UI.EditorInputManager.primaryClickOccurred().
GameUniverse model.MainModel.getGameUniverse ()
gets the game universe (list of all elements that could be used in the currently selected game
Returns
Definition at line 426 of file MainModel.java.
References model.state.GameState.getGameUniverse().
Referenced by view.editor.TabViewController.addNumberAttributes(), view.editor.ElementAccordionController.addNumberAttributes(), model.MainModel.addParticipantColor(), view.editor.ElementAccordionController.addStringAttributes(), model.MainModel.addTerrainToLevel(), model.MainModel.addUnitToLevel(), application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), view.editor.ElementAccordionController.init(), engine.Engine.instantiateFactories(), view.editor.ElementAccordionController.modelUpdate(), model.MainModel.newGame(), view.editor.ElementAccordionController.openDrawableGameElementWizard(), view.editor.ElementAccordionController.openSelectableGameElementWizard(), model.MainModel.removeDrawableGameElement(), model.MainModel.removeSelectableGameElement(), model.MainModel.setTerrain(), and view.editor.EditorScreen.updateParticipantDropDown().
LevelState model.MainModel.getLevel (LevelIdentifier levelID) throws LevelNotFoundException, CampaignNotFoundException
Definition at line 163 of file MainModel.java.
References model.MainModel.getCampaign(), and model.state.CampaignState.getLevel().
Referenced by application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), view.runner.RunnerScreen.playLevel(), view.editor.TabViewController.setLevel(), and model.MainModel.setLevel().
void model.MainModel.loadGame (String game) throws LanguagePropertyNotFoundException
Sets the game of the Model.
Parameters
game
Exceptions
LanguagePropertyNotFoundException
Definition at line 72 of file MainModel.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), model.GameSaveLoadMediator.loadGame(), model.MainModel.updateObservers(), and model.MainModel.updateSpritesAndMasks().
Referenced by application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), and view.splash.SplashScreen.loadGameAndSwitchScreen().
void model.MainModel.newGame (String gameName)
Definition at line 60 of file MainModel.java.
References model.GameUniverse.addParticipantColor(), engine.Engine.DEFAULT_PLAYER_COLOR_STRING, and model.MainModel.getGameUniverse().
Referenced by view.splash.SplashScreen.setUpButtons().
void model.MainModel.removeDrawableGameElement (String elementName) throws ElementInUseException
Definition at line 313 of file MainModel.java.
References model.MainModel.elementIsInUse(), model.MainModel.getGameUniverse(), model.GameUniverse.removeDrawableGameElementState(), and model.MainModel.updateObservers().
Referenced by view.editor.ElementAccordionController.init().
void model.MainModel.removeGoal (LevelState levelState, int index)
Definition at line 348 of file MainModel.java.
References model.state.LevelState.getGoals(), and model.MainModel.updateObservers().
Referenced by view.editor.TabViewController.deleteGoal().
void model.MainModel.removeSelectableGameElement (String elementName) throws ElementInUseException
Definition at line 320 of file MainModel.java.
References model.MainModel.elementIsInUse(), model.MainModel.getGameUniverse(), model.GameUniverse.removeSelectableGameElementState(), and model.MainModel.updateObservers().
Referenced by view.editor.ElementAccordionController.init().
void model.MainModel.saveGame () throws RuntimeException
Definition at line 110 of file MainModel.java.
Referenced by application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), view.runner.RunnerMenuBarController.initFileMenu(), and view.editor.EditorMenuBarController.saveGame().
void model.MainModel.saveGame (GameState game)
Definition at line 114 of file MainModel.java.
References view.splash.SplashScreen.EXISTING_GAMES, model.state.DescribableState.getName(), util.SaveLoadUtility.loadResource(), util.SaveLoadUtility.save(), and model.GameSaveLoadMediator.saveGame().
void model.MainModel.setEditorChosenColor (String color)
Definition at line 179 of file MainModel.java.
Referenced by view.editor.EditorScreen.initParticipantInfo().
void model.MainModel.setEditorChosenDrawable (String elementName)
Definition at line 187 of file MainModel.java.
References model.MainModel.clearEditorChosen().
Referenced by view.editor.ElementAccordionController.editorChooseDrawableElement().
void model.MainModel.setEditorChosenSelectable (String elementName)
Definition at line 192 of file MainModel.java.
References model.MainModel.clearEditorChosen().
Referenced by view.editor.ElementAccordionController.editorChooseSelectableElement().
void model.MainModel.setLevel (LevelIdentifier levelID, LevelState levelState) throws CampaignNotFoundException, LevelNotFoundException
Definition at line 168 of file MainModel.java.
References model.MainModel.getCampaign(), model.MainModel.getLevel(), and model.state.CampaignState.getLevels().
Referenced by view.editor.TabViewController.updateModelToSave().
void model.MainModel.setTerrain (LevelState levelState, String terrainName)
Definition at line 372 of file MainModel.java.
References model.state.LevelState.addTerrain(), model.GameUniverse.getDrawableGameElementState(), model.MainModel.getGameUniverse(), model.state.gameelement.AttributeContainer.getNumericalAttribute(), model.state.gameelement.StateTags.LEVEL_HEIGHT, model.state.gameelement.StateTags.LEVEL_WIDTH, model.state.LevelState.myAttributes, model.state.gameelement.GameElementState.myAttributes, model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
void model.MainModel.updateDescribableState (String[] selection, String name, String description) throws CampaignNotFoundException, LevelNotFoundException
Definition at line 134 of file MainModel.java.
References model.MainModel.getDescribableState(), model.state.DescribableState.updateDescription(), model.state.DescribableState.updateName(), and model.MainModel.updateObservers().
Referenced by view.editor.EditorScreen.initInfoBox().
void model.MainModel.updateObservers () private
Definition at line 414 of file MainModel.java.
Referenced by model.MainModel.addParticipantColor(), model.MainModel.createCampaign(), model.MainModel.createDrawableGameElementState(), model.MainModel.createGameElementState(), model.MainModel.createGoal(), model.MainModel.createLevel(), model.MainModel.createSelectableGameElementState(), model.MainModel.loadGame(), model.MainModel.removeDrawableGameElement(), model.MainModel.removeGoal(), model.MainModel.removeSelectableGameElement(), and model.MainModel.updateDescribableState().
void model.MainModel.updateSpritesAndMasks () private
Definition at line 89 of file MainModel.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), model.GameUniverse.getDrawableGameElementStates(), model.state.GameState.getGameUniverse(), model.GameUniverse.getSelectableGameElementStates(), and model.GameSaveLoadMediator.loadSpritesAndMasks().
Referenced by model.MainModel.loadGame().
Member Data Documentation
final String model.MainModel.LOAD_GAME_ERROR_KEY = "LoadGameError" static private
Definition at line 46 of file MainModel.java.
String model.MainModel.myEditorChosenColor private
Definition at line 50 of file MainModel.java.
String model.MainModel.myEditorChosenDrawableElement private
Definition at line 49 of file MainModel.java.
Referenced by model.MainModel.getEditorChosenDrawable().
String model.MainModel.myEditorChosenSelectableElement private
Definition at line 48 of file MainModel.java.
Referenced by model.MainModel.getEditorChosenSelectable().
GameState model.MainModel.myGameState private
Definition at line 47 of file MainModel.java.
Referenced by model.MainModel.getCurrentGame(), and model.MainModel.getDescribableState().
GameSaveLoadMediator model.MainModel.mySaveLoadMediator private
Definition at line 51 of file MainModel.java.
SpriteImageGenerator model.MainModel.mySpriteImageGenerator private
Definition at line 52 of file MainModel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/MainModel.java