voogasalad_TheException: view.editor.wizards.PositionWizard Class Reference
view.editor.wizards.PositionWizard Class Reference
Public Member Functions
boolean checkCanSave ()
void updateData ()
void launchForEdit (WizardData oldValues)
void loadGlobalValues (List< String > values)
Public Member Functions inherited from view.editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
abstract void launchForEdit (WizardData oldValues)
abstract void loadGlobalValues (List< String > values)
WizardData getWizardData ()
void displayErrorMessage (String error)
void removeWizardData (WizardData data)
void setStage (Stage s)
void closeStage ()
Protected Member Functions
void attachTextProperties ()
Protected Member Functions inherited from view.editor.wizards.Wizard
void addToData (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void setWizardType (WizardType type)
void attachTextProperties ()
boolean isNumber (String value)
Protected Attributes
TextField xValue
TextField yValue
Protected Attributes inherited from view.editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Private Attributes
final String X_VALUE_KEY = "XValue"
final String Y_VALUE_KEY = "YValue"
Additional Inherited Members
Static Public Attributes inherited from view.editor.wizards.Wizard
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
Detailed Description
Wizard for setting position of a GameElementState to add to a level
Author
Nishad
Definition at line 19 of file PositionWizard.java.
Member Function Documentation
void view.editor.wizards.PositionWizard.attachTextProperties () protected
Definition at line 43 of file PositionWizard.java.
References view.editor.wizards.Wizard.displayErrorMessage(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
boolean view.editor.wizards.PositionWizard.checkCanSave ()
Definition at line 30 of file PositionWizard.java.
References view.editor.wizards.Wizard.isNumber().
void view.editor.wizards.PositionWizard.launchForEdit (WizardData oldValues)
Definition at line 57 of file PositionWizard.java.
References model.data.WizardData.getValueByKey(), model.data.WizardDataType.X_POSITION, and model.data.WizardDataType.Y_POSITION.
void view.editor.wizards.PositionWizard.loadGlobalValues (List< String > values)
Definition at line 63 of file PositionWizard.java.
void view.editor.wizards.PositionWizard.updateData ()
Definition at line 36 of file PositionWizard.java.
References view.editor.wizards.Wizard.addToData(), model.data.WizardType.POSITION, view.editor.wizards.Wizard.setWizardType(), model.data.WizardDataType.X_POSITION, and model.data.WizardDataType.Y_POSITION.
Member Data Documentation
final String view.editor.wizards.PositionWizard.X_VALUE_KEY = "XValue" private
Definition at line 26 of file PositionWizard.java.
TextField view.editor.wizards.PositionWizard.xValue protected
Definition at line 22 of file PositionWizard.java.
final String view.editor.wizards.PositionWizard.Y_VALUE_KEY = "YValue" private
Definition at line 27 of file PositionWizard.java.
TextField view.editor.wizards.PositionWizard.yValue protected
Definition at line 24 of file PositionWizard.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/PositionWizard.java