voogasalad_TheException: game_engine.gameRepresentation.evaluatables.Evaluatable< T > Class Template Reference
game_engine.gameRepresentation.evaluatables.Evaluatable< T > Class Template Reference abstract
Public Member Functions
Evaluatable (Class< T > type, String id)
abstract T evaluate (ElementPair elements)
T evaluate ()
boolean setValue (ElementPair elements, T value)
boolean setValue (T value)
Class< T > getType ()
String getID ()
Private Attributes
Class< T > myType
String myID
Detailed Description
An object that can evaluate a condition on an element to return a value. Evaluators are generics to allow for the implementation of complex logic with evaluatables. Evaluatables have the option to both get and set values although the value setting is not by default implemented by children of evaluatable.
Author
Zach
Definition at line 13 of file Evaluatable.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.evaluatables.Evaluatable< T >.Evaluatable (Class< T > type, String id)
Create an evaluatable
Parameters
type the type of the class T of the evaluatable. Used as a workaround for the poor implementation of generics by Java
id an id that will be shared amongst all elements of an evaluatable tree. it allows leaves of the tree to reference higher up nodes.
Definition at line 26 of file Evaluatable.java.
Member Function Documentation
abstract T game_engine.gameRepresentation.evaluatables.Evaluatable< T >.evaluate (ElementPair elements) abstract
Take in a pair of elements, evaluate a condition on the elements, and return a boolean representing the condition's return value.
Referenced by game_engine.gameRepresentation.evaluatables.evaluators.IfThenEvaluator< A, B >.evaluate(), and game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.evaluate().
T game_engine.gameRepresentation.evaluatables.Evaluatable< T >.evaluate ()
Use the null pattern to evaluate a condition if no elements are given
Definition at line 41 of file Evaluatable.java.
Referenced by game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.delegateEvaluator(), and game_engine.gameRepresentation.evaluatables.Evaluatable<?>.evaluate().
String game_engine.gameRepresentation.evaluatables.Evaluatable< T >.getID ()
Get the current ID of the evlauatable
the evaluatable's ID string
Definition at line 77 of file Evaluatable.java.
Class<T> game_engine.gameRepresentation.evaluatables.Evaluatable< T >.getType ()
Get the type of the object as a way of bypassing Java type erasure
Returns
the generic's type
Definition at line 68 of file Evaluatable.java.
Referenced by game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.delegateEvaluator(), and game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.setParameter1Value().
boolean game_engine.gameRepresentation.evaluatables.Evaluatable< T >.setValue (ElementPair elements, T value)
Sets the evaluatable's value to a given value
Parameters
value the value to set the evaluatable's stored computation value to
Returns
a boolean indicating whether setting was successful
Definition at line 52 of file Evaluatable.java.
Referenced by game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.setParameter1Value(), and game_engine.gameRepresentation.evaluatables.Evaluatable<?>.setValue().
boolean game_engine.gameRepresentation.evaluatables.Evaluatable< T >.setValue (T value)
Use the null pattern to set a value if no element pair is applicable
Definition at line 59 of file Evaluatable.java.
Member Data Documentation
String game_engine.gameRepresentation.evaluatables.Evaluatable< T >.myID private
Definition at line 15 of file Evaluatable.java.
Referenced by game_engine.gameRepresentation.evaluatables.Evaluatable<?>.getID().
Class<T> game_engine.gameRepresentation.evaluatables.Evaluatable< T >.myType private
Definition at line 14 of file Evaluatable.java.
Referenced by game_engine.gameRepresentation.evaluatables.Evaluatable<?>.getType().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/evaluatables/Evaluatable.java