voogasalad_TheException: view.splash.SplashScreen Class Reference
view.splash.SplashScreen Class Reference
Public Member Functions
Node getRoot ()
void init ()
void modelUpdate ()
Public Member Functions inherited from view.gui.GUIScreen
void attachSceneHandler (MainView mainView)
void switchScreen (ViewScreenPath screen)
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Static Public Attributes
static final String EXISTING_GAMES
Private Member Functions
void setUpButtons ()
void loadGameAndSwitchScreen (ViewScreenPath path)
void drawTitle ()
void attachStringProperties ()
Private Attributes
GridPane splash
Button launchEditorButton
Button launchRunnerButton
ComboBox< String > myGames
ComboBox< String > gameDropDown
Button newGameButton
Label title
Static Private Attributes
static final String LAUNCH_EDITOR_KEY = "LaunchEditor"
static final String LAUNCH_RUNNER_KEY = "LaunchRunner"
static final String NEW_GAME_KEY = "NewGame"
static final String CHOOSE_GAME_KEY = "ChooseGame"
static final String DEFAULT_NEW_GAME_KEY = "NewGameDefault"
static final String NO_GAME_SELECT_ERROR_KEY = "NoGameSelectedError"
static final String DUVALL_PATH = "resources/duvall.txt"
static final Integer LOAD_DURATION = 1
Additional Inherited Members
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Detailed Description
Author
Jonathan
Nishad
Joshua
Definition at line 38 of file SplashScreen.java.
Member Function Documentation
void view.splash.SplashScreen.attachStringProperties () private
Definition at line 149 of file SplashScreen.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.splash.SplashScreen.setUpButtons().
void view.splash.SplashScreen.drawTitle () private
Definition at line 129 of file SplashScreen.java.
Referenced by view.splash.SplashScreen.init().
Node view.splash.SplashScreen.getRoot ()
Implements view.gui.GUIController.
Definition at line 69 of file SplashScreen.java.
References view.splash.SplashScreen.splash.
void view.splash.SplashScreen.init ()
Definition at line 74 of file SplashScreen.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), view.splash.SplashScreen.drawTitle(), util.SaveLoadUtility.loadResource(), and view.splash.SplashScreen.setUpButtons().
void view.splash.SplashScreen.loadGameAndSwitchScreen (ViewScreenPath path) private
Definition at line 108 of file SplashScreen.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), model.MainModel.loadGame(), view.gui.GUIContainer.myMainModel, and view.gui.GUIScreen.switchScreen().
Referenced by view.splash.SplashScreen.setUpButtons().
void view.splash.SplashScreen.modelUpdate ()
Definition at line 164 of file SplashScreen.java.
void view.splash.SplashScreen.setUpButtons () private
Definition at line 88 of file SplashScreen.java.
References view.splash.SplashScreen.attachStringProperties(), view.dialog.DialogBoxUtility.createMessageDialog(), view.gui.ViewScreenPath.EDITOR, util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), view.splash.SplashScreen.loadGameAndSwitchScreen(), view.gui.GUIContainer.myMainModel, model.MainModel.newGame(), view.gui.ViewScreenPath.RUNNER, and view.gui.GUIScreen.switchScreen().
Referenced by view.splash.SplashScreen.init().
Member Data Documentation
final String view.splash.SplashScreen.CHOOSE_GAME_KEY = "ChooseGame" static private
Definition at line 43 of file SplashScreen.java.
final String view.splash.SplashScreen.DEFAULT_NEW_GAME_KEY = "NewGameDefault" static private
Definition at line 44 of file SplashScreen.java.
final String view.splash.SplashScreen.DUVALL_PATH = "resources/duvall.txt" static private
Definition at line 47 of file SplashScreen.java.
final String view.splash.SplashScreen.EXISTING_GAMES static
Initial value:
=
            "src/resources/properties/view/existingGames.json"
Definition at line 48 of file SplashScreen.java.
Referenced by model.MainModel.saveGame().
ComboBox<String> view.splash.SplashScreen.gameDropDown private
Definition at line 62 of file SplashScreen.java.
final String view.splash.SplashScreen.LAUNCH_EDITOR_KEY = "LaunchEditor" static private
Definition at line 40 of file SplashScreen.java.
final String view.splash.SplashScreen.LAUNCH_RUNNER_KEY = "LaunchRunner" static private
Definition at line 41 of file SplashScreen.java.
Button view.splash.SplashScreen.launchEditorButton private
Definition at line 55 of file SplashScreen.java.
Button view.splash.SplashScreen.launchRunnerButton private
Definition at line 57 of file SplashScreen.java.
final Integer view.splash.SplashScreen.LOAD_DURATION = 1 static private
Definition at line 50 of file SplashScreen.java.
ComboBox<String> view.splash.SplashScreen.myGames private
Definition at line 59 of file SplashScreen.java.
final String view.splash.SplashScreen.NEW_GAME_KEY = "NewGame" static private
Definition at line 42 of file SplashScreen.java.
Button view.splash.SplashScreen.newGameButton private
Definition at line 64 of file SplashScreen.java.
final String view.splash.SplashScreen.NO_GAME_SELECT_ERROR_KEY = "NoGameSelectedError" static private
Definition at line 45 of file SplashScreen.java.
GridPane view.splash.SplashScreen.splash private
Definition at line 53 of file SplashScreen.java.
Referenced by view.splash.SplashScreen.getRoot().
Label view.splash.SplashScreen.title private
Definition at line 66 of file SplashScreen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/splash/SplashScreen.java