voogasalad_TheException: editor.ElementAccordionController Class Reference
editor.ElementAccordionController Class Reference
Public Member Functions
Node getRoot ()
void init ()
void updateItems (List< ImageElementPair > items)
void update ()
Public Member Functions inherited from view.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
abstract void update ()
Private Member Functions
Consumer< Consumer< WizardData > > openGameElementWizard ()
Private Attributes
Accordion elementAccordion
Static Private Attributes
static final String TERRAIN_WIZARD = "/editor/wizards/guipanes/TerrainWizard.fxml"
static final String GAME_ELEMENT_WIZARD
static final String ACCORDION_SUBPANE_PATH
static final String ELEMENT_KEY = "GameElement"
Additional Inherited Members
Protected Member Functions inherited from view.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.GUIContainer
MainModel myMainModel
Detailed Description
Definition at line 21 of file ElementAccordionController.java.
Member Function Documentation
Node editor.ElementAccordionController.getRoot ()
Implements view.GUIController.
Definition at line 35 of file ElementAccordionController.java.
void editor.ElementAccordionController.init ()
Definition at line 40 of file ElementAccordionController.java.
Consumer<Consumer<WizardData> > editor.ElementAccordionController.openGameElementWizard () private
Definition at line 62 of file ElementAccordionController.java.
References gamemodel.MainModel.createDrawableGameElement(), editor.wizards.Wizard.getStage(), view.WizardUtility.loadWizard(), view.GUIContainer.myMainModel, and editor.wizards.Wizard.setSubmit().
Referenced by editor.ElementAccordionController.updateItems().
void editor.ElementAccordionController.update ()
Definition at line 75 of file ElementAccordionController.java.
void editor.ElementAccordionController.updateItems (List< ImageElementPair > items)
Definition at line 43 of file ElementAccordionController.java.
References editor.ElementDropDownController.addElement(), editor.ElementDropDownController.bindGameElement(), util.multilanguage.MultiLanguageUtility.getInstance(), editor.ElementDropDownController.getRoot(), util.multilanguage.MultiLanguageUtility.getStringProperty(), editor.ElementAccordionController.openGameElementWizard(), and editor.ElementDropDownController.setButtonAction().
Referenced by editor.EditorScreen.updateAccordion().
Member Data Documentation
final String editor.ElementAccordionController.ACCORDION_SUBPANE_PATH static private
Initial value:
=
            "/editor/guipanes/GameElementDropDown.fxml"
Definition at line 26 of file ElementAccordionController.java.
final String editor.ElementAccordionController.ELEMENT_KEY = "GameElement" static private
Definition at line 29 of file ElementAccordionController.java.
Accordion editor.ElementAccordionController.elementAccordion private
Definition at line 32 of file ElementAccordionController.java.
final String editor.ElementAccordionController.GAME_ELEMENT_WIZARD static private
Initial value:
=
            "/editor/wizards/guipanes/DrawableGameElementWizard.fxml"
Definition at line 24 of file ElementAccordionController.java.
final String editor.ElementAccordionController.TERRAIN_WIZARD = "/editor/wizards/guipanes/TerrainWizard.fxml" static private
Definition at line 23 of file ElementAccordionController.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/ElementAccordionController.java