voogasalad_TheException: engine.computers.pathingComputers.MapGrid Class Reference
engine.computers.pathingComputers.MapGrid Class Reference
Public Member Functions
MapGrid (Number mapWidth, Number mapHeight)
List< Location > getNeighbors (Location centerLocation)
List< Location > getNeighborsForXYCoordinate (Location XY)
String toString ()
List< Location > getImpassableLocations ()
void registerObstaclePlacement (double[] bounds)
void registerObstacleRemoval (double[] bounds)
Static Public Attributes
static final int TILE_WIDTH = 96
static final int TILE_HEIGHT = 48
Private Member Functions
void initializeGrid ()
void alterLocationsInsideBounds (double[] bounds, BiConsumer< Integer, Integer > alteringFunction)
Private Attributes
Location[][] locationGrid
Detailed Description
Definition at line 10 of file MapGrid.java.
Constructor & Destructor Documentation
engine.computers.pathingComputers.MapGrid.MapGrid (Number mapWidth, Number mapHeight)
Definition at line 15 of file MapGrid.java.
References engine.computers.pathingComputers.MapGrid.initializeGrid(), engine.computers.pathingComputers.MapGrid.TILE_HEIGHT, and engine.computers.pathingComputers.MapGrid.TILE_WIDTH.
Member Function Documentation
void engine.computers.pathingComputers.MapGrid.alterLocationsInsideBounds (double[] bounds, BiConsumer< Integer, Integer > alteringFunction) private
Definition at line 115 of file MapGrid.java.
References engine.computers.pathingComputers.Location.getX(), engine.computers.pathingComputers.Location.getY(), and engine.computers.pathingComputers.MapGrid.TILE_WIDTH.
Referenced by engine.computers.pathingComputers.MapGrid.registerObstaclePlacement(), and engine.computers.pathingComputers.MapGrid.registerObstacleRemoval().
List<Location> engine.computers.pathingComputers.MapGrid.getImpassableLocations ()
Definition at line 94 of file MapGrid.java.
List<Location> engine.computers.pathingComputers.MapGrid.getNeighbors (Location centerLocation)
To be used to find neighbors from a Location that was generated by this grid - i.e. one that has myX and myY as multiples of TILE_WIDTH and TILE_HEIGHT, respectively.
Parameters
centerLocation
Returns
Definition at line 37 of file MapGrid.java.
References engine.computers.pathingComputers.Location.getX(), engine.computers.pathingComputers.Location.getY(), engine.computers.pathingComputers.MapGrid.TILE_HEIGHT, and engine.computers.pathingComputers.MapGrid.TILE_WIDTH.
Referenced by engine.computers.pathingComputers.PathingComputer.computePath().
List<Location> engine.computers.pathingComputers.MapGrid.getNeighborsForXYCoordinate (Location XY)
To be used to find neighbors from a Location that does not exist in the grid - i.e. one that lies between grid points.
Parameters
x
y
Returns
Definition at line 66 of file MapGrid.java.
References engine.computers.pathingComputers.Location.getX(), engine.computers.pathingComputers.Location.getY(), engine.computers.pathingComputers.MapGrid.TILE_HEIGHT, and engine.computers.pathingComputers.MapGrid.TILE_WIDTH.
Referenced by engine.computers.pathingComputers.PathingComputer.computePath(), and engine.computers.pathingComputers.PathingComputer.reconstructPath().
void engine.computers.pathingComputers.MapGrid.initializeGrid () private
Definition at line 22 of file MapGrid.java.
Referenced by engine.computers.pathingComputers.MapGrid.MapGrid().
void engine.computers.pathingComputers.MapGrid.registerObstaclePlacement (double[] bounds)
Definition at line 106 of file MapGrid.java.
References engine.computers.pathingComputers.MapGrid.alterLocationsInsideBounds().
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement(), and engine.elementFactories.LevelFactory.updateGridForObstacles().
void engine.computers.pathingComputers.MapGrid.registerObstacleRemoval (double[] bounds)
Definition at line 110 of file MapGrid.java.
References engine.computers.pathingComputers.MapGrid.alterLocationsInsideBounds().
String engine.computers.pathingComputers.MapGrid.toString ()
Definition at line 82 of file MapGrid.java.
References engine.computers.pathingComputers.Location.toString().
Member Data Documentation
Location [][] engine.computers.pathingComputers.MapGrid.locationGrid private
Definition at line 13 of file MapGrid.java.
final int engine.computers.pathingComputers.MapGrid.TILE_HEIGHT = 48 static
Definition at line 12 of file MapGrid.java.
Referenced by engine.computers.pathingComputers.MapGrid.getNeighbors(), engine.computers.pathingComputers.MapGrid.getNeighborsForXYCoordinate(), and engine.computers.pathingComputers.MapGrid.MapGrid().
final int engine.computers.pathingComputers.MapGrid.TILE_WIDTH = 96 static
Definition at line 11 of file MapGrid.java.
Referenced by engine.computers.pathingComputers.MapGrid.alterLocationsInsideBounds(), engine.computers.pathingComputers.MapGrid.getNeighbors(), engine.computers.pathingComputers.MapGrid.getNeighborsForXYCoordinate(), and engine.computers.pathingComputers.MapGrid.MapGrid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/computers/pathingComputers/MapGrid.java