voogasalad_TheException: view.editor.wizards.BoundsWizard Class Reference
view.editor.wizards.BoundsWizard Class Reference
Public Member Functions
void initialize ()
boolean checkCanSave ()
void updateData ()
void launchForEdit (WizardData oldValues)
void loadGlobalValues (List< String > values)
Public Member Functions inherited from view.editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
abstract void launchForEdit (WizardData oldValues)
abstract void loadGlobalValues (List< String > values)
WizardData getWizardData ()
void displayErrorMessage (String error)
void removeWizardData (WizardData data)
void setStage (Stage s)
void closeStage ()
Private Member Functions
void addXYPair (String x, String y)
boolean checkCoordinatesValid (List< TextField > coordinates)
String getCoordinates ()
Private Attributes
VBox allPoints
Button addPoint
List< TextField > xCoordinates
List< TextField > yCoordinates
Static Private Attributes
static final String ADD_POINT_KEY = "AddPoint"
static final String X_COR_KEY = "XCoordinate"
static final String Y_COR_KEY = "YCoordinate"
Additional Inherited Members
Static Public Attributes inherited from view.editor.wizards.Wizard
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
Protected Member Functions inherited from view.editor.wizards.Wizard
void addToData (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void setWizardType (WizardType type)
void attachTextProperties ()
boolean isNumber (String value)
Protected Attributes inherited from view.editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Detailed Description
This represents the Wizard used to accept a numerical value with an attribute name. It checks whether the inputted value is numeric, and then stores this value as a string, to conform with the WizardData data structure.
Author
Joshua, Nishad
Definition at line 27 of file BoundsWizard.java.
Member Function Documentation
void view.editor.wizards.BoundsWizard.addXYPair (String x, String y) private
Definition at line 57 of file BoundsWizard.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.editor.wizards.BoundsWizard.initialize(), and view.editor.wizards.BoundsWizard.launchForEdit().
boolean view.editor.wizards.BoundsWizard.checkCanSave ()
Definition at line 84 of file BoundsWizard.java.
References view.editor.wizards.BoundsWizard.checkCoordinatesValid().
boolean view.editor.wizards.BoundsWizard.checkCoordinatesValid (List< TextField > coordinates) private
Definition at line 89 of file BoundsWizard.java.
References view.editor.wizards.Wizard.isNumber().
Referenced by view.editor.wizards.BoundsWizard.checkCanSave().
String view.editor.wizards.BoundsWizard.getCoordinates () private
Definition at line 96 of file BoundsWizard.java.
Referenced by view.editor.wizards.BoundsWizard.updateData().
void view.editor.wizards.BoundsWizard.initialize ()
Implements view.gui.GUIController.
Definition at line 42 of file BoundsWizard.java.
References view.editor.wizards.BoundsWizard.addXYPair(), view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
void view.editor.wizards.BoundsWizard.launchForEdit (WizardData oldValues)
Definition at line 112 of file BoundsWizard.java.
References view.editor.wizards.BoundsWizard.addXYPair(), model.data.WizardDataType.BOUND_VALUES, and model.data.WizardData.getValueByKey().
void view.editor.wizards.BoundsWizard.loadGlobalValues (List< String > values)
Definition at line 121 of file BoundsWizard.java.
void view.editor.wizards.BoundsWizard.updateData ()
Definition at line 106 of file BoundsWizard.java.
References view.editor.wizards.Wizard.addToData(), model.data.WizardDataType.BOUND_VALUES, model.data.WizardType.BOUNDS, view.editor.wizards.BoundsWizard.getCoordinates(), and view.editor.wizards.Wizard.setWizardType().
Member Data Documentation
final String view.editor.wizards.BoundsWizard.ADD_POINT_KEY = "AddPoint" static private
Definition at line 29 of file BoundsWizard.java.
Button view.editor.wizards.BoundsWizard.addPoint private
Definition at line 36 of file BoundsWizard.java.
VBox view.editor.wizards.BoundsWizard.allPoints private
Definition at line 34 of file BoundsWizard.java.
final String view.editor.wizards.BoundsWizard.X_COR_KEY = "XCoordinate" static private
Definition at line 30 of file BoundsWizard.java.
List<TextField> view.editor.wizards.BoundsWizard.xCoordinates private
Definition at line 38 of file BoundsWizard.java.
final String view.editor.wizards.BoundsWizard.Y_COR_KEY = "YCoordinate" static private
Definition at line 31 of file BoundsWizard.java.
List<TextField> view.editor.wizards.BoundsWizard.yCoordinates private
Definition at line 39 of file BoundsWizard.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/BoundsWizard.java