voogasalad_TheException: editor.wizards.GridLines Class Reference
editor.wizards.GridLines Class Reference
Public Member Functions
GridLines (double imageWidth, double imageHeight, double frameX, double frameY)
void changeSize (double frameX, double frameY)
double getFrameX ()
double getFrameY ()
Private Member Functions
void createGridLines ()
void createRows ()
Line createRow ()
void createColumns ()
Line createColumn ()
Private Attributes
double myWidth
double myHeight
double myFrameX
double myFrameY
Detailed Description
Grid Lines
Author
Jonathan Tseng, Nishad Agrawal
Definition at line 13 of file GridLines.java.
Constructor & Destructor Documentation
editor.wizards.GridLines.GridLines (double imageWidth, double imageHeight, double frameX, double frameY)
Definition at line 19 of file GridLines.java.
References editor.wizards.GridLines.changeSize().
Member Function Documentation
void editor.wizards.GridLines.changeSize (double frameX, double frameY)
Definition at line 25 of file GridLines.java.
References editor.wizards.GridLines.createGridLines().
Referenced by editor.wizards.DrawableGameElementWizard.createSliderListeners(), and editor.wizards.GridLines.GridLines().
Line editor.wizards.GridLines.createColumn () private
Definition at line 64 of file GridLines.java.
Referenced by editor.wizards.GridLines.createColumns().
void editor.wizards.GridLines.createColumns () private
Definition at line 55 of file GridLines.java.
References editor.wizards.GridLines.createColumn().
Referenced by editor.wizards.GridLines.createGridLines().
void editor.wizards.GridLines.createGridLines () private
Definition at line 32 of file GridLines.java.
References editor.wizards.GridLines.createColumns(), and editor.wizards.GridLines.createRows().
Referenced by editor.wizards.GridLines.changeSize().
Line editor.wizards.GridLines.createRow () private
Definition at line 46 of file GridLines.java.
Referenced by editor.wizards.GridLines.createRows().
void editor.wizards.GridLines.createRows () private
Definition at line 37 of file GridLines.java.
References editor.wizards.GridLines.createRow().
Referenced by editor.wizards.GridLines.createGridLines().
double editor.wizards.GridLines.getFrameX ()
Definition at line 73 of file GridLines.java.
References editor.wizards.GridLines.myFrameX.
Referenced by editor.wizards.DrawableGameElementWizard.createSliderListeners().
double editor.wizards.GridLines.getFrameY ()
Definition at line 77 of file GridLines.java.
References editor.wizards.GridLines.myFrameY.
Referenced by editor.wizards.DrawableGameElementWizard.createSliderListeners().
Member Data Documentation
double editor.wizards.GridLines.myFrameX private
Definition at line 16 of file GridLines.java.
Referenced by editor.wizards.GridLines.getFrameX().
double editor.wizards.GridLines.myFrameY private
Definition at line 17 of file GridLines.java.
Referenced by editor.wizards.GridLines.getFrameY().
double editor.wizards.GridLines.myHeight private
Definition at line 15 of file GridLines.java.
double editor.wizards.GridLines.myWidth private
Definition at line 14 of file GridLines.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/wizards/GridLines.java