voogasalad_TheException: model.sprite.SpriteImageContainer Class Reference
model.sprite.SpriteImageContainer Class Reference
Public Member Functions
SpriteImageContainer (ImageView spritesheet, ImageView colorMask)
SpriteImageContainer (String spritesheetTag, String colorMaskTag) throws SaveLoadException
ImageView getSpritesheet ()
ImageView getColorMask ()
ImageView getColorMask (long color)
Private Member Functions
void locateColorMask (String colorMaskTag) throws SaveLoadException
void locateSpritesheet (String spritesheetTag) throws SaveLoadException
Private Attributes
ImageView mySpritesheet
ImageView myColorMask
Detailed Description
Passive data structure that wraps an animation spritesheet with a color mask for team identification. This is given to the Animator allowing for access to the spritsheet and color mask fundamental to visual rendering of game elements.
Author
Rahul
Definition at line 20 of file SpriteImageContainer.java.
Constructor & Destructor Documentation
model.sprite.SpriteImageContainer.SpriteImageContainer (ImageView spritesheet, ImageView colorMask)
Definition at line 24 of file SpriteImageContainer.java.
model.sprite.SpriteImageContainer.SpriteImageContainer (String spritesheetTag, String colorMaskTag) throws SaveLoadException
Definition at line 29 of file SpriteImageContainer.java.
References model.sprite.SpriteImageContainer.locateColorMask(), and model.sprite.SpriteImageContainer.locateSpritesheet().
Member Function Documentation
ImageView model.sprite.SpriteImageContainer.getColorMask ()
Definition at line 47 of file SpriteImageContainer.java.
References model.sprite.SpriteImageContainer.myColorMask.
Referenced by engine.visuals.elementVisuals.animations.Animator.Animator(), and model.MainModel.fetchImageContainer().
ImageView model.sprite.SpriteImageContainer.getColorMask (long color)
Parameters
color
Returns
Definition at line 56 of file SpriteImageContainer.java.
References model.sprite.ColorMapGenerator.colorFromLong(), and model.sprite.SpriteImageContainer.myColorMask.
ImageView model.sprite.SpriteImageContainer.getSpritesheet ()
Definition at line 43 of file SpriteImageContainer.java.
References model.sprite.SpriteImageContainer.mySpritesheet.
Referenced by engine.visuals.elementVisuals.animations.Animator.Animator(), model.MainModel.fetchImageContainer(), and engine.visuals.elementVisuals.animations.Animator.setColorMasking().
void model.sprite.SpriteImageContainer.locateColorMask (String colorMaskTag) throws SaveLoadException private
Definition at line 35 of file SpriteImageContainer.java.
References model.sprite.SpriteImageLoader.loadTeamColorMask().
Referenced by model.sprite.SpriteImageContainer.SpriteImageContainer().
void model.sprite.SpriteImageContainer.locateSpritesheet (String spritesheetTag) throws SaveLoadException private
Definition at line 39 of file SpriteImageContainer.java.
References model.sprite.SpriteImageLoader.loadSpritesheet().
Referenced by model.sprite.SpriteImageContainer.SpriteImageContainer().
Member Data Documentation
ImageView model.sprite.SpriteImageContainer.myColorMask private
Definition at line 22 of file SpriteImageContainer.java.
Referenced by model.sprite.SpriteImageContainer.getColorMask().
ImageView model.sprite.SpriteImageContainer.mySpritesheet private
Definition at line 21 of file SpriteImageContainer.java.
Referenced by model.sprite.SpriteImageContainer.getSpritesheet().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/sprite/SpriteImageContainer.java