voogasalad_TheException: model.state.gameelement.GameElementState Class Reference
model.state.gameelement.GameElementState Class Reference
Public Member Functions
GameElementState ()
String getName ()
void addType (String type)
List< String > getTypes ()
boolean isType (String typeString)
void deleteTypes (String typeString)
void addAction (ActionWrapper action)
Map< ActionType, List< ActionWrapper > > getActions ()
Public Member Functions inherited from util.JSONable
default String toJSON ()
Public Attributes
AttributeContainer attributes
Set< String > myTypes
Protected Attributes
Map< ActionType, List< ActionWrapper > > myActions
Static Private Attributes
static final long serialVersionUID = 6832117170246376287L
Detailed Description
The most basic flavor of GameElement - this type of element has no on-screen representation. Examples include triggers and goals. States are essentially data-wrapping objects and as such have no internal logic.
Author
Steve, Jonathan, Rahul, Nishad, Zach, Michael D., Stanley
Definition at line 24 of file GameElementState.java.
Constructor & Destructor Documentation
model.state.gameelement.GameElementState.GameElementState ()
Initialize the game element state and its internal data structures.
Definition at line 56 of file GameElementState.java.
Member Function Documentation
void model.state.gameelement.GameElementState.addAction (ActionWrapper action)
Add a string condition-action pair to the game element state
param actionType the type of the action being added param actionString a Vscript string representation of the action
Definition at line 106 of file GameElementState.java.
References engine.gameRepresentation.evaluatables.actions.ActionWrapper.getActionType().
Referenced by model.GameElementStateFactory.addEssentials(), application.Pong.createBall(), application.RPG.createEnemyUnit(), model.GameElementStateFactory.createGoal(), application.RPG.createGoal(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), application.RPG.createSpawnPoint(), application.Pong.hardCodeAGame(), and application.RPG.hardCodeAGame().
void model.state.gameelement.GameElementState.addType (String type)
Adds a type to a set of types
Parameters
type The new type
Definition at line 74 of file GameElementState.java.
Referenced by application.Pong.createBall(), application.Pong.createBoundary(), model.GameElementStateFactory.createDrawableGameElementState(), application.RPG.createEnemyUnit(), application.Pong.createGoalDisplayMarker(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), and application.RPG.createSpawnPoint().
void model.state.gameelement.GameElementState.deleteTypes (String typeString)
Definition at line 94 of file GameElementState.java.
Map<ActionType, List<ActionWrapper> > model.state.gameelement.GameElementState.getActions ()
Grabs all actions for use in evaluatable factory. Exposing the collection is in this case necessary for use by the factory as the element states are essentially data wrappers that are only used in the creation of objects by the factory
Returns
Definition at line 121 of file GameElementState.java.
References model.state.gameelement.GameElementState.myActions.
Referenced by model.data.WizardDataFactory.createWizardData(), and engine.elementFactories.GameElementFactory.generateActions().
String model.state.gameelement.GameElementState.getName ()
Returns
the name of the element, if it has been set
Definition at line 65 of file GameElementState.java.
References model.state.gameelement.AttributeContainer.getTextualAttribute(), and model.state.gameelement.StateTags.NAME.
Referenced by model.data.WizardDataFactory.createWizardData().
List<String> model.state.gameelement.GameElementState.getTypes ()
Returns
A list of the types
Definition at line 81 of file GameElementState.java.
References model.state.gameelement.GameElementState.myTypes.
Referenced by model.data.WizardDataFactory.createWizardData(), and engine.gameRepresentation.renderedRepresentation.GameElement.getTypes().
boolean model.state.gameelement.GameElementState.isType (String typeString)
Parameters
typeString The type we want to check
Returns
True if the type set contains typeString
Definition at line 90 of file GameElementState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.GameElement.isType().
Member Data Documentation
AttributeContainer model.state.gameelement.GameElementState.attributes
It was decided that all attributes for a game element would be saved in sets of attributes instead of in local instance variables. Although this may make it difficult at times to be sure of what attributes an object actually has, this choice was made to allow for the greatest amount of power for the VScript language as people creating the games will be able to use any numerical or string attribute of an object in their logic, allowing for much more power on the side of engine extensibility at the cost of some "parameter uncertainty" in the engine.
Definition at line 49 of file GameElementState.java.
Referenced by model.GameElementStateFactory.addEssentials(), model.MainModel.addTerrainToLevel(), model.MainModel.addUnitToLevel(), engine.elementFactories.AnimatorFactory.createAnimator(), application.Pong.createBall(), application.Pong.createBoundary(), application.RPG.createEnemyUnit(), application.Pong.createGoal(), application.RPG.createGoal(), application.Pong.createGoalDisplayMarker(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), engine.elementFactories.GameElementFactory.createSelectableGameElement(), application.RPG.createSpawnPoint(), engine.elementFactories.VisualizerFactory.createVisualizer(), model.data.WizardDataFactory.createWizardData(), model.state.gameelement.DrawableGameElementState.DrawableGameElementState(), model.state.gameelement.DrawableGameElementState.findGlobalBounds(), engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), engine.gameRepresentation.renderedRepresentation.GameElement.getTextualAttribute(), application.Pong.hardCodeAGame(), application.RPG.hardCodeAGame(), engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute(), model.MainModel.setTerrain(), engine.gameRepresentation.renderedRepresentation.GameElement.setTextualAttribute(), and model.GameUniverse.storeAttributes().
Map<ActionType, List<ActionWrapper> > model.state.gameelement.GameElementState.myActions protected
The actions for a given game element state will be stored in a map of ActionTypes that represent the type of action e.g. collision, internal, etc. to a list of Action wrappers of vscript commands of the actions to be executed. Conditions were removed from this representation as actions internally check for their own conditions.
Definition at line 38 of file GameElementState.java.
Referenced by model.state.gameelement.GameElementState.getActions().
Set<String> model.state.gameelement.GameElementState.myTypes
Definition at line 51 of file GameElementState.java.
Referenced by model.state.gameelement.GameElementState.getTypes().
final long model.state.gameelement.GameElementState.serialVersionUID = 6832117170246376287L static private
Definition at line 29 of file GameElementState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/gameelement/GameElementState.java