voogasalad_TheException: game_engine.visuals.UI.ClickManager Class Reference
game_engine.visuals.UI.ClickManager Class Reference
Public Member Functions
void clicked (MouseEvent event, double xLoc, double yLoc)
Point2D getLoc ()
boolean isPrimary ()
boolean isSecondary ()
Package Attributes
boolean isPrimary
boolean isSecondary
double xLoc
double yLoc
Detailed Description
The class for managing the clicks the user makes. Takes in click information and allows observers to get that information.
Author
John
Definition at line 16 of file ClickManager.java.
Member Function Documentation
void game_engine.visuals.UI.ClickManager.clicked (MouseEvent event, double xLoc, double yLoc)
Update the click manager based on a new mouse event
Parameters
event
xLoc
yLoc
Definition at line 29 of file ClickManager.java.
References game_engine.visuals.UI.ClickManager.isPrimary(), game_engine.visuals.UI.ClickManager.xLoc, and game_engine.visuals.UI.ClickManager.yLoc.
Referenced by game_engine.visuals.ScrollableScene.initializeHandlers().
Point2D game_engine.visuals.UI.ClickManager.getLoc ()
Definition at line 45 of file ClickManager.java.
boolean game_engine.visuals.UI.ClickManager.isPrimary ()
Definition at line 49 of file ClickManager.java.
Referenced by game_engine.visuals.UI.ClickManager.clicked().
boolean game_engine.visuals.UI.ClickManager.isSecondary ()
Definition at line 53 of file ClickManager.java.
Member Data Documentation
boolean game_engine.visuals.UI.ClickManager.isPrimary package
Definition at line 18 of file ClickManager.java.
boolean game_engine.visuals.UI.ClickManager.isSecondary package
Definition at line 19 of file ClickManager.java.
double game_engine.visuals.UI.ClickManager.xLoc package
Definition at line 20 of file ClickManager.java.
Referenced by game_engine.visuals.UI.ClickManager.clicked().
double game_engine.visuals.UI.ClickManager.yLoc package
Definition at line 20 of file ClickManager.java.
Referenced by game_engine.visuals.UI.ClickManager.clicked().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/UI/ClickManager.java