voogasalad_TheException: game_engine.visuals.UI.SelectionBox Class Reference
game_engine.visuals.UI.SelectionBox Class Reference
Public Member Functions
SelectionBox ()
void released (double topLeftX, double topLeftY, double bottomRightX, double bottomRightY)
double[] getPoints ()
Rectangle getBox ()
void resetBox ()
void setLocation (double pressedX, double pressedY)
Package Attributes
double[] points = new double[4]
Private Attributes
Rectangle myRectangle
Detailed Description
The class for creating the rectangle that the user draws during a game with their cursor. Extends observable so that other classes that want to be notified of unit selection can see where the box was drawn
Author
John
Definition at line 16 of file SelectionBox.java.
Constructor & Destructor Documentation
game_engine.visuals.UI.SelectionBox.SelectionBox ()
Definition at line 21 of file SelectionBox.java.
Member Function Documentation
Rectangle game_engine.visuals.UI.SelectionBox.getBox ()
Definition at line 38 of file SelectionBox.java.
References game_engine.visuals.UI.SelectionBox.myRectangle.
Referenced by game_engine.visuals.ScrollableScene.ScrollableScene().
double [] game_engine.visuals.UI.SelectionBox.getPoints ()
Definition at line 34 of file SelectionBox.java.
References game_engine.visuals.UI.SelectionBox.points.
void game_engine.visuals.UI.SelectionBox.released (double topLeftX, double topLeftY, double bottomRightX, double bottomRightY)
Definition at line 25 of file SelectionBox.java.
Referenced by game_engine.visuals.ScrollableScene.initializeHandlers().
void game_engine.visuals.UI.SelectionBox.resetBox ()
Definition at line 42 of file SelectionBox.java.
Referenced by game_engine.visuals.ScrollableScene.initializeHandlers().
void game_engine.visuals.UI.SelectionBox.setLocation (double pressedX, double pressedY)
Definition at line 53 of file SelectionBox.java.
Referenced by game_engine.visuals.ScrollableScene.initializeHandlers().
Member Data Documentation
Rectangle game_engine.visuals.UI.SelectionBox.myRectangle private
Definition at line 17 of file SelectionBox.java.
Referenced by game_engine.visuals.UI.SelectionBox.getBox().
double [] game_engine.visuals.UI.SelectionBox.points = new double[4] package
Definition at line 19 of file SelectionBox.java.
Referenced by game_engine.visuals.UI.SelectionBox.getPoints().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/UI/SelectionBox.java