voogasalad_TheException: game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState Class Reference
game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState Class Reference
Public Member Functions
GameElementState ()
String getName ()
String getType ()
String getTextualAttribute (String name)
Number getNumericalAttribute (String name)
void setTextualAttribute (String name, String value)
void setNumericalAttribute (String name, Number value)
void addAction (String actionType, String actionString)
Map< String, List< String > > getActions ()
Public Member Functions inherited from util.JSONable
default String toJSON ()
Protected Attributes
Map< String, List< String > > myActions
Set< Attribute< Number > > myNumericalAttributes
Set< Attribute< String > > myTextualAttributes
Package Functions
private< T > T getAttribute (Collection< Attribute< T >> collection, String attributeName, T defaultReturnObject)
private< T > void addAttribute (Collection< Attribute< T >> collection, String attributeName, T attributeValue)
Detailed Description
The most basic flavor of GameElement - this type of element has no on-screen representation. Examples include triggers and goals. States are essentially data-wrapping objects and as such have no internal logic.
Author
Steve, Jonathan, Rahul, Nishad, Zach
Definition at line 23 of file GameElementState.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.GameElementState ()
Initialize the game element state and its internal data structures.
Definition at line 48 of file GameElementState.java.
Member Function Documentation
void game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.addAction (String actionType, String actionString)
Add a string condition-action pair to the game element state
Parameters
actionType the type of the action being added
actionString a Vscript string representation of the action
Definition at line 147 of file GameElementState.java.
Referenced by gamemodel.GameElementStateFactory.addEssentials(), and gamemodel.GameElementStateFactory.createGoal().
private<T> void game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.addAttribute (Collection< Attribute< T >> collection, String attributeName, T attributeValue) package
Add an attribute with the given values to a given collection. Used to make switching between internal collection implementations easy
Parameters
collection
attributeName
attributeValue
Definition at line 114 of file GameElementState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setNumericalAttribute(), and game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setTextualAttribute().
Map<String, List<String> > game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getActions ()
Grabs all actions for use in evaluatable factory.
Returns
Definition at line 158 of file GameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.myActions.
Referenced by game_engine.elementFactories.GameElementFactory.generateActions().
private<T> T game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getAttribute (Collection< Attribute< T >> collection, String attributeName, T defaultReturnObject) package
Get an attribute from an internal collection
Parameters
collection the collection to extract the element from
attributeName the name of the attribute to extract
defaultReturnObject the value that should be returned if no attribute of the specified type was found
Returns
the attribute's value or the default return object if the attribute was not found
Definition at line 82 of file GameElementState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getNumericalAttribute(), and game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getTextualAttribute().
String game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getName ()
Returns
the name of the element, if it has been set
Definition at line 57 of file GameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getTextualAttribute(), and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.NAME_ATTRIBUTE_STRING.
Number game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getNumericalAttribute (String name)
Get a numerical attribute with the given name
Definition at line 102 of file GameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getAttribute().
Referenced by game_engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute().
String game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getTextualAttribute (String name)
Get a textual attribute with the given name
Definition at line 95 of file GameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getAttribute().
Referenced by game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getName(), game_engine.gameRepresentation.renderedRepresentation.GameElement.getTextualAttribute(), and game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getType().
String game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getType ()
Returns
the type of the element, if it has been set
Definition at line 65 of file GameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getTextualAttribute(), and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.TYPE_ATTRIBUTE_STRING.
void game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setNumericalAttribute (String name, Number value)
Set a numerical attribute with the given name to the given value
Definition at line 137 of file GameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.addAttribute().
Referenced by gamemodel.GameElementStateFactory.addEssentials(), application.ShittyMain.createArcher(), application.ShittyMain.hardCodeAGame(), test.conditions.ConditionFunctionalityTest.initialize(), and game_engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute().
void game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setTextualAttribute (String name, String value)
Add an attribute Set a textual attribute with the given name to the given value
Definition at line 130 of file GameElementState.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.addAttribute().
Referenced by gamemodel.GameElementStateFactory.addEssentials(), game_engine.stateManaging.GameElementManager.main(), and game_engine.gameRepresentation.renderedRepresentation.GameElement.setTextualAttribute().
Member Data Documentation
Map<String, List<String> > game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.myActions protected
The actions for a given game element state will be stored in a map of Strings that represent the type of action e.g. collision, internal, etc. to a list of strings vscript of the actions to be executed. Conditions were removed from this representation as actions can easily check for their own conditions using an && sign. i.e. condition&&action will only evaluate the action if the condition is true.
Definition at line 32 of file GameElementState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.getActions().
Set<Attribute<Number> > game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.myNumericalAttributes protected
It was decided that all attributes for a game element would be saved in sets of attributes instead of in local instance variables. Although this may make it difficult at times to be sure of what attributes an object actually has, this choice was made to allow for the greatest amount of power for the VScript language as people creating the games will be able to use any numerical or string attribute of an object in their logic, allowing for much more power on the side of engine extensibility at the cost of some "parameter uncertainty" in the engine.
Definition at line 42 of file GameElementState.java.
Referenced by game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.DrawableGameElementState().
Set<Attribute<String> > game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.myTextualAttributes protected
Definition at line 43 of file GameElementState.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/stateRepresentation/gameElement/GameElementState.java