voogasalad_TheException: view.editor.wizards.ActionWizard Class Reference
view.editor.wizards.ActionWizard Class Reference
Public Member Functions
boolean checkCanSave ()
void updateData ()
void initialize ()
void launchForEdit (WizardData oldValues)
void loadGlobalValues (List< String > values)
Public Member Functions inherited from view.editor.wizards.Wizard
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
abstract void launchForEdit (WizardData oldValues)
abstract void loadGlobalValues (List< String > values)
WizardData getWizardData ()
void displayErrorMessage (String error)
void removeWizardData (WizardData data)
void setStage (Stage s)
void closeStage ()
Private Member Functions
boolean dropdownsValid ()
String getDropdownText ()
void buildOptionedString (ActionOptions actionOption)
Private Attributes
ComboBox< ActionType > actionType
ComboBox< ActionOptions > actionChoice
Text message
VBox options
List< ComboBox< String > > dropdowns
Set< String > attributes
List< ComboBox< String > > numberDropdowns
Static Private Attributes
static final String EE_DELIMITER = "#"
static final String DELIMETER = "((?<=" + EE_DELIMITER + ")|(?=" + EE_DELIMITER + "))"
Additional Inherited Members
Static Public Attributes inherited from view.editor.wizards.Wizard
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
Protected Member Functions inherited from view.editor.wizards.Wizard
void addToData (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void setWizardType (WizardType type)
void attachTextProperties ()
boolean isNumber (String value)
Protected Attributes inherited from view.editor.wizards.Wizard
SplitPane root
Button save
Text errorMessage
Detailed Description
public ActionWrapper (String actionType, String actionName, String ... parameters)
Author
Joshua, Nishad
Definition at line 26 of file ActionWizard.java.
Member Function Documentation
void view.editor.wizards.ActionWizard.buildOptionedString (ActionOptions actionOption) private
Definition at line 93 of file ActionWizard.java.
References engine.gameRepresentation.evaluatables.actions.enumerations.ActionParameters.ATTR, engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.getMessage(), engine.gameRepresentation.evaluatables.actions.enumerations.ActionOptions.getOperators(), and engine.gameRepresentation.evaluatables.actions.enumerations.ActionParameters.NUMBER.
Referenced by view.editor.wizards.ActionWizard.initialize().
boolean view.editor.wizards.ActionWizard.checkCanSave ()
Definition at line 46 of file ActionWizard.java.
References view.editor.wizards.ActionWizard.dropdownsValid().
boolean view.editor.wizards.ActionWizard.dropdownsValid () private
Definition at line 52 of file ActionWizard.java.
References view.editor.wizards.Wizard.isNumber().
Referenced by view.editor.wizards.ActionWizard.checkCanSave().
String view.editor.wizards.ActionWizard.getDropdownText () private
Definition at line 73 of file ActionWizard.java.
Referenced by view.editor.wizards.ActionWizard.updateData().
void view.editor.wizards.ActionWizard.initialize ()
Implements view.gui.GUIController.
Definition at line 82 of file ActionWizard.java.
References view.editor.wizards.ActionWizard.buildOptionedString(), and model.state.gameelement.StateTags.getAllAttributes().
void view.editor.wizards.ActionWizard.launchForEdit (WizardData oldValues)
Definition at line 132 of file ActionWizard.java.
References model.data.WizardDataType.ACTION, model.data.WizardDataType.ACTION_PARAMETERS, model.data.WizardDataType.ACTIONTYPE, and model.data.WizardData.getValueByKey().
void view.editor.wizards.ActionWizard.loadGlobalValues (List< String > values)
Definition at line 144 of file ActionWizard.java.
void view.editor.wizards.ActionWizard.updateData ()
Definition at line 65 of file ActionWizard.java.
References model.data.WizardDataType.ACTION, model.data.WizardDataType.ACTION_PARAMETERS, model.data.WizardDataType.ACTIONTYPE, view.editor.wizards.Wizard.addToData(), view.editor.wizards.ActionWizard.getDropdownText(), view.editor.wizards.Wizard.setWizardType(), and model.data.WizardType.TRIGGER.
Member Data Documentation
ComboBox<ActionOptions> view.editor.wizards.ActionWizard.actionChoice private
Definition at line 34 of file ActionWizard.java.
ComboBox<ActionType> view.editor.wizards.ActionWizard.actionType private
Definition at line 32 of file ActionWizard.java.
Set<String> view.editor.wizards.ActionWizard.attributes private
Definition at line 42 of file ActionWizard.java.
final String view.editor.wizards.ActionWizard.DELIMETER = "((?<=" + EE_DELIMITER + ")|(?=" + EE_DELIMITER + "))" static private
Definition at line 29 of file ActionWizard.java.
List<ComboBox<String> > view.editor.wizards.ActionWizard.dropdowns private
Definition at line 40 of file ActionWizard.java.
final String view.editor.wizards.ActionWizard.EE_DELIMITER = "#" static private
Definition at line 28 of file ActionWizard.java.
Text view.editor.wizards.ActionWizard.message private
Definition at line 36 of file ActionWizard.java.
List<ComboBox<String> > view.editor.wizards.ActionWizard.numberDropdowns private
Definition at line 43 of file ActionWizard.java.
VBox view.editor.wizards.ActionWizard.options private
Definition at line 38 of file ActionWizard.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/ActionWizard.java