voogasalad_TheException: model.state.GameState Class Reference
model.state.GameState Class Reference
Public Member Functions
GameState (String name)
CampaignState getCampaign (String campaignName) throws CampaignNotFoundException
List< CampaignState > getCampaigns ()
void addCampaign (CampaignState campaignToAdd) throws CampaignExistsException
void removeCampaign (String campaignName)
GameUniverse getGameUniverse ()
Public Member Functions inherited from model.state.DescribableState
void updateName (String name)
void updateDescription (String description)
String getName ()
String getDescription ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from util.JSONable
default String toJSON ()
Private Attributes
List< CampaignState > myCampaigns
List< HighScore > myHighScores
GameUniverse myGameUniverse
Static Private Attributes
static final long serialVersionUID = -7286615449971559602L
Additional Inherited Members
Protected Member Functions inherited from model.state.DescribableState
DescribableState ()
DescribableState (String name)
Detailed Description
This class is analogous to a genre of game or a game tile such as Warcraft (tm).
Author
Steve, Jonathan, Nishad, Rahul
Definition at line 18 of file GameState.java.
Constructor & Destructor Documentation
model.state.GameState.GameState (String name)
Definition at line 28 of file GameState.java.
Member Function Documentation
void model.state.GameState.addCampaign (CampaignState campaignToAdd) throws CampaignExistsException
adds a campaign to the game
Parameters
campaignToAdd the campaignstate to be added to the gamestate's campaignstate's
Exceptions
CampaignExistsExeption
Definition at line 72 of file GameState.java.
Referenced by model.MainModel.createCampaign(), application.Pong.hardCodeAGame(), and application.RPG.hardCodeAGame().
CampaignState model.state.GameState.getCampaign (String campaignName) throws CampaignNotFoundException
gets the campaign with associated campaignName
Parameters
campaignName the name of the campaign to be returned
Returns
the Campaign with the associated campaignName
Exceptions
CampaignNotFoundException
Definition at line 43 of file GameState.java.
Referenced by model.MainModel.createLevel(), model.MainModel.getCampaign(), and model.MainModel.getDescribableState().
List<CampaignState> model.state.GameState.getCampaigns ()
returns unmodifiable list of campaigns
Returns
List<CampaignState> the list of the gamestate's campaignstates
Definition at line 61 of file GameState.java.
References model.state.GameState.myCampaigns.
Referenced by model.MainModel.elementIsInUse(), view.editor.EditorMenuBarController.onNewLevelClick(), view.runner.RunnerScreen.updateLevelChooser(), and view.editor.EditorScreen.updateProjectExplorer().
GameUniverse model.state.GameState.getGameUniverse ()
returns the game universe for this game
Returns
GameUniverse the GameUniverse of the GameState
Definition at line 101 of file GameState.java.
References model.state.GameState.myGameUniverse.
Referenced by model.MainModel.createDrawableGameElementState(), model.MainModel.createGameElementState(), model.MainModel.createSelectableGameElementState(), model.MainModel.getGameUniverse(), and model.MainModel.updateSpritesAndMasks().
void model.state.GameState.removeCampaign (String campaignName)
removes a campaign with a given name
Parameters
campaignName the name of the campaign to be removed
Definition at line 89 of file GameState.java.
Member Data Documentation
List<CampaignState> model.state.GameState.myCampaigns private
Definition at line 24 of file GameState.java.
Referenced by model.state.GameState.getCampaigns().
GameUniverse model.state.GameState.myGameUniverse private
Definition at line 26 of file GameState.java.
Referenced by model.state.GameState.getGameUniverse().
List<HighScore> model.state.GameState.myHighScores private
Definition at line 25 of file GameState.java.
final long model.state.GameState.serialVersionUID = -7286615449971559602L static private
Definition at line 23 of file GameState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/GameState.java