voogasalad_TheException: vooga.request.Request Class Reference
vooga.request.Request Class Reference
Public Member Functions
Request (String sender, String receiver, Map< String, String > message)
String sender ()
String receiver ()
Map< String, String > message ()
Request (String sender, String receiver, Map< String, String > message)
String sender ()
String receiver ()
Map< String, String > message ()
Private Attributes
String mySender
String myReceiver
Map< String, String > myMessage
Detailed Description
Definition at line 6 of file Request.java.
Constructor & Destructor Documentation
vooga.request.Request.Request (String sender, String receiver, Map< String, String > message)
Definition at line 12 of file Request.java.
References vooga.request.Request.message(), vooga.request.Request.receiver(), and vooga.request.Request.sender().
vooga.request.Request.Request (String sender, String receiver, Map< String, String > message)
Definition at line 12 of file Request.java.
References vooga.request.Request.message(), vooga.request.Request.receiver(), and vooga.request.Request.sender().
Member Function Documentation
Map<String, String> vooga.request.Request.message ()
Get the message
Returns
A map of attributes to values representing the message
Implements vooga.request.IRequest.
Definition at line 29 of file Request.java.
References vooga.request.Request.myMessage.
Referenced by vooga.request.Request.Request().
Map<String, String> vooga.request.Request.message ()
Get the message
Returns
A map of attributes to values representing the message
Implements vooga.request.IRequest.
Definition at line 29 of file Request.java.
References vooga.request.Request.myMessage.
String vooga.request.Request.receiver ()
Get the recipient
Returns
The address of the recipient
Implements vooga.request.IRequest.
Definition at line 24 of file Request.java.
References vooga.request.Request.myReceiver.
String vooga.request.Request.receiver ()
Get the recipient
Returns
The address of the recipient
Implements vooga.request.IRequest.
Definition at line 24 of file Request.java.
References vooga.request.Request.myReceiver.
Referenced by vooga.request.Request.Request().
String vooga.request.Request.sender ()
Get the sender
Returns
The address of the sender
Implements vooga.request.IRequest.
Definition at line 19 of file Request.java.
References vooga.request.Request.mySender.
String vooga.request.Request.sender ()
Get the sender
Returns
The address of the sender
Implements vooga.request.IRequest.
Definition at line 19 of file Request.java.
References vooga.request.Request.mySender.
Referenced by vooga.request.Request.Request().
Member Data Documentation
Map< String, String > vooga.request.Request.myMessage private
Definition at line 10 of file Request.java.
Referenced by vooga.request.Request.message().
String vooga.request.Request.myReceiver private
Definition at line 9 of file Request.java.
Referenced by vooga.request.Request.receiver().
String vooga.request.Request.mySender private
Definition at line 8 of file Request.java.
Referenced by vooga.request.Request.sender().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/build/build/src/vooga/request/Request.java