voogasalad_TheException: model.state.CampaignState Class Reference
model.state.CampaignState Class Reference
Public Member Functions
CampaignState (String name)
LevelState getLevel (String levelName) throws LevelNotFoundException
List< LevelState > getLevels ()
void addLevel (LevelState levelToAdd) throws LevelExistsException
void removeLevel (String levelName)
Public Member Functions inherited from model.state.DescribableState
void updateName (String name)
void updateDescription (String description)
String getName ()
String getDescription ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from util.JSONable
default String toJSON ()
Private Attributes
List< LevelState > myLevels
Static Private Attributes
static final long serialVersionUID = -2373136578395538792L
Additional Inherited Members
Protected Member Functions inherited from model.state.DescribableState
DescribableState ()
DescribableState (String name)
Detailed Description
This class is a collection of Levels used to string together gameplay in order to make a cohesive user experience.
Author
Steve, Jonathan, Nishad, Rahul
Definition at line 17 of file CampaignState.java.
Constructor & Destructor Documentation
model.state.CampaignState.CampaignState (String name)
Definition at line 25 of file CampaignState.java.
Member Function Documentation
void model.state.CampaignState.addLevel (LevelState levelToAdd) throws LevelExistsException
adds a level to the campaign
Parameters
levelToAdd the level to be appended to the list of the campaignstate's levelstates
Exceptions
LevelExistsException
Definition at line 61 of file CampaignState.java.
Referenced by model.MainModel.createLevel(), application.Pong.hardCodeAGame(), and application.RPG.hardCodeAGame().
LevelState model.state.CampaignState.getLevel (String levelName) throws LevelNotFoundException
gets the level with associated levelName
Parameters
levelName
Returns
the state of the level of interest
Exceptions
LevelNotFoundException
Definition at line 37 of file CampaignState.java.
Referenced by model.MainModel.getDescribableState(), and model.MainModel.getLevel().
List<LevelState> model.state.CampaignState.getLevels ()
Definition at line 49 of file CampaignState.java.
References model.state.CampaignState.myLevels.
Referenced by model.MainModel.setLevel().
void model.state.CampaignState.removeLevel (String levelName)
removes a level with a given name
Parameters
levelName the name of the level to be removed
Definition at line 78 of file CampaignState.java.
Member Data Documentation
List<LevelState> model.state.CampaignState.myLevels private
Definition at line 23 of file CampaignState.java.
Referenced by model.state.CampaignState.getLevels().
final long model.state.CampaignState.serialVersionUID = -2373136578395538792L static private
Definition at line 22 of file CampaignState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/CampaignState.java