voogasalad_TheException: model.state.gameelement.AttributeContainer Class Reference
model.state.gameelement.AttributeContainer Class Reference
Public Member Functions
AttributeContainer ()
String getTextualAttribute (String name)
Number getNumericalAttribute (String name)
Set< Attribute< Number > > getNumericalAttributes ()
Set< Attribute< String > > getTextualAttributes ()
void setTextualAttribute (String name, String value)
void setNumericalAttribute (String name, Number value)
Package Functions
private< T > T getAttribute (Collection< Attribute< T >> collection, String attributeName, T defaultReturnObject)
private< T > void addAttribute (Collection< Attribute< T >> collection, String attributeName, T attributeValue)
Private Attributes
Set< Attribute< Number > > myNumericalAttributes
Set< Attribute< String > > myTextualAttributes
Static Private Attributes
static final long serialVersionUID = -3942254987685526285L
Detailed Description
Definition at line 10 of file AttributeContainer.java.
Constructor & Destructor Documentation
model.state.gameelement.AttributeContainer.AttributeContainer ()
Definition at line 19 of file AttributeContainer.java.
Member Function Documentation
private<T> void model.state.gameelement.AttributeContainer.addAttribute (Collection< Attribute< T >> collection, String attributeName, T attributeValue) package
Add an attribute with the given values to a given collection. Used to make switching between internal collection implementations easy
Parameters
collection
attributeName
attributeValue
Definition at line 76 of file AttributeContainer.java.
Referenced by model.state.gameelement.AttributeContainer.setNumericalAttribute(), and model.state.gameelement.AttributeContainer.setTextualAttribute().
private<T> T model.state.gameelement.AttributeContainer.getAttribute (Collection< Attribute< T >> collection, String attributeName, T defaultReturnObject) package
Get an attribute from an internal collection
Parameters
collection the collection to extract the element from
attributeName the name of the attribute to extract
defaultReturnObject the value that should be returned if no attribute of the specified type was found
Returns
the attribute's value or the default return object if the attribute was not found
Definition at line 36 of file AttributeContainer.java.
Referenced by model.state.gameelement.AttributeContainer.getNumericalAttribute(), and model.state.gameelement.AttributeContainer.getTextualAttribute().
Number model.state.gameelement.AttributeContainer.getNumericalAttribute (String name)
Get a numerical attribute with the given name
Definition at line 56 of file AttributeContainer.java.
References model.state.gameelement.AttributeContainer.getAttribute().
Referenced by engine.visuals.elementVisuals.animations.Animator.Animator(), model.MainModel.areCoordinatesValid(), engine.elementFactories.LevelFactory.createLevel(), engine.visuals.elementVisuals.animations.Animator.determineAnimationDirection(), engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), model.state.gameelement.DrawableGameElementState.findGlobalBounds(), engine.gameRepresentation.renderedRepresentation.Level.getMapHeight(), engine.gameRepresentation.renderedRepresentation.Level.getMapWidth(), engine.gameRepresentation.renderedRepresentation.Level.getNumericalAttribute(), engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), engine.visuals.elementVisuals.Visualizer.initializeDisplay(), model.MainModel.setTerrain(), engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.toggleOpacity(), engine.UI.ParticipantManager.update(), and engine.visuals.elementVisuals.Visualizer.updateNodeLocation().
Set<Attribute<Number> > model.state.gameelement.AttributeContainer.getNumericalAttributes ()
Definition at line 60 of file AttributeContainer.java.
References model.state.gameelement.AttributeContainer.myNumericalAttributes.
Referenced by model.data.WizardDataFactory.createWizardData(), view.runner.GameRunnerPaneController.engineUpdate(), model.GameUniverse.storeAttributes(), and model.state.HighScore.toString().
String model.state.gameelement.AttributeContainer.getTextualAttribute (String name)
Get a textual attribute with the given name
Definition at line 49 of file AttributeContainer.java.
References model.state.gameelement.AttributeContainer.getAttribute().
Referenced by engine.visuals.elementVisuals.animations.Animator.determineAnimationType(), model.state.gameelement.GameElementState.getName(), engine.gameRepresentation.renderedRepresentation.Level.getTextualAttribute(), and engine.gameRepresentation.renderedRepresentation.GameElement.getTextualAttribute().
Set<Attribute<String> > model.state.gameelement.AttributeContainer.getTextualAttributes ()
Definition at line 64 of file AttributeContainer.java.
References model.state.gameelement.AttributeContainer.myTextualAttributes.
Referenced by model.data.WizardDataFactory.createWizardData(), model.GameUniverse.storeAttributes(), and model.state.HighScore.toString().
void model.state.gameelement.AttributeContainer.setNumericalAttribute (String name, Number value)
Set a numerical attribute with the given name to the given value
Definition at line 99 of file AttributeContainer.java.
References model.state.gameelement.AttributeContainer.addAttribute().
Referenced by model.GameElementStateFactory.addEssentials(), model.MainModel.addTerrainToLevel(), model.MainModel.addUnitToLevel(), application.Pong.createBall(), application.Pong.createBoundary(), application.RPG.createEnemyUnit(), application.Pong.createGoal(), application.RPG.createGoal(), application.Pong.createGoalDisplayMarker(), application.Pong.createGoalRegion(), model.MainModel.createLevel(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), engine.elementFactories.GameElementFactory.createSelectableGameElement(), application.RPG.createSpawnPoint(), model.state.gameelement.DrawableGameElementState.DrawableGameElementState(), application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), engine.users.Participant.Participant(), engine.gameRepresentation.renderedRepresentation.Level.setNumericalAttribute(), engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute(), and model.MainModel.setTerrain().
void model.state.gameelement.AttributeContainer.setTextualAttribute (String name, String value)
Add an attribute Set a textual attribute with the given name to the given value
Definition at line 92 of file AttributeContainer.java.
References model.state.gameelement.AttributeContainer.addAttribute().
Referenced by model.GameElementStateFactory.addEssentials(), application.Pong.createBall(), application.Pong.createBoundary(), application.Pong.createGoalDisplayMarker(), application.Pong.createGoalRegion(), model.MainModel.createLevel(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), application.RPG.hardCodeAGame(), application.Pong.hardCodeAGame(), engine.gameRepresentation.renderedRepresentation.Level.setTextualAttribute(), and engine.gameRepresentation.renderedRepresentation.GameElement.setTextualAttribute().
Member Data Documentation
Set<Attribute<Number> > model.state.gameelement.AttributeContainer.myNumericalAttributes private
Definition at line 16 of file AttributeContainer.java.
Referenced by model.state.gameelement.AttributeContainer.getNumericalAttributes().
Set<Attribute<String> > model.state.gameelement.AttributeContainer.myTextualAttributes private
Definition at line 17 of file AttributeContainer.java.
Referenced by model.state.gameelement.AttributeContainer.getTextualAttributes().
final long model.state.gameelement.AttributeContainer.serialVersionUID = -3942254987685526285L static private
Definition at line 14 of file AttributeContainer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/gameelement/AttributeContainer.java