voogasalad_TheException: game_engine.visuals.SelectionBox Class Reference
game_engine.visuals.SelectionBox Class Reference
Public Member Functions
SelectionBox ()
void released (double topLeftX, double topLeftY, double bottomRightX, double bottomRightY)
double[] getPoints ()
Rectangle getBox ()
void resetBox ()
void setSize (double width, double height)
void setX (double x)
void setY (double y)
void setLocation (double x, double y)
void setVisible (boolean b)
void update (Observable o, Object arg)
MouseEvent getLastClick ()
Package Attributes
double pressedY
Private Member Functions
void reactToDrag (MouseDragManager dragManager)
Private Attributes
Rectangle myRectangle
double pressedX
double[] points = new double[4]
MouseEvent lastEvent
Detailed Description
The class for creating the rectangle that the user draws during a game with their cursor. Extends observable so that other classes that want to be notified of unit selection can see where the box was drawn
Author
John
Definition at line 21 of file SelectionBox.java.
Constructor & Destructor Documentation
game_engine.visuals.SelectionBox.SelectionBox ()
Definition at line 27 of file SelectionBox.java.
Member Function Documentation
Rectangle game_engine.visuals.SelectionBox.getBox ()
Definition at line 47 of file SelectionBox.java.
References game_engine.visuals.SelectionBox.myRectangle.
Referenced by game_engine.visuals.ScrollablePane.initializeHandlers(), and game_engine.visuals.ScrollablePane.ScrollablePane().
MouseEvent game_engine.visuals.SelectionBox.getLastClick ()
Definition at line 137 of file SelectionBox.java.
References game_engine.visuals.SelectionBox.lastEvent.
Referenced by game_engine.stateManaging.GameElementManager.update().
double [] game_engine.visuals.SelectionBox.getPoints ()
Definition at line 43 of file SelectionBox.java.
References game_engine.visuals.SelectionBox.points.
Referenced by game_engine.stateManaging.GameElementManager.update().
void game_engine.visuals.SelectionBox.reactToDrag (MouseDragManager dragManager) private
Definition at line 119 of file SelectionBox.java.
References game_engine.UI.MouseManager.getLastClick(), game_engine.visuals.SelectionBox.pressedX, game_engine.visuals.SelectionBox.pressedY, game_engine.visuals.SelectionBox.setSize(), game_engine.visuals.SelectionBox.setVisible(), game_engine.visuals.SelectionBox.setX(), and game_engine.visuals.SelectionBox.setY().
Referenced by game_engine.visuals.SelectionBox.update().
void game_engine.visuals.SelectionBox.released (double topLeftX, double topLeftY, double bottomRightX, double bottomRightY)
Definition at line 34 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.update().
void game_engine.visuals.SelectionBox.resetBox ()
Definition at line 51 of file SelectionBox.java.
References game_engine.visuals.SelectionBox.setLocation(), and game_engine.visuals.SelectionBox.setSize().
Referenced by game_engine.visuals.SelectionBox.update().
void game_engine.visuals.SelectionBox.setLocation (double x, double y)
Definition at line 70 of file SelectionBox.java.
References game_engine.visuals.SelectionBox.setX(), and game_engine.visuals.SelectionBox.setY().
Referenced by game_engine.visuals.SelectionBox.resetBox(), and game_engine.visuals.SelectionBox.update().
void game_engine.visuals.SelectionBox.setSize (double width, double height)
Definition at line 57 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.reactToDrag(), and game_engine.visuals.SelectionBox.resetBox().
void game_engine.visuals.SelectionBox.setVisible (boolean b)
Definition at line 75 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.reactToDrag(), and game_engine.visuals.SelectionBox.update().
void game_engine.visuals.SelectionBox.setX (double x)
Definition at line 62 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.reactToDrag(), and game_engine.visuals.SelectionBox.setLocation().
void game_engine.visuals.SelectionBox.setY (double y)
Definition at line 66 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.reactToDrag(), and game_engine.visuals.SelectionBox.setLocation().
void game_engine.visuals.SelectionBox.update (Observable o, Object arg)
Definition at line 80 of file SelectionBox.java.
References game_engine.UI.MouseManager.getLastClick(), game_engine.UI.MouseManager.getMapLoc(), game_engine.visuals.SelectionBox.reactToDrag(), game_engine.visuals.SelectionBox.released(), game_engine.visuals.SelectionBox.resetBox(), game_engine.visuals.SelectionBox.setLocation(), and game_engine.visuals.SelectionBox.setVisible().
Member Data Documentation
MouseEvent game_engine.visuals.SelectionBox.lastEvent private
Definition at line 25 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.getLastClick().
Rectangle game_engine.visuals.SelectionBox.myRectangle private
Definition at line 22 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.getBox().
double [] game_engine.visuals.SelectionBox.points = new double[4] private
Definition at line 24 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.getPoints().
double game_engine.visuals.SelectionBox.pressedX private
Definition at line 23 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.reactToDrag().
double game_engine.visuals.SelectionBox.pressedY package
Definition at line 23 of file SelectionBox.java.
Referenced by game_engine.visuals.SelectionBox.reactToDrag().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/SelectionBox.java