voogasalad_TheException: engine.computers.boundsComputers.VisionComputer Class Reference
engine.computers.boundsComputers.VisionComputer Class Reference
Protected Member Functions
boolean checkComputingCondition (SelectableGameElement primaryObject, DrawableGameElement otherObject)
void givePrimaryObjectElements (SelectableGameElement primaryObject, List< DrawableGameElement > listToAdd)
Protected Member Functions inherited from engine.computers.Computer< T, E >
abstract void givePrimaryObjectElements (T primaryObject, List< E > objectsOfInterest)
abstract boolean checkComputingCondition (T primaryObject, E otherObject)
Additional Inherited Members
Public Member Functions inherited from engine.computers.Computer< T, E >
void compute (T primaryObject, List< E > objectsToCheck)
Detailed Description
A computer that indicates which objects an object with sight can see
Author
Zachary Bears, Jonathan
Definition at line 19 of file VisionComputer.java.
Member Function Documentation
boolean engine.computers.boundsComputers.VisionComputer.checkComputingCondition (SelectableGameElement primaryObject, DrawableGameElement otherObject) protected
Return true if the other object is contained within the primary object's vision bounds
See also
Computer::checkComputingCondition
Definition at line 28 of file VisionComputer.java.
References model.state.gameelement.traits.Boundable.getBounds(), and model.state.gameelement.traits.Sighted.getVisionBounds().
void engine.computers.boundsComputers.VisionComputer.givePrimaryObjectElements (SelectableGameElement primaryObject, List< DrawableGameElement > listToAdd) protected
Add the elements of interest to the primary object's visible elements list
See also
Computer::givePrimaryObjectElements
Definition at line 49 of file VisionComputer.java.
References engine.gameRepresentation.renderedRepresentation.SelectableGameElement.addInteractingElements(), and engine.computers.objectClassifications.InteractingElementType.VISIBLE.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/computers/boundsComputers/VisionComputer.java