voogasalad_TheException: editor.LevelTriggersViewController Class Reference
editor.LevelTriggersViewController Class Reference
Classes
class TriggerListCell
Public Member Functions
void setButtonAction (Consumer< Consumer< WizardData >> consumer)
Node getRoot ()
void initialize ()
void updateTriggerList (List< TriggerPair > triggers)
Private Member Functions
void initListView ()
Private Attributes
VBox levelTriggersView
Button newLevelTrigger
ListView< String > levelTriggers
ObservableList< String > myTriggerList
Detailed Description
Author
Jonathan Tseng
Nishad Agrawal
Definition at line 27 of file LevelTriggersViewController.java.
Member Function Documentation
Node editor.LevelTriggersViewController.getRoot ()
Implements view.GUIController.
Definition at line 43 of file LevelTriggersViewController.java.
References editor.LevelTriggersViewController.levelTriggersView.
void editor.LevelTriggersViewController.initialize ()
Implements view.GUIController.
Definition at line 48 of file LevelTriggersViewController.java.
References editor.LevelTriggersViewController.initListView().
void editor.LevelTriggersViewController.initListView () private
Definition at line 52 of file LevelTriggersViewController.java.
Referenced by editor.LevelTriggersViewController.initialize().
void editor.LevelTriggersViewController.setButtonAction (Consumer< Consumer< WizardData >> consumer)
Definition at line 38 of file LevelTriggersViewController.java.
Referenced by editor.TabViewController.init().
void editor.LevelTriggersViewController.updateTriggerList (List< TriggerPair > triggers)
Definition at line 70 of file LevelTriggersViewController.java.
Referenced by editor.TabViewController.updateLevelTriggersView().
Member Data Documentation
ListView<String> editor.LevelTriggersViewController.levelTriggers private
Definition at line 34 of file LevelTriggersViewController.java.
VBox editor.LevelTriggersViewController.levelTriggersView private
Definition at line 30 of file LevelTriggersViewController.java.
Referenced by editor.LevelTriggersViewController.getRoot().
ObservableList<String> editor.LevelTriggersViewController.myTriggerList private
Definition at line 36 of file LevelTriggersViewController.java.
Button editor.LevelTriggersViewController.newLevelTrigger private
Definition at line 32 of file LevelTriggersViewController.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/LevelTriggersViewController.java