voogasalad_TheException: view.editor.wizards.Wizard Class Reference
view.editor.wizards.Wizard Class Reference abstract
Public Member Functions
Node getRoot ()
void initialize ()
void setSubmit (Consumer< WizardData > c)
abstract boolean checkCanSave ()
abstract void updateData ()
abstract void launchForEdit (WizardData oldValues)
abstract void loadGlobalValues (List< String > values)
WizardData getWizardData ()
void displayErrorMessage (String error)
void removeWizardData (WizardData data)
void setStage (Stage s)
void closeStage ()
Static Public Attributes
static final String NUM_REGEX = "-?[0-9]+\\.?[0-9]*"
Protected Member Functions
void addToData (WizardDataType key, String value)
void addWizardData (WizardData wizData)
void setWizardType (WizardType type)
void attachTextProperties ()
boolean isNumber (String value)
Protected Attributes
SplitPane root
Button save
Text errorMessage
Private Member Functions
void save ()
void displayWarning ()
Private Attributes
Consumer< WizardData > mySaveConsumer
WizardData myUserInput
Stage myStage
Static Private Attributes
static final int ERROR_DISPLAY_DURATION = 3000
static final String SAVE_KEY = "Save"
static final String ERROR_KEY = "SaveError"
Detailed Description
This class represents the core functionality of any wizard within the Editor. It requires a concrete implementation of a Controller class which extends it along with an associated FXML file which includes specified fx:id's root, save, and errorMessage. This class gives the class which launches the wizard the ability to modify the error message, set a Consumer lambda function for when the save button is clicked, along with getting the data submitted by the wizard, and the stage held by the wizard such that it can be closed.
Author
Joshua, Nishad
Definition at line 36 of file Wizard.java.
Member Function Documentation
void view.editor.wizards.Wizard.addToData (WizardDataType key, String value) protected
Enables implementations of this abstract class to modify the WizardData with data inputted by the user, ideally this should only be called within updateData()
Parameters
key the type of data being saved
value the value of the data being saved, as a string
Definition at line 111 of file Wizard.java.
References model.data.WizardData.addDataPair().
Referenced by view.editor.wizards.AttributeWizard.storeKeyValuePair(), view.editor.wizards.CampaignWizard.updateData(), view.editor.wizards.PositionWizard.updateData(), view.editor.wizards.WidgetWizard.updateData(), view.editor.wizards.ActionWizard.updateData(), view.editor.wizards.LevelWizard.updateData(), view.editor.wizards.BoundsWizard.updateData(), view.editor.wizards.GameElementWizard.updateData(), and view.editor.wizards.AnimationWizard.updateData().
void view.editor.wizards.Wizard.addWizardData (WizardData wizData) protected
Enables implementations of this abstract class to modify the WizardData with nested wizards
Parameters
wizData the wizard data contanied by a nested wizard
Definition at line 121 of file Wizard.java.
References model.data.WizardData.addWizardData().
Referenced by view.editor.wizards.GameElementWizard.launchBoundsWizard(), and view.editor.wizards.GameElementWizard.storeContainerData().
void view.editor.wizards.Wizard.attachTextProperties () protected
Binds the multilanguage util to the text in the wizard
Definition at line 213 of file Wizard.java.
References view.editor.wizards.Wizard.displayErrorMessage(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.editor.wizards.Wizard.initialize().
abstract boolean view.editor.wizards.Wizard.checkCanSave () abstract
Note: this always happens before data is actually added to the WizardData
Returns
whether or not the data is acceptable to send to the model for the creation of whatever this wizard is intended to produce
Referenced by view.editor.wizards.Wizard.save().
void view.editor.wizards.Wizard.closeStage ()
Returns
The stage which holds this Wizard.
Definition at line 205 of file Wizard.java.
Referenced by view.editor.TabViewController.createInternalConsumer(), view.editor.wizards.GameElementWizard.launchBoundsWizard(), view.editor.wizards.CRUDContainer.launchEditWizard(), view.editor.TabViewController.launchNestedWizard(), view.editor.wizards.CRUDContainer.launchNestedWizard(), view.editor.EditorMenuBarController.onNewCampaignClick(), view.editor.EditorMenuBarController.onNewLevelClick(), view.editor.ElementAccordionController.openDrawableGameElementWizard(), and view.editor.ElementAccordionController.openSelectableGameElementWizard().
void view.editor.wizards.Wizard.displayErrorMessage (String error)
Parameters
error The new message to display when called.
Definition at line 178 of file Wizard.java.
References view.editor.wizards.Wizard.errorMessage.
Referenced by view.editor.wizards.CampaignWizard.attachTextProperties(), view.editor.wizards.PositionWizard.attachTextProperties(), view.editor.wizards.AttributeWizard.attachTextProperties(), view.editor.wizards.LevelWizard.attachTextProperties(), view.editor.wizards.WidgetWizard.attachTextProperties(), view.editor.wizards.AnimationWizard.attachTextProperties(), view.editor.wizards.Wizard.attachTextProperties(), view.editor.wizards.Wizard.displayWarning(), view.editor.wizards.GameElementWizard.isAnimationLaunchValid(), view.editor.wizards.GameElementWizard.loadColorMask(), view.editor.wizards.AnimationWizard.loadImage(), view.editor.wizards.GameElementWizard.loadImage(), view.editor.EditorMenuBarController.onNewCampaignClick(), view.editor.EditorMenuBarController.onNewLevelClick(), and view.editor.wizards.AnimationWizard.updateAnimationGrid().
void view.editor.wizards.Wizard.displayWarning () private
used internally to display the default error message if none has been provided.
Definition at line 156 of file Wizard.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), view.editor.wizards.Wizard.displayErrorMessage(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.editor.wizards.Wizard.save().
Node view.editor.wizards.Wizard.getRoot ()
Returns the root of the wizard's scene
Returns
Node root - the root of the scene
Implements view.gui.GUIController.
Definition at line 65 of file Wizard.java.
References view.editor.wizards.Wizard.root.
Referenced by view.editor.wizards.WizardUtility.loadWizard().
WizardData view.editor.wizards.Wizard.getWizardData ()
Returns
The WizardData object associated with this Wizard
Definition at line 170 of file Wizard.java.
References view.editor.wizards.Wizard.myUserInput.
Referenced by view.editor.wizards.GameElementWizard.boundsAlreadyExist(), view.editor.wizards.GameElementWizard.checkCanSave(), view.editor.wizards.GameElementWizard.getBoundsFromWizardData(), and view.editor.wizards.GameElementWizard.launchBoundsWizard().
void view.editor.wizards.Wizard.initialize ()
The default initialization of a wizard which creates a wizard data and puts a null consumer into the save button action.
Implements view.gui.GUIController.
Definition at line 74 of file Wizard.java.
References view.editor.wizards.Wizard.attachTextProperties(), view.editor.wizards.Wizard.myUserInput, and view.editor.wizards.Wizard.save().
boolean view.editor.wizards.Wizard.isNumber (String value) protected
Definition at line 223 of file Wizard.java.
Referenced by view.editor.wizards.WidgetWizard.argumentsValid(), view.editor.wizards.NumberAttributeWizard.checkCanSave(), view.editor.wizards.PositionWizard.checkCanSave(), view.editor.wizards.LevelWizard.checkCanSave(), view.editor.wizards.AnimationWizard.checkCanSave(), view.editor.wizards.BoundsWizard.checkCoordinatesValid(), view.editor.wizards.ActionWizard.dropdownsValid(), view.editor.wizards.GameElementWizard.setTextListener(), and view.editor.wizards.AnimationWizard.updateAnimationGrid().
abstract void view.editor.wizards.Wizard.launchForEdit (WizardData oldValues) abstract
Referenced by view.editor.wizards.GameElementWizard.launchBoundsWizard(), view.editor.wizards.CRUDContainer.launchEditWizard(), and view.editor.TabViewController.modifyGoals().
abstract void view.editor.wizards.Wizard.loadGlobalValues (List< String > values) abstract
Referenced by view.editor.TabViewController.addNumberAttributes(), view.editor.wizards.CRUDContainer.launchEditWizard(), view.editor.wizards.CRUDContainer.launchNestedWizard(), and view.editor.EditorMenuBarController.onNewLevelClick().
void view.editor.wizards.Wizard.removeWizardData (WizardData data)
Definition at line 188 of file Wizard.java.
References model.data.WizardData.removeWizardData().
void view.editor.wizards.Wizard.save () private
This is the default workflow for when the user hits the save button
Definition at line 85 of file Wizard.java.
References view.editor.wizards.Wizard.checkCanSave(), view.editor.wizards.Wizard.displayWarning(), and view.editor.wizards.Wizard.updateData().
Referenced by view.editor.wizards.Wizard.initialize().
void view.editor.wizards.Wizard.setStage (Stage s)
This should only be done by the WizardUtility which actually spawns a new wizard.
Parameters
s The stage which holds the Wizard
Definition at line 197 of file Wizard.java.
Referenced by view.editor.wizards.WizardUtility.loadWizard().
void view.editor.wizards.Wizard.setSubmit (Consumer< WizardData > c)
Parameters
c The Consumer of a WizardData to execute when save is hit if the wizard allows it to be saved
Definition at line 100 of file Wizard.java.
Referenced by view.editor.wizards.GameElementWizard.launchBoundsWizard(), view.editor.wizards.CRUDContainer.launchEditWizard(), view.editor.TabViewController.launchNestedWizard(), view.editor.wizards.CRUDContainer.launchNestedWizard(), view.editor.TabViewController.modifyGoals(), view.editor.EditorMenuBarController.onNewCampaignClick(), view.editor.EditorMenuBarController.onNewLevelClick(), view.editor.ElementAccordionController.openDrawableGameElementWizard(), and view.editor.ElementAccordionController.openSelectableGameElementWizard().
void view.editor.wizards.Wizard.setWizardType (WizardType type) protected
Parameters
type defines what type of wizard this is for a factory within the model
Definition at line 129 of file Wizard.java.
References model.data.WizardData.setType().
Referenced by view.editor.wizards.NumberAttributeWizard.updateData(), view.editor.wizards.CampaignWizard.updateData(), view.editor.wizards.PositionWizard.updateData(), view.editor.wizards.AttributeWizard.updateData(), view.editor.wizards.WidgetWizard.updateData(), view.editor.wizards.ActionWizard.updateData(), view.editor.wizards.LevelWizard.updateData(), view.editor.wizards.BoundsWizard.updateData(), view.editor.wizards.GameElementWizard.updateData(), and view.editor.wizards.AnimationWizard.updateData().
abstract void view.editor.wizards.Wizard.updateData () abstract
This method is the essential method within the wizard where the concrete implementation of a wizard, must convert the user inputted JavaFX data fields into data in a WizardData. Please be sure to use the given methods addToData(String, String) and addWizardData(WizardData).
Referenced by view.editor.wizards.Wizard.save().
Member Data Documentation
final int view.editor.wizards.Wizard.ERROR_DISPLAY_DURATION = 3000 static private
Definition at line 38 of file Wizard.java.
final String view.editor.wizards.Wizard.ERROR_KEY = "SaveError" static private
Definition at line 40 of file Wizard.java.
Text view.editor.wizards.Wizard.errorMessage protected
Definition at line 49 of file Wizard.java.
Referenced by view.editor.wizards.Wizard.displayErrorMessage(), view.editor.wizards.GameElementWizard.initialize(), and view.editor.wizards.AnimationWizard.initialize().
Consumer<WizardData> view.editor.wizards.Wizard.mySaveConsumer private
Default error message
Definition at line 55 of file Wizard.java.
Stage view.editor.wizards.Wizard.myStage private
Definition at line 57 of file Wizard.java.
WizardData view.editor.wizards.Wizard.myUserInput private
Definition at line 56 of file Wizard.java.
Referenced by view.editor.wizards.Wizard.getWizardData(), and view.editor.wizards.Wizard.initialize().
final String view.editor.wizards.Wizard.NUM_REGEX = "-?[0-9]+\\.?[0-9]*" static
Definition at line 41 of file Wizard.java.
SplitPane view.editor.wizards.Wizard.root protected
Definition at line 44 of file Wizard.java.
Referenced by view.editor.wizards.Wizard.getRoot().
Button view.editor.wizards.Wizard.save protected
Definition at line 46 of file Wizard.java.
final String view.editor.wizards.Wizard.SAVE_KEY = "Save" static private
Definition at line 39 of file Wizard.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/Wizard.java