voogasalad_TheException: engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T > Class Template Reference
engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T > Class Template Reference abstract
Public Member Functions
Evaluator (Class< T > type, String evaluatorRepresentation, Evaluatable< A > parameter1, Evaluatable< B > parameter2)
T evaluate (ElementPair elements)
T delegateEvaluator (A parameter1Value, B parameter2Value)
String toString ()
Public Member Functions inherited from engine.gameRepresentation.evaluatables.Evaluatable< T >
Evaluatable (Class< T > type)
abstract T evaluate (ElementPair elements)
boolean setValue (ElementPair elements, T value)
boolean setValue (T value)
Class< T > getType ()
Protected Member Functions
T evaluate (Object item1, Object item2)
T evaluate (Number item1, Number item2)
T evaluate (Boolean item1, Boolean item2)
T evaluate (GameElement item1, GameElement item2)
T evaluate (GameElement item1, String item2)
T evaluate (GameElement item1, ActionRepresentation item2)
T evaluate (GameElement item1, ElementPromise item2)
Evaluatable< A > getParameter1 ()
Evaluatable< B > getParameter2 ()
boolean setParameter1Value (Object value)
boolean setParameter2Value (Object value)
Private Attributes
String myEvaluatorRepresentation
Evaluatable< A > myParameter1
Evaluatable< B > myParameter2
ElementPair myElementPair
Detailed Description
An abstract class for evaluators that acts on parameters to provide for functionality such as <, >, <=, >=, +=, getNearest, etc. All implementations of evaluators must implement the evaluate method for their appropriate data type, allowing for a large variety of functions to be implemented.
Author
Zach
Parameters
<A> The type returned by the first parameter of the evaluatable
<B> the type returned by the second parameter of the evaluatable
<T> the type returned by the evaluatable
Definition at line 24 of file Evaluator.java.
Constructor & Destructor Documentation
engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.Evaluator (Class< T > type, String evaluatorRepresentation, Evaluatable< A > parameter1, Evaluatable< B > parameter2)
Create the evaluator with the string representation of the evaluator. This string representation will be set by the children of the evaluator and will be used in the creation of evaluators by a factory.
Parameters
type the return type of the evaluator. Used to bypass Java generic type erasure
id an id used by all leaves of an evaluatable tree to reference the tree as a whole
evaluatorRepresentation the representation of the evaluator e.g. "<=", "==","+="
elementManager the main game element manager
parameter1 a string representation of the parameter on the left side of the evaluator
parameter2 a string representation of the parameter on the right side of the evaluator
Definition at line 50 of file Evaluator.java.
Member Function Documentation
T engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.delegateEvaluator (A parameter1Value, B parameter2Value)
A method that delegates the public evaluate method to private evaluate methods with given casting. This method is messy but is the only way to work around generic erasure and compile-time typing by java. This method, although messy, allows for a powerful design pattern to work for the rest of the code and was included in order to take a hit in terms of ugly code to allow other code other code in the program to be cleaner.
Parameters
parameter1Value the value of the first parameter
parameter2Value the value of the second parameter
Returns
the result of evaluating on the two parameters
Definition at line 144 of file Evaluator.java.
Referenced by engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.evaluate().
T engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate (Object item1, Object item2) protected
Evaluate on two objects. By default returns null as all child evaluate methods implements necessary class overrides.
Parameters
item1 the object on the left side of the evaluator
item2 the object on the right side of the evaluator
Returns
the result of the evaluation on the two objects
Definition at line 69 of file Evaluator.java.
Referenced by engine.computers.boundsComputers.CollisionComputer.checkComputingCondition(), engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.delegateEvaluator(), engine.gameRepresentation.evaluatables.evaluators.NotCollision< A, B >.evaluate(), engine.gameRepresentation.evaluatables.actions.CheckAttributeCreateObjectAction.evaluate(), and engine.gameRepresentation.evaluatables.actions.MotherOfAllActions.evaluate().
T engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate (Number item1, Number item2) protected
Evaluate on two doubles
Definition at line 76 of file Evaluator.java.
T engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate (Boolean item1, Boolean item2) protected
Evaluate on two booleans
Definition at line 83 of file Evaluator.java.
T engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate (GameElement item1, GameElement item2) protected
Evaluate on two elements
Definition at line 90 of file Evaluator.java.
T engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate (GameElement item1, String item2) protected
Evaluate on one game element and one string
Definition at line 97 of file Evaluator.java.
T engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate (GameElement item1, ActionRepresentation item2) protected
Evaluate on one game element and one Action
Definition at line 104 of file Evaluator.java.
T engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate (GameElement item1, ElementPromise item2) protected
Evaluate on a game element and an element promise
Definition at line 111 of file Evaluator.java.
T engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate (ElementPair elements)
Evaluate the evaluator on the element pair
Parameters
elements a pairing of the current element and the element that is being examined by it
Definition at line 123 of file Evaluator.java.
Evaluatable<A> engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.getParameter1 () protected
Returns
the first parameter
Definition at line 166 of file Evaluator.java.
Evaluatable<B> engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.getParameter2 () protected
Returns
the second parameter
Definition at line 173 of file Evaluator.java.
boolean engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.setParameter1Value (Object value) protected
Set the value of the first parameter to a given value. Used by all assignment operators.
Parameters
value the value to set the first parameter to
Returns
a boolean indicating whether the setting was successful
Definition at line 185 of file Evaluator.java.
boolean engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.setParameter2Value (Object value) protected
Set the value for the second parameter. I understant that this code is a large amount of repeat from above. This had to happen due to javafx generics type erasure.
Parameters
value the value to set the first parameter to
Returns
a boolean indicating whether the setting was successful
Definition at line 205 of file Evaluator.java.
String engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.toString ()
Definition at line 218 of file Evaluator.java.
Member Data Documentation
ElementPair engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.myElementPair private
Definition at line 28 of file Evaluator.java.
String engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.myEvaluatorRepresentation private
Definition at line 25 of file Evaluator.java.
Referenced by engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.toString().
Evaluatable<A> engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.myParameter1 private
Definition at line 26 of file Evaluator.java.
Referenced by engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.getParameter1().
Evaluatable<B> engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.myParameter2 private
Definition at line 27 of file Evaluator.java.
Referenced by engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.getParameter2().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/evaluatables/evaluators/Evaluator.java