voogasalad_TheException: view.GUIScreen Class Reference
view.GUIScreen Class Reference abstract
Public Member Functions
void attachSceneHandler (MainView mainView)
Public Member Functions inherited from view.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
abstract void update ()
Public Member Functions inherited from view.GUIController
abstract Node getRoot ()
Protected Member Functions
void switchScreen (ViewScreen screen)
Protected Member Functions inherited from view.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Private Attributes
MainView myMainView
Additional Inherited Members
Protected Attributes inherited from view.GUIContainer
MainModel myMainModel
Detailed Description
Author
Nishad Agrawal, Jonathan Tseng
Definition at line 8 of file GUIScreen.java.
Member Function Documentation
void view.GUIScreen.attachSceneHandler (MainView mainView)
Definition at line 12 of file GUIScreen.java.
Referenced by view.MainView.launchScreen().
void view.GUIScreen.switchScreen (ViewScreen screen) protected
Definition at line 16 of file GUIScreen.java.
References view.MainView.launchScreen().
Referenced by view.SplashScreen.setUpButtons().
Member Data Documentation
MainView view.GUIScreen.myMainView private
Definition at line 10 of file GUIScreen.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/GUIScreen.java