voogasalad_TheException: game_engine.visuals.AnimationSequence Class Reference
game_engine.visuals.AnimationSequence Class Reference
Public Member Functions
AnimationSequence (String name, int startFrame, int stopFrame, boolean repeats)
AnimationSequence (String name, int startFrame, int stopFrame, boolean repeats, double slownessMultiplier)
AnimationSequence (String name, int startFrame, int stopFrame, AnimationSequence nextAnimation)
AnimationSequence reset ()
void setNextAnimation (AnimationSequence animation)
AnimationSequence getNextAnimation ()
boolean update ()
int getFrame ()
String toString ()
Private Attributes
int myStartFrame
int myStopFrame
int myCurrentFrame
String myName
AnimationSequence myNextAnimation
double mySlownessMultiplier
int myFrameCounter
Detailed Description
A basic animation. Keeps track of progress, the frame bounds, and the animation that will be played after it
Author
Zachary Bears
Definition at line 12 of file AnimationSequence.java.
Constructor & Destructor Documentation
game_engine.visuals.AnimationSequence.AnimationSequence (String name, int startFrame, int stopFrame, boolean repeats)
Initialize the animation
Parameters
name the animation's name
startFrame the start frame of the animation
stopFrame the stop frame of the animation
Definition at line 29 of file AnimationSequence.java.
game_engine.visuals.AnimationSequence.AnimationSequence (String name, int startFrame, int stopFrame, boolean repeats, double slownessMultiplier)
Initialize the animation and insert a multiplier for slowness
Parameters
slownessMultiplier a multiplier for the speed of the animation. Must be less than 1.
Definition at line 43 of file AnimationSequence.java.
game_engine.visuals.AnimationSequence.AnimationSequence (String name, int startFrame, int stopFrame, AnimationSequence nextAnimation)
Initialize the animation and set the next animation
Parameters
nextAnimation
Definition at line 59 of file AnimationSequence.java.
Member Function Documentation
int game_engine.visuals.AnimationSequence.getFrame ()
Get the current frame of the animation
Returns
Definition at line 117 of file AnimationSequence.java.
References game_engine.visuals.AnimationSequence.myCurrentFrame.
Referenced by game_engine.visuals.AnimationPlayer.update().
AnimationSequence game_engine.visuals.AnimationSequence.getNextAnimation ()
Get the next animation, resetting it to ensure it starts from the beginning
Returns
Definition at line 89 of file AnimationSequence.java.
References game_engine.visuals.AnimationSequence.reset().
Referenced by game_engine.visuals.AnimationPlayer.update().
AnimationSequence game_engine.visuals.AnimationSequence.reset ()
Reset the animation to the start frame
Definition at line 70 of file AnimationSequence.java.
References game_engine.visuals.AnimationSequence.myStartFrame.
Referenced by game_engine.visuals.AnimationSequence.getNextAnimation().
void game_engine.visuals.AnimationSequence.setNextAnimation (AnimationSequence animation)
Sets the animation's following animation
Parameters
animation
Definition at line 80 of file AnimationSequence.java.
Referenced by game_engine.visuals.AnimationPlayer.setNextAnimation().
String game_engine.visuals.AnimationSequence.toString ()
Definition at line 122 of file AnimationSequence.java.
References game_engine.visuals.AnimationSequence.myName.
Referenced by game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.addAnimation().
boolean game_engine.visuals.AnimationSequence.update ()
Increments the animation frame. Return true if the animation is complete.
Implements game_engine.gameRepresentation.stateRepresentation.gameElement.traits.Updatable.
Definition at line 97 of file AnimationSequence.java.
Referenced by game_engine.visuals.AnimationPlayer.update().
Member Data Documentation
int game_engine.visuals.AnimationSequence.myCurrentFrame private
Definition at line 16 of file AnimationSequence.java.
Referenced by game_engine.visuals.AnimationSequence.getFrame().
int game_engine.visuals.AnimationSequence.myFrameCounter private
Definition at line 20 of file AnimationSequence.java.
String game_engine.visuals.AnimationSequence.myName private
Definition at line 17 of file AnimationSequence.java.
Referenced by game_engine.visuals.AnimationSequence.toString().
AnimationSequence game_engine.visuals.AnimationSequence.myNextAnimation private
Definition at line 18 of file AnimationSequence.java.
double game_engine.visuals.AnimationSequence.mySlownessMultiplier private
Definition at line 19 of file AnimationSequence.java.
int game_engine.visuals.AnimationSequence.myStartFrame private
Definition at line 14 of file AnimationSequence.java.
Referenced by game_engine.visuals.AnimationSequence.reset().
int game_engine.visuals.AnimationSequence.myStopFrame private
Definition at line 15 of file AnimationSequence.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/AnimationSequence.java