voogasalad_TheException: engine.UI.EditorInputManager Class Reference
engine.UI.EditorInputManager Class Reference
Public Member Functions
EditorInputManager (MainModel model, GameElementManager gameElementManager, GameLoop gameLoop, Participant user)
void primaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
void secondaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
void primaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
void secondaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
void keyPressed (KeyEvent e)
void primaryDragOccurred (MouseEvent e, SelectionBox b)
void secondaryDragOccurred (MouseEvent e, SelectionBox b)
void screenButtonClicked (int buttonID)
Public Member Functions inherited from engine.UI.InputManager
InputManager (MainModel model, GameElementManager gameElementManager, GameLoop gameLoop, Participant user)
abstract void primaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
abstract void secondaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
abstract void primaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
abstract void secondaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
abstract void primaryDragOccurred (MouseEvent e, SelectionBox b)
abstract void secondaryDragOccurred (MouseEvent e, SelectionBox b)
abstract void keyPressed (KeyEvent e)
abstract void screenButtonClicked (int buttonID)
Private Member Functions
boolean checkElementAndCreate (String element, Consumer< String > consumer)
Additional Inherited Members
Protected Attributes inherited from engine.UI.InputManager
MainModel myMainModel
GameElementManager myElementManager
GameLoop myGameLoop
Participant myUser
Detailed Description
Input Manager when the editor is toggled as opposed to the game runner does not use the selection box... only 1 element can be selected at a time
Author
Jonathan Tseng, John L.
Definition at line 22 of file EditorInputManager.java.
Constructor & Destructor Documentation
engine.UI.EditorInputManager.EditorInputManager (MainModel model, GameElementManager gameElementManager, GameLoop gameLoop, Participant user)
Definition at line 24 of file EditorInputManager.java.
References engine.stateManaging.GameLoop.setEditorLoop().
Member Function Documentation
boolean engine.UI.EditorInputManager.checkElementAndCreate (String element, Consumer< String > consumer) private
Definition at line 56 of file EditorInputManager.java.
Referenced by engine.UI.EditorInputManager.primaryClickOccurred().
void engine.UI.EditorInputManager.keyPressed (KeyEvent e)
Definition at line 91 of file EditorInputManager.java.
References engine.stateManaging.GameElementManager.deleteSelectedUnit(), and engine.UI.InputManager.myElementManager.
void engine.UI.EditorInputManager.primaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
Definition at line 32 of file EditorInputManager.java.
References engine.stateManaging.GameElementManager.addDrawableGameElementToLevel(), engine.stateManaging.GameElementManager.addSelectableGameElementToLevel(), engine.UI.EditorInputManager.checkElementAndCreate(), model.MainModel.clearEditorChosen(), model.MainModel.getEditorChosenColor(), model.MainModel.getEditorChosenDrawable(), model.MainModel.getEditorChosenSelectable(), engine.UI.InputManager.myElementManager, engine.UI.InputManager.myMainModel, engine.UI.InputManager.myUser, engine.stateManaging.GameElementManager.selectAnySingleUnit(), and engine.stateManaging.GameElementManager.selectSingleUnit().
void engine.UI.EditorInputManager.primaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
Definition at line 75 of file EditorInputManager.java.
void engine.UI.EditorInputManager.primaryDragOccurred (MouseEvent e, SelectionBox b)
Definition at line 98 of file EditorInputManager.java.
void engine.UI.EditorInputManager.screenButtonClicked (int buttonID)
Definition at line 108 of file EditorInputManager.java.
void engine.UI.EditorInputManager.secondaryClickOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
Definition at line 65 of file EditorInputManager.java.
References engine.stateManaging.GameElementManager.moveSelectedUnit(), engine.UI.InputManager.myElementManager, and engine.UI.InputManager.myUser.
void engine.UI.EditorInputManager.secondaryClickReleaseOccurred (MouseEvent e, double mapTranslateX, double mapTranslateY, SelectionBox b)
Definition at line 83 of file EditorInputManager.java.
void engine.UI.EditorInputManager.secondaryDragOccurred (MouseEvent e, SelectionBox b)
Definition at line 103 of file EditorInputManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/UI/EditorInputManager.java