voogasalad_TheException: game_engine.computers.pathingComputers.PathingComputer Class Reference
game_engine.computers.pathingComputers.PathingComputer Class Reference
Public Member Functions
PathingComputer (MapGrid grid)
List< Location > findPath (double xStart, double yStart, double xEnd, double yEnd)
double determineCost (Location from, Location to)
List< Location > findPath (Location from, Location to)
Private Member Functions
double determineHeuristic (Location location)
double determinePathLength (Location from, Location to)
List< Location > reconstructPath (Location destination)
Private Attributes
MapGrid grid
PriorityQueue< Location > frontierLocations
HashMap< Location, Location > previousLocations
HashMap< Location, Double > minimumCosts
Location origin
List< Location > goals
Detailed Description
Implements the A* Search algorithm to figure out a path from a location to an objective.
Author
Steve
Definition at line 15 of file PathingComputer.java.
Constructor & Destructor Documentation
game_engine.computers.pathingComputers.PathingComputer.PathingComputer (MapGrid grid)
Definition at line 19 of file PathingComputer.java.
References game_engine.computers.pathingComputers.PathingComputer.grid.
Member Function Documentation
double game_engine.computers.pathingComputers.PathingComputer.determineCost (Location from, Location to)
Definition at line 68 of file PathingComputer.java.
References game_engine.computers.pathingComputers.PathingComputer.determinePathLength().
Referenced by game_engine.computers.pathingComputers.PathingComputer.findPath().
double game_engine.computers.pathingComputers.PathingComputer.determineHeuristic (Location location) private
Naive implementation of heuristic function (for now) assuming constant traversal time for every square, allowing for 8-directional movement and weighting diagonals appropriately.
Parameters
location - starting location
goal - ending location
Returns
diagonal adjustment to Chebyshev distance
Definition at line 41 of file PathingComputer.java.
References game_engine.computers.pathingComputers.Location.myX, and game_engine.computers.pathingComputers.Location.myY.
Referenced by game_engine.computers.pathingComputers.PathingComputer.findPath().
double game_engine.computers.pathingComputers.PathingComputer.determinePathLength (Location from, Location to) private
Naive implementation of distance function allowing for 8-directional movement and weighting diagonals appropriately.
Parameters
from
to
Returns
Definition at line 62 of file PathingComputer.java.
References game_engine.computers.pathingComputers.Location.movementSpeedScalingFactor, game_engine.computers.pathingComputers.Location.myX, and game_engine.computers.pathingComputers.Location.myY.
Referenced by game_engine.computers.pathingComputers.PathingComputer.determineCost().
List<Location> game_engine.computers.pathingComputers.PathingComputer.findPath (double xStart, double yStart, double xEnd, double yEnd)
Definition at line 23 of file PathingComputer.java.
List<Location> game_engine.computers.pathingComputers.PathingComputer.findPath (Location from, Location to)
Definition at line 75 of file PathingComputer.java.
References game_engine.computers.pathingComputers.PathingComputer.determineCost(), game_engine.computers.pathingComputers.PathingComputer.determineHeuristic(), game_engine.computers.pathingComputers.MapGrid.getNeighbors(), game_engine.computers.pathingComputers.MapGrid.getNeighborsForXYCoordinate(), and game_engine.computers.pathingComputers.PathingComputer.reconstructPath().
List<Location> game_engine.computers.pathingComputers.PathingComputer.reconstructPath (Location destination) private
Definition at line 108 of file PathingComputer.java.
References game_engine.computers.pathingComputers.MapGrid.getNeighborsForXYCoordinate().
Referenced by game_engine.computers.pathingComputers.PathingComputer.findPath().
Member Data Documentation
PriorityQueue<Location> game_engine.computers.pathingComputers.PathingComputer.frontierLocations private
Definition at line 27 of file PathingComputer.java.
List<Location> game_engine.computers.pathingComputers.PathingComputer.goals private
Definition at line 31 of file PathingComputer.java.
MapGrid game_engine.computers.pathingComputers.PathingComputer.grid private
Definition at line 17 of file PathingComputer.java.
Referenced by game_engine.computers.pathingComputers.PathingComputer.PathingComputer().
HashMap<Location, Double> game_engine.computers.pathingComputers.PathingComputer.minimumCosts private
Definition at line 29 of file PathingComputer.java.
Location game_engine.computers.pathingComputers.PathingComputer.origin private
Definition at line 30 of file PathingComputer.java.
HashMap<Location, Location> game_engine.computers.pathingComputers.PathingComputer.previousLocations private
Definition at line 28 of file PathingComputer.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/computers/pathingComputers/PathingComputer.java