voogasalad_TheException: engine.visuals.ScrollablePane Class Reference
engine.visuals.ScrollablePane Class Reference
Public Member Functions
ScrollablePane (Group root, double fieldWidth, double fieldHeight, String backgroundURI)
void bindSize (ReadOnlyDoubleProperty widthProperty, ReadOnlyDoubleProperty heightProperty)
ScrollableBackground getScrollingBackground ()
void mouseMoved (MouseEvent event)
void update ()
void addToScene (Group g)
void attachInputManager (InputManager inputManager)
double getFieldWidth ()
double getFieldHeight ()
void changeBackground (String backgroundURI)
Static Public Attributes
static final double SLOW_SCROLL_BOUNDARY = 120
static final double FAST_SCROLL_BOUNDARY = 75
static final double FAST_SPEED = 15
static final double SLOW_SPEED = 7
Private Member Functions
void initializeHandlers ()
void callCorrectMouseButtonAction (MouseEvent event, Consumer< MouseEvent > primaryAction, Consumer< MouseEvent > secondaryAction)
void setScrollSpeed (double mouseX, double mouseY)
Private Attributes
ScrollableBackground myBackground
SelectionBox mySelectionBox
InputManager myInputManager
Group root
double myMapWidth
double myMapHeight
Detailed Description
Basically the map. JavaFX Scene node that contains the eventHandlers necessary to scroll the map and register clicks.
Author
John, Michael D.
Definition at line 24 of file ScrollablePane.java.
Constructor & Destructor Documentation
engine.visuals.ScrollablePane.ScrollablePane (Group root, double fieldWidth, double fieldHeight, String backgroundURI)
Creates a new ScrollableScene for the map.
Parameters
root the group of elements to add to the Scene initially. If no objects have been created yet to add, just add an empty new Group()
width the width of the map (ideally larger than the screen width)
height the height of the map (ideally larger than the screen height)
Exceptions
IOException
Definition at line 47 of file ScrollablePane.java.
References engine.visuals.SelectionBox.getBox(), engine.visuals.ScrollablePane.initializeHandlers(), and engine.visuals.ScrollablePane.root.
Member Function Documentation
void engine.visuals.ScrollablePane.addToScene (Group g)
Definition at line 196 of file ScrollablePane.java.
Referenced by engine.visuals.VisualManager.attachParticipantManager(), and engine.visuals.VisualManager.VisualManager().
void engine.visuals.ScrollablePane.attachInputManager (InputManager inputManager)
Definition at line 200 of file ScrollablePane.java.
Referenced by engine.visuals.VisualManager.attachInputManager().
void engine.visuals.ScrollablePane.bindSize (ReadOnlyDoubleProperty widthProperty, ReadOnlyDoubleProperty heightProperty)
Definition at line 64 of file ScrollablePane.java.
void engine.visuals.ScrollablePane.callCorrectMouseButtonAction (MouseEvent event, Consumer< MouseEvent > primaryAction, Consumer< MouseEvent > secondaryAction) private
Definition at line 143 of file ScrollablePane.java.
Referenced by engine.visuals.ScrollablePane.initializeHandlers().
void engine.visuals.ScrollablePane.changeBackground (String backgroundURI)
Definition at line 213 of file ScrollablePane.java.
References engine.visuals.ScrollableBackground.tileBackground().
Referenced by engine.visuals.VisualManager.changeBackground().
double engine.visuals.ScrollablePane.getFieldHeight ()
Definition at line 209 of file ScrollablePane.java.
References engine.visuals.ScrollablePane.myMapHeight.
Referenced by engine.visuals.MiniMap.MiniMap().
double engine.visuals.ScrollablePane.getFieldWidth ()
Definition at line 205 of file ScrollablePane.java.
References engine.visuals.ScrollablePane.myMapWidth.
Referenced by engine.visuals.MiniMap.MiniMap().
ScrollableBackground engine.visuals.ScrollablePane.getScrollingBackground ()
gets the background map that objects actually get added to
Returns
the background of the scrollable scene
Definition at line 76 of file ScrollablePane.java.
References engine.visuals.ScrollablePane.myBackground.
Referenced by engine.visuals.MiniMap.moveSceneBox(), and engine.visuals.VisualManager.VisualManager().
void engine.visuals.ScrollablePane.initializeHandlers () private
initializes the handlers that respond to JavaFX events necessary for scrolling and registering clicks/ drags
Definition at line 84 of file ScrollablePane.java.
References engine.visuals.ScrollablePane.callCorrectMouseButtonAction(), engine.UI.InputManager.keyPressed(), engine.visuals.ScrollablePane.mouseMoved(), engine.visuals.ScrollableBackground.setXScrollSpeed(), and engine.visuals.ScrollableBackground.setYScrollSpeed().
Referenced by engine.visuals.ScrollablePane.ScrollablePane().
void engine.visuals.ScrollablePane.mouseMoved (MouseEvent event)
Definition at line 155 of file ScrollablePane.java.
References engine.visuals.ScrollablePane.setScrollSpeed().
Referenced by engine.visuals.ScrollablePane.initializeHandlers().
void engine.visuals.ScrollablePane.setScrollSpeed (double mouseX, double mouseY) private
Definition at line 164 of file ScrollablePane.java.
References engine.visuals.ScrollableBackground.setXScrollSpeed(), and engine.visuals.ScrollableBackground.setYScrollSpeed().
Referenced by engine.visuals.ScrollablePane.mouseMoved().
void engine.visuals.ScrollablePane.update ()
updates the background to scroll and draw selection boxes
Definition at line 192 of file ScrollablePane.java.
References engine.visuals.ScrollableBackground.update().
Referenced by engine.visuals.VisualManager.update().
Member Data Documentation
final double engine.visuals.ScrollablePane.FAST_SCROLL_BOUNDARY = 75 static
Definition at line 26 of file ScrollablePane.java.
Referenced by engine.visuals.AbilityMatrix.initializeDisplay(), and engine.visuals.MiniMap.MiniMap().
final double engine.visuals.ScrollablePane.FAST_SPEED = 15 static
Definition at line 27 of file ScrollablePane.java.
ScrollableBackground engine.visuals.ScrollablePane.myBackground private
Definition at line 30 of file ScrollablePane.java.
Referenced by engine.visuals.ScrollablePane.getScrollingBackground().
InputManager engine.visuals.ScrollablePane.myInputManager private
Definition at line 32 of file ScrollablePane.java.
double engine.visuals.ScrollablePane.myMapHeight private
Definition at line 36 of file ScrollablePane.java.
Referenced by engine.visuals.ScrollablePane.getFieldHeight().
double engine.visuals.ScrollablePane.myMapWidth private
Definition at line 35 of file ScrollablePane.java.
Referenced by engine.visuals.ScrollablePane.getFieldWidth().
SelectionBox engine.visuals.ScrollablePane.mySelectionBox private
Definition at line 31 of file ScrollablePane.java.
Group engine.visuals.ScrollablePane.root private
Definition at line 33 of file ScrollablePane.java.
Referenced by engine.visuals.ScrollablePane.ScrollablePane().
final double engine.visuals.ScrollablePane.SLOW_SCROLL_BOUNDARY = 120 static
Definition at line 25 of file ScrollablePane.java.
final double engine.visuals.ScrollablePane.SLOW_SPEED = 7 static
Definition at line 28 of file ScrollablePane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/ScrollablePane.java