voogasalad_TheException: view.editor.EditorScreen Class Reference
view.editor.EditorScreen Class Reference
Public Member Functions
Node getRoot ()
void updateModelToSave ()
void init ()
void modelUpdate ()
Public Member Functions inherited from view.gui.GUIScreen
void attachSceneHandler (MainView mainView)
void switchScreen (ViewScreenPath screen)
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Private Member Functions
void initProjectExplorer ()
void initInfoBox ()
void updateInfoBox (String[] selection)
void launchTab (LevelIdentifier levelID)
Tab createNewTab (LevelIdentifier levelID)
void initParticipantInfo ()
void attachTextProperties ()
void updateParticipantDropDown ()
void updateTabTexts ()
void updateProjectExplorer ()
Private Attributes
TabPane tabPane
TreeView< String > projectExplorer
ProjectExplorerController projectExplorerController
VBox gameInfoBox
DescribableInfoBoxController gameInfoBoxController
Parent editorMenuBar
EditorMenuBarController editorMenuBarController
BorderPane editorRoot
Button newGameElement
Button newTerrain
Button save
Accordion levelElementAccordion
ElementAccordionController levelElementAccordionController
ColorPicker teamColorPicker
Button addButton
ComboBox< String > participantDropDown
List< TabViewController > myTabViewControllers
Static Private Attributes
static final String TEAM_COLOR_PROMPT = "TeamColorPrompt"
static final String NEW_PARTICIPANT_KEY = "NewParticipant"
Additional Inherited Members
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Detailed Description
Screen for the Editor. Holds many sub-GUI panes
Author
Jonathan Tseng
Nishad Agrawal
Definition at line 46 of file EditorScreen.java.
Member Function Documentation
void view.editor.EditorScreen.attachTextProperties () private
Definition at line 198 of file EditorScreen.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), and util.multilanguage.MultiLanguageUtility.getStringProperty().
Referenced by view.editor.EditorScreen.init().
Tab view.editor.EditorScreen.createNewTab (LevelIdentifier levelID) private
Definition at line 147 of file EditorScreen.java.
References view.gui.GUIContainer.attachChildContainers(), model.state.LevelIdentifier.campaignName, view.dialog.DialogBoxUtility.createMessageDialog(), view.gui.GUIPanePath.EDITOR_TAB_VIEW, view.editor.TabViewController.getRoot(), model.state.LevelIdentifier.levelName, view.editor.TabViewController.modelUpdate(), and view.editor.TabViewController.setLevel().
Referenced by view.editor.EditorScreen.launchTab().
Node view.editor.EditorScreen.getRoot ()
Implements view.gui.GUIController.
Definition at line 87 of file EditorScreen.java.
References view.editor.EditorScreen.editorRoot.
void view.editor.EditorScreen.init ()
Definition at line 188 of file EditorScreen.java.
References view.gui.GUIContainer.attachChildContainers(), view.gui.MenuBarController.attachScreen(), view.editor.EditorScreen.attachTextProperties(), view.editor.EditorScreen.initInfoBox(), view.editor.EditorScreen.initParticipantInfo(), and view.editor.EditorScreen.initProjectExplorer().
void view.editor.EditorScreen.initInfoBox () private
Definition at line 107 of file EditorScreen.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), view.gui.GUIContainer.myMainModel, view.editor.DescribableInfoBoxController.setSubmitAction(), and model.MainModel.updateDescribableState().
Referenced by view.editor.EditorScreen.init().
void view.editor.EditorScreen.initParticipantInfo () private
Definition at line 174 of file EditorScreen.java.
References model.MainModel.addParticipantColor(), view.gui.GUIContainer.myMainModel, and model.MainModel.setEditorChosenColor().
Referenced by view.editor.EditorScreen.init().
void view.editor.EditorScreen.initProjectExplorer () private
Definition at line 91 of file EditorScreen.java.
References view.editor.ProjectExplorerController.getSelectedHierarchy(), view.editor.EditorScreen.launchTab(), view.editor.ProjectExplorerController.setOnLevelClicked(), view.editor.ProjectExplorerController.setOnSelectionChanged(), and view.editor.EditorScreen.updateInfoBox().
Referenced by view.editor.EditorScreen.init().
void view.editor.EditorScreen.launchTab (LevelIdentifier levelID) private
Definition at line 137 of file EditorScreen.java.
References view.editor.EditorScreen.createNewTab().
Referenced by view.editor.EditorScreen.initProjectExplorer().
void view.editor.EditorScreen.modelUpdate ()
Definition at line 211 of file EditorScreen.java.
References view.editor.ProjectExplorerController.getSelectedHierarchy(), view.editor.EditorScreen.updateInfoBox(), view.editor.EditorScreen.updateParticipantDropDown(), view.editor.EditorScreen.updateProjectExplorer(), and view.editor.EditorScreen.updateTabTexts().
void view.editor.EditorScreen.updateInfoBox (String[] selection) private
Definition at line 124 of file EditorScreen.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), model.MainModel.getDescribableState(), model.state.DescribableState.getDescription(), model.state.DescribableState.getName(), view.gui.GUIContainer.myMainModel, and view.editor.DescribableInfoBoxController.setText().
Referenced by view.editor.EditorScreen.initProjectExplorer(), and view.editor.EditorScreen.modelUpdate().
void view.editor.EditorScreen.updateModelToSave ()
Definition at line 101 of file EditorScreen.java.
void view.editor.EditorScreen.updateParticipantDropDown () private
Definition at line 221 of file EditorScreen.java.
References model.MainModel.getGameUniverse(), model.GameUniverse.getParticipantColors(), and view.gui.GUIContainer.myMainModel.
Referenced by view.editor.EditorScreen.modelUpdate().
void view.editor.EditorScreen.updateProjectExplorer () private
Definition at line 232 of file EditorScreen.java.
References model.state.GameState.getCampaigns(), model.MainModel.getCurrentGame(), model.state.DescribableState.getName(), view.gui.GUIContainer.myMainModel, and view.editor.ProjectExplorerController.update().
Referenced by view.editor.EditorScreen.modelUpdate().
void view.editor.EditorScreen.updateTabTexts () private
Definition at line 225 of file EditorScreen.java.
Referenced by view.editor.EditorScreen.modelUpdate().
Member Data Documentation
Button view.editor.EditorScreen.addButton private
Definition at line 80 of file EditorScreen.java.
Parent view.editor.EditorScreen.editorMenuBar private
Definition at line 62 of file EditorScreen.java.
EditorMenuBarController view.editor.EditorScreen.editorMenuBarController private
Definition at line 64 of file EditorScreen.java.
BorderPane view.editor.EditorScreen.editorRoot private
Definition at line 66 of file EditorScreen.java.
Referenced by view.editor.EditorScreen.getRoot().
VBox view.editor.EditorScreen.gameInfoBox private
Definition at line 58 of file EditorScreen.java.
DescribableInfoBoxController view.editor.EditorScreen.gameInfoBoxController private
Definition at line 60 of file EditorScreen.java.
Accordion view.editor.EditorScreen.levelElementAccordion private
Definition at line 74 of file EditorScreen.java.
ElementAccordionController view.editor.EditorScreen.levelElementAccordionController private
Definition at line 76 of file EditorScreen.java.
List<TabViewController> view.editor.EditorScreen.myTabViewControllers private
Definition at line 84 of file EditorScreen.java.
final String view.editor.EditorScreen.NEW_PARTICIPANT_KEY = "NewParticipant" static private
Definition at line 49 of file EditorScreen.java.
Button view.editor.EditorScreen.newGameElement private
Definition at line 68 of file EditorScreen.java.
Button view.editor.EditorScreen.newTerrain private
Definition at line 70 of file EditorScreen.java.
ComboBox<String> view.editor.EditorScreen.participantDropDown private
Definition at line 82 of file EditorScreen.java.
TreeView<String> view.editor.EditorScreen.projectExplorer private
Definition at line 54 of file EditorScreen.java.
ProjectExplorerController view.editor.EditorScreen.projectExplorerController private
Definition at line 56 of file EditorScreen.java.
Button view.editor.EditorScreen.save private
Definition at line 72 of file EditorScreen.java.
TabPane view.editor.EditorScreen.tabPane private
Definition at line 52 of file EditorScreen.java.
final String view.editor.EditorScreen.TEAM_COLOR_PROMPT = "TeamColorPrompt" static private
Definition at line 48 of file EditorScreen.java.
ColorPicker view.editor.EditorScreen.teamColorPicker private
Definition at line 78 of file EditorScreen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/EditorScreen.java