voogasalad_TheException: view.editor.ProjectExplorerController Class Reference
view.editor.ProjectExplorerController Class Reference
Public Member Functions
void update (String game, List< String > campaignOrder, Map< String, List< String >> campaignLevelMap)
void setOnSelectionChanged (Consumer< String[]> selectionChangedConsumer)
void setOnLevelClicked (Consumer< String > levelClicked)
String[] getSelectedHierarchy ()
Node getRoot ()
void initialize ()
Private Member Functions
void initListeners ()
void itemClicked (MouseEvent mouseEvent)
Private Attributes
TreeView< String > myTreeView
ProjectExplorerTreeItem< String > myGameNode
ObservableList< TreeItem< String > > myCampaigns
List< ProjectExplorerTreeItem< String > > myLevels
Consumer< String[]> mySelectionChangedConsumer
Consumer< String > myLevelClickedConsumer
Detailed Description
Controller for the project explorer
Author
Jonathan Tseng
Definition at line 25 of file ProjectExplorerController.java.
Member Function Documentation
Node view.editor.ProjectExplorerController.getRoot ()
Implements view.gui.GUIController.
Definition at line 122 of file ProjectExplorerController.java.
References view.editor.ProjectExplorerController.myTreeView.
String [] view.editor.ProjectExplorerController.getSelectedHierarchy ()
ugly code to get the hierarchy for the selected index
Returns
Definition at line 98 of file ProjectExplorerController.java.
Referenced by view.editor.ProjectExplorerController.initListeners(), view.editor.EditorScreen.initProjectExplorer(), and view.editor.EditorScreen.modelUpdate().
void view.editor.ProjectExplorerController.initialize ()
Implements view.gui.GUIController.
Definition at line 127 of file ProjectExplorerController.java.
References view.editor.ProjectExplorerController.initListeners().
void view.editor.ProjectExplorerController.initListeners () private
Definition at line 83 of file ProjectExplorerController.java.
References view.editor.ProjectExplorerController.getSelectedHierarchy(), and view.editor.ProjectExplorerController.itemClicked().
Referenced by view.editor.ProjectExplorerController.initialize().
void view.editor.ProjectExplorerController.itemClicked (MouseEvent mouseEvent) private
Definition at line 112 of file ProjectExplorerController.java.
References view.editor.ProjectExplorerTreeItem< T >.onClicked().
Referenced by view.editor.ProjectExplorerController.initListeners().
void view.editor.ProjectExplorerController.setOnLevelClicked (Consumer< String > levelClicked)
Definition at line 76 of file ProjectExplorerController.java.
Referenced by view.editor.EditorScreen.initProjectExplorer().
void view.editor.ProjectExplorerController.setOnSelectionChanged (Consumer< String[]> selectionChangedConsumer)
Definition at line 72 of file ProjectExplorerController.java.
Referenced by view.editor.EditorScreen.initProjectExplorer().
void view.editor.ProjectExplorerController.update (String game, List< String > campaignOrder, Map< String, List< String >> campaignLevelMap)
Definition at line 37 of file ProjectExplorerController.java.
References view.editor.ProjectExplorerTreeItem< T >.setAction().
Referenced by view.editor.EditorScreen.updateProjectExplorer().
Member Data Documentation
ObservableList<TreeItem<String> > view.editor.ProjectExplorerController.myCampaigns private
Definition at line 30 of file ProjectExplorerController.java.
ProjectExplorerTreeItem<String> view.editor.ProjectExplorerController.myGameNode private
Definition at line 29 of file ProjectExplorerController.java.
Consumer<String> view.editor.ProjectExplorerController.myLevelClickedConsumer private
Initial value:
= (String s) -> {
    }
Definition at line 34 of file ProjectExplorerController.java.
List<ProjectExplorerTreeItem<String> > view.editor.ProjectExplorerController.myLevels private
Definition at line 31 of file ProjectExplorerController.java.
Consumer<String[]> view.editor.ProjectExplorerController.mySelectionChangedConsumer private
Initial value:
= (String[] s) -> {
    }
Definition at line 32 of file ProjectExplorerController.java.
TreeView<String> view.editor.ProjectExplorerController.myTreeView private
Definition at line 28 of file ProjectExplorerController.java.
Referenced by view.editor.ProjectExplorerController.getRoot().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/ProjectExplorerController.java