voogasalad_TheException: model.state.gameelement.DrawableGameElementState Class Reference
model.state.gameelement.DrawableGameElementState Class Reference
Public Member Functions
DrawableGameElementState (Number xPosition, Number yPosition, AnimatorState animatorState)
void addAttributeDisplayerState (AttributeDisplayerState ADS)
void deleteAttributeDisplayerState (AttributeDisplayerState ADS)
List< AttributeDisplayerState > getDisplayerStates ()
double[] getBounds ()
void setBounds (double[] bounds)
double[] findGlobalBounds ()
double[] getVisionBounds ()
void setVisionBounds (double[] bounds)
Public Member Functions inherited from model.state.gameelement.GameElementState
GameElementState ()
String getName ()
void addType (String type)
List< String > getTypes ()
boolean isType (String typeString)
void deleteTypes (String typeString)
void addAction (ActionWrapper action)
Map< ActionType, List< ActionWrapper > > getActions ()
Public Member Functions inherited from util.JSONable
default String toJSON ()
Public Attributes
List< AttributeDisplayerState > myAttributeDisplayerStates
AnimatorState myAnimatorState
Public Attributes inherited from model.state.gameelement.GameElementState
AttributeContainer myAttributes
Set< String > myTypes
Private Attributes
double[] myVisionBounds
double[] myBounds
Static Private Attributes
static final long serialVersionUID = -2449775294910832264L
Additional Inherited Members
Protected Attributes inherited from model.state.gameelement.GameElementState
Map< ActionType, List< ActionWrapper > > myActions
Detailed Description
This GameElement is drawable but not necessarily selectable - examples include terrain. These elements must have a bounding box.
Author
Steve, Jonathan, Rahul, Zach, Michael D.
Definition at line 19 of file DrawableGameElementState.java.
Constructor & Destructor Documentation
model.state.gameelement.DrawableGameElementState.DrawableGameElementState (Number xPosition, Number yPosition, AnimatorState animatorState)
Create a drawable game element at a given x and y position.
Parameters
xPosition the x position of the element
yPosition the y position of the element
Definition at line 47 of file DrawableGameElementState.java.
References model.state.gameelement.GameElementState.myAttributes, model.state.gameelement.AttributeContainer.setNumericalAttribute(), model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
Member Function Documentation
void model.state.gameelement.DrawableGameElementState.addAttributeDisplayerState (AttributeDisplayerState ADS)
Adds AttributeDisplayStates to the list of displayerStates
Parameters
ADS An AttributeDisplayerState
Definition at line 68 of file DrawableGameElementState.java.
Referenced by model.GameElementStateFactory.createAttributeDisplayerState(), and application.RPG.hardCodeAGame().
void model.state.gameelement.DrawableGameElementState.deleteAttributeDisplayerState (AttributeDisplayerState ADS)
Removes a particular AttributeDisplayerState from the list of DisplayerStates
Parameters
ADS An AttributeDisplayerState
Definition at line 79 of file DrawableGameElementState.java.
double [] model.state.gameelement.DrawableGameElementState.findGlobalBounds ()
Take an object's bounds and add its x and y position to the bounds to get the global object bounds
Implements model.state.gameelement.traits.Boundable.
Definition at line 112 of file DrawableGameElementState.java.
References model.state.gameelement.AttributeContainer.getNumericalAttribute(), model.state.gameelement.GameElementState.myAttributes, model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
Referenced by engine.gameRepresentation.renderedRepresentation.DrawableGameElement.findGlobalBounds().
double [] model.state.gameelement.DrawableGameElementState.getBounds ()
Returns
the bounds of the bounded object
Implements model.state.gameelement.traits.Boundable.
Definition at line 93 of file DrawableGameElementState.java.
References model.state.gameelement.DrawableGameElementState.myBounds.
Referenced by engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getBounds().
List<AttributeDisplayerState> model.state.gameelement.DrawableGameElementState.getDisplayerStates ()
Definition at line 88 of file DrawableGameElementState.java.
References model.state.gameelement.DrawableGameElementState.myAttributeDisplayerStates.
Referenced by model.data.WizardDataFactory.createWizardData().
double [] model.state.gameelement.DrawableGameElementState.getVisionBounds ()
Gets the vision bounds of the sighted object
Implements model.state.gameelement.traits.Sighted.
Definition at line 130 of file DrawableGameElementState.java.
References model.state.gameelement.DrawableGameElementState.myVisionBounds.
void model.state.gameelement.DrawableGameElementState.setBounds (double[] bounds)
Set the bounds
Parameters
bounds the new bounds of the state set in a format that is usable by JavaFx's Polygon object
Definition at line 104 of file DrawableGameElementState.java.
Referenced by model.GameElementStateFactory.addVisuals(), application.Pong.createBoundary(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.RPG.createSpawnPoint(), and application.Pong.hardCodeAGame().
void model.state.gameelement.DrawableGameElementState.setVisionBounds (double[] bounds)
Sets the vision bounds of the sighted object
Parameters
bounds a double array of a polygon outline
Implements model.state.gameelement.traits.Sighted.
Definition at line 135 of file DrawableGameElementState.java.
Referenced by model.GameElementStateFactory.addVisuals().
Member Data Documentation
AnimatorState model.state.gameelement.DrawableGameElementState.myAnimatorState
Definition at line 35 of file DrawableGameElementState.java.
Referenced by model.GameElementStateFactory.addVisuals(), engine.elementFactories.AnimatorFactory.createAnimator(), application.Pong.createBall(), application.Pong.createBoundary(), model.MainModel.createDrawableGameElementState(), application.Pong.createGoalDisplayMarker(), application.Pong.createGoalRegion(), application.RPG.createMovingUnit(), application.Pong.createPaddle(), model.MainModel.createSelectableGameElementState(), application.RPG.createSpawnPoint(), and model.data.WizardDataFactory.createWizardData().
List<AttributeDisplayerState> model.state.gameelement.DrawableGameElementState.myAttributeDisplayerStates
This is a list of wrappers that contain information about widgets that have to be added to a particular game element. This DisplayerStates will be generated by the game editor and are utilized by a factory to create widgets
Definition at line 28 of file DrawableGameElementState.java.
Referenced by engine.elementFactories.VisualizerFactory.createVisualizer(), and model.state.gameelement.DrawableGameElementState.getDisplayerStates().
double [] model.state.gameelement.DrawableGameElementState.myBounds private
Definition at line 37 of file DrawableGameElementState.java.
Referenced by model.state.gameelement.DrawableGameElementState.getBounds().
double [] model.state.gameelement.DrawableGameElementState.myVisionBounds private
Definition at line 36 of file DrawableGameElementState.java.
Referenced by model.state.gameelement.DrawableGameElementState.getVisionBounds().
final long model.state.gameelement.DrawableGameElementState.serialVersionUID = -2449775294910832264L static private
Definition at line 33 of file DrawableGameElementState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/gameelement/DrawableGameElementState.java