voogasalad_TheException: model.sprite.SpriteImageGenerator Class Reference
model.sprite.SpriteImageGenerator Class Reference
Public Member Functions
SpriteImageGenerator () throws SaveLoadException
SpriteImageContainer fetchImageContainer (String imageTag)
Static Public Member Functions
static void loadSpriteImageContainers (Set< AnimatorState > animatorStates) throws SaveLoadException
static void loadSpriteImageContainer (AnimatorState state) throws SaveLoadException
Private Member Functions
void populateColorMaskMap (ResourceBundle bundle, String colorMaskDelimiter) throws SaveLoadException
Private Attributes
ColorMapGenerator myColorMapGenerator
String myColorMaskDelimiter = "-"
String myPropertiesLocation = "resources/gameelementresources/properties/"
String myColorMaskName = "colormasks.properties"
ResourceBundle myBundle
ResourceBundleRetriever myBundleRetriever
Static Private Attributes
static Map< String, SpriteImageContainer > myCachedContainer
Detailed Description
This class generates and caches sprite image containers that encapsulate a spritesheet and colormask represented in game elements.
Author
Rahul
Definition at line 20 of file SpriteImageGenerator.java.
Constructor & Destructor Documentation
model.sprite.SpriteImageGenerator.SpriteImageGenerator () throws SaveLoadException
Definition at line 29 of file SpriteImageGenerator.java.
References util.ResourceBundleRetriever.getBundle(), and model.sprite.SpriteImageGenerator.populateColorMaskMap().
Member Function Documentation
SpriteImageContainer model.sprite.SpriteImageGenerator.fetchImageContainer (String imageTag)
Get a sprite image container from an image tag specifying the location of the spritesheet.
Parameters
imageTag path to image
Returns
SpriteImageContainer wrapping the spritesheet and colormask
Definition at line 80 of file SpriteImageGenerator.java.
Referenced by model.MainModel.fetchImageContainer().
static void model.sprite.SpriteImageGenerator.loadSpriteImageContainer (AnimatorState state) throws SaveLoadException static
Creates a sprite image container from an animator state and caches the container.
Parameters
state animator state holding a spritesheet and colormask
Exceptions
SaveLoadException
Definition at line 65 of file SpriteImageGenerator.java.
Referenced by model.MainModel.createDrawableGameElementState(), model.MainModel.createSelectableGameElementState(), and model.sprite.SpriteImageGenerator.loadSpriteImageContainers().
static void model.sprite.SpriteImageGenerator.loadSpriteImageContainers (Set< AnimatorState > animatorStates) throws SaveLoadException static
Creates sprite image containers from the provided animator states
Parameters
animatorStates set of animator states holding a spritesheet and colormask
Exceptions
SaveLoadException
Definition at line 50 of file SpriteImageGenerator.java.
References model.sprite.SpriteImageGenerator.loadSpriteImageContainer().
Referenced by model.GameSaveLoadMediator.loadSpritesAndMasks().
void model.sprite.SpriteImageGenerator.populateColorMaskMap (ResourceBundle bundle, String colorMaskDelimiter) throws SaveLoadException private
Definition at line 37 of file SpriteImageGenerator.java.
References model.sprite.ColorMapGenerator.populateColorMaskMap().
Referenced by model.sprite.SpriteImageGenerator.SpriteImageGenerator().
Member Data Documentation
ResourceBundle model.sprite.SpriteImageGenerator.myBundle private
Definition at line 26 of file SpriteImageGenerator.java.
ResourceBundleRetriever model.sprite.SpriteImageGenerator.myBundleRetriever private
Definition at line 27 of file SpriteImageGenerator.java.
Map<String, SpriteImageContainer> model.sprite.SpriteImageGenerator.myCachedContainer static private
Definition at line 21 of file SpriteImageGenerator.java.
ColorMapGenerator model.sprite.SpriteImageGenerator.myColorMapGenerator private
Definition at line 22 of file SpriteImageGenerator.java.
String model.sprite.SpriteImageGenerator.myColorMaskDelimiter = "-" private
Definition at line 23 of file SpriteImageGenerator.java.
String model.sprite.SpriteImageGenerator.myColorMaskName = "colormasks.properties" private
Definition at line 25 of file SpriteImageGenerator.java.
String model.sprite.SpriteImageGenerator.myPropertiesLocation = "resources/gameelementresources/properties/" private
Definition at line 24 of file SpriteImageGenerator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/sprite/SpriteImageGenerator.java