voogasalad_TheException: gamemodel.GameElementStateFactory Class Reference
gamemodel.GameElementStateFactory Class Reference
Static Public Member Functions
static GameElementState createGameElementState (WizardData data)
static DrawableGameElementState createDrawableGameElementState (WizardData data, String imagePath)
static SelectableGameElementState createSelectableGameElementState (WizardData data)
static GameElementState createGoal (WizardData data)
Static Public Attributes
static final String GAME_ELEMENT = "GameElement"
static final String DRAWABLE_GAME_ELEMENT = "DrawableGameElement"
static final String NAME = "Name"
static final String STRING_ATTRIBUTE = "StringAttribute"
static final String NUMBER_ATTRIBUTE = "NumberAttribute"
static final String ATTRIBUTE = "Attribute"
static final String VALUE = "Value"
static final String TRIGGER = "Trigger"
static final String CONDITION = "Condition"
static final String ACTION = "Action"
static final String CAMPAIGN = "Campaign"
static final String LEVEL = "Level"
static final String IMAGE = "Image"
static final String WIDTH = "Width"
static final String HEIGHT = "Height"
static final String FRAME_X = "FrameX"
static final String FRAME_Y = "FrameY"
static final String ROWS = "Rows"
static final String START_FRAME = "StartFrame"
static final String STOP_FRAME = "StopFrame"
static final String ANIMATION_REPEAT = "AnimationRepeat"
Static Private Member Functions
static GameElementState addEssentials (GameElementState state, WizardData data)
Detailed Description
Factory that creates a SavableGameElementState based on the info args
Author
Nishad Agrawal, Jonathan Tseng
Definition at line 18 of file GameElementStateFactory.java.
Member Function Documentation
static GameElementState gamemodel.GameElementStateFactory.addEssentials (GameElementState state, WizardData data) static private
Definition at line 43 of file GameElementStateFactory.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.addAction(), editor.wizards.WizardData.getValueByKey(), editor.wizards.WizardData.getWizardDataByType(), game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setNumericalAttribute(), and game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setTextualAttribute().
Referenced by gamemodel.GameElementStateFactory.createDrawableGameElementState(), and gamemodel.GameElementStateFactory.createGameElementState().
static DrawableGameElementState gamemodel.GameElementStateFactory.createDrawableGameElementState (WizardData data, String imagePath) static
Definition at line 62 of file GameElementStateFactory.java.
References gamemodel.GameElementStateFactory.addEssentials(), editor.wizards.WizardData.getValueByKey(), game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setBounds(), and game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setSpritesheet().
Referenced by gamemodel.MainModel.createDrawableGameElement().
static GameElementState gamemodel.GameElementStateFactory.createGameElementState (WizardData data) static
Definition at line 58 of file GameElementStateFactory.java.
References gamemodel.GameElementStateFactory.addEssentials().
Referenced by gamemodel.MainModel.createGameElement().
static GameElementState gamemodel.GameElementStateFactory.createGoal (WizardData data) static
Definition at line 94 of file GameElementStateFactory.java.
References game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.addAction(), and editor.wizards.WizardData.getWizardDataByType().
Referenced by gamemodel.MainModel.addGoal().
static SelectableGameElementState gamemodel.GameElementStateFactory.createSelectableGameElementState (WizardData data) static
Definition at line 90 of file GameElementStateFactory.java.
Referenced by gamemodel.MainModel.createSelectableGameElement().
Member Data Documentation
final String gamemodel.GameElementStateFactory.ACTION = "Action" static
Definition at line 29 of file GameElementStateFactory.java.
Referenced by editor.wizards.TriggerWizard.updateData().
final String gamemodel.GameElementStateFactory.ANIMATION_REPEAT = "AnimationRepeat" static
Definition at line 41 of file GameElementStateFactory.java.
Referenced by editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.ATTRIBUTE = "Attribute" static
Definition at line 25 of file GameElementStateFactory.java.
Referenced by editor.wizards.StringAttributeWizard.updateData(), and editor.wizards.NumberAttributeWizard.updateData().
final String gamemodel.GameElementStateFactory.CAMPAIGN = "Campaign" static
Definition at line 30 of file GameElementStateFactory.java.
Referenced by editor.EditorMenuBarController.onNewLevelClick(), editor.wizards.CampaignWizard.updateData(), and editor.wizards.LevelWizard.updateData().
final String gamemodel.GameElementStateFactory.CONDITION = "Condition" static
Definition at line 28 of file GameElementStateFactory.java.
Referenced by editor.wizards.TriggerWizard.updateData().
final String gamemodel.GameElementStateFactory.DRAWABLE_GAME_ELEMENT = "DrawableGameElement" static
Definition at line 21 of file GameElementStateFactory.java.
Referenced by editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.FRAME_X = "FrameX" static
Definition at line 36 of file GameElementStateFactory.java.
Referenced by editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.FRAME_Y = "FrameY" static
Definition at line 37 of file GameElementStateFactory.java.
Referenced by editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.GAME_ELEMENT = "GameElement" static
Definition at line 20 of file GameElementStateFactory.java.
Referenced by editor.wizards.GameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.HEIGHT = "Height" static
Definition at line 35 of file GameElementStateFactory.java.
Referenced by editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.IMAGE = "Image" static
Definition at line 32 of file GameElementStateFactory.java.
Referenced by gamemodel.MainModel.createDrawableGameElement(), and editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.LEVEL = "Level" static
Definition at line 31 of file GameElementStateFactory.java.
Referenced by editor.wizards.LevelWizard.updateData().
final String gamemodel.GameElementStateFactory.NAME = "Name" static
Definition at line 22 of file GameElementStateFactory.java.
Referenced by gamemodel.MainModel.createDrawableGameElement(), editor.EditorMenuBarController.onNewCampaignClick(), editor.EditorMenuBarController.onNewLevelClick(), editor.wizards.CampaignWizard.updateData(), editor.wizards.LevelWizard.updateData(), editor.wizards.GameElementWizard.updateData(), and editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.NUMBER_ATTRIBUTE = "NumberAttribute" static
Definition at line 24 of file GameElementStateFactory.java.
Referenced by editor.wizards.NumberAttributeWizard.updateData().
final String gamemodel.GameElementStateFactory.ROWS = "Rows" static
Definition at line 38 of file GameElementStateFactory.java.
Referenced by editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.START_FRAME = "StartFrame" static
Definition at line 39 of file GameElementStateFactory.java.
Referenced by editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.STOP_FRAME = "StopFrame" static
Definition at line 40 of file GameElementStateFactory.java.
Referenced by editor.wizards.DrawableGameElementWizard.updateData().
final String gamemodel.GameElementStateFactory.STRING_ATTRIBUTE = "StringAttribute" static
Definition at line 23 of file GameElementStateFactory.java.
Referenced by editor.wizards.StringAttributeWizard.updateData().
final String gamemodel.GameElementStateFactory.TRIGGER = "Trigger" static
Definition at line 27 of file GameElementStateFactory.java.
Referenced by editor.wizards.TriggerWizard.updateData().
final String gamemodel.GameElementStateFactory.VALUE = "Value" static
Definition at line 26 of file GameElementStateFactory.java.
Referenced by editor.wizards.StringAttributeWizard.updateData(), and editor.wizards.NumberAttributeWizard.updateData().
final String gamemodel.GameElementStateFactory.WIDTH = "Width" static
Definition at line 34 of file GameElementStateFactory.java.
Referenced by editor.wizards.DrawableGameElementWizard.updateData().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/gamemodel/GameElementStateFactory.java