voogasalad_TheException: engine.gameRepresentation.evaluatables.actions.Action Class Reference
engine.gameRepresentation.evaluatables.actions.Action Class Reference abstract
Public Member Functions
Action (EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager, String[] args)
Boolean evaluate (ElementPair elements)
Public Member Functions inherited from engine.gameRepresentation.evaluatables.Evaluatable< T >
Evaluatable (Class< T > type)
abstract T evaluate (ElementPair elements)
boolean setValue (ElementPair elements, T value)
boolean setValue (T value)
Class< T > getType ()
Static Public Attributes
static final String MY_ELEMENT = "me"
static final String MY_PARTICIPANT = "my"
Protected Member Functions
abstract Evaluatable<?> initializeAction (String[] args, EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager) throws ClassNotFoundException, EvaluatorCreationException
abstract Boolean evaluate (Evaluatable<?> action, ElementPair elements)
ObjectOfInterestIdentifier makeObjectIdentifier (String objectIdentifierString)
List< Participant > identifyParticipantsOfInterest (String participantIdentifier, ParticipantManager manager)
boolean executeActionIfTimerExpired (GameElement element, String timerName, long timerReloadTime, ElementPair elements, Consumer< ElementPair > action)
Static Protected Attributes
static final GameElementParameter ACTOR
static final GameElementParameter ACTEE
Private Attributes
Evaluatable<?> myAction
Detailed Description
The wrapper for an action class. Actions are a layer of abstraction that was added on top of evaluators in order to make more strict type casting of parameters with evaluators. The action hierarchy arose from a time constraint on evaluatable parsing from strings. Essentially, actions represent commands with inputable commands for functionality.
See also
ActionOptions This allows for specifying complex actions using only string pieces as opposed to necessitating the user to type in long VScript strings for actions.
Author
Zach
Definition at line 32 of file Action.java.
Constructor & Destructor Documentation
engine.gameRepresentation.evaluatables.actions.Action.Action (EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager, String[] args)
Create an action
Parameters
id the type id of the action tree. Allows leaves to reference the tree as a whole
factory the factory for evaluators
args any arguments that dictate the makeup of the Action. These are specified through the ActionTypes.java file
Definition at line 45 of file Action.java.
References engine.gameRepresentation.evaluatables.actions.Action.initializeAction().
Member Function Documentation
Boolean engine.gameRepresentation.evaluatables.actions.Action.evaluate (ElementPair elements)
Definition at line 73 of file Action.java.
abstract Boolean engine.gameRepresentation.evaluatables.actions.Action.evaluate (Evaluatable<?> action, ElementPair elements) abstract protected
Check any necessary conditions and evaluate the action's internal action
Parameters
action the internal fundamental action of the action
elements any elements that may be acted upon
Returns
a boolean indicating whether action execution was successful
boolean engine.gameRepresentation.evaluatables.actions.Action.executeActionIfTimerExpired (GameElement element, String timerName, long timerReloadTime, ElementPair elements, Consumer< ElementPair > action) protected
Execute a given action if a timer has expired
Parameters
element the element containing the timer
timerName the name of the timer
timerReloadTime the amount of time until the timer can execute again
elements a grouping of important elements for the action to execute on
action the action to execute
Returns
a boolean indicating if he action was executed
Definition at line 137 of file Action.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.getTimer(), and engine.gameRepresentation.renderedRepresentation.GameElement.setTimer().
Referenced by engine.gameRepresentation.evaluatables.actions.CheckAttributeCreateObjectAction.evaluate().
List<Participant> engine.gameRepresentation.evaluatables.actions.Action.identifyParticipantsOfInterest (String participantIdentifier, ParticipantManager manager) protected
Identify participants given an identifier string
Parameters
participantIdentifier the string to identify the participants
manager the participant manager
Returns
the participants of interest
Definition at line 108 of file Action.java.
References engine.UI.ParticipantManager.getAI(), and engine.UI.ParticipantManager.getUser().
Referenced by engine.gameRepresentation.evaluatables.actions.PlayerStatsCheckAction.initializeAction(), engine.gameRepresentation.evaluatables.actions.PlayerAttributeInteractionAction.initializeAction(), engine.gameRepresentation.evaluatables.actions.ObjectTypeCheckAction.initializeAction(), and engine.gameRepresentation.evaluatables.actions.MotherOfAllActions.initializeAction().
abstract Evaluatable<?> engine.gameRepresentation.evaluatables.actions.Action.initializeAction (String[] args, EvaluatorFactory factory, GameElementManager elementManager, ParticipantManager participantManager) throws ClassNotFoundException, EvaluatorCreationException abstract protected
Initialize the action's action evaluatable for execution given the factory and the arguments of the action.
Returns
the evaluatable for the action
Referenced by engine.gameRepresentation.evaluatables.actions.Action.Action().
ObjectOfInterestIdentifier engine.gameRepresentation.evaluatables.actions.Action.makeObjectIdentifier (String objectIdentifierString) protected
Below are some helper methods to keep actions DRY Get an object of interest identifier based on a string
Parameters
objectIdentifierString the string for the object of interest.
Returns
the object of interest identifier
Definition at line 96 of file Action.java.
Referenced by engine.gameRepresentation.evaluatables.actions.CheckAttributeSetAttributeAction.initializeAction(), engine.gameRepresentation.evaluatables.actions.ObjectTypeCheckAction.initializeAction(), and engine.gameRepresentation.evaluatables.actions.MotherOfAllActions.initializeAction().
Member Data Documentation
final GameElementParameter engine.gameRepresentation.evaluatables.actions.Action.ACTEE static protected
Initial value:
=
            new GameElementParameter(new ActeeObjectIdentifier())
Definition at line 124 of file Action.java.
Referenced by engine.gameRepresentation.evaluatables.actions.ActOnObjectsAction.initializeAction(), and engine.gameRepresentation.evaluatables.actions.ObjectConditionAction.initializeAction().
final GameElementParameter engine.gameRepresentation.evaluatables.actions.Action.ACTOR static protected
Initial value:
=
            new GameElementParameter(new ActorObjectIdentifier())
Definition at line 122 of file Action.java.
Referenced by engine.gameRepresentation.evaluatables.actions.ActOnObjectsAction.initializeAction(), and engine.gameRepresentation.evaluatables.actions.ObjectConditionAction.initializeAction().
final String engine.gameRepresentation.evaluatables.actions.Action.MY_ELEMENT = "me" static
Definition at line 34 of file Action.java.
final String engine.gameRepresentation.evaluatables.actions.Action.MY_PARTICIPANT = "my" static
Definition at line 35 of file Action.java.
Evaluatable<?> engine.gameRepresentation.evaluatables.actions.Action.myAction private
Definition at line 33 of file Action.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/evaluatables/actions/Action.java