voogasalad_TheException: util.LoadSaveUtility Class Reference
util.LoadSaveUtility Class Reference
Public Member Functions
void save (JSONable object, String filePath) throws IOException
String saveImage (Image image, String filePath) throws IOException
Image loadImage (String filePath) throws IOException
Public Attributes
String myDefaultLocation
Static Public Attributes
static String FILE_SEPARATOR = File.separator
Package Functions
public< T > T loadResource (Class className, String filePath)
Private Member Functions
File obtainFile (String filePath) throws IOException
Static Private Attributes
static final String BAD_FILE_PATH = "Bad File Path"
Detailed Description
Utility class that handles the loading/saving of files.
Author
Rahul
Definition at line 24 of file LoadSaveUtility.java.
Member Function Documentation
Image util.LoadSaveUtility.loadImage (String filePath) throws IOException
Load an image at given file path
Parameters
filePath of image
Returns
Image object loaded if exists
Exceptions
IOException
Implements util.ILoadSave.
Definition at line 72 of file LoadSaveUtility.java.
public<T> T util.LoadSaveUtility.loadResource (Class className, String filePath) package
Load a resource from a given file and return Java object representation
Parameters
className Java class object that is being loaded
filePath that resource to be loaded from
Returns
Java class object
Implements util.ILoadSave.
Definition at line 30 of file LoadSaveUtility.java.
File util.LoadSaveUtility.obtainFile (String filePath) throws IOException private
Definition at line 52 of file LoadSaveUtility.java.
Referenced by util.LoadSaveUtility.save(), and util.LoadSaveUtility.saveImage().
void util.LoadSaveUtility.save (JSONable object, String filePath) throws IOException
Save a JSONable object to a library file
Parameters
object that can be converted to JSON format
filePath to which object should be saved
Exceptions
IOException in case of trouble reading
Implements util.ILoadSave.
Definition at line 44 of file LoadSaveUtility.java.
References util.LoadSaveUtility.obtainFile().
String util.LoadSaveUtility.saveImage (Image image, String filePath) throws IOException
Save an image from a particular file path
Parameters
image
filePath at which image is located
Returns
filePath where the image is saved to
Exceptions
IOException
Implements util.ILoadSave.
Definition at line 61 of file LoadSaveUtility.java.
References util.LoadSaveUtility.obtainFile().
Member Data Documentation
final String util.LoadSaveUtility.BAD_FILE_PATH = "Bad File Path" static private
Definition at line 25 of file LoadSaveUtility.java.
String util.LoadSaveUtility.FILE_SEPARATOR = File.separator static
Definition at line 26 of file LoadSaveUtility.java.
String util.LoadSaveUtility.myDefaultLocation
Initial value:
= "resources" + LoadSaveUtility.FILE_SEPARATOR + "img"
                                      + LoadSaveUtility.FILE_SEPARATOR
Definition at line 27 of file LoadSaveUtility.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/util/LoadSaveUtility.java