voogasalad_TheException: test.conditions.ConditionFunctionalityTest Class Reference
test.conditions.ConditionFunctionalityTest Class Reference
Public Member Functions
void initialize ()
void testGenericTypeIdentification ()
void testAttributeIncrimenting ()
void testValueAssignment ()
void testCollisions ()
void testRemoveAction ()
void testAddAction ()
Private Member Functions
int countIteratorElements (Iterator<?> iterator)
Private Attributes
DrawableGameElement myElement1
DrawableGameElement myElement2
NumericAttributeParameter myNumAttrParam
NumberParameter myNumberParam
GameElementParameter myElementParam1
GameElementParameter myElementParam2
ElementPair myElementPair
Detailed Description
A class used to test the construction and functionality of conditions and actions
Author
Zach, Steve
Definition at line 43 of file ConditionFunctionalityTest.java.
Member Function Documentation
int test.conditions.ConditionFunctionalityTest.countIteratorElements (Iterator<?> iterator) private
Count the number of elements in a given iterator
Definition at line 202 of file ConditionFunctionalityTest.java.
Referenced by test.conditions.ConditionFunctionalityTest.testAddAction(), and test.conditions.ConditionFunctionalityTest.testRemoveAction().
void test.conditions.ConditionFunctionalityTest.initialize ()
Create some test game elements for us to work with in the test
Definition at line 56 of file ConditionFunctionalityTest.java.
References game_engine.elementFactories.GameElementFactory.createDrawableGameElement(), game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setBounds(), game_engine.gameRepresentation.stateRepresentation.gameElement.GameElementState.setNumericalAttribute(), and game_engine.gameRepresentation.stateRepresentation.gameElement.DrawableGameElementState.setSpritesheet().
void test.conditions.ConditionFunctionalityTest.testAddAction ()
Test the addition of an action to an object then the removal of that action
Definition at line 178 of file ConditionFunctionalityTest.java.
References test.conditions.ConditionFunctionalityTest.countIteratorElements(), game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate(), game_engine.gameRepresentation.renderedRepresentation.GameElement.getActionsOfType(), and test.conditions.ConditionFunctionalityTest.myElementParam1.
void test.conditions.ConditionFunctionalityTest.testAttributeIncrimenting ()
Test basic actions that set an attribute value in the evaluatable
Definition at line 104 of file ConditionFunctionalityTest.java.
References game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate(), test.conditions.ConditionFunctionalityTest.myNumAttrParam, and test.conditions.ConditionFunctionalityTest.myNumberParam.
void test.conditions.ConditionFunctionalityTest.testCollisions ()
Definition at line 132 of file ConditionFunctionalityTest.java.
References game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate(), test.conditions.ConditionFunctionalityTest.myElementParam1, test.conditions.ConditionFunctionalityTest.myElementParam2, game_engine.gameRepresentation.renderedRepresentation.GameElement.setNumericalAttribute(), game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.X_POS_STRING, and game_engine.gameRepresentation.stateRepresentation.gameElement.StateTags.Y_POS_STRING.
void test.conditions.ConditionFunctionalityTest.testGenericTypeIdentification ()
Test the ability to make an evaluatable based on the types of its parameter. Test the workaround of generic's inability to identify type.
Definition at line 90 of file ConditionFunctionalityTest.java.
void test.conditions.ConditionFunctionalityTest.testRemoveAction ()
Test the addition of an action to an element then a removal of said element
Definition at line 151 of file ConditionFunctionalityTest.java.
References game_engine.gameRepresentation.renderedRepresentation.GameElement.addAction(), test.conditions.ConditionFunctionalityTest.countIteratorElements(), game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate(), game_engine.gameRepresentation.renderedRepresentation.GameElement.getActionsOfType(), and test.conditions.ConditionFunctionalityTest.myElementParam1.
void test.conditions.ConditionFunctionalityTest.testValueAssignment ()
Definition at line 122 of file ConditionFunctionalityTest.java.
References game_engine.gameRepresentation.evaluatables.parameters.NumberParameter.evaluate(), game_engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, T >.evaluate(), game_engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), test.conditions.ConditionFunctionalityTest.myNumAttrParam, and test.conditions.ConditionFunctionalityTest.myNumberParam.
Member Data Documentation
DrawableGameElement test.conditions.ConditionFunctionalityTest.myElement1 private
Definition at line 44 of file ConditionFunctionalityTest.java.
DrawableGameElement test.conditions.ConditionFunctionalityTest.myElement2 private
Definition at line 45 of file ConditionFunctionalityTest.java.
ElementPair test.conditions.ConditionFunctionalityTest.myElementPair private
Definition at line 50 of file ConditionFunctionalityTest.java.
GameElementParameter test.conditions.ConditionFunctionalityTest.myElementParam1 private
Definition at line 48 of file ConditionFunctionalityTest.java.
Referenced by test.conditions.ConditionFunctionalityTest.testAddAction(), test.conditions.ConditionFunctionalityTest.testCollisions(), and test.conditions.ConditionFunctionalityTest.testRemoveAction().
GameElementParameter test.conditions.ConditionFunctionalityTest.myElementParam2 private
Definition at line 49 of file ConditionFunctionalityTest.java.
Referenced by test.conditions.ConditionFunctionalityTest.testCollisions().
NumericAttributeParameter test.conditions.ConditionFunctionalityTest.myNumAttrParam private
Definition at line 46 of file ConditionFunctionalityTest.java.
Referenced by test.conditions.ConditionFunctionalityTest.testAttributeIncrimenting(), and test.conditions.ConditionFunctionalityTest.testValueAssignment().
NumberParameter test.conditions.ConditionFunctionalityTest.myNumberParam private
Definition at line 47 of file ConditionFunctionalityTest.java.
Referenced by test.conditions.ConditionFunctionalityTest.testAttributeIncrimenting(), and test.conditions.ConditionFunctionalityTest.testValueAssignment().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/test/conditions/ConditionFunctionalityTest.java