voogasalad_TheException: view.ViewScreen Enum Reference
view.ViewScreen Enum Reference
Public Member Functions
String getFilePath ()
Public Attributes
SPLASH =("/view/guipanes/SplashPage.fxml")
EDITOR =("/editor/guipanes/EditorRoot.fxml")
RUNNER =("")
Private Member Functions
ViewScreen (String filePath)
Private Attributes
String myFilePath
Detailed Description
Class for enumerated types of screens that can be opened
Author
Jonathan Tseng, Rahul
Definition at line 9 of file ViewScreen.java.
Constructor & Destructor Documentation
view.ViewScreen.ViewScreen (String filePath) private
Definition at line 17 of file ViewScreen.java.
Member Function Documentation
String view.ViewScreen.getFilePath ()
Definition at line 21 of file ViewScreen.java.
Referenced by view.MainView.launchScreen().
Member Data Documentation
view.ViewScreen.EDITOR =("/editor/guipanes/EditorRoot.fxml")
Definition at line 12 of file ViewScreen.java.
Referenced by view.SplashScreen.setUpButtons().
String view.ViewScreen.myFilePath private
Definition at line 15 of file ViewScreen.java.
view.ViewScreen.RUNNER =("")
Definition at line 13 of file ViewScreen.java.
view.ViewScreen.SPLASH =("/view/guipanes/SplashPage.fxml")
Definition at line 11 of file ViewScreen.java.
Referenced by view.MainView.MainView().
The documentation for this enum was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/ViewScreen.java