voogasalad_TheException: engine.visuals.elementVisuals.animations.AnimatorState Class Reference
engine.visuals.elementVisuals.animations.AnimatorState Class Reference
Public Member Functions
AnimatorState (String imageTag, String colorMaskTag, Dimension frameDimensions, int numRows, Set< AnimationSequence > animationSequenceList)
void addAnimationSequence (AnimationSequence seq)
AnimationSequence getAnimationSequence (List< AnimationTag > tags)
Set< AnimationSequence > getAllAnimationSequences ()
boolean containsAnimationSequence (AnimationSequence seq)
String getImageTag ()
String getColorMaskTag ()
Dimension getViewportSize ()
int getNumRows ()
Public Member Functions inherited from util.JSONable
default String toJSON ()
Private Attributes
String imageTag
String colorMaskTag
Dimension viewportSize
int numRows
Set< AnimationSequence > animationSequences
Static Private Attributes
static final long serialVersionUID = 1609072629703433749L
Detailed Description
A data wrapper object used to group the pertinent information for a spritesheet. Internal data is intentionally made public as this is just a data wrapper to simplify the passing of data
Author
Rahul, Zach, Steve
Definition at line 21 of file AnimatorState.java.
Constructor & Destructor Documentation
engine.visuals.elementVisuals.animations.AnimatorState.AnimatorState (String imageTag, String colorMaskTag, Dimension frameDimensions, int numRows, Set< AnimationSequence > animationSequenceList)
Create the Spritesheet
Parameters
imageTag the tag for the image that will be sent to the save/load utility to get the image
frameDimensions the dimensions of a frame of the spritesheet
numRows the number of columns across in the spritesheet
Definition at line 44 of file AnimatorState.java.
References engine.visuals.elementVisuals.animations.AnimatorState.colorMaskTag, engine.visuals.elementVisuals.animations.AnimatorState.imageTag, and engine.visuals.elementVisuals.animations.AnimatorState.numRows.
Member Function Documentation
void engine.visuals.elementVisuals.animations.AnimatorState.addAnimationSequence (AnimationSequence seq)
Definition at line 57 of file AnimatorState.java.
boolean engine.visuals.elementVisuals.animations.AnimatorState.containsAnimationSequence (AnimationSequence seq)
Definition at line 71 of file AnimatorState.java.
Set<AnimationSequence> engine.visuals.elementVisuals.animations.AnimatorState.getAllAnimationSequences ()
Definition at line 67 of file AnimatorState.java.
Referenced by model.data.WizardDataFactory.createWizardData().
AnimationSequence engine.visuals.elementVisuals.animations.AnimatorState.getAnimationSequence (List< AnimationTag > tags)
Definition at line 61 of file AnimatorState.java.
Referenced by engine.visuals.elementVisuals.animations.Animator.determineCorrectAnimation().
String engine.visuals.elementVisuals.animations.AnimatorState.getColorMaskTag ()
Definition at line 79 of file AnimatorState.java.
References engine.visuals.elementVisuals.animations.AnimatorState.colorMaskTag.
Referenced by model.data.WizardDataFactory.createWizardData().
String engine.visuals.elementVisuals.animations.AnimatorState.getImageTag ()
Definition at line 75 of file AnimatorState.java.
References engine.visuals.elementVisuals.animations.AnimatorState.imageTag.
Referenced by engine.visuals.elementVisuals.animations.Animator.Animator(), engine.elementFactories.AnimatorFactory.createAnimator(), and model.data.WizardDataFactory.createWizardData().
int engine.visuals.elementVisuals.animations.AnimatorState.getNumRows ()
Definition at line 87 of file AnimatorState.java.
References engine.visuals.elementVisuals.animations.AnimatorState.numRows.
Referenced by engine.visuals.elementVisuals.animations.Animator.getViewport().
Dimension engine.visuals.elementVisuals.animations.AnimatorState.getViewportSize ()
Definition at line 83 of file AnimatorState.java.
References engine.visuals.elementVisuals.animations.AnimatorState.viewportSize.
Referenced by model.data.WizardDataFactory.createWizardData(), engine.visuals.elementVisuals.animations.Animator.getViewport(), and engine.visuals.elementVisuals.animations.Animator.getViewportSize().
Member Data Documentation
Set<AnimationSequence> engine.visuals.elementVisuals.animations.AnimatorState.animationSequences private
Definition at line 31 of file AnimatorState.java.
String engine.visuals.elementVisuals.animations.AnimatorState.colorMaskTag private
Definition at line 28 of file AnimatorState.java.
Referenced by engine.visuals.elementVisuals.animations.AnimatorState.AnimatorState(), and engine.visuals.elementVisuals.animations.AnimatorState.getColorMaskTag().
String engine.visuals.elementVisuals.animations.AnimatorState.imageTag private
Definition at line 27 of file AnimatorState.java.
Referenced by engine.visuals.elementVisuals.animations.AnimatorState.AnimatorState(), and engine.visuals.elementVisuals.animations.AnimatorState.getImageTag().
int engine.visuals.elementVisuals.animations.AnimatorState.numRows private
Definition at line 30 of file AnimatorState.java.
Referenced by engine.visuals.elementVisuals.animations.AnimatorState.AnimatorState(), and engine.visuals.elementVisuals.animations.AnimatorState.getNumRows().
final long engine.visuals.elementVisuals.animations.AnimatorState.serialVersionUID = 1609072629703433749L static private
Definition at line 26 of file AnimatorState.java.
Dimension engine.visuals.elementVisuals.animations.AnimatorState.viewportSize private
Definition at line 29 of file AnimatorState.java.
Referenced by engine.visuals.elementVisuals.animations.AnimatorState.getViewportSize().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/elementVisuals/animations/AnimatorState.java