voogasalad_TheException: engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState Class Reference
engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState Class Reference
Public Member Functions
AttributeDisplayerState (AttributeDisplayerTags displayerTag, String numericParameterTag, double minAttributeValue, double maxAttributeValue)
AttributeDisplayerState (AttributeDisplayerTags displayerTag, String textualParameterTag, String value)
AttributeDisplayerTags getDisplayerTag ()
String getParameterTag ()
double getMinValue ()
double getMaxValue ()
String getTextValue ()
Public Member Functions inherited from util.JSONable
default String toJSON ()
Private Attributes
AttributeDisplayerTags displayerTag
String parameterTag
double minAttributeValue
double maxAttributeValue
String myTextValue
Static Private Attributes
static final long serialVersionUID = -4791954709522087485L
Detailed Description
A wrapper for all the savable information needed to represent an attribute displayer. This is just a data wrapper and as such all of its instance variables are public.
Author
Zach, Michael D., Stanley
Definition at line 14 of file AttributeDisplayerState.java.
Constructor & Destructor Documentation
engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.AttributeDisplayerState (AttributeDisplayerTags displayerTag, String numericParameterTag, double minAttributeValue, double maxAttributeValue)
Constructor
Parameters
displayerTag The reference to a widget's class
numericParameterTag The attribute name
minAttributeValue The max attribute value
maxAttributeValue The min attribute value
BackgroundColor The color in the background
ForegroundColor The color in the foreground
Definition at line 39 of file AttributeDisplayerState.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.displayerTag, engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.maxAttributeValue, and engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.minAttributeValue.
engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.AttributeDisplayerState (AttributeDisplayerTags displayerTag, String textualParameterTag, String value)
Definition at line 48 of file AttributeDisplayerState.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.displayerTag.
Member Function Documentation
AttributeDisplayerTags engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getDisplayerTag ()
Definition at line 55 of file AttributeDisplayerState.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.displayerTag.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createAttributeDisplayer().
double engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getMaxValue ()
Definition at line 67 of file AttributeDisplayerState.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.maxAttributeValue.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createNumericalAttributeDisplayer().
double engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getMinValue ()
Definition at line 63 of file AttributeDisplayerState.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.minAttributeValue.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createNumericalAttributeDisplayer().
String engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getParameterTag ()
Definition at line 59 of file AttributeDisplayerState.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.parameterTag.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createNumericalAttributeDisplayer(), and engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createTextualAttributeDisplayer().
String engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getTextValue ()
Definition at line 71 of file AttributeDisplayerState.java.
References engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.myTextValue.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createAttributeDisplayer(), and engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerFactory.createTextualAttributeDisplayer().
Member Data Documentation
AttributeDisplayerTags engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.displayerTag private
Definition at line 17 of file AttributeDisplayerState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.AttributeDisplayerState(), and engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getDisplayerTag().
double engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.maxAttributeValue private
Definition at line 20 of file AttributeDisplayerState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.AttributeDisplayerState(), and engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getMaxValue().
double engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.minAttributeValue private
Definition at line 19 of file AttributeDisplayerState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.AttributeDisplayerState(), and engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getMinValue().
String engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.myTextValue private
Definition at line 21 of file AttributeDisplayerState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getTextValue().
String engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.parameterTag private
Definition at line 18 of file AttributeDisplayerState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.getParameterTag().
final long engine.gameRepresentation.renderedRepresentation.attributeDisplayer.AttributeDisplayerState.serialVersionUID = -4791954709522087485L static private
Definition at line 16 of file AttributeDisplayerState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/renderedRepresentation/attributeDisplayer/AttributeDisplayerState.java