voogasalad_TheException: engine.gameRepresentation.evaluatables.Evaluatable< T > Class Template Reference
engine.gameRepresentation.evaluatables.Evaluatable< T > Class Template Reference abstract
Public Member Functions
Evaluatable (Class< T > type)
abstract T evaluate (ElementPair elements)
boolean setValue (ElementPair elements, T value)
boolean setValue (T value)
Class< T > getType ()
Private Attributes
Class< T > myType
Detailed Description
An object that can evaluate a condition on an element to return a value. Evaluators are generics to allow for the implementation of complex logic with evaluatables. Evaluatables have the option to both get and set values although the value setting is not by default implemented by children of evaluatables. The intent of this interface is to be used in the composite pattern to build large dynamic logic to allow for interaction between game elements and components.
Author
Zach
Definition at line 14 of file Evaluatable.java.
Constructor & Destructor Documentation
engine.gameRepresentation.evaluatables.Evaluatable< T >.Evaluatable (Class< T > type)
Create an evaluatable
Parameters
type the type of the class T of the evaluatable. Used as a workaround for the poor implementation of generics by Java
Definition at line 24 of file Evaluatable.java.
Member Function Documentation
abstract T engine.gameRepresentation.evaluatables.Evaluatable< T >.evaluate (ElementPair elements) abstract
Take in a pair of elements, evaluate a condition on the elements, and return a boolean representing the condition's return value.
Referenced by engine.gameRepresentation.evaluatables.evaluators.IfThen< A, B >.evaluate(), engine.gameRepresentation.evaluatables.actions.ActOnObjectsAction.evaluate(), engine.gameRepresentation.evaluatables.actions.ObjectConditionAction.evaluate(), engine.gameRepresentation.evaluatables.actions.PerformAttrCalculationAction.evaluate(), engine.gameRepresentation.evaluatables.actions.PlayerStatsCheckAction.evaluate(), engine.gameRepresentation.evaluatables.actions.PlayerAttributeInteractionAction.evaluate(), engine.gameRepresentation.evaluatables.actions.CheckAttributeSetAttributeAction.evaluate(), engine.gameRepresentation.evaluatables.actions.ObjectLocationCheckAction.evaluate(), engine.gameRepresentation.evaluatables.actions.ObjectTypeCheckAction.evaluate(), engine.gameRepresentation.evaluatables.actions.CheckAttributeCreateObjectAction.evaluate(), engine.gameRepresentation.evaluatables.actions.DecrementIncrementAttributeAction.evaluate(), engine.gameRepresentation.evaluatables.actions.MotherOfAllActions.evaluate(), and engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.evaluate().
Class<T> engine.gameRepresentation.evaluatables.Evaluatable< T >.getType ()
Get the type of the object as a way of bypassing Java type erasure
Returns
the generic's type
Definition at line 58 of file Evaluatable.java.
Referenced by engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.delegateEvaluator(), engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.setParameter1Value(), and engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.setParameter2Value().
boolean engine.gameRepresentation.evaluatables.Evaluatable< T >.setValue (ElementPair elements, T value)
Sets the evaluatable's value to a given value
Parameters
value the value to set the evaluatable's stored computation value to
Returns
a boolean indicating whether setting was successful
Definition at line 42 of file Evaluatable.java.
Referenced by engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.setParameter1Value(), engine.gameRepresentation.evaluatables.evaluators.Evaluator< A, B, Number >.setParameter2Value(), and engine.gameRepresentation.evaluatables.Evaluatable< Number >.setValue().
boolean engine.gameRepresentation.evaluatables.Evaluatable< T >.setValue (T value)
Use the null pattern to set a value if no element pair is applicable
Definition at line 49 of file Evaluatable.java.
Member Data Documentation
Class<T> engine.gameRepresentation.evaluatables.Evaluatable< T >.myType private
Definition at line 15 of file Evaluatable.java.
Referenced by engine.gameRepresentation.evaluatables.Evaluatable< Number >.getType().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/evaluatables/Evaluatable.java