voogasalad_TheException: game_engine.gameRepresentation.conditions.operators.Operator Class Reference
game_engine.gameRepresentation.conditions.operators.Operator Class Reference abstract
Public Member Functions
Operator (Evaluatable firstCondition, Evaluatable secondCondition, String operatorString)
boolean evaluate (ElementPair elements)
String toString ()
Protected Member Functions
abstract boolean applyOperator (boolean boolean1, boolean boolean2)
Private Attributes
Evaluatable myFirstCondition
Evaluatable mySecondCondition
String myOperatorString
Detailed Description
An abstract class that performs a boolean operation on two evaluatable objects. e.g. &&, ||, ! and returns the resulting boolean
Author
Zach
Definition at line 14 of file Operator.java.
Constructor & Destructor Documentation
game_engine.gameRepresentation.conditions.operators.Operator.Operator (Evaluatable firstCondition, Evaluatable secondCondition, String operatorString)
Initialize the operator with the necessary conditions
Parameters
firstCondition the leftmost condition for the operator to act on
secondCondition the rightmost condition for the operator to act on
operatorString the string representation for the operator
Definition at line 27 of file Operator.java.
Member Function Documentation
abstract boolean game_engine.gameRepresentation.conditions.operators.Operator.applyOperator (boolean boolean1, boolean boolean2) abstract protected
Apply the operator's function on two booleans
Parameters
boolean1 the first boolean
boolean2 the second boolean
Returns
the result of the operator being applied
Referenced by game_engine.gameRepresentation.conditions.operators.Operator.evaluate().
boolean game_engine.gameRepresentation.conditions.operators.Operator.evaluate (ElementPair elements)
Take in a pair of elements, evaluate a condition on the elements, and return a boolean representing the condition's return value.
Implements game_engine.gameRepresentation.conditions.Evaluatable.
Definition at line 34 of file Operator.java.
References game_engine.gameRepresentation.conditions.operators.Operator.applyOperator(), and game_engine.gameRepresentation.conditions.Evaluatable.evaluate().
String game_engine.gameRepresentation.conditions.operators.Operator.toString ()
Definition at line 49 of file Operator.java.
References game_engine.gameRepresentation.conditions.operators.Operator.myOperatorString.
Member Data Documentation
Evaluatable game_engine.gameRepresentation.conditions.operators.Operator.myFirstCondition private
Definition at line 16 of file Operator.java.
String game_engine.gameRepresentation.conditions.operators.Operator.myOperatorString private
Definition at line 18 of file Operator.java.
Referenced by game_engine.gameRepresentation.conditions.operators.Operator.toString().
Evaluatable game_engine.gameRepresentation.conditions.operators.Operator.mySecondCondition private
Definition at line 17 of file Operator.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/gameRepresentation/conditions/operators/Operator.java