voogasalad_TheException: game_engine.UI.MouseManager Class Reference
game_engine.UI.MouseManager Class Reference
Public Member Functions
void clicked (MouseEvent event, double xMap, double yMap)
Point2D getMapLoc ()
MouseEvent getLastClick ()
Package Attributes
double yLoc
Private Attributes
MouseEvent lastEvent
double xLoc
Detailed Description
The class for managing the clicks the user makes. Takes in click information and allows observers to get that information.
Author
John
Definition at line 15 of file MouseManager.java.
Member Function Documentation
void game_engine.UI.MouseManager.clicked (MouseEvent event, double xMap, double yMap)
Update the click manager based on a new mouse event
Parameters
event
xMap
yMap
Definition at line 26 of file MouseManager.java.
Referenced by game_engine.UI.InputManager.inputOccurred().
MouseEvent game_engine.UI.MouseManager.getLastClick ()
Definition at line 39 of file MouseManager.java.
References game_engine.UI.MouseManager.lastEvent.
Referenced by game_engine.visuals.SelectionBox.reactToDrag(), game_engine.visuals.SelectionBox.update(), and game_engine.stateManaging.GameElementManager.update().
Point2D game_engine.UI.MouseManager.getMapLoc ()
Definition at line 35 of file MouseManager.java.
Referenced by game_engine.visuals.SelectionBox.update(), and game_engine.stateManaging.GameElementManager.update().
Member Data Documentation
MouseEvent game_engine.UI.MouseManager.lastEvent private
Definition at line 16 of file MouseManager.java.
Referenced by game_engine.UI.MouseManager.getLastClick().
double game_engine.UI.MouseManager.xLoc private
Definition at line 17 of file MouseManager.java.
double game_engine.UI.MouseManager.yLoc package
Definition at line 17 of file MouseManager.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/UI/MouseManager.java