voogasalad_TheException: view.editor.LevelTriggersViewController Class Reference
view.editor.LevelTriggersViewController Class Reference
Classes
class TriggerListCell
Public Member Functions
void setButtonAction (Consumer< Consumer< WizardData >> consumer)
void setSelectedAction (BiConsumer< Integer, String > consumer)
void setDeleteAction (Consumer< Integer > consumer)
Node getRoot ()
void initialize ()
void updateTriggerList (List< TriggerPair > triggers)
Private Member Functions
void initListView ()
void itemClicked (int clicks, MouseEvent mouseEvent, BiConsumer< Integer, String > consumer)
void buttonClicked (Consumer< Integer > consumer)
Private Attributes
VBox levelTriggersView
Button newLevelTrigger
Button deleteTrigger
ListView< String > levelTriggers
ObservableList< String > myTriggerList
Static Private Attributes
static final String NEW_TRIGGER_KEY = "NewTrigger"
static final String DELETE_SELECTED_KEY = "DeleteSelected"
Detailed Description
This class represents the pane held within a TabPane representing all of the Triggers/Goals associated with a level. It holds a button to add a new Trigger/Goal along with a clickable list of the existing Goals. Both of these elements will spawn a TriggerWizard upon double-click. The publically accessible methods of this class include setting the onButtonClick and the onSelectedClick within the list view. Furthermore, one has the ability to update the list of triggers with a list of TriggerPair elements.
Author
Jonathan Tseng
Nishad Agrawal
Definition at line 37 of file LevelTriggersViewController.java.
Member Function Documentation
void view.editor.LevelTriggersViewController.buttonClicked (Consumer< Integer > consumer) private
Definition at line 119 of file LevelTriggersViewController.java.
Referenced by view.editor.LevelTriggersViewController.setDeleteAction().
Node view.editor.LevelTriggersViewController.getRoot ()
Implements view.gui.GUIController.
Definition at line 74 of file LevelTriggersViewController.java.
References view.editor.LevelTriggersViewController.levelTriggersView.
void view.editor.LevelTriggersViewController.initialize ()
Implements view.gui.GUIController.
Definition at line 79 of file LevelTriggersViewController.java.
References view.dialog.DialogBoxUtility.createMessageDialog(), util.multilanguage.MultiLanguageUtility.getInstance(), util.multilanguage.MultiLanguageUtility.getStringProperty(), and view.editor.LevelTriggersViewController.initListView().
void view.editor.LevelTriggersViewController.initListView () private
Definition at line 92 of file LevelTriggersViewController.java.
Referenced by view.editor.LevelTriggersViewController.initialize().
void view.editor.LevelTriggersViewController.itemClicked (int clicks, MouseEvent mouseEvent, BiConsumer< Integer, String > consumer) private
This method sends the currently selected text and position within the list of the selected item into the consumer when an element in the list of triggers has been double clicked.
Parameters
mouseEvent
consumer
Definition at line 110 of file LevelTriggersViewController.java.
Referenced by view.editor.LevelTriggersViewController.setSelectedAction().
void view.editor.LevelTriggersViewController.setButtonAction (Consumer< Consumer< WizardData >> consumer)
Parameters
consumer The consumer to execute when the new button is clicked
Definition at line 57 of file LevelTriggersViewController.java.
Referenced by view.editor.TabViewController.init().
void view.editor.LevelTriggersViewController.setDeleteAction (Consumer< Integer > consumer)
Definition at line 69 of file LevelTriggersViewController.java.
References view.editor.LevelTriggersViewController.buttonClicked().
Referenced by view.editor.TabViewController.init().
void view.editor.LevelTriggersViewController.setSelectedAction (BiConsumer< Integer, String > consumer)
Parameters
consumer The consumer to execute when an item in the list is selected
Definition at line 65 of file LevelTriggersViewController.java.
References view.editor.LevelTriggersViewController.itemClicked().
Referenced by view.editor.TabViewController.init().
void view.editor.LevelTriggersViewController.updateTriggerList (List< TriggerPair > triggers)
Parameters
triggers The list of values to pass into the ListView
Definition at line 127 of file LevelTriggersViewController.java.
Referenced by view.editor.TabViewController.updateLevelTriggersView().
Member Data Documentation
final String view.editor.LevelTriggersViewController.DELETE_SELECTED_KEY = "DeleteSelected" static private
Definition at line 40 of file LevelTriggersViewController.java.
Button view.editor.LevelTriggersViewController.deleteTrigger private
Definition at line 47 of file LevelTriggersViewController.java.
ListView<String> view.editor.LevelTriggersViewController.levelTriggers private
Definition at line 49 of file LevelTriggersViewController.java.
VBox view.editor.LevelTriggersViewController.levelTriggersView private
Definition at line 43 of file LevelTriggersViewController.java.
Referenced by view.editor.LevelTriggersViewController.getRoot().
ObservableList<String> view.editor.LevelTriggersViewController.myTriggerList private
Definition at line 51 of file LevelTriggersViewController.java.
final String view.editor.LevelTriggersViewController.NEW_TRIGGER_KEY = "NewTrigger" static private
Definition at line 39 of file LevelTriggersViewController.java.
Button view.editor.LevelTriggersViewController.newLevelTrigger private
Definition at line 45 of file LevelTriggersViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/LevelTriggersViewController.java