voogasalad_TheException: model.state.LevelState Class Reference
model.state.LevelState Class Reference
Public Member Functions
LevelState ()
LevelState (String name, String campaignName)
List< DrawableGameElementState > getTerrain ()
void addTerrain (DrawableGameElementState terrain)
List< SelectableGameElementState > getUnits ()
void addUnit (SelectableGameElementState unit)
List< GameElementState > getGoals ()
void removeElement (GameElementState state)
void addGoal (GameElementState goal)
boolean equals (Object o)
LevelIdentifier getIdentifier ()
Public Member Functions inherited from model.state.DescribableState
void updateName (String name)
void updateDescription (String description)
String getName ()
String getDescription ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Public Member Functions inherited from util.JSONable
default String toJSON ()
Public Attributes
AttributeContainer attributes
Private Attributes
List< DrawableGameElementState > myTerrains
List< SelectableGameElementState > myUnits
List< GameElementState > myGoals
LevelIdentifier myIdentifier
Static Private Attributes
static final long serialVersionUID = 846038357373984158L
Additional Inherited Members
Protected Member Functions inherited from model.state.DescribableState
DescribableState ()
DescribableState (String name)
Detailed Description
The Level class is the direct point of interaction for most gameplay and editing - this class holds all of the GameElements being used for the current editing and/or game running session. Essentially a data wrapper class for all objects and states contained in a level.
Author
Steve, Jonathan, Nishad, Rahul
Definition at line 21 of file LevelState.java.
Constructor & Destructor Documentation
model.state.LevelState.LevelState ()
Definition at line 33 of file LevelState.java.
Referenced by model.state.LevelState.equals().
model.state.LevelState.LevelState (String name, String campaignName)
Definition at line 36 of file LevelState.java.
Member Function Documentation
void model.state.LevelState.addGoal (GameElementState goal)
Parameters
goal the goal to be added to the level's list of goals
Definition at line 101 of file LevelState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement(), model.MainModel.createGoal(), application.Pong.hardCodeAGame(), and application.RPG.hardCodeAGame().
void model.state.LevelState.addTerrain (DrawableGameElementState terrain)
Parameters
terrain the terrain to be added to the level's terrains
Definition at line 59 of file LevelState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement(), and model.MainModel.setTerrain().
void model.state.LevelState.addUnit (SelectableGameElementState unit)
Parameters
unit the unit to be added to the level's list of units
Definition at line 77 of file LevelState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.addElement(), application.Pong.hardCodeAGame(), and application.RPG.hardCodeAGame().
boolean model.state.LevelState.equals (Object o)
Definition at line 106 of file LevelState.java.
References model.state.LevelIdentifier.equals(), model.state.LevelState.LevelState(), and model.state.LevelState.myIdentifier.
List<GameElementState> model.state.LevelState.getGoals ()
Returns
List<GameElementState> the list of the level's goals
Definition at line 86 of file LevelState.java.
References model.state.LevelState.myGoals.
Referenced by view.editor.TabViewController.createInternalConsumer(), engine.elementFactories.LevelFactory.createLevel(), model.MainModel.removeGoal(), and view.editor.TabViewController.updateLevelTriggersView().
LevelIdentifier model.state.LevelState.getIdentifier ()
Definition at line 115 of file LevelState.java.
References model.state.LevelState.myIdentifier.
Referenced by view.editor.TabViewController.isLevel(), and view.editor.TabViewController.updateModelToSave().
List<DrawableGameElementState> model.state.LevelState.getTerrain ()
Returns
List<DrawableGameElementState> the list of the level's terrains
Definition at line 50 of file LevelState.java.
References model.state.LevelState.myTerrains.
Referenced by engine.elementFactories.LevelFactory.createLevel().
List<SelectableGameElementState> model.state.LevelState.getUnits ()
Returns
myUnits the list of the level's units
Definition at line 68 of file LevelState.java.
References model.state.LevelState.myUnits.
Referenced by engine.elementFactories.LevelFactory.createLevel().
void model.state.LevelState.removeElement (GameElementState state)
Definition at line 90 of file LevelState.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.removeElement().
Member Data Documentation
AttributeContainer model.state.LevelState.attributes
Definition at line 27 of file LevelState.java.
Referenced by model.MainModel.areCoordinatesValid(), engine.elementFactories.LevelFactory.createLevel(), model.MainModel.createLevel(), engine.gameRepresentation.renderedRepresentation.Level.getMapHeight(), engine.gameRepresentation.renderedRepresentation.Level.getMapWidth(), engine.gameRepresentation.renderedRepresentation.Level.getNumericalAttribute(), engine.gameRepresentation.renderedRepresentation.Level.getTextualAttribute(), application.Pong.hardCodeAGame(), application.RPG.hardCodeAGame(), engine.gameRepresentation.renderedRepresentation.Level.setNumericalAttribute(), model.MainModel.setTerrain(), and engine.gameRepresentation.renderedRepresentation.Level.setTextualAttribute().
List<GameElementState> model.state.LevelState.myGoals private
Definition at line 30 of file LevelState.java.
Referenced by model.state.LevelState.getGoals().
LevelIdentifier model.state.LevelState.myIdentifier private
Definition at line 31 of file LevelState.java.
Referenced by model.state.LevelState.equals(), and model.state.LevelState.getIdentifier().
List<DrawableGameElementState> model.state.LevelState.myTerrains private
Definition at line 28 of file LevelState.java.
Referenced by model.state.LevelState.getTerrain().
List<SelectableGameElementState> model.state.LevelState.myUnits private
Definition at line 29 of file LevelState.java.
Referenced by model.state.LevelState.getUnits().
final long model.state.LevelState.serialVersionUID = 846038357373984158L static private
Auto-generated
Definition at line 26 of file LevelState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/state/LevelState.java