voogasalad_TheException: model.GameUniverse Class Reference
model.GameUniverse Class Reference
Public Member Functions
GameUniverse ()
void addParticipantColor (Long color)
Set< Long > getParticipantColors ()
void addGameElementState (GameElementState ges)
void addDrawableGameElementState (DrawableGameElementState dges)
void addSelectableGameElementState (SelectableGameElementState sges)
Set< GameElementState > getGameElementStates ()
Set< DrawableGameElementState > getDrawableGameElementStates ()
Set< SelectableGameElementState > getSelectableGameElementStates ()
void removeSelectableGameElementState (String sges)
void removeDrawableGameElementState (String dges)
void removeGameElementState (GameElementState ges)
GameElementState getGameElementState (String elementName)
DrawableGameElementState getDrawableGameElementState (String elementName)
SelectableGameElementState getSelectableGameElementState (String elementName)
Set< Attribute< Number > > getNumericalAttributes ()
Set< Attribute< String > > getStringAttributes ()
Private Member Functions
void storeAttributes (GameElementState ges)
Private Attributes
Set< Long > myParticipantColors
Set< Attribute< Number > > myNumericalAttributes
Set< Attribute< String > > myTextualAttributes
Set< GameElementState > myGameElementStates
Set< DrawableGameElementState > myDrawableGameElementStates
Set< SelectableGameElementState > mySelectableGameElementStates
Detailed Description
Class that represents all possible elements that could make up a game. This is a passive data structure/wrapper class** with no behavior.
Author
Jonathan Tseng, Rahul
Definition at line 23 of file GameUniverse.java.
Constructor & Destructor Documentation
model.GameUniverse.GameUniverse ()
Definition at line 31 of file GameUniverse.java.
Member Function Documentation
void model.GameUniverse.addDrawableGameElementState (DrawableGameElementState dges)
Definition at line 53 of file GameUniverse.java.
References model.GameUniverse.storeAttributes().
Referenced by model.MainModel.createDrawableGameElementState().
void model.GameUniverse.addGameElementState (GameElementState ges)
Definition at line 48 of file GameUniverse.java.
References model.GameUniverse.storeAttributes().
Referenced by model.MainModel.createGameElementState().
void model.GameUniverse.addParticipantColor (Long color)
Definition at line 40 of file GameUniverse.java.
Referenced by view.editor.EditorScreen.initParticipantInfo().
void model.GameUniverse.addSelectableGameElementState (SelectableGameElementState sges)
Definition at line 58 of file GameUniverse.java.
References model.GameUniverse.storeAttributes().
Referenced by model.MainModel.createSelectableGameElementState(), application.RPG.hardCodeAGame(), and application.Pong.hardCodeAGame().
DrawableGameElementState model.GameUniverse.getDrawableGameElementState (String elementName)
Definition at line 105 of file GameUniverse.java.
References util.DeepCopy.deepCopy().
Referenced by model.MainModel.addTerrainToLevel(), engine.elementFactories.GameElementFactory.createDrawableGameElement(), view.editor.ElementAccordionController.init(), and model.MainModel.setTerrain().
Set<DrawableGameElementState> model.GameUniverse.getDrawableGameElementStates ()
Definition at line 72 of file GameUniverse.java.
Referenced by view.editor.ElementAccordionController.modelUpdate(), view.editor.ElementAccordionController.openDrawableGameElementWizard(), and model.MainModel.updateSpritesAndMasks().
GameElementState model.GameUniverse.getGameElementState (String elementName)
Definition at line 98 of file GameUniverse.java.
References util.DeepCopy.deepCopy().
Referenced by engine.elementFactories.GameElementFactory.createGameElement().
Set<GameElementState> model.GameUniverse.getGameElementStates ()
Definition at line 68 of file GameUniverse.java.
Set<Attribute<Number> > model.GameUniverse.getNumericalAttributes ()
Definition at line 120 of file GameUniverse.java.
References model.GameUniverse.myNumericalAttributes.
Referenced by view.editor.TabViewController.addNumberAttributes(), and view.editor.ElementAccordionController.addNumberAttributes().
Set<Long> model.GameUniverse.getParticipantColors ()
Definition at line 44 of file GameUniverse.java.
SelectableGameElementState model.GameUniverse.getSelectableGameElementState (String elementName)
Definition at line 112 of file GameUniverse.java.
References util.DeepCopy.deepCopy().
Referenced by model.MainModel.addUnitToLevel(), engine.elementFactories.GameElementFactory.createSelectableGameElement(), and view.editor.ElementAccordionController.init().
Set<SelectableGameElementState> model.GameUniverse.getSelectableGameElementStates ()
Definition at line 76 of file GameUniverse.java.
Referenced by view.editor.ElementAccordionController.modelUpdate(), view.editor.ElementAccordionController.openSelectableGameElementWizard(), and model.MainModel.updateSpritesAndMasks().
Set<Attribute<String> > model.GameUniverse.getStringAttributes ()
Definition at line 124 of file GameUniverse.java.
References model.GameUniverse.myTextualAttributes.
Referenced by view.editor.ElementAccordionController.addStringAttributes().
void model.GameUniverse.removeDrawableGameElementState (String dges)
Definition at line 86 of file GameUniverse.java.
Referenced by view.editor.ElementAccordionController.openDrawableGameElementWizard(), and model.MainModel.removeDrawableGameElement().
void model.GameUniverse.removeGameElementState (GameElementState ges)
Definition at line 92 of file GameUniverse.java.
void model.GameUniverse.removeSelectableGameElementState (String sges)
Definition at line 80 of file GameUniverse.java.
Referenced by view.editor.ElementAccordionController.openSelectableGameElementWizard(), and model.MainModel.removeSelectableGameElement().
void model.GameUniverse.storeAttributes (GameElementState ges) private
Definition at line 63 of file GameUniverse.java.
References model.state.gameelement.GameElementState.attributes, model.state.gameelement.AttributeContainer.getNumericalAttributes(), and model.state.gameelement.AttributeContainer.getTextualAttributes().
Referenced by model.GameUniverse.addDrawableGameElementState(), model.GameUniverse.addGameElementState(), and model.GameUniverse.addSelectableGameElementState().
Member Data Documentation
Set<DrawableGameElementState> model.GameUniverse.myDrawableGameElementStates private
Definition at line 28 of file GameUniverse.java.
Set<GameElementState> model.GameUniverse.myGameElementStates private
Definition at line 27 of file GameUniverse.java.
Set<Attribute<Number> > model.GameUniverse.myNumericalAttributes private
Definition at line 25 of file GameUniverse.java.
Referenced by model.GameUniverse.getNumericalAttributes().
Set<Long> model.GameUniverse.myParticipantColors private
Definition at line 24 of file GameUniverse.java.
Set<SelectableGameElementState> model.GameUniverse.mySelectableGameElementStates private
Definition at line 29 of file GameUniverse.java.
Set<Attribute<String> > model.GameUniverse.myTextualAttributes private
Definition at line 26 of file GameUniverse.java.
Referenced by model.GameUniverse.getStringAttributes().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/model/GameUniverse.java