voogasalad_TheException: view.gui.StackPaneGUIScreen Class Reference
view.gui.StackPaneGUIScreen Class Reference abstract
Protected Member Functions
void setFront (Node child)
void bindPaneSize (Pane pane)
Protected Member Functions inherited from view.gui.GUIContainer
abstract void init ()
void attachChildContainers (GUIContainer...children)
void clearChildContainers ()
Protected Attributes
StackPane stackPane
Button sizedButton
Protected Attributes inherited from view.gui.GUIContainer
MainModel myMainModel
Additional Inherited Members
Public Member Functions inherited from view.gui.GUIScreen
void attachSceneHandler (MainView mainView)
void switchScreen (ViewScreenPath screen)
Public Member Functions inherited from view.gui.GUIContainer
final void initialize ()
void setModel (MainModel model)
final void update (Observable o, Object arg)
void engineUpdate (AttributeContainer attributes)
abstract void modelUpdate ()
Public Member Functions inherited from view.gui.GUIController
abstract Node getRoot ()
Detailed Description
Definition at line 10 of file StackPaneGUIScreen.java.
Member Function Documentation
void view.gui.StackPaneGUIScreen.bindPaneSize (Pane pane) protected
Definition at line 24 of file StackPaneGUIScreen.java.
Referenced by view.runner.RunnerScreen.init().
void view.gui.StackPaneGUIScreen.setFront (Node child) protected
Definition at line 17 of file StackPaneGUIScreen.java.
Referenced by view.runner.RunnerScreen.init(), and view.runner.RunnerScreen.playLevel().
Member Data Documentation
Button view.gui.StackPaneGUIScreen.sizedButton protected
Definition at line 15 of file StackPaneGUIScreen.java.
Referenced by view.runner.RunnerScreen.init().
StackPane view.gui.StackPaneGUIScreen.stackPane protected
Definition at line 13 of file StackPaneGUIScreen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/gui/StackPaneGUIScreen.java