voogasalad_TheException: game_requests.forwarding.DeliveryException Class Reference
game_requests.forwarding.DeliveryException Class Reference
Public Member Functions
DeliveryException (IRequest request, String reason)
IRequest request ()
String reason ()
Private Attributes
IRequest myRequest
String myReason
Static Private Attributes
static final long serialVersionUID = 7788838511248429280L
Detailed Description
An exception capturing when an error occurred during delivery of an request to a known receiver
Definition at line 9 of file DeliveryException.java.
Constructor & Destructor Documentation
game_requests.forwarding.DeliveryException.DeliveryException (IRequest request, String reason)
Create a new delivery exception
Parameters
request The request that failed to deliver
reason The reason the delivery failed
Definition at line 23 of file DeliveryException.java.
References game_requests.forwarding.DeliveryException.reason(), and game_requests.forwarding.DeliveryException.request().
Member Function Documentation
String game_requests.forwarding.DeliveryException.reason ()
Get the reason
Returns
The reason the delivery failed
Definition at line 43 of file DeliveryException.java.
References game_requests.forwarding.DeliveryException.myReason.
Referenced by game_requests.forwarding.DeliveryException.DeliveryException().
IRequest game_requests.forwarding.DeliveryException.request ()
Get the request
Returns
The request that failed to deliver
Definition at line 34 of file DeliveryException.java.
References game_requests.forwarding.DeliveryException.myRequest.
Referenced by game_requests.forwarding.DeliveryException.DeliveryException().
Member Data Documentation
String game_requests.forwarding.DeliveryException.myReason private
Definition at line 13 of file DeliveryException.java.
Referenced by game_requests.forwarding.DeliveryException.reason().
IRequest game_requests.forwarding.DeliveryException.myRequest private
Definition at line 12 of file DeliveryException.java.
Referenced by game_requests.forwarding.DeliveryException.request().
final long game_requests.forwarding.DeliveryException.serialVersionUID = 7788838511248429280L static private
Definition at line 11 of file DeliveryException.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_requests/forwarding/DeliveryException.java