voogasalad_TheException: game_engine.visuals.MiniMap Class Reference
game_engine.visuals.MiniMap Class Reference
Public Member Functions
MiniMap (ScrollablePane SS)
Canvas getDisplay ()
void setUnits (List< SelectableGameElement > units)
void updateMiniMap ()
Static Public Attributes
static final double FIELD_WIDTH = 2000
static final double FIELD_HEIGHT = 2000
Private Member Functions
void moveSceneBox ()
void moveUnits ()
void initializeDisplay ()
void initializeGraphicsContext ()
Private Attributes
ScrollablePane myScene
Canvas myDisplay
GraphicsContext myGraphicsContext
List< SelectableGameElement > gameUnits
Static Private Attributes
static final double MINIMAP_XPOS = 1000
static final double MINIMAP_YPOS = 32
static final double MINIMAP_WIDTH = 250
static final double MINIMAP_HEIGHT = 250
static final double X_SCALE = FIELD_WIDTH / MINIMAP_WIDTH
static final double Y_SCALE = FIELD_HEIGHT / MINIMAP_HEIGHT
Detailed Description
The minimap for the application
Author
Michael D.
Definition at line 16 of file MiniMap.java.
Constructor & Destructor Documentation
game_engine.visuals.MiniMap.MiniMap (ScrollablePane SS)
Constructor for the MiniMap
Definition at line 36 of file MiniMap.java.
References game_engine.visuals.MiniMap.initializeDisplay(), and game_engine.visuals.MiniMap.initializeGraphicsContext().
Member Function Documentation
Canvas game_engine.visuals.MiniMap.getDisplay ()
Gets the canvas for the minimap
Returns
The canvas representing the minimap
Definition at line 49 of file MiniMap.java.
References game_engine.visuals.MiniMap.myDisplay.
Referenced by game_engine.Engine.selectLevel(), and game_engine.Engine.updateGameLoop().
void game_engine.visuals.MiniMap.initializeDisplay () private
Definition at line 91 of file MiniMap.java.
Referenced by game_engine.visuals.MiniMap.MiniMap().
void game_engine.visuals.MiniMap.initializeGraphicsContext () private
Definition at line 99 of file MiniMap.java.
Referenced by game_engine.visuals.MiniMap.MiniMap(), and game_engine.visuals.MiniMap.updateMiniMap().
void game_engine.visuals.MiniMap.moveSceneBox () private
Definition at line 72 of file MiniMap.java.
References game_engine.visuals.ScrollablePane.getScrollingBackground(), game_engine.visuals.MiniMap.X_SCALE, and game_engine.visuals.MiniMap.Y_SCALE.
Referenced by game_engine.visuals.MiniMap.updateMiniMap().
void game_engine.visuals.MiniMap.moveUnits () private
Definition at line 83 of file MiniMap.java.
References game_engine.visuals.MiniMap.X_SCALE, and game_engine.visuals.MiniMap.Y_SCALE.
Referenced by game_engine.visuals.MiniMap.updateMiniMap().
void game_engine.visuals.MiniMap.setUnits (List< SelectableGameElement > units)
Sets the list of units of the current level
Parameters
units The list of units
Definition at line 59 of file MiniMap.java.
Referenced by game_engine.Engine.selectLevel(), and game_engine.Engine.updateGameLoop().
void game_engine.visuals.MiniMap.updateMiniMap ()
Updates the drawings and points on the minimap
Definition at line 66 of file MiniMap.java.
References game_engine.visuals.MiniMap.initializeGraphicsContext(), game_engine.visuals.MiniMap.moveSceneBox(), and game_engine.visuals.MiniMap.moveUnits().
Referenced by game_engine.stateManaging.GameLoop.update().
Member Data Documentation
final double game_engine.visuals.MiniMap.FIELD_HEIGHT = 2000 static
Definition at line 24 of file MiniMap.java.
final double game_engine.visuals.MiniMap.FIELD_WIDTH = 2000 static
Definition at line 23 of file MiniMap.java.
List<SelectableGameElement> game_engine.visuals.MiniMap.gameUnits private
Definition at line 31 of file MiniMap.java.
final double game_engine.visuals.MiniMap.MINIMAP_HEIGHT = 250 static private
Definition at line 22 of file MiniMap.java.
final double game_engine.visuals.MiniMap.MINIMAP_WIDTH = 250 static private
Definition at line 21 of file MiniMap.java.
final double game_engine.visuals.MiniMap.MINIMAP_XPOS = 1000 static private
Definition at line 19 of file MiniMap.java.
final double game_engine.visuals.MiniMap.MINIMAP_YPOS = 32 static private
Definition at line 20 of file MiniMap.java.
Canvas game_engine.visuals.MiniMap.myDisplay private
Definition at line 29 of file MiniMap.java.
Referenced by game_engine.visuals.MiniMap.getDisplay().
GraphicsContext game_engine.visuals.MiniMap.myGraphicsContext private
Definition at line 30 of file MiniMap.java.
ScrollablePane game_engine.visuals.MiniMap.myScene private
Definition at line 28 of file MiniMap.java.
final double game_engine.visuals.MiniMap.X_SCALE = FIELD_WIDTH / MINIMAP_WIDTH static private
Definition at line 25 of file MiniMap.java.
Referenced by game_engine.visuals.MiniMap.moveSceneBox(), and game_engine.visuals.MiniMap.moveUnits().
final double game_engine.visuals.MiniMap.Y_SCALE = FIELD_HEIGHT / MINIMAP_HEIGHT static private
Definition at line 26 of file MiniMap.java.
Referenced by game_engine.visuals.MiniMap.moveSceneBox(), and game_engine.visuals.MiniMap.moveUnits().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/MiniMap.java