voogasalad_TheException: view.editor.wizards.Grid Class Reference
view.editor.wizards.Grid Class Reference abstract
Classes
class Frame
Public Member Functions
Grid (double frameX, double frameY)
abstract void selectFrame (int row, int col, Paint fill)
double getFrameX ()
double getFrameY ()
Protected Member Functions
void resetExistingFill (String primary, Paint reset)
void createGrid ()
abstract void createColumns ()
abstract Group createColumn (int col)
Frame createFrame (int row, int col, Paint fill)
Protected Attributes
double myFrameX
double myFrameY
List< List< Frame > > frameCols
Static Protected Attributes
static final String FRAME_STROKE_COLOR = "black"
Detailed Description
Grid Lines used to be displayed over a sprite sheet within the drawable game element wizard.
Author
Jonathan Tseng, Nishad Agrawal
Definition at line 16 of file Grid.java.
Constructor & Destructor Documentation
view.editor.wizards.Grid.Grid (double frameX, double frameY)
Definition at line 22 of file Grid.java.
References view.editor.wizards.Grid.createGrid().
Member Function Documentation
abstract Group view.editor.wizards.Grid.createColumn (int col) abstract protected
abstract void view.editor.wizards.Grid.createColumns () abstract protected
Referenced by view.editor.wizards.Grid.createGrid().
Frame view.editor.wizards.Grid.createFrame (int row, int col, Paint fill) protected
Definition at line 49 of file Grid.java.
Referenced by view.editor.wizards.DirectionGrid.createColumn(), and view.editor.wizards.AnimationGrid.createColumn().
void view.editor.wizards.Grid.createGrid () protected
Definition at line 40 of file Grid.java.
References view.editor.wizards.Grid.createColumns().
Referenced by view.editor.wizards.AnimationGrid.changeSize(), and view.editor.wizards.Grid.Grid().
double view.editor.wizards.Grid.getFrameX ()
Definition at line 56 of file Grid.java.
References view.editor.wizards.Grid.myFrameX.
Referenced by view.editor.wizards.GameElementWizard.createSliderListeners().
double view.editor.wizards.Grid.getFrameY ()
Definition at line 60 of file Grid.java.
References view.editor.wizards.Grid.myFrameY.
Referenced by view.editor.wizards.GameElementWizard.createSliderListeners().
void view.editor.wizards.Grid.resetExistingFill (String primary, Paint reset) protected
Definition at line 32 of file Grid.java.
Referenced by view.editor.wizards.DirectionGrid.selectFrame(), and view.editor.wizards.AnimationGrid.selectFrame().
abstract void view.editor.wizards.Grid.selectFrame (int row, int col, Paint fill) abstract
Member Data Documentation
final String view.editor.wizards.Grid.FRAME_STROKE_COLOR = "black" static protected
Definition at line 17 of file Grid.java.
List<List<Frame> > view.editor.wizards.Grid.frameCols protected
Definition at line 20 of file Grid.java.
Referenced by view.editor.wizards.DirectionGrid.createColumn(), view.editor.wizards.AnimationGrid.createColumn(), view.editor.wizards.DirectionGrid.createColumns(), view.editor.wizards.AnimationGrid.createColumns(), view.editor.wizards.AnimationGrid.getNumRows(), view.editor.wizards.DirectionGrid.selectFrame(), and view.editor.wizards.AnimationGrid.selectFrame().
double view.editor.wizards.Grid.myFrameX protected
Definition at line 18 of file Grid.java.
Referenced by view.editor.wizards.AnimationGrid.changeSize(), view.editor.wizards.DirectionGrid.createColumns(), view.editor.wizards.AnimationGrid.createColumns(), and view.editor.wizards.Grid.getFrameX().
double view.editor.wizards.Grid.myFrameY protected
Definition at line 19 of file Grid.java.
Referenced by view.editor.wizards.AnimationGrid.changeSize(), view.editor.wizards.DirectionGrid.createColumn(), view.editor.wizards.AnimationGrid.createColumn(), and view.editor.wizards.Grid.getFrameY().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/Grid.java