voogasalad_TheException: engine.elementFactories.GameElementFactory Class Reference
engine.elementFactories.GameElementFactory Class Reference
Public Member Functions
GameElementFactory (GameUniverse universe, ActionFactory actionFactory, VisualizerFactory visualizerFactory)
GameElement createGameElement (String elementType, double x, double y)
GameElement createGameElement (GameElementState state)
DrawableGameElement createDrawableGameElement (String elementType, double x, double y)
DrawableGameElement createDrawableGameElement (DrawableGameElementState state)
SelectableGameElement createSelectableGameElement (String elementType, double x, double y, Number color)
SelectableGameElement createSelectableGameElement (SelectableGameElementState state)
Private Member Functions
void generateActions (GameElement element, GameElementState state)
Visualizer generateVisualizer (DrawableGameElementState elementState)
Private Attributes
GameUniverse myUniverse
ActionFactory myActionFactory
VisualizerFactory myVisualizerFactory
Detailed Description
Factory that takes in GameElementStates and generates their JavaFX representations as well as their Evaluatables, then packs it all into the rendered wrapper used in the engine.
Author
Steve, Stanley
Definition at line 29 of file GameElementFactory.java.
Constructor & Destructor Documentation
engine.elementFactories.GameElementFactory.GameElementFactory (GameUniverse universe, ActionFactory actionFactory, VisualizerFactory visualizerFactory)
Definition at line 34 of file GameElementFactory.java.
Member Function Documentation
DrawableGameElement engine.elementFactories.GameElementFactory.createDrawableGameElement (String elementType, double x, double y)
Definition at line 55 of file GameElementFactory.java.
References model.GameUniverse.getDrawableGameElementState(), and engine.gameRepresentation.renderedRepresentation.GameElement.setPosition().
Referenced by engine.stateManaging.GameElementManager.addDrawableGameElementToLevel(), and engine.elementFactories.LevelFactory.generateTerrainElements().
DrawableGameElement engine.elementFactories.GameElementFactory.createDrawableGameElement (DrawableGameElementState state)
Definition at line 62 of file GameElementFactory.java.
References engine.elementFactories.GameElementFactory.generateActions(), and engine.elementFactories.GameElementFactory.generateVisualizer().
GameElement engine.elementFactories.GameElementFactory.createGameElement (String elementType, double x, double y)
Definition at line 42 of file GameElementFactory.java.
References model.GameUniverse.getGameElementState(), and engine.gameRepresentation.renderedRepresentation.GameElement.setPosition().
Referenced by engine.stateManaging.GameElementManager.addGameElementToLevel(), and engine.elementFactories.LevelFactory.generateGoalElements().
GameElement engine.elementFactories.GameElementFactory.createGameElement (GameElementState state)
Definition at line 49 of file GameElementFactory.java.
References engine.elementFactories.GameElementFactory.generateActions().
SelectableGameElement engine.elementFactories.GameElementFactory.createSelectableGameElement (String elementType, double x, double y, Number color)
Definition at line 70 of file GameElementFactory.java.
References model.state.gameelement.GameElementState.attributes, model.GameUniverse.getSelectableGameElementState(), model.state.gameelement.AttributeContainer.setNumericalAttribute(), engine.gameRepresentation.renderedRepresentation.GameElement.setPosition(), and model.state.gameelement.StateTags.TEAM_COLOR.
Referenced by engine.stateManaging.GameElementManager.addSelectableGameElementToLevel(), and engine.elementFactories.LevelFactory.generateUnitEelements().
SelectableGameElement engine.elementFactories.GameElementFactory.createSelectableGameElement (SelectableGameElementState state)
Definition at line 81 of file GameElementFactory.java.
References engine.elementFactories.GameElementFactory.generateActions(), and engine.elementFactories.GameElementFactory.generateVisualizer().
void engine.elementFactories.GameElementFactory.generateActions (GameElement element, GameElementState state) private
Iterate through the actions within an element's state and instantiate all the element's actions
Parameters
element the game element
state the game element's state
Definition at line 95 of file GameElementFactory.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.addAction(), engine.gameRepresentation.evaluatables.actions.ActionFactory.createAction(), and model.state.gameelement.GameElementState.getActions().
Referenced by engine.elementFactories.GameElementFactory.createDrawableGameElement(), engine.elementFactories.GameElementFactory.createGameElement(), and engine.elementFactories.GameElementFactory.createSelectableGameElement().
Visualizer engine.elementFactories.GameElementFactory.generateVisualizer (DrawableGameElementState elementState) private
Definition at line 111 of file GameElementFactory.java.
References engine.elementFactories.VisualizerFactory.createVisualizer().
Referenced by engine.elementFactories.GameElementFactory.createDrawableGameElement(), and engine.elementFactories.GameElementFactory.createSelectableGameElement().
Member Data Documentation
ActionFactory engine.elementFactories.GameElementFactory.myActionFactory private
Definition at line 31 of file GameElementFactory.java.
GameUniverse engine.elementFactories.GameElementFactory.myUniverse private
Definition at line 30 of file GameElementFactory.java.
VisualizerFactory engine.elementFactories.GameElementFactory.myVisualizerFactory private
Definition at line 32 of file GameElementFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/elementFactories/GameElementFactory.java