voogasalad_TheException: engine.visuals.MiniMap Class Reference
engine.visuals.MiniMap Class Reference
Public Member Functions
MiniMap (ScrollablePane SS)
Canvas getDisplay ()
void updateMiniMap (List< SelectableGameElement > unitList)
Private Member Functions
void moveSceneBox ()
void moveUnits (List< SelectableGameElement > gameUnits)
void setUnitColor (SelectableGameElement SGE)
void setUnitShape (SelectableGameElement SGE)
void initializeDisplay ()
void initializeGraphicsContext ()
Private Attributes
double xScale
double yScale
ScrollablePane myScene
Canvas myDisplay
GraphicsContext myGraphicsContext
Static Private Attributes
static final int CONTEXT_RECT_LINE_WIDTH = 2
static final int CONTEXT_RECT_ARC_WIDTH = 10
static final int MINIMAP_UNIT_DIAMETER = 3
static final int MINIMAP_BUILDING_DIMENSION = 8
static final int MINIMAP_LINE_WIDTH = 5
static final int MINIMAP_ARC_WIDTH = 40
static final double MINIMIAP_OPACITY = 0.8
static final double MINIMAP_WIDTH = 320
static final double MINIMAP_HEIGHT = 160
static NumberBinding xPos
static NumberBinding yPos
Detailed Description
The minimap for the application
Author
Michael D., John L.
Definition at line 22 of file MiniMap.java.
Constructor & Destructor Documentation
engine.visuals.MiniMap.MiniMap (ScrollablePane SS)
Constructor for the MiniMap
Definition at line 47 of file MiniMap.java.
References engine.visuals.ScrollablePane.FAST_SCROLL_BOUNDARY, engine.visuals.ScrollablePane.getFieldHeight(), engine.visuals.ScrollablePane.getFieldWidth(), engine.visuals.MiniMap.initializeDisplay(), engine.visuals.MiniMap.initializeGraphicsContext(), engine.visuals.MiniMap.MINIMAP_HEIGHT, and engine.visuals.MiniMap.MINIMAP_WIDTH.
Member Function Documentation
Canvas engine.visuals.MiniMap.getDisplay ()
Gets the canvas for the minimap
Returns
The canvas representing the minimap
Definition at line 69 of file MiniMap.java.
References engine.visuals.MiniMap.myDisplay.
Referenced by engine.visuals.VisualManager.VisualManager().
void engine.visuals.MiniMap.initializeDisplay () private
Definition at line 124 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.MiniMap().
void engine.visuals.MiniMap.initializeGraphicsContext () private
Definition at line 132 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.MiniMap(), and engine.visuals.MiniMap.updateMiniMap().
void engine.visuals.MiniMap.moveSceneBox () private
Definition at line 82 of file MiniMap.java.
References engine.visuals.MiniMap.CONTEXT_RECT_ARC_WIDTH, engine.visuals.ScrollablePane.getScrollingBackground(), engine.visuals.MiniMap.xScale, and engine.visuals.MiniMap.yScale.
Referenced by engine.visuals.MiniMap.updateMiniMap().
void engine.visuals.MiniMap.moveUnits (List< SelectableGameElement > gameUnits) private
Definition at line 93 of file MiniMap.java.
References engine.visuals.MiniMap.setUnitColor(), and engine.visuals.MiniMap.setUnitShape().
Referenced by engine.visuals.MiniMap.updateMiniMap().
void engine.visuals.MiniMap.setUnitColor (SelectableGameElement SGE) private
Definition at line 100 of file MiniMap.java.
References model.sprite.ColorMapGenerator.colorFromLong(), engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), and model.state.gameelement.StateTags.TEAM_COLOR.
Referenced by engine.visuals.MiniMap.moveUnits().
void engine.visuals.MiniMap.setUnitShape (SelectableGameElement SGE) private
Definition at line 111 of file MiniMap.java.
References engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getPosition(), engine.visuals.MiniMap.MINIMAP_BUILDING_DIMENSION, engine.visuals.MiniMap.MINIMAP_UNIT_DIAMETER, model.state.gameelement.StateTags.MOVEMENT_SPEED, engine.visuals.MiniMap.xScale, and engine.visuals.MiniMap.yScale.
Referenced by engine.visuals.MiniMap.moveUnits().
void engine.visuals.MiniMap.updateMiniMap (List< SelectableGameElement > unitList)
Updates the drawings and points on the minimap
Definition at line 76 of file MiniMap.java.
References engine.visuals.MiniMap.initializeGraphicsContext(), engine.visuals.MiniMap.moveSceneBox(), and engine.visuals.MiniMap.moveUnits().
Referenced by engine.visuals.VisualManager.update().
Member Data Documentation
final int engine.visuals.MiniMap.CONTEXT_RECT_ARC_WIDTH = 10 static private
Definition at line 25 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.moveSceneBox().
final int engine.visuals.MiniMap.CONTEXT_RECT_LINE_WIDTH = 2 static private
Definition at line 24 of file MiniMap.java.
final int engine.visuals.MiniMap.MINIMAP_ARC_WIDTH = 40 static private
Definition at line 29 of file MiniMap.java.
final int engine.visuals.MiniMap.MINIMAP_BUILDING_DIMENSION = 8 static private
Definition at line 27 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.setUnitShape().
final double engine.visuals.MiniMap.MINIMAP_HEIGHT = 160 static private
Definition at line 32 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.MiniMap().
final int engine.visuals.MiniMap.MINIMAP_LINE_WIDTH = 5 static private
Definition at line 28 of file MiniMap.java.
final int engine.visuals.MiniMap.MINIMAP_UNIT_DIAMETER = 3 static private
Definition at line 26 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.setUnitShape().
final double engine.visuals.MiniMap.MINIMAP_WIDTH = 320 static private
Definition at line 31 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.MiniMap().
final double engine.visuals.MiniMap.MINIMIAP_OPACITY = 0.8 static private
Definition at line 30 of file MiniMap.java.
Canvas engine.visuals.MiniMap.myDisplay private
Definition at line 41 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.getDisplay().
GraphicsContext engine.visuals.MiniMap.myGraphicsContext private
Definition at line 42 of file MiniMap.java.
ScrollablePane engine.visuals.MiniMap.myScene private
Definition at line 40 of file MiniMap.java.
NumberBinding engine.visuals.MiniMap.xPos static private
Definition at line 37 of file MiniMap.java.
double engine.visuals.MiniMap.xScale private
Definition at line 34 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.moveSceneBox(), and engine.visuals.MiniMap.setUnitShape().
NumberBinding engine.visuals.MiniMap.yPos static private
Definition at line 38 of file MiniMap.java.
double engine.visuals.MiniMap.yScale private
Definition at line 35 of file MiniMap.java.
Referenced by engine.visuals.MiniMap.moveSceneBox(), and engine.visuals.MiniMap.setUnitShape().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/MiniMap.java