voogasalad_TheException: engine.visuals.elementVisuals.Visualizer Class Reference
engine.visuals.elementVisuals.Visualizer Class Reference
Public Member Functions
Visualizer (Animator animator, AttributeContainer attributes)
void setAnimateEnableProperty (SimpleBooleanProperty e)
void addWidget (AttributeDisplayer widget)
Node getNode ()
Point2D getNodeLocation ()
boolean update ()
void initializeDisplay ()
Private Member Functions
void updateNodeLocation ()
void updateWidgets ()
void updateAnimator ()
Private Attributes
Group visualRepresentation
VBox myVBox
List< AttributeDisplayer > myWidgets
Animator myAnimator
AttributeContainer attributesOfInterest
SimpleBooleanProperty enabled
Detailed Description
Author
Steve
Definition at line 25 of file Visualizer.java.
Constructor & Destructor Documentation
engine.visuals.elementVisuals.Visualizer.Visualizer (Animator animator, AttributeContainer attributes)
Definition at line 34 of file Visualizer.java.
References engine.visuals.elementVisuals.animations.Animator.registerNode().
Member Function Documentation
void engine.visuals.elementVisuals.Visualizer.addWidget (AttributeDisplayer widget)
Definition at line 52 of file Visualizer.java.
References engine.visuals.elementVisuals.widgets.attributeDisplays.AttributeDisplayer.registerAsComponent().
Referenced by engine.elementFactories.VisualizerFactory.createVisualizer().
Node engine.visuals.elementVisuals.Visualizer.getNode ()
Returns
the object's display node
Implements engine.visuals.Displayable.
Definition at line 58 of file Visualizer.java.
References engine.visuals.elementVisuals.Visualizer.visualRepresentation.
Referenced by engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode(), and engine.visuals.elementVisuals.Visualizer.initializeDisplay().
Point2D engine.visuals.elementVisuals.Visualizer.getNodeLocation ()
Definition at line 62 of file Visualizer.java.
Referenced by engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getPosition().
void engine.visuals.elementVisuals.Visualizer.initializeDisplay ()
Definition at line 75 of file Visualizer.java.
References engine.visuals.Dimension.getHeight(), engine.visuals.elementVisuals.Visualizer.getNode(), model.state.gameelement.AttributeContainer.getNumericalAttribute(), engine.visuals.elementVisuals.animations.Animator.getViewportSize(), engine.visuals.Dimension.getWidth(), engine.visuals.elementVisuals.animations.Animator.setAnimation(), engine.visuals.elementVisuals.animations.Animator.update(), model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
Referenced by engine.gameRepresentation.renderedRepresentation.DrawableGameElement.DrawableGameElement().
void engine.visuals.elementVisuals.Visualizer.setAnimateEnableProperty (SimpleBooleanProperty e)
Definition at line 48 of file Visualizer.java.
Referenced by engine.elementFactories.VisualizerFactory.createVisualizer().
boolean engine.visuals.elementVisuals.Visualizer.update ()
Update the object
Returns
a boolean status for the update
Implements model.state.gameelement.traits.Updatable.
Definition at line 67 of file Visualizer.java.
References engine.visuals.elementVisuals.Visualizer.updateAnimator(), engine.visuals.elementVisuals.Visualizer.updateNodeLocation(), and engine.visuals.elementVisuals.Visualizer.updateWidgets().
Referenced by engine.gameRepresentation.renderedRepresentation.DrawableGameElement.update().
void engine.visuals.elementVisuals.Visualizer.updateAnimator () private
Definition at line 99 of file Visualizer.java.
References engine.visuals.elementVisuals.animations.Animator.update().
Referenced by engine.visuals.elementVisuals.Visualizer.update().
void engine.visuals.elementVisuals.Visualizer.updateNodeLocation () private
Definition at line 86 of file Visualizer.java.
References model.state.gameelement.AttributeContainer.getNumericalAttribute(), model.state.gameelement.StateTags.X_POSITION, and model.state.gameelement.StateTags.Y_POSITION.
Referenced by engine.visuals.elementVisuals.Visualizer.update().
void engine.visuals.elementVisuals.Visualizer.updateWidgets () private
Definition at line 93 of file Visualizer.java.
Referenced by engine.visuals.elementVisuals.Visualizer.update().
Member Data Documentation
AttributeContainer engine.visuals.elementVisuals.Visualizer.attributesOfInterest private
Definition at line 31 of file Visualizer.java.
SimpleBooleanProperty engine.visuals.elementVisuals.Visualizer.enabled private
Definition at line 32 of file Visualizer.java.
Animator engine.visuals.elementVisuals.Visualizer.myAnimator private
Definition at line 30 of file Visualizer.java.
VBox engine.visuals.elementVisuals.Visualizer.myVBox private
Definition at line 28 of file Visualizer.java.
List<AttributeDisplayer> engine.visuals.elementVisuals.Visualizer.myWidgets private
Definition at line 29 of file Visualizer.java.
Group engine.visuals.elementVisuals.Visualizer.visualRepresentation private
Definition at line 27 of file Visualizer.java.
Referenced by engine.visuals.elementVisuals.Visualizer.getNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/visuals/elementVisuals/Visualizer.java