voogasalad_TheException: engine.gameRepresentation.evaluatables.ElementPair Class Reference
engine.gameRepresentation.evaluatables.ElementPair Class Reference
Public Member Functions
ElementPair (GameElement actor, GameElement actee)
GameElement getActor ()
GameElement getActee ()
Private Attributes
GameElement myActor
GameElement myActee
Detailed Description
A grouping for elements used in passing actor/actee to conditions and actions. This is intentionally a data wrapper object to make passing parameters simpler into evaluatables.
Author
Zach
Definition at line 13 of file ElementPair.java.
Constructor & Destructor Documentation
engine.gameRepresentation.evaluatables.ElementPair.ElementPair (GameElement actor, GameElement actee)
Definition at line 17 of file ElementPair.java.
Member Function Documentation
GameElement engine.gameRepresentation.evaluatables.ElementPair.getActee ()
Definition at line 26 of file ElementPair.java.
References engine.gameRepresentation.evaluatables.ElementPair.myActee.
Referenced by engine.gameRepresentation.evaluatables.parameters.objectIdentifiers.ActeeObjectIdentifier.getElementOfInterest().
GameElement engine.gameRepresentation.evaluatables.ElementPair.getActor ()
Definition at line 22 of file ElementPair.java.
References engine.gameRepresentation.evaluatables.ElementPair.myActor.
Referenced by engine.gameRepresentation.evaluatables.actions.AttributeIncrementerAction.evaluate(), engine.gameRepresentation.evaluatables.actions.CheckAttributeCreateObjectAction.evaluate(), engine.gameRepresentation.evaluatables.actions.DecrementIncrementAttributeAction.evaluate(), engine.gameRepresentation.evaluatables.actions.MotherOfAllActions.evaluate(), and engine.gameRepresentation.evaluatables.parameters.objectIdentifiers.ActorObjectIdentifier.getElementOfInterest().
Member Data Documentation
GameElement engine.gameRepresentation.evaluatables.ElementPair.myActee private
Definition at line 15 of file ElementPair.java.
Referenced by engine.gameRepresentation.evaluatables.ElementPair.getActee().
GameElement engine.gameRepresentation.evaluatables.ElementPair.myActor private
Definition at line 14 of file ElementPair.java.
Referenced by engine.gameRepresentation.evaluatables.ElementPair.getActor().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/evaluatables/ElementPair.java