voogasalad_TheException: game_engine.visuals.ScrollablePane Class Reference
game_engine.visuals.ScrollablePane Class Reference
Public Member Functions
ScrollablePane (Group root, InputManager inputManager, double width, double height)
ScrollableBackground getScrollingBackground ()
void mousePressed (MouseEvent event)
void update ()
void addBoxObserver (Observer o)
void addToScene (Group g)
Static Public Attributes
static final double SLOW_SCROLL_BOUNDARY = 120
static final double FAST_SCROLL_BOUNDARY = 75
static final double FAST_SPEED = 15
static final double SLOW_SPEED = 7
static final double FIELD_WIDTH = 2000
static final double FIELD_HEIGHT = 2000
Private Member Functions
void initializeHandlers ()
void setScrollSpeed (double mouseX, double mouseY)
Private Attributes
ScrollableBackground myBackground
SelectionBox mySelectionBox
InputManager myInputManager
Group root
Detailed Description
Basically the map. JavaFX Scene node that contains the eventHandlers necessary to scroll the map and register clicks.
Author
John, Michael D.
Definition at line 22 of file ScrollablePane.java.
Constructor & Destructor Documentation
game_engine.visuals.ScrollablePane.ScrollablePane (Group root, InputManager inputManager, double width, double height)
Creates a new ScrollableScene for the map.
Parameters
root the group of elements to add to the Scene initially. If no objects have been created yet to add, just add an empty new Group()
width the width of the map (ideally larger than the screen width)
height the height of the map (ideally larger than the screen height)
Exceptions
IOException
Definition at line 44 of file ScrollablePane.java.
References game_engine.UI.InputManager.addClickObserver(), game_engine.UI.InputManager.addMouseDragObserver(), game_engine.visuals.SelectionBox.getBox(), game_engine.visuals.ScrollablePane.initializeHandlers(), and game_engine.visuals.ScrollablePane.root.
Member Function Documentation
void game_engine.visuals.ScrollablePane.addBoxObserver (Observer o)
adds an observer to the selection boxes drawn on this scene
Parameters
o the object that wants to be notified about the location on the map the box was drawn
Definition at line 171 of file ScrollablePane.java.
Referenced by game_engine.visuals.VisualManager.addBoxObserver().
void game_engine.visuals.ScrollablePane.addToScene (Group g)
Definition at line 175 of file ScrollablePane.java.
Referenced by game_engine.visuals.VisualManager.addMiniMap().
ScrollableBackground game_engine.visuals.ScrollablePane.getScrollingBackground ()
gets the background map that objects actually get added to
Returns
the background of the scrollable scene
Definition at line 84 of file ScrollablePane.java.
References game_engine.visuals.ScrollablePane.myBackground.
Referenced by game_engine.visuals.MiniMap.moveSceneBox(), and game_engine.visuals.VisualManager.VisualManager().
void game_engine.visuals.ScrollablePane.initializeHandlers () private
initializes the handlers that respond to JavaFX events necessary for scrolling and registering clicks/ drags
Definition at line 92 of file ScrollablePane.java.
References game_engine.visuals.SelectionBox.getBox(), game_engine.UI.InputManager.inputOccurred(), game_engine.visuals.ScrollablePane.mousePressed(), and game_engine.visuals.ScrollablePane.setScrollSpeed().
Referenced by game_engine.visuals.ScrollablePane.ScrollablePane().
void game_engine.visuals.ScrollablePane.mousePressed (MouseEvent event)
Definition at line 125 of file ScrollablePane.java.
References game_engine.UI.InputManager.inputOccurred(), game_engine.visuals.ScrollableBackground.setXScrollSpeed(), and game_engine.visuals.ScrollableBackground.setYScrollSpeed().
Referenced by game_engine.visuals.ScrollablePane.initializeHandlers().
void game_engine.visuals.ScrollablePane.setScrollSpeed (double mouseX, double mouseY) private
Definition at line 133 of file ScrollablePane.java.
References game_engine.visuals.ScrollableBackground.setXScrollSpeed(), and game_engine.visuals.ScrollableBackground.setYScrollSpeed().
Referenced by game_engine.visuals.ScrollablePane.initializeHandlers().
void game_engine.visuals.ScrollablePane.update ()
updates the background to scroll and draw selection boxes
Definition at line 161 of file ScrollablePane.java.
References game_engine.visuals.ScrollableBackground.update().
Referenced by game_engine.visuals.VisualManager.update().
Member Data Documentation
final double game_engine.visuals.ScrollablePane.FAST_SCROLL_BOUNDARY = 75 static
Definition at line 24 of file ScrollablePane.java.
final double game_engine.visuals.ScrollablePane.FAST_SPEED = 15 static
Definition at line 25 of file ScrollablePane.java.
final double game_engine.visuals.ScrollablePane.FIELD_HEIGHT = 2000 static
Definition at line 28 of file ScrollablePane.java.
Referenced by application.ShittyMain.hardCodeAGame(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move().
final double game_engine.visuals.ScrollablePane.FIELD_WIDTH = 2000 static
Definition at line 27 of file ScrollablePane.java.
Referenced by application.ShittyMain.hardCodeAGame(), and game_engine.gameRepresentation.renderedRepresentation.SelectableGameElement.move().
ScrollableBackground game_engine.visuals.ScrollablePane.myBackground private
Definition at line 30 of file ScrollablePane.java.
Referenced by game_engine.visuals.ScrollablePane.getScrollingBackground().
InputManager game_engine.visuals.ScrollablePane.myInputManager private
Definition at line 32 of file ScrollablePane.java.
SelectionBox game_engine.visuals.ScrollablePane.mySelectionBox private
Definition at line 31 of file ScrollablePane.java.
Group game_engine.visuals.ScrollablePane.root private
Definition at line 33 of file ScrollablePane.java.
Referenced by game_engine.visuals.ScrollablePane.ScrollablePane().
final double game_engine.visuals.ScrollablePane.SLOW_SCROLL_BOUNDARY = 120 static
Definition at line 23 of file ScrollablePane.java.
final double game_engine.visuals.ScrollablePane.SLOW_SPEED = 7 static
Definition at line 26 of file ScrollablePane.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/ScrollablePane.java