voogasalad_TheException: game_engine.visuals.LayeredAnimationPlayer Class Reference
game_engine.visuals.LayeredAnimationPlayer Class Reference
Public Member Functions
LayeredAnimationPlayer (List< Image > spriteSheets, Dimension tileSize, int numCols)
void setAnimations (List< AnimationSequence > animations)
void setNextAnimations (@NotNull List< AnimationSequence > animations)
List< ImageView > getNode ()
boolean update ()
Dimension getDimension ()
Private Member Functions
Rectangle2D getImageBounds (Image img)
Rectangle2D getViewport (int frameNumber)
Private Attributes
List< AnimationSequence > myCurrentAnimations
Dimension myTileSize
int myNumCols
List< ImageView > myDisplay
List< Rectangle2D > myImageBounds
Detailed Description
Definition at line 10 of file LayeredAnimationPlayer.java.
Constructor & Destructor Documentation
game_engine.visuals.LayeredAnimationPlayer.LayeredAnimationPlayer (List< Image > spriteSheets, Dimension tileSize, int numCols)
Definition at line 18 of file LayeredAnimationPlayer.java.
References game_engine.visuals.Dimension.getHeight(), game_engine.visuals.LayeredAnimationPlayer.getImageBounds(), and game_engine.visuals.Dimension.getWidth().
Member Function Documentation
Dimension game_engine.visuals.LayeredAnimationPlayer.getDimension ()
Definition at line 79 of file LayeredAnimationPlayer.java.
References game_engine.visuals.LayeredAnimationPlayer.myTileSize.
Rectangle2D game_engine.visuals.LayeredAnimationPlayer.getImageBounds (Image img) private
Definition at line 34 of file LayeredAnimationPlayer.java.
Referenced by game_engine.visuals.LayeredAnimationPlayer.LayeredAnimationPlayer().
List<ImageView> game_engine.visuals.LayeredAnimationPlayer.getNode ()
Definition at line 48 of file LayeredAnimationPlayer.java.
References game_engine.visuals.LayeredAnimationPlayer.myDisplay.
Rectangle2D game_engine.visuals.LayeredAnimationPlayer.getViewport (int frameNumber) private
Definition at line 68 of file LayeredAnimationPlayer.java.
References game_engine.visuals.Dimension.getHeight(), game_engine.visuals.Dimension.getWidth(), and game_engine.visuals.LayeredAnimationPlayer.myNumCols.
Referenced by game_engine.visuals.LayeredAnimationPlayer.update().
void game_engine.visuals.LayeredAnimationPlayer.setAnimations (List< AnimationSequence > animations)
Definition at line 38 of file LayeredAnimationPlayer.java.
void game_engine.visuals.LayeredAnimationPlayer.setNextAnimations (@NotNull List< AnimationSequence > animations)
Definition at line 42 of file LayeredAnimationPlayer.java.
boolean game_engine.visuals.LayeredAnimationPlayer.update ()
Definition at line 52 of file LayeredAnimationPlayer.java.
References game_engine.visuals.LayeredAnimationPlayer.getViewport().
Member Data Documentation
List<AnimationSequence> game_engine.visuals.LayeredAnimationPlayer.myCurrentAnimations private
Definition at line 12 of file LayeredAnimationPlayer.java.
List<ImageView> game_engine.visuals.LayeredAnimationPlayer.myDisplay private
Definition at line 15 of file LayeredAnimationPlayer.java.
Referenced by game_engine.visuals.LayeredAnimationPlayer.getNode().
List<Rectangle2D> game_engine.visuals.LayeredAnimationPlayer.myImageBounds private
Definition at line 16 of file LayeredAnimationPlayer.java.
int game_engine.visuals.LayeredAnimationPlayer.myNumCols private
Definition at line 14 of file LayeredAnimationPlayer.java.
Referenced by game_engine.visuals.LayeredAnimationPlayer.getViewport().
Dimension game_engine.visuals.LayeredAnimationPlayer.myTileSize private
Definition at line 13 of file LayeredAnimationPlayer.java.
Referenced by game_engine.visuals.LayeredAnimationPlayer.getDimension().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_engine/visuals/LayeredAnimationPlayer.java