voogasalad_TheException: engine.gameRepresentation.renderedRepresentation.Level Class Reference
engine.gameRepresentation.renderedRepresentation.Level Class Reference
Public Member Functions
Level (LevelState levelState, List< DrawableGameElement > terrain, List< SelectableGameElement > units, List< GameElement > goals, Group terrainAndBuildingsGroup, Group unitsGroup, MapGrid grid)
LevelState getLevelState ()
double getMapWidth ()
double getMapHeight ()
String getName ()
String getDescription ()
MapGrid getGrid ()
List< DrawableGameElement > getTerrain ()
List< SelectableGameElement > getUnits ()
List< GameElement > getGoals ()
Number getNumericalAttribute (String attributeTag)
void setNumericalAttribute (String attributeTag, Number attributeValue)
String getTextualAttribute (String attributeTag)
void setTextualAttribute (String attributeTag, String attributeValue)
List< Group > getGroups ()
void removeElement (DrawableGameElement element)
void addElement (GameElement newElement)
void addElement (DrawableGameElement newElement)
void addElement (SelectableGameElement newElement)
int evaluateGoals ()
Private Attributes
LevelState myState
Group myTerrainAndBuildingsGroup
Group myUnitsGroup
MapGrid myGrid
List< DrawableGameElement > myTerrain
List< SelectableGameElement > myUnits
List< GameElement > myGoals
Detailed Description
The representation of a basic level in the game. Contains a state of the level, a display group, lists of terrains and units, and a list of goals for the level. Essentially acts as a displayable wrapper around the serializable levelState object.
Author
Jonathan, Nishad, Rahul
Definition at line 20 of file Level.java.
Constructor & Destructor Documentation
engine.gameRepresentation.renderedRepresentation.Level.Level (LevelState levelState, List< DrawableGameElement > terrain, List< SelectableGameElement > units, List< GameElement > goals, Group terrainAndBuildingsGroup, Group unitsGroup, MapGrid grid)
Take in a level state and create the visual representation of the level from it.
Parameters
levelState
Definition at line 35 of file Level.java.
Member Function Documentation
void engine.gameRepresentation.renderedRepresentation.Level.addElement (GameElement newElement)
Definition at line 147 of file Level.java.
References model.state.LevelState.addGoal(), and engine.gameRepresentation.renderedRepresentation.GameElement.registerAsChild().
Referenced by engine.stateManaging.GameElementManager.addDrawableGameElementToLevel(), engine.stateManaging.GameElementManager.addGameElementToLevel(), and engine.stateManaging.GameElementManager.addSelectableGameElementToLevel().
void engine.gameRepresentation.renderedRepresentation.Level.addElement (DrawableGameElement newElement)
Definition at line 152 of file Level.java.
References model.state.LevelState.addTerrain(), model.state.gameelement.StateTags.BLOCKING, engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getBounds(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode(), engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.registerAsDrawableChild(), and engine.computers.pathingComputers.MapGrid.registerObstaclePlacement().
void engine.gameRepresentation.renderedRepresentation.Level.addElement (SelectableGameElement newElement)
Definition at line 161 of file Level.java.
References model.state.LevelState.addUnit(), model.state.gameelement.StateTags.BLOCKING, engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getBounds(), engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode(), engine.gameRepresentation.renderedRepresentation.GameElement.getNumericalAttribute(), model.state.gameelement.StateTags.MOVEMENT_SPEED, engine.gameRepresentation.renderedRepresentation.SelectableGameElement.registerAsSelectableChild(), and engine.computers.pathingComputers.MapGrid.registerObstaclePlacement().
int engine.gameRepresentation.renderedRepresentation.Level.evaluateGoals ()
Evaluates all the goals of the level and determines whether the level needs to end
Returns
positive if player has won, negative if player has lost, 0 else. If both win and lose are set, will return negative (losing overrides winning)
Definition at line 181 of file Level.java.
References engine.gameRepresentation.renderedRepresentation.Level.getGoals().
Referenced by engine.stateManaging.GameLoop.updateRunner().
String engine.gameRepresentation.renderedRepresentation.Level.getDescription ()
Definition at line 67 of file Level.java.
References model.state.DescribableState.getDescription().
List<GameElement> engine.gameRepresentation.renderedRepresentation.Level.getGoals ()
Definition at line 83 of file Level.java.
References engine.gameRepresentation.renderedRepresentation.Level.myGoals.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.evaluateGoals().
MapGrid engine.gameRepresentation.renderedRepresentation.Level.getGrid ()
Definition at line 71 of file Level.java.
References engine.gameRepresentation.renderedRepresentation.Level.myGrid.
Referenced by engine.stateManaging.GameElementManager.setLevel().
List<Group> engine.gameRepresentation.renderedRepresentation.Level.getGroups ()
Definition at line 127 of file Level.java.
Referenced by engine.Engine.instantiateManagers().
LevelState engine.gameRepresentation.renderedRepresentation.Level.getLevelState ()
Definition at line 51 of file Level.java.
References engine.gameRepresentation.renderedRepresentation.Level.myState.
double engine.gameRepresentation.renderedRepresentation.Level.getMapHeight ()
Definition at line 59 of file Level.java.
References model.state.LevelState.attributes, model.state.gameelement.AttributeContainer.getNumericalAttribute(), and model.state.gameelement.StateTags.LEVEL_HEIGHT.
Referenced by engine.Engine.instantiateManagers().
double engine.gameRepresentation.renderedRepresentation.Level.getMapWidth ()
Definition at line 55 of file Level.java.
References model.state.LevelState.attributes, model.state.gameelement.AttributeContainer.getNumericalAttribute(), and model.state.gameelement.StateTags.LEVEL_WIDTH.
Referenced by engine.Engine.instantiateManagers().
String engine.gameRepresentation.renderedRepresentation.Level.getName ()
Definition at line 63 of file Level.java.
References model.state.DescribableState.getName().
Number engine.gameRepresentation.renderedRepresentation.Level.getNumericalAttribute (String attributeTag)
Get a numeric attribute contained by the game element
Parameters
attributTag the tag of the attribute of interest
Returns
the attribute's value or 0 if the attribute was not declared
Definition at line 93 of file Level.java.
References model.state.LevelState.attributes, and model.state.gameelement.AttributeContainer.getNumericalAttribute().
List<DrawableGameElement> engine.gameRepresentation.renderedRepresentation.Level.getTerrain ()
Definition at line 75 of file Level.java.
References engine.gameRepresentation.renderedRepresentation.Level.myTerrain.
Referenced by engine.stateManaging.GameElementManager.selectAnySingleUnit(), and engine.stateManaging.GameLoop.updateEditor().
String engine.gameRepresentation.renderedRepresentation.Level.getTextualAttribute (String attributeTag)
Get a textual attribute contained by the game element
Parameters
attributeTag the tag of the attribute
Returns
the value of the attribute or "" if it does not exist
Definition at line 113 of file Level.java.
References model.state.LevelState.attributes, and model.state.gameelement.AttributeContainer.getTextualAttribute().
List<SelectableGameElement> engine.gameRepresentation.renderedRepresentation.Level.getUnits ()
Definition at line 79 of file Level.java.
References engine.gameRepresentation.renderedRepresentation.Level.myUnits.
Referenced by engine.stateManaging.GameElementManager.clearSelectedElementsOfTarget(), engine.stateManaging.GameElementManager.deselectAllElements(), engine.stateManaging.GameElementManager.findAllElementsOfType(), engine.stateManaging.GameElementManager.notifyButtonClicked(), engine.stateManaging.GameElementManager.notifySelectedElementsOfTarget(), engine.stateManaging.GameElementManager.selectAnySingleUnit(), engine.stateManaging.GameElementManager.selectSingleUnit(), engine.stateManaging.GameElementManager.selectUnitsInBounds(), engine.stateManaging.GameElementManager.setSelectedUnitCommand(), engine.stateManaging.GameLoop.updateEditor(), and engine.stateManaging.GameLoop.updateRunner().
void engine.gameRepresentation.renderedRepresentation.Level.removeElement (DrawableGameElement element)
Remove an element from the level
Parameters
element the element to be removed
Definition at line 139 of file Level.java.
References engine.gameRepresentation.renderedRepresentation.DrawableGameElement.getNode(), engine.gameRepresentation.renderedRepresentation.GameElement.getState(), and model.state.LevelState.removeElement().
Referenced by engine.stateManaging.GameElementManager.deleteSelectedUnit(), and engine.stateManaging.GameLoop.updateRunner().
void engine.gameRepresentation.renderedRepresentation.Level.setNumericalAttribute (String attributeTag, Number attributeValue)
Set a numeric attribute contained by the game element
Parameters
attributeTag the tag of the attribute
attributeValue the value of the attribute
Definition at line 103 of file Level.java.
References model.state.LevelState.attributes, and model.state.gameelement.AttributeContainer.setNumericalAttribute().
void engine.gameRepresentation.renderedRepresentation.Level.setTextualAttribute (String attributeTag, String attributeValue)
Set the value of a textual attribute contained by the game element
Parameters
attributeTag the tag of the attribute
attributeValue the attribute's value
Definition at line 123 of file Level.java.
References model.state.LevelState.attributes, and model.state.gameelement.AttributeContainer.setTextualAttribute().
Member Data Documentation
List<GameElement> engine.gameRepresentation.renderedRepresentation.Level.myGoals private
Definition at line 28 of file Level.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.getGoals().
MapGrid engine.gameRepresentation.renderedRepresentation.Level.myGrid private
Definition at line 25 of file Level.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.getGrid().
LevelState engine.gameRepresentation.renderedRepresentation.Level.myState private
Definition at line 22 of file Level.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.getLevelState().
List<DrawableGameElement> engine.gameRepresentation.renderedRepresentation.Level.myTerrain private
Definition at line 26 of file Level.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.getTerrain().
Group engine.gameRepresentation.renderedRepresentation.Level.myTerrainAndBuildingsGroup private
Definition at line 23 of file Level.java.
List<SelectableGameElement> engine.gameRepresentation.renderedRepresentation.Level.myUnits private
Definition at line 27 of file Level.java.
Referenced by engine.gameRepresentation.renderedRepresentation.Level.getUnits().
Group engine.gameRepresentation.renderedRepresentation.Level.myUnitsGroup private
Definition at line 24 of file Level.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/engine/gameRepresentation/renderedRepresentation/Level.java