voogasalad_TheException: view.gui.GUIPanePath Enum Reference
view.gui.GUIPanePath Enum Reference
Public Member Functions
String getFilePath ()
Public Attributes
RUNNER_PANE =("/view/runner/GameRunnerPane.fxml")
INFO_BOX =("/view/editor/guipanes/DescribableInfoBox.fxml")
ELEMENT_ACCORDION =("/view/editor/guipanes/EditorElementAccordion.fxml")
EDITOR_MENU_BAR =("/view/editor/guipanes/EditorMenuBar.fxml")
EDITOR_TAB_VIEW =("/view/editor/guipanes/EditorTabView.fxml")
GAME_ELEMENT_DROP_DOWN =("/view/editor/guipanes/GameElementDropDown.fxml")
LEVEL_TRIGGER_VIEW =("/view/editor/guipanes/EditorTriggerView.fxml")
PROJECT_EXPLORER_VIEW =("/view/editor/guipanes/ProjectExplorerView.fxml")
CAMPAIGN_WIZARD =("/view/editor/wizards/guipanes/CampaignWizard.fxml")
LEVEL_WIZARD =("/view/editor/wizards/guipanes/LevelWizard.fxml")
WIDGET_WIZARD =("/view/editor/wizards/guipanes/WidgetWizard.fxml")
PARTICIPANT_WIZARD =("/view/editor/wizards/guipanes/ParticipantWizard.fxml")
NUMBER_ATTRIBUTE_WIZARD =("/view/editor/wizards/guipanes/NumberAttributeWizard.fxml")
GAME_ELEMENT_WIZARD =("/view/editor/wizards/guipanes/GameElementWizard.fxml")
STRING_ATTRIBUTE_WIZARD =("/view/editor/wizards/guipanes/StringAttributeWizard.fxml")
ACTION_WIZARD =("/view/editor/wizards/guipanes/ActionWizard.fxml")
POSITION_WIZARD =("/view/editor/wizards/guipanes/PositionWizard.fxml")
ANIMATION_WIZARD =("/view/editor/wizards/guipanes/AnimationWizard.fxml")
BOUNDS_WIZARD =("/view/editor/wizards/guipanes/BoundsWizard.fxml")
DIALOG_BOX =("/view/dialog/DialogBox.fxml")
Private Member Functions
GUIPanePath (String filePath)
Private Attributes
String myFilePath
Detailed Description
Author
Jonathan Tseng, Nishad
Definition at line 10 of file GUIPanePath.java.
Constructor & Destructor Documentation
view.gui.GUIPanePath.GUIPanePath (String filePath) private
Definition at line 40 of file GUIPanePath.java.
Member Function Documentation
String view.gui.GUIPanePath.getFilePath ()
Definition at line 44 of file GUIPanePath.java.
Referenced by view.editor.wizards.WizardUtility.loadWizard().
Member Data Documentation
view.gui.GUIPanePath.ACTION_WIZARD =("/view/editor/wizards/guipanes/ActionWizard.fxml")
Definition at line 30 of file GUIPanePath.java.
Referenced by view.editor.wizards.GameElementWizard.initContainers(), view.editor.TabViewController.launchNestedWizard(), and view.editor.TabViewController.modifyGoals().
view.gui.GUIPanePath.ANIMATION_WIZARD =("/view/editor/wizards/guipanes/AnimationWizard.fxml")
Definition at line 32 of file GUIPanePath.java.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
view.gui.GUIPanePath.BOUNDS_WIZARD =("/view/editor/wizards/guipanes/BoundsWizard.fxml")
Definition at line 33 of file GUIPanePath.java.
Referenced by view.editor.wizards.GameElementWizard.launchBoundsWizard().
view.gui.GUIPanePath.CAMPAIGN_WIZARD =("/view/editor/wizards/guipanes/CampaignWizard.fxml")
Definition at line 23 of file GUIPanePath.java.
Referenced by view.editor.EditorMenuBarController.onNewCampaignClick().
view.gui.GUIPanePath.DIALOG_BOX =("/view/dialog/DialogBox.fxml")
Definition at line 36 of file GUIPanePath.java.
Referenced by view.dialog.DialogBoxUtility.createDialogBox().
view.gui.GUIPanePath.EDITOR_MENU_BAR =("/view/editor/guipanes/EditorMenuBar.fxml")
Definition at line 16 of file GUIPanePath.java.
view.gui.GUIPanePath.EDITOR_TAB_VIEW =("/view/editor/guipanes/EditorTabView.fxml")
Definition at line 17 of file GUIPanePath.java.
Referenced by view.editor.EditorScreen.createNewTab().
view.gui.GUIPanePath.ELEMENT_ACCORDION =("/view/editor/guipanes/EditorElementAccordion.fxml")
Definition at line 15 of file GUIPanePath.java.
view.gui.GUIPanePath.GAME_ELEMENT_DROP_DOWN =("/view/editor/guipanes/GameElementDropDown.fxml")
Definition at line 18 of file GUIPanePath.java.
view.gui.GUIPanePath.GAME_ELEMENT_WIZARD =("/view/editor/wizards/guipanes/GameElementWizard.fxml")
Definition at line 28 of file GUIPanePath.java.
Referenced by view.editor.ElementAccordionController.openDrawableGameElementWizard(), and view.editor.ElementAccordionController.openSelectableGameElementWizard().
view.gui.GUIPanePath.INFO_BOX =("/view/editor/guipanes/DescribableInfoBox.fxml")
Definition at line 14 of file GUIPanePath.java.
view.gui.GUIPanePath.LEVEL_TRIGGER_VIEW =("/view/editor/guipanes/EditorTriggerView.fxml")
Definition at line 19 of file GUIPanePath.java.
view.gui.GUIPanePath.LEVEL_WIZARD =("/view/editor/wizards/guipanes/LevelWizard.fxml")
Definition at line 24 of file GUIPanePath.java.
Referenced by view.editor.EditorMenuBarController.onNewLevelClick().
String view.gui.GUIPanePath.myFilePath private
Definition at line 38 of file GUIPanePath.java.
view.gui.GUIPanePath.NUMBER_ATTRIBUTE_WIZARD =("/view/editor/wizards/guipanes/NumberAttributeWizard.fxml")
Definition at line 27 of file GUIPanePath.java.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
view.gui.GUIPanePath.PARTICIPANT_WIZARD =("/view/editor/wizards/guipanes/ParticipantWizard.fxml")
Definition at line 26 of file GUIPanePath.java.
view.gui.GUIPanePath.POSITION_WIZARD =("/view/editor/wizards/guipanes/PositionWizard.fxml")
Definition at line 31 of file GUIPanePath.java.
view.gui.GUIPanePath.PROJECT_EXPLORER_VIEW =("/view/editor/guipanes/ProjectExplorerView.fxml")
Definition at line 20 of file GUIPanePath.java.
view.gui.GUIPanePath.RUNNER_PANE =("/view/runner/GameRunnerPane.fxml")
Definition at line 12 of file GUIPanePath.java.
view.gui.GUIPanePath.STRING_ATTRIBUTE_WIZARD =("/view/editor/wizards/guipanes/StringAttributeWizard.fxml")
Definition at line 29 of file GUIPanePath.java.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
view.gui.GUIPanePath.WIDGET_WIZARD =("/view/editor/wizards/guipanes/WidgetWizard.fxml")
Definition at line 25 of file GUIPanePath.java.
Referenced by view.editor.wizards.GameElementWizard.initContainers().
The documentation for this enum was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/gui/GUIPanePath.java