voogasalad_TheException: game_requests.forwarding.AddressConflictException Class Reference
game_requests.forwarding.AddressConflictException Class Reference
Public Member Functions
AddressConflictException (String conflictingAddress, IReceiver conflictingReceiver)
String conflictingAddress ()
IReceiver conflictingReceiver ()
Private Attributes
String myConflictingAddress
IReceiver myConflictingReceiver
Static Private Attributes
static final long serialVersionUID = -3572949740426821224L
Detailed Description
An exception capturing when an address conflicts with a pre-existing address
Definition at line 8 of file AddressConflictException.java.
Constructor & Destructor Documentation
game_requests.forwarding.AddressConflictException.AddressConflictException (String conflictingAddress, IReceiver conflictingReceiver)
Create a new address conflict exception
Parameters
conflictingAddress The address that conflicts with a pre-existing address
conflictingReceiver The receiver that already possesses that address
Definition at line 22 of file AddressConflictException.java.
References game_requests.forwarding.AddressConflictException.conflictingAddress(), and game_requests.forwarding.AddressConflictException.conflictingReceiver().
Member Function Documentation
String game_requests.forwarding.AddressConflictException.conflictingAddress ()
The conflicting address
Returns
The address that conflicts with a pre-existing address
Definition at line 33 of file AddressConflictException.java.
References game_requests.forwarding.AddressConflictException.myConflictingAddress.
Referenced by game_requests.forwarding.AddressConflictException.AddressConflictException().
IReceiver game_requests.forwarding.AddressConflictException.conflictingReceiver ()
The conflicting receiver
Returns
The receiver that already possesses that address
Definition at line 42 of file AddressConflictException.java.
References game_requests.forwarding.AddressConflictException.myConflictingReceiver.
Referenced by game_requests.forwarding.AddressConflictException.AddressConflictException().
Member Data Documentation
String game_requests.forwarding.AddressConflictException.myConflictingAddress private
Definition at line 11 of file AddressConflictException.java.
Referenced by game_requests.forwarding.AddressConflictException.conflictingAddress().
IReceiver game_requests.forwarding.AddressConflictException.myConflictingReceiver private
Definition at line 12 of file AddressConflictException.java.
Referenced by game_requests.forwarding.AddressConflictException.conflictingReceiver().
final long game_requests.forwarding.AddressConflictException.serialVersionUID = -3572949740426821224L static private
Definition at line 10 of file AddressConflictException.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_requests/forwarding/AddressConflictException.java