voogasalad_TheException: editor.wizards.WizardData Class Reference
editor.wizards.WizardData Class Reference
Public Member Functions
WizardData ()
void setName (String name)
void addDataPair (String key, String value)
void addWizardData (WizardData wizData)
Map< String, String > getData ()
List< WizardData > getWizards ()
String getName ()
String getValueByKey (String key)
List< WizardData > getWizardDataByType (String type)
String toString ()
Private Attributes
String myName
Map< String, String > myData
List< WizardData > myWizards
Detailed Description
Author
Nishad Agrawal
Definition at line 16 of file WizardData.java.
Constructor & Destructor Documentation
editor.wizards.WizardData.WizardData ()
Definition at line 21 of file WizardData.java.
Member Function Documentation
void editor.wizards.WizardData.addDataPair (String key, String value)
Definition at line 31 of file WizardData.java.
Referenced by editor.wizards.Wizard.addToData().
void editor.wizards.WizardData.addWizardData (WizardData wizData)
Definition at line 35 of file WizardData.java.
Referenced by editor.wizards.Wizard.addWizardData().
Map<String, String> editor.wizards.WizardData.getData ()
Definition at line 39 of file WizardData.java.
References editor.wizards.WizardData.myData.
String editor.wizards.WizardData.getName ()
Definition at line 47 of file WizardData.java.
References editor.wizards.WizardData.myName.
String editor.wizards.WizardData.getValueByKey (String key)
Definition at line 51 of file WizardData.java.
Referenced by gamemodel.GameElementStateFactory.addEssentials(), gamemodel.MainModel.createDrawableGameElement(), and gamemodel.GameElementStateFactory.createDrawableGameElementState().
List<WizardData> editor.wizards.WizardData.getWizardDataByType (String type)
Definition at line 55 of file WizardData.java.
Referenced by gamemodel.GameElementStateFactory.addEssentials(), and gamemodel.GameElementStateFactory.createGoal().
List<WizardData> editor.wizards.WizardData.getWizards ()
Definition at line 43 of file WizardData.java.
References editor.wizards.WizardData.myWizards.
void editor.wizards.WizardData.setName (String name)
Definition at line 27 of file WizardData.java.
Referenced by editor.wizards.Wizard.setDataName().
String editor.wizards.WizardData.toString ()
Definition at line 61 of file WizardData.java.
Member Data Documentation
Map<String, String> editor.wizards.WizardData.myData private
Definition at line 18 of file WizardData.java.
Referenced by editor.wizards.WizardData.getData().
String editor.wizards.WizardData.myName private
Definition at line 17 of file WizardData.java.
Referenced by editor.wizards.WizardData.getName().
List<WizardData> editor.wizards.WizardData.myWizards private
Definition at line 19 of file WizardData.java.
Referenced by editor.wizards.WizardData.getWizards().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/editor/wizards/WizardData.java