voogasalad_TheException: view.editor.wizards.WizardUtility Class Reference
view.editor.wizards.WizardUtility Class Reference
Static Public Member Functions
static Wizard loadWizard (GUIPanePath path, Dimension d)
Detailed Description
Definition at line 12 of file WizardUtility.java.
Member Function Documentation
static Wizard view.editor.wizards.WizardUtility.loadWizard (GUIPanePath path, Dimension d) static
Definition at line 14 of file WizardUtility.java.
References view.GUILoadStyleUtility.addScene(), view.GUILoadStyleUtility.generateGUIPane(), view.gui.GUIPanePath.getFilePath(), view.GUILoadStyleUtility.getInstance(), view.editor.wizards.Wizard.getRoot(), and view.editor.wizards.Wizard.setStage().
Referenced by view.editor.wizards.GameElementWizard.launchBoundsWizard(), view.editor.wizards.CRUDContainer.launchEditWizard(), view.editor.TabViewController.launchNestedWizard(), view.editor.wizards.CRUDContainer.launchNestedWizard(), view.editor.TabViewController.modifyGoals(), view.editor.EditorMenuBarController.onNewCampaignClick(), and view.editor.EditorMenuBarController.onNewLevelClick().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_TheException/repository/src/view/editor/wizards/WizardUtility.java