voogasalad_TheException: game_requests.Request Class Reference
game_requests.Request Class Reference
Public Member Functions
Request (String sender, String receiver, Map< String, String > message)
String sender ()
String receiver ()
Map< String, String > message ()
Private Attributes
String mySender
String myReceiver
Map< String, String > myMessage
Detailed Description
Definition at line 6 of file Request.java.
Constructor & Destructor Documentation
game_requests.Request.Request (String sender, String receiver, Map< String, String > message)
Definition at line 12 of file Request.java.
References game_requests.Request.message(), game_requests.Request.receiver(), and game_requests.Request.sender().
Member Function Documentation
Map<String, String> game_requests.Request.message ()
Get the message
Returns
A map of attributes to values representing the message
Implements game_requests.IRequest.
Definition at line 29 of file Request.java.
References game_requests.Request.myMessage.
Referenced by game_requests.Request.Request().
String game_requests.Request.receiver ()
Get the recipient
Returns
The address of the recipient
Implements game_requests.IRequest.
Definition at line 24 of file Request.java.
References game_requests.Request.myReceiver.
Referenced by game_requests.Request.Request().
String game_requests.Request.sender ()
Get the sender
Returns
The address of the sender
Implements game_requests.IRequest.
Definition at line 19 of file Request.java.
References game_requests.Request.mySender.
Referenced by game_requests.Request.Request().
Member Data Documentation
Map<String, String> game_requests.Request.myMessage private
Definition at line 10 of file Request.java.
Referenced by game_requests.Request.message().
String game_requests.Request.myReceiver private
Definition at line 9 of file Request.java.
Referenced by game_requests.Request.receiver().
String game_requests.Request.mySender private
Definition at line 8 of file Request.java.
Referenced by game_requests.Request.sender().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/voogasalad_TheException/repository/src/game_requests/Request.java